### ISSUE TITLE
Build under win7 64bit os, and running under winxp 32bit os, met a error.

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#101]
Originally reported by: **zaazbb (Bitbucket: [zaazbb](https://bitbucket.org/zaazbb), GitHub: [zaazbb](https://github.com/zaazbb))**

----------------------------------------

Build environment:
os: windows 7 64bit.
python:python-3.4.1.amd64.msi
cx_freeze: cx_Freeze-4.3.3.win-amd64-py3.4.exe (from http://www.lfd.uci.edu/~gohlke/pythonlibs/)

running environment:
os: windows xp 32bit.

met a error "xxx is not a valid win32 application."

How can I build win32 version application use cz_freeze.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/101

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Build with 32bit python and 32bit cx_freeze


I build using win7 64bit, 32bit and 64bit builds.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

To build a 32-bit application, you need to build it with a 32-bit version of Python and cx_Freeze, along with 32 bit versions of any extension modules you need (like PyQt). These will be the ones *without* amd64 in the filename.

You can use 32-bit applications on a 64-bit system, but *not* 64 bit applications on a 32 bit system.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

If you are using anaconda, you can have side-by-side installations of 32-bit and 64-bit versions of Miniconda.  I have my default 64-bit version in c:\\Miniconda and my 32-bit chain in c:\\Miniconda32bit

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

You can install 32 and 64 bit python side by side as well.

I have my 64bit python in C:\Python34-64
32bit is in C:\Python34

**Comment by marcelotduarte** [comment]
This is too old and on W10, Py37, I see no errors. Can I close this issue?
