### ISSUE TITLE
Circular dependency while executing cx_Freeze result

### ISSUE THREAD

**Issue by steven-chau** [marcelotduarte/cx_Freeze#1013]
Hi,

I have run into a run-time problem that is very similar to the following Stackoverflow issue.

https://stackoverflow.com/questions/66821044/circular-dependency-while-executing-cx-freeze-result

Could someone shed some light on this? Thanks very much!

**Comment by marcelotduarte** [comment]
There are a similar question and answer in #991

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
