### ISSUE TITLE
Windows 10 , cx_Freeze PyQt5.QtWebengineWidgets

### ISSUE THREAD

**Issue by Hellfireone** [marcelotduarte/cx_Freeze#1014]
Hello I have Problems use cx_Freeze with my GUI App build with PyQt5 and PyQt5 WebEngineWidgets , after building my App , and setting up my setup.py 

i use python setup.py bdist_msi , no Error but after pressing on .exe

cx_Freeze: Python error in main script
Traceback (most recent call last):
........
ImportError: DLL load failed while importing QtWebEngineWidgets: das angegebene Modul wurde nicht gefunden.

i need help pls :)

**Comment by marcelotduarte** [comment]
Can you test with the most recent version?
`pip uninstall -y cx_Freeze`
`pip install --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --pre`

[sample](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyqt5-simplebrowser)

to run the sample use test_simplebrowser --no-sandbox
[reference](https://doc.qt.io/qt-5/qtwebengine-debugging.html#using-command-line-arguments)
