### ISSUE TITLE
Realoding msilib breaks passing `msilib.Binary` objects into `bdist_msi`’s `data` parameter

### ISSUE THREAD

**Issue by Cimbali** [marcelotduarte/cx_Freeze#1019]
### Bug description

On windows, the `data` option passed to `bdist_msi` is used to pass in arbitrary data to put in the installer’s tables. To add stream data, the correct way is to wrap its path in a `msilib.Binary`, as is done with the install icon:

https://github.com/marcelotduarte/cx_Freeze/blob/f5be487e5db58d2a482b272313e6809a06b7e3d0/cx_Freeze/windist.py#L555-L559

However, msilib recognizes these objects with `isinstance()`:

https://github.com/python/cpython/blob/eb77133564d74eb09ed63872a69b9827d4841b49/Lib/msilib/__init__.py#L113-L116

Thus after reloading msilib, `msilib.Binary` objects that were created before the reload are not recognized

https://github.com/marcelotduarte/cx_Freeze/blob/f5be487e5db58d2a482b272313e6809a06b7e3d0/cx_Freeze/windist.py#L819

### Reproduce 

Add any `msilib.Binary` data in the `setup()`’s options, e.g.:

```python
setup(data={
   'Icon': [('SecondIcon', msilib.Binary('path\to\icon')]
})
```
This causes a `TypeError: Unsupported type Binary` to be thrown inside add_config’s add_data.

https://github.com/marcelotduarte/cx_Freeze/blob/f5be487e5db58d2a482b272313e6809a06b7e3d0/cx_Freeze/windist.py#L128-L129

The path doesn’t even have to exist for the error to be thrown.

### Expected behavior

The data is added to the `msi` installer.

### Platform Information

- Windows-10-10.0.17763-SP0
- 64 bits
- Python 3.8.9 in msys2 / mingw64
- cx_Freeze 6.5.3

-----

I’m more than happy to provide a PR for this but there’s a number of ways this could be fixed and I’m not sure which is preferable:
- wrap paths in some `cx_Freeze` object and only make them into `msiilb.Binary` when calling `add_data()`
- (just) before calling `add_data()`, iterate over arguments to identify old `msilib.Binary` objects and re-create them as
  ```python3
  msilib.Binary(old_bin.name)
  ```
- something else I didn’t think of?

**Comment by marcelotduarte** [comment]
My preference is the first option.  Do you think to create an option like binary-data?
@cainesi I see that you have knowledge in this area. Can you suggest?

**Comment by cainesi** [comment]
It looks like the Binary object is only used for one table (the "Binary" table). So I think we should either:

1) detect that table when processing the data parameter, and convert the relevant table column to Binary. We would say in the documentation that for that table the user should provide a string with a path to the file (rather than a Binary object). We could also provide a warning message if a non-string is provided. [i prefer this one — easier for the user). 

2) provide a separate bdist_msi parameter for including information in the Binary table. 

FYI, the reason for the msilib reload is because the msilib stores some data about the msi creation in a global variable in the module. The effect of that is that there are problems if you try to create a second msi without reloading the library. (I came across this when I had a script that auto-generated several msi files.)

**Comment by Cimbali** [comment]
As far as I can tell there are at least 6 tables using Binary, maybe more but that are not used in the `.msi` file I checked:

- [Binary](https://docs.microsoft.com/en-us/windows/win32/msi/binary-table)
- [Icon](https://docs.microsoft.com/en-us/windows/win32/msi/icon-table) (this one is used in `cx_Freeze`)
- [SFPCatalog](https://docs.microsoft.com/en-us/windows/win32/msi/sfpcatalog-table)
- [MsiDigitalCertificate](https://docs.microsoft.com/en-us/windows/win32/msi/msidigitalcertificate-table)
- [MsiPatchHeaders](https://docs.microsoft.com/en-us/windows/win32/msi/msipatchheaders-table)
- [Patch](https://docs.microsoft.com/en-us/windows/win32/msi/patch-table)

We can keep track of which fields expect binary values, and expect the path to a file as a `str` argument. Only files are supported by the `msilib` backend anyway.

**Comment by marcelotduarte** [comment]
I'll be happy to see your PR.

**Comment by cainesi** [comment]
@Cimbali It looks like you are right.  I was going by what was in the msilib documentation, which suggested that the Binary object was only for use with the Binary table. So I guess we would need to go through the MSI documentation and find all the tables that have a Binary column. 

As a completely alternative approach, I think it probably works to change the windist.py line you identified
```importlib.reload(msilib)```
to instead say
```msilib._directories = set()```
I have not tested that yet, though, and I worry it may be more brittle going forward.  If we do that, then I think we would also want to add before that line
```
assert(hasattr(msilib, "_directories"))
assert(isinstance(msilib._directories, set))
```
That way it will be clear what is going on if the internal structure of msilib subsequently changes.

**Comment by Cimbali** [comment]
@cainesi The way it’s implemented right now in #1024 does not guarantee to be exhaustive, but it’s easy to extend in the future both for maintainers of cx_Freeze (adding new lines to the dict), and by users with a custom `cmd_class` inheriting from cx_Freeze’s `bdist_msi`, e.g.:


```python3
class extended_bdist_msi(cx_Freeze.wininst.bdist_msi):
     _binary_columns = {**cx_Freeze.wininst.bdist_msi._binary_columns, 'AnotherTable': 5}

cx_Freeze.setup(cmdclass={'bdist_msi': extended_bdist_msi}, […more options])
```

It might be easier / more readable / more future-proof to shift this responsibility on the end user though, by making a cx_Freeze equivalent to `msilib.Binary` and translating from the one to the other after reloading msilib (i.e. when calling `msilib.add_data`).

The way reloading msilib works right now seems well documented in the code and understandable. (The whole API seems to be weirdly scoped at the module level rather than requiring a top-level object per installer anyways.) I’m not sure changing it to be dependent on its internals is the best way.

**Comment by cainesi** [comment]
Is there a reason you don't like your other original suggestion —of detecting and fixing Binary objects that are passed in?

**Comment by Cimbali** [comment]
No that’s fine too, didn’t seem to be @marcelotduarte’s favorite is all. I can update the PR with whichever way seems most appropriate.

**Comment by cainesi** [comment]
I guess whichever way we go, we should mention the appropriate wrapper object in the documentation.

**Comment by Cimbali** [comment]
I guess another option is to accept `bytes` objects. It’s probably the most natural, but `msilib` only accepts paths to files, so it means writing the bytes to a temporary file and using that file name.

**Comment by marcelotduarte** [comment]
I liked your implementation. Saturday I'll test and merge if it is ok.
@cainesi 
> we should mention the appropriate wrapper object in the documentation.

the documentation is ok?

**Comment by cainesi** [comment]
Yes, the documentation looks okay to me.  I would slightly prefer to add a list of the 6 tables where we are making the adjustment (so people encountering problems with those tables would be pointed in the right direction by the docs).

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7b1 has just been released.
pip install cx-Freeze==6.7b1
