### ISSUE TITLE
Not able to create python executables independantly

### ISSUE THREAD

**Issue by Sriram21** [marcelotduarte/cx_Freeze#1028]
Hi,

I have multiple packages in my project wherein each package will be treated as a separate module/entity.

But when i compile using cxfreeze setup.py i am not able to segregate the executable based on packages.

If i compile it two times for two different modules all the source code gets included in both of the modules..

I need to build my python executables based on the packages..

Any help is much appreciated,

Regards,
Sriram

**Comment by marcelotduarte** [comment]
I use a setup to build 9 executables in a project and its works!
Maybe what you want is a bit different, using the -b option (build_exe=directory) you can specify the directory for each of the executables.
Check the docs:
https://cx-freeze.readthedocs.io/en/latest/distutils.html#build-exe
https://cx-freeze.readthedocs.io/en/latest/distutils.html#cx-freeze-executable

If you can, post the setup.py here.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
Closing due to lack of information.
If you had issues please open a new issue.
