### ISSUE TITLE
qtconsole and cx_freeze

### ISSUE THREAD

**Issue by neurochen** [marcelotduarte/cx_Freeze#1036]
**Describe the bug**
Hi, thanks for the wonderful cx_Freeze! We are embedding a python console in our pyqt app, using qtconsole. However, when we ran the exe from cx_freeze, it constantly reopened more and more qtconsole window. And the old console always displayed "Kernel died, restarting." Could you please take a look at it?

**To Reproduce**
Install qtconsole first and then cx_freeze the script below.
```python
if __name__ == '__main__':
    import multiprocessing
    multiprocessing.freeze_support()
    from qtconsole.qtconsoleapp import main
    main()
```

**Screenshots**
![image](https://user-images.githubusercontent.com/10821596/116019940-4fe61400-a613-11eb-85d7-5a69ee15e21a.png)

**Desktop (please complete the following information):**
 - windows 10 x64
 - python 3.8.5
 - cx_Freeze  6.6
 - qtconsole 5.0.3:

**Comment by marcelotduarte** [comment]
I think you should create executables to simulate what happens in qtconsole. qtconsole start ipykernel, so you should have to start it like in https://github.com/ipython/ipykernel/blob/master/ipykernel/__main__.py
It uses zmq to comunicate....
In a normal python app, one script can start another process calling python. In a cx-freeze app doesn't exist python, so you should start the app by your own.

**Comment by neurochen** [comment]
It seems that this is actually what qtconsole does inside the main function above:
JupyterQtConsoleApp.launch_instance()

**Comment by marcelotduarte** [comment]
It launches an instance of the kernel, using subprocess.Popen or another function.
So, you should create 2 executables, one for the kernel and another for the console with communication via zmq.
Maybe you should follow the examples and adapt them to executables in cx-freeze:
https://github.com/jupyter/qtconsole/tree/master/examples

**Comment by bakulev** [comment]
@neurochen could you contact with me? write please abakulev@thorlabs.com
Sorry that I am writing here. I do not know how to contact with you by other way.

**Comment by marcelotduarte** [comment]
I take this opportunity to inform:
[cx_Freeze 6.11](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.11.0) has just been released.
pip install --upgrade cx_Freeze
