### ISSUE TITLE
bdist_msi argument "add_to_path" should possibly be "add-to-path"

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#104]
Originally reported by: **Anonymous**

----------------------------------------

Hello,

The command line argument for adding to the path with bdist_msi is labeled as "add_to_path" in the documentation. On my machine when running 'python setup.py bdist_msi --add_to_path True' the program fails (in cmd.exe). Running with '--add-to-path' appears to work (it is correctly listed in the '--help' option, but not in the man page).

Fantastic package, btw. Keep up the good work!

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/104

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

The docs do say "To specify the same options on the command line, use dashes..."

There are two formats for each distutils option: a script format `add_to_path` and a command line format `--add-to-path`. We could show every option in both ways, but that would take up more space.

**Comment by marcelotduarte** [comment]
PR #1097
