### ISSUE TITLE
cx_Freeze cannot support quiet msi installer ?

### ISSUE THREAD

**Issue by VictorMartin-fr** [marcelotduarte/cx_Freeze#1044]
Hello,

Is it possible to create a MSI installer who support quiet install (with msiexec) ?

I manage to create a MSI installer, but because of the "destination file" section in the setup, I can't run the installation in quiet mode (the installation start succesfully in background task, but can't be complete).

Thanks !

**Comment by marcelotduarte** [comment]
Hi! 
How is your setup?

https://cx-freeze.readthedocs.io/en/latest/setup_script.html?highlight=msi#bdist-msi
https://stackoverflow.com/questions/8560166/silent-installation-of-a-msi-package/8560308
http://msdn.microsoft.com/en-us/library/aa370557(v=vs.85).aspx

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.11](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.11.0) has just been released.
pip install --upgrade cx_Freeze

Re-open if you can supply the setup.py and code that is failing.
