### ISSUE TITLE
Cannot pack h5py

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#105]
Originally reported by: **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**

----------------------------------------

With git version of cx_Freeze, I cannot pack h5py as a package.  If I don't include it as a package, it finds the PYD files ok, but it doesn't include the PY files.

To prove I really have it:

```
Python 2.7.6 |Continuum Analytics, Inc.| (default, May 27 2014, 15:00:33) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io and https://binstar.org
>>> import h5py
>>> h5py.__file__
'C:\\Miniconda\\lib\\site-packages\\h5py\\__init__.pyc'
```

Output:
```
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    pack()
  File "setup.py", line 44, in pack
    executables = [GUI2Exe_Target_1]
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\dist.py", line 347, in setup
    distutils.core.setup(**attrs)
  File "C:\Miniconda\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "C:\Miniconda\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Miniconda\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Miniconda\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Miniconda\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Miniconda\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\dist.py", line 217, in run
    freezer.Freeze()
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\freezer.py", line 567, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\freezer.py", line 344, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\finder.py", line 644, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "C:\Miniconda\lib\site-packages\cx_freeze-5.0-py2.7-win-amd64.egg\cx_Freeze\finder.py", line 345, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'h5py'
```
Script:

```
#!python

def pack():
    
    from cx_Freeze import setup, Executable
    import sys, shutil, glob, os

    if len(sys.argv) == 1:
        sys.argv += ['build', '--build-exe=h5pack']

    base = None
    if sys.platform == "win32":
        base = "Win32GUI"

    GUI2Exe_Target_1 = Executable(
        # what to build
        script = "nothing.py",
        initScript = None,
        base = base,
        targetName = "nothing.exe",
        icon = None
        )

    setup(
        version = "1.0",
        description = "No Description",
        author = "No Author",
        name = "cx_Freeze Sample File",
        
        options = {"build_exe": {"include_files": [],
                                 "includes": [],
                                 "excludes": [],
                                 "packages": ['h5py'],
                                 "path": []
                                 }
                   },
                               
        executables = [GUI2Exe_Target_1]
        )

if __name__=='__main__':
    pack()




```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/105

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

The issue is that h5py.api_gen no longer exists in h5py, and the hook should be modified.  Can we fail in a more elegant way and/or optionally add the hooks?  I was going to add a PR to just remove the h5py.api_gen, but then it would break older versions

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Add a version check? or perhaps use a try and except so in older versions it will fall back.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

The conditional should really go in the hook - perhaps a try..except ImportError block to check if it is needed?  Or is that a bad idea?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

The more pressing issue is that the error message on the hook import is actually wrong.  It finds h5py fine, but it dies on h5py.api_gen

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

I would think a try and except for that one would solve the issue.

Catch the error, and then fix it, no error and it would work as normal.


I don't know much about the hooks though, but you can see what you can come up with

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

I took a look at hooks.py


It's pretty simple


```
#!python

def load_h5py(finder, module):
    """h5py module has a number of implicit imports"""
    finder.IncludeModule('h5py.defs')
    finder.IncludeModule('h5py.utils')
    finder.IncludeModule('h5py._proxy')
    finder.IncludeModule('h5py.api_gen')
```

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

Yeah my idea was

``` python

def load_h5py(finder, module):
    """h5py module has a number of implicit imports"""
    finder.IncludeModule('h5py.defs')
    finder.IncludeModule('h5py.utils')
    finder.IncludeModule('h5py._proxy')
    try:
        import h5py.api_gen
        finder.IncludeModule('h5py.api_gen')
    except ImportError:
        pass
```
Any negative side-effects with this change? I can do a PR if not

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

I don't see why it would cause any.

Though maybe importing it isnt the best thing? Why not just catch it at "finder.IncludeModule('h5py.api_gen')" ?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

But to do so requires up to know when api_gen was removed from h5py, which I don't.  And don't have an easy way to find out.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

It looks like it should work fine. You should try it on your own version of cx_freeze to make sure it doesnt cause anything unexpected to happen

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

On mine I just commented out the line :)  I was just wondering whether the fact that the module was loaded (for older versions) would then cause issues for cx_Freeze.

I'll put a PR together with this change, and then we can discuss there.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ian Bell (Bitbucket: [ibell](https://bitbucket.org/ibell), GitHub: [ibell](https://github.com/ibell))**:

----------------------------------------

PR added: https://bitbucket.org/anthony_tuininga/cx_freeze/pull-request/64/only-add-h5pyapi_gen-if-it-can-be-imported/diff

**Comment by anthony-tuininga** [comment]
*Original comment by* **Roland Thiolliere (Bitbucket: [rthiolliere](https://bitbucket.org/rthiolliere), GitHub: Unknown)**:

----------------------------------------

for h5py 2.3.1, I also had to add     finder.IncludeModule('h5py.h5ac')

**Comment by anthony-tuininga** [comment]
*Original comment by* **John David Reaver (Bitbucket: [jdreaver](https://bitbucket.org/jdreaver), GitHub: [jdreaver](https://github.com/jdreaver))**:

----------------------------------------

I'm having this exact same issue with version 2.5.0 of h5py. Does anyone know enough about cx_Freeze or h5py to suggest a solution? I'm not sure what changed from then to now.

EDIT: I figured out my problem. The PR from Ian did not make it into cx_Freeze version 4.3.4. I fixed it by monkeypatching the new `load_h5py` function into `cx_Freeze.hooks` after importing cx_Freeze in my setup.py file.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Samer Afach (Bitbucket: [samerafach](https://bitbucket.org/samerafach), GitHub: [samerafach](https://github.com/samerafach))**:

----------------------------------------

This issue is still not fixed until today, which is quite surprising. Until now I have to fix `hooks.py` manually every time I install cx_freeze. Could someone please explain why this has been up for about a year now while the fix is super-trivial?

I'm happy to commit this myself. Should I? Does everyone have credentials for this?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

The pull request (see above) has been merged. It is simply waiting on me to produce a new release. My apologies for the lengthy delay. My day job no longer gives me the ability to work on this so I am doing it in my spare time!

**Comment by anthony-tuininga** [comment]
*Original comment by* **Samer Afach (Bitbucket: [samerafach](https://bitbucket.org/samerafach), GitHub: [samerafach](https://github.com/samerafach))**:

----------------------------------------

Thank you. I appreciate your efforts. It just was quite surprising. Please do it when you can.

**Comment by marcelotduarte** [comment]
Since 2016 it has already been resolved.
