### ISSUE TITLE
No option for setting RAM, terms and conditions, etc..

### ISSUE THREAD

**Issue by ajinzrathod** [marcelotduarte/cx_Freeze#1060]
**I am not reporting a bug, just want new things in the new update.**

cx_freeze is very amazing. 
But it would be great if it had more options like

1. Setting terms and conditions in installation
2. Specifying minimum RAM required
or any such features will be helpful

I searched many documentation related to above options, but was unable to fetch it.

If there is some docs related to this, please help me out.

**Comment by marcelotduarte** [comment]
Which OS are you referring to on this support?

>     1. Setting terms and conditions in installation

Which installation option do you use?


> I found it many where for since a long time but unable to get the results.
> If there is some docs related to this, please help me out.

I didn't quite understand the first sentence, so I'll link you to the beginning of the [documentation](https://cx-freeze.readthedocs.io/en/latest/).

**Comment by ajinzrathod** [comment]
I have not used Mac and most of applications in Linux doesn't ask for TNC.  So currently I am referring to Windows.

> I didn't quite understand the first sentence, so I'll link you to the beginning of the documentation.

I have updated the sentence now.

**Comment by marcelotduarte** [comment]
So, you're referring to using bdist_msi? Sorry, I need more concrete information. If you can, specify some links.

**Comment by ajinzrathod** [comment]
I am really new to installation processes in Windows. You can refer to the image below. Can I customize the installer to something like this?
* Which gets installed only after the user accepts permission
* If my application requires a minimum of 4 GB of RAM, it should check while installation whether the device is compatible or not.

[Image](https://ibb.co/7RCXMLK)

Another update that is really nice is

**Comment by ajinzrathod** [comment]
I am new to installation processes in Windows. Sorry but I really don't know how can I explain this. You can refer to the image below. Can I customize the installer to something like this?

[Image](https://ibb.co/7RCXMLK)

* Application gets installed only after the user accepts permission
* If my application requires a minimum of 4 GB of RAM, it should check while installation whether the device is compatible or not.

-----------------

And I want to create console-based scripts. You can refer [this video](https://youtu.be/GaWs-LenLYE?t=475) and skip to 7:55 to see how he runs **hello world** using Terminal

But this is build using [setuptools](https://pypi.org/project/setuptools/). I want to create these console-based scripts using cx_Freeze. So that in Linux, when I write the name of my app. It should also launch from the Command line.

**Comment by ajinzrathod** [comment]
One more question.
I want my app in Windows Application Launcher. In the same way, Spotify, sublime and all such apps are visible. See this image 

![this](https://i.stack.imgur.com/L7I4H.png) 

[This](https://github.com/marcelotduarte/cx_Freeze/issues/48#issue-202360209) says that 
> shortcutDir must be set to `"DesktopFolder"` or `"ProgramMenuFolder"`

I don't want it only in one place. I want it at both places.
shortcutDir must be set to `"DesktopFolder"` **AND** `"ProgramMenuFolder"`

How can I achieve this?

**Comment by ajinzrathod** [comment]
One issue I found is that the installer does not show **Install** button. Instead, it shows **Next**. The moment I click on **Next**, it starts getting installed.

Other options it should ask while installation whether to add to desktop or not, etc..

- [ ]  Add to desktop
- [ ] Launch after install

**Comment by marcelotduarte** [comment]
> How can I achieve this?

We lack more information. I suggest to you find:
http://msdn.microsoft.com/en-us/library/aa370905(v=vs.85).aspx#System_Folder_Properties
https://docs.microsoft.com/en-us/windows/win32/msi/windows-installer-portal

**Comment by ajinzrathod** [comment]
I will see it later and reopen this if needed

**Comment by marcelotduarte** [comment]
After getting success, help us improve the docs or code.
https://cx-freeze.readthedocs.io/en/latest/development/index.html
