### ISSUE TITLE
FreeBSD patchelf problem 

### ISSUE THREAD

**Issue by igroykt** [marcelotduarte/cx_Freeze#1061]
I did not find a solution either here or in Google. 

I get the error:

> copying /usr/local/lib/python3.7/lib-dynload/_bisect.so -> build/lib/_bisect.so
> Traceback (most recent call last):
>   File "setup.py", line 19, in <module>
>     executables = [Executable("auth.py"), Executable("clean.py")]
>   File "/usr/local/lib/python3.7/site-packages/cx_Freeze/dist.py", line 397, in setup
>     distutils.core.setup(**attrs)
>   File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.7/site-packages/cx_Freeze/dist.py", line 265, in run
>     freezer.Freeze()
>   File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 805, in Freeze
>     self._WriteModules(filename, self.finder)
>   File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 781, in _WriteModules
>     copyDependentFiles=True,
>   File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 226, in _CopyFile
>     has_rpath = self.patchelf.get_rpath(target)
> AttributeError: 'Freezer' object has no attribute 'patchelf'

To reproduce just install or build any version of python and try to freeze app.

On Linux and Windows it works as expected.

Info:
 - FreeBSD 11.2-13.0
 - amd64
 - cx-Freeze 6.6
 - Python 3.7.3-3.8.9
 - patchelf 0.12

Is there any solution? Thank.

P.S. setup.py:
```
import sys, os
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {
    "packages": ["os", "sys", "godaddypy", "configparser", "time", "logging", "dns.resolver", "tld"],
    "build_exe": "build"    
}

# GUI applications require a different base on Windows (the default is for
# a console application).
base = None

setup(
    name = "letsencrypt-godaddy",
    version = "1.2",
    description = "letsencrypt-godaddy",
    options = {"build_exe": build_exe_options},
    executables = [Executable("auth.py"), Executable("clean.py")]
)
```

**Comment by igroykt** [comment]
According to actual source code this problem will be solved on new release.
For now I can workaround like this in file /usr/local/lib/python3.8/site-packages/cx_Freeze/freezer.py:
```
...
27: if os.name == 'posix':
28:     from .patchelf import Patchelf
...
226: if os.name == 'posix':
227:     self.patchelf = Patchelf()
```

**Comment by marcelotduarte** [comment]
In Line 551:
```
if sys.platform == "linux":
            self.patchelf = Patchelf()
```

Can you me inform, the value of sys.platform in FreeBSD?
Maybe we should use another comparison.

**Comment by igroykt** [comment]
> 
> 
> In Line 551:
> 
> ```
> if sys.platform == "linux":
>             self.patchelf = Patchelf()
> ```
> 
> Can you me inform, the value of sys.platform in FreeBSD?
> Maybe we should use another comparison.

Hi.
Looks like bad idea because it returns distro specific value:
```
>>> import sys
>>> print(sys.platform)
freebsd13
```
It will be better to use platform.system() since it's a part of python:
```
>>> import platform
>>> print(platform.system())
FreeBSD
```
Also I will test actual code to see if it works.

**Comment by igroykt** [comment]
@marcelotduarte well I'm stuck.
First I got error:

> raise ConfigError(f"no base named {name!r}")

Looking at code I found that in setup.py now I should use "Console" value instead of "None":
```
base = "Console"
...
executables = [Executable("auth.py", base=base), Executable("clean.py", base=base)]
...
```
Then I got error:

> NameError: name '_base' is not defined

And found mistype (I guess) in executables.py:
```
self._base = base
```
Then I got err:

> NameError: name 'Patchelf' is not defined

So I updated comparison in freezer.py:
```
...
import platform
...
if platform.system() == "Linux" or platform.system() == "FreeBSD":
    from .patchelf import Patchelf
...
```

Next error:

> AttributeError: 'Executable' object has no attribute '_ext'

Added four variables in executables.py:
```
...
name: Optional[str] = "",
ext: Optional[str] = "",
...
self._name = name
self._ext = ext
...
```
And the result:

> running build
> running build_exe
> creating directory build/lib
> copying /usr/local/lib/python3.8/config-3.8/libpython3.8.a -> build/lib/libpython3.8.a
> copying Console -> build/auth
> error: [Errno 2] No such file or directory: 'Console'

:goberserk:

**Comment by marcelotduarte** [comment]
> Looks like bad idea because it returns distro specific value

Exactly. It is a bad idea to compare sys.platform for freebsd and other systems.
We had a different approach recently. In main branch, the code take care of windows, macos, and Linux (but the Linux code can be used by other OSes).
Can you test the main branch?
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main`

I'll try to use a docker to test FreeBSD before the release.

**Comment by igroykt** [comment]
> 
> 
> > Looks like bad idea because it returns distro specific value
> 
> Exactly. It is a bad idea to compare sys.platform for freebsd and other systems.
> We had a different approach recently. In main branch, the code take care of windows, macos, and Linux (but the Linux code can be used by other OSes).
> Can you test the main branch?
> `pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main`
> 
> I'll try to use a docker to test FreeBSD before the release.

Okay. I removed the package and installed it as you instruct.
Then I changed the comparison to:
```
if platform.system() == "Linux" or platform.system() == "FreeBSD":
    from .patchelf import Patchelf
```
And it worked!
:feelsgood:

**Comment by marcelotduarte** [comment]
PR #1067 to fix this.
Can you test the main branch?
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main

**Comment by igroykt** [comment]
> 
> 
> PR #1067 to fix this.
> Can you test the main branch?
> pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main

It works :)

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7b2 has just been released.
pip install cx-Freeze==6.7b2
Assuming this has been resolved.
If you had issues please open a new issue.
