### ISSUE TITLE
zip_exclude_packages = "*" does not work

### ISSUE THREAD

**Issue by graeme-hattan** [marcelotduarte/cx_Freeze#1117]
From the documentation for zip_file_excludes:

> use * to specify that all packages should be placed in the file system and excluded from the zip file (the default)

However, a zip file is a always created by default, regardless of whether `*` is specified.

Looking at the source code I see that the option does default to `*` and that this is checked here:

https://github.com/marcelotduarte/cx_Freeze/blob/09561f0699b2a2c6822bfbb99de466d2c26085a5/cx_Freeze/freezer.py#L408

However, the only place `zipExcludeAllPackages` is ever read is a couple of lines below to raise a config error if `zipIncludeAllPackages` is also set. I don't see any other code relevant to this feature, `zipIncludeAllPackages` gets passed to `ModuleFinder`, but `zipExcludeAllPackages` doesn't. Looks like this is only partly implemented.

**Comment by marcelotduarte** [comment]
The definitions of packages and modules are different.
https://docs.python.org/3/tutorial/modules.html
https://docs.python.org/3/tutorial/modules.html#packages

**Comment by graeme-hattan** [comment]
Ok, thanks, I didn't realise that distinction was being made, and I see how some of the packages installed by pip are in fact just modules with regard to how the interpreter imports them.

However, one thing I'm still a little confused about is that the `mpl_toolkits` directory from matplotlib, along with some __init__ files get pulled into the zip file. Seems that by this definition it should count as a package?

**Comment by marcelotduarte** [comment]
> However, one thing I'm still a little confused about is that the `mpl_toolkits` directory from matplotlib, along with some **init** files get pulled into the zip file. Seems that by this definition it should count as a package?

It is a bug. Described in #1276, resolved in PR #1290

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.8.4](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8.4) has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
