### ISSUE TITLE
Open3D Error w/ cx_Freeze

### ISSUE THREAD

**Issue by marcelotduarte** [marcelotduarte/cx_Freeze#1118]
### Discussed in https://github.com/marcelotduarte/cx_Freeze/discussions/1087

<div type='discussions-op-text'>

<sup>Originally posted by **jmachcse** June  1, 2021</sup>
Hey all --

I'm having an issue with using cx_Freeze with a large project. In it I have a file called `mathematics.py` that contains the line `if isinstance(Q, o3d.open3d_pybind.geometry.PointCloud):` 

The error I'm running into is `error: [Errno 2] No such file or directory: 'build\\exe.win-amd64-3.8\\lib\\open3d\\cpu\\pybind\\mathematics.pyc'`

I'm not sure why cx_Freeze is looking for that file in that folder when I don't think it should even exist at all.

Any assistance is appreciated! </div>

**Comment by jmachcse** [comment]
As of right now as discussed in #1087 the current issue is reflected in this traceback:

```
(GUIProject) C:\GUIProject>python setup.py build
running build
running build_exe
error: [Errno 2] No such file or directory: 'C:\\Users\\jmach\\AppData\\Local\\Temp\\cxfreeze913sxqzp\\nbconvert\\tests\\exporter_entrypoint\\eptest-0.1.dist-info\\entry_points.txt'
```

This is the farthest traceback I get on cx_Freeze 6.7b7

<details>
<summary> Current setup.py </summary>

```
from cx_Freeze import setup, Executable

build_options = {
    "include_files": [
        # ("pytest_runner-5.3.1.dist-info"),
        # ("PyYAML-5.4.1-py3.8-win-amd64.egg-info"),
        ("resources"),
    ],
    "packages": [
        "open3d",
        "yaml",
        "hdfdict",
        "xmltodict",
        "bin",
        "src",
    ],
    "includes": [],
    "excludes": ["nbconvert.tests"],
}



base = None
# base = 'Win32GUI' if sys.platform=='win32' else None

executables = [Executable("main.py", base=base)]

setup(
    name="My_Project",
    version="1.0",
    description="1.0 of my first bundled exe",
    options={"build_exe": build_options},
    executables=executables,
)

```
</details>
</summary>


There are more tracebacks in #1087 but I can't remember what version of cx_Freeze they were on.

Thanks for any help, all!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7b8 has just been released.
pip install cx-Freeze==6.7b8

Try it out and confirm.

**Comment by jmachcse** [comment]
It's looking like everything is working to me! 
No pyyaml errors, pytest runner errors, nothing. 
If I get any errors in further testing that I think are cx_Freeze related I'll let you know.
Thank you so much for working on this issue for over a month now!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
pip install --upgrade cx_Freeze
