### ISSUE TITLE
ImportError: unable to find Qt5Core.dll on PATH

### ISSUE THREAD

**Issue by andrewchenshx** [marcelotduarte/cx_Freeze#1119]
env:
1)Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
2)PyQt5 Version: 5.12.3
3)cx_freeze: Version: 6.6
result:
1)The exe file is generated without error messages.
2)while the exe invoked from command line, here is the error messages:

> Traceback (most recent call last):
  File "C:\Users\hp\Anaconda3\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 81, in run
    module.run()
  File "C:\Users\hp\Anaconda3\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
    exec(code, m.__dict__)
  File "tbbs_assist.py", line 10, in <module>
  File "C:\Users\hp\Anaconda3\lib\site-packages\PyQt5\__init__.py", line 41, in <module>
    find_qt()
  File "C:\Users\hp\Anaconda3\lib\site-packages\PyQt5\__init__.py", line 33, in find_qt
    raise ImportError("unable to find Qt5Core.dll on PATH")
ImportError: unable to find Qt5Core.dll on PATH

line 10 of my_program.py is as following:
`from PyQt5 import QtCore`

after some investigation, here is something interesting.
compared to the last successful build( i committed to my private git server),
/lib/PyQt5/Qt5Core.dll, /lib/PyQt5/Qt5Gui.dll, and /lib/PyQt5/Qt5Widgets.dll and some other files are now missing,
and /lib/PyQt5/Qt5Core_conda.dll, /lib/PyQt5/Qt5Gui_conda.dll, and /lib/PyQt5/Qt5Widgets_conda.dll and some other files are now added.

**Comment by andrewchenshx** [comment]
it's duplicate of #678, which is closed

**Comment by marcelotduarte** [comment]
Can you remove all pyqt packages? Use a conda list to check if all are removed, and then install pyqt.
Remove cx_freeze and install the new cx_freeze 6.7
I do not hope that this will resolve your issue, but to fresh the results and help me to work on that.
Then put your setup.py (or the relevant part) and a traceback (like in the first comment).
I'll work to resolve issues with pyqt and conda.

**Comment by andrewchenshx** [comment]
after upgrading to 6.7, it works

**Comment by marcelotduarte** [comment]
To document:
The fix for this error is PR #974 released in 6.6
A change in pyqt 5.12.3 needs a change in the PATH.
With pyqt 5.12.2 or 5.12.1 it worked (and probably you have your last successful build).

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8b1 has just been released with fixes for pyqt5. Please, try it out and report.
pip install cx-Freeze==6.8b1

**Comment by andrewchenshx** [comment]
cx_Freeze 6.8b1 + pyqt5 works!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
