### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by rayzchen** [marcelotduarte/cx_Freeze#1128]
**Prerequisite**
 - Make sure no duplicated issue has already been reported. You should look for closed issues, too.
 - Make sure you are not asking us to help to solve your specific issue. GitHub issues are opened mainly for development purposes. If you want to ask someone to help to solve your problem, go to some community site like StackOverflow, etc.
 - Make sure your problem is not derived from packaging (e.g. Homebrew). 

**Describe the bug**
I am using PyUnity to make an exe, which depends on a number of modules. If i use `--includes` or the "includes" attribute of the `build_exe_options`, it packages every single package I have installed on my computer.

**To Reproduce**
Steps to reproduce the behavior
Install PyUnity

main.py
```python
from pyunity.examples import show
show()
```
run `cxfreeze -c main.py -install-dir dist`
the exe says `cannot find sdl2`
run `cxfreeze -c main.py --install-dir dist --includes pyunity`
the exe says `cannot find sdl2`
run `cxfreeze -c main.py --install-dir dist --includes pyunity,OpenGL,glfw,sdl2,sdl2dll,PIL,glm`
the exe takes 20 mins to build and includes every package I have installed (about 100)

**Expected behavior**
Only my specified modules are included

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 16.04): Windows 10
 - OS architecture (e.g. amd64): 64bit
 - cx_Freeze version [e.g. 6.6]: 6.6
 - Python version [e.g. 3.9]: 3.9

**Additional context**

**Comment by marcelotduarte** [comment]
I tried to install pyunit:
`pip install PyUnit`
ERROR: Could not find a version that satisfies the requirement PyUnit (from versions: none)
ERROR: No matching distribution found for PyUnit

I think that it is a very old package that does not support py39.
If you use a package that imports some other packages and includes some others, the list will grow.
If you use includes, you can use excludes too.

Can I close this issue?

**Comment by rayzchen** [comment]
I was referring to my own package `pyunity`...

**Comment by rayzchen** [comment]
But why does --include-dir have to include every package?

> If you use includes, you can use excludes too.

Do I need to exclude all packages I have installed?

**Comment by marcelotduarte** [comment]
> Do I need to exclude all packages I have installed?

No, You don't. Just to use as an example, PIL has imports for various packages: pyqt5, pyside2, wxWidgets, etc. So with this packages, a large list of packages are included. 

I usually use a venv with only the packages I need for a certain project, so even if it has references to a certain package, it will be ignored.

If you use one of the [samples](https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples), like bcrypt or simple you will get a few packages included. If you use pillow samples, you can get mores packages than you want.

EDIT: My reasoning was incomplete. If you use a venv with only cx_Freeze and pillow, using the pillow sample, only pillow package (and the standard library) are included.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.11](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.11.0) has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
