### ISSUE TITLE
Add base to cxfreeze script

### ISSUE THREAD

**Issue by maicol07** [marcelotduarte/cx_Freeze#1131]
Hi,

can you add the base option to the cxfreeze script like the one in the distutils script?

Thanks

**Comment by marcelotduarte** [comment]
Hi! cxfreeze script has option --base-name

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
