### ISSUE TITLE
PySide2 application does not work properly

### ISSUE THREAD

**Issue by Lois31** [marcelotduarte/cx_Freeze#1143]
Hello team,

I have an issue when I freeze my PySide2 application. Several libraries are not correctly copying.

Platform configuration:

- Windows 10 x86_64
- Python 3.9.6
- Virtual Env:
  - cx_Freeze 6.7
  - PySide2 5.15.2

Here the source code of my example application:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from PySide2.QtWidgets import QApplication, QWidget
# import QtGui and QtCore only so that they are also frozen
import PySide2.QtGui
import PySide2.QtCore

def main():
    app = QApplication(sys.argv)
    window = QWidget()
    window.setWindowTitle("Simple")
    window.show()
    return app.exec_()

if __name__ == "__main__":
    sys.exit(main())
```

Here the setup.py script:
```python
import os
import sys

import PySide2
from cx_Freeze import setup, Executable

plugins_path = os.path.join(PySide2.__path__[0], "plugins")

base = None
if sys.platform == 'win32':
    base = 'Win32GUI'

options = {
    'build_exe': {
        "include_files": [os.path.join(plugins_path, "platforms")],  # additional plugins needed by qt at runtime
        "zip_include_packages": ["PySide2", "shiboken2", "encodings"],  # reduce size of packages that are used
        "excludes": ["tkinter", "unittest", "email", "http", "xml", "pydoc", "pdb"],  # exclude packages that are not really needed
    }
}

executables = [
    Executable('PySide2app.py', base=base),
    Executable('test-gui.py', base='Console')
]

setup(
    name='simple_PySide2',
    version='0.1',
    description='Sample cx_Freeze PySide2 script',
    options=options,
    executables=executables
)
```

To finish the command line that I use to freeze my application
```bash
python setup.py build --build-exe bin\windows
```

The following libraries are missing:
- vcruntime140.dll
- lib/shiboken2.abi3.dll
- lib/pyside2.abi3.dll
- lib/Qt5*.dll (Qt5Core.dll, Qt5Xml.dll, Qt5Gui.dll, ...)

**Comment by marcelotduarte** [comment]
For vcruntime to be copied:
https://cx-freeze.readthedocs.io/en/latest/faq.html#microsoft-visual-c-redistributable-package
https://cx-freeze.readthedocs.io/en/latest/distutils.html#cmdoption-arg-include_msvcr

In a CI a test the sample at:
https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples/pyside2
and it works in py36 to 39

I'll take a look at your example app.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.8b2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8b2) has just been released.
Please check the updated sample:
https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples/pyside2
Please, try it out and report.
pip install cx-Freeze==6.8b2

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
