### ISSUE TITLE
Unable to load shiboken2 after freezing on shared directory

### ISSUE THREAD

**Issue by Lois31** [marcelotduarte/cx_Freeze#1144]
Hello team,

I have an issue when I freeze my PySide2 application. 
I am unable to launch it on a shared directory.
This issue is related to issue #767.

Platform configuration:

- Windows 10 x86_64
- Python 3.9.6
- Virtual Env:
  - cx_Freeze 6.7
  - PySide2 5.15.2

Here the source code of my example application:
```python
import os
import sys
if getattr(sys, 'frozen', False):
    dll_path = os.path.join(os.path.dirname(sys.executable), 'lib')
    print(dll_path)
    os.add_dll_directory(dll_path)

from PySide2 import QtGui, QtCore, QtUiTools, QtWidgets, QtXml

print("Import OK")
```

Here the setup.py script:
```python
import os
import sys

import PySide2
from cx_Freeze import setup, Executable

plugins_path = os.path.join(PySide2.__path__[0], "plugins")

base = None
if sys.platform == 'win32':
    base = 'Win32GUI'

options = {
    'build_exe': {
        "include_files": [os.path.join(plugins_path, "platforms")],  # additional plugins needed by qt at runtime
        "zip_include_packages": ["PySide2", "shiboken2", "encodings"],  # reduce size of packages that are used
        "excludes": ["tkinter", "unittest", "email", "http", "xml", "pydoc", "pdb"],  # exclude packages that are not really needed
    }
}

executables = [
    Executable('test-gui.py', base='Console')
]

setup(
    name='simple_PySide2',
    version='0.1',
    description='Sample cx_Freeze PySide2 script',
    options=options,
    executables=executables
)
```

To finish the command line that I use to freeze my application
```bash
python setup.py build --build-exe bin\windows
```

I specify that this application is built in a virtual environment locally.

This application works in the following cases:
- locally:
  - The frozen application: _bin\windows\test-gui.exe_
  - The application from source: _python test-gui.py_
- on shared directory:
  - The application from source: _python test-gui.py_

However, the freeze app crashes indefinitely when launched on a shared directory.
After launching a ctrl-c, below the Python traces
```bash
Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python39\lib\genericpath.py", line 19, in exists
    os.stat(path)
FileNotFoundError: [WinError 2] 
The specified file can not be found: '\\\\filer001\\HOME25\\files.dir\\shibokensupport\\signature\\loader.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "(builtin)", line 113, in bootstrap
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python39\lib\genericpath.py", line 19, in exists
    os.stat(path)
KeyboardInterrupt
Fatal Python error: could not initialize part 2
Python runtime state: initialized

Current thread 0x00003f08 (most recent call first):
  File "C:\temp\PYTHON39_QT5\python_env\lib\site-packages\shiboken2\__init__.py", line 30 in <module>
  File "<frozen zipimport>", line 259 in load_module
  File "<frozen importlib._bootstrap>", line 627 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "C:\temp\PYTHON39_QT5\python_env\lib\site-packages\PySide2\__init__.py", line 58 in _setupQtDirectories
  File "C:\temp\PYTHON39_QT5\python_env\lib\site-packages\PySide2\__init__.py", line 107 in <module>
  File "<frozen zipimport>", line 259 in load_module
  File "<frozen importlib._bootstrap>", line 627 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "test-gui.py", line 8 in <module>
  File "C:\temp\PYTHON39_QT5\python_env\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15 in run
  File "C:\temp\PYTHON39_QT5\python_env\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104 in run
```

For information, the _\\\\filer001\\HOME25_ folder is the shared directory on which I launched the application.
The application is built in the _C:\temp\PYTHON39_QT5_ directory

Thanks for your help.

**Comment by ctismer** [comment]
Interesting! Can you please try the same on a local drive?
Fact is that PySide does not find its shibokensupport directory. Therefore, it does an urgency fallback
and uses a builtin ZIP file. This gets unpacked to a temp folder until the run ends.
cx_freeze seems to memorize the temp file path, unfortunately.

I think this error is not new, but in 5.12, the signature module was ignored when not found.
Meanwhile, I consider it a mis-configuration, and a lot of code relies on it.

Maybe we just need to convince cx_freeze to ignore the temp file.

**Comment by Lois31** [comment]
Hello, and thank you for your feedback.
As I tried to explain in my ticket, it works very well in source or frozen mode on a local disk.
The problem only occurs in frozen mode on a share disk on Windows (No problem on Linux).

I tested the same configuration this morning with PySide2 5.12.0 and everything works fine.
As you supposed, there has been a change in the handling of the _signature_ module from PySide2 5.12.1.
This is described in the following tickets: [PYSIDE-932](https://bugreports.qt.io/browse/PYSIDE-932), [PYSIDE-942](https://bugreports.qt.io/browse/PYSIDE-942), [PYSIDE-1621](https://bugreports.qt.io/browse/PYSIDE-1621).

How to configure cx_freeze to ignore the _signature_ module?

**Comment by ctismer** [comment]
Sure, I am the one who's guilty to invent that signature module :innocent:
> The problem only occurs in frozen mode on a share disk on Windows 

And that shared disk is from which OS? Maybe it is just a syntax problem.
I guess if we can avoid that the urgency zip file is created and unpacked,
the problem would vanish.

How should I configure the drive to test the scenario? I am on macOS.
Does it make sense to try on a shared Parallels windows drive, or even vice-versa?

**Comment by ctismer** [comment]
I have implemented a fully virtual zipimporter solution that should no longer have the problem. But it works for Python 3, only.

**Comment by Lois31** [comment]
I closed the ticket because a perennial solution will be implemented in a future version of PySide (cf [PYSIDE-1621](https://bugreports.qt.io/browse/PYSIDE-1621))
