### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'google-api-python-client' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by NicholasDawson** [marcelotduarte/cx_Freeze#1147]
**Prerequisite**
I did find an instance of this issue, but it is not the exact same so I wanted to provide details to potentially help the development team on this issue.

Issue: https://github.com/marcelotduarte/cx_Freeze/issues/438
Workaround that worked for me: https://github.com/marcelotduarte/cx_Freeze/issues/438#issuecomment-472954154

I tried including `pkg_resources` in the list of packages for the build options but that didn't work either. The only thing that worked was to either manually copy the dist-info folder to the lib of the build or use the workaround function above to ensure those files are added automatically.

**Describe the bug**
When I build the executable using the following `setup.py` and the command `py setup.py build`
```python3
from cx_Freeze import setup, Executable

# Dependencies
build_exe_options = {
    "packages": [
        "io",
        "json",
        "os",
        "pickle",
        "multiprocessing",
        "piexif",
        "google.auth.transport.requests",
        "google_auth_oauthlib.flow",
        "googleapiclient.discovery",
        "httplib2",
        "PIL",
        "tqdm",
        "pkg_resources"
    ]
}

base = None

setup(
    name="Archiver for Google Photos",
    version="0.1.0",
    description="A tool to maintain an archive/mirror of your Google Photos library for backup/migration purposes.",
    options={"build_exe": build_exe_options},
    executables=[Executable("gphotos_archiver.py", base=base)]
)
```
The build is successful, but on run of the resultant executable I get the following error:
```
❯ .\gphotos_archiver.exe
Traceback (most recent call last):
  File "C:\Users\18603\.virtualenvs\ArchiverForGooglePhotos-b7olzZyw\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
    module_init.run(name + "__main__")
  File "C:\Users\18603\.virtualenvs\ArchiverForGooglePhotos-b7olzZyw\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
    exec(code, module_main.__dict__)
  File "gphotos_archiver.py", line 12, in <module>
  File "C:\Users\18603\.virtualenvs\ArchiverForGooglePhotos-b7olzZyw\lib\site-packages\googleapiclient\discovery.py", line 68, in <module>
    from googleapiclient.http import build_http
  File "C:\Users\18603\.virtualenvs\ArchiverForGooglePhotos-b7olzZyw\lib\site-packages\googleapiclient\http.py", line 64, in <module>
    from googleapiclient.model import JsonModel
  File "C:\Users\18603\.virtualenvs\ArchiverForGooglePhotos-b7olzZyw\lib\site-packages\googleapiclient\model.py", line 36, in <module>
    _LIBRARY_VERSION = pkg_resources.get_distribution("google-api-python-client").version
  File "C:\Users\18603\.virtualenvs\ArchiverForGooglePhotos-b7olzZyw\lib\site-packages\pkg_resources\__init__.py", line 466, in get_distribution
    dist = get_provider(dist)
  File "C:\Users\18603\.virtualenvs\ArchiverForGooglePhotos-b7olzZyw\lib\site-packages\pkg_resources\__init__.py", line 342, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\Users\18603\.virtualenvs\ArchiverForGooglePhotos-b7olzZyw\lib\site-packages\pkg_resources\__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\18603\.virtualenvs\ArchiverForGooglePhotos-b7olzZyw\lib\site-packages\pkg_resources\__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'google-api-python-client' distribution was not found and is required by the application
```

I am able to fix the bug by pasting the `google_api_python_client-2.13.0.dist-info` folder (which is in the `Lib\site-packages` directory of the pipenv) into the `build\exe.win-amd64-3.9\lib` directory after building the executable using `py setup.py build` command.

I think the problem is that `google_api_python_client` isn't actually the name of the module you import, it is just the name of the installed pip package `https://pypi.org/project/google-api-python-client/`.

There is no package folder called `google_api_python_client`.

**To Reproduce**
To reproduce this issue, run the `setup.py` above using the command `py setup.py build` and in that directory include the following file: `gphotos_archiver.py`. (I included the `Pipfile` and `Pipfile.lock` below as well so you can ensure the packages are the same as mine)

[code.zip](https://github.com/marcelotduarte/cx_Freeze/files/6816767/code.zip)

**Expected behavior**
What I expect is that the executable should run successfully as all the modules/packages required are included. It seems the dist-info was never detected and added to the lib of the exe as a result.

I think cx_Freeze should be able to detect and include the dist-info as necessary.

My fix was to use the following `setup.py` as listed in the workaround here: https://github.com/marcelotduarte/cx_Freeze/issues/438#issuecomment-472954154
```python3
import pkg_resources
from os.path import join, basename
from cx_Freeze import setup, Executable


def collect_dist_info(packages):
    """
    Recursively collects the path to the packages' dist-info.
    From: https://github.com/marcelotduarte/cx_Freeze/issues/438#issuecomment-472954154
    """
    if not isinstance(packages, list):
        packages = [packages]
    dirs = []
    for pkg in packages:
        distrib = pkg_resources.get_distribution(pkg)
        for req in distrib.requires():
            dirs.extend(collect_dist_info(req.key))
        dirs.append((distrib.egg_info, join('Lib', basename(distrib.egg_info))))
    return dirs


# Dependencies
build_exe_options = {
    "packages": [
        "io",
        "json",
        "os",
        "pickle",
        "multiprocessing",
        "piexif",
        "google.auth.transport.requests",
        "google_auth_oauthlib.flow",
        "googleapiclient.discovery",
        "httplib2",
        "PIL",
        "tqdm",
        "pkg_resources"
    ],
    "include_files":
        collect_dist_info("google_api_python_client")
}

base = None

setup(
    name="Archiver for Google Photos",
    version="0.1.0",
    description="A tool to maintain an archive/mirror of your Google Photos library for backup/migration purposes.",
    options={"build_exe": build_exe_options},
    executables=[Executable("gphotos_archiver.py", base=base)]
)
```

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 16.04): **Windows 10 Education (21H1)**
 - OS architecture (e.g. amd64): **amd64**
 - cx_Freeze version [e.g. 6.6]: **6.7**
 - Python version [e.g. 3.9]: **3.9.6**

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8b1 has just been released with fixes for this issue (PR #1151). Please, try it out and report.
pip install cx-Freeze==6.8b1

**Comment by NicholasDawson** [comment]
I just tested, it is working great without the need for a workaround. Thank you Marcelo

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
