### ISSUE TITLE
Output of `cx_freeze` > version `6.2` fails to pass apple notarization

### ISSUE THREAD

**Issue by TechnicalPirate** [marcelotduarte/cx_Freeze#1166]
**Describe the bug**

When passing the output of an app frozen with` cx_freeze` to [Apple for notarization](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution) it fails to pass the gatekeeper - Specifically the `libintl.8.dylib` is reported as unsigned - This issue appears to have started with `cx_freeze` version `6.3` - prior to this i can successfully notarize my app with `python 3.8.11` and `cx_freeze` `6.2` :) 

```        
       {
            "severity": "error",
            "code": null,
            "path": "ourapp.pkg Contents/Payload/Applications/ourapp.app/Contents/Resources/lib/libintl.8.dylib",
            "message": "The binary is not signed.",
            "docUrl": null,
            "architecture": "x86_64"
        },

        {
            "severity": "error",
            "code": null,
            "path": "ourapp.pkg Contents/Payload/Applications/ourapp.app/Contents/Resources/lib/libintl.8.dylib",
            "message": "The signature does not include a secure timestamp.",
            "docUrl": null,
            "architecture": "x86_64"
        },
```

**To Reproduce**
_I can prepare a full sample as required, please ask if there none of the existing samples have been passed to notarization_ 
Edit : This user kindly provided a sample https://github.com/marcelotduarte/cx_Freeze/issues/594 [here in a gist ](https://gist.github.com/darad/0941523d06ef4be50ea1861ba3b5d776)of how they handle restructuring the bundle for code-signing

**Expected behaviour**
Notarizating apps made with cx_freeze should pass Apples gatekeeper 

**~Desktop~ Build Agent**
 - Platform information (e.g. Ubuntu Linux 16.04): Jenkins OSX BigSur
 - OS architecture (e.g. amd64): 64bit

**Python + cx_version reproductions**
Have tested generating builds using all versions of `cx_freeze` from `6.1` upwards on both Python `3.9` and python `3.8.11` - The issue begins to occur with version `6.3`

Reproduced with:
- Py `3.9.2-6` + cx_freeze `6.6:6.7`
- Py `3.8.11` + cx_freeze `6.6:6.7` + `6.3`
- _I tested cx_freeze `6.4` and `6.5` with both Py versions but was hitting an unrelated `PySide2` bug_

**Additional context**
- I'm actively working on this task, i will keep updating this issue with more information as i go - if you haven't got a ready made sample for OSX notarization I will prepare you one :)

**Comment by TechnicalPirate** [comment]
After walking back through combinations of python + cx_freeze - this failure began to occur with version `6.3` - Updated original issue to reflect this. Going to log-off for the day now, but i'd be more than happy to help investigate this / test updates :) 


_Next day edit : Saw the `6.8b1` pre release - tested that - same result `libintl.8` failing_

**Comment by marcelotduarte** [comment]
@TechnicalPirate I will gladly accept contributions to resolve these issues. I can review and test in the CI environment. Unfortunately, I have little time and I don't have macOS access to work on it and debug.
https://cx-freeze.readthedocs.io/en/latest/development/index.html#contributing

**Comment by marcelotduarte** [comment]
Between version 6.2 and 6.3 there seems to be nothing that I could have caused this, at least there are no major changes aimed at macOS.
https://cx-freeze.readthedocs.io/en/latest/releasenotes.html#version-6-3-october-2020

Try to use [bin_excludes](https://cx-freeze.readthedocs.io/en/latest/distutils.html#cmdoption-arg-bin_excludes)
bin_excludes=["libintl.8"]

**Comment by TechnicalPirate** [comment]
Hey @marcelotduarte thanks for the update - I agree in the changelog nothing stood out to me for OSX, but i did notice this in the general updates

> Ensure the copy of default python libraries in all platforms (PR #706, Issue #701)

I'm not working today as i'm rather unwell but i'll try to look more in depth at this once recovered. Updates to follow :)

**Comment by TechnicalPirate** [comment]
Hi @marcelotduarte :) 

Resumed work on this today, using `bin_excludes=["libintl.8.dylib"]` gets it past Apple Notarization... but haven't been able to confirm things as working in the final product as we're hitting some `PySide2` errors with missing images

```
ImportError: dlopen(/Users/team.mate/Applications/OurApp.app/Contents/MacOS/lib/PySide2/QtWidgets.abi3.so, 2): Library not loaded: @executable_path/../Frameworks/QtWidgets
  Referenced from: /Users/team.mate/Applications/OurApp.app/Contents/MacOS/lib/PySide2/QtWidgets.abi3.so
  Reason: image not found
```

... I'll be investigating this in more depth tomorrow... [prob related to this!](https://github.com/marcelotduarte/cx_Freeze/issues/594) .. [also tangentially linked to this](https://github.com/marcelotduarte/cx_Freeze/issues/1103)

The good news is i've now got `pyenv` and `pipenv` playing nice on our Jenkins images so testing combinations of versions + dep's is pretty trivial now :)

**Comment by marcelotduarte** [comment]
Hi, I'm working on pyside2 hooks, and soon I'll notify you to test. I too commented in the other post, so you can check for now with the beta version.
pip install cx-freeze==6.8b1

**Comment by TechnicalPirate** [comment]
Awesome, I'll get on that tomorrow :)

**Comment by marcelotduarte** [comment]
Please, do two tests for me and report:
1) Use the beta version with a patch that make conda on osx to compile in py39
`pip install cx-freeze==6.8b1`
2) A more recent development version with pyside2 hooks (6.8a2)
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Comment by TechnicalPirate** [comment]
Hey Marcel,

Have tested both - no luck yet - we're currently investigating if our ["restructure app bundle"](https://github.com/marcelotduarte/cx_Freeze/issues/594) code ( so the frameworks conform to Apples expected structure ) is at fault, still digging currently....

edit: end of day update - comparing our last successful product builds ( py3.6.8, cx_freeze 6.1 and Mojave build agent ) - it appears that yes somethings very different in the output running `otool -l` on `QtWidgets.abi3.so` to look for where its finding dependencies gives radically different results.

*Old*
```
	@rpath/libpyside2.abi3.5.14.dylib (compatibility version 5.14.0, current version 5.14.1)
	@rpath/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.14.0, current version 5.14.1)
	@rpath/libshiboken2.abi3.5.14.dylib (compatibility version 5.14.0, current version 5.14.1)
	@rpath/QtGui.framework/Versions/5/QtGui (compatibility version 5.14.0, current version 5.14.1)
	@rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

*New*

```
	@executable_path/../Frameworks/libpyside2.abi3.5.15.dylib (compatibility version 5.15.0, current version 5.15.2)
	@executable_path/../Frameworks/QtWidgets (compatibility version 5.15.0, current version 5.15.2)
	@executable_path/../Frameworks/libshiboken2.abi3.5.15.dylib (compatibility version 5.15.0, current version 5.15.2)
	@executable_path/../Frameworks/QtGui (compatibility version 5.15.0, current version 5.15.2)
	@executable_path/../Frameworks/QtCore (compatibility version 5.15.0, current version 5.15.2)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

We will continue investigating tomorrow :)

**Comment by TechnicalPirate** [comment]
Hi @marcelotduarte  we managed to track down the failure in the products of our builds - we're pretty confident something changed since `cx_freeze-6.4` that changed bundle structures for PySide2 ( Or PySide itself changed structure? ) and in doing so busted our "rejig" script

Next steps:

1) I will close this issue as  `bin_excludes=["libintl.8.dylib"]`  is a valid workaround for now 😺
2) We will provide you an updated `gist` of our re-packaging script in the hopes it can be used to help [address this issue ](https://github.com/marcelotduarte/cx_Freeze/issues/594) and make the output of cx_freeze inline with apples expectations
3) We will test the environment variables [mentioned on this issue](https://github.com/marcelotduarte/cx_Freeze/issues/1103) to see if we regain backward compatibility 

Thanks again for your support ^ guidance ❤️

**Comment by marcelotduarte** [comment]
> something changed since cx_freeze-6.4 that changed bundle structures for PySide2

changed both ;-)

Please update me with your tests.
A hug.

**Comment by TechnicalPirate** [comment]
Continuing with this / [Related backwards compatibility](https://github.com/marcelotduarte/cx_Freeze/issues/1103) task today 

I'm reopening this ticket because `bin_excludes=["libintl.8.dylib"]` is a acceptable workaround for installing the product on BigSur - The app won't function on `Mojave` or `Catalina` without that library. 

We can of course *not* notarize at all in which case the product works on Mojave and up -

However, without notarization users on Catalina or newer get a blocking malicious software dialog on application startup

**Comment by TechnicalPirate** [comment]
Trying to get my head around where this is coming from - a colleague if he builds locally doesn't have this `.dylib` picked up.

```
running build_exe
creating directory build/exe.macosx-10.9-x86_64-3.9/lib
copying /Volumes/jenkins/.pyenv/versions/3.9.6/lib/python3.9/config-3.9-darwin/libpython3.9.a -> build/exe.macosx-10.9-x86_64-3.9/lib/libpython3.9.a
copying /usr/local/opt/gettext/lib/libintl.8.dylib -> build/exe.macosx-10.9-x86_64-3.9/lib/libintl.8.dylib
```

It's the only library i can see been copied out of `/user/local` by cx_freeze.

_____

Some progress, I'm adding some hacks to our refactor script to ensure that `.dylib` ends up in `/Frameworks` so it can actually be signed by us - right now its failing because its outside the expected bundle structure.

**Edit Status** -  Current status, Fixed!

@marcelotduarte -  I'm able to resolve this by self-signing with our refactor script now I've caught this rogue `dylib` and moved it to the right place- but how would you like to proceed from here on the bigger topic of ensuring `cx_freezes` `bdist_mac` output is actually adhering to Apples requirements? 

Is this something you feel is important to resolve in the short-mid term? 

As always, thanks for your work maintaining this awesome library :)

**Comment by TechnicalPirate** [comment]
Closing this issue - i have updated the `gist` provided in the other issue with the changes to our restructuring script :)

**Comment by marcelotduarte** [comment]
> how would you like to proceed from here on the bigger topic of ensuring cx_freezes bdist_mac output is actually adhering to Apples requirements?

Yes, I do. But, I need that you contribute a PR.

**Comment by TechnicalPirate** [comment]
Ok, I'll try and put some time aside to get into this. Is there a discord or some other means to communicate with the `cx_freeze` project to ask more daft / quick questions? :)

**Comment by marcelotduarte** [comment]
No. You can open a new issue or reopen. Or in the pull request, we discuss and review.

**Comment by marcelotduarte** [comment]
Making a PR you and your team are also benefited, because we will have a version built into cx_Freeze and I can also use a basic test to check if it is still functional. So when you release a version, it already has the functionality ready.
As I realized by gist, it would be a command that extends on bdist_mac, so we have to get a name, maybe bdist_mac_notarization

**Comment by TechnicalPirate** [comment]
👍 Coolios - I'll try and get on this mid august, my expectation would be we should refactor the `bdist_mac` to correctly output the right structure rather than creating a new target type*.

_I'm a bit of a pessimist and I'm assuming at somepoint they will flatly refuse to allow Apps to run if they don't follow their guidelines, each new OS version has introduced more restrictions over products installed on their OS:D_
