### ISSUE TITLE
ImportError: dynamic module does not define init function (PyInit__lzma)

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#117]
Originally reported by: **Anonymous**

----------------------------------------

When try to run freezed aplication I got this problem:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_freeze-5.0-py3.4-win32.egg\cx_Fre
    exec(code, m.__dict__)
  File "appGUI.py", line 6, in <module>
  File "C:\Python34\lib\lzma.py", line 26, in <module>
    from _lzma import *
ImportError: dynamic module does not define init function (PyInit__lzma)

 My system is Windows Seven 32bit, Python 3.4.1, cx_freeze 5.0 compiled 27-10-2014

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/117

**Comment by anthony-tuininga** [comment]
*Original comment by* **Adrian Czapnik (Bitbucket: [flashmaker](https://bitbucket.org/flashmaker), GitHub: [flashmaker](https://github.com/flashmaker))**:

----------------------------------------

The same problem when try to import encodings idna:
ImportError: dynamic module does not define init function (PyInit_unicodedata)

**Comment by marcelotduarte** [comment]
Assuming this has been resolved.
If you had issues please re-open.
