### ISSUE TITLE
patchelf issues

### ISSUE THREAD

**Issue by marcelotduarte** [marcelotduarte/cx_Freeze#1171]
<div type='discussions-op-text'>

<sup>Originally posted by **Fox214** July  9, 2021</sup>
Hi,

I've been using cx_freeze for years for a linux program. I recently tried the latest version which forces me to install patchelf in order to build. I was using patchelf after the process on a few selected files to make sure I got the right version of them and simply force ignore LD_LIBRARY_PATH anyways. The problem I'm having is after patchelf runs my program just seg faults and core dumps. I think its being too aggressive, i'm not certain if patchelf itself is corrupting some of the .so files, or the cx_freeze call is editing them in a manner that causes the fail. 

I would like to propose some changes to the flow:
1. allow cx_freeze to run without patchelf. Probably best to make an option to disable, but if were as simple as if not in the users path it skips the processing that would work too. (it fails currently if its not in my path) 
2. If the user does run it, the default can be do everything but having the ability to either tell it which files to run or skip would be beneficial. I have no preference toward either method, supporting both may be best as different users might have a preferred one. For the explicit list it could be a ilst of tuples with (filename, patchelf args) structure (if the 2nd one blank it would use the default settings), an omit list could just be a list of files
3. you should do a chmod +w (via os.chmod()) type operation before running patchelf, otherwise it fails. </div>

@marcelotduarte
marcelotduarte
11 days ago
Maintainer

When I decided to include patchelf in cx-freeze, I even thought of something like your option 1. Use if installed.
The problem was that I had to help a lot of people with issues and that were directly connected to rpath. As most large packages use manylinux and consequently use patchelf to tune rpath, I saw the need to tweak it again for cx-freeze.
Maybe the right thing would be to find out which package used patchelf and use them only.
Leaving patchelf as an option will not work. Anyone who doesn't have it installed won't install it and then complain that it's not working and I'll have to ask to install it. Only in pure python projects (they don't use C extensions) you don't really need patchelf, in which case it won't fail and won't force installation. If the guy didn't install it, there won't be an error.
Of course, I'm not saying it's perfect, I've had to fix one or two bugs because of patchelf and I think there's one more open. But I think it's easier to fix them (because I'll have to fix them anyway) than to guide people to install patchelf after discovering that this is the cause, the lack of it.

I suggest you give me your system details and errors on issue #1132 if you think it's the same type of error you encountered.
1 reply
@Fox214
Fox214
11 days ago
Author

I'm not sure I started seeing segfaults with 6.5.3 (I did not try 6.5.1 or 6.5.2) my code is much more complex than that test case and is on CentOS 7.

But I got a preliminary build to work with 6.7 and i checked there are 179 so files in the build, 53 of them have altered RPATHs, 49 of them are incorrect and I can tell from looking at readelf -d.

If I unset LD_LIBRARY_PATH before running cx_freeze (I set this so libraries are standardized and I do not get different behavior across the compute farm) only 36 files are edited, and the path seems reasonable. (otherwise it contained my LD_LIBRARY_PATH in it, which is not what I want) it still core dumps, possible due to the issue #1132 (this occurs on 3.7.x and 3.8.x for me too)

**Comment by marcelotduarte** [comment]
@Fox214 I converted to an issue. Soon I'll take a look at it.

**Comment by Fox214** [comment]
Ok thanks, I did verify 6.5.2 is the last version that works for me (if you ping me here I can test the new versions). 

Sorry this is light on the details but the modules I've had to tinker with to get to work (particularly with patchelf, possibly with includes etc..) have been numpy, scipy, scikit-learn, matplotlib and pyqt5, some of the issues seem to have been transitory (ie affecting just one or a couple specific versions) I think I ran into an issue the other day for some portion of matplotlib that needed the execution bit set (similar to the write bit I mention in point 3 above) i had to copy the entire python library to a new directory and do a chmod +x on my file and point cx_Freeze to that. (might have been the ldd step?)

If someone does a chmod 400 to their python directory I think cxfreeze should still work on it so it can do a chmod +w or chmod +x as needed on the files after it copies them. 

I apologize for lack of better information, i've spent days doing ldd/readelf -d on files and sometimes using more complex methods to tease out how to link everything so it works and its complex and involves a large number of files, at which point I don't have time to try and boil things down to a simple case :( 

Hard for me to say if the seg fault is from patchelf or something else, I get similar seg faults if files are not linked correctly. I can always rerun patchelf afterwards to fix things, but I'd rather not. Having the ability to turn it off would also allow me to see if it is patchelf causing the problem or if its independent of that.

**Comment by marcelotduarte** [comment]
As I said before:
> When I decided to include patchelf in cx-freeze, I even thought of something like your option 1. Use if installed.
The problem was that I had to help a lot of people with issues and that were directly connected to rpath. As most large packages use manylinux and consequently use patchelf to tune rpath, I saw the need to tweak it again for cx-freeze.

Some of the packages that I remember is numpy, pillow, pyzmq, ... that is distributed using manylinux and use patchelf, so I decide to use it too, because what cx-freeze does is a distribution of various packages in an app.

numpy uses patchelf in manylinux, but if you compile it from sources, it doesn't use patchelf. Do you compile it from sources?

In older versions of patchelf I already saw reports of segfaults. But with v 0.12 it is more stable. I know that CentOS does not have patchelf in its distribution, then, how do you install it? Do you compile it from source like described [here](https://cx-freeze.readthedocs.io/en/latest/installation.html#requirement-for-linux)?

Is your python compiled from sources or compiled with configure option --with-lto?

**Comment by marcelotduarte** [comment]
> If someone does a chmod 400 to their python directory I think cxfreeze should still work on it so it can do a chmod +w or chmod +x as needed on the files after it copies them.

I think that issue #659 and rejected PR #661 are related.

**Comment by Fox214** [comment]
I've run into issues with older patchelf (and 0.12) but the new version has definitely fixed some of those bugs. Also sorry if I wasn't clear the more common reason I've seen patchelf create seg faults is not because patchelf did the something wrong, but because the user told patchelf to link files in a manner that will not work, sometimes you get a stderr message stating if can't find an .so file (easy enough to fix) but sometimes it just core dumps. (and some times those can be analyzed and sometimes they cannot). Also if it was not clear my entire paragraph was a relatively short summation of my tinkering with patchelf over several years. I think I built 0.12 from source initially to work around a bug I was having with 0.8, but eventually my IT group installed it and I deleted the version I built. 

Yes my python was built with "-with-lto" (at least on linux, we have powerPC too, not sure about that version) and all the modules are installed with pip (I do occasionally need to build something but I think recent versions of most modules and pip have worked out) 

Regarding the file permissions: right now it seems the program is failing if its not set correctly (execute for ldd, write for patchelf), and there does not seem to be away to fix it other than copying read only files so you own them and changing them ahead of time. I think any of the following would be an improvement:
1. if a mode needs set check if it is and do it if its not
2. if a mode needs to be set just do it
3. if a mode needs to be set check for it and skip the operation if its not

1 and 2 are effectively the same thing although one of them may perform better (alternatively it could be a setup option if there was some concern about automatically doing this). 3 could obviously cause things to not work correctly, but its may be possible to fix in the build process (it may depend which file/how as well), but having it not being able to run at all is not a good position.

**Comment by marcelotduarte** [comment]
> I think I built 0.12 from source initially to work around a bug I was having with 0.8, but eventually my IT group installed it and I deleted the version I built.

Please try to install like described [here](https://cx-freeze.readthedocs.io/en/latest/installation.html#requirement-for-linux) to  to rule out this possibility. It will take a minute.

> Yes my python was built with "-with-lto"

In issue #1132 it gave segfault but it didn't give indications of using lto, but when I saw that it was using lto, I realized that this could be the problem.
Please test the new beta version to rule out this possibility.
pip install cx-freeze==6.8b1

Please try it out and report. If fails try to debug or show me traceback, logs, etc like the guy did at #1132.
I'll try to use a docker to simulate some operations (to be honest I use a docker with centOS6 for some tests with samples from cx-freeze. I'm going to make one with centOS7). Send me a output of:
python -m sysconfig

> Regarding the file permissions

I'll read this part in the next step.

**Comment by Fox214** [comment]
Sorry it will likely be a couple of weeks before I will have time to test any of this, but I will try and get to it and provide feedback.

**Comment by Fox214** [comment]
Ok so trying to look at this:
1. using 6.5.2 everything works fine
2. patchelf is failing the bootstrap:
 autoreconf: cannot create /tmp/11246762.1.q/ar8939.11387: No such file or directory

I will try 6.8b1 tomorrow most likely

**Comment by marcelotduarte** [comment]
Try 6.8b2 that has more fixes.
pip install cx-freeze==6.8b2

**Comment by Fox214** [comment]
8b1 nominally worked for me, I've not ran anything complex nor investigated any details.

**Comment by Fox214** [comment]
8b2 I'm having issues with:
Traceback (most recent call last):
  File ".../CPython/3.8.2/linux64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 1053, in _post_copy_hook
    relative = dependent_file.relative_to(source_dir)
  File ".../CPython/3.8.2/linux64/lib/python3.8/pathlib.py", line 899, in relative_to
    raise ValueError("{!r} does not start with {!r}"

ValueError: '.../lib64/libstdc++.so.6' does not start with' .../CPython/3.8.2/linux64/lib/python3.8/site-packages/matplotlib/backends'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 635, in <module>
    setup(  name =...
  File "...CPython/3.8.2/linux64/lib/python3.8/site-packages/cx_Freeze/dist.py", line 447, in setup
    setuptools.setup(**attrs)
  File ".../CPython/3.8.2/linux64/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "../CPython/3.8.2/linux64/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File ".../CPython/3.8.2/linux64/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File ".../CPython/3.8.2/linux64/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File ".../CPython/3.8.2/linux64/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File ".../CPython/3.8.2/linux64/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File ".../CPython/3.8.2/linux64/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File ".../CPython/3.8.2/linux64/lib/python3.8/site-packages/cx_Freeze/dist.py", line 317, in run
    freezer.Freeze()
  File ".../CPython/3.8.2/linux64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 623, in Freeze
    self._write_modules(library_zip, finder)
  File ".../CPython/3.8.2/linux64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 546, in _write_modules
    self._copy_file(
  File ".../CPython/3.8.2/linux64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 175, in _copy_file
    self._post_copy_hook(
  File ".../CPython/3.8.2/linux64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 1062, in _post_copy_hook
    relative = file.relative_to(targetdir)
  File ".../CPython/3.8.2/linux64/lib/python3.8/pathlib.py", line 899, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: 'lib-linux64/lib/matplotlib/libstdc++.so.6' does not start with 'lib-linux64/lib/matplotlib/backends'

**Comment by Fox214** [comment]
I went back and redid it with 8b1, if I set LD_LIBRARY_PATH before hand, the files are wrong (not sure if they would work on another network) but everything tested ok on the current network.

If I do not set LD_LIBRARY_PATH i had to fiddle with a couple things, but I got it to work, and the results of the RPATH's look reasonable. 

Both passed all my regressions.

**Comment by marcelotduarte** [comment]
PR #1181 and #1201 changed this a bit. In my test #1201 is necessary in py36/37.
I see you use matplotlib. Will you be able to create a sample so that I can reproduce this error that you had in the [previous comment](https://github.com/marcelotduarte/cx_Freeze/issues/1171#issuecomment-901881667) and try to figure out the logic in this case?
What is the backend you're using with matplotlib?

If I understood, in summary:
6.5.2 ok
6.6,6.7 fail
6.8b1 fail
6.8b1 with LD_LIBRARY_PATH fail
6.8b1 without LD_LIBRARY_PATH ok
6.8b2 fail?

**Comment by Fox214** [comment]
I can see if I can come up with a small sample to do the matplot lib issue.

6.5.2 ok
6.6,6.7 fail
6.8b1 pass with both, with LD_LIBRARY_PATH the RPATHs are wrong, (because LD_LIBRARY_PATH was absolute) so not sure what happens if I move the code (within network or off network) if its extraneous paths it may still be ok) it appears I do not need to set this during compile 
6.8b2 fail (matplot lib issues)

**Comment by marcelotduarte** [comment]
I released a new beta today.
pip install cx-Freeze==6.8b4

**Comment by marcelotduarte** [comment]
And new with PR #1232 
pip install cx-Freeze==6.8b5

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.

**Comment by Fox214** [comment]
I was able to get 6.8 to work. Sorry busy with other stuff last few weeks. (it does fail if I set LD_LIBRARY_PATH, but is ok without it)

I assume you do not need a testcase for matplotlib now?

**Comment by marcelotduarte** [comment]
LD_LIBRARY_PATH should work if use a different [init_script](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cx-freeze-executable) ConsoleSetLibPath

> I assume you do not need a testcase for matplotlib now?

Yes, please open a new issue.
