### ISSUE TITLE
Building an executable with requested Admin privileges

### ISSUE THREAD

**Issue by OmerFI** [marcelotduarte/cx_Freeze#1188]
Is there any way to pass an option that will request elevation upon application restart? (like pyinstaller's --uac-admin option)
If not, can anybody work on it to improve this library

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.10](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.10) has just been released.

**Comment by OmerFI** [comment]
Thanks a lot!
