### ISSUE TITLE
ImportError when running sample setup.py with cx_Freeze 6.7

### ISSUE THREAD

**Issue by itsupera** [marcelotduarte/cx_Freeze#1191]
**Describe the bug**
When executing `python3 setup.py` for the PyQt5 sample, raise the following exception:
```
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    from cx_Freeze.hooks import get_qt_plugins_paths
ImportError: cannot import name 'get_qt_plugins_paths' from 'cx_Freeze.hooks' (/home/itsupera/repos/cx_Freeze/venv/lib/python3.8/site-packages/cx_Freeze/hooks.py)
```

**To Reproduce**
```
git clone https://github.com/marcelotduarte/cx_Freeze.git
cd cx_Freeze
virtualenv -p python3 venv
source venv/bin/activate
pip install --upgrade cx_Freeze
cd cx_Freeze/samples/pyqt5
python3 setup.py
```
It does work for the current beta version though (version 6.8b1), after running `pip install --upgrade cx_Freeze --pre` it did not raise an exception anymore.

**Expected behavior**
Should not raise an exception but print the usage.

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information: Ubuntu Linux 20.04.2
 - OS architecture: amd64
 - cx_Freeze version: 6.7
 - Python version: 3.8.10

**Comment by marcelotduarte** [comment]
This sample is for future 6.8 version
For 6.7 version the sample is in: https://github.com/marcelotduarte/cx_Freeze/tree/6.7/cx_Freeze/samples

If you want to test with cx_Freeze 6.8:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main`

**Comment by itsupera** [comment]
Ah my bad, I did not think it would be different.

Thank you for your great work !

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
