### ISSUE TITLE
[debug] disable symbol stripping when building with `--debug`

### ISSUE THREAD

**Issue by bartoszek** [marcelotduarte/cx_Freeze#1194]
Just notice a small caveat, when trying to build with `python setup.py build --debug` the resulting `Console` binary has stripped debug symbols. This is caused by including `-s` switch in CFLAGS here:
https://github.com/marcelotduarte/cx_Freeze/blob/9a9cf3050c82be370498aa6cc79fe69ad93a7160/setup.py#L98
Would be nice to escape it with `if self.debug` to preserve default behaviour of the `--debug` switch in `setuptools:build_ext`

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
