### ISSUE TITLE
Failed to find module in subpackage in zipped egg

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#120]
Originally reported by: **Martin Pengelly-Phillips (Bitbucket: [martinpengellyphillips](https://bitbucket.org/martinpengellyphillips), GitHub: [martinpengellyphillips](https://github.com/martinpengellyphillips))**

----------------------------------------

It seems that cx-freeze fails to find modules in subpackages when the package is part of a zipped egg (tested using cx-freeze 4.3.3 on Windows 8).

For example, cx-freeze will find `foo.bar` (where *foo* is a package and *bar* is a module) in a zipped egg just fine. However, `foo.baz.bim` will fail to find module *bim* in the subpackage *baz*.

Digging into the code it seems that it is down to a path mismatch. The zip cache normalises the stored path, but the finder does not. This leads to lookups like:

`C:\Users\martin\data\python_virtualenv\cxfreeze_test\lib\site-packages\foo-0.1.0-py2.7.egg\foo/baz, __init__`

Here it seems the forward slash causes the lookup to fail.

Adding a normpath call to the top of the `ZipModulesCache.find` method solves it for me:
```python

class ZipModulesCache(object):
    """A cache of module and package locations within zip files."""
    def __init__(self):
        # filename -> None (used like a set)
        self.files_seen = {}
        # (path, modulename) -> module_details
        self.loadable_modules = {}
    
    def find(self, path, modulename):
        """Find a module in the given path.
        
        path should be a string referring to a zipfile or a directory in a
        zip file. If it is outside a zip file, it will be ignored.
        
        modulename should be a string, with only the last part of the module
        name, i.e. not containing any dots.
        
        If the module is found, this returns information in the same format
        as :func:`imp.find_module`. Otherwise, it returns None.
        """
        path = os.path.normpath(path)
        try:
            return self.retrieve_loadable_module(path, modulename)
        except KeyError:
            pass

        if path in self.files_seen:
            return None

        # This is a marker that we've seen it, whether or not it's a zip file.
        self.files_seen[path] = None

        if os.path.isfile(path) and zipfile.is_zipfile(path):
            self.cache_zip_file(path)
            try:
                return self.retrieve_loadable_module(path, modulename)
            except KeyError:
                return None
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/120

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Make it into a pull request

**Comment by anthony-tuininga** [comment]
*Original comment by* **Rafael Bertoldi (Bitbucket: [fogo_](https://bitbucket.org/fogo_), GitHub: Unknown)**:

----------------------------------------

I've been a victim of same issue. I've created a PR [here](https://bitbucket.org/anthony_tuininga/cx_freeze/pull-requests/90/)

**Comment by guettli** [comment]
Is there a reason why this was not merged?

**Comment by native-api** [comment]
Ppl report being hit by this issue at StackOverflow, too: https://stackoverflow.com/questions/42609043/cx-freeze-cannot-find-pkg-resources

**Comment by marcelotduarte** [comment]
Assuming this has been resolved.
If you had issues please re-open.
