### ISSUE TITLE
error: zipimport.ZipImportError: can't find module 'myscript__main__'

### ISSUE THREAD

**Issue by AlexWang516** [marcelotduarte/cx_Freeze#1203]
I'm experiencing an issue when trying to use `cx_Freeze:6.7` againt `python 3.9.6` on windows 10.

I just using `if __name__ == "__main__:"` in my main script `myscript.py`.
The `setup.py` I use is:

```
import sys
import cx_Freeze
import pathlib

baseDir = pathlib.Path(__file__).parent

build_exe_options = {"include_files":[baseDir.joinpath("resources"), baseDir.joinpath("viewerConf.json")], "include_msvcr":True}


base = None
if sys.platform == "win32":
    base = "Win32GUI"

cx_Freeze.setup(name = "myScript",
       version = "0.1",
       description = "My Script",
       options = {"build_exe": build_exe_options},
       executables = [cx_Freeze.Executable(baseDir.joinpath("myscript.py"), base=base, icon=str(baseDir.joinpath("myScript.ico")))]
)
```
When I run the generated executable file. The error is:
```
Traceback (most recent call last):
  File "C:\software\Python\Python39\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
    module_init.run(name + "__main__")
  File "C:\software\Python\Python39\lib\site-packages\cx_Freeze\initscripts\Console.py", line 12, in run
    code = __loader__.get_code(name)
  File "<frozen zipimport>", line 159, in get_code
  File "<frozen zipimport>", line 721, in _get_module_code

zipimport.ZipImportError: can't find module 'myscript__main__'
```

My environment is:
- Windows 10
- amd 64
- cx_Freeze: 6.7
- Python version: 3.9.6

The same python script and setup.py works fine at cx_Freeze: 6.3 and python 3.8.

**Comment by marcelotduarte** [comment]
Can you test with the beta [cx_Freeze 6.8b2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8b2).
Please, try it out and report. It has support for pathlib.
pip install cx-Freeze==6.8b2

**Comment by AlexWang516** [comment]
> Can you test with the beta [cx_Freeze 6.8b2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8b2).
> Please, try it out and report. It has support for pathlib.
> pip install cx-Freeze==6.8b2

cx_Freeze 6.8b2 works fine.
Thank you @marcelotduarte

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
