### ISSUE TITLE
Consider using modulegraph to find module dependencies

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#123]
Originally reported by: **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**

----------------------------------------

I noticed that py2app uses a package called [modulegraph](https://pypi.python.org/pypi/modulegraph/) to locate dependencies. We should consider ripping out cx_Freeze.finder, which does the same thing, and adding a dependency on modulegraph instead, so that we don't have to maintain that rather tricky code.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/123

**Comment by marcelotduarte** [comment]
No.
