### ISSUE TITLE
Versions >= 6.6 do not copy libffi.so even if listed in include_files

### ISSUE THREAD

**Issue by schooft** [marcelotduarte/cx_Freeze#1239]
I don't know if the file should be copied automatically, but I would expect that all files specified in `include_files` are copied.

**To Reproduce**
```
$ cat demo.py 
import ctypes
```
```
$ cat setup.py 
from cx_Freeze import setup, Executable
build_exe_options = {
    "include_files":[("/usr/lib/x86_64-linux-gnu/libffi.so.7", "lib/libffi.so.7")],
    "excludes": ["tkinter"]}
setup(
    name = "demo",
    version = "0.1",
    description = "My demo application!",
    options = {"build_exe": build_exe_options},
    executables = [Executable("demo.py")]
)
```
```
$ cat Dockerfile 
FROM python:3.7 as builder

RUN apt-get update && \
    apt-get install -y patchelf

RUN python -m pip install -U importlib-metadata wheel
# RUN python -m pip install cx_freeze==6.5
RUN python -m pip install cx_freeze==6.6

WORKDIR /code
COPY . .

RUN python setup.py build_exe

RUN ls -l /code/build/* /code/build/*/lib
RUN ldd /code/build/*/lib/_ctypes*

CMD ["bash", "-c", "[[ -f build/exe.linux-x86_64-3.7/lib/libffi.so.7 ]] && echo exists || echo missing"]
```
```
$ docker build -t libffi .
$ docker run --rm libffi
missing
```

**Expected behavior**
File `llibffi.so.7` is copied to the build directory.

**Desktop (please complete the following information):**
 -  Platform information: python:3.7 docker image on Debian 9
 -  OS architecture: amd64
 -  cx_Freeze version: 6.6 to 6.8
 -  Python version: 3.7

**Additional context**
It is easy to workaround the problem by copying the file manually.

**Comment by marcelotduarte** [comment]
Instead of include_files, you should use bin_includes:
"bin_includes": "libffi.so.7",

**Comment by schooft** [comment]
Thanks, `bin_includes` works perfectly, even without specifying the library version.

The FAQ should probably be updated. It says
>  List compiled libraries (.dll or .so files) in the `include_files` option.

Maybe a warning that references `bin_includes` could be logged if files listed in `"include_files"` are skipped as that is a bit surprising. Otherwise, the issue can be closed.

**Comment by marcelotduarte** [comment]
The faq should be updated then. That is the case where the files are within the module. When they are from the system, bin_* is the correct to bypass some checks.
See https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-bin_includes

**Comment by marcelotduarte** [comment]
Documentation updated: https://cx-freeze.readthedocs.io/en/latest/faq.html#problems-with-running-frozen-programs
