### ISSUE TITLE
cx_freeze does not include modules started with digits

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#124]
Originally reported by: **Andrey Santanna (Bitbucket: [andreysantanna](https://bitbucket.org/andreysantanna), GitHub: Unknown)**

----------------------------------------

Django migration modules, such as** 0001_initial.py** are not processed by ModuleFinder.

This affects both python 2.X and 3.X implementations.

on finder.py

```
#!python

try:
    isidentifier = str.isidentifier  # Built in method in Python 3
except AttributeError:
    # Check with regex for Python 2
    _identifier_re = re.compile(r'^[a-z_]\w*$', re.I)
    def isidentifier(s):
        return bool(_identifier_re.match(s))
```

Should be replaced with:

```
#!python

_identifier_re = re.compile(r'^[a-z_0-9]\w*$', re.I)
def isidentifier(s):
     return bool(_identifier_re.match(s))

```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/124

**Comment by anthony-tuininga** [comment]
*Original comment by* **Giric Goyal (Bitbucket: [giricgoyal](https://bitbucket.org/giricgoyal), GitHub: [giricgoyal](https://github.com/giricgoyal))**:

----------------------------------------

I too encountered the problem with django's migration module. When I run my exe, it gives me FileNotFoundError at .zip/django/contrib/admin/migrations. When i looked at th directory and compared it with system installed django, found that 0001_initial.pyc was missing.
Do we have a fix for this yet? Or the workaround that you mentioned worked?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Giric Goyal (Bitbucket: [giricgoyal](https://bitbucket.org/giricgoyal), GitHub: [giricgoyal](https://github.com/giricgoyal))**:

----------------------------------------

I still have that FileNotFoundError after I applied these changes. But now I have the file in my directory.

Unhandled exception in thread started by <function check_errors.<locals>.wrapper
 at 0x035E05D0>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\utils\autoreload.py", line 223, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python34\lib\site-packages\django\core\management\commands\runserver.
py", line 112, in inner_run
    self.check_migrations()
  File "C:\Python34\lib\site-packages\django\core\management\commands\runserver.
py", line 164, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "C:\Python34\lib\site-packages\django\db\migrations\executor.py", line 19
, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Python34\lib\site-packages\django\db\migrations\loader.py", line 47,
in __init__
    self.build_graph()
  File "C:\Python34\lib\site-packages\django\db\migrations\loader.py", line 174,
 in build_graph
    self.load_disk()
  File "C:\Python34\lib\site-packages\django\db\migrations\loader.py", line 91,
in load_disk
    for name in os.listdir(directory):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\
Workspaces\\work\\Deploy\\applePie\\deploy\\appServer\\library.zip\\django\\cont
rib\\admin\\migrations'

**Comment by anthony-tuininga** [comment]
*Original comment by* **Andrey Santanna (Bitbucket: [andreysantanna](https://bitbucket.org/andreysantanna), GitHub: Unknown)**:

----------------------------------------

This may be solved with the resolution of issue #79, but I can't confirm right now

**Comment by anthony-tuininga** [comment]
*Original comment by* **Andrey Santanna (Bitbucket: [andreysantanna](https://bitbucket.org/andreysantanna), GitHub: Unknown)**:

----------------------------------------

This issue, i mean https://bitbucket.org/anthony_tuininga/cx_freeze/pull-requests/79/re-allow-including-modules-with-non/diff

**Comment by marcelotduarte** [comment]
Assuming this has been resolved.
