### ISSUE TITLE
MSI installer issue when upgrading

### ISSUE THREAD

**Issue by marcelotduarte** [marcelotduarte/cx_Freeze#1243]
### Discussed in https://github.com/marcelotduarte/cx_Freeze/discussions/1242

<div type='discussions-op-text'>

<sup>Originally posted by **phil245** September 11, 2021</sup>
Just to clarify I am using an upgrade code/UUID to allow for new installer to remove the previous version without the need for the user to remove serveral installed versions of one program.
After compiling my code into an msi installer, it will install perfectly fine, however if I update the program and compile a new msi installer and install that with the program already on my system, it goes through the removal and installation ok but does not put the executable file into the installation folder.
If I run the installer again and choose the repair option, it will install the executable file.

I want make it clear this has only been an issue since updating cx_freeze to 6.8, I have rolled back to version 6.5.3 and it works fine as it did before.
I am using Python 3.8.10 on Windows 10 and have tried the installers on serveral Windows machines all with the same result.
One other thing of note, the older cx_freeze version creates a msi installer with a suffix of -amd64 and 6.8 with -win64. I'm unsure if this is relevant or helpful.

I will try with the other versions of cx_freeze to narrow down if it is only with 6.8.

I'm unsure if anyone else has this issue. From the research I have done I cannot find any reasons why this happens or how to fix it.</div>

**Comment by marcelotduarte** [comment]
@phil245 I converted to issue.
Please, test with 6.6 and 6.7 to and report. Maybe we have to check with some betas to test what is the patch that introduced the regression.
I imagine the regressions could have happened between 6.7 and 6.8 anyway because there were more changes.
This name change was one last thing I did I think you can try renaming the file in the old format to see if it's the cause.

**Comment by phil245** [comment]
There is another slight issue i have found with cx_freeeze 6.8.
It doesn't always include all packages, everything that comes with python was not an issue, but I would have to explicitly include certain packages such as 'PIL and 'pystray' to name a couple.
I will confirm if this is still an issue, but may not have been an issue with 6.5.3

**Comment by phil245** [comment]
I have tested version6.5.3 which is fault free.
Version 6.6 is fault free.
Version 6.7 and 6.8 have the issue when upgrading it does not install the executable, running the installer again, and doing a repair installs the exectuable.
The issue with the packages not being installed is not an issue, it was only 'pystray' that was an issue, but including the package in the setup file solves that.

**Comment by marcelotduarte** [comment]
> but I would have to explicitly include certain packages such as 'PIL and 'pystray' to name a couple.

I have a test with PIL and it works without includes/packagesm but I'll check it.

> Version 6.7 and 6.8 have the issue when upgrading

Can you check with the pre-releases?

pip install cx_Freeze==6.7b1

6.7b1 to b8 if I remenber. When it fails you can stop and report (if the fails is related) and I'll check in the sources a change that can be the cause...

**Comment by phil245** [comment]
@marcelotduarte I have just tried it with cx_freeze 6.7b1 and the issue is present.

**Comment by marcelotduarte** [comment]
Between 6.6 (Apr 14) to 6.7b1 (May 23) has 5 PRs. I think that the first 2 may be the cause. PR #1032 and #1024
The other 3 are most cosmetic: #1055 #1056 #1057
Can you take a look at the code and explanation to see if see any change that can be conflicting with your code?

**Comment by marcelotduarte** [comment]
@phil245 A new issue #1250 points the #1032 as the cause of this bug. I think you should participate in that discussion to help us to fix this issue, and I close this issue.

**Comment by Cimbali** [comment]
It would be interesting to confirm this is the same bug exactly.
@phil245 can you inspect the executables (as in right click > properties) that are installed and report any version / date / language metadata ? And also tell us which are missing ?

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.8.1](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8.1) has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
@phil245 If you had issues please open a new issue.
@Cimbali Thanks!
