### ISSUE TITLE
[Errno 13] Permission denied on MacOS Big Sur

### ISSUE THREAD

**Issue by cedk** [marcelotduarte/cx_Freeze#1249]
Building a GTK application on Big Sur generate this error:
`error: [Errno 13] Permission denied: '/Users/ced/tryton/build/exe.macosx-11-arm64-3.9/lib/cairo/_cairo.cpython-39-darwin.so'`
But the same script on Catalina is working correctly.

**Comment by marcelotduarte** [comment]
Remove the directory `/Users/ced/tryton/build/exe.macosx-11-arm64-3.9` and try again.
Another possibility is that the file _cairo* in this system is write-protected. Check if the source of the file is read-only and report.

**Comment by cedk** [comment]
Indeed if I make the source files on the system (from homebrew), the build can continue. I had to do that for `_cairo.cpython-39-darwin.so`, `_gi.cpython-39-darwin.so` and `_gi_cairo.cpython-39-darwin.so`.
But then the result application can not be run because of `EXC_BAD_ACCESS (Code Signature Invalid)` when dlopen one of those library.
I guess it is because cx_freeze modify them.

So there are two issues:
* If cx_freeze needs to modify some libraries, it should change the mode to be writable.
* If cx_freeze is modifying a signed library, it should probably create a new signature?

**Comment by cedk** [comment]
I created https://github.com/marcelotduarte/cx_Freeze/pull/1251 to apply an ad-hoc signature to the modified libraries.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.8.1](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8.1) has just been released.
