### ISSUE TITLE
Deprecations of distutils and bdist_msi and bdist_rpm in setuptools

### ISSUE THREAD

**Issue by Cimbali** [marcelotduarte/cx_Freeze#1254]
Just to make you aware of this deprecations and maybe discuss what could need to be done:
- [PEP 632 deprecates the distutils module](https://www.python.org/dev/peps/pep-0632/)
- setuptools commands such as `bdist_msi` that are extended by cx_Freeze (and maybe others like `bdist_dmg`) are [being deprecated](https://github.com/pypa/setuptools/issues/1988#issuecomment-927109818) in setuptools

**Comment by marcelotduarte** [comment]
I'm aware. I referenced it in PR #1195. But in #1055, #1196, and possibly others, I've been changing some code.

> setuptools commands such as `bdist_msi` that are extended by cx_Freeze (and maybe others like `bdist_dmg`) are [being deprecated](https://github.com/pypa/setuptools/issues/1988#issuecomment-927109818) in setuptools

Before the release of python 3.11 (in a year) I plan to include this code in cx_Freeze. I intend to port the code that works today on python 3.8 (which doesn't have the deprecations of py 3.9). We have to check the license.

**Comment by marcelotduarte** [comment]
Recently I merged bdist_rpm and bdist_msi in the code base of cx_Freeze. Also, I made various changes to get rid of distutils calls.
