### ISSUE TITLE
When you freeze a python http server , it does not  responds to request .

### ISSUE THREAD

**Issue by Dennis-Asamoah** [marcelotduarte/cx_Freeze#1262]
I wrote a simple python http server to serve the files(folders) of the present working directory.

```
import socketserver
http=''
def httpServer(hostIpAddress):
  global  http
  socketserver.TCPServer.allow_reuse_address=True
  try:
    with  socketserver.TCPServer((hostIpAddress,22818),SimpleHTTPRequestHandler) as http:
       print(1123)
       http.serve_forever()
 except Exception as e:
     print(str(e))
       

if __name__ == '__main__':
     httpServer('192.168.1.2')    
  
```
this code works as expected .It serves the contents. However when i Freeze it (convert ist to executable) using cx-freeze . It does not serve the files .IN chrome it outs ERR_EMPTY_RESPONSE. I tried other browsers but to no avail.

My setup.py for the freeze is
```
executables = [
    Executable("test_http.py", base=base,target_name="test_http",shortcutName="test_http",shortcutDir="DesktopFolder")
]

setup(
    name="test_http",
    options={"build_exe":build_exe_option,"bdist_msi":bdist_msi_options},
    executables=executables
    )
```
The .exe works without any error and you can even see the program running in task manager but  the http server doesn't work.

cx-freeze(i tried version 6.6,6.7,6.8)
 python 3.7.7 32 bits 
os : windpows 8.1

**Comment by marcelotduarte** [comment]
What is the value of `base`?
In the example in [documentation](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#setup-script):
```
# base="Win32GUI" should be used only for Windows GUI app
base = None
if sys.platform == "win32":
    base = "Win32GUI"
```
In your case, this is a Console app, so remove it or use base=None

**Comment by Dennis-Asamoah** [comment]
@marcelotduarte  thank  you for the response. The reason why i did base=="Win32GUI" , is because this piece of code is part of a gui app. The entire app works without any problem, except the http  part which doesn't. So during the debug process , i seperated that part of code to test it . So that is why i still maintained the win32GUI.

However  upon your recommendation , i changed the base to None and it worked. But like i said that part of code is a part of a gui app.So what should i do in this case ?

thank you .

**Comment by Dennis-Asamoah** [comment]
I  would be very grateful if you can give me a time of your busy schedule and help me out ,is really important.
    On Friday, October 8, 2021, 02:40:51 AM GMT+1, Marcelo Duarte ***@***.***> wrote:  
 
 


What is the value of base?
In the example in documentation:
# base="Win32GUI" should be used only for Windows GUI app
base = None
if sys.platform == "win32":
    base = "Win32GUI"

In your case, this is a Console app, so remove it or use base=None

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by marcelotduarte** [comment]
Well, I don't know what other modules you use, for example, if you use multiprocess, thread, etc.
I think of two suggestions:
1) When you use it directly via python, the program runs, because in the background, python starts in console mode. So if you redirect sys.stdout and sys.stderr to a file before running this code, it should work.
2) Create two executables. One as Win32GUI and one as Console. cx_Freeze allows this, it's more work but it's guaranteed. Like:
```
executables = [
    Executable("test_http.py", target_name="test_http"),
    Executable("test_gui.py", base=base,target_name="test_gui",shortcutName="test_gui",shortcutDir="DesktopFolder"),
]
```
Then, in part of the code that calls the test_http code, you use a code like:
```
if getattr(sys, "frozen", False):
    # The application is frozen
    frozendir = os.path.dirname(sys.executable) # if you need to fix the path
    subprocess.call(["test_http"])
else:
    # normal call
```

**Comment by Dennis-Asamoah** [comment]
This worked for me . Instead of a using it as a function i  used it as class .
Even if base==Win32Gui
it still works
@marcelotduarte  thank you.

```
import http.server
import threading
import functools
import time
 
# Example simple http server as thread
 
class SilentHandler(http.server.SimpleHTTPRequestHandler):
    
    def log_message(self, format, *args, **kwargs):
        # do any logging you like there
        pass
    
class MyHttpServerThread(threading.Thread):
    
    def __init__(self, address=("0.0.0.0",8000), target_dir="."):
        super().__init__()
        self.address = address
        self.target_dir = "."
        self.server = http.server.HTTPServer(address, functools.partial(SilentHandler, directory=self.target_dir))
        self.start()
 
    def run(self):
        self.server.serve_forever(poll_interval=1)
 
    def stop(self):
        self.server.shutdown() # don't call from this thread
        
# test  
 
if __name__ == "__main__":
    http_server = MyHttpServerThread()
    time.sleep(10)
    http_server.stop()
    print("done")
```

**Comment by marcelotduarte** [comment]
You're using threading. It's a good solution.
