### ISSUE TITLE
Start to support Python 3.10

### ISSUE THREAD

**Issue by DiddiLeija** [marcelotduarte/cx_Freeze#1266]
Python 3.10 has been released [a few days ago](https://www.python.org/dev/peps/pep-0619/#schedule). I have noticed that some users are using Python 3.10, and want to use `cx_Freeze` on it. But as I can see, [it is not supported yet, according to the docs](https://cx-freeze.readthedocs.io/en/latest/).

I know this will mean a large process of adoption, just want to remind you :) Also, Python 3.10 deprecates the `distutils` module, so it will probably mean a few problems.

**Comment by marcelotduarte** [comment]
> Python 3.10 has been released

I tested cx_Freeze with python 3.10rc1 with a few samples because a limited support of libraries. For example, pandas doesnot work yet, but using numpy works. I think in two month or less I should declare experimental support for python 3.10

> Also, Python 3.10 deprecates the `distutils` module,

See #1254

**Comment by DiddiLeija** [comment]
> I tested cx_Freeze with python 3.10rc1 with a few samples because a limited support of libraries. For example, pandas doesnot work yet, but using numpy works. I think in two month or less I should declare experimental support for python 3.10

Estupend! Thanks for the quick response!

> See #1254

Yeah, I read that issue before, and I'll be paying attention to it.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.9](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.9) has just been released.
pip install --upgrade cx_Freeze
