### ISSUE TITLE
Native namespace packages are always freezed into library.zip

### ISSUE THREAD

**Issue by IvanKosik** [marcelotduarte/cx_Freeze#1276]
**Describe the bug**
Native namespace packages [PEP 420](https://www.python.org/dev/peps/pep-0420/) are always freezed into library.zip. When some package is freezed into *.zip, then it has no their data-files (but when package is not native namespace package, then all is good: project is not zipped and has their data-files).

**To Reproduce**
Prepare python environment: install e.g. ruamel.yaml (version 0.17.16) or other native namespace package (parent folder of such package does not contain __init__.py file).
Then create such script to freeze into *.exe:
```
import sys
from pathlib import Path
from cx_Freeze import setup, Executable

FILE_DIR = Path(__file__).parent
BUILD_DIR = FILE_DIR / 'build'

build_exe_options = {
    'build_exe': BUILD_DIR,
    'packages': [
        'ruamel.yaml'
    ]
}

app_base = 'Win32GUI' if sys.platform == 'win32' else None
setup(
    name='cx_Freeze Tester',
    options={
        'build_exe': build_exe_options,
    },
    executables=[Executable(
        FILE_DIR / 'main.py',
        base=app_base,
    )]
)
```

We will get our namespace package here:
build\lib\library.zip\ruamel

**Expected behavior**
Our namespace package have to be here:
build\lib\ruamel
Because we did not set the _--zip-include-packages_ option for this package.

**Desktop:**
 - Platform information: Windows 10
 - OS architecture: amd64
 - cx_Freeze version: 6.8.1
 - Python version: 3.9

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.8.4](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8.4) has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
