### ISSUE TITLE
`sys.stdout` is `None`

### ISSUE THREAD

**Issue by tufbel** [marcelotduarte/cx_Freeze#1288]
I used `loguru` instead of default `logging`.
My `settings.py` file reads like this:
```python
from loguru import logger

LOGGER_CONFIG = {
    "handlers": [
        {
            "sink": sys.stdout,
            "level": "DEBUG" if DEBUG else os.getenv("LOG_LEVEL", "info").upper(),
            "enqueue": True,
            "backtrace": True,
            "diagnose": True,
            "catch": True
        },
        {
            "sink": PROJECT_DIR.joinpath("logs/project.log"),
            "rotation": "3 MB",
            "retention": "30 days",
            "level": "INFO",
            "enqueue": True,
            "backtrace": True,
            "diagnose": True,
            "encoding": "utf-8",
            "catch": True
        },
    ]
}

logger.configure(**LOGGER_CONFIG)
```
The program works fine when I use `python settings.py`. 

But after I build it through cx_Freeze, it will show an `TypeError` at line 824 of `_logger.py`,   because I found that `sys.stdout` was `None` when executed.

**Comment by tufbel** [comment]
I found out that `Executable("main.py", base="Win32GUI")` was the cause.
Python Docs says so:
`
Note Under some conditions stdin, stdout and stderr as well as the original values __stdin__, __stdout__ and __stderr__ can be None. It is usually the case for Windows GUI apps that aren’t connected to a console and Python apps started with pythonw.
`
What are the optional parameters of the base of `Executable()`.

**Comment by marcelotduarte** [comment]
[Executable](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cx-freeze-executable)
If you use base=None, it will run as a console app, and `sys.stdout` is set.
Maybe, an option is to set `sys.stdout` to an file in frozen mode.
```
import sys
if getattr(sys, "frozen", False):
        # The application is frozen
```

**Comment by tufbel** [comment]
> [Executable](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cx-freeze-executable) If you use base=None, it will run as a console app, and `sys.stdout` is set. Maybe, an option is to set `sys.stdout` to an file in frozen mode.
> 
> ```
> import sys
> if getattr(sys, "frozen", False):
>         # The application is frozen
> ```

ty
