### ISSUE TITLE
Universal binary support with CX_FREEZE

### ISSUE THREAD

**Issue by sikandarilyas** [marcelotduarte/cx_Freeze#1297]
Hi,
This is a question rather than an issue.

I want to know if we can create universal binaries with cx_freeze. Currently we are using cx_freeze to create executable but it seems it doesn't support universal binary for Apple M1.

Please let know if this option is supported. If yes, how can be build our executable as universal binary with cx_freeze. If not supported, then is there a plan in roadmap to support it in near future.

**Comment by marcelotduarte** [comment]
There is no plan for this feature. But I know that at some point it will be implemented. One developer can implement by sending a PR or I can receive requests and support to implement.

**Comment by marcelotduarte** [comment]
Please read this [comment](https://discuss.python.org/t/providing-binary-packages-for-apple-m1/9288/5) from a core python developer.
So if I understand correctly, if you use python from python.org or the MacPorts version that supports universal2, the files you generate will be universal2 as well.

**Comment by TechnicalPirate** [comment]
I need to look into this - one of our users has a m1 mac and our frozen apps are installing without issue - another user has a m1 and has problems - will try to remember to come back and post findings once i look into the difference between the machines. 

_( But yes my understanding was things should be backward/forward compatible with the right build environment )_

**Comment by marcelotduarte** [comment]
@TechnicalPirate I found some info.
For py38 universal binaries run only on macos 11 and up. 
For py39 it works in macos 10.9 and up for intel and macos 11 for apple silicon. The same for py310.

I'm generating wheels for 10.9, 10.14 (py36,37,38), 10.15 (py39,310), so you can check?
The site of the packages is https://marcelotduarte.github.io/packages/ 
There are packages for arm64 too, and universal2, but I cannot test it in any form.
The 10.15/10,15 packages I tested via GHA and @DiddiLeija  tested in his machine.

For the default arch run:
```
pip uninstall -y cx_Freeze
pip install --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --pre --no-cache
```
More information can be found in this [comment](https://github.com/marcelotduarte/cx_Freeze/issues/1311#issuecomment-1061144032)

CC: @cainesi @sikandarilyas @cedk

**Comment by cainesi** [comment]
I am still on an Intel mac, so I cannot test unfortunately.

**Comment by marcelotduarte** [comment]
@cainesi Can you test the if 10.9 and 10.14 versions work correctly?
And the universal wheel can be tested in intel too, as it support the 2 archs.

**Comment by cainesi** [comment]
Hi @marcelotduarte,

Sure, I can test on intel.   The only machine I have access to at the moment though is on MacOS 11, so I won't be able to check that it actually runs on the old OSXs (10.9/10.15).  Is that okay?

**Comment by marcelotduarte** [comment]
With macOS 11 you can test the 10.9, 10.15 and universal. I tested the 10.15 in a macOS 11 in GHA.
the 10.9 is the minimum deployment machine.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.11](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.11.0) has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
