### ISSUE TITLE
Duplicates of dll-files (python, VCRUNTIME140)

### ISSUE THREAD

**Issue by FreeHarry** [marcelotduarte/cx_Freeze#1304]
Since long a time I have the problem to have duplicate dll-files, comparing the application dir to the `lib` subdir.

If set `include_msvcr=False`, then only `python#.dll` is duplicated.

If set `include_msvcr=True`, `python#.dll` and `VCRUNTIME140.dll` are duplicated.

I can remove the dll's from the `lib` subdir and everything works well. Would it be possible to exclude these dll's in the `lib` subdir automatically in cx_freeze?

I use cx_freeze 6.8.4 on Windows 10.

**Comment by marcelotduarte** [comment]
I see that this can happen. I have a solution I'm testing. I saw, for example, that when copying _asyncio.pyd, it copies python39.dll to the lib. The duplicated vcruntime140.dll in the lib is on purpose.
Can you show me when python3x.dll is copied to lib?
When giving the build, post for me the line "copying" from python to lib and the previous line that usually indicates where detected. Just to find out which modules might be doing this.

**Comment by FreeHarry** [comment]
These are the "copying" lines you wanted ...

```
copying C:\Users\user\.pyvirtualenvs\general\lib\site-packages\win32\_win32sysloader.pyd -> \\VBoxSvr\Host-Dropbox\Programming\python\projects\opencadfile\build\lib\_win32sysloader.pyd
copying C:\Users\user\AppData\Local\Programs\Python\Python39\python39.dll -> \\VBoxSvr\Host-Dropbox\Programming\python\projects\opencadfile\build\lib\python39.dll
```
It seems if I import one of the modules of the package `pywin32` it results in this duplicated `python39.dll` file.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.10](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.10) has just been released.
