### ISSUE TITLE
Editing Windows App Manifest

### ISSUE THREAD

**Issue by harshdeepsehgal** [marcelotduarte/cx_Freeze#1305]
Has there been any update on this? I'm working on a project where I need to bypass UIPI on windows and set DPI awareness. Both can be set only in the manifest.

### Discussed in https://github.com/marcelotduarte/cx_Freeze/discussions/997

<div type='discussions-op-text'>

<sup>Originally posted by **AdarshSrikanth** April  5, 2021</sup>
I'm trying to set compatibility option to the executable built with Cx-Freeze. I'm trying to do this with the help of a windows application manifest file.

1. Is there a way to bundle the windows application manifest file to an exe built with Cx-Freeze.
2. If not, is there any other way to specify the compatibility of the application built with Cx-Freeze.</div>

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.10](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.10) has just been released.
