### ISSUE TITLE
Fatal Python error: Py_Initialize: Unable to get the locale encoding ImportError: No module named 'encodings'

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#131]
Originally reported by: **Lee Philip (Bitbucket: [lee_philip](https://bitbucket.org/lee_philip), GitHub: Unknown)**

----------------------------------------

I downloaded cx_Freeze from [here](https://bitbucket.org/anthony_tuininga/cx_freeze), installed it successfully on Ubuntu following [this thread](#32/cant-compile-cx_freeze-in-ubuntu-1304) .

After run python3 setup.py build in cx_Freeze/samples/simple,then change the dir to cx_Freeze/samples/simple/build/exe.linux-i686-3.4,run the following command ,I got the error

```
#!python

➜  exe.linux-i686-3.4  ./hello
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
[1]    3950 abort      ./hello
➜  exe.linux-i686-3.4  
```

any idea on fixing this issue ?

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/131

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

The development version of cx_Freeze does not work with the system packaged Python on Debian/Ubuntu based systems (even after you work around issue #32). That is due to [this patch](http://bazaar.launchpad.net/~doko/python/pkg3.4-debian/view/head:/patches/no-zip-on-sys.path.diff), which stops Python adding `lib/pythonXY.zip` to sys.path. Executables built by cx_Freeze rely on a zip file in that location being added to sys.path.

Workaround: build executables using another Python, e.g. the Continuum built version in [Miniconda](http://conda.pydata.org/miniconda.html), or by compiling vanilla CPython yourself.

It's not clear how this could be fixed in cx_Freeze.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Julian Rath (Bitbucket: [jrath](https://bitbucket.org/jrath), GitHub: [jrath](https://github.com/jrath))**:

----------------------------------------

I have the some problem on win32 with py352. Building in a virtualenv

**Comment by anthony-tuininga** [comment]
*Original comment by* **Dejan Stojković (Bitbucket: [dejan_](https://bitbucket.org/dejan_), GitHub: Unknown)**:

----------------------------------------

Me too. Python 3.5 x64 on Windows in virtualenv

**Comment by anthony-tuininga** [comment]
*Original comment by* **Julian Rath (Bitbucket: [jrath](https://bitbucket.org/jrath), GitHub: [jrath](https://github.com/jrath))**:

----------------------------------------

The solution is not to use `virtualenv`, but `python -m venv`. HTH

**Comment by anthony-tuininga** [comment]
*Original comment by* **Stefan Lehmann (Bitbucket: [mrleeh](https://bitbucket.org/mrleeh), GitHub: [mrleeh](https://github.com/mrleeh))**:

----------------------------------------

I tried 
```
#!bash

python -m venv 
```
to create my virtualenv like @jrath suggested and it worked. But I don't know why. What is the difference of `python -m venv` to calling `virtualenv`? And why does it affect the behaviour of cx_freeze?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Stefan Lehmann (Bitbucket: [mrleeh](https://bitbucket.org/mrleeh), GitHub: [mrleeh](https://github.com/mrleeh))**:

----------------------------------------

OK, I got it so far: venv is the successor of virtualenv and has been added to the standard library since Python 3.3. It is based on virtualenv but handles things much better. Originally it was called by the wrapper script `pyvenv` but that has been deprecated due to issues with the wrapping. Hence one should use `python -m venv` to create a virtual environment.

* [Discussion about venv on Reddit](https://www.reddit.com/r/learnpython/comments/4hsudz/pyvenv_vs_virtualenv/)
* [Python 3.6 documentation on venv](https://docs.python.org/3.6/library/venv.html#venv-def)

**Comment by anthony-tuininga** [comment]
*Original comment by* **Elliot Berman (Bitbucket: [edjubuh](https://bitbucket.org/edjubuh), GitHub: [edjubuh](https://github.com/edjubuh))**:

----------------------------------------

I ran into this issue as well, I discovered that the root issue within cx_Freeze is that `distutils.sysconfig.get_config_var("LIBDIR")`
 normally returns nothing (it's not set). When running in a virtual environment, it is set to the libs folder of the "real" Python installation directory, so all of the dependency files are placed in `build\exe.(something)\libs`, not in `build\exe.(something)`, as is the behavior without virtualenv. My workaround was to comment out [lines 626-7 of freezer.py](https://bitbucket.org/anthony_tuininga/cx_freeze/src/e44258991eda05b32c3e63ad0bea409fe6aca1a2/cx_Freeze/freezer.py?at=default&fileviewer=file-view-default#freezer.py-626). Not sure why the code would want to use LIBDIR. Perhaps someone can comment on why this behavior is present.

**Comment by peacegiverman** [comment]
Hi. I just submitted a pull request that fixes this.

**Comment by anthony-tuininga** [comment]
Version 6.x has addressed this.
