### ISSUE TITLE
Help: How to customise configuration file `setup.cfg`?

### ISSUE THREAD

**Issue by im-coder-lg** [marcelotduarte/cx_Freeze#1310]
Hi @marcelotduarte,

I am a new user of cx_Freeze and I find it intriguing. I am helping a GitHub friend of mine on a Python project. We want to create installers for Windows, macOS and Linux.
Actually, now I have two questions. Can I use cx_Freeze for building Linux .deb/.rpm installers?
And the second one is this: I visited the `setup.py` config site(link [here](https://cx-freeze.readthedocs.io/en/latest/setup_script.html)).
Over there, I found this code:
```python
directory_table = [
    ("ProgramMenuFolder", "TARGETDIR", "."),
    ("MyProgramMenu", "ProgramMenuFolder", "MYPROG~1|My Program"),
]

msi_data = {
    "Directory": directory_table,
    "ProgId": [
        ("Prog.Id", None, None, "This is a description", "IconId", None),
    ],
    "Icon": [
        ("IconId", "icon.ico"),
    ],
}

bdist_msi_options = {
    "add_to_path": True,
    "data": msi_data,
    "environment_variables": [
        ("E_MYAPP_VAR", "=-*MYAPP_VAR", "1", "TARGETDIR")
    ],
    "upgrade_code": "{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}",
}

build_exe_options = {"excludes": ["tkinter"], "include_msvcr": True}

executables = [
    Executable(
        "hello.py",
        copyright="Copyright (C) 2021 cx_Freeze",
        base=base,
        icon="icon.ico",
        shortcutName="My Program Name",
        shortcutDir="MyProgramMenu",
    ),
],

setup(
    name="hello",
    version="0.1",
    description="Sample cx_Freeze script to test MSI arbitrary data stream",
    executables=executables,
    options={
        "build_exe": build_exe_options,
        "bdist_msi": bdist_msi_options,
    },
)
```
Does this code go to `setup.cfg`? If it does, can I get the link for the config file's entire syntax?
Thanks in advance for your help and for creating cx_Freeze!

**Comment by im-coder-lg** [comment]
Also, can you guide me on creating an MSI and DMG installer and if you know this, can you also help me on creating an AppImage of Python files?

**Comment by im-coder-lg** [comment]
Project link(in case you need it, I got permission from my friend, it's still in development. If you want, you yourself can open a PR on adding cx_Freeze to the project): https://github.com/sumeshir26/TimerX

**Comment by im-coder-lg** [comment]
We need some more time before merging. I'll give the go-ahead once everything is clear.

**Comment by im-coder-lg** [comment]
I kinda think I understood, but I need your help. Keeping this open!

**Comment by marcelotduarte** [comment]
Hi!
So many questions.. but, yes, cx_Freeze can build .msi and .rpm
I suggest to you do a basic setup like in the first [link](https://cx-freeze.readthedocs.io/en/latest/setup_script.html) and test with:
python setup.py build_exe
If you get success, probably the next step is ok. Then add commands for msi and test:
python setup.py bdist_msi

For mac, has 2 options:
python setup.py bdist_mac
python setup.py bdist_dmg

Check the samples: https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples
There are some for msi usage. In pyqt5 sample (I know, you use tkinter) you can extract in setup.py a basic usage of msi, mac and dmg.

For rpm, use bdist_rpm and maybe you can need a extra code like in this [comment](https://github.com/marcelotduarte/cx_Freeze/issues/1048#issuecomment-858370283)

**Comment by marcelotduarte** [comment]
I tried to run the program on ubuntu. If it doesn't run in python, it won't run in cx_Freeze.
requirements.txt needs darkdetect

python main.py
Line 21: TclError: bad attribute "-transparent": must be -alpha, -topmost, -zoomed, -fullscreen, or -type
Line 24:
```
Traceback (most recent call last):
  File "/home/marcelo/D/testes/TimerX/main.py", line 24, in <module>
    HWND = ctypes.windll.user32.GetForegroundWindow()
AttributeError: module 'ctypes' has no attribute 'windll'
```
...

**Comment by im-coder-lg** [comment]
Thanks for the help! Can you try the same in TimerX's 8th PR? Addressed a lot of changes there.

**Comment by im-coder-lg** [comment]
Hey @marcelotduarte It's the blur plugin. Right now, there are module errors in the git repo's main branch. So, I addressed these changes(and a lot others) in my PR, reportedly sumeshir26/TimerX#8, you can test in that branch. If you have a Windows computer, you can get the BlurWindow module and uncomment the BlurWindow properties.

**Comment by im-coder-lg** [comment]
> `HWND = ctypes.windll.user32.GetForegroundWindow()`

This is actually a commented-out line in my fork and a supposed-to-be-commented-out line in the main branch. It's kinda fixed as of now.

**Comment by im-coder-lg** [comment]
Does cx_Freeze support DEB files since it already has RPM support?

**Comment by im-coder-lg** [comment]
@marcelotduarte sorry for disturbing you on a weekend. Can you tell if we can create `.DEB` files or `.tar.gz` tarballs with cx_Freeze and if we can, then how? Also, when I tested the installer, I encountered error 2756, so is it easy to fix this?

**Comment by marcelotduarte** [comment]
> Can you tell if we can create `.DEB` files or `.tar.gz` tarballs

No, we cannot. But I hope that you can convert the rpm to deb or rpm to tgz using alien.

sudo apt-get install alien

> Also, when I tested the installer, I encountered error 2756, so is it easy to fix this?

Show me the traceback. Give me more information about the error.

**Comment by im-coder-lg** [comment]
I don't understand what a traceback is, but it happened like this:
My friend asked me to test cx_Freeze on my branch. I cloned it, got checked out to the branch, and installed all the requirements. Then, I got cx_freeze to work with this command on my Git Bash:
```bash
$ python setup.py bdist_msi
```
Just so you know, I am using Python 3.8 from Anaconda3 on a Windows 7 PC.
It generated an unzipped part and an MSI. On launching it, it looks kinda like, choose the path, get sure about installing. But then, a popup appears saying that this ended due to error 2756. I tried it again, again, and again but it always ended up there. I will post a recording soon.

**Comment by sumeshir26** [comment]
@marcelotduarte The error is in the MSI
![image](https://user-images.githubusercontent.com/68823982/145665684-2aab5088-8d79-4fca-bbeb-9b4be2475d53.png)

**Comment by im-coder-lg** [comment]
That's the one!

**Comment by marcelotduarte** [comment]
In setup.py, what are the bdist_msi_options?

**Comment by im-coder-lg** [comment]
We use the `bdist_msi_options` for the config for `bdist_msi`. Is anything wrong there?

**Comment by sumeshir26** [comment]
@marcelotduarte 
![image](https://user-images.githubusercontent.com/68823982/145666088-1c94698e-4310-4835-900c-004f0e52834f.png)

**Comment by marcelotduarte** [comment]
I have not been using msi, but there are others who use and have kept the code updated. I'm going to suggest you to check the use of shortcut_dir and install_icon, as there might be something wrong with these parameters.
https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cx-freeze-executable
https://cx-freeze.readthedocs.io/en/latest/setup_script.html#bdist-msi
And in the last case:
https://docs.microsoft.com/en-us/windows/win32/msi/windows-installer-portal

**Comment by marcelotduarte** [comment]
In addition, msi accepts macros, for example, see this [post](https://stackoverflow.com/questions/57339138/msi-created-in-cx-freeze-does-not-install-program)
In the option initial_target_dir has a macro:
'initial_target_dir': r'[ProgramFilesFolder]\%s\%s' % ("Name", "Product"),

**Comment by im-coder-lg** [comment]
So, you mean that Line 41 below is incorrect?
https://github.com/sumeshir26/TimerX/blob/3a92f052c7d1e20557c752690cfe442c82a669cb/setup.py#L41
Or there is an incorrect usage in the parameters?

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.11](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.11.0) has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
