### ISSUE TITLE
include-files doesn't include modules or packages

### ISSUE THREAD

**Issue by mrkbutty** [marcelotduarte/cx_Freeze#1321]
**Describe the bug**
Running a windows exe via PATH instead of full path to exe changes the python sys.path.
When using frozen scripts which use dynamic imports of local modules it fails because cannot find module.

**To Reproduce**
See repo at: https://github.com/mrkbutty/freezetest

No problem running direct from dist:

```
>dist\freezetest.exe
Hello, from main file: freezetest.py
I think progdir is C:\Code\freezetest\dist
I think path is ['C:\\Code\\freezetest\\dist', 'C:\\Code\\freezetest\\dist\\lib\\library.zip', 'C:\\Code\\freezetest\\dist\\lib']
Hello, from subfunc file: C:\Code\freezetest\dist\tools\submod.py
I think progdir is C:\Code\freezetest\dist
I think path is ['C:\\Code\\freezetest\\dist', 'C:\\Code\\freezetest\\dist\\lib\\library.zip', 'C:\\Code\\freezetest\\dist\\lib']
```

Issue when running after dist moved C:\tmp\dist and C:\tmp\dist is added into windows PATH and I run from working directory C:\:

```
>freezetest
Hello, from main file: freezetest.py
I think progdir is c:\tmp\dist
I think path is ['C:\\', 'c:\\tmp\\dist\\lib\\library.zip', 'c:\\tmp\\dist\\lib']
Traceback (most recent call last):
  File "C:\Code\freezetest\.venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
    module_init.run(name + "__main__")
  File "C:\Code\freezetest\.venv\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
    exec(code, module_main.__dict__)
  File "freezetest.py", line 19, in <module>
  File "freezetest.py", line 15, in main
  File "c:\program files\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tools.submod'
Steps to reproduce the behavior
```

**Expected behavior**
I did not expect the sys.path to change depending on how the exe was executed.

**Desktop (please complete the following information):**
 - Platform information: Microsoft Windows [Version 10.0.19043.1415]
 - OS architecture: amd64
 - cx_Freeze version: 6.9
 - Python version: 3.8.10

**Additional context**
Took me a long time to figure this out after converting from pyinstaller to cx_freeze because I wanted the easier to setup multiple exe support.  I could not figure why unfrozen would work, but installed program in the path would not work.

**Comment by mrkbutty** [comment]
BTW I fixed original program by adding:

```
def getprogdir():
    if getattr(sys, 'frozen', False):
        return getattr(sys, '_MEIPASS', os.path.dirname(sys.executable))
    else:
        return os.path.dirname(os.path.abspath(sys.modules['__main__'].__file__))

progdir = getprogdir()
sys.path.insert(0, progdir)
```

However, maybe it is a security concern for some that the working directory is still in the sys.path so could be used to override expected modules and packages.

**Comment by marcelotduarte** [comment]
There are an error in the freeze.bat
`cxfreeze -c freezetest.py --target-dir dist --include-files=tools --zip-include-packages=* --zip-exclude-packages=`
If change --include-files=tools by --packages=tools
`cxfreeze -c freezetest.py --target-dir dist --packages=tools --zip-include-packages=* --zip-exclude-packages=`
or by module (--includes)
`cxfreeze -c freezetest.py --target-dir dist --includes=tools.submod --zip-include-packages=* --zip-exclude-packages=`

And if tools is a package, the correct is to add a `__init__.py` in tools directory.

And, yes, this line https://github.com/marcelotduarte/cx_Freeze/blob/1d9da6f160270d85b31236485d41e9ecc52c35a1/source/bases/Common.c#L152

should be updated to avoid security issues. I already updated for linux and mac, but in windows, I needed a test. I think that your sample is the test.

EDIT: To complement the information: include_files should be used to data files
See [Using data files](https://cx-freeze.readthedocs.io/en/latest/faq.html#using-data-files)

**Comment by mrkbutty** [comment]
Thanks for the freeze.bat file tips Marcelo.
I will attempt to test your fix too.

Regarding "And if tools is a package, the correct is to add a `__init__.py` in tools directory."
 - I thought this too however after investigating that is no longer a requirement for "namespace packages" in python 3.3 and later...
 - See: https://stackoverflow.com/questions/448271/what-is-init-py-for
 - And: https://www.python.org/dev/peps/pep-0420/

**Comment by marcelotduarte** [comment]
cx_Freeze detects namespace packages and workaround to make it a package.

**Comment by marcelotduarte** [comment]
PR #1324 fix a mentioned security issue.
[cx_Freeze 6.10](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.10) has just been released.
