### ISSUE TITLE
Idea: Add some CI?

### ISSUE THREAD

**Issue by DiddiLeija** [marcelotduarte/cx_Freeze#1363]
Hi everybody!

I think you already know GitHub Actions (GHA), because we already have a `build-wheel` workflow. However, what about using CI for linting or running the tests living in `tests/`?

This can be really useful, for example, on PRs. We can run tests on any Python we support, and (almost) every platform supported. We can also start with automation tools such as [Nox](https://nox.thea.codes) or [tox](https://tox.wiki), so both users and CI can run exactly the same.

If you're interested, and need some help, please tell me :)

**Comment by marcelotduarte** [comment]
Hi!
I think about a pre-commit. If you can help, of course, I want to.

**Comment by DiddiLeija** [comment]
Ok! I will be working on pre-commit. I'll post a PR later.

**Comment by marcelotduarte** [comment]
> hat about using CI for linting or running the tests living in `tests/`?

Feel free to add this too ;-)
