### ISSUE TITLE
Cryptography module

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#138]
Originally reported by: **Nils Hjelte (Bitbucket: [silok](https://bitbucket.org/silok), GitHub: [silok](https://github.com/silok))**

----------------------------------------

I have problems with getting the cryptography module to run properly. I get this error message:

```
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/primitives/padding.py", line 18, in <module>
    with open(os.path.join(os.path.dirname(__file__), "src/padding.h")) as f:
IOError: [Errno 20] Not a directory: '/Volumes/Big/Work/agx/SimulationServer/build/exe.macosx-10.10-x86_64-2.7/library.zip/cryptography/hazmat/primitives/src/padding.h'

```

The cryptography files are available in the zip-file, but the cryptography module is unable to locate the header-file.

Current solution: If I unzip the cryptography content from the library.zip to the folder build/exe.macosx-10.10-x86_64-2.7/cryptography the code executes ok

Note: The zip file does not contain the headers either, but unpacking it (pyc-files) still resolves the missing header exception...

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/138

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
