### ISSUE TITLE
Drop Python 3.6?

### ISSUE THREAD

**Issue by DiddiLeija** [marcelotduarte/cx_Freeze#1382]
The [Python 3.6 EOL](https://www.python.org/dev/peps/pep-0494/#lifespan) happened like 3 months ago. Is it worthy to remove it from cx_Freeze supported versions? Do we have any blocker?

If we are going to drop Python 3.6, we should drop it from:

- the package classifiers
- the GitHub README
- the docs
- the GitHub CI, that runs Python

**Comment by marcelotduarte** [comment]
I plan to keep it for at least the next version. Conda-forge no longer supports py36 since cx_Freeze 6.9. On Linux and Windows, there are still people who use py36.
