### ISSUE TITLE
Install cx_Freezeby failed by pip in python310

### ISSUE THREAD

**Issue by zearoby** [marcelotduarte/cx_Freeze#1384]
Hi,

I tried to install cx_Freeze by "pip install cx_Freeze" in system console in python310, but this worked weel in python39.
I have searched the issue in google and bing, but did't find any useful solution.

Are there any differences between python39 and python310 about to install cx_Freeze?

Thanks

**Comment by marcelotduarte** [comment]
Windows?
More information, please! Error messages, traceback, etc.

**Comment by zearoby** [comment]
Hi,

My computer platform is windows 10 with Python310 and installed cx_Freeze by command "pip install cx_Freeze" in system console, but it worked successfully with Python39. Below is the screen shot when installing cx_Freeze failed:

![image](https://user-images.githubusercontent.com/22544491/154244447-d14fa746-9b14-4ea0-b956-35ddfed63dd7.png)

After I installed c++14.0 in system:
![image](https://user-images.githubusercontent.com/22544491/154245054-81e64455-830d-4194-b035-16dd97301ae7.png)

I really don't know what happend and what should I do for this issue. Thank you very much.

**Comment by zearoby** [comment]
The Chinese words in screen shot "**无法打开包括文件**" means "**can't open the file**".

**Comment by marcelotduarte** [comment]
cx_Freeze on windows depends on two packages. For python 3.10 these packages are not available. I need to document this.

So, you should install it manually before cx_Freeze.
```
pip install -f https://lief-project.github.io/packages/lief/ "lief>=0.12.0.dev0"
pip install -i https://marcelotduarte.github.io/packages/ cx_Logging
pip install cx_Freeze
```

**Comment by zearoby** [comment]
Hi,

Thank you very much. This solution worked fine in my windows system.
