### ISSUE TITLE
Using UTF-8 in MSI installer

### ISSUE THREAD

**Issue by machobymb** [marcelotduarte/cx_Freeze#1385]
Hi!

I created an msi installer under Win 10. I use codepage 852 and Hungarian language.
When I create the installer, cx_Freeze not use UTF-8 codepage, only when modify the HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\OEMCP  to 65001.
How can I config the setup.py to using UTF-8?

**Comment by marcelotduarte** [comment]
I think this depends of your code editor, but you can use the old:
`# -*- coding: utf-8 -*-`
in the first line

**Comment by marcelotduarte** [comment]
Can I close the issue?

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
