### ISSUE TITLE
An error when the script runs `Segmentation fault`

### ISSUE THREAD

**Issue by tufbel** [marcelotduarte/cx_Freeze#1386]
Running `python main.py` is fine:
```shell
2022-02-21 19:10:14.856 | INFO     | src.settings:<module>:30 - [PROD] Server
2022-02-21 19:10:16.156 | INFO     | src.ait.transport:register_handler:27 - Register Ait handler: GPSAitHandler
2022-02-21 19:10:16.156 | INFO     | src.ait.transport:register_handler:27 - Register Ait handler: StatusTrafficAitHandler
```
But I used cx_freeze to run `python setup.py build` and then `./build/exe.linux-x86_64-3.9/main` :
```shell
2022-02-21 19:15:39.111 | INFO     | src.settings:<module>:30 - [PROD] Server
Segmentation fault
```

**Comment by marcelotduarte** [comment]
More info please.
Try to write a small sample to demonstrate the error.
And your basic setup.py

**Comment by tufbel** [comment]
> More info please. Try to write a small sample to demonstrate the error. And your basic setup.py

I found that the cause of this error was `import orjson`

**Comment by marcelotduarte** [comment]
Did you solve the issue?
If not, probably you need to add some extension that was missing.
Maybe using package=["orjson"]

**Comment by tufbel** [comment]
> Did you solve the issue? If not, probably you need to add some extension that was missing. Maybe using package=["orjson"]

Thank you. My problem is not solved.
I tried the method you mentioned, but I still couldn't solve it.
```python
    packages: List = []

    requirements_str = "-".join(get_all_requirements())
    for pack in get_all_packages():
        if pack in requirements_str:
            packages.append(pack)

    packages.append("orjson")
    build_exe_options = {
        "include_files": [ "pyproject.toml"],
        "packages": packages,
        "excludes": [],
    }
    setup(
        name=PROJECT_DIR.name,
        version=PROJECT_CONFIG["tool"]["commitizen"]["version"],
        description=PROJECT_DIR.name,
        options={"build_exe": build_exe_options},
        executables=[Executable("main.py")],
    )
```

**Comment by tufbel** [comment]
I changed the `orjson` version from 3.6.7 to 3.6.4 to solve the problem successfully

**Comment by zariiii9003** [comment]
@marcelotduarte it seems like adding "zoneinfo" to packages solves this issue.

**Comment by marcelotduarte** [comment]
Added sample PR #1605 
Tested with v 3.8.0 fails
Added hooks PR #1606 
@zariiii9003 I discovered that is depends on others packages, but the interesting is that it depends on json too.

https://github.com/ijl/orjson/blob/master/src/typeref.rs#L181

**Comment by zariiii9003** [comment]
@marcelotduarte thank you! 👍
