### ISSUE TITLE
Issue with Chinese character in the name of folder of executable with using Pyside2

### ISSUE THREAD

**Issue by VirginianBlue** [marcelotduarte/cx_Freeze#1395]
same issue with (https://github.com/marcelotduarte/cx_Freeze/issues/972) by using PySide2

For an executable frozen by cx-Freeze 6.10, with Python:
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Pyside2  '5.15.2.1'

I got this result:
![打包错误](https://user-images.githubusercontent.com/50310664/156103408-845e31c9-06ca-4c3b-831d-c1944e62886f.png)

**Comment by marcelotduarte** [comment]
I have a fix.
```
pip uninstall -y cx_Freeze
pip install -i https://marcelotduarte.github.io/packages/ cx_Freeze --pre
```
Can you test and report?

**Comment by VirginianBlue** [comment]
It works in my test_code.
But another issue occurs in my project.
![6-11报错](https://user-images.githubusercontent.com/50310664/156133556-d90903e4-5690-415a-b399-dd2dc3f63978.png)

And I try to replace the Pyside2 folder contents under lib folder with legacy files(version6.10).
This issue occurred when runing under folder-with-chinese-name.
`Could not find QtWebEngineProcess.exe`
![couldnotfind](https://user-images.githubusercontent.com/50310664/156136877-94c14db6-6b7b-4a1d-a794-94d5398e1213.png)

**Comment by marcelotduarte** [comment]
Can you provide a minimal sample to reproduce this error?

**Comment by VirginianBlue** [comment]
Sample : [test.zip](https://github.com/marcelotduarte/cx_Freeze/files/8166108/test.zip)
I use cx_Freeze-6.11.0-dev1 like this:
`cxfreeze --target-name="test" --target-dir="test_web" --uac-admin test.py`

**Comment by marcelotduarte** [comment]
Can you test with the most recent version?
`pip uninstall -y cx_Freeze`
`pip install --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --pre`

**Comment by marcelotduarte** [comment]
I tested your sample and it works, with an exception, you should use test --single-process
[qt command line](https://doc.qt.io/qt-5/qtwebengine-debugging.html#using-command-line-arguments)

To build you can use cxfreeze --zip-include-packages=PySide2 to reduce size of build directory.

With cx_Freeze [sample](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyside2-simplebrowser) is needed to run: test_simplebrowser --no-sandbox

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.12.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.12.0) has just been released.
