### ISSUE TITLE
cx_Freeze ModuleNotfoundError Fails to use some modules.

### ISSUE THREAD

**Issue by IverNoError** [marcelotduarte/cx_Freeze#1409]
If I run a script and I pip install psutil and I use psutil in this python script it all works. If I then try to use cx_Freeze on this script it builds a exe or windows installer and I run it I get a error saying psutil is not defined. I tried everything from making a new env installing psutil in other ways but cx_Freeze wont work. And I try to use some other code without psutil then I build it with exe then run the exe that is without psutil just some other script and it works all good. This is also happening for another module I have pip installed this is very weird. The program works but then when I use cx_freeze on it. It says psutil is not defined. And if I make a new env I build it I run the exe I get the error. And then in the same env if I try to build it. It will not let me build the program. It just says in the building process psutil not defined.

*When I say defined I mean this error*
ModuleNotfoundError: No module named 'psutil' 

 - Newest version of windows 10
 - Latest version of cx_Freeze
 - Python version 3.9.7

**Comment by marcelotduarte** [comment]
Use the [packages](https://cx-freeze.readthedocs.io/en/latest/setup_script.html?highlight=packages#cmdoption-arg-packages) option

**Comment by IverNoError** [comment]
raise ImportError(f"No module named {name!r}")
ImportError: No module named 'psutil'

I still get this I tried many ways now to include the packages. Latest I tried with the exact code from docs it just do not work

**Comment by marcelotduarte** [comment]
Paste a simple sample to reproduce the error and I'll check.

**Comment by IverNoError** [comment]
ayman.py
```
import psutil
cpu_count = psutil.cpu_count()
print(cpu_count)
```
Setup.py
```
import sys
from cx_Freeze import setup, Executable

build_exe_options = {"packages": ["psutil"]}

base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(
    name="ayman",
    version="0.1",
    description="My GUI application!",
    options={"build_exe": build_exe_options},
    executables=[Executable("ayman.py", base=base)],
)
``` 
Build command:
`python setup.py build_exe`

**Comment by IverNoError** [comment]
and I do pip install psutil before that ofc

**Comment by marcelotduarte** [comment]
I was unable to reproduce the error. One thing I saw wrong in the setup is to use base="win32" and this sample will run in console mode. Putting base=None resolves and we can see the result.
The error mentioned I did not see.
There must be something wrong with your system. I used a venv to test.
You can upgrade some tools, or remove and install, like:
python -m pip install --upgrade pip
pip install --upgrade setuptools
pip uninstall -y cx_Freeze psutil
pip install cx_Freeze psutil
and build it:
python setup.py build

**Comment by IverNoError** [comment]
Seems to be all working now I just changed my code over to vs code and changed the python path thanks
