### ISSUE TITLE
Cannot freeze PyQt5 UI created with Designer

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#141]
Originally reported by: **Anonymous**

----------------------------------------

I've created a GUI using the Designer application in PyQt5.4.1 for my application (available on this branch [here](https://github.com/le717/Blocks/tree/pyt-ui)). The GUI is done, and now I'm trying to freeze the program ([setup.py](https://github.com/le717/Blocks/blob/pyt-ui/setup.py)). Freezing seems to be fine, but when I run the exe I get the following message.

![](https://dl.dropboxusercontent.com/u/58490278/Screenshots/Blocks/freeze-error.png)

I've found the only way to fix this is to copy the pyuic5-generated .py files from the ui folder to a ui folder with my exe.

This seems like a bug in cx_Freeze because the point of freezing an exe is not to include source code in your released binary. Does anyone what can be done to fix this bug and possibly work around it in the meantime? Thanks!

-le717

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/141

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Feldmann (Bitbucket: [tfeldmann](https://bitbucket.org/tfeldmann), GitHub: [tfeldmann](https://github.com/tfeldmann))**:

----------------------------------------

Please try to add an empty \__init__.py to your "ui" folder and freeze again.

**Comment by le717** [comment]
This was my bug report. It's long been fixed. You can close it on here and BitBucket. :)

**Comment by anthony-tuininga** [comment]
Thanks for following up!
