### ISSUE TITLE
Windows service executable missing in distribution

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#145]
Originally reported by: **Wolfgang L. (Bitbucket: [tds](https://bitbucket.org/tds), GitHub: [tds](https://github.com/tds))**

----------------------------------------

The windows service executable "Win32Service.exe" (part of bases) is missing in the Python 2.7 wheel distribution set. (also in every other binary distribution for Windows)

This needs a dependency to cx-logging to build and run. Could be this is not installed on the build machine.

Think best for long term is to remove the dependency to cx-logging, it seems unmaintained and this dependency is complicated to handle for a build.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/145

**Comment by marcelotduarte** [comment]
Assuming this has been resolved.
