### ISSUE TITLE
In Python3.10, I cannot use distutils module and error is No module named 'distutils.command.bdist_wininst'

### ISSUE THREAD

**Issue by seanlab1** [marcelotduarte/cx_Freeze#1483]
How can I remove this module in option or any other methods

**Describe the bug**
No module named 'distutils.command.bdist_wininst'

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 16.04):
 - OS architecture (e.g. amd64):
 - cx_Freeze version [e.g. 6.6]:
 - Python version [e.g. 3.9]:

**Additional context**

**Comment by marcelotduarte** [comment]
Please, I need more details. Are you using windows? the setup.py or command line, etc.

**Comment by marcelotduarte** [comment]
Python 3.10 removed this module.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.11](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.11.0) has just been released.
pip install --upgrade cx_Freeze

Despite the lack of response, v6.11 no longer relies on distutils.
