### ISSUE TITLE
6.10 will not package correctly with cryptography

### ISSUE THREAD

**Issue by MSchnapp** [marcelotduarte/cx_Freeze#1490]
Unable to package executable with cryptography.  Application is being built for Windows.  Python version 3.7.4 and cx_freeze version 6.10.  Was using 6.8 and it worked perfectly, but because of the new addition of uac_admin, I was trying to package with 6.10.  I have tried multiple versions of cryptography, and cffi to see if there was a version mismatch.  I could only see the error for a second but it was setting "Fatal Python error: _PyInterpreterState_Get(): no current thread state" in the debug console when trying to launch executable.  If I pip uninstall cryptography, and rebuild, it would start no problem with the exception of it eventually setting the ImportError: No module named Cryptography found.  However if I keep everything else the same, remove the uac_admin flag and roll back into 6.8, everything compiles and works flawlessly.  I also tried removing the uac_admin flag and uninstall leif, and it would still not compile successfully.
.

**Comment by marcelotduarte** [comment]
I test cx_Freeze with cryptography and bcrypt in [samples](https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples). Can you test too?
I recommend that you test your project using base=None instead of using base=Win32GUI and run it in console/cmd to get the traceback.
Another possible issue is the use of LIEF in 6.10, which I need to polish, so you can disable it for get dependencies (See PR #1344). Basically, you must use `set CX_FREEZE_BIND=imagehlp` or in setup.py script use os.environ.

**Comment by MSchnapp** [comment]
So I seen that and those also did not want to build correctly, And I generate two MSI, one with win32gui and one with None, for debug reasons, and thats how I was able to see the Fatal Python error.  And thats what I was wondering, but it looks like if you want to use uat_admin, you need to use LIEF because of the manifest file it generates.

**Comment by marcelotduarte** [comment]
For the manifest it needs LIEF, but setting the CX_FREEZE_BIND=imagehlp disables it only for dependencies.
Are you testing only with bdist_msi or tested with build_exe too?
Do you tested with the samples?

**Comment by marcelotduarte** [comment]
@MSchnapp The  [cryptography](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/cryptography) sample works for me with python 3.6 to 3.10. Can you provide a minimal example so I can resolve this issue?

**Comment by marcelotduarte** [comment]
ping @MSchnapp

**Comment by MSchnapp** [comment]
So I have been testing with just bdist_msi because that’s the format I will need for distribution.  And so will I still be able to use uat_admin with LIEF disabled? And I have, I will test again tonight. Are there version restrictions around which cryptography can be used?

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.12.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.12.0) has just been released.



> And so will I still be able to use uat_admin with LIEF disabled?

Yes. LIEF ise used for more than one task. CX_FREEZE_BIND=imagehlp disables it only for dependencies.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.13.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.13.0) has just been released.
Can you check if this has been resolved?

**Comment by MSchnapp** [comment]
Sorry for the delay, I believe so far so good
