### ISSUE TITLE
bin_includes not including soname (for tidylib)

### ISSUE THREAD

**Issue by 1over137** [marcelotduarte/cx_Freeze#1492]
**Describe the bug**
The `bin_includes` option does not seem to be including the sonames I specified. The soname in this case is libtidy.so.5.8.0. 
Location: `ls -l /usr/lib64 | grep tidy`:
```
lrwxrwxrwx   1 root root        13 May  5 11:53 libtidy.so -> libtidy.so.58
lrwxrwxrwx   1 root root        16 May  5 11:53 libtidy.so.58 -> libtidy.so.5.8.0
-rwxr-xr-x   1 root root   1089040 May  5 11:53 libtidy.so.5.8.0
```

**To Reproduce**
Sample script: testtidy.py
```py
from tidylib import tidy_document
document, errors = tidy_document('''<p>f&otilde;o <img src="bar.jpg">''',
    options={'numeric-entities':1})
print(document)
print(errors)
```
Setup script: setup.py

```py
import sys
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
# "packages": ["os"] is used as example only
build_exe_options = {"packages": ["tidylib"], 
                     "excludes": ["tkinter"],
                     "bin_path_includes": ["/usr/lib64"],
                     "bin_includes": ["libtidy", "libtidy.so", "libtidy.so.5.8.0"]
                    }

# base="Win32GUI" should be used only for Windows GUI app
base = None

setup(
    name="testtidy",
    version="0.1",
    description="My GUI application!",
    options={"build_exe": build_exe_options},
    executables=[Executable("testtidy.py", base=base)],
)
```
Result: 

None of the sonames are included into the build directory. If the built binary is executed on a system without libtidy.so present, it returns an OSError of not being able to open the soname.

**Expected behavior**
At least one of the listed sonames should appear in the build directory and the bundled executable should run without libtidy.so present on the system. 

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 16.04): Gentoo
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.6]: 6.10
 - Python version [e.g. 3.9]: 3.10

**Comment by marcelotduarte** [comment]
I tested in Ubuntu and for me, I have to use:
```
"bin_path_includes": ["/usr/lib/x86_64-linux-gnu"],
"include_files": [("/usr/lib/x86_64-linux-gnu/libtidy.so.5deb1", "lib/libtidy.so.5deb1")]
```
In this specific case (tidy) the .so is loaded dynamically.
bin_includes works only with **"list of files to include when determining dependencies of binary files**" and this is not the case.

**Comment by marcelotduarte** [comment]
[Release 6.15.9](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.9) is out!

With this version, bin_path_includes, include_files and possibly other options can be removed, as it detects the library automatically. Tested on Ubuntu. Can you test it in your system and give feedback?
