### ISSUE TITLE
Erro depois de trasformar em .exe

### ISSUE THREAD

**Issue by Thomaz-Castro** [marcelotduarte/cx_Freeze#1497]
Fiz um programa que baixa videos do youtube (está no meu github). ele funciona perfeitamene no VScode, porem depois de gerar o .exe, ele da um erro quando clico pra baixar em mp3
![image](https://user-images.githubusercontent.com/103527232/168498627-401d9707-160c-426a-89a9-094f8de40f29.png)

**Comment by marcelotduarte** [comment]
In the traceback, file Downloader.py line 63 or in the next module, probably you create a file (or filename), and in the frozen app the directory is different, and you get the error.
Maybe related to https://cx-freeze.readthedocs.io/en/latest/faq.html#using-data-files

**Comment by Thomaz-Castro** [comment]
adicionei a pasta dentro de "build" porem recebei outro erro quando tento baixar em mp3, acho que está relacionado ao print da barra de progresso que o moviepy cria no console
![image](https://user-images.githubusercontent.com/103527232/168854338-81a567cb-9edd-4191-86dd-67db40acf01a.png)

**Comment by marcelotduarte** [comment]
Infelizmente vc passou pouca informação sobre o projeto. Vc pode me mostrar o setup.py ou comando q vc usou para construir o executável, e também pode me mostrar as linhas 60-65 do downloader.py?

**Comment by Thomaz-Castro** [comment]
[O projeto do downloader.py no meu Github](https://github.com/Thomaz-Castro/Video_Downloader)

O setup.py:
![image](https://user-images.githubusercontent.com/103527232/168917892-e89cd97a-9e9e-4ffa-b7bd-e6e5e7cdb480.png)
para incluir a pasta "mp" que é usada como um caminho para a conversão de .mp4 para .mp3, usei o comando no terminal `python .\setup.py build_exe --include-files=mp`

linhas 60-65 do downloader.py:
![image](https://user-images.githubusercontent.com/103527232/168918142-f7dedfc1-565b-47cf-a2fa-44f1007b82b4.png)
essa parte do codigo pega o caminho com o nome do arquivo .mp4, e troca ".mp4" por ".mp3".
depois ele junta o nome do arquivo já com a extensão .mp3 e junta com o caminho para a pasta downloads.
após isso vem a parte que acho que está dando problema, a linha 63 ela pega o arquivo  ".mp4" da pasta "mp" e trasfere para pasta de "downloads" já como um ".mp3", só que nesse processo ele cria uma barra de progressão no console, mas como o .exe não tem console, acho que é ai que o problema acontece.
depois na linha 64 ele excluiu o .mp4 na pasta "mp", e na linha 65 ele atualiza a interface do PySimpleGUI com "Baixado com sucesso"

**Comment by marcelotduarte** [comment]
Esta pasta 'mp' não deve existir relativa ao executável. include_files não incluirá uma pasta.
No seu código vc deve verificar se mp existe e criar se necessário.

**Comment by Thomaz-Castro** [comment]
existe sim, fiz um teste agora comentando as linhas 63-64 e o programa funcionou normal, deixando o arquivo .mp4 na pasta mp. Então continuo achando que o problema é porque o "write_audiofile" tenta imprimir no console a barra de progressão e como não encontra o console da erro

**Comment by Thomaz-Castro** [comment]
Consegui resolver!!!
![image](https://user-images.githubusercontent.com/103527232/169147793-57ab7914-8b9c-4db5-a30a-d0b4b7255c8c.png)
Dentro de "AudioClip.py" (um arquivo do moviepy), alterei "logger".
antes estava com 'bar' ai eu alterei pra "None", rodando dentro do VScode ele não printou nenhuma mensagem, trasnformei em .exe e rodou liso. Agradeço pela anteção, agora só vou adicionar icones e etc.
