### ISSUE TITLE
cx_freeze:python error in main script when i running the univorn 

### ISSUE THREAD

**Issue by brightAI2021** [marcelotduarte/cx_Freeze#1503]
**Describe the bug**

cx_freeze:python error in main script when i running the univorn with fastapi 
I build exe  is ok, but when i run the exe file , pop up the error in windows

AttributeError:'NoneType' object has no attribut 'isatty'

file D:\pythoon3.10\lib\logging\config.py

raise ValueError("unable to configure formatter ''default")

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04):
 - OS architecture (e.g. amd64):
 - cx_Freeze version [e.g. 6.10]:
 - Python version [e.g. 3.9]:

**Additional context**

**Comment by marcelotduarte** [comment]
Please reduce the need to ask for additional information by filling out a good report.

**Comment by marcelotduarte** [comment]
Can you provide complete information?

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.12.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.12.0) has just been released.
Closing due to lack of information.
