### ISSUE TITLE
Name cannot contain non-alphanumeric characters

### ISSUE THREAD

**Issue by mathiascode** [marcelotduarte/cx_Freeze#1510]
**Describe the bug**
Since the switch to setuptools in cx_Freeze 6.11, the `name` parameter cannot contain non-alphanumeric characters anymore.

When the setup process reaches the egg_info command, non-alphanumeric characters are replaced with a hyphen according to pkg_resources.safe_name:

https://github.com/pypa/setuptools/blob/d508e3841d3a40aeb602b0a9a883b227a27a3842/pkg_resources/__init__.py#L1309-L1314

https://github.com/pypa/setuptools/blob/499c468a57d240e5bb450bdb6daedc3e559541dd/setuptools/command/egg_info.py#L126-L128

Invalid names fail here:

https://github.com/pypa/setuptools/blob/499c468a57d240e5bb450bdb6daedc3e559541dd/setuptools/command/egg_info.py#L220-L228

This is an issue in Windows builds, which use the `name` parameter for the product name and other user-facing parts in the installer.

**To Reproduce**
Change the name in one of the sample setup.py scripts to e.g. Nicotine+.

```
setup(
    name="Nicotine+",
```

Terminal output:

```
...
running install_scripts
running egg_info
error: Invalid distribution name or version syntax: Nicotine--3.3.0
```

**Expected behavior**
Names can contain any characters.

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): MinGW on Windows Server 2019 (GitHub Actions)
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.10]: 6.11
 - Python version [e.g. 3.9]: 3.9

**Comment by marcelotduarte** [comment]
I liked your bug report. I would love for everyone to take the trouble to describe the problem so well.
Unfortunately, as distutils is deprecated, we have to go in the direction of setuptools and follow its rules. I see that you already know that the name is exceptional and you use the name "nicotine-plus" in the setup for installation via pip, so in cx_Freeze you will have to do the same as:
https://github.com/nicotine-plus/nicotine-plus/blob/master/setup.py#L78

If you want to use the + in the MSI filename this is possible, just use the [target-name](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-target_name) option.

Hope this helps.

**Comment by mathiascode** [comment]
Looking at the documentation again, I can probably mitigate my largest issue (name option being used for the installation path) by manually specifying the install_dir option. I can't check the source code right now, but I believe the setuptools name option was also used for the product name in the executable, as well as the application name in the installer GUI. While these are mostly cosmetic issues that don't affect me much, perhaps the name could be taken from a new or another existing option?

**Comment by marcelotduarte** [comment]
The code that defines default target_name is:
https://github.com/marcelotduarte/cx_Freeze/blob/main/cx_Freeze/command/bdist_msi.py#L891-L907

I'm thinking in implement two options product_name and product_version in bdist_msi to "maintain" the compatibility because all of the rest of the code depends on the name, including registry options/names.

**Comment by marcelotduarte** [comment]
I found that the target_name option was overloaded and fixed, so you can use it as I indicated.
You have to change only the name to a safe name like "nicotine-plus" and add in bdist_msi options the option "target_name" = "Nicotine+" (or in your case the config.name) and the rest will work as in cx_Freeze 6.10.
You can test the fix using the mingw packages at https://marcelotduarte.github.io/packages/mingw/

**Comment by mathiascode** [comment]
Thanks, that takes care of the installer for me. A minor detail: if you set `target_version`, the installer basename repeats the version twice: `ProgramName-version-arch-version.msi`

The only issue remaining is that the setuptools name option is always used for ProductName here: https://github.com/marcelotduarte/cx_Freeze/blob/95c6c40d8b6793f5fc908d9d2d3f26bac405b1ac/cx_Freeze/freezer.py#L699

**Comment by marcelotduarte** [comment]
I updated the patch to fix the two remaining issues. The second, ProductName, I cannot change at that point, so I replicated the code in bdist_msi and change the values accordingly.
Can you test it again?

**Comment by mathiascode** [comment]
The executable in `build/exe.*` has the setuptools name option as product name (to be expected, since the value is changed when generating the installer). When creating my portable package, I can work around this by using the files from the `build/bdist.*` folder instead (with keep_temp option enabled), so it's not a big deal for me. However, I wonder if an optional product_name cx_Freeze.Executable option would be a cleaner solution in the long run (since there are already Windows-only options such as copyright and trademarks)?

Minor issue in your latest patch: the plat_name option is no longer respected, it's overwritten.

**Comment by marcelotduarte** [comment]
> When creating my portable package, I can work around this by using the files from the `build/bdist.*` folder instead (with keep_temp option enabled),

ok

> an optional product_name cx_Freeze.Executable option would be a cleaner solution in the long run

I think so, but cx_Freeze accepts a list of 'Executable's. So it could get a little confusing if you use a prodct_name in each Executable.
I could use the product_name of the first item, but I would have to see all the implications. target_name at this point will be used for all Executables and also for the msi filename.

> Minor issue in your latest patch: the plat_name option is no longer respected, it's overwritten.

Before, it was ignored.

**Comment by mathiascode** [comment]
You're right, it's a bit of a pain to implement. In any case, I'd say the latest patch works well enough for my immediate needs.

**Comment by marcelotduarte** [comment]
Good news. The updated PR solves the issue with the name without changing it.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.11.1](https://github.com/marcelotduarte/cx_Freeze/releases/tag/v6.11.1) has just been released.
pip install --upgrade cx_Freeze

**Comment by mathiascode** [comment]
Thanks for the quick release and all the work on cx_Freeze! Your patch works well.

**Comment by marcelotduarte** [comment]
PR #1520 solved the issue and the code you have tested is part of PR #1524
The new release for MinGW has been committed too, but it is slow to publish the packages, maybe in 2 days.
