### ISSUE TITLE
Error when .dist-info directory has subdirectories

### ISSUE THREAD

**Issue by ubalklen** [marcelotduarte/cx_Freeze#1513]
**Describe the bug**
Currently, cx_Freeze considers packages' .dist-info directories can only have files, and will call [Path.read_bytes()](https://docs.python.org/3/library/pathlib.html#pathlib.Path.read_bytes) from them:

https://github.com/marcelotduarte/cx_Freeze/blob/a69f0d32cd093165ed2fb659c36e1921028244ba/cx_Freeze/module.py#L50-L53

But if there are subdirectories, `read_bytes` will raise a `PermissionError`. This already happens in the wild with `soupsieve`, a dependecy of the popular [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/). `soupsieve` has a `license_files` subfolder in their .dist-info, so it can't be freezed. See more details on this [issue](https://github.com/facelessuser/soupsieve/issues/250) in their repo.

**To Reproduce**
**main.py**:
```
from bs4 import BeautifulSoup

html_doc = """<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""

soup = BeautifulSoup(html_doc, "html.parser")
print(soup.prettify())
```

From a terminal:
```
cxfreeze main.py
```

**Expected behavior**
A frozen executable.

**Desktop (please complete the following information):**
 - Platform information: Windows 10
 - cx_Freeze version: 6.11.0
 - Python version: 3.9

**Comment by marcelotduarte** [comment]
You can test the fix using:
`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by ubalklen** [comment]
I can confirm the patch fixed the issue on my side.

**Comment by ofek** [comment]
FYI all backends will do this soon https://peps.python.org/pep-0639/#license-files-in-project-formats

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.11.1](https://github.com/marcelotduarte/cx_Freeze/releases/tag/v6.11.1) has just been released.
pip install --upgrade cx_Freeze
