### ISSUE TITLE
How to use cx_Freeze with python config file?

### ISSUE THREAD

**Issue by surachai45** [marcelotduarte/cx_Freeze#1523]
Dear Admin
I develop python application and save configuration in settings.py. After I compile with cx_Freeze py file was compiled to pyc file in library.zip. I would like to change the configuration file after install. Could I save configuration file in py format and change this file without compilation. I try but it is not effected.

BestRegard,
Surachai Locharoen

**Comment by surachai45** [comment]
python 3.8 and cx_Freeze 6.10

**Comment by marcelotduarte** [comment]
I think that #1359 is similar (and w/ lots of off-topic).
