### ISSUE TITLE
Installers no longer work on Windows 11

### ISSUE THREAD

**Issue by wsarce** [marcelotduarte/cx_Freeze#1530]
**Describe the bug**
cx_Freeze installers fail to install on Windows 11.  Previously working installers no longer work either.

**To Reproduce**
Run `python cx_freeze_setup.py bdist_msi`
Install generated test-win64.msi file

**Expected behavior**
The installer will display an error window saying "Installer stopped prematurely."

**Screenshots**
![image](https://user-images.githubusercontent.com/22334349/175821911-ff790168-f06b-4566-a5ec-cfb272a293c2.png)

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Microsoft Windows 11 Home (10.0.22621 Build 22621)
 - OS architecture (e.g. amd64): x64
 - cx_Freeze version [e.g. 6.11]: 6.11.1
 - Python version [e.g. 3.10]: 3.8

**Test Scripts**
_test.py_
```
import tkinter as tk


root = tk.Tk()
root.mainloop()
```
_cx_freeze_setup.py_
```
import sys
from cx_Freeze import setup, Executable


base = None
if sys.platform == "win32":
    base = "Win32GUI"

executable = [Executable("test.py",
                         targetName="test.exe",
                         base=base,
                         shortcutName="test",
                         shortcutDir="MyProgramMenu",
                         ),]

setup(name="test",
      executables=executable)
```

**Comment by wsarce** [comment]
With Windows 11, it seems like having multiple versions of the same software installed leads to an inability to install future versions.  Uninstalling previous versions of the software using Apps -> Installed Apps -> Uninstall and then installing the most recent version worked.  

Before this, various errors were popping up in a log of the install including an inability to resolve various paths that were used for shortcuts, etc.

Helpful reference: https://docs.microsoft.com/en-us/troubleshoot/windows-server/application-management/msi-installation-error-1603

**Comment by marcelotduarte** [comment]
> With Windows 11, it seems like having multiple versions of the same software installed leads to an inability to install future versions.

Have you used [upgrade_code](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-upgrade_code)?

**Comment by wsarce** [comment]
> > With Windows 11, it seems like having multiple versions of the same software installed leads to an inability to install future versions.
> 
> Have you used [upgrade_code](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-upgrade_code)?

No, I haven't seen that option before.  Could it be that my programs were using the same GUID internally by Windows?  Two distinct packaged programs were having this issue and, after uninstalling previous versions for one, both install successfully.  

Are there any limits on the GUID selection for the bdist_msi command or does Windows associate it with my program?

**Comment by marcelotduarte** [comment]
As doc says, you can use it to reinstall the program:
"define the GUID of the upgrade code for the package that is created; this is used to force removal of any packages created with the same upgrade code prior to the installation of this one; the valid format for a GUID is {XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX} where X is a hex digit. Refer to [Windows GUID](https://docs.microsoft.com/en-us/windows/win32/api/guiddef/ns-guiddef-guid)."
For each program you must define a different upgrade_code.
There are another variable, product_code, that are generated internally if you do not provide one, product_code.

Check issue #585
