### ISSUE TITLE
PySide6 zip_include_packages

### ISSUE THREAD

**Issue by ecejeff** [marcelotduarte/cx_Freeze#1546]
I'm porting my application from PySide2 to PySide6. I'm trying to use PySide6 with `'zip_include_packages': ['*']`, as that's the only way I've found to get reasonable installer sizes.

I'm using the following versions of things:
- Python 3.10.4
- cx_Freeze 6.11.1

and the cx_Freeze example samples/pyside6

### Using PySide6 6.3.1:

When using
```
'zip_include_packages': ['*'],
'zip_exclude_packages': [
    'PySide6',
    'shiboken6',
],
```
it works, but the build directory size is 395MB.

When using
```
'zip_include_packages': ['*'],
'zip_exclude_packages': [
    'shiboken6',
],
```
the directory size is 45MB but it gives the following error:
![image](https://user-images.githubusercontent.com/10063217/177415509-523932c3-c01f-48c0-a4a5-cea1e02f38b1.png)

### Using PySide6 6.2.4:

When using
```
'zip_include_packages': ['*'],
'zip_exclude_packages': [
    'PySide6',
    'shiboken6',
],
```
it works, but the directory size is 380MB.

When using
```
'zip_include_packages': ['*'],
'zip_exclude_packages': [
    'shiboken6',
],
```
it gives the following error:
![image](https://user-images.githubusercontent.com/10063217/177414462-5bb40ec9-22d1-4fda-8830-b541d60b23e9.png)

I would really prefer to use PySide6 version 6.3.1 as it has some bug fixes for high DPI monitors that 6.2.4 doesn't have.

**Comment by marcelotduarte** [comment]
I worked in hooks for pyside6 recently (PR #1533)
To reduce size I tested it using "zip_include_packages": ["PySide6"] 

You can test it using the development version:
`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by ecejeff** [comment]
That works!

The development version (cx-Freeze==6.12.0.dev1) works with my preferred configuration:
```
'zip_include_packages': ['*'],
'zip_exclude_packages': [
    'shiboken6',
],
```
and PySide6 version 6.3.1. The resulting directory is 95MB.

There's a lot of duplicate Qt6*.dlls at various levels. For example, Qt6Core.dll is present in the following locations:
- lib\PySide6\plugins\imageformats
- lib\PySide6\plugins\platforms
- lib\PySide6\plugins\styles
- lib\PySide6

The program still runs fine after deleting all of the Qt*.dlls in the plugins directory.

This isn't really a problem for me though, as even with the duplicates my program's installer sizes are:
- Old installer with PySide2: 49 MB
- New installer with PySide6: 47 MB

So clearly the duplicates are being compressed with no difficulty, and even a slight size advantage.

**Comment by marcelotduarte** [comment]
> There's a lot of duplicate Qt6*.dlls at various levels.

This is a know issue #1372

**Comment by ecejeff** [comment]
Thanks for the link. It's not an actual problem for my use case, and my main issue has been resolved with the development version.
