### ISSUE TITLE
Required environment variables TCL_LIBRARY and TK_LIBRARY not set by Python 3.5

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#155]
Originally reported by: **Aivar Annamaa (Bitbucket: [aivarannamaa](https://bitbucket.org/aivarannamaa), GitHub: [aivarannamaa](https://github.com/aivarannamaa))**

----------------------------------------

When freezing Tkinter programs in Windows 7 with Python 3.5 32bit, cx_freeze fails, because it expects environment variables TCL_LIBRARY and TK_LIBRARY to be set.

A workarond of setting these manually seems to work

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/155

**Comment by anthony-tuininga** [comment]
*Original comment by* **David Pratt (Bitbucket: [dave_p](https://bitbucket.org/dave_p), GitHub: Unknown)**:

----------------------------------------

Could you specify exactly how to manually set the TCL_LIBRARY and TK_LIBRARY variables?  I'm getting an error when trying to freeze a python file that uses pygame which says:
"File "C:\Program Files (x86)\Python 3.5\lib\os.py", line 681, in __getitem__
KeyError: 'TCL_LIBRARY'"

I've tried editing the os.py file but it doesn't change my error message at all.  Any suggestions?

**Comment by anthony-tuininga** [comment]
*Original comment by* **David Pratt (Bitbucket: [dave_p](https://bitbucket.org/dave_p), GitHub: Unknown)**:

----------------------------------------

Sorry, the error says:
...
"File "C:\Program Files (x86)\Python 3.5\lib\os.py", line 681, in getitem raises KeyError(key) from None
KeyError: 'TCL_LIBRARY'"

**Comment by anthony-tuininga** [comment]
*Original comment by* **Aivar Annamaa (Bitbucket: [aivarannamaa](https://bitbucket.org/aivarannamaa), GitHub: [aivarannamaa](https://github.com/aivarannamaa))**:

----------------------------------------

I created a bat file for running cx_freeze:


```
#!bat

set TCL_LIBRARY=C:\Python35\tcl\tcl8.6
set TK_LIBRARY=C:\Python35\tcl\tcl8.6
... execute cx_freeze ...
```

**Comment by anthony-tuininga** [comment]
*Original comment by* **David Pratt (Bitbucket: [dave_p](https://bitbucket.org/dave_p), GitHub: Unknown)**:

----------------------------------------

So does that go inside the "setup.py" file that is used to freeze my other .py file?

-----------
from cx_Freeze import setup, Executable

set TCL_LIBRARY = C:\Program Files (x86)\Python 3.5\tcl\tcl8.6
set TK_LIBRARY = C:\Program Files (x86)\Python 3.5\tcl\tcl8.6

build_exe_options = {'excludes': ['Tkinter']}
script = [Executable('knit2.py')]


setup(
    name = '',
    version = '',
    description = '',
    options = {'build_exe': build_exe_options},
    executables = script
    )
-----------

**Comment by anthony-tuininga** [comment]
*Original comment by* **David Pratt (Bitbucket: [dave_p](https://bitbucket.org/dave_p), GitHub: Unknown)**:

----------------------------------------

from cx_Freeze import setup, Executable

set TCL_LIBRARY = C:\Program Files (x86)\Python 3.5\tcl\tcl8.6
set TK_LIBRARY = C:\Program Files (x86)\Python 3.5\tcl\tcl8.6

build_exe_options = {'excludes': ['Tkinter']}
script = [Executable('knit2.py')]


setup(
    name = '',
    version = '',
    description = '',
    options = {'build_exe': build_exe_options},
    executables = script
    )

**Comment by anthony-tuininga** [comment]
*Original comment by* **Turson (Bitbucket: [Tor_Yohanson](https://bitbucket.org/Tor_Yohanson), GitHub: Unknown)**:

----------------------------------------

Hi! Tried cx_Freeze yesterday and got the same error.
Solved it with adding to my setup.py these lines:


```
#!python
import os

os.environ['TCL_LIBRARY'] = "C:\\Program Files (x86)\\Python35-32\\tcl\\tcl8.6"
os.environ['TK_LIBRARY'] = "C:\\Program Files (x86)\\Python35-32\\tcl\\tk8.6"

```

Also, for correct work of tkinter GUI, I've imported tk86.dll and tcl86t.dll to exe.win* folder.

**Comment by TOLoneWolf** [comment]
hooks.py
```
def load_tkinter(finder, module):
    """the tkinter module has data files that are required to be loaded so
       ensure that they are copied into the directory that is expected at
       runtime."""
    if sys.platform == "win32":
        import tkinter
        import _tkinter
        dummy_tkinter_object = tkinter.Tk()  # Used to get the current tcl, tc libraries.
        os.environ["TCL_LIBRARY"] = os.path.normpath(dummy_tkinter_object.tk.exprstring('$tcl_library'))
        os.environ["TK_LIBRARY"] = os.path.normpath(dummy_tkinter_object.tk.exprstring('$tk_library'))
        tclSourceDir = os.environ["TCL_LIBRARY"]
        tkSourceDir = os.environ["TK_LIBRARY"]
        finder.IncludeFiles(tclSourceDir, "tcl")
        finder.IncludeFiles(tkSourceDir, "tk")
        for sys_path in sys.path:
            if sys_path.endswith("DLLs"):
                if os.path.exists(sys_path):
                    dll_files = os.listdir(sys_path)
                    for dll in dll_files:
                        if dll.startswith('tcl') and dll.endswith('.dll'):
                            finder.IncludeFiles(os.path.join(sys_path, dll), dll)
                            continue
                        elif dll.startswith('tk') and dll.endswith('.dll'):
                            finder.IncludeFiles(os.path.join(sys_path, dll), dll)
                            continue
```
This fixes the issue for me on windows when trying to freeze my tkinter GUI program.

**Comment by marcelotduarte** [comment]
PR #559 solve it.
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
