### ISSUE TITLE
cx_freeze includes too many packages in the frozen version

### ISSUE THREAD

**Issue by gbaudic** [marcelotduarte/cx_Freeze#1570]
**Describe the bug**
The lib folder produced while freezing contains way more packages than what would be expected based on the frozen code. 

**To Reproduce**
I used the pyside2 sample from the cx_freeze repository, modified as follows to include numpy too so it becomes more representative of my real project in terms of dependencies. The setup.py script remains untouched. 

```
"""A simple script to demonstrate PySide2."""

import sys

from PySide2.QtCore import Qt
from PySide2.QtWidgets import QApplication, QLabel, QWidget
from numpy import zeros  # added line


def main():
    app = QApplication(sys.argv)
    window = QWidget()
    window.setWindowTitle("Simple")
    window.setGeometry(300, 300, 300, 300)
    label = QLabel(window)
    label.setText("Hello World!")
    label.setGeometry(0, 0, 300, 300)
    label.setAlignment(Qt.AlignCenter)
    matrix = zeros((10, 10))  # added line
    window.show()
    return app.exec_()


if __name__ == "__main__":
    sys.exit(main())
```

**Expected behavior**
The frozen lib directory should not contain packages which are not used by the frozen app, such as, in this case, pandas, torch, sqlite3, PyQt5, pythonnet... With the simple example above, the frozen app directory takes 2.6 GB!

**Screenshots**
NA

**Desktop:**
 - Platform information: Windows 10 64-bit
 - OS architecture: amd64
 - cx_Freeze version: 6.10, as provided by the WinPython 3.10.4.0 distribution
 - Python version: 3.10.4, as provided by the WinPython 3.10.4.0 distribution 

**Additional context**
I have only seen this issue so far on Python installs where a lot of packages are installed. It does not seem to be Windows-specific, as I noticed a similar behavior on a Linux install with ~200 packages installed.  
It seems to me that cx_freeze is going too far when looking for potential dependencies. A workaround could be to work with cx_freeze only when in a virtualenv, where only the necessary packages are installed (which is not the case here), but in this case I think this should be documented.  
Note that the frozen app works perfectly.

**Comment by marcelotduarte** [comment]
> I have only seen this issue so far on Python installs where a lot of packages are installed. It does not seem to be Windows-specific, as I noticed a similar behavior on a Linux install with ~200 packages installed.

This is the key for this issue. cx_Freeze follows the imports.


> A workaround could be to work with cx_freeze only when in a virtualenv, where only the necessary packages are installed

This is recommended install option.

An another way to block cx_Freeze to follow the imports is using the exclude option. In the setup.py of pyside2 sample has some [excludes](https://github.com/marcelotduarte/cx_Freeze/blob/main/samples/pyside2/setup.py#L23), like tkinter, and you can add others that you have in your system. You must use the name as it is imported.

```
        # exclude packages that are not really needed
        "excludes": [
            "tkinter",
            "unittest",
            "email",
            "http",
            "xml",
            "pydoc",
            # add more packages here.
        ]
```

**Comment by gbaudic** [comment]
Thank you for the quick and clear explanation! Indeed, it works much better on the same installation and freezing the same code when using a virtualenv.  
I still think that this fact (not using cx_freeze on big installs) should be documented more clearly, maybe in the FAQ page of the documentation. I can initiate a PR for this; otherwise, this issue can be closed.

**Comment by marcelotduarte** [comment]
> I can initiate a PR for this

Feel free to contribute!
