### ISSUE TITLE
No way to use asyncio in a Windows service

### ISSUE THREAD

**Issue by fraca7** [marcelotduarte/cx_Freeze#1571]
The ProactorEventLoop calls `signal.set_wakeup_fd` when instantiated. This leads to the "set_wakeup_fd only works in main thread of the main interpreter" error. It seems that neither the service handler's `__init__`, `initialize`, or `run` methods are called from the main interpreter thread. Even trying to instantiate the loop at the global level doesn't work, so I guess the module is not imported from the main thread.

So there is no way to use asyncio in a Windows service ?

Platform: Windows 10, 64 bits
cx_Freeze version 6.11.1
Python 3.10.5

**Comment by marcelotduarte** [comment]
I can't answer this question for you, but there's a gist that might be able to:
https://gist.github.com/mgrandi/0cf9e603135eda176534

If u need cx_Logging for py3.10 use:
pip install --extra-index-url https://marcelotduarte.github.io/packages/ cx_Logging

**Comment by fraca7** [comment]
I've come across this already. This is very old:

  1. The case of the service methods is wrong (Run instead of run, etc), so it won't even work as is
  2. Is uses the "asyncio.async" function which have been deprecated waaaaaay back since "async" is a reserved word from Python 3.7 on

This gist seems to show that at some point, either the handler's constructor was invoked from the main interpreter thread, or the Proactor event loop didn't use set_wakeup_fd, or set_wakeup_fd didn't check the calling thread, whatever. Anyway it doesn't work any more.

**Comment by fraca7** [comment]
Looking at the source (Win32Service.c), the Python interpreter is indeed initialized in wmain(), the import and instantiation done from Service_Main, which is called (I think) from a service manager thread. A simple fix for this would be to import and instantiate the handler class from wmain() instead.

The only potential drawback is that it would break code that depends on being in the SCM thread in `__init__` (is that even possible), but such code belongs to initialize() anyway. I can make a PR if you're OK with this.

**Comment by fraca7** [comment]
I also see that there's a fallback to CamelCase methods in there, for backward compatibility I guess, but the gist still won't work with Python >= 3.7 :)

**Comment by marcelotduarte** [comment]
> I also see that there's a fallback to CamelCase methods in there ... but the gist still won't work

You can convert to sneak, SessionChanged become session_changed....

> The only potential drawback is that it would break code that depends on being in the SCM thread in __init__ (is that even possible), but such code belongs to initialize() anyway. I can make a PR if you're OK with this.

You can send a PR and I'll try to get @anthony-tuininga to review it for me....

**Comment by fraca7** [comment]
Okay! I'll work on this and send a PR monday (early week-end now)

**Comment by fraca7** [comment]
Done in PR #1572. I added a sample of service using asyncio. It works well for my own code.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.12.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.12.0) has just been released.
