### ISSUE TITLE
v6.11.1 install from source fail: cannot open cx_Logging.lib

### ISSUE THREAD

**Issue by WillyJL** [marcelotduarte/cx_Freeze#1574]
**Describe the bug**
Install from source failed at tag v6.11.1 on GitHub Actions:
```bash
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\libs /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" advapi32.lib cx_Logging.lib delayimp.lib build\temp.win-amd64-3.10\Release\source/bases/Win32Service.obj /OUT:build\lib.win-amd64-3.10\cx_Freeze\bases\Win32Service-cp310-win_amd64.exe /DELAYLOAD:cx_Logging.cp310-win_amd64.pyd /MANIFEST
LINK : fatal error LNK1181: cannot open input file 'cx_Logging.lib'
```

**To Reproduce**
- Clone and checkout v6.11.1
- Install with `python -m pip install -e ./`
- Fails with above error

**Expected behavior**
Installs fine

**Desktop:**
 - Platform information: Microsoft Windows Server 2022 10.0.20348
 - OS architecture: I think amd64
 - cx_Freeze version: v6.11.1
 - Python version: 3.10.5

**Additional context**
Full log:
<details>
<summary>Expand</summary>
<pre><code>
Obtaining file:///D:/a/F95Checker/F95Checker/cx_Freeze
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting lief>=0.11.5
  Downloading lief-0.12.1-cp310-cp310-win_amd64.whl (4.9 MB)
     ---------------------------------------- 4.9/4.9 MB 11.1 MB/s eta 0:00:00
Collecting setuptools<=60.10.0,>=59.0.1
  Using cached setuptools-60.10.0-py3-none-any.whl (1.1 MB)
Collecting packaging>=21.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     -------------------------------------- 40.8/40.8 kB 984.2 kB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ---------------------------------------- 98.3/98.3 kB 2.8 MB/s eta 0:00:00
Installing collected packages: setuptools, pyparsing, lief, packaging, cx-Freeze
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
  Running setup.py develop for cx-Freeze
    error: subprocess-exited-with-error
    
    python setup.py develop did not run successfully.
    exit code: 1
    
    [41 lines of output]
    running develop
    C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-dx5s800r\overlay\Lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-dx5s800r\overlay\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    writing cx_Freeze.egg-info\PKG-INFO
    writing dependency_links to cx_Freeze.egg-info\dependency_links.txt
    writing entry points to cx_Freeze.egg-info\entry_points.txt
    writing requirements to cx_Freeze.egg-info\requires.txt
    writing top-level names to cx_Freeze.egg-info\top_level.txt
    reading manifest file 'cx_Freeze.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'doc/src/license.rst'
    writing manifest file 'cx_Freeze.egg-info\SOURCES.txt'
    running build_ext
    running install_include
    copying source/bases/cx_Logging.h -> C:/hostedtoolcache/windows/Python/3.10.5/x64/include
    creating build
    creating build\temp.win-amd64-3.10
    creating build\temp.win-amd64-3.10\Release
    creating build\temp.win-amd64-3.10\Release\source
    creating build\temp.win-amd64-3.10\Release\source\bases
    "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\hostedtoolcache\windows\Python\3.10.5\x64\include -IC:\hostedtoolcache\windows\Python\3.10.5\x64\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsource/bases/Console.c /Fobuild\temp.win-amd64-3.10\Release\source/bases/Console.obj
    Console.c
    creating D:\a\F95Checker\F95Checker\cx_Freeze\build\lib.win-amd64-3.10
    creating D:\a\F95Checker\F95Checker\cx_Freeze\build\lib.win-amd64-3.10\cx_Freeze
    creating D:\a\F95Checker\F95Checker\cx_Freeze\build\lib.win-amd64-3.10\cx_Freeze\bases
    "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\libs /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" build\temp.win-amd64-3.10\Release\source/bases/Console.obj /OUT:build\lib.win-amd64-3.10\cx_Freeze\bases\Console-cp310-win_amd64.exe /MANIFEST
    Generating code
    Finished generating code
    "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\hostedtoolcache\windows\Python\3.10.5\x64\include -IC:\hostedtoolcache\windows\Python\3.10.5\x64\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsource/bases/Win32GUI.c /Fobuild\temp.win-amd64-3.10\Release\source/bases/Win32GUI.obj
    Win32GUI.c
    "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\libs /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" user32.lib build\temp.win-amd64-3.10\Release\source/bases/Win32GUI.obj /OUT:build\lib.win-amd64-3.10\cx_Freeze\bases\Win32GUI-cp310-win_amd64.exe /MANIFEST
    Generating code
    Finished generating code
    "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\hostedtoolcache\windows\Python\3.10.5\x64\include -IC:\hostedtoolcache\windows\Python\3.10.5\x64\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsource/bases/Win32Service.c /Fobuild\temp.win-amd64-3.10\Release\source/bases/Win32Service.obj
    Win32Service.c
    "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\libs /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" advapi32.lib cx_Logging.lib delayimp.lib build\temp.win-amd64-3.10\Release\source/bases/Win32Service.obj /OUT:build\lib.win-amd64-3.10\cx_Freeze\bases\Win32Service-cp310-win_amd64.exe /DELAYLOAD:cx_Logging.cp310-win_amd64.pyd /MANIFEST
    LINK : fatal error LNK1181: cannot open input file 'cx_Logging.lib'
    error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
    [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

python setup.py develop did not run successfully.
exit code: 1

[41 lines of output]
running develop
C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-dx5s800r\overlay\Lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-dx5s800r\overlay\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing cx_Freeze.egg-info\PKG-INFO
writing dependency_links to cx_Freeze.egg-info\dependency_links.txt
writing entry points to cx_Freeze.egg-info\entry_points.txt
writing requirements to cx_Freeze.egg-info\requires.txt
writing top-level names to cx_Freeze.egg-info\top_level.txt
reading manifest file 'cx_Freeze.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'doc/src/license.rst'
writing manifest file 'cx_Freeze.egg-info\SOURCES.txt'
running build_ext
running install_include
copying source/bases/cx_Logging.h -> C:/hostedtoolcache/windows/Python/3.10.5/x64/include
creating build
creating build\temp.win-amd64-3.10
creating build\temp.win-amd64-3.10\Release
creating build\temp.win-amd64-3.10\Release\source
creating build\temp.win-amd64-3.10\Release\source\bases
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\hostedtoolcache\windows\Python\3.10.5\x64\include -IC:\hostedtoolcache\windows\Python\3.10.5\x64\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsource/bases/Console.c /Fobuild\temp.win-amd64-3.10\Release\source/bases/Console.obj
Console.c
creating D:\a\F95Checker\F95Checker\cx_Freeze\build\lib.win-amd64-3.10
creating D:\a\F95Checker\F95Checker\cx_Freeze\build\lib.win-amd64-3.10\cx_Freeze
creating D:\a\F95Checker\F95Checker\cx_Freeze\build\lib.win-amd64-3.10\cx_Freeze\bases
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\libs /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" build\temp.win-amd64-3.10\Release\source/bases/Console.obj /OUT:build\lib.win-amd64-3.10\cx_Freeze\bases\Console-cp310-win_amd64.exe /MANIFEST
Generating code
Finished generating code
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\hostedtoolcache\windows\Python\3.10.5\x64\include -IC:\hostedtoolcache\windows\Python\3.10.5\x64\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsource/bases/Win32GUI.c /Fobuild\temp.win-amd64-3.10\Release\source/bases/Win32GUI.obj
Win32GUI.c
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\libs /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" user32.lib build\temp.win-amd64-3.10\Release\source/bases/Win32GUI.obj /OUT:build\lib.win-amd64-3.10\cx_Freeze\bases\Win32GUI-cp310-win_amd64.exe /MANIFEST
Generating code
Finished generating code
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\hostedtoolcache\windows\Python\3.10.5\x64\include -IC:\hostedtoolcache\windows\Python\3.10.5\x64\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsource/bases/Win32Service.c /Fobuild\temp.win-amd64-3.10\Release\source/bases/Win32Service.obj
Win32Service.c
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\libs /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64 /LIBPATH:C:\hostedtoolcache\windows\Python\3.10.5\x64\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" advapi32.lib cx_Logging.lib delayimp.lib build\temp.win-amd64-3.10\Release\source/bases/Win32Service.obj /OUT:build\lib.win-amd64-3.10\cx_Freeze\bases\Win32Service-cp310-win_amd64.exe /DELAYLOAD:cx_Logging.cp310-win_amd64.pyd /MANIFEST
LINK : fatal error LNK1181: cannot open input file 'cx_Logging.lib'
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Process completed with exit code 1.
</code></pre>
</details>

Tag 6.10 works fine

Also v6.11.1 has the leading v while everything else doesn't, just in case you didn't notice

**Comment by marcelotduarte** [comment]
cx_Loging has no support for py310, so you must install it before install cx_Freeze from source.
Check how to do here: https://github.com/marcelotduarte/cx_Freeze/blob/main/.github/workflows/ci.yml#L39



> Tag 6.10 works fine

You have used py310 or py39?



> Also v6.11.1 has the leading v while everything else doesn't, just in case you didn't notice

There was this change since v6.11.0.

**Comment by WillyJL** [comment]
> You have used py310 or py39?

I was using python 3.10.4 with cx_Freeze 6.10. Today I updated my workflow to use 3.10.x, so 3.10.5 for now, and v6.11.1. Then reverted to 6.10, but that still works fine with 3.10.5

**Comment by marcelotduarte** [comment]
6.10 limited the version of setuptools, so cx_Logging was installed together. But with newer setuptools, it build cx_Freeze in isolated environment, so can cause errors.
But you can adapt like I make in the ci tests.
