### ISSUE TITLE
Adding publisher field and icon to Add or Remove Programs entry

### ISSUE THREAD

**Issue by wsarce** [marcelotduarte/cx_Freeze#1575]
How do I add a publisher name to my MSI file so that when installed it's entry under the "Add or Remove Programs" menu has either no publisher info (Windows 10) or it lists "UNKNOWN" (Windows 11).  How can I fill this field?

Also, is there a way to add my icon file to this entry as well? 

I'm using cx-Freeze 6.11.1

The Microsoft information on these fields can be found [here](https://docs.microsoft.com/en-us/windows/win32/msi/configuring-add-remove-programs-with-windows-installer).  I'm not sure how to set these variables.

Any direction would be helpful.

**Comment by wsarce** [comment]
Adding `"install_icon": r'images\icon.ico',` to my bdist_msi_options dict worked to resolve the icon issue.

**Comment by marcelotduarte** [comment]
[install_icon](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-install_icon) ok

Options name, version, and author in setup are used in MSI too.

**Comment by wsarce** [comment]
They are used in the MSI, but the author doesn't make it into the publisher field, which is by default set to UNKNOWN.  I need a way to set that publisher field.

I tried adding a keyword argument `publisher` into the setup function, which doesn't update the publisher field in the installed program.

**Comment by marcelotduarte** [comment]
Some keywords used are inherited from [setuptools](https://setuptools.pypa.io/en/latest/references/keywords.html).

Maybe you can find more information in the code for [bdist_msi](https://github.com/marcelotduarte/cx_Freeze/blob/main/cx_Freeze/command/bdist_msi.py).

Sorry for the lack of documentation.

**Comment by wsarce** [comment]
Okay, if you set `author`, the publisher field gets set to that, but it's only visible when opened in a software like Advanced Installer.  That was quite the rabbit hole to jump down looking through the bdist_msi source.

`url` sets the Support Link field.

`author_email` sets the Contact field.

Thank you for taking the time to help me find the correct rabbit hole to go down.
