### ISSUE TITLE
Tk can't load PNGs in 6.12.0.dev1

### ISSUE THREAD

**Issue by black-sliver** [marcelotduarte/cx_Freeze#1577]
**Describe the bug**

6.10.0 was working
6.11.0 broke embedding Tk on Linux
```
  File "tkinter/__init__.py", line 2299, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: [...]
```
6.12.0.dev1 fixes that, but has now a different problem:
```
  File "LttPAdjuster.py", line 386, in set_icon
    logo = tk.PhotoImage(file=local_path('data', 'icon.png'))
  File "tkinter/__init__.py", line 4093, in __init__
  File "tkinter/__init__.py", line 4038, in __init__
_tkinter.TclError: couldn't recognize data in image file "/tmp/.mount_Archipyq5USL/opt/Archipelago/data/icon.png"
```
```
$ file /tmp/.mount_Archipyq5USL/opt/Archipelago/data/icon.png
/tmp/.mount_Archipyq5USL/opt/Archipelago/data/icon.png: PNG image data, 128 x 128, 8-bit/color RGBA, non-interlaced
```
I have no idea how freezing Tk works, but i assume it's not finding the PNG backend?

**To Reproduce**

freeze an application that uses tk.PhotoImage(file='path/to/file.png')

**Expected behavior**

tk.PhotoImage() loading the PNG

**Desktop:**

 - Platform information: Arch Linux
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version: 6.12.0.dev1
 - Python version: 3.10.5
 - tkinter.TkVersion: 8.6

**Additional context**

In the 6.10 freeze we don't have a libpng in libs/, but one in libs/Kivy.libs (that should not be used by tk however)
```
$ ldd _tkinter.cpython-310-x86_64-linux-gnu.so | grep png
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f55d9b8f000)
```
In the 6.12.0.dev1 freeze there is a libpng15-ce838cd1.so.15.13.0 in libs/
```
$ ldd _tkinter.cpython-310-x86_64-linux-gnu.so | grep png
	libpng15-ce838cd1.so.15.13.0 => /tmp/.mount_ArchipC39yct/opt/Archipelago/lib/./../lib/libpng15-ce838cd1.so.15.13.0 (0x00007f57ee200000)
$ file /tmp/.mount_ArchipC39yct/opt/Archipelago/lib/./../lib/libpng15-ce838cd1.so.15.13.0
/tmp/.mount_ArchipC39yct/opt/Archipelago/lib/./../lib/libpng15-ce838cd1.so.15.13.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9dce7a7cadc13c5d4a9bd1004943f0f391f01af7, stripped
```

**Comment by marcelotduarte** [comment]
To test, I use the Tkinter [sample](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/tkinter). 
Can you adapt it to demonstrate the issue so I can fix it.
We could use the favicon.png in the icon samples.

**Comment by black-sliver** [comment]
~~https://github.com/black-sliver/cx_Freeze/commit/c4663f864828ecc16016097f5f484b4d679d5eeb~~
https://github.com/black-sliver/cx_Freeze/commit/a0e7fa07c8bb9dfd9ca021d0a202346877842e90

Should I PR this?

**Comment by marcelotduarte** [comment]
> Should I PR this?

It's a good idea. I asked you to adapt the sample because I don't use Tkinter, I don't have the skills with it.
If you can improve the layout to show the figure, that would be good.

Anyway, I was able to reproduce the problem.

In version 6.11 I started using manylinux to allow applications to run on older versions of linux. But manylinux2014 comes with tk8.5, hence the cause of the bug.
I made a patch for manylinux to use tk 8.6.12 and in my tests, it worked.

To use cx_Freeze 6.11.1 with the same behavior as 6.10, you can build and install it like this:
`pip install cx-freeze --no-binary cx-freeze`

**Comment by black-sliver** [comment]
>  If you can improve the layout to show the figure, that would be good.

The icon should be displayed as the window and taskbar icon. Is that not good/enough? (Tested on windows and linux)

**Comment by marcelotduarte** [comment]
> The icon should be displayed as the window and taskbar icon. Is that not good/enough?

In my CI tests, it is not shown in Linux. But on my desktop it is.
You can test with dev release:
`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

Results for linux, windows and macos.
![tkinter-0-test_tkinter-linux-x86_64-3 10](https://user-images.githubusercontent.com/12752334/183962514-a77e95ca-224d-47f4-80c9-e1d8fe1d0f48.png)

![tkinter-0-test_tkinter-win-amd64-3 10](https://user-images.githubusercontent.com/12752334/183962552-ee68dfc8-a482-4503-aeb3-e76c5fd0a85b.png)

![tkinter-0-test_tkinter-macosx-10 15-x86_64-3 10](https://user-images.githubusercontent.com/12752334/183962586-c30c6b07-c150-44a2-bfc9-94e6e187a4c0.png)

**Comment by black-sliver** [comment]
> In my CI tests, it is not shown in Linux. But on my desktop it is.

Should throw an exception if the load fails, so should still be fine for testing. Let me know in the PR if you absolutely want to have it changed, (I have very little experience with Tk.)

>  You can test with dev release:
> `pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

Works. Thank you!

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.12.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.12.0) has just been released.
