### ISSUE TITLE
ImportError: this platform is not supported: No module named 'pynput.keyboard._darwin'

### ISSUE THREAD

**Issue by xuanloct4** [marcelotduarte/cx_Freeze#1578]
**Describe the bug**
Return exception "this platform is not supported: No module named 'pynput.keyboard._darwin'" after making program successfully with cz_freeze

**To Reproduce**
- In my gui.py file, it imports pynput.mouse
 from pynput.mouse import Controller
- Run the following command, it returns success
cxfreeze -c  gui.py --target-dir dist
- But when I open the program file (gui) inside the dist folder, it return failure
python3.9/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: No module named 'pynput.keyboard._darwin'

**Desktop (please complete the following information):**
 - OS MacOS BigSur 11.5.2 Intel
 - cx_Freeze version 6.11.1
 - Python version 3.9

**Comment by marcelotduarte** [comment]
Try to add to command:
 --includes pynput.keyboard._darwin 
or 
--packages pynput

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.12.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.12.0) has just been released.

Assuming this has been resolved.
