### ISSUE TITLE
Problem using cx-freeze on Linux (Mint 20.3)

### ISSUE THREAD

**Issue by aiotech-pub** [marcelotduarte/cx_Freeze#1580]
### Discussed in https://github.com/marcelotduarte/cx_Freeze/discussions/1579

<div type='discussions-op-text'>

<sup>Originally posted by **aiotech-pub** August  8, 2022</sup>

I am porting a win32 Python application to Linux and I want to build its executable using cx-freeze. The win32 application works and I am able to build its executable using cx-freeze. In Linux, instead, cx-freeze ends with a strange error:

running build
running build_exe
error: [Errno 2] No such file or directory: '/home/massimo/.local/share/virtualenvs/JanasMagicKey-vnaevMls/lib/python3.8/site-packages/wheel-0.37.1.dist-info/__pycache__

I checked the win32 project and I see there is no pycache folder in its equivalent position so I really do not understand the error itself and what I have to do to solve the problem.
I am working using PyDev and pipenv.
I attached my setup file for Linux (named setup_cx.txt 
[setup_cx.txt](https://github.com/marcelotduarte/cx_Freeze/files/9282386/setup_cx.txt)
instead of setup_cx.py)
</div>

**Comment by marcelotduarte** [comment]
Can you test with the development version?

To install the latest development build:

`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.12.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.12.0) has just been released.

Can you test with 6.12?
