### ISSUE TITLE
Dependencies copied multiple times on windows

### ISSUE THREAD

**Issue by cainesi** [marcelotduarte/cx_Freeze#1590]
**Describe the bug**
The same DLL may be copied into a frozen application multiple times. I think this was a problem that was previously fixed (#366).  

PR #1589 is possibly a fix for this, which would cause all the dependencies to be copied into a single location (the /lib directory). 

**To Reproduce**
Build the pyqt5 sample.  The Qt5Core.dll DLL gets copied into most of the plugin directories (lib\PyQt5\Qt5\plugins).  The multiple copies are unnecessary.

**Expected behavior**
Each DLL should only be copied once.

**Desktop (please complete the following information):**
Windows, using Python 3.9 and cx_Freeze 3.11.1.

**Comment by frmdstryr** [comment]
It seems like this issue has returned.
