### ISSUE TITLE
Potentially incorrect filename for MSI file

### ISSUE THREAD

**Issue by cainesi** [marcelotduarte/cx_Freeze#1592]
**Describe the bug**
When the name of the msi file is specified by passing the target-name parameter to the bdist_msi command, the msi is created with the wrong file name. 

**To Reproduce**
In the "simple" sample, execute bdist_msi with --target-name a.msi.

An msi file is created named "a.msi-0.1-win64.msi".

**Expected behavior**
Create an msi file named "a.msi".  That has historically been the behavior.

**Desktop (please complete the following information):**
Python 3.9 / Cx_freeze 6.11.1 / Windows 10

**Additional context**
I suspect this may have been an unintended change made when the msi module was integrated into cx_freeze?

A "quick and dirty" fix is proposed in PR #1591.

**Comment by marcelotduarte** [comment]
While fixing issue #1510 (fixed in PR #1520), I detected an issue and the fix (PR #1524) probably is incomplete.

**Comment by cainesi** [comment]
Hi @marcelotduarte, it looks like you are correct that the changes in #1524 were the source of the issue.  Is there an easy way to explain what the intended change in #1524? That would help me understand what fix might be appropriate.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.13.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.13.0) has just been released.
