### ISSUE TITLE
PySide6 bloated

### ISSUE THREAD

**Issue by brzGatsu** [marcelotduarte/cx_Freeze#1594]
Hi,

I am using Pyside 6.3.1 and cx-freeze 6.11.1 on Windows 10.

Freezing my app works, however, it is five times the size it used to be with PyQT 5. I noticed that:
- Absolutely everything from PySide is copied over including a lot of stuff that I don't reference, like Qt6WebEngineCore.dll (121 MB), even an examples folder (4.5 MB). My app works totally fine after deleting the mentioned example files.
- Adding PySide6 to zip_include_packages results in an error when starting the exe: 
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\site-packages\cx_Freeze\initscripts_startup_.py", line 120, in run
module_init.run(name + "_main_")
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 16, in run
exec(code, module_main._dict_)
File "MyProject.py", line 8, in <module>
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\PySide6_init_.py", line 143, in <module>
_all_ = _find_all_qt_modules()
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\PySide6_init_.py", line 131, in _find_all_qt_modules
files = os.listdir(location)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\User\\Documents\\Workspace\\Projects\\MyProject\\build\\MyProject\\lib\\library.zip
PySide6'

**Comment by marcelotduarte** [comment]
Try with the latest development build:

`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

It has pyside6 support and I used the sample to test: https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyside6

**Comment by brzGatsu** [comment]
Works, thank you!!

**Comment by brzGatsu** [comment]
Hi, sorry to re-open this. The Devbuild works much better but there is some room for improvement.

I get these files inside lib/PySide6 even though i don't use / import anything of the module:
- Qt6Network.dll
- QtNetwork.pyd

I get a duplicate of the following files inside each folder of lib/PySide6/plugins:
- Qt6Core.dll
- Qt6Gui.dll
- Qt6Widgets.dll (only in "styles")


Deleting these files reduces my app size from 135 MB to 90 MB which is quite substantial.

**Comment by marcelotduarte** [comment]
Please make a new try with the latest development build:

`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by brzGatsu** [comment]
Thank you, much better! No more duplicate Qt6Core/Gui/Widgets.

I do still get Qt6Network though, even though I don't import anything from it (Qt6Network.dll and QtNetwork.pyd in lib/PySide6)

**Comment by marcelotduarte** [comment]
There are modules that depend on QtNetwork. For instance, QtMultimedia, QtWebsockets, etc, and some plugins.
You can exclude it using [excludes](https://cx-freeze.readthedocs.io/en/latest/setup_script.html?#cmdoption-arg-excludes). Use "PySide6.QtNetwork" to exclude.

**Comment by brzGatsu** [comment]
Will do, thanks for the fix!

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.12.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.12.0) has just been released.
