### ISSUE TITLE
Import clr (pythonnet) crashes when frozen with cx_freeze : "ImportError: No module named site"

### ISSUE THREAD

**Issue by borisb39** [marcelotduarte/cx_Freeze#1604]
**Prerequisite**
 - Make sure no duplicated issue has already been reported. You should look for closed issues, too.
 - Make sure you are not asking us to help to solve your specific issue. GitHub issues are opened mainly for development purposes. If you want to ask someone to help to solve your problem, go to some community site like StackOverflow, etc.
 - Make sure your problem is not derived from packaging (e.g. Homebrew).

**Describe the bug**
When I try to import clr once packaged into an executable with cx_freeze it crashes and gives the error: "ImportError: No module named site"

**To Reproduce**

test.py

```python
import clr
```

setup.py

```python
from cx_Freeze import setup, Executable  
cible = Executable(script="test.py",
                   targetName="test.exe")            
setup(version="0.1",
      executables=[cible])
```

PowerShell: create executable package

```PowerShell
python setup.py build
```

PowerShell: move Python.Runtime.dll at correct location

```PowerShell
Move-Item -Path .\build\exe.win-amd64-2.7\Python.Runtime.dll -Destination .\build\exe.win-amd64-2.7\lib\Python.Runtime.dll
```

PowerShell: launch the executable : it crashes

![image](https://user-images.githubusercontent.com/112186960/188686368-f3524694-45e9-4934-b071-eb93f93b8350.png)

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows10 version 1909
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]:  5.1.1
 - Python version [e.g. 3.10]: 2.7.15
- Pythonnet version: 2.5.2
- 
**Additional context**
Everything is working fine when launched in debug. I also noticed that site.pcy is not included in the executable package.

**Comment by marcelotduarte** [comment]
I cannot help with v 5.x
I suggest to you upgrade to python 3.8 as it works with pythonnet.
Similar issues #249 #1049

**Comment by borisb39** [comment]
OK, thanks for the answer anyway.
