### ISSUE TITLE
cx_Freeze completely broken inside of any virtualenv (Python 3.7)

### ISSUE THREAD

**Issue by fpf3** [marcelotduarte/cx_Freeze#1617]
**Describe the bug**
Importing cx_Freeze attempts to load a module which is not present in the virtualenv distutils package. (bdist_msi.py)

Can't find any documentation on performing a cx_Freeze build inside of a venv, but if I copy/paste that module from my global Lib/ directory, it builds just fine.

**To Reproduce**
```
c:\Users\username> py -3.7 -m virtualenv cx_freeze_bug
c:\Users\username> cx_freeze_bug\Scripts\activate.bat
(cx_freeze_bug) c:\Users\username> pip install cx_Freeze==6.6
...
(cx_freeze_bug) c:\Users\username> python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from cx_Freeze import setup, Executable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Public\HgRepos\psoc-xl80\Python3\psoc_venv\lib\site-packages\cx_Freeze\__init__.py", line 4, in <module>
    from .dist import bdist_rpm, build, build_exe, install, install_exe, setup
  File "C:\Users\Public\HgRepos\psoc-xl80\Python3\psoc_venv\lib\site-packages\cx_Freeze\dist.py", line 20, in <module>
    from .windist import bdist_msi
  File "C:\Users\Public\HgRepos\psoc-xl80\Python3\psoc_venv\lib\site-packages\cx_Freeze\windist.py", line 1, in <module>
    import distutils.command.bdist_msi
ModuleNotFoundError: No module named 'distutils.command.bdist_msi'
```

**Expected behavior**
The cx_Freeze module is successfully imported

**Desktop (please complete the following information):**
 - Platform information : Windows 10
 - OS architecture : x86_64
 - cx_Freeze version : 6.6
 - Python version : 3.7.4

**Comment by marcelotduarte** [comment]
With cx_Freeze 6.6 you should use setuptools < 59, if I remember, because setuptools deprecated and removed bdist_msi, so recent setuptools broke cx_Freeze.

cx_Freeze 6.10 incorporated bdist_msi, but I recommend that you use cx_Freeze 6.11.1

> Can't find any documentation on performing a cx_Freeze build inside of a venv, but if I copy/paste that module from my global Lib/ directory, it builds just fine.

In the readme: https://github.com/marcelotduarte/cx_Freeze/#installation
In the docs: https://cx-freeze.readthedocs.io/en/latest/installation.html#installation

**Comment by fpf3** [comment]
Thanks, that appears to have worked.
