### ISSUE TITLE
[Question] cx_Freeze 6.10+ and confuse not working together?

### ISSUE THREAD

**Issue by noahblumADS** [marcelotduarte/cx_Freeze#1621]
Hi, 

I use cx_Freeze to freeze an application I distribute. In this application, I use a package called [confuse](https://github.com/beetbox/confuse) which allows me to load a configuration. 

In my application, I use the command `config = confuse.Configuration('MyApp', __name__)`, where `__name__` points to an empty `__init__.py` to load a default configuration ([Confuse Documentation](https://confuse.readthedocs.io/en/latest/usage.html#basic-usage)). Up until cx_Freeze v6.10, I was able to just include the `__init__.py` file in my `include_files` section of the `setup.py`, and confuse had no problem using that file to find my default configuration when my application was frozen.

However, whenever I try to use a version greater than 6.9, confuse cannot find my default configuration. I have no idea what may have changed in cx_Freeze between version 6.9 and 6.10 that would cause this. If anyone has any suggestions on how to change my `setup.py` so that confuse can find and use `__init__.py` like it does in cx_Freeze 6.9, I would be greatly appreciative.

While I can just use 6.9 for the time being, I would like to resolve my issue so I can use the latest versions. 

Please let me know if you need more information from me on this matter.

**Comment by marcelotduarte** [comment]
Please provide a minimum setup.py and a test app to show this behavior. I'll try to identify the issue.

**Comment by noahblumADS** [comment]
Sorry for the late response. Here is a [repo](https://github.com/noahblumADS/minimal) I set up with the Test App. `setup.py` is located in `src`. 

I ran it with both `cx_Freeze` 6.9 and 6.11.1, and still encountered the issue. 

Please let me know if there's anything else I can do.

**Comment by noahblumADS** [comment]
Hi, just curious if there was any update on this issue. 

Let me know if there's anything I can do to help.

**Comment by marcelotduarte** [comment]
I used your repo to test. 
In setup.py the os.environ is not used. In setup() function has a packages=['modules'] that causes a error, because it does not exist.
```
# Determine the base
import os
import sys
from cx_Freeze import Executable, setup, __version__

base = 'Win32GUI' if sys.platform == 'win32' else None

PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
#os.environ['TCL_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tcl8.6')
#os.environ['TK_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tk8.6')

executables = [Executable(script='main.py',
                          base=base,
                          target_name="TestApp")]

options = {'build_exe': {'build_exe': f"../Executable ({__version__})",
                         'include_files': [#"../src",
                                           "config_default.yaml",
                                           #"__init__.py"
                                           ]}}

setup(options=options,
      name="TestApp",
      version=1.0,
      description="TestApp",
      #packages=['modules'],
      executables=executables)
```
In the main.py I add a line after line 6 using https://confuse.readthedocs.io/en/latest/usage.html#manually-specifying-config-files:
`config.set_file("config_default.yaml")`

**Comment by marcelotduarte** [comment]
Can I close this issue?
