### ISSUE TITLE
ValueError in Module.update_distribution

### ISSUE THREAD

**Issue by cainesi** [marcelotduarte/cx_Freeze#1631]
**Prerequisite**
 Unclear

**Describe the bug**
Freeze fails with a ValueError in Module.update_distribution.  Error arises at the line:

`requires = importlib_metadata.requires(distribution.name) or []`

The error appears to arise because distribution.name is None.

**To Reproduce**
Unclear

**Expected behavior**
No error.

**Desktop (please complete the following information):**
Python 3.9 / OSX.
cx_freeze latest version on main branch.

**Additional context**
#1630 removes the error for me. But I think there is an underlying issue that I am still trying to untangle.  (i.e., I don't think distribution.name should be None in the first place?)

**Comment by marcelotduarte** [comment]
Merged PR #1630. If you understand that this resolves this issue, please, close this.

>  I don't think distribution.name should be None in the first place?

Where?

https://github.com/marcelotduarte/cx_Freeze/blob/main/cx_Freeze/module.py#L163-L167

**Comment by cainesi** [comment]
The issue I was having was that 
`distribution = DistributionCache.from_name(name)`
would sometime return a (non-None) object for which distribution.name was None.   Then the subsequent line
`requires = importlib_metadata.requires(distribution.name) or []`
raised the ValueError.

But your suggestion about re-installing the virtualenv fixed that error.  So I'm able to freeze successfully now without #1630.  So actually not sure if we need #1630?  Maybe it should fail if something does wring with the distribution object?

I think I need to read module.py and importlib_metadata.PathDistribution more carefully at some point to understand what's going on there.

**Comment by marcelotduarte** [comment]
We only need the metadata if it exists. If it gives an error for not finding the metadata, we can ignore it.

[cx_Freeze 6.12.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.12.0) has just been released.

**Comment by cainesi** [comment]
> We only need the metadata if it exists. If it gives an error for not finding the metadata, we can ignore it.

Great. Thanks for the explanation.
