### ISSUE TITLE
PySide2 (and PySide6) creates executables without support for Wayland

### ISSUE THREAD

**Issue by ephyran** [marcelotduarte/cx_Freeze#1634]
**Describe the bug**
When you build a PySide application via cx_Freeze on KDE Plasma, including with the current development build, unless you forcibly ignore Wayland via `QT_QPA_PLATFORM=xcb` when launching, the following occurs when you attempt to run the resulting executable:
```
qt.qpa.wayland: Failed to load client buffer integration: "wayland-egl"
qt.qpa.wayland: Available client buffer integrations: ()
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "xdg-shell-v6" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells ("xdg-shell", "xdg-shell-v6", "wl-shell", "ivi-shell")
```
According to an issue visible [here](https://github.com/pyinstaller/pyinstaller/issues/6483) regarding a similar bug with PyQt5 and PyInstaller, this may be due to a small number of Wayland-specific Qt plugins not being included in the final build, specifically the ones found under PySide2/Qt/plugins/wayland-shell-integration, wayland-graphics-integration-client, wayland-decoration-client, and possibly wayland-graphics-integration-server.

**To Reproduce**
Seems to occur regardless of what you have in your setup.py as long as you use PySide2 or 6 and are on Wayland, but the setup.py I've been using is:
```
from cx_Freeze import setup, Executable
import sys

build_exe_options = {
    "excludes": ["tkinter"],
    "zip_include_packages": ["*"],
    "zip_exclude_packages": ["PySide2.QtNetwork"],
    "excludes": ["PySide2.QtNetwork"],
    "optimize": 2
}

setup(
    name = "-----",
    version = "0.0",
    description = "-----",
    options = {"build_exe": build_exe_options},
    executables = [Executable("src/gui/main.py",
        base = ("Win32GUI"
            if sys.platform == "win32"
            else None))]
)
```

**Expected behavior**
The application should launch without forcibly falling back on X.

**Desktop (please complete the following information):**
 - Platform information: EndeavourOS, 5.15.72-1-lts kernel
 - OS architecture: amd64
 - cx_Freeze version: 6.11.1, 6.12.0.dev2
 - Python version: 3.10

**Comment by marcelotduarte** [comment]
The [pyside2](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyside2) sample works for me with or without wayland activated. I'm using Ubuntu 22.04 LTS.
Using QT_QPA_PLATFORM=wayland it fails.
So, I updated the samples to show how to include the plugins in the [setup.py](https://github.com/marcelotduarte/cx_Freeze/blob/main/samples/pyside2/setup.py) (PR #1636)
Now it works using QT_QPA_PLATFORM=wayland or xcb.

Please test.

I think that in the future I should add it as a default, but in order to optimize, I avoid adding too many plugins, and that's why we have this option to add manually.

**Comment by ephyran** [comment]
This solution works for me as well. Thank you! Closing the issue.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.12.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.12.0) has just been released.
