### ISSUE TITLE
Building a Windows service fails

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#165]
Originally reported by: **Mark Muzenhardt (Bitbucket: [redrooster](https://bitbucket.org/redrooster), GitHub: [redrooster](https://github.com/redrooster))**

----------------------------------------

If I try to build samples/service, the application builds but will not start. It crashes with "Fatal Python error: Py_Initialize: unable to load the file system codec ImportError: No module named "encodings".

I use following Versions: Python 3.4, cx_Freeze 4.3.4, Windows 7

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/165

**Comment by anthony-tuininga** [comment]
*Original comment by* **Adrian Czapnik (Bitbucket: [flashmaker](https://bitbucket.org/flashmaker), GitHub: [flashmaker](https://github.com/flashmaker))**:

----------------------------------------

I have the same problem and found a solution.
In the file cx_Freeze / finder.py change the line 441:
```
#!python

module.code = marshal.load (fp)
```

to: 
```
#!python

module.code = marshal.loads (fp.read ())
```


This change solves the problem for me.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Adrian Czapnik (Bitbucket: [flashmaker](https://bitbucket.org/flashmaker), GitHub: [flashmaker](https://github.com/flashmaker))**:

----------------------------------------

I did some more tests and this change does not bring a solution as previously thought.

I wrote a script that is able to show the error, if any, will be able to occur.

```
#!python

#import time
import codecs
import threading
#import encodings.idna

def lookup():
    #time.sleep(0.1)
    codecs.lookup("idna")

if __name__ == "__main__":
    thr_pool = [threading.Thread(target=lookup) for _ in range(100)]

    for t in thr_pool:
        t.start()

    for t in thr_pool:
        t.join()
```

Typically, the error occurs in the thread of 0 to 12.
If I uncomment 'time.sleep (0.1)' or 'import encodings.idna' this problem will never occur.

The problem occurs regardless of whether it is compiled as win32service or as a Console.

**Comment by marcelotduarte** [comment]
Assuming this has been resolved.
