### ISSUE TITLE
Missing .dll files required by executable in MinGW

### ISSUE THREAD

**Issue by mathiascode** [marcelotduarte/cx_Freeze#1651]
**Describe the bug**

Since cx_Freeze 6.12, executables created in MinGW no longer run, complaining about missing .dll files. The files in question are `libwinpthread-1.dll` and `libgcc_s_seh-1.dll`.

Error message: `The code execution cannot proceed because libgcc_s_seh-1.dll was not found. Reinstalling the program may fix the problem.`

In cx_Freeze 6.11, these files were installed both in the `lib` directory and the same directory as the executable. In cx_Freeze 6.12, they are only installed in the `lib` directory. Copying them to the same directory as the executable makes it work again.

**To Reproduce**

Use any of the sample setup.py scripts in a MinGW environment, and attempt to run the generated executable.

**Expected behavior**

Required .dll files are installed in the correct directory to allow the executable to run.

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): MinGW on Windows Server 2019 (GitHub Actions)
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: 6.12
 - Python version [e.g. 3.10]: 3.10

**Comment by mathiascode** [comment]
I don't think these dlls are used for anything else, so it might just be a case of them being copied to the wrong folder (`lib` instead of the executable folder).

**Comment by marcelotduarte** [comment]
To install the latest development build:

download the package at https://marcelotduarte.github.io/packages/

Install w/ pacman -U

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.13.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.13.0) has just been released.
