### ISSUE TITLE
when will cx_freeze and cx_logging be compatible with python 3.11

### ISSUE THREAD

**Issue by jschwar313** [marcelotduarte/cx_Freeze#1662]
**Describe the bug**
When will cx_freeze and cx_logging be compatible with python 3.11?

**To Reproduce**
Install python 3.11 on windows 10 64-bit and try installing cx_freeze.

**Comment by marcelotduarte** [comment]
Coming soon. I believe within a month. But there are already packages available to test.

https://github.com/marcelotduarte/cx_Freeze#installation

To install the latest development build:

`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze cx_Logging`

**Comment by jschwar313** [comment]
Great.  Let me know once it's ready.  it won't install now.  there are dependencies that won't install that prevent it from installing.  Thanks.

**Comment by marcelotduarte** [comment]
It installs and works! Let me give you the secret ;-)
```
pip install --pre -f https://lief.s3-website.fr-par.scw.cloud/latest/lief/ lief
pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Logging
pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze
```

**Comment by jschwar313** [comment]
Cool.  Thanks so much.  I've installed them and I created the executable again under python 3.11 and I installed it.  I'll see how it goes starting tomorrow.  Thanks again.

**Comment by jschwar313** [comment]
It's working just fine.  Please let me know when lief and cx_logging and cx_freeze are released officially and I'll install those versions.  I want to update my requirements.txt file with those version numbers.  Thanks so much for the help.

**Comment by jschwar313** [comment]
I have a question.  I have three executables created using cx_freeze from three different python files and they are all the same length.  Is the code stored in a DLL somewhere?  I am using windows 10 and cx_freeze version 6.14.0.dev0 like you told me to do.

**Comment by marcelotduarte** [comment]
The executables are a bootstrap code taht calls your code, compiled, in lib/library.zip

**Comment by jschwar313** [comment]
I just uninstalled that version of cx_Freeze and installed version 6.13.1 and it seemed to work.  Is that version now compatible with python 3.11.1?

**Comment by marcelotduarte** [comment]
cx_Freeze has been compatible w/ python 3.11 since release 6.13, but at the release, cx_Logging, and Lief were not.
Bu wheel for cx_Freeze 6.13.1 on windows isn't available. If you have an MS C compiler, then it builds and installs.
Soon I will release a new version.

**Comment by marcelotduarte** [comment]
To install the latest development build [1] compatible with Python 3.11:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

[1] https://github.com/marcelotduarte/cx_Freeze#installation
