### ISSUE TITLE
ImportError when using 'path' option

### ISSUE THREAD

**Issue by d5423197** [marcelotduarte/cx_Freeze#1668]
Hello there,

I am using cx_Freeze to package up my project. When I want to run the app.exe, it shows zlib.dll is missing. But I can find it in the lib folder.

My current solution is to move zlib.dll file from lib to the directory where app.exe is located. It works. 

But I want a long run solution. Any help will be appreciated!

ZD

**Comment by marcelotduarte** [comment]
The guy, I even wanted to help you, but without information, it's difficult. There is a form that if filled out helps a lot. What I can tell you is that it works for me.
Now, no kidding, tell me more about it, tell me which version of cx_Freeze and python, how to reproduce, these things.... if the python is from mingw, official, conda...

**Comment by Fox214** [comment]
With python 3.8.5 and cx_Freeze 6.11, 6.12 or 6.13 (6.10 is working) I am getting the following:

Maybe something related to setuptools? I was getting another error about multiple top level modules, which is why I tried to upgrade from the notes saying there was a fix related to that. 
```
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/cx_Freeze/__init__.py", line 68, in setup
    setuptools.setup(**attrs)
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/cx_Freeze/command/build.py", line 176, in run
    self.run_command(cmd_name)
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/cx_Freeze/command/build_exe.py", line 259, in run
    freezer.Freeze()
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 623, in Freeze
    finder: ModuleFinder = self._get_module_finder()
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 331, in _get_module_finder
    finder = ModuleFinder(
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/cx_Freeze/finder.py", line 82, in __init__
    self._add_base_modules()
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/cx_Freeze/finder.py", line 101, in _add_base_modules
    self.include_module("zlib")
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/cx_Freeze/finder.py", line 782, in include_module
    module = self._import_module(name, deferred_imports)
  File ".../CPython/3.8.5/linux64/lib/python3.8/site-packages/cx_Freeze/finder.py", line 325, in _import_module
    raise ImportError(f"No module named {name!r}")
ImportError: No module named 'zlib'
```

**Comment by marcelotduarte** [comment]
When you quoted zlib.dll I thought it was windows.
Well, I still need more information. Are you using miniconda on Linux?
What is the version of setuptools?

**Comment by Fox214** [comment]
I assume, zlib.dll is windows, I am not the original poster.

I am using linux, compiled from source, no special builds. 

setuptools:
Version: 60.10.0

**Comment by marcelotduarte** [comment]
@Fox214 How to reproduce?
What is the command to install cx_Freeze from sources that you have used?
Can you reproduce with the simple sample or another at [samples](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples)?

**Comment by Fox214** [comment]
Ok I've discovered the problem is if I set the 'path' option in build_exe_options. I took your sqlite sample and added it to reproduce the error (if I remove path from my complex code it does run then, similarly if I add it to the simple example below it fails):
```
from cx_Freeze import Executable, setup
import sys
import os

targetArch='linux64'
archDir = 'lib-{}'.format(targetArch)
cwd = os.getcwd()
searchPath = ['{}/{}'.format(cwd,archDir)] + sys.path


setup(
    name="test_sqlite3",
    version="0.3",
    description="cx_Freeze script to test sqlite3",
    executables=[Executable("test_sqlite3.py")],
    options={
        "build_exe": {
            "excludes": ["tkinter"],
            'path' : searchPath,
            "replace_paths": [("*", "")],
            "zip_include_packages": ["*"],
            "zip_exclude_packages": [],
        }
    },
)
```

**Comment by Fox214** [comment]
Is there plans to fix this issue? It seems to still exist.

**Comment by marcelotduarte** [comment]
Please test:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by Fox214** [comment]
I'm getting this: error: option --build-exe not recognized

**Comment by marcelotduarte** [comment]
What is the command that you are trying to do?

If using:
python setup.py build --build-exe dist
Change to:
python setup.py build_exe --build-exe dist

**Comment by Fox214** [comment]
That compiles but I get a seg fault when I try to run the program.

**Comment by marcelotduarte** [comment]
Are you testing with the sample sqlite or with your project?

**Comment by Fox214** [comment]
with my project (which is much more complicated), but the sqlite scripted core dumped as well:

$ lib-linux64/test_sqlite3 
Segmentation fault (core dumped)

**Comment by marcelotduarte** [comment]
In the additional path, I have nothing, just a directory to test. Before the path it fails. Now it works!
But, I continue to execute it in the build/exe.*/test_sqlite3
What you have in the directory?
What is your system os, etc?
Give me more information. Without information...

**Comment by Fox214** [comment]
this is linux64 (x86). its the same test_sqlite.py as in your samples and my setup.py is in the thread above. 

find . yields;
```./setup.py
./test_sqlite3.py
./core.5440
./lib-linux64
./lib-linux64/test_sqlite3
./lib-linux64/frozen_application_license.txt
./lib-linux64/lib
./lib-linux64/lib/library.zip
./lib-linux64/lib/_asyncio.cpython-38-x86_64-linux-gnu.so
... <lots of *.so files>
./lib-linux64/lib/zlib.cpython-38-x86_64-linux-gnu.so
./core.5840
./run.cx
```
Just running it from the build dir, with the relative path.

**Comment by marcelotduarte** [comment]
Do you include in the path option the `lib-linux64` and compiles the executable to the same directory?
This is incorrect. 
[path](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-path) should be "comma-separated list of paths to search [for modules]; the default value is sys.path".

**Comment by Fox214** [comment]
its in the setup.py: searchPath = ['{}/{}'.format(cwd,archDir)] + sys.path

so I should remove the path? or specify it differently? (the above has been working for years)

**Comment by marcelotduarte** [comment]
If you do not change the path (or in this case, remove it) your application should work normally.
You app work for years because in the this value is ignored in prior versions. cx_Freeze before 6.11 (I suppose) always uses sys.path instead of path, but when I changed to distribute binary wheels, I need to fix this.
And you ended up showing me another bug.

**Comment by Fox214** [comment]
I deleted path and the code still seg faults (x86 linux, test_sqlite) or do I need a newer version of cx_freeze? This is from the beta version I got last week.

**Comment by marcelotduarte** [comment]
Please, uninstall cx_Freeze beta and install 6.14.4

**Comment by Fox214** [comment]
that worked for me, thanks!
