### ISSUE TITLE
Python 3.9 + PySide6 error on start with zip option enabled

### ISSUE THREAD

**Issue by brzGatsu** [marcelotduarte/cx_Freeze#1673]
Using Python 3.9.7 with zip_include_packages on windows results in "libshiboken does not exist" error on start.

Repro:
- cx_Freeze Simple browser example
- Add the following to setup.py:
"zip_include_packages" : "*"
"zip_exclude_packages" : ""
- Build and observe error on starting the exe

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 10
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: cx_Freeze 6.13
 - Python version [e.g. 3.10]: 3.9.7

**Comment by marcelotduarte** [comment]
Please check if it is related to others issues with shiboken2, especially #1144 
It must work if you use zip_exclude_packages=["shiboken6"]

**Comment by brzGatsu** [comment]
I don't have shiboken2/PySide2 installed. It does indeed work when excluding shiboken6 like you suggested. Wondering though - I did not have to exclude shiboken with Python 3.7.8 - the python upgrade was the only thing I changed.

**Comment by marcelotduarte** [comment]
Can you test if this bug is a side effect of #1674? Can you test with cx_Freeze 6.13.1?

**Comment by brzGatsu** [comment]
Just tried with Simple Browser example and 6.13.1. It seems to not be related, still complains about shiboken6 missing unless its put in the zip excludes. To be fair It's only a small issue for me, the impact on build size is small.

**Comment by marcelotduarte** [comment]
I believe that previously I had not understood that you wanted shiboken6 and pyside6 in the zip option.
I made a patch to support this.

You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
