### ISSUE TITLE
Windows environment path user entries are gone

### ISSUE THREAD

**Issue by brzGatsu** [marcelotduarte/cx_Freeze#1674]
After upgrading from cx_Freeze 6.12 to 6.13 the system environment variable "PATH" on windows is overriden by cx_Freeze and only contains:

[App]\lib\PySide6;
[App]\lib\library.zip;
[App]\lib;
C:\WINDOWS;
C:\WINDOWS\System32

All user entries are gone. This only happens with the frozen executable.

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 10
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: 6.13
 - Python version [e.g. 3.10]: tested with Python 3.7.8 and Python 3.9.7
 - PySide version 6.4

**Comment by marcelotduarte** [comment]
@TTimo commented https://github.com/marcelotduarte/cx_Freeze/pull/1659#issuecomment-1295109361

**Comment by brzGatsu** [comment]
Heh, seems I was faster than TTimo  :D I absolutely agree with him that disabling this security aspect should be an option! Our use case: users need to install pftk on their machines - we cannot redistribute it for licensing reasons. We expect it to be in the environment path (the pdftk installer takes care of it) but this is broken now.

**Comment by marcelotduarte** [comment]
I think I will have to revert if I don't find a good solution, improving security and not breaking what already exists. For a case of looking for a file, like yours, I imagine you can include the path of this program to os.environ in the starting script.

**Comment by marcelotduarte** [comment]
Can you test with the he latest development build?
`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

More info: https://github.com/marcelotduarte/cx_Freeze#installation

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.13.1](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.13.1) has just been released.

**Comment by brzGatsu** [comment]
I can confirm that it is fixed for both Python 3.7.8 and Python 3.9.7. Thank you!
