### ISSUE TITLE
error: [Errno 13] Permission denied: 'build/exe.macosx-10.9-x86_64-2.7/tcl/word.tcl'

### ISSUE THREAD

**Issue by 18237634625** [marcelotduarte/cx_Freeze#1678]
macOS: 12.3.1

Xcode: 13.4

python: 2.7.18

cx_Freeze: 5.0

 On a mac computer, I use cx_freeze5.0 for a simple packaging test。

error：
`
error: [Errno 13] Permission denied: 'build/exe.macosx-10.9-x86_64-2.7/tcl/word.tcl'
`
I have to use python2.7 to package my script, cx_freeze only supports python2.7 in version 5.0. So I can't upgrade cx_freeze to solve this problem

**Comment by marcelotduarte** [comment]
Python 2.7 is EOL.
If you do not depend on tkinter, you can use --excludes=tkinter (maybe TkInter, I do not remember the correct naome of package in 2.7 version).
