### ISSUE TITLE
[PyQt6]DLL load failed

### ISSUE THREAD

**Issue by JakobDev** [marcelotduarte/cx_Freeze#1685]
I build my [my project](https://gitlab.com/JakobDev/jdMinecraftLauncher) using cx-Freeze. It was build using a CI. You can find the CI configuration [here](https://gitlab.com/JakobDev/jdMinecraftLauncher/-/blob/master/.gitlab-ci.yml) and the full log [here](https://gitlab.com/JakobDev/jdMinecraftLauncher/-/jobs/3333408939). It is just a few PowerShell commands, so this should be easy reproduce able. The final build was later [uploaded to SourceForge](https://sourceforge.net/projects/jdminecraftlauncher/files/4.1/jdMinecraftLauncher-4.1-WindowsPortable.zip/download). 

It works on my System without any problems. But when I wanted to publish it on Winget, [I got told that it throws a error](https://github.com/microsoft/winget-pkgs/pull/88878#issuecomment-1319134047). The error says `ImportError: DLL load failed while importing QtWidgets`. To be clear: The installer just unpacks the files you find in the ZIP I linked above in a directory and does nothing more. So it works on my System but not on someone's else.

I already found #1595, which seems to have the same problem, but it was fixed in a newer version that I'm already using.

**Comment by marcelotduarte** [comment]
Please check the [FAQ](https://cx-freeze.readthedocs.io/en/latest/faq.html#microsoft-visual-c-redistributable-package).

**Comment by JakobDev** [comment]
> Please check the [FAQ](https://cx-freeze.readthedocs.io/en/latest/faq.html#microsoft-visual-c-redistributable-package).

Building with `include_msvcr` was (of course) tested in a private build before creating a bug report. The private build contains the api-ms.win DLL files, but it didn't resolve the problem.

**Comment by JakobDev** [comment]
@marcelotduarte Any news on this? This is currently blocking a Windows release for multiple Programs.

**Comment by JakobDev** [comment]
@marcelotduarte I have now tried it with the [official exmaple](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyqt6). You can find the repo [here](https://gitlab.com/JakobDev/cx-freeze-test). The build is [here](https://gitlab.com/JakobDev/cx-freeze-test/-/jobs/3433026903). But I still get the same result.

**Comment by marcelotduarte** [comment]
Using the pyqt6 sample works for me. Using your build works for me too. I download the artifact that you build and it runs.
![remmina_giga_giga_20221206-234935](https://user-images.githubusercontent.com/12752334/206050836-96f6f0b9-ed9f-4c44-bccf-40c7baf42ab0.png)

**Comment by JakobDev** [comment]
Have you installed Python on your Computer? As described above, it works on a Dev machine but not on another.

**Comment by marcelotduarte** [comment]
My machine is Linux. I do tests with some samples using CI (Github Action). In the case of Windows tests, sometimes I do tests on machines I have access to. In this case, I did tests on 2 machines, with python and without python. But even on the machine that has python, python is not in the PATH. And I used it to test the executable you generated.

**Comment by JakobDev** [comment]
I have no setup a new fresh VM and the problem is gone fo what ever reason and my Program does start. But now I'm facing the next problem: QtWebEnfine does not work correctly. You can get the latest build of my App [here](https://gitlab.com/JakobDev/launcherbuild/-/jobs/3440321693). and the confi is [here](https://gitlab.com/JakobDev/launcherbuild/-/blob/master/build_exe.py).

When I start it, I get this screen:
![CxFreeze](https://user-images.githubusercontent.com/15185051/206310887-32a2991f-391e-4c32-a4d2-cb6071b0b867.png)

When I run it directly with Python
```
pip install -r requirements.txt
python ./jdMinecraftLauncher.py
```
I get this Screen, which is correct:
![Python](https://user-images.githubusercontent.com/15185051/206311243-0a12cb5e-e6cf-42c5-b8e4-c10632b5902f.png)

The Window has also the correct Icon and the Splash screen is working.

Can you reproduce this, or is this just another weird VM Bug? I'm also using Linux, so I don't have a real Machine with Windows.

**Comment by marcelotduarte** [comment]
> VM Bug?

I thought you were using a real machine. I access the machines I mentioned via remote access generally, and a while ago I had problems with an older machine with an AMD A4 processor, and the problem was the video driver. Via VNC I was able to test the pyqt5/pyside2 sample, via RA it gave an error in opengl. So I think your problem may be related to the VM's video driver.

> QtWebEnfine does not work correctly

In my tests I had problems in pyqt5/pyside2, in pyside6/pyqt6 I had no problems. But the output is usually:

`test_simplebrowser --single-process`

Check the [PyQt6 documentation](https://doc-snapshots.qt.io/qt6-dev/qtwebengine-debugging.html#using-command-line-arguments) on how to enable this option automatically, if applicable.

**Comment by JakobDev** [comment]
> I thought you were using a real machine.

Sorry for confusing you. I use VirtualBox for Windows related tests.

I have now tested it on a friends PC, but still get the same result. The Icon (SVG) is also not displayed. Running it with --single-process does not help (sys.argv is passed to QApplication).

**Comment by marcelotduarte** [comment]
Try the options:
--no-sandbox
--single-process
--enable-features=NetworkServiceInProcess

**Comment by marcelotduarte** [comment]
Testing w/ cx_Freeze 6.14.x pyqt6-webengine 6.3.1/6.3.2 worked w/ --single-process.
I used https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyqt6-simplebrowser
I detected some issue with SVG and pdf and fixed it.
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

I'll continue to trying to detect the others issues.
With pyside6 the similar sample https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyqt6-simplebrowser works.

**Comment by marcelotduarte** [comment]
Copying a single `qt.conf` solves the issue for me using the sample. Can you test and give feedback?

**Comment by marcelotduarte** [comment]
https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.14.7
