### ISSUE TITLE
Qt5 environment mix up

### ISSUE THREAD

**Issue by Lois31** [marcelotduarte/cx_Freeze#1686]
**Describe the bug**
I am developing a Python(3.7) / PySide2(5.12.0) application which aims to launch complex applications composed of multiple processes.
In order to launch these processes, I use _subprocess_ module and to deliver a binary of my application I use the _cx_Freeze_ module.
All this works very well, except that I ran into a problem when launching a QT 5.12.5 HMI with my frozen app:

![qt_error](https://user-images.githubusercontent.com/59613296/202652812-1addb41e-23f2-442a-a0eb-44a218dfc8eb.png)

After several hours of investigation, I suspect that the problem comes from the fact that _cx_Freeze_ adds a wrapper at the level of the application's binary which modifies the environment, which causes a loading probelm between the PySide2(5.12.0) libraries and that Qt5.12.5 application launched.

To reach this conclusion, I add that I carried out the following tests:
- Launching the Qt5.12.5 HMI through my frozen Python(3.7)/Pysyde2(5.12.0) application: [ FAIL ]
- Launching the Qt5.12.5 HMI through my Python(3.7)/Pysyde2(5.12.0) application directly in my Python virtual environment: [  OK  ]
- Freezed my application without the HMI (without PySide2) and launched the Qt5.12.5 HMI from the command line: [  OK  ]

I also point out that I checked the PATH and QT* environment variables which are correct.

**To Reproduce**
I would have liked to provide you with a simple code example that reproduces the problem but it takes too much time.

**Expected behavior**
Correct launch of the _Qt5.12.5_ HMI with my frozen Python(3.7)/Pysyde2(5.12.0) application.

**Desktop (please complete the following information):**
 - Platform information: Windows 10
 - OS architecture: amd64
 - cx_Freeze version: 6.13.1
 - Python version: 3.7

**Additional context**
In order to correctly freeze my Python/PySide2 application, and to reduce the size of the generated binary, I had to add the _PySide2_ and _shiboken2_ modules in the zipped library via the following configuration:
`zip_include_packages = ['PySide2', 'shiboken2']`

**Comment by marcelotduarte** [comment]
Can you test with some different options?
 zip_include_packages = ['PySide2']

> _cx_Freeze_ adds a wrapper at the level of the application's binary which modifies the environment

- cx_Freeze adds a debug code, activated by set QT_DEBUG=1 before run the code
- adds a resource only for conda-forge (if is your case, try to remove it in PySide2 subdirectory, _cx_freeze_resource.pyc)
- adds a qt.conf at PySide2 subdirectory (you can remove it to test too).

**Comment by Lois31** [comment]
Thank-you for your prompt response.
- test with `zip_include_packages = ['PySide2']`: [ FAIL ]
- test with `zip_include_packages = []`: [ FAIL ]
- test delete file `qt.conf`: [ FAIL ]

For information, I am not in a _conda_ environment

![image](https://user-images.githubusercontent.com/59613296/202714679-7788a2cb-adf0-4b1d-95f5-f0ab1c4ce265.png)

**Comment by marcelotduarte** [comment]
This S:\ is a network drive? Maybe related to #1144?
Try with  PySide2 5.15.2.1

**Comment by Lois31** [comment]
That's good, it was me who created support #1144.

The conclusion of this support is because of a bug concerning the management of network drives on _Qt5_ version higher than 5.12.0, I'm stuck on _PySide2 5.12.0_. This problem is fixed in _Qt6_ versions. But I have not yet planned to migrate to these versions.

Nevertheless, the various tests that I carried out show that it is not a _Qt_ problem but _cx_Freeze_ which modifies the _Qt_ behavior.

**Comment by Lois31** [comment]
Hello,
First of all, I wish you my best wishes for this new year 2023 !

I worked on the subject and I provide you a concrete example which reproduces the problem.
The tarball [simple_example.zip](https://github.com/marcelotduarte/cx_Freeze/files/10384067/simple_example.zip) contains the following:
- **blackbox**: Basic C++ GUI Qt5.12.5
- **Qt5.12.5**: Minimal library of Qt5.12.5 necessary for the functioning of the GUI (blackbox)
- **sources**
  - **cli.py**: Simple Pyhton script to launch the Qt5.12.5 GUI (blackbox) via the _subprocess_ module
  - **gui.py**: Simple GUI _Pyside2_5.12.0_ to launch the Python **cli.py** script
- **setup.py**: _cx_Freeze_ configuration script allowing to create **cli** & **gui** executables by integrating _PySide2_
- **setup_without_PySide2_5.12.0.py**: _cx_Freeze_ configuration script allowing to create **cli** executable without _PySide2_

### Environement
- Windows 10 (x64)
- [Python V3.7.9](https://www.python.org/ftp/python/3.7.9/python-3.7.9-amd64.exe)
- requirements.txt:
  cx-Freeze==6.13.1
  PySide2==5.12.0 

### Setting up the Python virtual environment
1. Install Python v3.7.9
2. In a _cmd.exe_, create the Python environment
```
>cd simple_example
>C:\Python\V3.7.9\python.exe -m venv simple_example\python_env\windows
>python_env\windows\Scripts\activate.bat
(windows)>python -m pip install -r requitements.txt
```

### Tests
#### Test without cx_Freeze
```
// Enabling the python environment
>python_env\windows\Scripts\activate.bat
// Launch of the Qt5 GUI
(windows)>python sources\cli.py
```
**Conclusion: Qt5.12.5 GUI launches correctly - [  OK  ]**


#### Test with cx_Freeze without PySide2
```
// Enabling the python environment
>python_env\windows\Scripts\activate.bat
// Freeze the cli script
(windows)>python setup_without_PySide2_5.12.0.py build --build-exe simple_example\binaries\windows_x64
// Disable Python environment
(windows)>deactivate
// Launch of the Qt5 GUI
>binaries\windows_x64\cli
```
**Conclusion: Qt5.12.5 GUI launches correctly - [  OK  ]**

#### Test with cx_Freeze with PySide2
```
// Enabling the python environment
>python_env\windows\Scripts\activate.bat
// Freeze the cli script
(windows)>python setup.py build --build-exe simple_example\binaries\windows_x64
// Disable Python environment
(windows)>deactivate
// Launch of the Qt5 GUI
>binaries\windows_x64\cli
```
**Conclusion: Qt5.12.5 GUI not launching - [ FAIL ]**

## Annex 1: Qt5.12.5 GUI (blackbox)
![GUI](https://user-images.githubusercontent.com/59613296/211597734-6d98bf42-ba58-4613-938a-c67ff0ed606d.png)

**Comment by Lois31** [comment]
Hello Team,
Do you have any feedback on this topic ?
You have a simple and concrete example that reproduces the problem.
Regards

**Comment by Lois31** [comment]
Hello @marcelotduarte ,
Do you have any feedback on this topic ?
Regards

**Comment by Lois31** [comment]
Hello @marcelotduarte ,
Did you have time to look at this point, blocking in our case ?
Best regards,

**Comment by marcelotduarte** [comment]
@Lois31, I work on Linux, having limited access to Windows machines. Most of the tests for this project I do using CI from github.
I think it would take too long to look for a solution to something that has already been fixed upstream, recognized as a PySide2 issue in issue #1144
Another thing is the use of Python 3.7, which I have thought about stopping supporting it several times and I will stop supporting it in June as soon as it reaches EOL.
The work for you to upgrade the python and the pyside2 versions should be less than trying to understand the inner workings of pyside2. Of course, I don't know how big your system is.
Another thing, this is a project that accepts contributions, mainly code. If you want to try, be sure I'll help you find a solution.

**Comment by marcelotduarte** [comment]
@Lois31 I make some tests with your blackbox.
Using a network drive:
1) python sources\cli.py ok - show info
2) ok
3) ok - image:
![remmina_giga_giga local_20230307-022259](https://user-images.githubusercontent.com/12752334/223303139-dd4a2f19-89af-40b6-9417-4536ee1234bd.png)
4) same as 3, but outside of venv
![remmina_giga_giga local_20230307-022502](https://user-images.githubusercontent.com/12752334/223303439-3f9a4070-d6a4-489a-86f2-4c9cab1e37d5.png)

**Comment by Lois31** [comment]
Hello @marcelotduarte ,
Thank you for these different tests. 
However, I don't recognize the GUI compiled with Qt 5.12.5 that I provided to you.

What version of Qt did you use for your GUI?

**Comment by marcelotduarte** [comment]
> However, I don't recognize the GUI compiled with Qt 5.12.5 that I provided to you.

I used only what you provided.

I don't think I can help you with this matter, I tried to do more than I could. I hope you found a solution.
I'm going to close the issue since, in addition to what I said previously, I'm not even able to provide support for Python 3.7.
