### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by andrew-ares** [marcelotduarte/cx_Freeze#1689]
**Describe the bug**
Run the executable file and it complains:
```
Traceback (most recent call last):
  File "/home/nvidia/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 120, in run
    module_init.run(name + "__main__")
  File "/home/nvidia/.local/lib/python3.6/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "main.py", line 8, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
```

It's odd, the `sklearn` is installed. And reinstall it doesn't fix it.

**To Reproduce**
setup.py
```python3
import sys
import os

from cx_Freeze import Executable, setup

build_exe_options = {"packages": ["os"], "excludes": ["tkinter"],}

base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(
    name="main",
    version="0.1",
    description="test",
    options={"build_exe": build_exe_options},
    executables=[Executable("main.py", base=base,target_name="main")],
)
```

**Expected behavior**
it works

**Desktop (please complete the following information):**
 - Platform information: Linux tx2-nx 4.9.201-tegra # 630 SMP PREEMPT Fri Nov 19 13:47:15 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
 - OS architecture: aarch64
 - cx_Freeze version: 6.12.0
 - Python version 3.6.9

**Comment by marcelotduarte** [comment]
Try "packages": ["sklearn"]

**Comment by marcelotduarte** [comment]
@TENX-S Please check issues #1706 and #1616

PR https://github.com/marcelotduarte/cx_Freeze/pull/1715 and https://github.com/marcelotduarte/cx_Freeze/pull/1716 fix this.

To test, install the latest development build:

`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
