### ISSUE TITLE
install_dir option not read anymore in install_exe options

### ISSUE THREAD

**Issue by FabeG** [marcelotduarte/cx_Freeze#1695]
**Describe the bug**
Starting from version 6.11.0, the ``install_dir`` option for ``install_exe`` seems unread (at least for Windows version). Only the default value ``C:\\program files\<name>`` is used as ``install_dir``.

For version 6.10.0, everything is working as expected.

**To Reproduce**

Using the following ``setup.py`` file will reproduce the error:

```python
from cx_Freeze import setup, Executable

setup(
    name="test",
    version="0.1",
    description="test",
    options={
        "install_exe": {"install_dir": "D:/users"},
    },
    executables=[
        Executable(
            "test.py",
            targetName="test.exe",
            base=None,
        )
    ],
)
```
Starting from cx_freeze 6.11.0, running ``python setup.py install`` will raise the following error:

![cx_freeze](https://user-images.githubusercontent.com/21279450/204500793-7bb80437-8ca2-451a-91d6-d1ac3ee988a1.png)

**Expected behavior**
Like in ``cx_freeze`` version 6.10.0, it is expected that the ``exe`` is created in the specified ``install_dir`` folder, that is ``D:\users`` folder.

**Desktop (please complete the following information):**
 - Platform information : Windows 10
 - OS architecture : amd64
 - cx_Freeze version : 6.11.0 / 6.12.0 / 6.13.1
 - Python version : 3.8

**Comment by marcelotduarte** [comment]
To test the development version:

`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --upgrade`

**Comment by FabeG** [comment]
I tested the development version using the wheel (cx_Freeze-6.14.0.dev1-cp38-cp38-win_amd64.whl) in https://marcelotduarte.github.io/packages/cx-freeze (and upgrading also cx-Logging to 3.1.0 and setuptools to 65.6.3).

Unfortunately, the error described in my first message is still showing up.

**Comment by marcelotduarte** [comment]
I tested with `install_exe` and it passed, but with `install`, it failed. I'll investigate.

**Comment by marcelotduarte** [comment]
Please test a fix in the dev version:

`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by FabeG** [comment]
With the updated development version (cx_Freeze-6.14.0.dev2-cp38-cp38-win_amd64.whl), ``python setup.py install`` is working again ! Thanks a lot !
