### ISSUE TITLE
How do we sign the executables that cx_Freeze produces?

### ISSUE THREAD

**Issue by jschwar313** [marcelotduarte/cx_Freeze#1727]
How do we sign the executables that cx_Freeze produces so that my name shows up as the author in the executable?

**Comment by marcelotduarte** [comment]
Check documentation [about setup script](https://cx-freeze.readthedocs.io/en/latest/setup_script.html) and a recently included page [Keywords](https://cx-freeze.readthedocs.io/en/latest/keywords.html).

**Comment by jschwar313** [comment]
One of your links in the keywords page doesn't exist.  This is the link.  Could you please update it?  https://setuptools.pypa.io/en/latest//userguide/declarative_config  This one also doesn't work:  https://setuptools.pypa.io/en/latest//userguide/pyproject_config

**Comment by jschwar313** [comment]
I want to have my name show up as the publisher in control panel for my application.  It says unknown right now.  How do I do this?  Here's a screen print of what it shows now.  Sorry if I wasn't clear. 
 
![publisher needs update](https://user-images.githubusercontent.com/71224599/210136176-ebc71002-817c-4a85-9c04-727335878083.jpg)

**Comment by marcelotduarte** [comment]
The cited documentation has an author and others keywords. Use it like this:
```
setup(
    name="Hello Program",
    version="0.1",
    author="cx_Freeze",
    description="Sample cx_Freeze script to test MSI extension registration",
    executables=executables,
    options={
        "build_exe": {"excludes": ["tkinter"]},
        "bdist_msi": bdist_msi_options,
    },
)
```
There is a bug #1695 that may affect this behavior too, so use the development version to test:
`pip install --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze --upgrade`

**Comment by marcelotduarte** [comment]
Can I close this issue?

**Comment by jschwar313** [comment]
Yes.
