### ISSUE TITLE
Python3.dll must be bundled along with python34.dll

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#173]
Originally reported by: **Marcio Marchini (Bitbucket: [sglebs](https://bitbucket.org/sglebs), GitHub: [sglebs](https://github.com/sglebs))**

----------------------------------------

I am packaging my application and python34.dll is bundled in but not python3.dll. Unfortunately some modules link against the public API in python3.dll, so they fail to load. The workaround is to copy python3.dll separately. The real fix should probably go in freezer.py, _GetDefaultBinIncludes. 

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/173

**Comment by cvicentiu** [comment]
This still seems to be a problem with python 3.7.
I can't quite figure out *why* this works on my development Windows machine, but when I move the application to a clean windows 10 (32bit) install, it can not find python3.dll. I assume it ends up loading the dll from the base installed location on the dev machine (something like C:\Python3-32Bit in my case). It can not find it on the clean install as there's no python installed there at all.

What I did:
* Installed python 3.7.4 using the windows installer (32 bit)
* created virtualenv from python 3.7.4
* Activated the virtualenv.
* installed cx_freeze 6.0 from the current master branch: 7f0ceefa89ab48896bb28c8f57c0e550b338d9d8 -> python setup.py build python setup.py install
* Installed PySide2 5.13
* Simple application that starts a PySide2 window.

Fails to import shiboken2 module with DLL module not found.

Adding python3.dll to the same folder as the .exe makes the app work. Leaving this here in case it helps someone else and hope that @anthony-tuininga gets a chance to look at this.

Adding the following code to build_exe_options bundles python3.dll and makes the setup.py work correctly, but it feels like a hack.

```
PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))

build_exe_options = {
    ....
    "include_files": [
        os.path.join(PYTHON_INSTALL_DIR, 'Scripts', 'python3.dll'),
    ],
    ....
}
```

If I can provide any more help, let me know. Thanks for all the hard work, cx_Freeze has definitely helped me a lot!
