### ISSUE TITLE
Version's 4th element is not set correctly in resulting windows exe

### ISSUE THREAD

**Issue by Berserker66** [marcelotduarte/cx_Freeze#1744]
**Describe the bug**
`version=f"{buildtime.year}.{buildtime.month}.{buildtime.day}.{buildtime.hour}"`
results in a 0 as the last element of "File Version", but "Product Version" is set correctly
![image](https://user-images.githubusercontent.com/3189725/211639284-d49e07a7-fa75-4d32-9579-221bc1e5d882.png)

**To Reproduce**
```
import datetime

import cx_Freeze

buildtime = datetime.datetime.now(datetime.timezone.utc)
cx_Freeze.setup(
    name="Test",
    version=f"{buildtime.year}.{buildtime.month}.{buildtime.day}.{buildtime.hour}",
)
```

**Expected behavior**
The 0 to be an 18, like in Product Version

**Screenshots**
![image](https://user-images.githubusercontent.com/3189725/211639284-d49e07a7-fa75-4d32-9579-221bc1e5d882.png)

**Desktop (please complete the following information):**
Windows 10, Python3.10, amd64, with cx_Freeze 6.13.1

**Additional context**
This version field is then read by inno setup, which cannot read from Product Version. This also used to work, but I did not keep track of which version broke it.

**Comment by marcelotduarte** [comment]
<s>I cannot reproduce this error.</s> I updated the [simple](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/simple) sample version to use as test.

**Comment by marcelotduarte** [comment]
To install the latest development build:

`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
