### ISSUE TITLE
ImportError: The 'packaging' package is required

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#175]
Originally reported by: **Florian Bruhin (Bitbucket: [The-Compiler](https://bitbucket.org/The-Compiler), GitHub: [The-Compiler](https://github.com/The-Compiler))**

----------------------------------------

Since updating to setuptools 19.3, I get this when starting my application:

```
  File "C:\projects\qutebrowser\.tox\unittests-frozen\lib\site-packages\pkg_resources\extern\__init__.py", line 60, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

It goes away when adding `pkg_resources._vendor.packaging` to `packages` (for the `build_exe` options)

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/175

**Comment by anthony-tuininga** [comment]
*Original comment by* **okin (Bitbucket: [okin](https://bitbucket.org/okin), GitHub: [okin](https://github.com/okin))**:

----------------------------------------

I hit the same bug on an Ubuntu 16.04. Luckily the fix posted by @The-Compiler worked not only for `packages` but also for `six`.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Nate Roberts (Bitbucket: [nroberts5](https://bitbucket.org/nroberts5), GitHub: Unknown)**:

----------------------------------------

Hi @okin. I am getting the same problem after locally installing python, some modules (including setuptools-24.0.3, six, packaging, and PyInstaller), and then using that local python to run pyinstaller on a .py file. When I try to run the executable, I get the same error. Can you give a little more detail about how to use @The-Compiler 's fix?  I don't understand how to implement "It goes away when adding pkg_resources._vendor.packaging to packages (for the build_exe options)" 

```
#!shell


$ ./PyInstallerTest/.localpython/bin/pyinstaller dcmINFO.py -F

$ ./dist/dcmINFO 
Traceback (most recent call last):

  File "PyInstallerTest/.localpython/lib/python3.4/site-packages/PyInstaller-3.2-py3.4.egg/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>

  File "/usr/g/research/nroberts/PyInstallerTest/.localpython/lib/python3.4/site-packages/PyInstaller-3.2-py3.4.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)

  File "pkg_resources/__init__.py", line 68, in <module>

  File "pkg_resources/extern/__init__.py", line 60, in load_module

ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
Failed to execute script pyi_rth_pkgres
```

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
