### ISSUE TITLE
setup.py has  "replace_paths": [("*", "")] but it's rejected.

### ISSUE THREAD

**Issue by jschwar313** [marcelotduarte/cx_Freeze#1765]
**Prerequisite**
 - Make sure no duplicated issue has already been reported. You should look for closed issues, too.
 - Make sure you are not asking us to help to solve your specific issue. GitHub issues are opened mainly for development purposes. If you want to ask someone to help to solve your problem, go to some community site like StackOverflow, etc.
 - Make sure your problem is not derived from packaging (e.g. Homebrew).

Stackoverflow says this is ok for replace_paths:  https://stackoverflow.com/questions/39108524/how-to-pass-commands-to-gcc-through-cx-freeze

**Describe the bug**
My setup.py script has the following line:

```
build_exe_options = {
    "include_msvcr": True,
    "include_files": ["dist\\h drive backup script.cmd",
                      "dist\\iTunes backup.cmd",
                      "dist\\system backup script.cmd",
                      "dist\\aws bucket cleanup script c drive.cmd",
                      "dist\\aws bucket cleanup script h drive.cmd",
                      "dist\\delete old backups c drive.cmd",
                      "dist\\delete old backups h drive.cmd",
                      "dist\\delete old log files.cmd",
                      "NOTICE.txt",
                      "LICENSE.txt", ],
    "replace_paths": [("*", "")],
    "includes": ["html.parser", "boto3.s3.inject", "shutil", "boto3", "botocore"]
```

I get the following error:

(prod) H:\Users\LindaJim\Documents\SourceCode\Software\aws_pc_backup>python setup_aws_pc_backup2.py bdist_msi
H:\Users\LindaJim\Documents\SourceCode\Software\aws_pc_backup\prod\Lib\site-packages\cx_Freeze\common.py:172: UserWarning: camelCase values is obsolete and will be removed in the next major version -> use the new name 'target_name'
  warnings.warn(
running bdist_msi
running build
running build_exe
error: 'replace_paths' must be a list of strings (got [('*', '')])

**To Reproduce**
Steps to reproduce the behavior (a setup.py or a minimal code sample will be good)

I'm using python 3.11.1.  I'll attach my requirements.txt, too.  

I'm issuing the following command:

python setup_aws_pc_backup2.py bdist_msi

**Expected behavior**
There should be no error.  I recently upgraded to cx_Freeze 6.14.0.  I have had replace_paths like this for quite some time.

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 10
 - OS architecture (e.g. amd64): intel
 - cx_Freeze version [e.g. 6.11]: 6.14.0
 - Python version [e.g. 3.10]: 3.11.1

**Additional context**
Nothing that I know of.

[setup_aws_pc_backup2.py.txt](https://github.com/marcelotduarte/cx_Freeze/files/10494018/setup_aws_pc_backup2.py.txt)
[requirements.txt](https://github.com/marcelotduarte/cx_Freeze/files/10494026/requirements.txt)

**Comment by Berserker66** [comment]
Hey, I was in the process of making the same Issue, but yours is way more detailed, so thank you.
I will add this snipped from my discarded issue:
trying my hardest to interpret the documentation I came up with `"replace_paths": ["*."],` which is accepted and does work as replacement, but that really could have used a shoutout in the changelog if a format like that is now desired.

**Comment by marcelotduarte** [comment]
regression at #1761

**Comment by marcelotduarte** [comment]
In the previous version, this format is accepted, and I can restore it.
But the documented format is `<search>=<replace>`
See https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-replace_paths
So, this works:
`"replace_paths": ["*="],`

**Comment by jschwar313** [comment]
It would help if you tell us in that documentation that "replace_paths": ["*="] would work.  Maybe I wouldn't have opened an issue then.  It's not easy to see that the way it's written.  I couldn't figure it out from what you said, so I started to look elsewhere.

**Comment by marcelotduarte** [comment]
But the documentation already exists for a long time ago. I use this in some projects before I become a maintainer.

**Comment by jschwar313** [comment]
Here's another place on the internet that says the way I tried is the way to get it to work:

https://willpittman.net:8080/index.php?title=Python_cx_freeze

**Comment by Berserker66** [comment]
I'm pretty sure when I tried ["*="] I got paths that looked like "=/rest_of_path"

**Comment by jschwar313** [comment]
> But the documentation already exists for a long time ago. I use this in some projects before I become a maintainer.

Please don't assume that people were using replace_paths the way you mentioned instead of using what was said in other more easily understood posts, especially since that other way just stopped working.

**Comment by marcelotduarte** [comment]
6.14.1 fixes the regression with lists (include_files inclusive)
6.14.2 fixes the version in windows
