### ISSUE TITLE
include_resources option no longer working in 6.14.0

### ISSUE THREAD

**Issue by mathiascode** [marcelotduarte/cx_Freeze#1767]
**Describe the bug**
It's no longer possible to use the bdist_mac `include_resources` option in cx_Freeze 6.14.0. It incorrectly requires a list of strings, but actually uses a list of tuples: https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-include_resources

`error: 'include_resources' must be a list of strings (got [('/usr/local/etc/fonts/fonts.conf', 'share/fonts/fonts.conf'), ('/usr/local/etc/fonts/conf.d/65-nonlatin.conf', 'share/fonts/conf.d/65-nonlatin.conf')...`

**To Reproduce**
Attempt to use a list of tuples with this option.

**Expected behavior**
A list of tuples is accepted.

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): macOS 10.15
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: 6.14
 - Python version [e.g. 3.10]: 3.10.8

**Comment by calendulish** [comment]
same for include_files

**Comment by marcelotduarte** [comment]
6.14.2

**Comment by mathiascode** [comment]
Thank you!
