### ISSUE TITLE
cx_freeze not working with playwright sync

### ISSUE THREAD

**Issue by Dadangdut33** [marcelotduarte/cx_Freeze#1771]
**Describe the bug**
For unknown reason I can't use playwright for python code that is compiled using cx_freeze. I have tested using other builder (pyinstaller) and it works fine, but I love the way cx_freeze bundle the app and would like to use cx_freeze if possible. 

**To Reproduce**
I have installed both cx_freeze and playwright correctly. I have also [setup](https://playwright.dev/python/docs/library#pyinstaller) playwright for bundling. The code below works just fine when not compiled using cx_freeze, but it doesn't work when trying to launch from .exe compiled by cx_freeze

example code to use:
```py
# main.py
from playwright.sync_api import sync_playwright

print("Hello World")
with sync_playwright() as p:
    print("Playwright launched")

    browser = p.chromium.launch()
    print("Browser launched")

    page = browser.new_page()
    print("Page created")

    page.goto("http://whatsmyuseragent.org/", timeout=45 * 1000)
    print("Page loaded")

    page.screenshot(path="example.png")
    print("Screenshot taken")

    browser.close()
    print("Browser closed")

print("Done")
```

Compile the app using the command
```bash
cxfreeze .\main.py
```

**Expected behavior**
The code should run just fine but it got stuck after `hello world` on .exe compiled by cx_freeze

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 11 22H2
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: 6.14.1
 - Python version [e.g. 3.10]: 3.10.8

**Comment by marcelotduarte** [comment]
For me it worked in Linux.
```bash
pip install playwright
PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium
cxfreeze main.py
build/exe.linux-x86_64-3.10/main
```
Windows:
```cmd
pip install playwright
set PLAYWRIGHT_BROWSERS_PATH=0
playwright install chromium
cxfreeze main.py
build\exe.win-amd64-3.11\main.exe
```

![remmina_CTC017-Rosinha-RDP_192 168 6 47_20230708-040551](https://github.com/marcelotduarte/cx_Freeze/assets/12752334/1337c5e7-4182-4924-80b4-2a8b9fd1789f)

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
