### ISSUE TITLE
Proper way to initialize FS encoding with cxfreeze

### ISSUE THREAD

**Issue by kilinitt** [marcelotduarte/cx_Freeze#1779]
Hi @marcelotduarte what is the proper way to initialize the file system encoding? Specifically, I need utf-8 encoding always, but relying on LC_ALL is a little flaky since it depends on which glibc language packs are installed, etc. Is there a better way to do this besides specifying LC_ALL?

**Comment by marcelotduarte** [comment]
cx_Freeze is a python package and initialize in the same way of python. So, the rules at [Python UTF-8 Mode](https://docs.python.org/3/library/os.html#python-utf-8-mode) are valid.
In the bootstrap, we use [Py_DecodeLocale](https://docs.python.org/3/c-api/sys.html?highlight=py_decodelocale#c.Py_DecodeLocale) to decode the arguments like the python code do.
Py_DecodeLocale has a note:
Changed in version 3.7: The function now uses the UTF-8 encoding in the [Python UTF-8 Mode](https://docs.python.org/3/library/os.html#utf8-mode).

**Comment by kilinitt** [comment]
Thank you @marcelotduarte. Will try the other options to force it with PYTHONUTF8 set to 1.

**Comment by marcelotduarte** [comment]
I thought it was just a question. Are you having some kind of problem? Please describe it and let me know the OS and other relevant information.
