### ISSUE TITLE
cx_freeze not working in windows with application having long path (>260 chars)

### ISSUE THREAD

**Issue by rishky1001** [marcelotduarte/cx_Freeze#1786]
**Describe the bug**
I am running into an issue with a script I've built into an executable using cx_freeze. The script works fine when run as a Python script, but when run as a cx_freeze application, it fails when it encounters a file whose path is longer than 260 characters. Error it throws is ModuleNotFoundException.

I understand this is limiation of windows of not supporting long paths longer than 260 characters.
Do we have anything similiar to pyInstaller in cx_freeze to support longPaths?
https://github.com/pyinstaller/pyinstaller/pull/5424

**To Reproduce**
Steps to reproduce the behavior (a setup.py or a minimal code sample will be good)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows
 - OS architecture (e.g. amd64): x64
 - cx_Freeze version [e.g. 6.11]: 6.14.3
 - Python version [e.g. 3.10]: 3.10.9

**Additional context**

**Comment by marcelotduarte** [comment]
Our manifest has [longPathAware](https://github.com/marcelotduarte/cx_Freeze/blob/main/source/bases/manifest.txt#L21) enabled.
Are you using [manifest](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-manifest) option?

**Comment by rishky1001** [comment]
@marcelotduarte ,

Is there any documentation for how to create the cx_freeze manifest?
Can we auto generate it also for the project?

**Comment by marcelotduarte** [comment]
The default manifest used is https://github.com/marcelotduarte/cx_Freeze/blob/main/source/bases/manifest.txt
that is the same of used by python itself.
You can use a different manifest using the manifest option (https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-manifest).
The documentation is on Microsoft. The is a start: https://learn.microsoft.com/en-us/windows/win32/sbscs/manifests

**Comment by marcelotduarte** [comment]
Returning to the initial question, if you have an issue that is not in the manifest, we have to discover the origin. Do you have a way to play it with a simple app?

**Comment by marcelotduarte** [comment]
I think the aswer is here: https://stackoverflow.com/a/71603209/13913627

**Comment by marcelotduarte** [comment]
@rishky-msft The answer at SO solves this issue?

**Comment by rishky1001** [comment]
Yeah seems like user has to change the windows registry setting to enable long path. I cant find any alternative to avoid changing this setting manually.

Thanks it worked
________________________________

**Comment by marcelotduarte** [comment]
https://cx-freeze.readthedocs.io/en/latest/faq.html#removing-the-max-path-limitation
