### ISSUE TITLE
matplotlib.libs folder is not copied/detected by cx_Freeze

### ISSUE THREAD

**Issue by VegarS** [marcelotduarte/cx_Freeze#1789]
**Describe the bug**
When freezing the matplotlib sample scripts in the cx_Freeze samples directory, I get an error when running matplotlib_eg.exe: "FileNotFoundError: [WinError 2]: No such file: C:\\Users\\....\\build\\exe.win-amd64-3.10\\lib\\matplotlib.libs".

matplotlib.libs is a directory in site-packages containing two DLLs and is not copied to the build directory by cx_Freeze.

![image](https://user-images.githubusercontent.com/1231463/220568541-08944319-d50d-4cef-97de-4105292ada11.png)

**To Reproduce**

- Run setup.py in cx_Freeze/samples/matplotlib: py -3.10 setup.py build_exe
- Run frozen matplotlib_eg.exe

**Desktop:**
 - Platform information: Windows 10 20H2
 - OS architecture: 64-bit
 - cx_Freeze version: 6.14.4
 - Python version: 3.10.9
 - matplotlib version: 3.7.0

Workaround seems to be to downgrade to matplotlib 3.6.3.

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by VegarS** [comment]
Runs without errors with the latest development build. Thanks for the swift response!

**Comment by marcelotduarte** [comment]
[Release 6.14.5](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.14.5)
