### ISSUE TITLE
cx-freeze bdist_msi help

### ISSUE THREAD

**Issue by Holmberg-15A** [marcelotduarte/cx_Freeze#1794]
I tried to read the documentation, but some functions are not described there, I wanted to ask how to make the installer automatically create a directory at startup and start installing the application in this directory so that the user does not have a directory selection window, that is, so that the user runs the installer and he does not ask the user which folder to install, but immediately starts the installation is it possible?

**Comment by amieruljapri** [comment]
Maybe it has something to do with `directories`? I am trying to do the same with bdist_msi option but currently stuck as this question

[Problem SO](https://stackoverflow.com/questions/71024868/cx-freeze-bdist-msi-directories-syntax-how-to-interpret-directory-table )

Maybe someone can add an explanation to add custom path via `directories `

**Comment by Holmberg-15A** [comment]
I searched but never found the answer it looks like cx-freeze just won't be able to do it
