### ISSUE TITLE
bdist_msi install to C:\Program Files

### ISSUE THREAD

**Issue by amieruljapri** [marcelotduarte/cx_Freeze#1797]
Hi, ive managed to wrap python as executable in msi via cx_freeze however it can't install to Program Files. The error :

`The installer has insufficient privileges to access this directory:`

**Comment by marcelotduarte** [comment]
Please check:
https://cx-freeze.readthedocs.io/en/latest/setup_script.html#bdist-msi
Test with all_users
https://learn.microsoft.com/en-us/windows/win32/msi/windows-installer-portal

**Comment by amieruljapri** [comment]
Thank you. Have a nice day
