### ISSUE TITLE
cx-freeze postinstall is not included in the PIP *.tar.gz file

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#181]
Originally reported by: **12345 67890 (Bitbucket: [12345_67890](https://bitbucket.org/12345_67890), GitHub: Unknown)**

----------------------------------------

This is a very simple issue to fix. All you need to to is update the *.tar.gz file on PIP with the cx-freeze postinstall file.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/181

**Comment by marcelotduarte** [comment]
PR #511 solve this issue.
