### ISSUE TITLE
matplotlib.libs folder is not created by msi installer

### ISSUE THREAD

**Issue by VegarS** [marcelotduarte/cx_Freeze#1813]
**Describe the bug**
Related to #1789. When building msi from the matplotlib sample scripts in the cx_Freeze samples directory I get an error when running matplotlib_eg.exe: "FileNotFoundError: [WinError 2]: No such file: C:\\....\\lib\\matplotlib.libs".

Although matplotlib.libs is now copied to the build directory, it is not recreated by the msi installer (probably because it is an empty directory).

**To Reproduce**
- Run setup.py in cx_Freeze/samples/matplotlib: py -3.10 setup.py bdist_msi
- Install created msi file
- Run installed version of matplotlib_eg.exe

**Desktop:**
 - Platform information: Windows 10 20H2
 - OS architecture: 64-bit
 - cx_Freeze version: 6.14.5
 - Python version: 3.10.9
 - matplotlib version: 3.7.0

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by marcelotduarte** [comment]
[Release 6.14.6](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.14.6)
