### ISSUE TITLE
Cannot load imports from non-existent stub (librosa)

### ISSUE THREAD

**Issue by jpcarreon** [marcelotduarte/cx_Freeze#1837]
**Describe the bug**
After trying to run a frozen Pyside6 app with a librosa import on **Windows**, the application gives the error:
```
Traceback (most recent call last):
  File "C:\Users\Lithium\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 139, in run
    module_init.run(name + "__main__")
  File "C:\Users\Lithium\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\console.py", line 18, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "main.py", line 4, in <module>
  File "C:\Users\Lithium\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\__init__.py", line 215, in <module>
    __getattr__, __dir__, __all__ = lazy.attach_stub(__name__, __file__)
  File "C:\Users\Lithium\AppData\Local\Programs\Python\Python310\lib\site-packages\lazy_loader\__init__.py", line 243, in attach_stub
    raise ValueError(f"Cannot load imports from non-existent stub {stubfile!r}")
ValueError: Cannot load imports from non-existent stub 'C:\\Users\\Lithium\\Documents\\test-deploy\\dist\\lib\\librosa\\__init__.pyci'
```
This bug seems to only occur when I use the **latest librosa** version, 0.10.0. When I downgraded to 0.9.2, I was able to successfully run the frozen application. 

**To Reproduce**
Install librosa 0.10.0
[Using this Pyside6 app with a librosa import](https://gist.github.com/jpcarreon/add3a20bfc0afea0d8f33a54bfae6960)
Freeze the application with a setup file
```python
import sys
from cx_Freeze import setup, Executable

build_exe_options = {
    "includes": ["librosa"],
    "zip_include_packages": ["PySide6"],
    "include_msvcr": True,
}

base = "Win32GUI" if sys.platform == "win32" else None

setup(
    name="Test",
    version="1.0",
    description="My GUI application!",
    options={"build_exe": build_exe_options},
    executables=[Executable("main.py", base=base)],
    
)
```

Run the frozen application

**Expected behavior**
Shows a simple Pyside6 application which lets the user select an mp3/flac file.

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 10 Pro 22H2 
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: 6.14.7
 - Python version [e.g. 3.10]: 3.10.10

**Additional context**
Freezing and running an app which uses librosa 0.10.10 on Ubuntu 20.04 works just fine. This bug only happened when I attempted to freeze my app on a Windows VM.

**Comment by marcelotduarte** [comment]
Change:
`"includes": ["librosa"],`
To:
` "packages": ["librosa"],`
should solve the issue.

**Comment by jpcarreon** [comment]
I tried that and it still gave me the same error.
<details>
<summary>screenshot</summary>
<img src="https://user-images.githubusercontent.com/80230345/225500433-898e72e7-b985-42a1-9ae9-25b8a780ed68.png" alt="screenshot" />
</details>

**Comment by marcelotduarte** [comment]
Now I see the issue with the suffix (.pyi vs .pyci)
(For my reference `lazy.attach_stub(__name__, __file__)` in  https://github.com/librosa/librosa/pull/1579/files#diff-3cb8a08f8ebafdecd7c0436b39b9b3907f40055b6f0c13c431b3585fbf29b3a8)

Later I'll make a hook to workaround this.

**Comment by jpcarreon** [comment]
Thanks a lot! Looking forward to the release.

**Comment by marcelotduarte** [comment]
I verified that lazy_loader v0.2rc00.2 has a fix for this: https://github.com/scientific-python/lazy_loader/releases
Therefore, you must request the librosa maintainer to use it and make a new release.

**Comment by jpcarreon** [comment]
Interesting, I shall do so if I notice any issues with using librosa 0.9.2. I do not really mind waiting for librosa to update by themselves. Nonetheless, I thank you for the help.

**Comment by samreg** [comment]
Hello @jpcarreon , I have exactly the same problem while compiling a python project using LIBROSA 10.2 with cx_Freeze on windows platform.

Did you get any further informations or did you find a way to make it work?

Thanks

**Comment by jpcarreon** [comment]
Downgrade librosa to 0.9.2 and it should work.

**Comment by marcelotduarte** [comment]
Could you update lazy_loader to 0.2 and give us feedback?

**Comment by jpcarreon** [comment]
Thanks for the heads up! I have updated librosa to 0.10.0.post2 and lazy_loader to 0.2 and it now correctly runs on Windows.

**Comment by samreg** [comment]
I tried to compile with cx_freeze and the auto-py-to-exe (based on PyInstaller I guess)

1.  I downgraded librosa to 0.9.2 and **it worked**.
2. After I upgraded layzy_loader and **it still worked**.



Then I tried the config (librosa last version 10.0.post2 and layzy_loader 0.2. I do not have the initial error (of this tread) 
Cx_freeze, gives.... nothing at all! Even no logs, or error, but not my program...
auto-py-to-exe gives me another error , still with librosa 
```
.....site-packages\librosa\feature\spectral.py", line 8, in <module>
    import scipy.fftpack
ModuleNotFoundError: No module named 'scipy.fftpack'
```
I will try to figure that out. 


 Thanks

**Comment by marcelotduarte** [comment]
Include it with --includes=scipy.fftpack

**Comment by samreg** [comment]
It works! Thanks a lot!!

**Comment by marcelotduarte** [comment]
@samreg Can you test if it works using --packages=librosa instead of previous --includes?

**Comment by samreg** [comment]
Actually, I had used --package and not --includes...

I have just tested with --includes but , then, it does not work. 
layzy_loader says : no modules named "librosa.feature.spectral"

**Comment by marcelotduarte** [comment]
[Release 6.14.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.14.8)
