### ISSUE TITLE
How does cx_Freeze detect the virtual environments/dependencies?

### ISSUE THREAD

**Issue by klm555** [marcelotduarte/cx_Freeze#1838]
(This question was also posted on [here](https://stackoverflow.com/questions/75156735/how-does-cx-freeze-detect-the-virtual-environments-dependencies), but no one answered.)

**My Problem**
I just succeeded to build ```.exe``` file with cx_Freeze.\
The only problem is that **the size of the build folder(incl. .exe, .ui, libraries) is too large(1.02GB)** in spite of a few functions. And I found that the folder called **numpy_mkl takes up a large proportion(745MB)** of the build folder.

Because Anaconda is installed on my PC and I know that numpy installed in Anaconda environment accompanies mkl, I created ```.venv```(independent virtual environment with virtualenv) and installed numpy with ```pip install numpy``` in this virtual environment.

However **it seems cx_Freeze consider not only the libraries from active virtual environment(```.venv```) but also from the libraries installed by Anaconda.**

This is the part of the log from execution of ```python setup.py build```.

```creating directory C:\Users\hwlee\Desktop\Python\PBD_p3d\build\exe.win-amd64-3.9\lib\numpy_mkl
copying C:\Users\anaconda3\Library\bin\mkl_avx.1.dll -> C:\Users\Desktop\Python\P3-pid\build\exe.win-amd64-3.9\lib\numpy_mkl\mkl_avx.1.dll
copying C:\Users\anaconda3\Library\bin\mkl_avx2.1.dll -> C:\Users\Desktop\Python\P3-pid\build\exe.win-amd64-3.9\lib\numpy_mkl\mkl_avx2.1.dll
```
Is there anyone who knows how cx_Freeze detect the dependencies?\
Or any solution to this problem is welcome! 

**Desktop (please complete the following information):**
 - Platform information : Windows 10.0.19043
 - OS architecture : 64bit
 - cx_Freeze version : 6.13.1
 - Python version : 3.9.12

**Comment by marcelotduarte** [comment]
The answer would be long. Please feel free to check the sources. The [code layout](https://cx-freeze.readthedocs.io/en/latest/development/code_layout.html) can help too.

You can limit what is to be included. For instance, if you do not need numpy, you can use [excludes](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-excludes).
It is very common to use excludes with tkinter too, as tkinter is always present.
`excludes = ["tkinter", "numpy"]`
In anaconda, if you uninstalled numpy but do not uninstall mkl the files continue present.

**Comment by klm555** [comment]
@marcelotduarte 
Thank you for your answer!
I think my post was too rambling, so allow me to clarify. The point of my post is **I created the local environment** .venv and built the exe file in that specific project folder. However **it seems some libraries from the global environment are also being included in the exe file.**

I found numpy_mkl folder in ``build\exe.win-amd64-3.9\lib``, so tried ``excludes = ['numpy_mkl']`` in setup.py, but it still has not excluded numpy_mkl(I cannot exclude whole numpy library because it is used in the code).

Do you come up with any idea how to deal with this problem?

**Comment by marcelotduarte** [comment]
>  In anaconda, if you uninstalled numpy but do not uninstall mkl the files continue present.

Use conda list to see the name of mkl (perhaps mkl-service) and try to uninstall it.

**Comment by gengshenghong** [comment]
I got similiar issues in conda context~

I have a conda environment, with numpy,scipy,matplotlib etc.

When I create a folder with a hello.py file (print hello world only), run 'cxfree hello.py', the result build directory is about 30M, which is expected.

But when I create a test.py file (just one line to import numpy as np), run 'cxfree hello.py' (**not test.py**), the result build directroy is 1.7G!! If I run 'cxfree test.py', it is also 1.7G obviously.

It is very confusing:
1. there is no relationship between hello.py and test.py, why it will increases to 1.7G for the helloworld script.
2. even for test.py, does it make sense to be 1.7G? It seems like many unneccessary libraries are packaged.

are these expected? will cxfreeze analysis the dependencies automatically? I've tested other libraries, importing any library will result the build directory to be about 1.7G always.

Thanks,
Shenghong

**Comment by marcelotduarte** [comment]
@gengshenghong It is expected.
A simple hello script -  print("hello") - doesn't import anything, so cx_Freeze don't find nothing, only the basic standard library.
An import numpy added to it has various internal imports, and in conda, that are various extensions, like mkl that are detected to be used by numpy.
The better approach to get the minimal size is using python from python.org and using a virtual environment with only the needed packages, and sometimes with the use of excludes reducing more and more. For example, if you do not use tkinter, use --excludes=tkinter
In your test, try to use --exludes=mkl or --excludes=mkl_service to see the results and give me feedback.
I'll try to explore the possibility to optimize this case.

**Comment by gengshenghong** [comment]
Thank you for your feedback.

> A simple hello script - print("hello") - doesn't import anything, so cx_Freeze don't find nothing, only the basic standard library.

For this issue, please note that I am running cxfreeze on hello.py, but it is affected by test.py in the same directory. (hello.py does not import test.py in fact).
```
# hello.py
print('hello, world')

# test.py
import numpy as np

print(np.__version__)

# the command line
cxfreeze hello.py -> 1.7G
cxfreeze test.py -> 1.7G
```

> An import numpy added to it has various internal imports, and in conda, that are various extensions, like mkl that are detected to be used by numpy.

In fact, not only mkl, all the packages in my conda environment are packaged. I've tested with --excludes=mkl but it is still 1.7G. I also tested with --includes=numpy it is same. I also have pyside6 installed in the conda environment, everything are packaged into build in fact~

Thank you for your clarification, I heard that conda enviroment is a bit complex in dependencies by design. Maybe it is better to package in a clean environment with official python installed~

Thanks,
Shenghong

**Comment by gengshenghong** [comment]
```
build_exe_options = {
    "excludes": ["tkinter", "unittest"],
    "zip_include_packages": ["encodings", "PySide6"],
}
```

I've added above configurations, the size is now 1.2G. Maybe the automatic dependecy analysis has some issues in my conda enviroment and require some fine tune configurations manually~

Thanks,
Shenghong

**Comment by gengshenghong** [comment]
@marcelotduarte I can confirm the size comes from MKL (about 800M!), but using excludes=mkl does not affect. I've uninstall numpy and reinstall with "conda install blas=*=openblas numpy" to make sure MKL does not exist in my conda environment. Now, the build will be about 700M. Maybe more fine tune with the environment itself will help~

But is is still a little confusing when create an unimported test.py in hello.py folder, run cx freeze with hello.py will also be affected in my enviroment.

Thanks,
Shenghong

**Comment by marcelotduarte** [comment]
@klm555 In conda-forge mkl is a package but is not a python package, so this confused me, and excludes=mkl really does not work.
Now, the new hook for numpy only copies the mkl libraries if it is installed with numpy. And works with the blas option mentioned by @gengshenghong

**Comment by marcelotduarte** [comment]
[Release 6.14.9](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.14.9)

**Comment by klm555** [comment]
This really reduced the size of the build folder drastically!
I think this isn't' the best solution which excludes all libraries from conda environment, but this is satisfactory enough.
Thank you so much @marcelotduarte and @gengshenghong !

**Comment by marcelotduarte** [comment]
In a conda environment is the best solution. There are libraries that can not be excluded.
If you use pip to install numpy, it does not copy mkl.
If you use `conda install -c conda-forge blas=*=openblas numpy` it does not copy mkl, only openblas.
What can be the best?

**Comment by klm555** [comment]
@marcelotduarte Still don't know the reason(this problem may be caused from somewhere on my PC), but when anaconda is already installed on my Windows, even if I create independent environment which doesn't use any libraries from conda, libraries from conda are installed together in the building process.

This is something I have not faced in pyinstaller when I build with same process.
