### ISSUE TITLE
ImportError: cannot import name 'launcher' from partially initialized module 'ipyparallel.cluster'

### ISSUE THREAD

**Issue by CanYing0913** [marcelotduarte/cx_Freeze#1845]
**Describe the bug**
I have a project in my [repo](https://github.com/CanYing0913/CaImAn/tree/GUI_dev). As you can see from `src/src_caiman.py`, I import quite a lot modules and submodules from `caiman` library. I freeze it and have following error:
![image](https://user-images.githubusercontent.com/74372617/226446068-793c4ea8-8d86-4589-9e7b-f518d11102d7.png)
I know that I can change the way it imports modules to fix it. However, because the error comes from the library which utilizes bulit-in package (`ipyparallel`), I don't really want to modify anything there. Is there anything I can do to make this work?

**To Reproduce**
setup.py already in the repo. Below is the way to create a conda environment:
```
conda install -n base mamba
mamba create -n test_env -c conda-forge numpy=1.21 caiman pyimagej openjdk=8 seaborn
conda activate test_env
conda install -c conda-forge cx-logging lief
conda install -y --no-channel-priority -S -c ttps://marcelotduarte.github.io/packages/conda cx_Freeze
```

**Desktop (please complete the following information):**
 - Platform information: Windows 10 64 bit
 - OS architecture: amd64
 - cx_Freeze version : 6.15.0.dev2
 - Python version : 3.8

**Comment by marcelotduarte** [comment]
Errors similar to this can be solved by using [packages](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-packages)

**Comment by CanYing0913** [comment]
> Errors similar to this can be solved by using [packages](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-packages)

I see. What module(s) exactly I need to put there in this case? I simply put 'caiman' there since it is the root package that causes it, but it didn't work. Should I put whatever the error message suggests?

**Comment by marcelotduarte** [comment]
ipyparallel

Em seg., 20 de mar. de 2023 19:25, Yian Wang ***@***.***>
escreveu:

**Comment by CanYing0913** [comment]
Thanks, it fixed for me.

**Comment by CanYing0913** [comment]
Greeting, sir, sorry to bother you, I just want to know if the version of `cx_Freeze` I am using will be updated to the next release to `conda-forge`? I am trying to write a procedure to replicate my environment. If I still need to run `conda install -y --no-channel-priority -S -c ttps://marcelotduarte.github.io/packages/conda cx_Freeze` in the future, I will do so. Thanks!

**Comment by marcelotduarte** [comment]
I always publish new releases to pypi, conda-forge and msys2. `packages` is only for test/development version.
