### ISSUE TITLE
ImportError: No module named 'importlib.abc'

### ISSUE THREAD

**Issue by vasole** [marcelotduarte/cx_Freeze#1846]
I get this error message when trying to freeze an application.

However, if I remove the line `self.include_module("importlib.abc")` in `finder.py` or I replace it by `self.include_module("importlib")` everything works fine.

Windows platform, python 3.10 and 3.11 from python.org

**Comment by marcelotduarte** [comment]
This error is strange, because I always used about 30 of the [samples](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples) to test before each release and it works.
Paste the error message and more information on how to get the error. For example, can you test with the [simple](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/simple) sample?

**Comment by vasole** [comment]
Yes it is strange. Your example works perfectly.

However, I need to replace `importlib.abc` by `importlib` in my case:

![image](https://user-images.githubusercontent.com/5636251/226885193-01ca8cb9-a552-40fa-9a2f-17ad655522c4.png)

**Comment by marcelotduarte** [comment]
The 4 lines starting at 'Warninh' are from your cx_setup.py?
Put here the `pip list`

**Comment by vasole** [comment]
Yes, they are from my script.

![image](https://user-images.githubusercontent.com/5636251/226887532-c50ad6f7-d467-4c72-b32b-1e7f055bacb2.png)

**Comment by marcelotduarte** [comment]
remove (uninstall) or update importlib-metadata and test

**Comment by vasole** [comment]
Same result. I have tried both, removal and upgrade.

![image](https://user-images.githubusercontent.com/5636251/226901767-1fc32f49-1bd0-4a9c-828a-c90dd111c439.png)

**Comment by marcelotduarte** [comment]
What is the exact python version? (python -VV)
Are you using some environment variable starting with DISTUTILS or SETUPTOOLS? (set or cmd /c "set")

**Comment by vasole** [comment]
Python 3.11.2 (but the problem was also present with Python 3.10)

No environment variable starting by DISTUTILS nor SETUPTOOLS.

**Comment by marcelotduarte** [comment]
You says:

> Your example works perfectly.

If the simple sample works, and it includes "importlib.abc" without errors, I just think that is some package that is changing the behavior of python. importlib-metadata and setuptools change the finder mechanism, but I have used this versions.... are you change sys.path or using build_exe [path](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-path)?

Can you paste your setup or relevant part of it?

**Comment by vasole** [comment]
You will have to comment line 76 in:

https://github.com/vasole/pymca/blob/cx/package/cxfreeze/cx_setup.py

I have been using cx_Freeze since 2006 and perhaps some of the things I do there they are no longer necessary but if it works...

**Comment by marcelotduarte** [comment]
line 199 break it
line 120-122 can be changed to excludes.append("tkinter")
line 99-101 is irrelevant as encodings is included as package.

**Comment by vasole** [comment]
Great! Removing 199 works nicely.

Thanks a lot and sorry for the time taken.
