### ISSUE TITLE
Missing .dll file required by executable in MinGW

### ISSUE THREAD

**Issue by mathiascode** [marcelotduarte/cx_Freeze#1850]
**Describe the bug**

Executables created in MinGW no longer run, complaining about a missing `libwinpthread-1.dll` file.

Error message: `The code execution cannot proceed because libwinpthread-1.dll was not found. Reinstalling the program may fix the problem.`

This seems like issue https://github.com/marcelotduarte/cx_Freeze/issues/1651 again, but `libgcc_s_seh-1.dll` is present this time.

**To Reproduce**

Use any of the sample setup.py scripts in a MinGW environment, and attempt to run the generated executable.

**Expected behavior**

Required .dll files are installed in the correct directory to allow the executable to run.

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): MinGW on Windows Server 2019 (GitHub Actions)
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: 6.14.7
 - Python version [e.g. 3.10]: 3.10

**Comment by marcelotduarte** [comment]
I have tests in GA too, 23 samples are tested in ucrt64, mingw64, and 32. Tested Mar 13 and passed.
I'll run the tests now.

**Comment by marcelotduarte** [comment]
[Release 6.14.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.14.8)
