### ISSUE TITLE
Some files are not uploaded after the build

### ISSUE THREAD

**Issue by fernandohlBayer** [marcelotduarte/cx_Freeze#1858]
**Prerequisite**

**Describe the bug**

When I run ```python setup.py build```, some files are not uploaded to the lib directory.
For example, I'm using boto3. When I look for the directory boto3, the directory s3 is not uploaded. Even adding "packages" or "include" in the option build_exec, it doesn't work.

**Expected behavior**
All files should be uploaded to the lib directory

**Screenshots**
![image](https://user-images.githubusercontent.com/124812229/228961878-fb4e9e30-1eba-4891-b250-2b162eb96af1.png)
![image](https://user-images.githubusercontent.com/124812229/228964824-402431d7-020a-474d-8d76-ecb622063cd5.png)
![image](https://user-images.githubusercontent.com/124812229/228964899-18222b4b-bb52-480e-89d0-4aa50f6dac46.png)

**Desktop (please complete the following information):**
 - Platform information (Windows 10)
 - OS architecture (amd64)
 - cx_Freeze version [cx-Freeze==6.14.7]
 - Python version [3.11]

**Comment by marcelotduarte** [comment]
Try to use packages = ["boto3.s3"]
I see that boto3 uses a lazy load model that can break the search for packages.

**Comment by fernandohlBayer** [comment]
I tried to do it this way, but it didn't work :/. 

A lot of files are not uploaded to the lib directory. However, I ended up doing a copy of my venv where I have the lib directory to setup build the lib directory

```python
import shutil
shutil.copytree(
    f'{venv_name}/Lib/site-packages/',
    f'build/{os.listdir("build")[0]}/lib/',
    dirs_exist_ok=True
)
```
I know it's not the best way. However, It worked for me.

I'm going to research about boto3 to understand what happened.

Thanks a lot.

**Comment by marcelotduarte** [comment]
Make a simple test to me, that I'll create a hook for it.
I have access to a S3 key, so with a sample we can test and debug.

**Comment by fernandohlBayer** [comment]
I tried other tests, but they didn't work.
Would you like me to do a specific test?

**Comment by marcelotduarte** [comment]
I mean a simple code to reproduce the error.

**Comment by fernandohlBayer** [comment]
I have checked the logs, and I don't find copy information on the boto3.s3
![image](https://github.com/marcelotduarte/cx_Freeze/assets/124812229/c14c2b80-cf35-41ac-9780-48a407d6cfd2)

My test:

```python
import sys

from cx_Freeze import Executable, setup

VERSION = "0.1.1"

if __name__ == "__main__":
    # Dependencies are automatically detected, but it might need fine tuning.
    print(f'Building version app: {VERSION}')
    build_exec_options = {
        "packages": ["boto3", "boto3.s3"],
        "excludes": ["pytest"],
        "optimize": 2,
    }

    base = "Win32GUI" if sys.platform == "win32" else None

    setup(
        name="APP TEST",
        version=VERSION,
        description="TEST",
        options={"build_exec": build_exec_options},
        executables=[
            Executable(
                "main.py",
                base=base,
                icon="source/static/bivm.ico",
                target_name="test.exe",
            )
        ],
    )
```

It looks like the code ignores the directory.

**Comment by marcelotduarte** [comment]
ok, I need a simple **main.py** to reproduce the error, for instance:
```
import boto3
#more code
```

**Comment by fernandohlBayer** [comment]
Right. Test file:

```python
import PySimpleGUI as sg
import boto3
import certifi

layout = [[sg.Text("Hello from PySimpleGUI")], [sg.Button("OK")]]

# Create the window
window = sg.Window("Demo", layout)

s3 = boto3.resource(
    "s3",
    aws_access_key_id='AWS_ACCESS_KEY_ID',
    aws_secret_access_key='AWS_SECRET_ACCESS_KEY',
    verify=certifi.where(),
)

# Create an event loop
while True:
    event, values = window.read()
    if event == "OK" or event == sg.WIN_CLOSED:
        s3.Object('bucket_name', 'path').put(Body=values)

window.close()
```

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by fernandohlBayer** [comment]
Of course.

I did a test, and it now works perfectly.

Outcome:
![image](https://github.com/marcelotduarte/cx_Freeze/assets/124812229/642a8af7-34c9-49ab-b7a5-8e12721d63b5)
![image](https://github.com/marcelotduarte/cx_Freeze/assets/124812229/06564cf3-a268-4219-9348-8e2ae6f7255e)
