### ISSUE TITLE
How to include a MediaPipe .task file

### ISSUE THREAD

**Issue by rajtilakjee** [marcelotduarte/cx_Freeze#1895]
I have created a Python script for a hand gesture recognition task. It includes a .py file, a .task MediaPipe model, and a requirements.txt file. How to include the .task file? Should I use --add-data?

**Comment by marcelotduarte** [comment]
Use [include_files](https://cx-freeze.readthedocs.io/en/latest/setup_script.html#cmdoption-arg-include_files).

**Comment by rajtilakjee** [comment]
@marcelotduarte It worked! Thanks so much!
