### ISSUE TITLE
scipy.libs folder is not copied/searched at correct location by cx_Freeze

### ISSUE THREAD

**Issue by dcnieho** [marcelotduarte/cx_Freeze#1899]
**Describe the bug**
Apparently the same as issue https://github.com/marcelotduarte/cx_Freeze/issues/1889 but for scipy instead of matplotlib:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\huml-dkn\\Downloads\\glassesValidator-Windows\\lib\\library.zip\\scipy.libs'.
scipy.libs is found under \lib\scipy.libs but not in the searched location \lib\library.zip\scipy.libs.

**To Reproduce**
Scipy is used in rather complicated code (https://github.com/dcnieho/glassesValidator), so i don't have a simple example. But any file using scipy that you cx_freeze should do the trick. I'll try to whip up an sample and send as pull request.

**Desktop (please complete the following information):**
Running OS (but built in github action https://github.com/dcnieho/glassesValidator/actions/runs/5176976719/jobs/9326492455):
 - Platform information: Windows 11
 - OS architecture: amd64
 - cx_Freeze version: Latest, installed with `pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
 - Python version: 3.10
 - Scipy version: 1.10.1

**Comment by dcnieho** [comment]
Yes, this is a issue with a local build on my machine as well. Close #1900, then:
```
pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze
pip install scipy
python .\setup_zip.py build
```
and running the exe reproduces the error.

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by dcnieho** [comment]
Super, that fixed the problem! I see you have also included my pull request already, so i don't have to rebase that, correct? Thanks for the quick action!

**Comment by dcnieho** [comment]
Would you be up for making a release soon? Matplotlib and scipy working again is important to me!

**Comment by marcelotduarte** [comment]
~Please make a new pull request with your sample based on main branch, not on develop branch.~
I'll make a release soon, maybe 2 days.

**Comment by marcelotduarte** [comment]
I pushed new pr for the sample: #1904

**Comment by marcelotduarte** [comment]
[Release 6.15.1](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.1)
