### ISSUE TITLE
zip_exclude_packages incomplete for packages having subfolders

### ISSUE THREAD

**Issue by lilagerd** [marcelotduarte/cx_Freeze#1907]
**Describe the bug**
zip_exclude_packages only works for partial content of a package with subfolders. .pyc files are located in the library.zip, not in the file system

**To Reproduce**
Instantiate Freezer with zip_exclude_packages=["Cryptodome"]. This results in a lib\Cryptodome\Util folder containing only partial content (*.pyd and *.pyi files), e.g. file "asn1.pyi". The library.zip contains a Cryptodome folder too with all the .pyc files, e.g. file "library.zip\Cryptodome\Util\asn1.pyc".

**Expected behavior**
All content for the excluded package is in the filesystem, not in the library.zip.

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Windows 10 Pro, 21H2
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: cx_Freeze-6.15.1
 - Python version [e.g. 3.10]: Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32

**Additional context**
Seems to be an issue since this checkin:
https://github.com/marcelotduarte/cx_Freeze/pull/1839/commits/66df633a44e8569e4d2c9bd7c359c255d485b12a

Change is in module cx_freeze\module.py, property/method "in_file_system"

Probably the fix is to change the following return:
    @property
    def in_file_system(self) -> int:
		...
        if self.parent is not None:
            return self.parent._in_file_system  -> return self.parent.in_file_system

**Comment by Berserker66** [comment]
Ran into this with https://github.com/ArchipelagoMW/Archipelago/blob/main/setup.py
Current release only includes the init for /worlds/* folders, creating a broken release. Last major version ([6.14.9](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.14.9)) works fine.

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by lilagerd** [comment]
Thanks for the quick fix. With the patch, our application (which is quite complex, among others with dependencies to PyQt and waitress) can be built without errors.

**Comment by marcelotduarte** [comment]
[Release 6.15.2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.2)
