### ISSUE TITLE
zip-include-packages broken for nested packages

### ISSUE THREAD

**Issue by mndavidoff** [marcelotduarte/cx_Freeze#1912]
**Describe the bug**

When `--zip-include-packages` is used for a package that has nested packages, the nested packages are only partially included in `library.zip`. The `library.zip` file contains `__init__.pyc` for a nested package, but not the `*.pyc` for any other modules included in the nested package.

**To Reproduce**

The complete test case, including `__init__.py` files, is attached. Here are the salient files.

In `p/p1.py`:
```python
print('This is p.p1')
```

In `p/q/q1.py`:
```python
print('This is p.q.q1')
```

In `main.py`:
```python
import p.p1
import p.q.q1
```

Run cx_Freeze:

```bash
cxfreeze --zip-include-packages=p main.py
```

Run the application:

```bash
build/exe.linux-x86_64-3.9/main
```

Output:
```
This is p.p1
Traceback (most recent call last):
  File "/home/monte/.cache/pypoetry/virtualenvs/cxfreeze-zip-test-KweqTxz--py3.9/lib64/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 130, in run
    module_init.run(name + "__main__")
  File "/home/monte/.cache/pypoetry/virtualenvs/cxfreeze-zip-test-KweqTxz--py3.9/lib64/python3.9/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
    exec(code, module_main.__dict__)  # pylint: disable=exec-used
  File "main.py", line 2, in <module>
    import p.q.q1
ModuleNotFoundError: No module named 'p.q.q1'
```

Note that `library.zip` contains:

* `p/__init__.pyc`
* `p/p1.pyc`
* `p/q/__init__.pyc`

However, this file is in the file system, not `library.zip`:

* `lib/p/q/q1.pyc`

**Expected behavior**

The expected output is:

```
This is p.p1
This is p.q.q1
```

**Desktop (please complete the following information):**
 - Platform information: Rocky Linux 8.7
 - OS architecture: amd64 (x86_64)
 - cx_Freeze version: 6.15.1
 - Python version: 3.9

**Additional context**

This worked in cx_Freeze 6.14.9. The regression appears to have been introduced in cx_Freeze 6.15.0.

[cxfreeze-zip-test.tar.gz](https://github.com/marcelotduarte/cx_Freeze/files/11739411/cxfreeze-zip-test.tar.gz)

**Comment by mndavidoff** [comment]
This issue might be related to #1907.

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by mndavidoff** [comment]
The patch fixes this issue. Thank you!

**Comment by marcelotduarte** [comment]
Thank you for the good steps to reproduce. I used it as sample to test.
[Release 6.15.2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.2)
