### ISSUE TITLE
error: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\myuser\\AppData\\Local\\Microsoft\\WindowsApps\\python3.11.exe\\python311.dll'

### ISSUE THREAD

**Issue by subjoel** [marcelotduarte/cx_Freeze#1915]
hi, so i am trying to use cx_freeze but whenever i run python setup.py build it gives me this output:
```
running build
running build_exe
error: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\myuser\\AppData\\Local\\Microsoft\\WindowsApps\\python3.11.exe\\python311.dll'
```

**Comment by subjoel** [comment]
anyone know how to fix this?

**Comment by marcelotduarte** [comment]
Are you using Python from Windows Store?
Use the Python from python.org

**Comment by marcelotduarte** [comment]
Can I close this issue?

**Comment by Aurelog** [comment]
Hello, got the same the same issue.
Removing Windows Apps Python, and install it from Python.org fixed this as you mentionned.

Thank you !
