### ISSUE TITLE
'exit' is not defined (built-in)

### ISSUE THREAD

**Issue by Berserker66** [marcelotduarte/cx_Freeze#1937]
**Prerequisite**
 - Make sure no duplicated issue has already been reported. You should look for closed issues, too.
 - Make sure you are not asking us to help to solve your specific issue. GitHub issues are opened mainly for development purposes. If you want to ask someone to help to solve your problem, go to some community site like StackOverflow, etc.
 - Make sure your problem is not derived from packaging (e.g. Homebrew).

I have found references to this on Stackoverflow since about 2017, but looking for it through issues here has not been successful, though I only looked at titles given the sheer amount

**Describe the bug**
exit() built-in function is reported as not defined when the application  is frozen. 
For example from https://github.com/ArchipelagoMW/Archipelago/pull/1905:
```
Traceback (most recent call last):
  File "__startup__.py", line 130, in run
  File "console.py", line 16, in run
  File "MultiServer.py", line 2294, in <module>
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "MultiServer.py", line 2262, in main
NameError: name 'exit' is not defined
```

**To Reproduce**
Steps to reproduce the behavior (a setup.py or a minimal code sample will be good)

https://github.com/ArchipelagoMW/Archipelago/blob/main/setup.py

**Expected behavior**

Expected the built-in to exist and to be callable, as well as result in shutdown. If there's a good reason to not have exit available, then I would have expected it to be replaced with a function that raises an Exception saying why.

**Screenshots**

Not applicable

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04):
 - OS architecture (e.g. amd64):
 - cx_Freeze version [e.g. 6.11]:
 - Python version [e.g. 3.10]:

Windows 10 22H2
amd64
Tested 6.14.9 and 6.15.2, likely many affected though.
Tested with 3.11

**Additional context**

**Comment by marcelotduarte** [comment]
From https://docs.python.org/3/library/constants.html?highlight=exit#constants-added-by-the-site-module
_"The [site](https://docs.python.org/3/library/site.html#module-site) module (which is imported automatically during startup, except if the [-S](https://docs.python.org/3/using/cmdline.html#cmdoption-S) command-line option is given) adds several constants to the built-in namespace. They are useful for the interactive interpreter shell and should not be used in programs."_

cx_Freeze is built with no support to site (site-packages) using [Py_NoSiteFlag](https://docs.python.org/3/c-api/init.html?highlight=py_nositeflag#c.Py_NoSiteFlag).

**Comment by Berserker66** [comment]
Ok, fair. Given that when looking up this problem via google, one finds several Stackoverflow issues, none of which have this insight, I'd recommend putting a replacement function in place that notifies of this "quirk".

**Comment by marcelotduarte** [comment]
https://www.geeksforgeeks.org/python-exit-commands-quit-exit-sys-exit-and-os-_exit/
