### ISSUE TITLE
Error with frozen executable using 3.5 and pywin32

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#194]
Originally reported by: **Jeff Smith (Bitbucket: [tardis5500](https://bitbucket.org/tardis5500), GitHub: Unknown)**

----------------------------------------

This is with the lastest cx_freeze source, Python 3.5.1 (64-bit), and pywin32 220.

I freeze a simple script:
import pywintypes
print('Hello world')

When I run it I get 
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\cx_freeze-5.0-py3.5-win-amd64.egg\cx_Freeze\initscripts\Console.py", line 21, in <module>
    exec(code, m.__dict__)
  File "tester.py", line 1, in <module>
ImportError: No module named 'pywintypes'

I recently upgraded from Python 3.4 using cx_freeze 4.3.4 where this worked fine.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/194

**Comment by anthony-tuininga** [comment]
*Original comment by* **12345 67890 (Bitbucket: [12345_67890](https://bitbucket.org/12345_67890), GitHub: Unknown)**:

----------------------------------------

I do want to confirm here that cx_Freeze doesn't play well with pywin32, even in the lastest version, with Python 3.5. I had to roll back to 3.4 because I couldn't get it to work.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Rob Ashdown (Bitbucket: [robashdown_ae](https://bitbucket.org/robashdown_ae), GitHub: Unknown)**:

----------------------------------------

I'm also seeing this issue, in Python 3.5.2 (32 bit), cx_freeze==5.0, pywin32==220

**Comment by thopiekar** [comment]
I personally don't see any issues.
Using our (Ultimaker) build scripts for Cura, I just added PyWin32 to the list of dependencies and it got included to our package at the end, which is a NSIS installer.
I personally worry more about the support to generate a COM server: https://github.com/anthony-tuininga/cx_Freeze/issues/333
Currently I have here a everything working: Can connect to a running instance, etc, but can't dispatch a server. Thought about different reasons, but noticed that Py2Exe provides special support to generate these needed executables. Are there somewhere special options, I don't know of?

**Comment by marcelotduarte** [comment]
This is too old.
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
