### ISSUE TITLE
Version metadata not being retrieved properly for py-cord

### ISSUE THREAD

**Issue by morg-mov** [marcelotduarte/cx_Freeze#1962]
### Discussed in https://github.com/marcelotduarte/cx_Freeze/discussions/1961

<div type='discussions-op-text'>

<sup>Originally posted by **Morg-S9** July 13, 2023</sup>
I'm building a program that utilizes a fork of the Discord.py library called Pycord.

I'm trying to freeze it for ease of use for others, but for one reason or another, after testing the frozen program on a workstation other than my own, it throws this runtime warning:
`C:\Users\Morg\<redacted>\venv\Lib\site-packages\discord\__init__.py:22: RuntimeWarning: Package is not installed, and setuptools_scm is not installed. As a fallback, discord._version.__version__ will be set to 0.0.0`

Implying that it's looking for ``__init__.py`` in my python virtual environment that I use for development rather than the included one with the frozen program.

What could be causing this?</div>

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by marcelotduarte** [comment]
[Release 6.15.4](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.4) is out!

**Comment by morg-mov** [comment]
Great! Thank you!
