### ISSUE TITLE
MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#199]
Originally reported by: **hadim (Bitbucket: [hadim](https://bitbucket.org/hadim), GitHub: [hadim](https://github.com/hadim))**

----------------------------------------

I have the following error running a binary created with `cx_freeze`. My Python program contains numpy and pandas related stuff.

```
MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.
```

Do you know if `cx_freeze` should have included numpy related library such as MKL ? or should I do it myself ?

Thanks

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/199

**Comment by anthony-tuininga** [comment]
*Original comment by* **Robert McLeod (Bitbucket: [robbmcleod](https://bitbucket.org/robbmcleod), GitHub: [robbmcleod](https://github.com/robbmcleod))**:

----------------------------------------

I assume you are using Anaconda which is linked to MKL?  In which case you can get around this by using the OpenBLAS version.

conda install nomkl numpy scipy scikit-learn numexpr
conda remove mkl mkl-service

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released with namespace detection. Please, try it.
I see an issue with numpy 1.18.3 to 1.19 and pillow 7.x, and I'm investigating.
For now, it has a workaround.
pip install "numpy<1.18.3" "pillow<7"
Assuming this has been resolved.
If you had issues please re-open.
