### ISSUE TITLE
Load monkeypatched libraries in dependencies

### ISSUE THREAD

**Issue by deeplow** [marcelotduarte/cx_Freeze#1996]
**Describe the bug**
In our project ([related issue](https://github.com/freedomofpress/dangerzone/issues/501)) we import the `markdown` module. Cx_Freeze build fine, but when we execute it, it fails to import the module

**To Reproduce**
Theoretically any project that imports the `markdown` but this is more general than that, I think.

**Expected behavior**
When executing there should be no error importing

**Screenshots**
![258082393-27039253-7e5e-40c4-9780-c5e7d4fae27a](https://github.com/marcelotduarte/cx_Freeze/assets/47065258/9d5a3591-7ac4-4c61-ace7-f5c331fce3ff)

**Desktop (please complete the following information):**
 - Platform information: Windows 10
 - OS architecture (e.g. amd64): x86_64
 - cx_Freeze version [e.g. 6.11]: 6.13.2
 - Python version [e.g. 3.10]: 3.11.0

**Additional context**
What I think is happening here is that Cx_Freeze relies on implicit dependencies and includes them in the "frozen" version. However, because the `markdown` module does not explicitly state `html.parser` as dependency, it fails to be included by Cx_Freeze and then it's not available when [this code](https://github.com/Python-Markdown/markdown/blob/master/markdown/htmlparser.py#L29):

```python
# Import a copy of the html.parser lib as `htmlparser` so we can monkeypatch it.
# Users can still do `from html import parser` and get the default behavior.
spec = importlib.util.find_spec('html.parser')
```

Our fix is to add a line before `import markdown`:

```python
import html.parser
import markdown
```

However, this is a bit dirty since we're not having a back-boxed approach to a dependency. It would be nice if Cx_Freeze could detect when modules are implicitly imported via the importlib module and also load them.

I think having Markdown explicitly state that dependency is not ideal because `html.parser` is in the [standard python library](https://github.com/python/cpython/blob/3.11/Lib/html/parser.py) and should always be assumed as present.

**Comment by marcelotduarte** [comment]
Detecting importlib is quite tricky, especially this method used by markdown.
Automatically including the whole stdlib isn't ideal either, because, for example, tkinter is in the stdlib, but not everyone wants it included in the binary.
But cx_Freeze has two mechanisms to solve this.
1) You can use the [includes](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cmdoption-arg-includes) option.
2) We can create a hook (#1997).

**Comment by marcelotduarte** [comment]
[Release 6.15.6](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.6) is out!

**Comment by deeplow** [comment]
Thanks! :heart:
