### ISSUE TITLE
Strange behaviour with py-cpuinfo

### ISSUE THREAD

**Issue by gcailly** [marcelotduarte/cx_Freeze#2001]
**Describe the bug**
After compiling my Python program (PySide6 GUI app) using cx_Freeze, I'm encountering strange behaviors that I don't see when running the uncompiled Python script. Specifically, a terminal window appears momentarily and then closes. Additionally, a second instance of my program is launched unexpectedly.

**To Reproduce**

I use this code in my program. It's a complex GUI so I only put here the problematic lines. When I remove them, no problem at all when compiled.

from cpuinfo import get_cpu_info

cpu_model = get_cpu_info().get("brand_raw", '')
print(cpu_model)

**Expected behavior**
I expect the compiled program to behave similarly to the Python script, without the terminal window appearing and without launching a second window (which is really strange).

**Desktop** (please complete the following information):

    Platform information: Windows 10
    OS architecture: 64 bits
    cx_Freeze version: 6.15
    Python version: 3.11.4

**Additional context**
I've identified that the module py-cpuinfo might be related to this issue. When running the Python script, this module operates as expected, but there seem to be anomalies once the code is compiled with cx_Freeze.
Maybe it could be related to this issue ?
https://github.com/workhorsy/py-cpuinfo/issues/174#issuecomment-1210459512

**Comment by marcelotduarte** [comment]
When a program (or in this case, a library) uses multiprocessing, the use of [freeze_support](https://docs.python.org/3/library/multiprocessing.html?#multiprocessing.freeze_support) is required.

In your case:

```
from multiprocessing import freeze_support
from cpuinfo import get_cpu_info

if __name__ == '__main__':
    freeze_support()
    cpu_model = get_cpu_info().get("brand_raw", '')
    print(cpu_model)
```

**Comment by gcailly** [comment]
Thank you very much.
Sadly, the behavior is the same : console window opens briefly, another main window appears, and I need to close this window for the CPU information retrieval to continue.
No problem when cx_freeze is not used.

**Comment by gcailly** [comment]
Sorry, I didn't read the documentation correctly.
It says :
> One needs to call this function straight after the if __name__ == '__main__' line of the main module.
Which I didn't do.
