### ISSUE TITLE
Seg-fault on PySide/PyQt4 and numpy in Python 3.4.5

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#201]
Originally reported by: **Robert McLeod (Bitbucket: [robbmcleod](https://bitbucket.org/robbmcleod), GitHub: [robbmcleod](https://github.com/robbmcleod))**

----------------------------------------

Hi,

With Python 3.4 there's a segmentation fault on trying to __init__() the QApplication in both PySide and PyQt4 if numpy is also imported.  I don't have the same problem in Python 2.7.12.

numpy.__version__ = '1.11.1'  (linked to OpenBLAS)
PySide.__version__ = '1.2.4'
PyQt4.Qt.PYQT_VERSION_STR = '4.11.4'

Here's a code fragment that can replicate the error:

```
#!python

import sys
from PySide import QtGui
#from PyQt4 import QtGui

# It looks like numpy asks for PyQt4, which gives us a namespace collision between PySide and PyQt4?
import numpy as np

class PySideApp( QtGui.QApplication, object ):

    def __init__(self):
        print( "DEBUG 0" )
        testArray = np.zeros( [256,256] )
        print( "sys.argv = " + str(sys.argv) )
        QtGui.QApplication.__init__(self, sys.argv)
        print( "DEBUG 1" )
        self.MainWindow = QtGui.QMainWindow()
        self.MainWindow.show()
        self.exec_()
        
        pass

if __name__ == "__main__":
    daauto = PySideApp()
```

And using the sample PyQt4 setup.py:

```
#!python

import sys
from cx_Freeze import setup, Executable

base = None
if sys.platform == 'win32':
    base = 'Win32GUI'

options = {
    'build_exe': {
        'includes': 'atexit'
    }
}

executables = [
    Executable('PySideApp.py', base=base)
]

setup(name='simple_PySide',
      version='0.1',
      description='Sample cx_Freeze PySide script',
      options=options,
      executables=executables
      )
```

Any thoughts on what might be happening?  I looked through hooks.py but I didn't see anything.  

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/201

**Comment by marcelotduarte** [comment]
Qt 4 reached end-of-life on 2015-12-19. Its Python bindings are also EOL: PyQt4 since 2018-08-31 and PySide since 2015-10-14.
