### ISSUE TITLE
cx_Freeze.exception.OptionError: no base named 'console' ('console-cpython-311-powerpc64le-linux-gnu')

### ISSUE THREAD

**Issue by Fox214** [marcelotduarte/cx_Freeze#2010]
Python version: 3.11.3
Cx_freeze version: 6.15.4
OS: RedHat 7.5
Arch: Power

Getting this error when I am running.
Pip installed without issue, works fine for x86 and arm architectures (same python/cx-freeze version)

For the ppc version the lib/python3.11/site-packages/cx_Freeze/bases directory is missing a lot of data (which explains the error I'm sure) don't know how to get it there. Specifically the lib lib-dynload and tcltk directories are all missing. (and the plethora of .so file contained therein) 

I've tried a manual build as well, same results.

**Comment by Fox214** [comment]
6.15.3 appears to work, so I will use that for now.

**Comment by marcelotduarte** [comment]
Try to use:

`pip install --no-binary=cx_Freeze cx_Freeze`

Have you tested with 6.15.5?

**Comment by Fox214** [comment]
6.15.5 appears to work. 6.15.4 did not with the flag. 

Now after I compile (with 6.15.3 or 6.15.5) I am getting this error while running:
lib/_sqlite3.cpython-311-powerpc64le-linux-gnu.so: undefined symbol: sqlite3_blob_open

The same symbol is in x86, ppc and arm files (with U via nm -a) (appears to be copied from):
lib/python3.11/lib-dynload/_sqlite3.cpython-311-x86_64-linux-gnu.so

However for both x86 and arm if I do nm -a on the copied version the symbols are stripped, but not in the ppc, what is it doing to the file after the copy? I'm still trying to drill through the code to find out.

**Comment by Fox214** [comment]
It appears that its actually copying from lib/python3.11/lib-dynload only for ppc (which has the symbols) and its copying the stripped version from lib/python3.11/site-packages/cx_freeze/base/lib-dynload on arm/x86 (that directory does not exist on ppc)

**Comment by marcelotduarte** [comment]
There are a difference here. For x86_64 and aarch64 cx_Freeze has binaries. For this other platform it is compiled from sources, so the cx_freeze/base/lib-dynload does not exist and the libraries are caught from the system.

Probably the patchelf dependency used is the system dependency and maybe it is corrupting something. What version of patchelf?

**Comment by Fox214** [comment]
Using patchelf 0.17.2 (all platforms, both 'new' and 'old' builds) the 'old' build is python 3.8.5 and cx_freeze 6.9 and works on all 3 platforms.

LD_DEBUG output for the 'new' (x86):

> symbol=sqlite3_blob_open;  lookup in file=myprog [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/libpthread.so.0 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/libdl.so.2 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/libutil.so.1 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/libm.so.6 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/libc.so.6 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
> symbol=sqlite3_blob_open;  lookup in file=/path/to/myprog/lib-linux64/lib/_sqlite3.cpython-311-x86_64-linux-gnu.so [0]
> symbol=sqlite3_blob_open;  lookup in file=/path/to/myprog/lib-linux64/lib/../lib/libsqlite3-f79e2a86.so.0.8.6 [0]
> binding file /path/to/myprog/lib-linux64/lib/_sqlite3.cpython-311-x86_64-linux-gnu.so [0] to /path/to/myprog/lib-linux64/lib/../lib/libsqlite3-f79e2a86.so.0.8.6 [0]: normal symbol `sqlite3_blob_open'
> symbol=PyObject_SetAttrString;  lookup in file=myprog [0]
> binding file /path/to/myprog/lib-linux64/lib/_sqlite3.cpython-311-x86_64-linux-gnu.so [0] to myprog [0]: normal symbol `PyObject_SetAttrString'

new ppc:

> symbol=sqlite3_blob_open;  lookup in file=myprog [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/power9/libpthread.so.0 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/libdl.so.2 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/libutil.so.1 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/power9/libm.so.6 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/libz.so.1 [0]
> symbol=sqlite3_blob_open;  lookup in file=/path/to/myprog/lib-linuxppc64/lib/libssl.so.1.1 [0]
> symbol=sqlite3_blob_open;  lookup in file=/path/to/myprog/lib-linuxppc64/lib/libcrypto.so.1.1 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/power9/libc.so.6 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/ld64.so.2 [0]
> symbol=sqlite3_blob_open;  lookup in file=/path/to/myprog/lib-linuxppc64/lib/_sqlite3.cpython-311-powerpc64le-linux-gnu.so [0]
> symbol=sqlite3_blob_open;  lookup in file=/path/to/myprog/lib-linuxppc64/lib/libsqlite3.so.0 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/power9/libpthread.so.0 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/power9/libc.so.6 [0]
> symbol=sqlite3_blob_open;  lookup in file=/lib64/ld64.so.2 [0]
> /path/to/myprog/lib-linuxppc64/lib/_sqlite3.cpython-311-powerpc64le-linux-gnu.so: error: symbol lookup error: undefined symbol: sqlite3_blob_open (fatal)
> file=/path/to/myprog/lib-linuxppc64/lib/_sqlite3.cpython-311-powerpc64le-linux-gnu.so [0];  destroying link map
> 
> file=/path/to/myprog/lib-linuxppc64/lib/libsqlite3.so.0 [0];  destroying link map

Turning silent=False on cxfreeze (x86):

> copying /CPython/3.11.3/linux64/lib/python3.11/site-packages/cx_Freeze/bases/lib-dynload/_sqlite3.cpython-311-x86_64-linux-gnu.so -> /path/to/myprog/lib-linux64/lib/_sqlite3.cpython-311-x86_64-linux-gnu.so
> copying /CPython/3.11.3/linux64/lib/python3.11/site-packages/cx_Freeze/bases/lib-dynload/../lib/libsqlite3-f79e2a86.so.0.8.6 -> /path/to/myprog/lib-linux64/lib/libsqlite3-f79e2a86.so.0.8.6

ppc:

> copying /CPython/3.11.3/linuxppc64/lib/python3.11/lib-dynload/_sqlite3.cpython-311-powerpc64le-linux-gnu.so -> /path/to/myprog/lib-linuxppc64/lib/_sqlite3.cpython-311-powerpc64le-linux-gnu.so

Curiously running nm -a on the cx freeze sqlite .so file says 'no symbols' even though its resolving it. I'm still poking around, I may try older versions of cx_freeze to see if one works (back to 6.9)

**Comment by Fox214** [comment]
Ok here's what happened with older versions (all 3.11.3 on ppc):
Version    	Status
6.9.0		Failed to install
6.10.0		Failed to install
6.11.1		Failed to run (missing symbol)
6.12.0		Failed to run (missing symbol)
6.13.2		Failed to run (missing symbol)
6.14.0		Failed to compile
6.14.9		Failed to run (missing symbol)
6.15.0		Failed to run (missing symbol)
6.15.1		Failed to run (missing symbol)
6.15.2		Failed to run (missing symbol)
6.15.3		Failed to run (missing symbol)
6.15.4		Failed to compile
6.15.5		Failed to run (missing symbol)

gcc was complaining about missing eval.h file in 6.9 and 6.10, this file appears to be missing from python3.11 but was in python3.8 it does seem to have some header definitions for PyObject stuff, but I don't know C well at all.

**Comment by marcelotduarte** [comment]
I will suggest you to generate the binary for your platform:
NOTE: docker or podman is required
( podman is easy to use, install and use `export CIBW_CONTAINER_ENGINE=podman` )
1) create a venv
2) build wheels
```
git clone https://github.com/marcelotduarte/cx_Freeze -b main615x
cd cx_Freeze
python -m cibuildwheel --output-dir wheelhouse --only cp311-manylinux_powerpc64le
```
Note: check if powerpc64le is the correct, use the suffix of sysconfig.get_platform()

3) So you can install cx_Freeze using:
`pip install -f path/to/wheelhouse cx_Freeze`

**Comment by Fox214** [comment]
I am trying to get my IT to install podman (i tried to build it myself and lack go on ppc as well) so I can let you know when/if that completes. 

I think the source my problem is sqlite3 installed locally is like 3.7.x and was build with extensions. The version I am trying to cx_freeze to is 3.33, is on a network file system, and was not built with extensions, thus when it copies that .so file (via include_files) the symbol is missing.  The symbol is the lib-dynload file (needed nm -D to detect) so this works on linux/arm but not ppc since I am missing the dynload .so file. 

3 things I am working on:
1. getting podman to follow your suggestion of building my own wheel and generate that missing file
2. trying to build python with the network sqlite 3.33 so it will never look for those symbols
3. may try and rebuild the network sqlite with the extentions (and the symbols should be present)

**Comment by marcelotduarte** [comment]
If you generate the binary, it will work, because to generate the binaries, we use manylinux, and the version in use of sqlite is 3.42 (https://github.com/pypa/manylinux/commit/794cbf3213a39416c5ea09f07cf300f100a40944).
I think that the correct command:
`python -m cibuildwheel --output-dir wheelhouse --only cp311-manylinux_ppc64le`

**Comment by Fox214** [comment]
That command requires docker (I assume untar the cx freeze package and run from the directory with setup.py in it?) so it doesn't work for me. 

I am still waiting to see if my IT can have podman installed, I have not been successful thus far in trying to build python to use a non-system sqlite by default. and my attempts to rebuild sqlite have also been unfruitful thus far, although still working on that.

**Comment by marcelotduarte** [comment]
Works with Podman too. Check [CIBW_CONTAINER_ENGINE](https://cibuildwheel.readthedocs.io/en/stable/options/#container-engine).
export CIBW_CONTAINER_ENGINE=podman

**Comment by Fox214** [comment]
Any ideas on this I got podman but its not working:

> Copying config 24991ae881 done  
Writing manifest to image destination
Storing signatures
ERRO[0008] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:54 for /run/lock/lockdev): Check /etc/subuid and /etc/subgid: lchown /run/lock/lockdev: invalid argument 
  ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:54 for /run/lock/lockdev): Check /etc/subuid and /etc/subgid: lchown /run/lock/lockdev: invalid argument
Error: Error committing the finished image: error adding layer with blob "sha256:3fe478aaff9b8f3ba958253e7339e9016ec07c075b805ebfc8cd372ddd01ee64": ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:54 for /run/lock/lockdev): Check /etc/subuid and /etc/subgid: lchown /run/lock/lockdev: invalid argument
Error: Command ['podman', 'create', '--env=CIBUILDWHEEL', '--name=cibuildwheel-d7abbf67-366f-4830-b99e-b3f45a23011f', '--interactive', '--volume=/:/host', 'quay.io/pypa/manylinux2014_ppc64le:2023-08-07-e3f636d', '/bin/bash'] failed with code 125. None

**Comment by marcelotduarte** [comment]
Check https://github.com/containers/podman/issues/12715

**Comment by Fox214** [comment]
Nothing in that thread is helping. I was able to rebuild sqlite and got it to work at least (not my preferred solution (if only because this affects other users and becomes a bit of the tail wagging the dog), but its a path)

**Comment by marcelotduarte** [comment]
I build new binary wheels for py310+ ppc64le.

You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

Please uninstall the previous version and test.

**Comment by Fox214** [comment]
Thank you so much, that is working for me!

I had to add a bunch of numpy stuff to the includes any idea as to why?

(specifically it was: 'numpy.testing', 'numpy.testing._private', 'numpy.testing._private.decorators', 'numpy.testing._private.extbuild', 'numpy.testing._private.nosetester', 'numpy.testing._private.utils')

**Comment by marcelotduarte** [comment]
You can try to use excludes=["numpy.testing"]
I'm working on optimizing some packages that include a lot of unnecessary stuff. NumPy is on my to-do list.

**Comment by marcelotduarte** [comment]
[Release 6.15.6](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.6) is out!

**Comment by marcelotduarte** [comment]
> I had to add a bunch of numpy stuff to the includes any idea as to why?

@Fox214 PR #2036 

You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by Fox214** [comment]
That is better, I still had to add numpy.testing to the includes though.

**Comment by marcelotduarte** [comment]
> 

To includes or to excludes?

**Comment by Fox214** [comment]
To includes.

I think it may be related to do including the skops module. 

I have quite a few things (about 500) in the excludes the majority are in numpy, scipy and sklearn. 

Several years ago in order to reduce the build time (and size of the output directory although that is less important to me) I added all those to exclude, I've just been tweaking it as needed over time. 

When I included skops recently I had to tweak the numpy stuff a bit. 
This is what I have set (relative to skops/numpy + a bit extra):
packages = [  'cassandra', 'idna', 'numpy', 'scipy', 'secrets', 'skops' ]
includes = [ 'elasticsearch', 'numpy.testing', 'numpy.testing._private', 'numpy.testing._private.decorators', 'numpy.testing._private.extbuild', 'numpy.testing._private.nosetester', 'numpy.testing._private.utils', 'py4j.java_collections', 'skops.io.old._general_v0', 'skops.io.old._numpy_v0' ]
excludes = ['numpy.libs',
'numpy.compat.setup',
'numpy.conftest',
'numpy.core.cversions',
'numpy.core.generate_numpy_api',
'numpy.core.setup',
'numpy.core.setup_common',
'numpy.core.tests.test_datetime',
'numpy.core.tests.test_deprecations',
'numpy.core.tests.test_function_base',
'numpy.core.tests.test_getlimits',
'numpy.core.tests.test_half',
'numpy.core.tests.test_longdouble',
'numpy.core.tests.test_multiarray',
'numpy.core.tests.test_numeric',
'numpy.core.tests.test_print',
'numpy.core.tests.test_regression',
'numpy.distutils',
'numpy.distutils.command.bdist_rpm',
'numpy.distutils.command.build_ext',
'numpy.distutils.command.config',
'numpy.distutils.command.develop',
'numpy.distutils.command.egg_info',
'numpy.distutils.command.install',
'numpy.distutils.command.sdist',
'numpy.distutils.core',
'numpy.distutils.cpuinfo', 
'numpy.distutils.exec_command',
'numpy.distutils.fcompiler.absoft',
'numpy.distutils.fcompiler.gnu',
'numpy.distutils.fcompiler.mips',
'numpy.distutils.fcompiler.pg',
'numpy.distutils.mingw32ccompiler',
'numpy.distutils.misc_util',
'numpy.distutils.msvc9compiler',
'numpy.distutils.msvccompiler',
'numpy.distutils.npy_pkg_config', 
'numpy.distutils.system_info', 
'numpy.distutils.tests.test_exec_command',
'numpy.distutils.tests.test_misc_util',
'numpy.distutils.tests.test_npy_pkg_config',
'numpy.distutils.tests.test_system_info',
'numpy.f2py',
'numpy.f2py.__main__',
'numpy.f2py.diagnose',
'numpy.f2py.f2py2e',
'numpy.f2py.setup',
'numpy.f2py.tests.test_array_from_pyobj',
'numpy.f2py.tests.test_assumed_shape',
'numpy.f2py.tests.test_block_docstring',
'numpy.f2py.tests.test_callback',
'numpy.f2py.tests.test_common',
'numpy.f2py.tests.test_kind',
'numpy.f2py.tests.test_mixed',
'numpy.f2py.tests.test_parameter',
'numpy.f2py.tests.test_regression',
'numpy.f2py.tests.test_return_character',
'numpy.f2py.tests.test_return_complex',
'numpy.f2py.tests.test_return_integer',
'numpy.f2py.tests.test_return_logical',
'numpy.f2py.tests.test_return_real',
'numpy.f2py.tests.test_size',
'numpy.f2py.tests.test_string',
'numpy.f2py.tests.util',
'numpy.fft.setup',
'numpy.fft.tests.test_fftpack',
'numpy.lib.recfunctions',
'numpy.lib.setup',
'numpy.lib.tests.test__datasource',
'numpy.lib.tests.test_arrayterator',
'numpy.lib.tests.test_format',
'numpy.lib.tests.test_function_base',
'numpy.lib.tests.test_recfunctions',
'numpy.lib.tests.test_regression',
'numpy.lib.tests.test_shape_base',
'numpy.lib.tests.test_utils',
'numpy.lib.user_array',
'numpy.linalg.setup',
'numpy.ma.setup',
'numpy.ma.tests.test_old_ma',
'numpy.matrixlib.setup',
'numpy.polynomial.setup',
'numpy.random.normal',
'numpy.random.seed',
'numpy.random.setup',
'numpy.setup',
'numpy.spacing',
'numpy.testing.nose_tools.noseclasses',
'numpy.testing.nose_tools.parameterized', 
'numpy.testing.noseclasses',
'numpy.testing.setup',
'numpy.testing.tests.test_doctesting',
'numpy.testing.tests.test_utils',
'numpy.tests.test_ctypeslib',
'numpy.tests.test_scripts',
'numpy.tests.test_warnings' ]

**Comment by marcelotduarte** [comment]
Basically what is excluded is [here](https://github.com/marcelotduarte/cx_Freeze/blob/main/cx_Freeze/hooks/numpy.py#L58).
It's interesting that numpy.testing is excluded by cx_Freeze (because I follow a recommendation from numpy) and you include it, but then exclude several submodules from it.
Another thing I see is that you also exclude 'numpy.distutils' and several submodules, as it is excluded in cx_Freeze, once the main 'numpy.distutils' is excluded, all submodules are excluded.

**Comment by Fox214** [comment]
Perhaps I will at some point blank out the lists and compare size/runtime and maybe retry to optimize from scratch, it was set the way it is many years and versions of python, cx freeze and numpy ago (and other modules) its only evolved 'as needed' since then. 

Would not completely surprise me if something that was once helpful has since because counterproductive due to the changes.

**Comment by marcelotduarte** [comment]
I changed the hook a bit, as I discovered that numpy.testing is used by Scipy. Internally numpy does use numpy.testing only to tests, but Scipy uses it to check some functionality.

[Release 6.15.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.8) is out!

**Comment by Fox214** [comment]
I have a question because I just realized something and its related to this:

I am (had been) manually using include_files = [ ('/path/to/sqlite.so','lib/libsqlite3.so.0') ] 

This was guaranteeing me a specific version of sqlite3 (3.33) rather than whatever one was randomly installed on the local host. 

With this version of python3.11 and cx_freeze, its putting a libsqlite3-f79e2a86.so.0.8.6 in there and ignoring that one. This happens to be 3.42.0 

I just manually move libsqlite3.so.0 to  libsqlite3-f79e2a86.so.0.8.6 it fails with the errors (as it appears my sqlite was not built with extentions) but ignoring that for a moment, because I am guessing it would work if I had a sqlite3 .so file built with the extensions, **what is the best way to make sure it picks up the sqlite I want it to?** 

I don't love the idea of doing a glob for a random name (libsqlite3-*.so*) to replace, although I suspect that would work. 

(FWIW, I am not having any other issues with 3.42, it just doesn't match what I was expecting and its not currently matching some other programs we would like it to match (sister products))

**Comment by marcelotduarte** [comment]
The module sqlite3 (sqlite3.py) depends on _sqlite3 (_sqlite3.cpython-310-x86_64-linux-gnu.so) that depends on  libsqlite3*.so.*
So, you should replace _sqlite3.* in lib-dynload directory with a compatible one with your libsqlite3 in lib.
Another user made a change like this for SSL and it worked.

**Comment by stsln** [comment]
When using cx_Freeze in Alt Linux W 10.1, I get the same error.

Two files have been created in the project:
main.py

`print('Hello, World!')`

setup.py

```
import sys
from cx_Freeze import setup, Executable

base = "Win32GUI" if sys.platform == "win32" else None

setup(
    name="guifoo",
    version="0.1",
    description="My GUI application!",
    executables=[Executable("main.py", base=base)])
```

`python setup.py build ` returns an error:

```
    raise OptionError(f"no base named {name!r} ({name_base!r})")
cx_Freeze.exception.OptionError: no base named 'console' ('console-cpython-39')
```

**Comment by marcelotduarte** [comment]
@stsln pip install --no-binary=cx_Freeze cx_Freeze

**Comment by stsln** [comment]
> @stsln pip install --no-binary=cx_Freeze, cx_Freeze

Thanks for the help, but first we need to update gcc better.

**Comment by marcelotduarte** [comment]
> Thanks for the help, but first we need to update gcc better.

Oh yes, I forgot to say that in Ubuntu we need:
`sudo apt install build-essential python3-dev python3-pip python3-venv python3-virtualenv python3-tk`

So it would help if you got the equivalent for your system.

**Comment by Fox214** [comment]
> I don't love the idea of doing a glob for a random name (libsqlite3-_.so_) to replace, although I suspect that would work.
```
sqlitedef = 'lib/libsqlite3.so.0'
freezeSqlite = glob.glob(f'{pyLib}/python*/site-packages/cx_Freeze/bases/lib/libsqlite3-*.so*')
if len(freezeSqlite):
    fname = freezeSqlite[0].split('/')[-1]
    sqlitedef = f'lib/{fname}'
include_files = [ (sqliteso,sqlitedef),...]
```

I finally got 3.33 rebuilt with the right extention symbols so I can use it I tried doing the above, it functions correctly, however because the file I am copying to is part of the cx_freeze install, it is getting overwritten by that afterwards so I still do not end up with the correct version. (I am just manually doing the same copy after I run build_ext step, and that works). 

I suspect if I rebuilt python (or perhaps just cx freeze) I could make it correct then, but that is still not ideal, as the version I am trying to match is not a part of that process and can update asynchronously. 

The upshot of cx freeze embedding sqlite this way is by default you will get a consistent version (which is good!) the downside is I've been working around that for years and am trying to match another version independently. I guess the request is it would be nice to have a way to specify which sqlite library to use, it could be as simple as changing when the include_files are copied, or maybe there is a better way. 

My currently solution works and is not onerous, it just feels kludgy.

**Comment by marcelotduarte** [comment]
cx_Freeze depends on python installed on machine (if using `pip install --no-binary=cx_Freeze cx_Freeze`) or the [manylinux](https://github.com/pypa/manylinux) python distributed in the wheel (if using `pip install cx_Freeze`).

> I suspect if I rebuilt python (or perhaps just cx freeze) I could make it correct then, but that is still not ideal, as the version I am trying to match is not a part of that process and can update asynchronously.

If you rebuild python you can set the libraries. I use manylinux because it uses an old version of linux (glibc) so the app can run in various linux versions and updates libraries like sqlite, openssl and tkinter, among others.
If you change a manylinx docker to generate your python (or rebuild local python) you should generate your cx_Freeze binaries using [this](https://cx-freeze.readthedocs.io/en/stable/development/index.html#building-redistributable-binary-wheels).

> The upshot of cx freeze embedding sqlite this way is by default you will get a consistent version (which is good!) 

This was the objective of generating binaries, as there were many issues due to the particularities of each Linux system (and also on macOS). Previously only for Windows there were binaries.

> the downside is I've been working around that for years and am trying to match another version independently. 

To get the old behavior you should uninstall cx_Freeze and install it using:
`pip install --no-binary=cx_Freeze cx_Freeze`

**Comment by Fox214** [comment]
I may try that next time I rebuild python, its all set for now (but never forever) I don't use system python I custom build a version that is portable (and I need to build the same thing for multiple arch) 
I may try to run experiment soon just to test if I think about it.
