### ISSUE TITLE
cx_Freeze executable when called from outside folder throws import error.

### ISSUE THREAD

**Issue by mai1x9** [marcelotduarte/cx_Freeze#2012]
**Prerequisite**
 - I guess there's no issue on this.

**Describe the bug**
After building using cx freeze, I have got the final executable with build folder. Now if I run the executable everything works fine. But if I run the executable from outside the build, like from other folder, calling the executable by giving fullpath it raises `ImportError` for the packages that were written by development team (not the third party packages which are inside lib, these packages are outside lib, in root directory).

Eg: Project structure,
```
contrib
src
utils
pkg
lib (generated by cx freeze_
app.exe
```
When run from other folder by giving full path of app.exe, it throws `ImportError pkg/or contrib etc..`

**To Reproduce**
Just take any random example with a custom package, then build using cz freeze, execute it from outside root folder by giving exact path.

**Expected behavior**
I have used cx frreze `6.14.7` and this error has raised. When using `cx_freeze < 6.x` version, i never found this issue.

**Screenshots**
From below screenshot if I give the path of executable by running from another directroy, it is throwing the error.
![Screenshot (195)](https://github.com/marcelotduarte/cx_Freeze/assets/43678329/2858d54b-2179-4af9-83c4-d730237afd5e)

**Desktop (please complete the following information):**
 - Platform information: Windows 10.
 - OS architecture (e.g. amd64):
 - cx_Freeze version : 6.14.7
 - Python version : 3.8.8

**Additional context**
- If i move the packages (like pkg, contrib as mentioned above ) from my root project folder to `lib` folder then the import error is fixed, but its raising import error in other areas.
- The cz freeze app will be installed in program files, so when windows shortcut is given , setting the StartIn directory or working directroy path of the project will fix the issue. ?
- I want to understand why the error is raising and how to fix without using working directory option.
- Why did it work for 5.x cx freeze version but not with `6.14.7`?

Any help/ suggestions would be great.

**Comment by marcelotduarte** [comment]
There are some changes between versions for security, but I don't know if is your case.
The frozen app is on the source?
Are you using setup.py? Can you paste it here?

**Comment by mai1x9** [comment]
Thanks @marcelotduarte for quick reply, I will share a sample code and explain clearly what's the issue so it may help you to give a better suggestion or reasoning. 

I will update it by tomorrow

**Comment by marcelotduarte** [comment]
Can I close this issue?

[Release 6.15.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.8) is out!

**Comment by mai1x9** [comment]
> Can I close this issue?
> 
> [Release 6.15.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.8) is out!

sure thanks for reaching out.

Anyways I will update the sample code to reproduce the issues just want to know why it is happening.

I will reopen whenever I update you with code.
thanks.
