### ISSUE TITLE
.dylib files are copied twice on Mac

### ISSUE THREAD

**Issue by daniilS** [marcelotduarte/cx_Freeze#2016]
**Describe the bug**
When using cx_Freeze on MacOS, dylibs from some modules are included twice: once in the original directory, and once in `/libs/`. This is especially noticeable with packages using e.g. numpy and scipy, which end up becoming very large. The frozen executable still seems to work if the dylib from `/libs/` is removed.

**To Reproduce**
```py
# ./example.py
import numpy as np

print(np.arange(4))
```
`cxfreeze example.py`

**Expected behavior**
The frozen application is much larger than expected: for example, the BLAS library from numpy appears both in `exe.macosx-10.9-universal2-3.11/lib/libopenblas64_.0.dylib` and `exe.macosx-10.9-universal2-3.11/lib/numpy/.dylibs/libopenblas64_.0.dylib`. If the copy in `/lib/` is removed, running `example` still works, but I'm unsure if it's entirely redundant or is still used under specific conditions.

**Desktop (please complete the following information):**
 - Platform information: macOS Monterey 12.4
 - OS architecture: x86_64
 - cx_Freeze version: 6.15.5
 - Python version: 3.11.3

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by daniilS** [comment]
That fixes the issue with libopenblas64_.0.dylib, thanks! However, I noticed three issues when testing with 6.16.0.dev7:
- The three other numpy .dylib files are still copied twice, and again only one version seems to be used: `libgfortran.5.dylib`, `libquadmath.0.dylib`, and `libgcc_s.1.1.dylib`.
- .dylib files are still copied twice for `scipy`, so it will probably require a similar patch. I'm not sure if any more modules are also affected, but would be happy to help with testing.
- Either this patch or some other change caused a regression in detecting dependencies. I noticed it with `scipy.optimize`, which depends on `numpy.testing`, but `numpy.testing` is no longer automatically included.

A minimal example showing all issues:
```python
# ./example.py
import scipy.optimize

print("Hello world!")
```
`cxfreeze example.py --silent && ./build/example`

<details>
<summary>Output</summary>

```
Traceback (most recent call last):
  File "/Users/dos23/Documents/cx_test/new/lib/python3.11/site-packages/cx_Freeze/initscripts/__startup__.py", line 124, in run
    module_init.run(name + "__main__")
  File "/Users/dos23/Documents/cx_test/new/lib/python3.11/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "example.py", line 1, in <module>
  File "/Users/dos23/Documents/cx_test/new/lib/python3.11/site-packages/scipy/optimize/__init__.py", line 410, in <module>
    from ._minimize import *
  File "/Users/dos23/Documents/cx_test/new/lib/python3.11/site-packages/scipy/optimize/_minimize.py", line 27, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "/Users/dos23/Documents/cx_test/new/lib/python3.11/site-packages/scipy/optimize/_trustregion_constr/__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "/Users/dos23/Documents/cx_test/new/lib/python3.11/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 5, in <module>
    from .._constraints import (
  File "/Users/dos23/Documents/cx_test/new/lib/python3.11/site-packages/scipy/optimize/_constraints.py", line 8, in <module>
    from numpy.testing import suppress_warnings
ModuleNotFoundError: No module named 'numpy.testing'
```
</details>

**Comment by marcelotduarte** [comment]
I updated the patch. Please, rerun the pip install to test:

`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by daniilS** [comment]
Thank you, that fixes issues 2 and 3 from my last comment! The only remaining problem is that `libgcc_s.1.1.dylib`, `libquadmath.0.dylib`, and `libgfortran.5.dylib` are still duplicated into `/libs/` from both numpy and scipy.

**Comment by marcelotduarte** [comment]
[Release 6.15.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.8) is out!

I'll continue to work to identify the remaining duplicates.
