### ISSUE TITLE
Unify tkinter hooks for Python 2 and 3

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#202]
Originally reported by: **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**

----------------------------------------

I noticed while helping someone on the mailing list that there are two completely separate hooks for freezing tkinter on Python 2 and 3:
https://bitbucket.org/anthony_tuininga/cx_freeze/src/adb1d5716a84478f3ee45c86316fb2060a8f9929/cx_Freeze/hooks.py?fileviewer=file-view-default#hooks.py-603

I don't think tkinter changed much for Python 3, and the Python 2 hook code does seem to work in Python 3. So it would be good for them to share code.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/202

**Comment by marcelotduarte** [comment]
PR #559 
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
