### ISSUE TITLE
Support for AppImage: bdist_appimage available

### ISSUE THREAD

**Issue by marcelotduarte** [marcelotduarte/cx_Freeze#2054]
A new bdist_appimage is available on Linux systems, to create an AppImage application.
It is a development version, please contribute with tests and impressions.

You can test the feature using the latest development build:
`pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

To run:
`python setup.py bdist_appimage`

Documentation is [here](https://cx-freeze--2050.org.readthedocs.build/en/2050/setup_script.html#bdist-appimage).

**Comment by jontis** [comment]
Worked like a charm. Many thanks :-D

**Comment by CanYing0913** [comment]
Works perfectly, thanks! Just wondering when version 6.17 will be on conda-forge? I noticed the latest version is just 6.15.

**Comment by marcelotduarte** [comment]
@CanYing0913 Current is 6.15.13.
bdist_appimage should be released in the next major release, perhaps in a month.

**Comment by marcelotduarte** [comment]
[Release 7.0.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.0.0) is out!
[Documentation](https://cx-freeze.readthedocs.io)
