### ISSUE TITLE
sqlite3.dll not shipped

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#207]
Originally reported by: **Johannes Eckstein (Bitbucket: [skidzo](https://bitbucket.org/skidzo), GitHub: [skidzo](https://github.com/skidzo))**

----------------------------------------

Hi all the last bug i solved after installing cx_Freeze on Python35 is worth to be mentioned I guess.

To get cx_Freeze working again:
https://github.com/sekrause/cx_Freeze-Wheels

The sqlite3.dll somehow gets lost...

Python35\DLLs\sqlite3.dll, this may be because the depending file is _sqlite3.pyd in the same Directory. Somehow this dependency does not get resolved.

This Problem affects various other packages as tkinter and so on.

Nevertheless I got my PyQT5.7 application running!

Good luck in the new Job and have fun!

Thanks a lot for this package!

Keep up the good work!

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/207

**Comment by anthony-tuininga** [comment]
*Original comment by* **Parry Cadwallader (Bitbucket: [wbc35](https://bitbucket.org/wbc35), GitHub: Unknown)**:

----------------------------------------

@skidzo did you have to do anything else after installing the wheel?  I upgraded to cx_freeze 5.0 and I'm still receiving the `_sqlite3` DLL not found issue.

**Comment by anthony-tuininga** [comment]
*Original comment by* **David Hobbs (Bitbucket: [hobbsd](https://bitbucket.org/hobbsd), GitHub: [hobbsd](https://github.com/hobbsd))**:

----------------------------------------

I had the same problem and got the sqlite3.dll included by adding it to the `include_files` under `build_exe` in the setup.py `options`. For example:

    options = {'build_exe': {'include_files': [os.path.join(sys.base_prefix, 'DLLs', 'sqlite3.dll']}}

**Comment by anthony-tuininga** [comment]
*Original comment by* **Harald Hanöfner (Bitbucket: [HarryH](https://bitbucket.org/HarryH), GitHub: [HarryH](https://github.com/HarryH))**:

----------------------------------------

Since the module sqlite3 belongs to the python standard library I would recommend to add a new hook within the cx_Freeze library.

Adding the following code snippet to the ```hooks.py``` works well for me:
```
#!python
def load_sqlite3(finder, module):
    """In Windows, the sqlite3 module requires an additional dll sqlite3.dll to
       be present in the build directory."""
    if sys.platform == "win32":
        dll_name = "sqlite3.dll"
        dll_path = os.path.join(sys.base_prefix, "DLLs", dll_name)
        finder.IncludeFiles(dll_path, dll_name)

```

**Comment by anthony-tuininga** [comment]
Hook has been added.

**Comment by kurt-rhee** [comment]
I have the same issue.  I am using cx_freeze 6.0 in an anaconda environment.
