### ISSUE TITLE
Exclude `python3.dll`

### ISSUE THREAD

**Issue by yasirroni** [marcelotduarte/cx_Freeze#2116]
My use case is to create a patch where user can copy paste old files with latest patch. In this use case, I'm using exhaustive exclude for faster creation, such as

```shell
cxfreeze -c GUI/GUI.py --target-dir dist --exclude-modules currency_converter,fastapi,jinja2,numpy,openpyxl,pandas,pydantic,scipy,sympy,xlrd,xlsxwriter,xlwings,asyncio,concurrent,ctypes,currency_converter,distutils,email,html,http,lib2to3,logging,multiprocessing,pydoc_data,pywin32_system32,tcl8,tcl8.6,test,tk8.6,tkinter,unittest,urllib,xml,xmlrpc
```

It can further optimized with excluding `python3.dll` and `python3.8.dll`. Later when I know that I upgrade dependency and or python, I can delete them from exclude list.

This make patch distribution smaller and faster creation.

**Comment by marcelotduarte** [comment]
I'm not sure, but it should work using the name or fullpath with [bin-excludes](https://cx-freeze.readthedocs.io/en/stable/script.html#cmdoption-bin-excludes).

**Comment by yasirroni** [comment]
> I'm not sure, but it should work using the name or fullpath with [bin-excludes](https://cx-freeze.readthedocs.io/en/stable/script.html#cmdoption-bin-excludes).

That is not possible, based on this example,

```python
import time

print("Hello World!")

time.sleep(5)
```

run using

```shell
cxfreeze -c cx_freeze/hello_world.py --target-dir cx_freeze/dist  --bin-excludes python3.dll
```
___
I've been tryting to find any related code inside this repository but can't find any relevant code yet, so I can't help to make a PR.

This message also appears, right after we run,

```text
creating directory ...\cx_freeze\dist
copying ...\Programs\Python\Python38\python3.dll -> ...\cx_freeze\dist\python3.dll
copying ...\Programs\Python\Python38\python38.dll -> ...\cx_freeze\dist\python38.dll
```

**Comment by marcelotduarte** [comment]
With PR #2624, a file like python3.dll will be copied only if required by some package (pytq5/6 for instance).
Furthermore, bin-excludes should exclude a file even if it is required (user choice should prevail, even if it causes problems).

**Comment by marcelotduarte** [comment]
[Release 7.2.4](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.4) is out!
[Documentation](https://cx-freeze.readthedocs.io)
