### ISSUE TITLE
DLL load failed while importing _core: The specified module could not be found.

### ISSUE THREAD

**Issue by MesterPerfect** [marcelotduarte/cx_Freeze#2136]
I'm encountering an issue when compiling my program using Python 3.10 and cx-Freeze 6.15.10 on Windows 10 Version 22H2 (OS Build 19045.3693). During compilation, I receive warnings similar to the following:

```
C:\Users\MesterPerfect\Desktop\st>python setup.py build
running build
running build_exe
WARNING: cannot find 'api-ms-win-crt-runtime-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-crt-stdio-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-crt-math-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-crt-locale-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-crt-heap-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-crt-string-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-crt-filesystem-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-crt-time-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-crt-environment-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-crt-convert-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-crt-utility-l1-1-0.dll'
creating directory C:\Users\MesterPerfect\Desktop\st\SoundTranscriber
copying C:\Program Files\Python310\vcruntime140.dll -> C:\Users\MesterPerfect\Desktop\st\SoundTranscriber\vcruntime140.dll
copying C:\Program Files\Python310\vcruntime140_1.dll -> C:\Users\MesterPerfect\Desktop\st\SoundTranscriber\vcruntime140_1.dll
WARNING: cannot find 'api-ms-win-core-localization-l1-2-0.dll'
WARNING: cannot find 'api-ms-win-core-registry-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-heap-l2-1-0.dll'
WARNING: cannot find 'api-ms-win-core-libraryloader-l1-2-0.dll'
WARNING: cannot find 'api-ms-win-eventing-provider-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-processthreads-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-synch-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-string-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-sysinfo-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-security-base-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-handle-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-errorhandling-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-heap-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-string-l2-1-0.dll'
WARNING: cannot find 'api-ms-win-core-synch-l1-2-0.dll'
WARNING: cannot find 'api-ms-win-core-processenvironment-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-file-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-debug-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-processthreads-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-memory-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-profile-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-memory-l1-1-3.dll'
WARNING: cannot find 'api-ms-win-core-privateprofile-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-atoms-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-heap-obsolete-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-string-obsolete-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-localization-obsolete-l1-2-0.dll'
WARNING: cannot find 'api-ms-win-core-stringansi-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-sidebyside-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-kernel32-private-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-kernel32-legacy-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-kernel32-legacy-l1-1-1.dll'
WARNING: cannot find 'api-ms-win-core-appinit-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-apiquery-l2-1-0.dll'
WARNING: cannot find 'api-ms-win-core-delayload-l1-1-1.dll'

WARNING: cannot find 'api-ms-win-core-delayload-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-core-apiquery-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-power-setting-l1-1-0.dll'
WARNING: cannot find 'api-ms-win-power-base-l1-1-0.dll'


```
Despite successful assembly, all users who install the software encounter the following error message:

```
Traceback (most recent call last):
  File "D:\tecwindow\SoundTranscriber\Lib\site-packages\cx_Freeze\initscripts\startup.py", line 130, in run
  File "D:\tecwindow\SoundTranscriber\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "SoundTranscriber.py", line 1, in <module>
  File "D:\tecwindow\SoundTranscriber\Lib\site-packages\wx\init.py", line 17, in <module>
  File "D:\tecwindow\SoundTranscriber\Lib\site-packages\wx\core.py", line 12, in <module>
ImportError: DLL load failed while importing _core: The specified module could not be found.

```

The program fails to function, and the issue persists until Microsoft Visual C++ 2015-2019 x86 and x64 are installed.

Here's the code I'm using:

```

# setup.py

import sys
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {
"build_exe": "SoundTranscriber",
"optimize": 1,
"include_files": ["data", "documentation"],
"packages": ["custom_ctrl", "general_classes", "general_functions" etc ],
"includes": ["wx", "pysrt", "docx", "accessible_output2",etc],
"zip_include_packages": ["wx"],
"excludes": ["tkinter", "test", "setuptools", "pip", "numpy"],
"include_msvcr": True
}

description="SoundTranscriber"

# GUI applications require a different base on Windows (the default is for a
# console application).
base= None
if sys.platform == "win32":
	base = "Win32GUI"
	setup(name="SoundTranscriber", version="1.1.2", description=description, options={"build_exe": build_exe_options}, executables=[Executable("main.py", base=base)])
```

Please provide assistance in resolving this issue. Thank you for your time.

**Comment by MesterPerfect** [comment]
![image_2023-11-19_17-42-19](https://github.com/marcelotduarte/cx_Freeze/assets/44323153/98155eae-bc3f-4778-a230-c6c38e9ec828)

**Comment by marcelotduarte** [comment]
I use a sample with matplotlib and wx [here](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/matplotlib) that works for me.
Are using the latest version of wxPython?

> The program fails to function, and the issue persists until Microsoft Visual C++ 2015-2019 x86 and x64 are installed.

Do you mean Microsoft Visual C++ Redistributable Package?
https://cx-freeze.readthedocs.io/en/stable/faq.html#microsoft-visual-c-redistributable-package

**Comment by MesterPerfect** [comment]
> I use a sample with matplotlib and wx [here](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/matplotlib) that works for me. Are using the latest version of wxPython?
> 
> > The program fails to function, and the issue persists until Microsoft Visual C++ 2015-2019 x86 and x64 are installed.
> 
> Do you mean Microsoft Visual C++ Redistributable Package? https://cx-freeze.readthedocs.io/en/stable/faq.html#microsoft-visual-c-redistributable-package

I have been using the latest stable version of cx_Freeze and wxPython. When I used cx_Freeze with matplotlib and the latest version of wxPython, the dependencies were included, and the program worked as far as my hardware was concerned.

However, I ran into another problem. My program is based on the yt_dlp library for downloading from YouTube. When I compile my program, the cx_Freeze library fails to include some dependencies, such as yt_dlp.compat._deprecated and yt_dlp.utils._deprecated. I need to manually include these frameworks in the "includes" section of my setup.py file.

The correct format for the "includes" section is:

```
"includes": ["wx", "pysrt", "yt_dlp", "yt_dlp.compat._deprecated", "yt_dlp.utils._deprecated"],
```

The incorrect format is:

```
"includes": ["wx", "pysrt", "yt_dlp"],
```

**Comment by marcelotduarte** [comment]
I'll make a hook for [yt_dlp](https://pypi.org/project/yt-dlp/).

**Comment by marcelotduarte** [comment]
You can test the PR #2145 within the latest development build:
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by MesterPerfect** [comment]
> You can test the PR #2145 within the latest development build: `pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze` For conda-forge the command is: `conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

The setup.py code was updated, and the error message no longer appears. Consequently, the library is included, and everything is now working fine.

**Comment by marcelotduarte** [comment]
It should work with empty includes.
Can I close this issue by merging the PR?

**Comment by MesterPerfect** [comment]
> It should work with empty includes.
> Can I close this issue by merging the PR?

Yes, you can, and thank you, for the quick response and solution to the problem.

**Comment by marcelotduarte** [comment]
[Release 6.15.11](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.11) is out!
