### ISSUE TITLE
Include package metadata and expose it through packaging tools

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#216]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](https://bitbucket.org/jaraco), GitHub: [jaraco](https://github.com/jaraco))**

----------------------------------------

In my involvement with [this ticket in the mock project](https://github.com/testing-cabal/mock/issues/385#issuecomment-263894161), it came to my attention that cx_freeze apparently excludes the package metadata (egg-info, dist-info, etc) when freezing. While some metadata may not be applicable in a frozen application, I can certainly see applications making use of introspection to [detect and report versions](https://github.com/yougov/pmxbot/blob/master/pmxbot/commands.py#L833-L839) or [expose functionality via plugins](https://github.com/jaraco/keyring/blob/10.1/keyring/backend.py#L142-L171).

I suggest that cx_freeze could (a) copy/include metadata exposed by the package and (b) provide a mechanism in pkg_resources to serve that metadata just as it does for other forms of installation.

By doing so, it would eliminate the incentive for packages to avoid use of this functionality in order to retain compatibility with cx_Freeze.

I unfortunately won't be able to contribute this feature, but I'll happily help guide someone willing to help contribute, especially with implementing the pkg_resources functionality.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/216

**Comment by nicoddemus** [comment]
Is there a mechanism in place to extend pkg_resources to serve that metadata?

**Comment by nicoddemus** [comment]
cc @jaraco

**Comment by jaraco** [comment]
I don't believe there's a plugin mechanism, but pkg_resources could itself be extended to support additional file types or structures in a file type (such as zip files), especially if such a format is well-specified, such as with a PEP or other consensus.

**Comment by henryborchers** [comment]
Any progress on this?

**Comment by jaraco** [comment]
A little more detail - `pkg_resources` defines an [IMetadataProvider](https://github.com/pypa/setuptools/blob/cfb0d71afd7d6cb026e35930b80b98e779f52c24/pkg_resources/__init__.py#L585), which defines the abstract interface for a provider of metadata.

The [NullProvider](https://github.com/pypa/setuptools/blob/cfb0d71afd7d6cb026e35930b80b98e779f52c24/pkg_resources/__init__.py#L1464) and [DefaultProvider](https://github.com/pypa/setuptools/blob/cfb0d71afd7d6cb026e35930b80b98e779f52c24/pkg_resources/__init__.py#L1589) are implementations that provide metadata based on files in the file system. The [ZipProvider](https://github.com/pypa/setuptools/blob/cfb0d71afd7d6cb026e35930b80b98e779f52c24/pkg_resources/__init__.py#L1683) is an implementation for resolving the metadata based on zip files (including eggs).

I'm not yet sure how these metadata providers are selected, but if there was a metadata provider that matched when the module's loader is one provided by cx_Freeze, I imagine that could be integrated to resolve metadata for cx_Freeze applications.

I'd start with [the docs](http://setuptools.readthedocs.io/en/latest/pkg_resources.html) and then focus on the pkg_resources code and try to follow the logic to implement a suitable provider for cx_Freeze.

**Comment by xavfaure** [comment]
Dear jaraco,
I'm trying to make a standalone application using cx-freeze. I use PyQt5 with mayavi, traitsui, tvtk and some other. I've encountered the pkg_resource pb  : qt4 xxx.toolkit not found while lauching the xe file....lauching the main.py works perfrectly in a prompt console. along your doc, I didn't manage to point out what shall I do to solve this issue. Would you mind give me some first setps ? thanks in advance :)

**Comment by jaraco** [comment]
Hi @xavfaure.

At this point, I'm considering pkg_resources soft-deprecated and I've been pushing users to instead rely on [entrypoints](https://pypi.org/project/entrypoints), [importlib_resources](https://pypi.org/project/importlib_resources), and [importlib_metadata](https://pypi.org/project/importlib_metadata). In fact, keyring (referenced above) already uses entrypoints to load its entrypoints. pmxbot will soon too.

Therefore, I recommend first that you work with the Qt and related packages to first see if they can update to the newer package metadata tools. Once they've done that, if the necessary metadata still isn't available in the cxFreeze environment, you'll want to submit a bug report (and ideally a pull request) to the relevant project (probably entrypoints) describing the deficiency and what you're trying to achieve.

**Comment by marcelotduarte** [comment]
PR #608 merged.
