### ISSUE TITLE
DLL load failed while importing _core from PyAV module

### ISSUE THREAD

**Issue by martinmiglio** [marcelotduarte/cx_Freeze#2164]
**Describe the bug**
When running build_exe on a project including the [PyAV module](https://pypi.org/project/av/), the executable errors:
```
> .\build\exe.win-amd64-3.11\av-lib-cx-freeze-repro.exe
Traceback (most recent call last):
  File "XXX\pypoetry\Cache\virtualenvs\av-lib-cx-freeze-repro-vnBVzzJ2-py3.11\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run      
    module_init.run(name + "__main__")
  File "XXX\pypoetry\Cache\virtualenvs\av-lib-cx-freeze-repro-vnBVzzJ2-py3.11\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
    exec(code, module_main.__dict__)
  File "src\main.py", line 1, in <module>
    import av
  File "XXX\pypoetry\Cache\virtualenvs\av-lib-cx-freeze-repro-vnBVzzJ2-py3.11\Lib\site-packages\av\__init__.py", line 32, in <module>
    from av._core import time_base, library_versions
ImportError: DLL load failed while importing _core: The specified module could not be found.
```

**To Reproduce**
Building, then executing the frozen executable of any code which imports the PyAV module will result in this error.
This repo is a minimal reproduction: https://github.com/martinmiglio/av-lib-cx-freeze-repro

**Expected behavior**
cx_freeze includes the necessary dependencies of PyAV when building an executable

**Desktop:**
 - Platform information: Windows 11 22631.2792
 - OS architecture: amd64
 - cx_Freeze version: 6.15.11
 - Python version: 3.11.6

**Comment by marcelotduarte** [comment]
Try to use `includes = ["av._core"]`
If it work, I'll make a hook. I think I'll have to include av.libs in the hook too, but do a test and let me know.
EDIT:
No includes needed. I made a hook.

**Comment by martinmiglio** [comment]
Thanks for including the hook! 💖

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build:
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Comment by martinmiglio** [comment]
doing the same with poetry:
```toml
[tool.poetry.group.build.dependencies]
cx-freeze = {version = "^6.16.0.dev12", source = "cx-freeze-devel"}

[[tool.poetry.source]]
name = "cx-freeze-devel"
url = "https://marcelotduarte.github.io/packages/"
priority = "explicit"
```

cx freeze's stated version after install:
```bash
> poetry run cxfreeze --version       
cxfreeze 6.16.0-dev12 Copyright (c) 2020-2023 Marcelo Duarte. All rights reserved. Copyright (c) 2007-2020 Anthony Tuininga. All rights reserved. Copyright (c) 2001-2006 Computronix Corporation. All rights reserved.
```

still yields the same error as first reported

could this issue be caused by this warning about missing dll's from cx-freeze:
```
WARNING: cannot find 'api-ms-win-core-*'
```

**Comment by marcelotduarte** [comment]
Add [include_msvcr](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cmdoption-arg-include_msvcr) to test.

**Comment by martinmiglio** [comment]
> Add [include_msvcr](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cmdoption-arg-include_msvcr) to test.

the following results in the same error:
```python
setup(
    name=PROJECT_NAME,
    executables=[
        Executable(
            script=ENTRY_POINT,
            target_name=f"{PROJECT_NAME}.exe",
        )
    ],
    options={
        "build_exe": {
            "include_msvcr": True,
        },
    },
)
```

**Comment by marcelotduarte** [comment]
I used to test:
 `cxfreeze main.py`
 `cxfreeze main.py --include-msvcr`
Both worked to me. The latest build is: 
[2164.zip](https://github.com/marcelotduarte/cx_Freeze/files/13693600/2164.zip)

As github does not upload 7z file, I renamed it to zip. Please open with 7zip.

**Comment by martinmiglio** [comment]
this is a headache, i am able to run the executable you linked, but cannot reproduce, even when using `cxfreeze main.py` instead of my setup script.

any steps i could take to debug this? i imagine it has to do with my build environment, but this is even caused in a windows-latest container in a github action (which is where my actual application is built)

**Comment by martinmiglio** [comment]
comparing the `lib` folder contents to your zip, when running `cxfreeze main.py`, there is no `pyav.libs` folder in my output. this seems like the issue.

**Comment by martinmiglio** [comment]
I have gotten it to work after installing [`pyav`](https://pypi.org/project/pyav/) instead of [`av`](https://pypi.org/project/av/) (not the same module).
pyav is a fork of av (also named pyav)

Can the hook be made to work with AV, not the fork?

**Comment by marcelotduarte** [comment]
I was going to ask you for a pip list (or equivalent). That could be it, I followed the link you gave me in the first comment.

**Comment by marcelotduarte** [comment]
ok, I adapted the hook to support both versions.
You can test using the [branch](https://github.com/marcelotduarte/cx_Freeze/pull/2165#issuecomment-1858311057).
The development version will be updated only tomorrow.

**Comment by martinmiglio** [comment]
the updated hook works with the av module now, thanks for working through this with me and adding the hook!

**Comment by marcelotduarte** [comment]
[Release 6.15.12](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.12) is out!
