### ISSUE TITLE
cx_freeze : ImportError: No module named moves.urllib

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#217]
Originally reported by: **YoanBouzin (Bitbucket: [YoanBOUZIN](https://bitbucket.org/YoanBOUZIN), GitHub: Unknown)**

----------------------------------------

After many error, I have this one :

```
#!python

Traceback (most recent call last):
File
"C:\Python27\lib\site-packages\cs_Freeze\initscripts\__startup__.py",
line 2, in <module>
__import__(name + "__init__")
File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py",
line 21, in <module>
scriptModule = __import__(moduleName)
File "Launcher.py" , line 54, in <module>
File "C:\Python27\lib\site-packages\packaging\requirements.py", line12, in <module>
from six.moves.urllib import parse as urlparse
ImportError: No module named moves.urllib
```

I have a problem with this impot error, I think the problem are with six.

I posted also the issue in stackoverflow.

http://stackoverflow.com/questions/41211334/cx-freeze-importerror-no-module-named-moves-urllib

You can see all the code in this post too.

I provide the two files, the setup.py file and the file with the imports

Thanks in advance for your help.

Regards,

Yoan

Ps: I don't know what priority to select so, I use the default "major"

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/217

**Comment by raginisharma14** [comment]
Is this issue resolved? If yes, could you please let me know, what is the solution

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
