### ISSUE TITLE
Absolute pathes adding for build at docker container & crash application after installation at others machines

### ISSUE THREAD

**Issue by valeriigamaley** [marcelotduarte/cx_Freeze#2177]
I build MSI distro through cx_Freeze 6.15.12 in docker container pyton3.8-windowsservercore, but when i get the complete installer &  install at other machine I have errors with application trying to use absolute path from container but not the relative path for utility. 

**Steps To Reproduce**
**My setup file**:

```
from cx_Freeze import setup, Executable

executables = [
    Executable(script = 'cimbioz.py',
               base = 'Win32GUI',
               icon = ".\installer\cimbioz.ico",)
]

packages = ['wheel', 'setuptools', 'certifi', 'future', 'six', 'urllib3', 'requests', 'regpath',
            'openpyxl', 'tornado', 'lxml', 'psutil', 'dateutil', 'docx'']

excludes = ['tcl8', 'pip', 'tkinter']

include_files = [
            (".\chromium", ".\chromium"),
            (".\converter\web_gui\www", ".\converter\web_gui\www"),
            (".\converter\www\static", ".\converter\www\static"),
            ]

shortcut_table = [
    (
     "DesktopShortcut",         
     "DesktopFolder",          
     "CIMбиоз",                 
     "TARGETDIR",               
     "[TARGETDIR]cimbioz.exe", 
     "--dev",                  
     "CIMбиоз - тонкий клиент", 
     None,                      
     "CIMbiozIcon",             
     None,                      
     None,                      
     'TARGETDIR',              
    )
]

icon_table = [
    ("CIMbiozIcon",             
     ".\installer\cimbioz.ico"  
    )
]

msi_data = { "Shortcut": shortcut_table, 
             "Icon": icon_table,       
           }

options = {
    'build_exe': {
        'include_msvcr': False,
        'packages': packages,
        'include_files': include_files,
        'excludes': excludes,
        'optimize': 2,
    },
    'bdist_msi': {
        'data': msi_data,
        'install_icon': ".\installer\cimbioz.ico",
        'upgrade_code': "{29c62e07-d875-4af7-9cd6-cca5ea1c716e}",
    }
}

setup(name = 'CIMбиоз',
      version = '2.0.1',
      description = 'CIMбиоз',
      executables = executables,
      options = options)
```

**Expected behavior**
After installation i get this error which contains a full absolute path from container to files:

```
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\tornado\web.py", line 1784, in _execute
  File "C:\Users\ContainerAdministrator\CIMbioz\converter\web_gui\api\index_handler.py", line 8, in get
  File "C:\Python\lib\site-packages\tornado\web.py", line 940, in render
  File "C:\Python\lib\site-packages\tornado\web.py", line 1086, in render_string
  File "C:\Python\lib\site-packages\tornado\template.py", line 446, in load
  File "C:\Python\lib\site-packages\tornado\template.py", line 476, in _create_template
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ContainerAdministrator\\CIMbioz\\converter\\web_gui\\api\\../www/index.html'
```
Application try to get some wrong pathes when i installed it on another machines and use path from container.

**Screenshots**
Traceback get an error at this block of code. PyInstaller not get some errors but i need MSI through cx_Freeze.
![image](https://github.com/marcelotduarte/cx_Freeze/assets/90517013/89600a87-408b-4243-bbd1-a6c7528cbffb)
What should I do to fix that bad patterns?

**Desktop:**
 - Platform information: Docker Windows, image python38-windowsservercore
 - OS architecture: amd64
 - cx_Freeze version: 6.15.11
 - Python version: 3.8.10

**Comment by marcelotduarte** [comment]
> After installation i get this error which contains a full absolute path from container to files:

This information is for debug. This can be changed with [replace_paths](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cmdoption-arg-replace_paths).

To locate your data files, check this [link](https://cx-freeze.readthedocs.io/en/stable/faq.html#using-data-files).

**Comment by valeriigamaley** [comment]
> This information is for debug. This can be changed with [replace_paths](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cmdoption-arg-replace_paths).

How I need change pathes at my example, could you explain at more details, because I don't understand how to do it right?

> To locate your data files, check this [link](https://cx-freeze.readthedocs.io/en/stable/faq.html#using-data-files).

And same question here: what I need to do with this example and where I should use this code block to indicate pathes for my data files?

**Comment by marcelotduarte** [comment]
Use of replace_paths: https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/replace
Samples using data files:
https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/opencv
https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/tkinter
https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pillow

**Comment by valeriigamaley** [comment]
> Use of replace_paths: https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/replace Samples using data files: https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/opencv https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/tkinter https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pillow

very grateful for these examples) i get a decision for my problem, thx)
