### ISSUE TITLE
ImportError: No module named 'phonenumbers.data.region_US'

### ISSUE THREAD

**Issue by sumersao** [marcelotduarte/cx_Freeze#2179]
**Describe the bug**
I'm using the [phonenumberslite](https://pypi.org/project/phonenumbers/ ) python package in my code. Binarizing it yields the following error:

`ModuleNotFoundError: No module named 'phonenumbers.data.region_US'`

This is because (I think) in the docs it says it dynamically imports metadata for the regions that are being used (see below).

<img width="828" alt="Screenshot 2023-12-20 at 2 47 56 PM" src="https://github.com/marcelotduarte/cx_Freeze/assets/47700511/91598c8d-d9fb-444e-87fe-90c2b5d2323e">

**Expected behavior**
When I include "phonenumbers.data.region_US" in my setup.py that works, but it fails on a different region. I just want there to be a way to include all of these subregions without manually importing them (I'm supporting international phone numbers). When I try 
```
"includes": [
        "phonenumbers.data.*"
    ],
```
it doesn't like the glob pattern. What's the best way to handle this?

**Desktop (please complete the following information):**
 - Platform information: MacOS 14
 - OS architecture (e.g. amd64): Arm
 - cx_Freeze version: 6.16.0.dev11
 - Python version [e.g. 3.10]: 3.10

**Additional context**
My project has been successfully using cx_freeze before this, so I know it's just an issue with this library.

**Comment by marcelotduarte** [comment]
A hook can be made to this, but basically, you can use [packages](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cmdoption-arg-packages):
 `"packages": ["phonenumbers"]`

**Comment by sumersao** [comment]
Wow it worked. Tysm for the fast reply!!
