### ISSUE TITLE
exe file created with cx_freeze from a customtkinter app opens the console upon loading despite setup configuratuion

### ISSUE THREAD

**Issue by zinando** [marcelotduarte/cx_Freeze#2190]
I was using cx_freeze to package an app i created using customtkinter/tkinter libraries. Despite setting the base as "Win32GUI", the executable generated still opens the console upon loading. Here is my setup.py:
```
import sys
from cx_Freeze import setup, Executable

base = None

if sys.platform == 'win32':
    base = 'Win32GUI'

options = {
    'build_exe': {
        'include_files': ['assets', 'appclasses', 'helpers', 'static', 'main.py', 'app_settings.json'],  # Add any additional files or data needed here
    },
}

executables = [
    Executable('welcome.py', base=base, icon='assets/icons/app_icon.ico', target_name='Pikanto.exe'),  # Replace 'your_main_script.py' with your main script
]

setup(
    name='Pikanto',
    version='1.0',
    description='A logistics weight management console.',
    options=options,
    executables=executables
)

```
My pc is running on windows 11pro

**Comment by marcelotduarte** [comment]
I don't see any error in your setup. What I can recommend is for you to test directly, setting base=None and base="Win32GUI" to see if they behave differently.
And also use the latest version of setuptools and cx_Freeze 6.15.12 for such tests.

EDIT: You can also test using the [tkinter](https://github.com/marcelotduarte/cx_Freeze/tree/main615x/samples/tkinter) sample I use for testing.

**Comment by marcelotduarte** [comment]
Can I close issue?

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
