### ISSUE TITLE
api-ms-*.dll are copied regardless of `include_msvcr` value

### ISSUE THREAD

**Issue by bicobus** [marcelotduarte/cx_Freeze#2192]
Might be related to #367. Asked bout this behavior in discussion #2171.

I run a build workflow on github, as I do not own a microsoft machine. During the build, various api-ms-*.dll are copied from the PATH. I feel that this behavior is unwarranted.

Specific to the build:

* My [setup.py](https://github.com/BannerlordCE/pyCEStoriesEditor/blob/2f416a502c17de36822befa98a079b2a8952f98c/setup.py).
* The [build workflow](https://github.com/BannerlordCE/pyCEStoriesEditor/blob/2f416a502c17de36822befa98a079b2a8952f98c/.github/workflows/build.yml)
* Last [job](https://github.com/BannerlordCE/pyCEStoriesEditor/actions/runs/7430262647/job/20219746239) (please look at the *build* section)

Version of cx_Freeze: 6.15.12

It may yet be user error, in which case I apologize.

**Comment by marcelotduarte** [comment]
I can confirm this issue. With VS 2022 and PowerShell, there are new API-ms DLLs to exclude. I'll make a patch.

**Comment by marcelotduarte** [comment]
Can you test the patch with the latest development build?
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
With poetry use the following URL:
https://marcelotduarte.github.io/packages/cx-freeze/cx_Freeze-6.16.0.dev13-cp311-cp311-win_amd64.whl

**Comment by bicobus** [comment]
Thanks for the resolution. I don't own any machine running Windows, so it's somewhat difficult for me to test on demand. I mostly use github's actions to build and publish for windows.

Though, wouldn't it be a good idea to have dummy builds setup on this repository for this express purpose?  Isn't it already the case?

**Comment by marcelotduarte** [comment]
We have tests running in GHA that do this, and I also use several samples to run tests in another repository. But it is not always possible to cover all cases, so feedback is important. I'm going to release a .13 version soon, so when you have a build, if you can give me feedback.

**Comment by marcelotduarte** [comment]
[Release 6.15.13](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.15.13) is out!

**Comment by bicobus** [comment]
I ran the workflow and the api-* files were properly ignored, which ended up failing the workflow because `rm` failed to remove non-existent files. So it failed successfully, I guess  :tada: 

However, cx-Freeze still complains about not finding some api-ms-* files. Shouldn't those warning be silent? They're thrown as warning, but those dll not being present is the intended behavior.

**Comment by marcelotduarte** [comment]
For now, [silent_level](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cmdoption-arg-silent_level) = 3 is used to quiet these warnings. To be able to mute depending on the include_msvcr option, I will need to refactor a few things.
