### ISSUE TITLE
bdist_appimage application seems to have read-only files

### ISSUE THREAD

**Issue by CanYing0913** [marcelotduarte/cx_Freeze#2232]
**Prerequisite**
- [x] Make sure no duplicated issue has already been reported. You should look for closed issues, too.
- [x] Make sure you are not asking us to help to solve your specific issue. GitHub issues are opened mainly for development purposes. If you want to ask someone to help to solve your problem, go to some community site like StackOverflow, etc.
- [x] Make sure your problem is not derived from packaging (e.g. Homebrew).

**Describe the bug**
My application will need a folder named as "cache" for image display purposes. In my `setup.py`, I added it so the folder is also included during packaging:
```python3
import sys
from cx_Freeze import setup, Executable

build_exe_options = {
    "excludes": ['PyQt5'],
    'packages': ['ipyparallel', 'skimage', 'seaborn'],
    'include_files': ['config.ini', 'cache'],
    'silent_level': '1'
}

base = "Win32GUI" if sys.platform == "win32" else None

executables = [
    Executable(
        'main_GUI.py',
        base=base,
        target_name='test'
    )
]

setup(
    name="test",
    version="0.1",
    description="Test on build for incomplete GUI application",
    options={
        "build_exe": build_exe_options,
        "bdist_msi": {},
        "bdist_dmg": {},
        "bdist_appimage": {},
    },
    executables=executables,
)
```
However, when I try to run the resulting AppImage, the following error message occurs:
```bash
$./test.AppImage
2024-01-29 20:39:45.963723: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/cz/lib/python3.11/site-packages/cx_Freeze/initscripts/__startup__.py", line 132, in run
  File "/usr/share/miniconda/envs/cz/lib/python3.11/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
  File "main_GUI.py", line 414, in <module>
  File "main_GUI.py", line 406, in main
  File "/home/runner/work/CaImAn/CaImAn/src/src_pipeline.py", line 178, in __init__
  File "/usr/share/miniconda/envs/cz/lib/python3.11/pathlib.py", line 1116, in mkdir
OSError: [Errno 30] Read-only file system: '/tmp/.mount_CalciuWLDPTV/lib/cache'
```
Are there any further steps in `setup.py` I need to take to get rid of permission issues? Thank you.

**To Reproduce**
The AppImage can be found [here](https://github.com/CanYing0913/CaImAn/blob/1298e5a86701af75ce8430cd95d8ac107cd48ae5/CalciumZero-0.1-x86_64.AppImage).

**Expected behavior**
There should be without permission issue.

**Desktop (please complete the following information):**
 - WSL2, Ubuntu Linux 22.04
 - amd64
 - cx_Freeze version from https://marcelotduarte.github.io/packages/conda
 - Python version: 3.11

**Comment by marcelotduarte** [comment]
Please read the documentation of [AppImage](https://docs.appimage.org/).
[Overview](https://docs.appimage.org/reference/architecture.html?highlight=read+only#overview).
[Running AppImages](https://docs.appimage.org/user-guide/run-appimages.html#running-appimages)
[Extract the contents of an AppImage](https://docs.appimage.org/user-guide/run-appimages.html#extract-the-contents-of-an-appimage)

Perhaps you can use the [Portable mode](https://docs.appimage.org/user-guide/portable-mode.html).

**Comment by marcelotduarte** [comment]
[Release 7.2.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.0) is out!
[Documentation](https://cx-freeze.readthedocs.io)
[Updated documetation about AppImage](https://cx-freeze.readthedocs.io/en/stable/bdist_appimage.html)
