### ISSUE TITLE
ImportError 'packaging.version'

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#226]
Originally reported by: **Anonymous**

----------------------------------------

I am trying to freeze a python script that uses "netmiko", "paramiko" modules. The freeze finish successfully but when trying to run the program I am getting this error:  

ImportError: The 'packaging.version' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

I am using python 3.5.2 on windows 7.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/226

**Comment by johndlawlor** [comment]
Just wondering is there a solution to this? I getting the same error using, 
cx_freeze-5.0.01-py3.4-win-amd64

**Comment by MolotovCherry** [comment]
Still not solved? It's really annoying

Edit, solved with
`packages = ['appdirs', 'pkg_resources._vendor'],`

**Comment by marcelotduarte** [comment]
I think that PR #481 (in cx-freeze 6.1) and now the updated #584 solve this issue (in the master).
@cherryleafroad Can you confirm?

**Comment by marcelotduarte** [comment]
PR merged.
