### ISSUE TITLE
cx_freeze interaction with cryptography module

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#227]
Originally reported by: **Anonymous**

----------------------------------------

Hi,

I have a problem to freeze python script that use "cryptography" module, the error I get is:

"ValueError: Multibackend cannot be initialized with no backends. If you are seeing this error when trying to use default_backend() please try uninstalling and reinstalling cryptography. Failed to execute script"

cx_freeze version 5.0.1
cryptography 1.5.1 (also tried 1.7.1)
python 3.5.2
windows 7

I found this patch but it also doesn't work:

def patch_crypto_be_discovery():

    """
    Monkey patches cryptography's backend detection.
    Objective: support pyinstaller freezing.
    """

    from cryptography.hazmat import backends

    try:
        from cryptography.hazmat.backends.commoncrypto.backend import backend as be_cc
    except ImportError:
        be_cc = None

    try:
        from cryptography.hazmat.backends.openssl.backend import backend as be_ossl
    except ImportError:
        be_ossl = None

    backends._available_backends_list = [
        be for be in (be_cc, be_ossl) if be is not None
    ]

please help.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/227

**Comment by anthony-tuininga** [comment]
*Original comment by* **Jake Omann (Bitbucket: [jhomann](https://bitbucket.org/jhomann), GitHub: Unknown)**:

----------------------------------------

Hello,

I am using the cryptography module also - the weird thing that I find is when I freeze my code I get the following:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
  File "/usr/local/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 24, in <module>
  File "ncpa.py", line 18, in <module>
  File "/root/ncpa/agent/listener/certificate.py", line 2, in <module>
  File "/usr/local/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/usr/local/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
  File "/usr/local/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
  File "/usr/local/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
  File "ExtensionLoader_cryptography_hazmat_bindings__openssl.py", line 22, in <module>
  File "ExtensionLoader_cryptography_hazmat_bindings__openssl.py", line 14, in __bootstrap__
  File "/usr/local/lib/python3.5/imp.py", line 342, in load_dynamic
ImportError: /usr/local/ncpa/lib/python3.5/_cffi_backend.cpython-35m-x86_64-linux-gnu.so: object file has no loadable segments
```

Now the interesting part is that the version of CFFI > 1.5.2 breaks the functionality of cryptography/cffi loading libraries properly. I don't know that much about all the ways libraries are loaded and whatnot but it seems that the issue is that something isn't being included.

Either way, for the time being while I am working on the issue - I've forced the install do the pip install for **cffi==1.5.2** and you can do the same, since I believe that cryptography only needs 1.3 and above or something like that.

My example of how my includes are laid out do produce all the files I would expect to be available so I am assuming that the fact that it cannot find backends is an issue with the freezing process OR cffi/cryptography not playing nice in frozen environments. Possibly both, not sure.

**Comment by lovetox** [comment]
@anthony-tuininga 

hm maybe im missing something here but your import seems wrong

i use this on windows and with cx_freeze and i have no problems

`from cryptography.hazmat.backends.openssl import backend`

**Comment by lovetox** [comment]
@anthony-tuininga 

ah i think im getting it now, you try to use default_backend() in your script?

yeah that never worked for me on windows with cx_freeze, i just import the specific backend i need.

so at least the monkey patch should work with the corrected import line above

**Comment by lovetox** [comment]
Ah sorry didnt see that these are imported issues

nevertheless i tested this

Python 3.5.3
cx_freeze 5.0.1
cryptography 1.7.1
cffi 1.9.1
Windows 7

### setup.py
```python
from cx_Freeze import setup, Executable

build_exe_options = {"packages": ['os', 'cffi', 'idna']}


setup(name="test",
      version="0.1",
      description="My GUI application!",
      options={"build_exe": build_exe_options},
      executables=[Executable("test.py", base=None)])
```

### test.py


```python
from cryptography.hazmat.backends import default_backend
a = default_backend()

print('WORKS')
```

using default_backend() works without problems, no tracebacks.

so i think this can be closed

**Comment by anthony-tuininga** [comment]
Ok. Thanks for following up.
