### ISSUE TITLE
WIN rerror

### ISSUE THREAD

**Issue by Valdemir-DSW** [marcelotduarte/cx_Freeze#2283]
Its compiler is very good, fast and is not recognized as something malicious on the computer like others! But there is a problem if I build on Windows 10 and someone else on Windows 11 tries to use it and it doesn't work (I interface with Tk and customtkinter)              
![image](https://github.com/marcelotduarte/cx_Freeze/assets/134114016/59ffc74b-ceb1-4835-ace7-35914e70c810)

**Comment by marcelotduarte** [comment]
Can you make a simple test that I can reproduce the error?

**Comment by Valdemir-DSW** [comment]
> Can you make a simple test that I can reproduce the error?

pelo jeito você é do brasil, e um software que deixo no meu site  https://sites.google.com/view/dsw-wheel/baixar?authuser=0         

o en questão que eu recebi a print foi o DSW o primeiro da lista mas tem o DSW button box  e o DSW joystick e DSW lite  , eu utilizo o script de configuração setup.py  
[setup.txt](https://github.com/marcelotduarte/cx_Freeze/files/14487939/setup.txt)
estou mandando em TXT por que o github não quis deixar enviar .py              
[teste.txt](https://github.com/marcelotduarte/cx_Freeze/files/14487954/teste.txt)
pode tentar compilar esse teste que eu tenho que era algo que eu estava projetando no passado

**Comment by Valdemir-DSW** [comment]
algo engraçado foi que apareceu como um erro no meu pc mas isso foi em outro pc , nao entendi o porque

**Comment by marcelotduarte** [comment]
blz? E o 'requirements.txt'?

**Comment by Valdemir-DSW** [comment]
requirements.txt 
?

**Comment by marcelotduarte** [comment]
Descobri os outros pacotes necessários: pygame pyserial 

Fiz 2 testes: usando base=None e base=Win32GUI
Como não tenho volante, o programa abriu, nos 2 casos.
No mode base=None, rodando no cmd, pode ver que dá alguns erros, então sugiro, vc usar assim para depurar, pq aparentemente não é um problema com o cx_Freeze.

**Comment by marcelotduarte** [comment]
Can I close the issue?

**Comment by marcelotduarte** [comment]
Closing the issue due to lack of response. If necessary, please reopen or leave a comment.

**Comment by marcelotduarte** [comment]
[Release 7.0.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.0.0) is out!
[Documentation](https://cx-freeze.readthedocs.io)
