### ISSUE TITLE
mako.Template.render hangs in frozen cherrypy application

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#229]
Originally reported by: **Anders Nylund (Bitbucket: [motozz](https://bitbucket.org/motozz), GitHub: Unknown)**

----------------------------------------

This snippet hangs when calling t.render() in the index function (when accessing localhost:8080), t.render() works fine when called before starting the cherrypy app. 

```
#!python

from mako.template import Template
import cherrypy

t=Template('test')
print t.render()

class App:
    @cherrypy.expose
    def index(self):
        print 'render:'
        out = t.render()
        print out
        return out

cherrypy.quickstart(App(), '/')
```

Frozen with:

```
#!python

from cx_Freeze import setup, Executable

__version__ = '1.0'

options = {
    'build_exe': {
        'packages': ['pygments'],
    }
}

executables = [
    Executable('cherry.py'),
]

setup(name='test',
      version = __version__,
      options=options,
      executables=executables
      )
```

There are no errors, it just hangs. And it works without freezing... I have successfully frozen an app like this before with older versions of python, mako, cherrypy and cx_freeze, but now I can't reproduce that success (didn't save the version numbers of the working combination)

Environment:
```
#!
Python 2.7.13
CherryPy (8.8.0)
cx-Freeze (5.0.1)
Mako (1.0.6)
Pygments (2.1.3)
setuptools (20.10.1)

Windows 10
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/229

**Comment by motoz** [comment]
I can't reproduce this any more with cx_freeze version 5.1.1
Seems to be fixed!
