### ISSUE TITLE
multiprocessing.Manager().dict creation fails in 5.x (hangs process), but is successful for 4.3.4 (Python 2.7)

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#231]
Originally reported by: **Anonymous**

----------------------------------------

Hello,

I have the below code which I've frozen with Python 2.7 64-bit, and with the 5.x version of cx_Freeze the main process will freeze when the dict is created. However, with 4.3.4, the dict is created and the main process gets all the way to the raw_input() statement without any issues.

```
#!python

if __name__.endswith("__main__"):
    import multiprocessing
    multiprocessing.freeze_support()
    mgr = multiprocessing.Manager()
    var = [1] * 10000000 #main process will use more memory (easier to find in device mgr)
    print "before creating dict"
    mgr_dict = mgr.dict(
        {
            'test': 1
        }
    )

    print "after creating dict"
    raw_input("...")
```

I notice that after it hangs, if I go to Device Manager and kill the subprocess, it outputs this stack trace which seems to indicate on which line it is hanging (it always outputs the same line, which seems to support this):

```
#!python
before creating dict
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 21, in <module>
    scriptModule = __import__(moduleName)
  File "t.py", line 9, in <module>
  File "C:\Python27\lib\multiprocessing\managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "C:\Python27\lib\multiprocessing\managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "C:\Python27\lib\multiprocessing\connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "C:\Python27\lib\multiprocessing\connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
EOFError

```

As you can also see, the file path is also indicating that it is using the python in the C: drive. Is this a bug or a feature of cx_Freeze? I notice issue [214](https://bitbucket.org/anthony_tuininga/cx_freeze/issues/214/cx_freeze-keeps-looking-in-python-libs-not), but I don't have the same symptoms (process.pyc is still lowercase in my folder).

Also, if it is important, here is the setup.py script I'm using:

```
#!python

from cx_Freeze import setup, Executable

executables = [
    Executable('t.py')
]

setup(name='t',
      version='0.1',
      description='Sample cx_Freeze script',
      executables=executables
      )
```

Let me know if I'm missing anything obvious. Thank you.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/231

**Comment by henfri** [comment]
Hello,

I am experiencing the same Problem (including https://bitbucket.org/anthony_tuininga/cx_freeze/issues/214/cx_freeze-keeps-looking-in-python-libs-not)

Is there any known Workaround?

Regards,
Hendrik

**Comment by marcelotduarte** [comment]
See PR #622

**Comment by marcelotduarte** [comment]
Can you test the PR? (only if you have a C compiler)

pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/622/head
