### ISSUE TITLE
Flag to prevent library.zip creation

### ISSUE THREAD

**Issue by Mx772** [marcelotduarte/cx_Freeze#2313]
**Prerequisite**

**Describe the ~~bug~~ Feature**
I see in the past it was possible to generate directory that didn't include library.zip such as this gist:
https://gist.github.com/CountChu/c07cff7c1db062b24463a60a35eebe1e using `create_shared_zip=false`.

But on the latest version, I can't seem to reproduce this via any method of configuration. 

I thought one of these might do it:
```
"zip_exclude_packages": ["*"],
"no_compress": True,
```

**To Reproduce**
Steps to reproduce the behavior (a setup.py or a minimal code sample will be good)
Any setup.py to my knowledge

**Expected behavior**

A way to prevent library.zip from generating. (Possibly having the files be external to the zip,etc)

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Win11
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: cxfreeze 6.15.16
 - Python version [e.g. 3.10]: Python 3.10.11

**Additional context**

While uploading to some third-party sites, they prevent nested zips (One such being nexusMods).

As a result, this fails. Unpacking/moving the files causes failures, so I'd love if there was a way to flag to just have them unzipped and referenced loosely. 

If there is some flag/config I'm missing please let me know!

**Comment by marcelotduarte** [comment]
> I see in the past it was possible to generate directory that didn't include library.zip such as this gist:
> https://gist.github.com/CountChu/c07cff7c1db062b24463a60a35eebe1e using `create_shared_zip=false`.

I had never seen this option.

> I thought one of these might do it:
> 
> ```
> "zip_exclude_packages": ["*"],
> "no_compress": True,
> ```

It is possible to implement an option like this, it will be useful when using bdist_appimage too, because I don't see the need for a zip inside the AppImage which is also a zip.

**Comment by marcelotduarte** [comment]
@Mx772 I just implemented a new option zip_filename that works along with no_compress.
Use:
"no_compress": True,
"zip_filename": None,

You can test the patch in the latest development build (cx_Freeze 7.1.0.dev13):
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

Please test and give feedback.

**Comment by marcelotduarte** [comment]
[Documentation](https://cx-freeze--2379.org.readthedocs.build/en/2379/setup_script.html#cmdoption-arg-zip_filename)

**Comment by marcelotduarte** [comment]
[Release 7.1.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.1.0) is out!
[Documentation](https://cx-freeze.readthedocs.io)
