### ISSUE TITLE
cx_Freeze.exception.OptionError: no base named 'console' ('console-cpython-311-darwin')

### ISSUE THREAD

**Issue by abhinavbandaru** [marcelotduarte/cx_Freeze#2329]
**Error**
When trying to run setup function of cx_freeze (snippet attached later), facing the following issue
```
Traceback (most recent call last):
   File "/Volumes/build/mts/release/sb-73133480/bora/install/vcsa-installer/vcsaCliInstaller/setup.py", line 130, in <module>
     Executable(script='main.py',
   File "/Volumes/build/mts/release/sb-73133480/bora/install/vcsa-installer/vcsaCliInstaller/deps/cx_freeze/cx_Freeze/executable.py", line 43, in __init__
     self.base = base
     ^^^^^^^^^
   File "/Volumes/build/mts/release/sb-73133480/bora/install/vcsa-installer/vcsaCliInstaller/deps/cx_freeze/cx_Freeze/executable.py", line 77, in base
     raise OptionError(f"no base named {name!r} ({name_base!r})")
cx_Freeze.exception.OptionError: no base named 'console' ('console-cpython-311-darwin')
```

**To Reproduce**
I installed cx_freeze-6.15.16 tar from [pypi](https://files.pythonhosted.org/packages/aa/f2/acda72a8d7d36f97c9ed968f340060c46c22b1ae8393e975eeca524f0ec0/cx_Freeze-6.15.16.tar.gz) and then unpacked it to create a universal mac whl in the following way (the commands are run from inside the unpacked tar):

```
export CFLAGS =-arch x86_64 -arch arm64 -I/${PYTHON_PATH}
export ARCHFLAGS=-arch x86_64 -arch arm64
export MACOSX_DEPLOYMENT_TARGET=12.6
${PYTHON_PATH} setup.py bdist_wheel
```
And then run the setup function of cx_freeze. Attaching snippet below.
Snippet of setup.py: 
```
from cx_Freeze import setup, Executable

buildOptions = dict(
    zip_include_packages=["*"],
    zip_exclude_packages=[],
    optimize=2,
    excludes=excludes,
    includes=includes,
    include_files=INCLUDE_FILES,
    packages=packages,
    path=sys.path)

executables = [
    Executable(script='main.py',
               target_name=utils.platform.get_bin_file_name(product))
]

setup(name='install',
      version='6.15',
      description="<redacted>",
      options=dict(build_exe=buildOptions),
      executables=executables,
      data_files=data_files)
```

**Desktop:**
 - Platform information: Macosx Monterey
 - OS architecture: x86_64
 - cx_Freeze version: 6.15.16
 - Python version: 3.11.4

Please lmk if additional information is required.

**Comment by marcelotduarte** [comment]
Please read https://cx-freeze.readthedocs.io/en/stable/development/index.html#building-redistributable-binary-wheels

In your case, use: 
pip install --upgrade cibuildwheel
cibuildwheel --only cp311-macosx_universal2

**Comment by marcelotduarte** [comment]
Can I close the issue?

**Comment by abhinavbandaru** [comment]
My apologies, I couldn't revert back. I'll need a day more to confirm this.

**Comment by abhinavbandaru** [comment]
Reopening this issue because I notice that `python -m build` also can be used according to the docs: https://cx-freeze.readthedocs.io/en/stable/development/index.html#building-redistributable-binary-wheels 

Command used: `python -m build --wheel --outdir <outdir>'

I was able to generate the universal wheel `cx_Freeze-6.15.16-cp311-cp311-macosx_12_0_universal2.whl` and this wheel ran into the same error as above
```
Traceback (most recent call last):
   File "/Volumes/build/mts/release/sb-73133480/bora/install/vcsa-installer/vcsaCliInstaller/setup.py", line 130, in <module>
     Executable(script='main.py',
   File "/Volumes/build/mts/release/sb-73133480/bora/install/vcsa-installer/vcsaCliInstaller/deps/cx_freeze/cx_Freeze/executable.py", line 43, in __init__
     self.base = base
     ^^^^^^^^^
   File "/Volumes/build/mts/release/sb-73133480/bora/install/vcsa-installer/vcsaCliInstaller/deps/cx_freeze/cx_Freeze/executable.py", line 77, in base
     raise OptionError(f"no base named {name!r} ({name_base!r})")
cx_Freeze.exception.OptionError: no base named 'console' ('console-cpython-311-darwin')
```
The env variables are the same as above
```
export CFLAGS =-arch x86_64 -arch arm64 -I/${PYTHON_PATH}
export ARCHFLAGS=-arch x86_64 -arch arm64
export MACOSX_DEPLOYMENT_TARGET=12.6
```

**Comment by marcelotduarte** [comment]
> Reopening this issue because I notice that `python -m build` also can be used according to the docs: https://cx-freeze.readthedocs.io/en/stable/development/index.html#building-redistributable-binary-wheels

No!

A wheel like that is therefore an intermediate stage to producing a binary that can be distributed. That final binary may be a wheel - in that case, run auditwheel (Linux) or delocate (macOS) to vendor the required shared libraries into the wheel.

To reach this, cx_Freeze’s binary wheels is built using [cibuildwheel](https://pypi.org/project/cibuildwheel).

**Comment by marcelotduarte** [comment]
In the next release, we will have again universal2 wheels for Python 3.11 and 3.12.

You can test the patch in the latest development build (cx_Freeze 7.1.0.dev13) as soon as it's available tomorrow:
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

If you don't automatically download universal2 with pip, download the wheel at https://marcelotduarte.github.io/packages/cx-freeze/

**Comment by marcelotduarte** [comment]
[Release 7.1.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.1.0) is out!
[Documentation](https://cx-freeze.readthedocs.io)

**Comment by abhinavbandaru** [comment]
Thank you so much!
