### ISSUE TITLE
cx_Freeze - ImportError: No module named 'scipy.spatial.ckdtree'

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#233]
Originally reported by: **Anonymous**

----------------------------------------

exe was build .but,not working error will come

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/233

**Comment by nickvandewiele** [comment]
Is there a way to _temporarily_ sidestep this error, while a more permanent solution is in the works? E.g. can I manually copy files into a location?

**Comment by nickvandewiele** [comment]
Nevermind, simply copying `scipy/spatial/ckdtree.py` into the frozen subfolder did the trick.

**Comment by kai06046** [comment]
I compare the scipy included files under exe build path with my python path, found that there is a file name conflict between `cKDTree.cp35-win_amd64.pyd` in exe build path and `ckdtree.cp35-win_amd64.pyd` in my python path. Renaming and then exe can run.

**Comment by arjd** [comment]
This is also an issue for me, and it's preventing me from deploying an msi. Is there a way to target the dist folder instead to create an msi?

**Comment by arjd** [comment]
Think I found the problem. cx_Freeze looks like it's duplicating this module, the first time with the wrong name; and when it tries to write the second time I suppose the first .pyd won't get overwritten. Yay for Windows not being case-sensitive!!!!

From the modules list from cx_Freeze.finder:
```
<Module name='scipy.spatial.cKDTree', file='omitting my python path.....\\lib\\site-packages\\scipy\\spatial\\cKDTree.cp36-win32.pyd'>
<Module name='scipy.spatial.ckdtree', file='omitting my python path.....\\lib\\site-packages\\scipy\\spatial\\ckdtree.cp36-win32.pyd'>
```

There is no cKDTree module. It's only ckdtree. I'm not even sure how it got the capitalized .pyd file cause it doesn't even exist. I did check the module itself just to be thorough and there isn't even a class named cKDTree, only KDTree. The module docstrings do suggest there might be some cKDTree cxx file somewhere but I think those are kept and maintained by the scipy team only as I can't find anything like that.

I wrote a really hanky 5 line workaround to get this thing to work but I'm really not pleased with this solution. My guess is that the root cause is somewhere in the finder.py module with all the hanky _Import helper subfunctions. Not sure why the choice was made to recurse that way but w/e.

**Comment by danaukes** [comment]
this might be a conflict between the cKDTree class and the ckdtree module and how it gets imported in other packages.  I see it's used in astropy and sklearn packages as well as from within scipy in several places.

if you don't need ckdtree, then in lib/site-packages/scipy/spatial/__init__.py, comment out line 94:
`from ckdtree import *`

**Comment by 7kbird** [comment]
I found a simple workaround on windows:

add 'scipy.spatial.cKDTree' to `excludes` in `build_exe` options

then the `cKDTree.*.pyd` will not be copied but the `ckdtree.*.pyd` is kept in the `lib\scipy\spatial` of the build folder

**Comment by anthony-tuininga** [comment]
Is this still relevant for the latest code on the v5.x and master branches? Its possible another bug fix may have corrected this already.

**Comment by danaukes** [comment]
Last time i updated it still was an issue, but that was 6 months ago. Next
time I build my app I'll let you know.

**Comment by ghost** [comment]
I just encountered this problem using the 5.1.1 release.  I followed @7kbird 's advice about excluding 'scipy.spatial.cKDTree' and that work in my situation.

**Comment by Overdrivr** [comment]
I can confirm it too. Workaround from @7kbird works, please note if you're not paying attention like me that the typo is important. `scipy.spatial.cKDTree` works, `scipy.spatial.ckdtree` doesn't.

**Comment by yucongo** [comment]
Workaround from @7kbird didnt work in my case. I had to rename cKDTree.cp36-win_amd64.pyd to ckdtree.pyd in the relevant build directory (lib\scipy\spatial).

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by bryantChhun** [comment]
Sadly, I struggled with exactly this problem today, And then @7kbird 's post works to solve it.

Using version 6.1 on windows 10

**Comment by mpetitjean** [comment]
I just came across the same issue today using cx_Freeze 6.1 under Windows 10, and the workaround of @7kbird did the trick.

I suppose we should re-open the issue ?

**Comment by marcelotduarte** [comment]
I'll make a PR for the next release.

**Comment by marcelotduarte** [comment]
Can you test the PR? (only if you have a C compiler)

`pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/626/head`

**Comment by marinaPauw** [comment]
Please note, this issue still exists. I find the same issue with none of the workarounds working for me.

**Comment by marcelotduarte** [comment]
@marinaPauw, was your test with cx-freeze 6.1 or current master?
To test with the current master (only if you have a C compiler):
`pip uninstall -y cx_Freeze`
`pip install git+https://github.com/anthony-tuininga/cx_Freeze.git@master`

**Comment by marinaPauw** [comment]
I was using the latest version available via pip install --upgrade, but it seems the issue had indeed been resolved. I was stuck so long with it I uninstalled python and all the packages and re-installed only the ones I needed for this project and now it seems to work! Despite my having previously reinstalled scipy itself. So probably one of the packages was installed incorrectly or there was a version mismatch somewhere. Either way, I no longer get this error, thanks for your rapid response!

**Comment by double0darbo** [comment]
I was getting a similar issue on scipy.ndimage:

```
File "<dir>\Anaconda3\envs\clone37\lib\site-packages\scipy\ndimage\__init__.py", line 151, in <module>
    from .filters import *
  File "<dir>\Anaconda3\envs\clone37\lib\site-packages\scipy\ndimage\filters.py", line 36, in <module>
    from . import _ni_support
ImportError: cannot import name '_ni_support' from 'scipy.ndimage' (<dir>\Anaconda3\envs\clone37\build\exe.win-amd64-3.7\lib\scipy\ndimage\__init__.pyc)
```
I needed to remove the build files copied over, and then it worked. 

However, I am still getting an issue with running the .exe on its own. Inside the command line, it works fine. Once I try clicking on the .exe, it freezes and dies.
