### ISSUE TITLE
My app tries to create files in library.zip

### ISSUE THREAD

**Issue by arun-gautham** [marcelotduarte/cx_Freeze#2331]
My app create 2 files on startup unfortunately, since the pyc are in library.zip it fails.

And the installer, creator always puts all the pyc files in zip even though i specify not to

  "zip_exclude_packages":["*"]

**Comment by marcelotduarte** [comment]
https://cx-freeze.readthedocs.io/en/stable/faq.html#using-data-files

**Comment by marcelotduarte** [comment]
Can I close the issue?
