### ISSUE TITLE
Can you help?

### ISSUE THREAD

**Issue by RileyDevGithub** [marcelotduarte/cx_Freeze#2335]
I made a program, but while trying to back up the src, I accidentally deleted it. All I have is the build which you can find on my Github: [Here](https://github.com/RileyDevGithub/Odyssey-Engine) Thank you if possible! I have none of the src; in the meantime I will try to recover myself, but I will let you know.

**Comment by RileyDevGithub** [comment]
Update: I can't recover the src.

**Comment by marcelotduarte** [comment]
Maybe this can help you, but I've never tested it: https://github.com/EurosTeam/cxFreezextractor
I will close the issue because it is outside the scope of the project.
