### ISSUE TITLE
Redirect the SourceForge site to github.io

### ISSUE THREAD

**Issue by sekrause** [marcelotduarte/cx_Freeze#234]
Now that cx_Freeze has a new home at https://anthony-tuininga.github.io/cx_Freeze/ it's probably a good idea to finally get rid of http://cx-freeze.sourceforge.net/ because SourceForge sites often make a project look somewhat stale.

Fortunately SourceForge seems to officially support HTTP redirects for project websites: https://sourceforge.net/p/forge/documentation/Project%20Web%20Services/#re-directing-to-another-site

So it should be possible to keep the SourceForge project for the mailing list etc, but to redirect all users coming from Google to the new site. Eventuall Google should point to the new site, too.

**Comment by anthony-tuininga** [comment]
Thanks. Redirect put in place.

**Comment by sekrause** [comment]
The PHP direct from SourceForge's documentation didn't work? That one would be immediate for the user and the search engines would be more likely to update their index to the new location. Probably the best would be a permanent redirect with an `index.php` like this:

```php
<?php
header("HTTP/1.1 301 Moved Permanently");
header("Location: https://anthony-tuininga.github.io/cx_Freeze/");
exit;
?>
```

**Comment by anthony-tuininga** [comment]
Thanks. I didn't try the PHP one but I just tried the one you gave me and it works fine. Thanks for the help!
