### ISSUE TITLE
UnboundLocalError: cannot access local variable 'exclude_names' where it is not associated with a value

### ISSUE THREAD

**Issue by gbtami** [marcelotduarte/cx_Freeze#2362]
Follow up to https://github.com/marcelotduarte/cx_Freeze/issues/2356
After the new MSYS2 cx-Freeze package arrived we triggered a new build for pychess bdist_msi 
https://github.com/pychess/pychess/actions/runs/8837952115/job/24269587548
![](https://i.imgur.com/6Dc33n7.png)

**Comment by marcelotduarte** [comment]
https://github.com/marcelotduarte/cx_Freeze/pull/2363#issuecomment-2079740445

**Comment by gbtami** [comment]
Seems it produces the same error with 7.0.0-3
https://github.com/pychess/pychess/actions/runs/8855111639/job/24329191820

**Comment by marcelotduarte** [comment]
I'm sorry, I didn't patch msys2 correctly. But I'm also working on tests for the msys2 version, so it avoids these errors. I ended up discovering other errors with this #2367.
I'm waiting for the pytest-datafiles package to become available and then I'll send a new patch.

**Comment by hartwork** [comment]
> I'm sorry, I didn't patch msys2 correctly. But I'm also working on tests for the msys2 version, so it avoids these errors. I ended up discovering other errors with this #2367.

@marcelotduarte thanks for your help!

> I'm waiting for the pytest-datafiles package to become available and then I'll send a new patch.

For anyone else wondering how or when pytest-datafiles will be available:
- it's in the queue at https://packages.msys2.org/queue as package `mingw-w64-python-pytest-datafiles` with status "Ready for upload but waiting for dependencies"
- I'm not sure what could be missing in terms of dependencies, package `PKGBUILD` is at https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python-pytest-datafiles/PKGBUILD if you want to check for yourself.

**Comment by marcelotduarte** [comment]
https://github.com/msys2/MINGW-packages/pull/20760 merged.

**Comment by hartwork** [comment]
@marcelotduarte thank you!

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build (7.1.0.dev9):
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`
For msys2, download the file at: https://marcelotduarte.github.io/packages/msys2/ and use it w/ `pacman -U`
