### ISSUE TITLE
Allow storing all Python packages in a subdirectory on Windows

### ISSUE THREAD

**Issue by sekrause** [marcelotduarte/cx_Freeze#237]
On Unix systems all the Python packages are nicely stored in a subdirectory like `python3.5` while on Windows they're just in the same directory as the executable. This leads to many `*.pyd` files polluting the installation directory and it's getting even worse with the new `zipExcludePackages` option where Python packages are put directly next to the executable as subdirectories and might even conflict with already existing subdirectories (e.g. for resource files).

It would be nice if all Python packages (`*.pyd` and those excluded from the ZIP) would end up in a new subdirectory so that we only have `python35.dll`, `python35.zip` and the new `python35` directory next to the executables.

I've already implemented this change at https://github.com/sekrause/cx_Freeze/commit/6047ed1d82e765ce2c216051e3bccd898a74225a and it's only 10 lines of code changed. So far I've found no problems even if modules require additional DLLs.

What do you think? It might even be a good default option in the future...

**Comment by eeyrjmr** [comment]
This was possible with cx_freeze-4.3.x but something has changed with 5.0.  Quite a few things have changed from 4.x to 5.x and I havn't figured out what are bugs and what are intended direction

What I used todo  was:

`# -*- coding: utf-8 -*-

from cx_Freeze import setup, Executable
import sys
import site
import os

site_dir = site.getsitepackages()[1]
# Process the includes, excludes and packages first

#include_files = ['icons']
include_files = []
includes = []
excludes = ['wx','pydoc_data','curses']
packages = []

sys.path.append(os.path.join(os.path.dirname(__file__), '.', 'bin'))



EXE1 = Executable(
    # what to build
    script = "NVM.py",
    initScript = None,
    base = 'Win32GUI',
    targetDir = "NVM",
    targetName = "NVM.exe",
    compress = True,
    copyDependentFiles = True,
    appendScriptToExe = True,
    appendScriptToLibrary = False,
    icon = 'hardware_chip.ico'
    )


setup(

    version = "0.0.1",
    description = " NVM",
    author = "JRB",
    name = "NVM",

    options = {"build_exe": {"includes": includes,
                             "excludes": excludes,
                             "packages": packages,
                             'include_files':include_files,
                             "path": sys.path,

                            'append_script_to_exe':False,
                            'build_exe':"_NVM/bin",
                            'compressed':True,
                            'copy_dependent_files':True,
                            'create_shared_zip':True,
                            'include_in_shared_zip':True,
                            'optimize':2,
                             }
               },

    executables = [EXE1]
    )


`

And then within the application in question add at the start:

`import os
import sys

if getattr(sys,'frozen',False):
    # if trap for frozen script wrapping
    sys.path.append(os.path.join(os.path.dirname(sys.executable),'bin'))
    sys.path.append(os.path.join(os.path.dirname(sys.executable),'bin\\library.zip'))
    os.environ['TCL_LIBRARY'] = os.path.join(os.path.dirname(sys.executable),'bin\\tcl')
    os.environ['TK_LIBRARY'] = os.path.join(os.path.dirname(sys.executable),'bin\\tk')
    os.environ['MATPLOTLIBDATA'] = os.path.join(os.path.dirname(sys.executable),'bin\\mpl-data')

`
This no longer works as there was a change in how cx_freeze executes the script (no longer appended to the exe)

**Comment by sekrause** [comment]
Thanks for the info. I switched from py2exe to cx_Freeze 5.0 because of Python 3.5 support, so unfortunately I never got to use cx_Freeze 4.3.

If I see it correctly cx_Freeze always launches `Console.py` at the beginning for executables, so `sys.path` needs to be extended there because in the application's main it would be too late. Unfortunately that needs a change in cx_Freeze itself and is nothing I could do in my application.

**Comment by anthony-tuininga** [comment]
I will take a look at why Windows works differently regarding the placement of extension modules. Thanks for posting your code.

@eeyrjmr If you have questions about what was changed, let me know. The removal of the ability to append the zip file to the executable was deliberate. The current approach makes use of the builtin ability of Python to load a zip file. This greatly simplified the code and removed a lot of potential bugs at the same time. Having a portion of the Python standard library shipped with cx_Freeze meant that you could get conflicts with your own installation of Python -- unless it was identical -- and 5.0 eliminated that possibility. Hope that explains things!

**Comment by eeyrjmr** [comment]
@anthony-tuininga no criticism with regards to the removal & I saw the specific commit and the reasoning (I couldn't re-find it to post).

I mention it because there are a number of changes and I am trying to figure out what are intentional (and thus I need to adapt my setup.py) or what are due to bugs. eg with v5.x an entire py module directory is copied (temp files and all) rather than the pyd/py files... just trying to figure out if this is a byproduct of improving things or an unexpected side effect 

With v4.x I used the above setup and header to enable a subdirectory for the exact same reasons (keeps the root clean). I didn't know this was windows specific.

**Comment by sekrause** [comment]
@eeyrjmr The copying of the whole package directory is because of the new zip_exclude_packages option (http://cx-freeze.readthedocs.io/en/latest/distutils.html) and intended behavior:

> list of packages which should be excluded from the zip file and placed in the file system instead; the default is for all packages to be placed in the file system since a number of packages assume that is where they are found and will fail when placed in a zip file; use * to specify that all packages should be placed in the file system and excluded from the zip file (the default)

It's a very useful option because for example the `requests` package can't include its certificate store in the ZIP file and then won't trust any SSL connections. Though I personally think it's not a good default to exclude *all* packages from the ZIP by default. My preference is to put all packages into the ZIP and only exclude those which need non-py files in their package.

**Comment by eeyrjmr** [comment]
@sekrause that was why I was holding off raising an issue.  At present I am using py34+cx+freeze4x for frozen application, but I am messing around with py36 & thus cx-5.0.1

what you mention w.r.t. the content of a directory makes sense & thus my build script can easily be adapted to deal with that. 

There are other changes with regards to cx-5 that I am trying to figure out if they are bugs or a change. You have highlighted a difference between windows and other platforms with regards to the modules residing in the subdirectory. I mitigated this with cx-4.x as described above so no I am just figuring out if I was abusing a "bug" or the inability to do this is due to other cx-5 changes and thus just wait for your enhancement to be accepted

**Comment by anthony-tuininga** [comment]
The current code in the master branch (which will become cx_Freeze 6.x) now places all files in a subdirectory called "lib" on all platforms and creates a zip file called "lib/library.zip" on all platforms. I believe this resolves your issue. If you can test and confirm, that would be appreciated!

**Comment by sekrause** [comment]
I like this change. I just tested it with Python 3.5 on Windows and so far there seem to be no problems.

**Comment by eeyrjmr** [comment]
Interesting, I have held off migrating to py36 due to this but this sounds good.
I'll make a note that py36+cx6 should be trialed once it is updated

**Comment by azuring2** [comment]
Will cx_Freeze 6.x support python 2.7 still?
Much of our code still needs python 2.7 library and cannot transport to 3.5 . We hope cx_Freeze can support 2.7. For example ,there are too many pyds and dlls(more than 70) in the root directories of our application, we hope the new pyd-packing feature can be applied to cx_Freeze version for python 2.7.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
