### ISSUE TITLE
Pyside6 missing base translation file

### ISSUE THREAD

**Issue by brzGatsu** [marcelotduarte/cx_Freeze#2374]
PySide 6.7
cx_Freeze 7.0

When freezing a PySide6 app, the qt base translation files are missing. They contain translations i.e. for shortcuts and default buttons. They are typically loaded by using the QTranslator (https://doc.qt.io/qt-6/qtranslator.html).

Source folder: Lib/site-packages/PySide6/translations/qtbase_\<LANGUAGE\>.qm

**Comment by marcelotduarte** [comment]
You can test the patch in the latest development build (wait for cx_Freeze 7.1.0.dev19):
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

**Comment by marcelotduarte** [comment]
[Release 7.1.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.1.0) is out!
[Documentation](https://cx-freeze.readthedocs.io)
