### ISSUE TITLE
App is displayed in non-retina resolution

### ISSUE THREAD

**Issue by adius** [marcelotduarte/cx_Freeze#239]
When I start the app with `python3 myapp.py` it's displayed with retina resolution.
When I build it with cx_Freeze it's pixelized.

<img width="301" alt="screen shot 2017-01-27 at 19 09 12" src="https://cloud.githubusercontent.com/assets/969983/22384045/79045492-e4c4-11e6-88eb-f2ab5696f51f.png">

Left: not-retina, right: retina

The app uses only https://docs.python.org/2/library/tkinter.html.
Is there a way to fix this?

**Comment by David-Luis** [comment]
I have the same issue with pyqt5, low resolution when built with cx_Freeze :(

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7b1 has just been released.
pip install cx-Freeze==6.7b1

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
