### ISSUE TITLE
Reducing the Size of PyTorch-Based Executable

### ISSUE THREAD

**Issue by hwy1992129** [marcelotduarte/cx_Freeze#2412]
Hi,

I'm working on converting a Python program that uses PyTorch to an executable file. However, the folder for the app is too large. I've noticed that the original torch2.3+cu118 in conda is around 5GB, and the torch library in the app is about 4GB.

I'm wondering how to use torch while keeping the executable file small. Specifically, how do others create standalone binary executables that are only 200-300 MB in size?

Any advice or suggestions would be greatly appreciated. Thank you!

**Comment by MJT369** [comment]
If you try to make it setup files with innostup or zeep your exe you will see size of file 3 time smaller...

**Comment by marcelotduarte** [comment]
Please read https://github.com/marcelotduarte/cx_Freeze/pull/2587#issue-2544403027

To get the wheels to install cx_Freeze:
py310: https://github.com/marcelotduarte/cx_Freeze/actions/runs/11007824656/artifacts/1969844338
py39: https://github.com/marcelotduarte/cx_Freeze/actions/runs/11007824656/artifacts/1969844223
Can you test the fix?

**Comment by marcelotduarte** [comment]
> I'm wondering how to use torch while keeping the executable file small. Specifically, how do others create standalone binary executables that are only 200-300 MB in size?

The possibility I see is using torch+cpu and compressing the binary. For example, on Linux this is possible using [bdist_appimage](https://cx-freeze.readthedocs.io/en/stable/bdist_appimage.html), on Windows, using [bdist_msi](https://cx-freeze.readthedocs.io/en/stable/bdist_msi.html) it should be reduced as well.

**Comment by MJT369** [comment]
in directory  \build\exe.win-amd64-3.12\lib\torch\lib cx_Freez must delete OrCAD Capture files it will be fix size of freeze script.Maybe possible using this method delete unwanted files for other library as nltk for reduce size of script Regards 
    On Tuesday, September 24, 2024 at 09:56:30 AM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 



I'm wondering how to use torch while keeping the executable file small. Specifically, how do others create standalone binary executables that are only 200-300 MB in size?


The possibility I see is using torch+cpu and compressing the binary. For example, on Linux this is possible using bdist_appimage, on Windows, using bdist_msi it should be reduced as well.

**Comment by MJT369** [comment]
I have no linux to test wheel sorry 😐
    On Tuesday, September 24, 2024 at 09:42:47 AM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 


Please read #2587 (comment)

To get the wheels to install cx_Freeze:
py310: https://github.com/marcelotduarte/cx_Freeze/actions/runs/11007824656/artifacts/1969844338
py39: https://github.com/marcelotduarte/cx_Freeze/actions/runs/11007824656/artifacts/1969844223
Can you test the fix?

**Comment by marcelotduarte** [comment]
@MJT369 To test Py312 windows: https://github.com/marcelotduarte/cx_Freeze/actions/runs/11007824656/artifacts/1969844790

**Comment by MJT369** [comment]
AppData\Local\Programs\Python\Python312\Scripts>pip install C:\Users\Sabir\Downloads\cx-freeze-pip-windows-latest-3.12\cx_Freeze-7.2.2-cp312-cp312-win_amd64.whlProcessing c:\users\sabir\downloads\cx-freeze-pip-windows-latest-3.12\cx_freeze-7.2.2-cp312-cp312-win_amd64.whlRequirement already satisfied: packaging>=24 in c:\users\sabir\appdata\local\programs\python\python312\lib\site-packages (from cx-Freeze==7.2.2) (24.1)Requirement already satisfied: setuptools<76,>=65.6.3 in c:\users\sabir\appdata\local\programs\python\python312\lib\site-packages (from cx-Freeze==7.2.2) (75.1.0)Requirement already satisfied: cx-Logging>=3.1 in c:\users\sabir\appdata\local\programs\python\python312\lib\site-packages (from cx-Freeze==7.2.2) (3.2.0)Requirement already satisfied: lief<0.16.0,>=0.12.0 in c:\users\sabir\appdata\local\programs\python\python312\lib\site-packages (from cx-Freeze==7.2.2) (0.15.1)cx-Freeze is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel
    On Wednesday, September 25, 2024 at 08:05:00 AM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 


@MJT369 To test Py312 windows: https://github.com/marcelotduarte/cx_Freeze/actions/runs/11007824656/artifacts/1969844790

**Comment by marcelotduarte** [comment]
Please uninstall it then install:
pip uninstall cx_Freeze

**Comment by MJT369** [comment]
Installed and New problems with numpy is importing error numpy from it's source directory...
    On Wednesday, September 25, 2024 at 09:14:21 AM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 


Please uninstall it then install:
pip uninstall cx_Freeze

**Comment by MJT369** [comment]
Pyqt5 not working for me with cx_Freeze 7.2.2My python is 12 
    On Wednesday, September 25, 2024 at 09:14:21 AM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 


Please uninstall it then install:
pip uninstall cx_Freeze

**Comment by marcelotduarte** [comment]
@MJT369 Can you show me the error with numpy and pyqt5?
I used the samples [pandas](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pandas) and [pyqt5](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/pyqt5) to test.
I'll redo the tests later.

**Comment by MJT369** [comment]
I re installed python 12 pyqt5 problems fixed 
    On Wednesday, September 25, 2024 at 07:52:37 PM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 


@MJT369 Can you show me the error with numpy and pyqt5?
I used the samples pandas and pyqt5 to test.
I'll redo the tests later.

**Comment by MJT369** [comment]
If re freezes script a gain get pyqt5  error Import error Dll load failed while importing QtCore ... module not find.    On Wednesday, September 25, 2024 at 07:52:37 PM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 


@MJT369 Can you show me the error with numpy and pyqt5?
I used the samples pandas and pyqt5 to test.
I'll redo the tests later.

**Comment by marcelotduarte** [comment]
PR #2588 fixed an regression w/ numpy.
Also I found a warning with numpy > 2.0 with pyside2 and is a cause of error to import qtcore, so I suspect that it can affect pyqt5.
Please test the rebased version.
pip uninstall cx_Freeze
and get the wheel in https://github.com/marcelotduarte/cx_Freeze/actions/runs/11081448732/artifacts/1990254817
If fails with numpy > 2, try w/ numpy 1.26.4

**Comment by MJT369** [comment]
I tested  v723 it with completely new python 12 with updated librarys and unfortunately QtCore importing error  and  also get error like [WinError 193] %1 is not a valid Win32 application. Error loading "N:\taraz_sofware\TarazSoft\build\exe.win-amd64-3.12\lib\torch\lib\dbghelp.dll" or one of its dependencies.
For torch    On Saturday, September 28, 2024 at 11:17:30 AM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 


PR #2588 fixed an regression w/ numpy.
Also I found a warning with numpy > 2.0 with pyside2 and is a cause of error to import qtcore, so I suspect that it can affect pyqt5.
Please test the rebased version.
pip uninstall cx_Freeze
and get the wheel in https://github.com/marcelotduarte/cx_Freeze/actions/runs/11081448732/artifacts/1990254817
If fails with numpy > 2, try w/ numpy 1.26.4

**Comment by marcelotduarte** [comment]
@MJT369 
What the versions of
pyqt
torch
numpy
...
Are you using venv?

**Comment by marcelotduarte** [comment]
@MJT369 I believe your problem is neither with torch nor pyqt5. Even if it is with one of those packages conflicting with cx_Freeze, I suggest you write a small piece of code to reproduce the error and I should be able to fix it. Telling me it didn't work doesn't help me. I have reports that it works with the recent changes and I have also tested them with the code provided.
Please open a new issue with a good report and I will investigate the cause and provide a solution.

torch https://github.com/marcelotduarte/cx_Freeze/issues/2526#issuecomment-2385654039
pyqt5 https://github.com/marcelotduarte/cx_Freeze/issues/2552#issuecomment-2381368103
pyqt6 https://github.com/marcelotduarte/cx_Freeze/issues/2542#issuecomment-2379660590

**Comment by MJT369** [comment]
Please Try freeze  this script with windows 10
    On Tuesday, October 1, 2024 at 07:45:55 PM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 


@MJT369 I believe your problem is neither with torch nor pyqt5. Even if it is with one of those packages conflicting with cx_Freeze, I suggest you write a small piece of code to reproduce the error and I should be able to fix it. Telling me it didn't work doesn't help me. I have reports that it works with the recent changes and I have also tested them with the code provided.
Please open a new issue with a good report and I will investigate the cause and provide a solution.

torch #2526 (comment)
pyqt5 #2552 (comment)
pyqt6 #2542 (comment)

**Comment by marcelotduarte** [comment]
> Please Try freeze  this script with windows 10

What script?

**Comment by MJT369** [comment]
Sorry for not inform please find it attached file
    On Wednesday, October 2, 2024 at 04:30:49 PM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 



Please Try freeze this script with windows 10


What script?

**Comment by marcelotduarte** [comment]
> Sorry for not inform please find it attached file

No attachment was received. Please use github interface and paste the script.
EDIT: It is better to open a new issue.

**Comment by MJT369** [comment]
I opened New issues with attached app script.Flowing https://github.com/marcelotduarte/cx_Freeze/issues/2599


    On Wednesday, October 2, 2024 at 08:32:07 PM GMT+3:30, Marcelo Duarte ***@***.***> wrote:  
 
 



Sorry for not inform please find it attached file


No attachment received. Please use github interface and paste the script.
