### ISSUE TITLE
error: [Errno 13] Permission denied: 'test1'

### ISSUE THREAD

**Issue by gtatyous** [marcelotduarte/cx_Freeze#243]
All of the cx_Freeze examples are for one file (module). I need to make an executable for an entire python package. Why is that hard to make?

Here's my directory:
```
test1/
  __init__ 
  __main__
```

The way I run this from the command line is by using the following cmd

`python -m test1 
`
`__init__` is empty and `__main__` just have a simple `print` statement. I am using python 3.5.1 but I can switch to python 3.4 if that would fix the problem

Here is my `setup.py` for win64

```
from cx_Freeze import setup, Executable
import sys

build_exe_options = {"packages": ['test1'],
                     "include_files": []
                    }
executables = [
                Executable("__main__")
              ]
setup(
    name = "Foo",
    version = "0.1",
    description = "Help please!",
    author = "me",
    options = {"build_exe": build_exe_options},
    executables = executables
)
```

**Comment by olegario96** [comment]
Same problem here

**Comment by anthony-tuininga** [comment]
Can you not create a simple Python file that calls your package? The code that starts up your application doesn't know about the "-m" option.
