### ISSUE TITLE
cxfeeze example references non-existent CLI option

### ISSUE THREAD

**Issue by cdavidson-project-canary** [marcelotduarte/cx_Freeze#2430]
**Describe the bug**
The example command located at https://cx-freeze.readthedocs.io/en/stable/script.html references a command option "--target-dir" which is not described on the page and does not appear in the help printout.

**Comment by marcelotduarte** [comment]
[Release 7.2.2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.2) is out!
[Documentation](https://cx-freeze.readthedocs.io)
