### ISSUE TITLE
PyQt6 import error in cx_Freeze 7.1, missing DLL

### ISSUE THREAD

**Issue by VegarS** [marcelotduarte/cx_Freeze#2431]
Freezing with cx_Freeze 7.1 causes an import error in PyQt6 scripts. It can be reproduced with the PyQt6 sample files:
![image](https://github.com/marcelotduarte/cx_Freeze/assets/1231463/7ea63cb2-4ca2-41df-9783-3233ba4e9047)

The issue is also present in 7.2.0dev2, but everything seems to work with 7.0.0.

**To Reproduce**
- Run setup.py in cx_Freeze/samples/pyqt6: py -3.11 setup.py build
- Run resulting exe file in build/exe.win-amd64-3.11

**Desktop:**
 - Platform information: Windows 11
 - OS architecture: amd64
 - cx_Freeze version: 7.1 and 7.2.0dev2
 - Python version: 3.11

**Comment by marcelotduarte** [comment]
[Release 7.1.0-post0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.1.0-post0) is out!
[Documentation](https://cx-freeze.readthedocs.io)
