### ISSUE TITLE
Extend DMG functionality by using an external library

### ISSUE THREAD

**Issue by ntindle** [marcelotduarte/cx_Freeze#2441]
Tools like [`dmgbuild` (python)](https://github.com/dmgbuild/dmgbuild) and [`appdmg` (node)](https://www.npmjs.com/package/appdmg) for MacOS allow the user to configure the layout of the `.dmg` drive and add things like this

![img of a visually configured dmg](https://raw.githubusercontent.com/LinusU/node-appdmg/bb0f693a74341fda7934b42fd0adcb37022f6e05/help/help.png)

Would you be interested in having that feature for cx_Freeze, and if so, how would you expect it to be integrated? Reimplementation of the existing package (dmgbuild) or using it?

The work to add it on doesn't seem to be that large and with guidance I would be willing to put up a pr

_Originally posted by @ntindle in https://github.com/marcelotduarte/cx_Freeze/discussions/2438_

**Comment by ntindle** [comment]
> I'm not a macOS user, but I knew about dmgbuild and [create-dmg](https://github.com/create-dmg/create-dmg), which seem more complete, but more difficult to integrate.
And answering your question, I am happy with your willingness to contribute and I believe that using dmgbuild as a dependency is the best option.
The implementation of bdist_dmg in this case, should be moved from [here](https://github.com/marcelotduarte/cx_Freeze/blob/main/cx_Freeze/command/bdist_mac.py#L27) to a new module.
There a test [here](https://github.com/marcelotduarte/cx_Freeze/blob/main/tests/test_command_bdist_mac.py#L46) that can be moved to new module and enhanced to test the new options.

Message from @marcelotduarte for context

**Comment by marcelotduarte** [comment]
[Release 7.2.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.0) is out!
[Documentation](https://cx-freeze.readthedocs.io)
