### ISSUE TITLE
Linux builds have started failing since updating to 7.2

### ISSUE THREAD

**Issue by ntindle** [marcelotduarte/cx_Freeze#2508]
**Prerequisite**
 - Make sure no duplicated issue has already been reported. You should look for closed issues, too.
 - Make sure you are not asking us to help to solve your specific issue. GitHub issues are opened mainly for development purposes. If you want to ask someone to help to solve your problem, go to some community site like StackOverflow, etc.
 - Make sure your problem is not derived from packaging (e.g. Homebrew).

**Describe the bug**
Since updating to 7.2 from my fork of 7.1 with the MSI and DMG changes in, builds on ubuntu for appimage have begun to fail

**To Reproduce**
Don't yet have but you can see the pipeline here: https://github.com/Significant-Gravitas/AutoGPT/actions/runs/9968979624/job/27545138099#step:16:14960

**Expected behavior**
Build should pass or give a clear failure reason. Scroll up a few lines to 14649 and a traceback is output in the middle of other code. I'm not sure if its related

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): GHA Ubuntu
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: 7.2.0
 - Python version [e.g. 3.10]: 3.10

**Additional context**

**Comment by marcelotduarte** [comment]
The error occurs in https://github.com/Significant-Gravitas/AutoGPT/actions/runs/9968979624/job/27545138099#step:16:14697 (a SIGABRT when running patchelf). Maybe there is a problem with memory allocation.
Try to rerun the failed job.
The patchelf used is 0.17.2 (https://github.com/Significant-Gravitas/AutoGPT/actions/runs/9968979624/job/27545138099#step:16:77) which is the same one I've been using for a while, but if the error persists you can try using a previous version.

**Comment by ntindle** [comment]
Will try it out!

**Comment by marcelotduarte** [comment]
> Build should pass or give a clear failure reason. Scroll up a few lines to 14649 and a traceback is output in the middle of other code. I'm not sure if its related

It would help if you used `python -u setup.py ...` because the stderr and stdout are mixed in the output.
`-u     : force the stdout and stderr streams to be unbuffered;`

**Comment by marcelotduarte** [comment]
[Release 7.2.2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.2) is out!
[Documentation](https://cx-freeze.readthedocs.io)

Can you test it?

**Comment by marcelotduarte** [comment]
https://github.com/marcelotduarte/cx_Freeze/pull/2620#issue-2577432613

**Comment by marcelotduarte** [comment]
[Release 7.2.4](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.4) is out!
[Documentation](https://cx-freeze.readthedocs.io)
