### ISSUE TITLE
can't open file 'cxfreeze': [Errno 2] No such file or directory while bdist_rpm or bdist_deb

### ISSUE THREAD

**Issue by geekdinazor** [marcelotduarte/cx_Freeze#2527]
**Prerequisite**
 - Make sure no duplicated issue has already been reported. You should look for closed issues, too.
 - Make sure you are not asking us to help to solve your specific issue. GitHub issues are opened mainly for development purposes. If you want to ask someone to help to solve your problem, go to some community site like StackOverflow, etc.
 - Make sure your problem is not derived from packaging (e.g. Homebrew).

**Describe the bug**
Building RPM/DEB with `cxfreeze bdist_rpm` command crashed with error `<project_path>/.venv/bin/python: can't open file 'cxfreeze': [Errno 2] No such file or directory` using pyproject.toml. I use virtualenv located in <project_path>/.venv and cx_freeze package installed in this virtualenv. 

**Error log:** 
```
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.F4Gidd
+ umask 022
+ cd <project_path>/build/bdist.linux-x86_64/rpm/BUILD
+ cd <project_name_and_version>
+ env CFLAGS=-O2 -g <project_path>/.venv/bin/python cxfreeze build_exe -O1 --silent
<project_path>/.venv/bin/python: can't open file 'cxfreeze': [Errno 2] No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.F4Gidd (%build)
```
I use cxfreeze command method for pyproject.toml which advised in documentation but it seems runs setup.py in copied project directory in RPM build directory. See: https://github.com/marcelotduarte/cx_Freeze/blob/main/cx_Freeze/command/bdist_rpm.py#L473  and https://github.com/marcelotduarte/cx_Freeze/blob/main/cx_Freeze/command/bdist_rpm.py#L484
Using setup.py method works correctly.

**To Reproduce**
Steps to reproduce the behavior (a setup.py or a minimal code sample will be good)

1. Copy files in  [simple_pyproject sample](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/simple_pyproject) to project directory. 
2. Create virtualenv in project directory 
3. Activate virtualenv and install cx_freeze using `pip install cx_freeze` command
4. Run `cxfreeze bdist_rpm` command.

**Expected behavior**
Creation of RPM package sucessfully.

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): LMDE 6 (faye)
 - OS architecture (e.g. amd64): amd64
 - cx_Freeze version [e.g. 6.11]: 7.2.0
 - Python version [e.g. 3.10]: 3.8.11

**Additional context**

**Comment by marcelotduarte** [comment]
It's good to know that you'll be using pyproject.
To test the fix, install:
`pip install git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/2529/head`

You can use the [simple_pyproject sample](https://github.com/marcelotduarte/cx_Freeze/tree/main/samples/simple_pyproject) but you should remove the [line](https://github.com/marcelotduarte/cx_Freeze/pull/2529/files#diff-a82c12bf5b87b7fd5731a4d9a2b1a5a3ddf239f7a7816ca432ec2ff84f753821L9) not to throw a build-id in rpm.

Please give me feedback.

**Comment by geekdinazor** [comment]
Thanks for fix.  It works like a charm!

**Comment by marcelotduarte** [comment]
[Release 7.2.1](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.1) is out!
[Documentation](https://cx-freeze.readthedocs.io)
