### ISSUE TITLE
'build_exe' has no such option 'compressed '

### ISSUE THREAD

**Issue by danpla** [marcelotduarte/cx_Freeze#253]
After upgrading to v5.0.1, cx_Freeze gives an error:
```
py -3.4 setup_win.py build_exe
running build_exe
error: error in setup script: command 'build_exe' has no such option 'compressed'
```
The option is still available in the cxfreeze script and listed in the documentation.

**Comment by eeyrjmr** [comment]
the compressed option was dropped with v5.0

https://bitbucket.org/anthony_tuininga/cx_freeze/pull-requests/67/remove-some-parameters-from-freezer/diff

**Comment by MarvBob** [comment]
The documentation of build_exe should be updated to remove the compressed option (http://cx-freeze.readthedocs.io/en/latest/distutils.html#build-exe).
Also, is there a way to get the same result as with the compressed option ? I mean having the python modules in a library.zip folder ?

**Comment by den-run-ai** [comment]
This breaks meld diff tool:

https://github.com/GNOME/meld

**Comment by fireundubh** [comment]
> Also, is there a way to get the same result as with the compressed option?

~~I would like an answer to this question as well. Thanks.~~

edit: Found the solution here: https://stackoverflow.com/a/44429619/5157341
