### ISSUE TITLE
`PyQt6` issues in `cx_Freeze 7.2.0`

### ISSUE THREAD

**Issue by kristofmulier** [marcelotduarte/cx_Freeze#2542]
We're using `cx_Freeze` to build our application Embeetle IDE (https://embeetle.com) on both Windows and Linux. The `cx_Freeze` version `7.2.0` caused an issue with `PyQt6` in the Windows build. Our `.svg` icons no longer showed up:

![image](https://github.com/user-attachments/assets/a10ae20e-7fc3-4937-a8b3-ed9c8d1ce37f)

Rolling back to `cx_Freeze 7.1.1` fixed the issue:

![image](https://github.com/user-attachments/assets/e56be497-6f4e-4a8d-bc10-a5e4d1737c9e)

The build happens on a Windows 10 computer (last screenshot is on Windows 11, but the build was on Windows 10) with `Python 3.12.4`:

- Python : `3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]`
- `PyQt6==6.7.1`
- `PyQt6-QScintilla==2.14.1`
- `PyQt6-Qt6==6.7.2`
- `PyQt6-WebEngine==6.7.0`
- `PyQt6-WebEngine-Qt6==6.7.2`
- `PyQt6-WebEngineSubwheel-Qt6==6.7.2`
- `PyQt6_sip==13.8.0`

**Comment by kristofmulier** [comment]
Hi @marcelotduarte ,
I made a PayPal donation of 60$ to show my appreciation for your work. Hope to get in touch with you:
kristof@embeetle.com

Kind regards,
Kristof

**Comment by marcelotduarte** [comment]
@kristofmulier Thanks!
I've been busy lately, but I've had some free time and I'm trying to fix some bugs.
I haven't been able to test exactly what the problem is with SVG, but I believe it's an error similar to #2552.

**Comment by marcelotduarte** [comment]
[Release 7.2.1](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.1) is out!
[Documentation](https://cx-freeze.readthedocs.io)

Please test and give me feedback.

**Comment by kristofmulier** [comment]
Hi @marcelotduarte ,
Unfortunately, the `cx_Freeze 7.2.1` Release doesn't fix the svg-problem:

![image](https://github.com/user-attachments/assets/9bcf9228-58d2-4420-8802-fd0b4f3a59ec)

Here's the version information of this build:

```
Embeetle Version
================
version: 1.8.25
date: 11 Sep 2024
platform: windows

Python Version
==============
version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]

Installed Packages
==================
aenum==3.1.15
astyle-py==1.0.5
attrs==24.2.0
cabarchive==0.2.4
certifi==2024.8.30
chardet==5.2.0
colorama==0.4.6
cx_Freeze==7.2.1
cx_Logging==3.2.0
Cython==3.0.11
feedparser==6.0.11
filelock==3.15.4
hypothesis==6.112.0
lief==0.14.1
lowbar==1.5.3
Markdown==3.7
packaging==24.1
pieces_copilot_sdk==0.6.0
pieces_os_client==3.2.0
pip==24.2
pydantic==1.10.17
pyelftools==0.31
Pygments==2.18.0
PyQt6==6.7.1
PyQt6-QScintilla==2.14.1
PyQt6-Qt6==6.7.2
PyQt6-WebEngine==6.7.0
PyQt6-WebEngine-Qt6==6.7.2
PyQt6-WebEngineSubwheel-Qt6==6.7.2
PyQt6_sip==13.8.0
pyserial==3.5
pyte==0.8.2
python-dateutil==2.9.0.post0
pywin32==306
pywinpty==2.0.13
PyYAML==6.0.2
pyzmq==26.1.0
regex==2024.7.24
setuptools==70.3.0
sgmllib3k==1.0.0
six==1.16.0
sortedcontainers==2.4.0
striprtf==0.0.26
typing_extensions==4.12.2
urllib3==2.2.2
vboxapi==1.0
wasmtime==12.0.0
watchdog==5.0.2
wcwidth==0.2.13
websocket-client==1.8.0
wheel==0.43.0
winshell==0.6
xmltodict==0.13.0
zmq==0.0.0
```

I'm afraid I'll have to switch back to `cx_Freeze 7.1.1`.

**Comment by marcelotduarte** [comment]
Can you show me how to reproduce this error? It could be a small code based on this: https://github.com/marcelotduarte/cx_Freeze/blob/main/samples/pyqt6/test_pyqt6.py

**Comment by kristofmulier** [comment]
I've written a very small project (one `main.py` file and one `build.py` file) to reproduce the problem. Please download and unzip this on a Windows PC:

[svg-pyqt-test.zip](https://github.com/user-attachments/files/17073972/svg-pyqt-test.zip)

You should now see this in the unzipped `svg-pyqt-test` folder:

<img src="https://github.com/user-attachments/assets/dfca14e0-90ad-4fc4-96bc-c11428393a83" width="500" />


First install the python packages:

```
> pip install --upgrade -r requirements.txt
```

This will install `cx_Freeze 7.1.1`. Now run the `build.py` file without any additional arguments. The script uses `cx_Freeze` to build `main.py`. The `frozen` folder should appear. In there is the `main.exe` executable:

<img src="https://github.com/user-attachments/assets/c2589ed1-b1d4-4599-b13e-eaafcf338c3f" width="300" />

As you can see, when built with `cx_Freeze 7.1.1` - it's just fine. The little house icon is in the button.

Now let's change the `requirements.txt` file. Switch from `cx_Freeze 7.1.1` to `cx_Freeze 7.2.1`:

```
# cx_Freeze == 7.1.1     # svg files work
cx_Freeze == 7.2.1   # svg files don't work
```
 Run the requirements file again:

```
> pip install --upgrade -r requirements.txt
```

And build again:

```
> python build.py
```

And look:

<img src="https://github.com/user-attachments/assets/d4220247-880c-4466-9d3c-82e4e49faaa4" width="300" />

**Comment by marcelotduarte** [comment]
Can you test the PR #2578?
`pip install git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/2578/head`

**Comment by marcelotduarte** [comment]
Wheel for Windows, Python 3.12: https://github.com/marcelotduarte/cx_Freeze/actions/runs/10970558992/artifacts/1961238206

**Comment by kristofmulier** [comment]
Yes, that seems to work!
I downloaded the Wheel for Windows (I'm on a Windows 11 with Python 3.12.6) and then installed it like so:

```cmd
> cd C:\Users\krist\Downloads\cx-freeze-pip-windows-latest-3.12
> pip install cx_Freeze-7.2.1-cp312-cp312-win_amd64.whl
```

Now when I check:

```cmd
>pip freeze
cx_Freeze @ file:///C:/Users/krist/Downloads/cx-freeze-pip-windows-latest-3.12/cx_Freeze-7.2.1-cp312-cp312-win_amd64.whl#sha256=1ff2f45fcb9562abccedc17506c4fe157ebcc814015e0c68782fa4158e5f4741
cx_Logging==3.2.0
Cython==3.0.11
...
```

Then I went into my little `svg-pyqt-test` program - the one I prepared for testing this - and ran a build. It works:

<img src="https://github.com/user-attachments/assets/eca392c6-a3c3-42a1-9f19-624af1a65619" width=600>

As you can see, the svg-icon is right there, in the button.

**Comment by marcelotduarte** [comment]
[Release 7.2.2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.2) is out!
[Documentation](https://cx-freeze.readthedocs.io)

**Comment by marcelotduarte** [comment]
@kristofmulier 
Is v7.2.2 working as expected?

**Comment by kristofmulier** [comment]
Hi @marcelotduarte ,
Yes, it works like a charm!
Thanks a lot

**Comment by marcelotduarte** [comment]
Thank you for your feedback.
