### ISSUE TITLE
cx-Freeze - No module named 'scipy._lib.array_api_compat._aliases'

### ISSUE THREAD

**Issue by Knightly123** [marcelotduarte/cx_Freeze#2544]
I updated scipy from v1.4.1 to v1.14.0, when I built the program with cx_Freeze 7.2.0, I got this error message:No module named 'scipy._lib.array_api_compat._aliases'.

below code will cause this issue, and I found that in SciPy, 'scipy._lib.array_api_compat._aliases' not exists, but you can find 'scipy._lib.array_api_compat.**numpy**._aliases'
**from scipy.signal import butter, sosfiltfilt**

Here is my environment:
python 3.12.2
scipy 1.14.0
numpy 1.26.4

My VM is win10 21H2,  use conda env, the bolded code can reproduce this issue.
For now I downgrade the version from 1.14.0 to 1.11.4(by pip), it works.

**Comment by marcelotduarte** [comment]
I need more details. An ideal issue is a [bug report](https://github.com/marcelotduarte/cx_Freeze/issues/new?assignees=&labels=&projects=&template=bug-report.md&title=) with more details, how to reproduce, OS, environment (pip, conda).

**Comment by marcelotduarte** [comment]
I cannot reproduce the error using the most recent version in conda, cx_freeze 7.2.1, scipy 1.14.1, nor with scipy 1.14.0 rev 2
I suspect that is a conda package error for rev 0.
If the error persists, please try an cleaner install. If this does not solve, please report and provide a small code to reproduce the error.

**Comment by marcelotduarte** [comment]
Issue #2596 is related and a fix was provided.
[Release 7.2.3](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.3) is out!
[Documentation](https://cx-freeze.readthedocs.io)
