### ISSUE TITLE
Why is Executable target_name has to be  A valid identifier?

### ISSUE THREAD

**Issue by istyaq-ahmmed** [marcelotduarte/cx_Freeze#2572]
In https://github.com/marcelotduarte/cx_Freeze/blob/7.2.1/cx_Freeze/executable.py#L234 target_name is required to be a valid identifier.

Is there any reason for that? I removed that condition and it seems to work fine.
my
target_name="6578e4ecf0464d7fb253de58"

**Comment by marcelotduarte** [comment]
Maybe a regression - issue #884 fixed by #889

**Comment by marcelotduarte** [comment]
[Release 7.2.2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.2) is out!
[Documentation](https://cx-freeze.readthedocs.io)

**Comment by istyaq-ahmmed** [comment]
Thank you.
