### ISSUE TITLE
Numexpr cant find mkl dll after freeze

### ISSUE THREAD

**Issue by GabrielMarcilio** [marcelotduarte/cx_Freeze#2574]
My project is crashes when using pandas to write  a dataframe to hdf. The error happens when numexpr calls set_vml_num_threads. I created a simple app that has numpy, mkl and numexpr that is able to reproduce the error:

The AddLog and ClearLog functions are just used to check if the application ran until the end. What is really important in the script is the lines to import numexpr and call set_vml_num_threads:

```python
log_file = any_path.txt


def _AddLog(msg):
    with open(log_file, 'a') as f:
        print(msg)
        f.write(msg + '\n')

def _ClearLog():
    with open(log_file, 'w') as file:
        print('Clearing log')


import sys
_ClearLog()


import numexpr as ne 
import numpy as np

a = np.random.rand(1000000)
b = np.random.rand(1000000)

_AddLog('Setting numthread')
ne.set_vml_num_threads(4)
_AddLog('numthread set')

result = ne.evaluate("3 * a + 4 * b")

_AddLog(f'Operation result {result}')

_AddLog('we are good')`
```
I saved this script into file test_mkl.py create an environment to run this code:
conda create --name numexpr python=3.10.4 cx_freeze numexpr=2.8.0 numpy mkl

After that i run the application with: python test_mkl.py.

The script runs correctly and the log output has the operation result:

> Setting numthread
> numthread set
> Operation result [0.27513036 5.82476118 4.14923834 ... 5.05542331 3.88291216 2.11872052]
> we are good

However after freeze the application (here follows my setup.py script:

```python
import sys
from cx_Freeze import setup, Executable

    
build_exe_options = {"packages": ["subprocess"], "excludes": [],"zip_exclude_packages":[]}


setup(  name = "test_mkl_bin",
    version = "1.0",
    description = "start_scipy_binary",
    options = {"build_exe": build_exe_options},
    executables = [Executable("test_mkl.py", base = 'Win32GUI')])
```

after freeze the application and run the created application the app crashes in the line to sen vml_num_thread, the output log only contain the message immediatly before it:

> Setting numthread

Also, in the created binary. if i copy the contents of folder lib/mkl to the root along the .exe, the application runs correctly and the number of threads is correctly set. This makes me guess that the numexpr is not able to find mkl dlls, in lib/mkl folder

**Comment by marcelotduarte** [comment]
Try to install libxcrypt and give me feedback (maybe related to #2457).

**Comment by marcelotduarte** [comment]
[Release 7.2.2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.2) is out!
[Documentation](https://cx-freeze.readthedocs.io)

**Comment by GabrielMarcilio** [comment]
Hi Marcelo, thanks for the fast return. I added libxcript to the environment and the application kept crashing. On the other hand, when i created my environment with cx-freeze version 7.2.2 the application runs correctly.

Thanks and have a nice day.
