### ISSUE TITLE
MSI file size

### ISSUE THREAD

**Issue by markox92** [marcelotduarte/cx_Freeze#2575]
Why is the MSI size different between the latest and dev CX? I mean, if I build the MSI with the latest 7.2.1 file, the size is 59 MB, if I build with the CX Dev the size is 48 MB, with the same build options.

**Comment by marcelotduarte** [comment]
It's hard to answer you without knowing what packages you're using. In any case, it could be some optimization. For example, in version 7.2.2, optimizations were made to reduce duplicate files when using pyside6 among others.
[Release 7.2.2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.2) is out!
[Documentation](https://cx-freeze.readthedocs.io)
