### ISSUE TITLE
Is it possible to use Win32GUI mode while retaining `sys.stdin` and `sys.stdout`?

### ISSUE THREAD

**Issue by jdasm** [marcelotduarte/cx_Freeze#2576]
I have a Qt application that has a feature allowing for executing external python scripts in a subprocess, using `cmd.exe` to provide script interaction. This uses the Python dist frozen into the exe. Since the actual application is a Qt GUI application I need the console hidden by using the Win32GUI mode, but as a result there is no stdin/stdout for the script launched from `cmd.exe`. This results in predictable error message like below (from `cmd.exe`):

    RuntimeError: input(): lost sys.stdin

The frozen application launches a script by:

1. Spawn a `cmd.exe` as subprocess with command passing the script file path to the frozen executable as argument
3. Frozen executable launched from `cmd.exe` sees it was called with a script argument, runs script via `exec()` instead of starting normal application
4. Script input/output is interacted with through the spawned `cmd.exe`

More specifically, the application launches the script like below:

    def _run_script(script_path: str | os.PathLike[Any]):
        """
        Run a python script from a new command line window
        """
        script_path = str(script_path)
    
        if getattr(sys, "frozen", False):
            commands = ["start", "/wait", "cmd", "/k", f"{sys.executable}", "--user-script", script_path]
        else:
            commands = ["start", "/wait", "cmd", "/k", sys.executable, script_path]
    
        process = subprocess.Popen(
            commands,
            shell=True,
        )

And the entry point to the frozen application naively intercepts the script call like this:

        if len(sys.argv) == 3:
            if sys.argv[1] == "--user-script":
                with open(sys.argv[2], "r") as handle:
                    exec(handle.read())
                sys.exit()
            else:
                raise RuntimeError("Unknown input arguments")

**cx_Freeze build**

The application is built via `cxfreeze.exe` instead of `setup.py` as I need the setup configuration for other purposes.

    cxfreeze --base=Win32GUI --target=main.exe --include-msvcr --script=... includes=... --excludes=... --include-files=...

**Desktop (please complete the following information):**
 - Windows 10
 - 64-bit
 - 7.0.0
 - 3.11

Thanks!

**Comment by jdasm** [comment]
I have came up with an alternative solution of having a separate `freeze_setup.py` config for cx_Freeze, from which I add a second executable purely responsible for executing my external scripts, such that this executable is marked as `Console`:


      setup(
          options={"build_exe": options},

          executables=[
              Executable(
                  main.py,
                  base="Win32GUI",
                  target_name="main.exe",
              ),
              Executable(
                  runscript.py,
                  base="Console",
                  target_name="runscript.exe",
              )
          ]
      )

**Comment by marcelotduarte** [comment]
Good. I use multiple executables in similar situations.
