### ISSUE TITLE
Unproper unpacking on Finder line 561

### ISSUE THREAD

**Issue by Chris-Fr-C** [marcelotduarte/cx_Freeze#258]
Good afternoon.
I started using cx_Freeze, and noticed an error that caused the crash of the compilation.
I'm using Python 3.6
I solved the problem changing the line 561 of finder.py
"fromList, = arguments" into "fromList = arguments"
I thought this could be useful, and maybe you can fix it on the source too.
Thanks for the job you did on this package.

Christophe

**Comment by FreeHarry** [comment]
See issue #254
