### ISSUE TITLE
include_msvcr is not working on 5.0.1

### ISSUE THREAD

**Issue by leoseverini** [marcelotduarte/cx_Freeze#259]
In the old version i used
`"include_msvcr" : True`
and works fine.
in the version 5.0.1 it stop working. I see in the code that I need to use "True" instead of True. (as a String)
So I tried too
`"include_msvcr" : "True"`
Still not working.
There is something Im missing? or it is a bug on the new version?
Thanks

**Comment by MarvBob** [comment]
Hey I am definitely not an expert with cx Freeze but I feel this project needs a bit of help these days.

All I can say is I am using `"include_msvcr" : True` without quotes and it's working.

Is there any error message in the output ? Any information or just nothing happening ?
Maybe you could provide your code for help. Just the `setup` call.

**Comment by henryborchers** [comment]
I'm having this exact problem when building an .msi inside a virtualenv. "include_msvcr" seems to be working outside of a virtualenv for me.

**Comment by anthony-tuininga** [comment]
Please provide a sample that demonstrates the problem. Thanks.

**Comment by marcelotduarte** [comment]
PR #973 fix this.
