### ISSUE TITLE
VTK 9.3.1 causes missing DLC for vtkRenderingCore

### ISSUE THREAD

**Issue by madmoonman** [marcelotduarte/cx_Freeze#2593]
**Describe the bug**
As the title says, when packaging a program using VTK 9.3.1, I get a missing DLL error for vtkRenderingCore. I was able to fix the issue by reverting back VTK to 9.2.6 and build successfully with that.

**To Reproduce**
Sorry, I do not have a MWE, but simply changing the VTK version fixed it, so it cannot be a problem in my code. It can probably be reproduced with a VTK python example.

**Desktop (please complete the following information):**
 - Windows 10
 - cx_Freeze version: 7.2.2
 - Python version: 3.11.1

**Comment by marcelotduarte** [comment]
You can test the patch with:
`pip install git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/2595/head`
Or get the wheel from https://github.com/marcelotduarte/cx_Freeze/actions/runs/11118384181/artifacts/1998824822

**Comment by marcelotduarte** [comment]
[Release 7.2.3](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.3) is out!
[Documentation](https://cx-freeze.readthedocs.io)
