### ISSUE TITLE
Errors using freezes windows app include Pyqt5 and argostranslate  libraries

### ISSUE THREAD

**Issue by MJT369** [marcelotduarte/cx_Freeze#2599]
If I try freezes app include Pyqt5 and argos translate I getting dependence and directory errors .
My os is windows 10 pro 64
Python 312
Cx_freeze 723 or 722
[Taraz_v02.zip](https://github.com/user-attachments/files/17234823/Taraz_v02.zip)

**Comment by marcelotduarte** [comment]
Dependencies / requirements?
pyqt5
argos
what more?

**Comment by MJT369** [comment]
> Dependencies / requirements? pyqt5 argos what more?


    install_requires=[
        'PyQt5>=5.15.11',
        'pyperclip>=1.9.0',
        'langdetect>=1.0.9',
        'pdf2docx>= 0.5.8',
        'python-docx>=1.0.0',
        'pyspellchecker>=0.8.1',
        'translatepy>=2.3',
        'argostranslate>=1.9.6',
        'deep_translator>=1.11.4',
        'wikipedia>=1.4.0',
        'farsi_tools>=0.2',
        'autocorrect>=2.6.1',
        'requests>=2.25.1',
        'urllib3>=1.26.5',
        'ftfy>= 6.2.3',
        'openpyxl>=3.1.5',
        'cydifflib>=1.1.0',
        'translators>=5.9.2',
        'torch>=2.4.1',
        'pandas>=2.2.0',
        'pypdf>=4.0.0',
        'camelot-py==0.11.0',
        'ghostscript==0.7'
    ],

**Comment by marcelotduarte** [comment]
I haven't tested your code yet, but I saw a problem in the first few lines. You use lazy loading. So this will prevent cx_Freeze from detecting the imported packages.
So, I recommend you check these two topics and make adjustments in your setup:
https://cx-freeze.readthedocs.io/en/stable/faq.html#problems-with-freezing-programs
https://cx-freeze.readthedocs.io/en/stable/faq.html#problems-with-running-frozen-programs

**Comment by MJT369** [comment]
> I haven't tested your code yet, but I saw a problem in the first few lines. You use lazy loading. So this will prevent cx_Freeze from detecting the imported packages. So, I recommend you check these two topics and make adjustments in your setup: https://cx-freeze.readthedocs.io/en/stable/faq.html#problems-with-freezing-programs https://cx-freeze.readthedocs.io/en/stable/faq.html#problems-with-running-frozen-programs

I use to  cx_freeze with python 11 it was installed well and working properly but with python 12 doesn't that problem can be cuse of other things not detecting ( there is importer function for detecting import librarys by cx_Freeze )

**Comment by MJT369** [comment]
I run VS (terminal) as   administrator  (if try to refreeze script windows not allowed to replace old files that cx freezes have to show errors and skip freezing    ) if I remove old files in default freezes directory
 and refreeze  again  than Pyqt5 working and  Pyqt5 issue fixed  ...
but argos translate  not working cause error loading buildexe.win-amd64-3.12libtorchlib dbghelp.dll or one of its dependencies
