### ISSUE TITLE
Support for Win32 service dependencies

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#26]
Originally reported by: **boris_kuchin (Bitbucket: [boris_kuchin](https://bitbucket.org/boris_kuchin), GitHub: Unknown)**

----------------------------------------

Parameters for win32 service are missing ability to set dependency on other services. In this call (`source/bases/Win32Service.c:407`):

~~~
serviceHandle = CreateService(managerHandle, PyString_AS_STRING(fullName),
            PyString_AS_STRING(displayName), SERVICE_ALL_ACCESS,
            SERVICE_WIN32_OWN_PROCESS, info.startType, SERVICE_ERROR_NORMAL,
            PyString_AS_STRING(command), NULL, NULL, NULL, NULL, NULL);
~~~

third parameter from the end allows to pass service dependencies as `LPCTSTR`. So, if one adds one more entry in `udt_ServiceInfo` struct and read it in `Setup_Python` it would be possible to add service dependencies while installing service.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/26

**Comment by anthony-tuininga** [comment]
*Original comment by* **Jonas Gröger (Bitbucket: [JonasGroeger](https://bitbucket.org/JonasGroeger), GitHub: [JonasGroeger](https://github.com/JonasGroeger))**:

----------------------------------------

Have you tried adding it yourself and compiling it if it works?

**Comment by anthony-tuininga** [comment]
*Original comment by* **boris_kuchin (Bitbucket: [boris_kuchin](https://bitbucket.org/boris_kuchin), GitHub: Unknown)**:

----------------------------------------

Nope. We've eventually solved it manually via registry entry in our installer. I've found the issue (and possibly a solution) while searching `cx_freeze` code for some `Config.py` option

**Comment by marcelotduarte** [comment]
Assuming this has been resolved.
