### ISSUE TITLE
packages' entry_points are missing

### ISSUE THREAD

**Issue by cluck** [marcelotduarte/cx_Freeze#2608]
I have a Python project that declares and implements [entry-points](https://packaging.python.org/en/latest/specifications/entry-points/) and queries the entry-points to call into optional plugins. This is working properly when cx_Freeze is not involved.

When using cx_Freeze the same query for entry-points returns no result, and all information about entry_points on any included package seem to be not present. Looking at the lib and lib/library.zip content, there are indeed no entry_points.txt files in the *.dist-info directories.

Incorporating these files manually into lib/library.zip makes the freezed binary to suddenly find the entry-points.

**To Reproduce**
I have created a minimal demo at https://github.com/cluck/cx_Freeze_entry-points

**Expected behavior**
All entry_points should be preserved.

**Comment by cluck** [comment]
This seems to solve the issue for me:

```
--- a/cx_Freeze/module.py      2024-10-04 12:27:58.901401600 +0200
+++ b/cx_Freeze/module.py      2024-10-04 12:49:35.301438400 +0200
@@ -86,6 +86,10 @@
             if source.is_file():
                 target = target_path / "METADATA"
                 target.write_bytes(source.read_bytes())
+            source = source_path / "entry_points.txt"
+            if source.is_file():
+                target = target_path / "entry_points.txt"
+                target.write_bytes(source.read_bytes())
             source = source_path / "top_level.txt"
             if source.is_file():
                 target = target_path / "top_level.txt"
```

**Comment by cluck** [comment]
I have updated the demo to show that only packages with an *.egg-info are affected. The demo now includes the pip package to show that entry_points of pip are actually preserved without the patch. It still shows that entry_points of dummymod are not preserved.

I have a `dummymod.egg-info` directory in the development directory when I develop dummymod in editable mode. Despite also having a `venv/lib/python3.11/site-packages/dummymod-1.0.0.dist-info` directory, cx_Freeze seems to discover this .egg-info directory.

**Comment by marcelotduarte** [comment]
[Release 7.2.4](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.4) is out!
[Documentation](https://cx-freeze.readthedocs.io)
