### ISSUE TITLE
 Problems with python 2.7 and multiprocessing

### ISSUE THREAD

**Issue by lnordhus** [marcelotduarte/cx_Freeze#262]
The following exsample worked with version 4.3.4 of cx_freeze, but after the update the pool = Pool() command do not seem to start the "_handle_tasks" method.
################ stuff.py
def f((x,y)): print("inside") return x * x
def main_stuff(): from multiprocessing.pool import Pool pool = Pool() # start 4 worker processes
print("before")
from my_code.MultiprosessingBugTests.newStuff import f
result = pool.map_async(f, [(10,20)])  # evaluate "f(10)" asynchronously in a single process
result.wait()
pool.close()
pool.join()
print("after")
if name == 'main': from multiprocessing import freeze_support freeze_support() main_stuff()
############ setup.py
from cx_Freeze import setup, Executable
build_exe_options = { 'build_exe': r'C:\temp\stuff3', }
setup( version="1.0", options={"build_exe": build_exe_options}, executables=[Executable(r'C:\temp\TestProject\my_code\MultiprosessingBugTests\stuff.py', base=None)] )

**Comment by anthony-tuininga** [comment]
This problem may have been solved by the 5.0.2 release. Please re-open if this is not the case.
