### ISSUE TITLE
patchelf died with <Signals.SIGABRT: 6>.

### ISSUE THREAD

**Issue by HyperDev724** [marcelotduarte/cx_Freeze#2625]
**Prerequisite**
 - Make sure no duplicated issue has already been reported. You should look for closed issues, too.
 - Make sure you are not asking us to help to solve your specific issue. GitHub issues are opened mainly for development purposes. If you want to ask someone to help to solve your problem, go to some community site like StackOverflow, etc.
 - Make sure your problem is not derived from packaging (e.g. Homebrew).

**Describe the bug**

Using cx_freeze 7.2.3 to package the project in the Python environment of Linux Miniconda, the packaging error is:
subprocess.CalledProcessError: Command '['/usr/local/miniconda3/envs/py31012/bin/patchelf', '--force-rpath', '--set-rpath', '$ORIGIN/lib', PosixPath('/root/api/build/exe.linux-x86_64-3.10/lib/cx_Freeze/bases/console-cpython-310-x86_64-linux-gnu')]' died with <Signals. SIGABRT: 6>.

When using cx_freeze 6.11.1 for packaging, it can be successfully packaged

**To Reproduce**
Steps to reproduce the behavior (a setup.py or a minimal code sample will be good)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 22.04): Centos7.9
 - OS architecture (e.g. amd64):
 - cx_Freeze version [e.g. 6.11]: 7.2.3
 - Python version [e.g. 3.10]: MiniConda Python 3.10.12

**Additional context**

**Comment by marcelotduarte** [comment]
Duplicate of #2508
Please read https://github.com/marcelotduarte/cx_Freeze/pull/2620#issue-2577432613
I tested only on Ubuntu. Can you test it in your system?
Uninstall cx_Freeze then
`pip install git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/2620/head`
Or download the wheel at https://github.com/marcelotduarte/cx_Freeze/actions/runs/11310828894/artifacts/2049482481
A better option is to create a new environment for the test and use pip only for the test.

**Comment by HyperDev724** [comment]
![image](https://github.com/user-attachments/assets/4e1da981-f61c-4a86-b121-208c76e66844)

**Comment by marcelotduarte** [comment]
Download the wheel at https://github.com/marcelotduarte/cx_Freeze/actions/runs/11310828894/artifacts/2049482481
Unzip it and 
`pip install cx_Freeze-7.3.0.dev0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`

**Comment by marcelotduarte** [comment]
To use the first option, you need the c compiler, read https://cx-freeze.readthedocs.io/en/stable/development/index.html#conda-forge

**Comment by HyperDev724** [comment]
Successfully packaged, the packaged program can also run successfully

**Comment by gabiapple** [comment]
Hello @marcelotduarte 
There is an option to use this  patch with Python 3.8.5?

I'm getting an error while trying to install it:
```
pip install git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/2620/head
Collecting git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/2620/head
  Cloning https://github.com/marcelotduarte/cx_Freeze.git (to revision refs/pull/2620/head) to /tmp/pip-req-build-3zq8_j_3
  Running command git clone --quiet https://github.com/marcelotduarte/cx_Freeze.git /tmp/pip-req-build-3zq8_j_3
  WARNING: Did not find branch or tag 'refs/pull/2620/head', assuming revision or ref.
  Running command git fetch -q https://github.com/marcelotduarte/cx_Freeze.git refs/pull/2620/head
  Running command git checkout -q 023a15a54fbad84f0d68a3dfb6a99cc49a14f746
  Resolved https://github.com/marcelotduarte/cx_Freeze.git to commit 023a15a54fbad84f0d68a3dfb6a99cc49a14f746
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: packaging>=24 in /home/gabriela/venvs/js-clean/lib/python3.8/site-packages (from cx_Freeze==7.3.0.dev0) (24.1)
Requirement already satisfied: setuptools<76,>=65.6.3 in /home/gabriela/venvs/js-clean/lib/python3.8/site-packages (from cx_Freeze==7.3.0.dev0) (75.2.0)
Requirement already satisfied: importlib-metadata>=6 in /home/gabriela/venvs/js-clean/lib/python3.8/site-packages (from cx_Freeze==7.3.0.dev0) (8.5.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/gabriela/venvs/js-clean/lib/python3.8/site-packages (from cx_Freeze==7.3.0.dev0) (4.12.2)
Requirement already satisfied: tomli>=2.0.1 in /home/gabriela/venvs/js-clean/lib/python3.8/site-packages (from cx_Freeze==7.3.0.dev0) (2.0.2)
Requirement already satisfied: filelock>=3.12.3 in /home/gabriela/venvs/js-clean/lib/python3.8/site-packages (from cx_Freeze==7.3.0.dev0) (3.16.1)
Requirement already satisfied: patchelf>=0.14 in /home/gabriela/venvs/js-clean/lib/python3.8/site-packages (from cx_Freeze==7.3.0.dev0) (0.17.2.1)
INFO: pip is looking at multiple versions of cx-freeze to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'cx-freeze' requires a different Python: 3.8.5 not in '>=3.9'
```

**Comment by marcelotduarte** [comment]
Hello, @gabiapple 
I didn't intend to release more versions for 3.8, but if you migrated to Linux ;-)

[Release 7.2.4](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.4) is out!
[Documentation](https://cx-freeze.readthedocs.io)
