### ISSUE TITLE
When using SQLite the "sqlite3.dll" is not copied, but should be

### ISSUE THREAD

**Issue by swhcz** [marcelotduarte/cx_Freeze#263]
Hi there,

not sure if this is a bug (just reject if it isn't, as the workaround is trivial):

I'm freezing a PySide / SQLite application for Windows, and recently all was good. Now that I've upgraded to Python 3.6 (and probably quite a few packages alongside) freezing works but execution fails with a DLL import error, complaining that SQLite is missing a library.

Long story short, I located C:\Python36\DLLs\sqlite3.dll, copied it next to the binary, and all is fine again.

Question is: should this have been done automatically?

I had the same freezing done for an older Python (3.4), which was working OK for a long time, so it may have been introduced with Python 3.6.

Thanks a lot!
Sebastian

**Comment by FreeHarry** [comment]
See issue #207

**Comment by anthony-tuininga** [comment]
A hook has been added so that this can be done automatically.

**Comment by andreapiso** [comment]
Is the hook in the available version? I am on 5.1.1 and got the exact same error, sqlite3.dll not found...

**Comment by Jonas-Carvalho** [comment]
I've got the same error as well. My version is 5.1.1 and python 3.6.8 
:/

**Comment by kurt-rhee** [comment]
Same error in version 6.0

**Comment by brightening-eyes** [comment]
hi,
I have the same error in master with python 3.7 (with virtualenv) as well.
please add a workaround for it.
thanks.

**Comment by anthony-tuininga** [comment]
Can you provide a simple script that demonstrates the issue? In cx_Freeze master there is a sample for sqlite3. Does that also not work for you?

**Comment by brightening-eyes** [comment]
hi,
install telethon with pip, then import it. and you can see that cx_freeze won't copy sqlite3.dll (when used with virtualenv).
didn't try that without virtualenv.
