### ISSUE TITLE
Incorrect Handling of Native Namespace Packages (PEP 420)

### ISSUE THREAD

**Issue by IvanKosik** [marcelotduarte/cx_Freeze#2644]
**Describe the bug**
When creating an *.exe for a native namespace package [PEP 420](https://peps.python.org/pep-0420/) such as `company/appname` (where `company` is a namespace package without an `__init__.py` file, and `appname` is a regular package with an `__init__.py` file), the resulting build includes an unexpected `__init__.pyc` file in the `exe_dir/lib/company/` directory.

**To Reproduce**
Create a namespace package structure:
```
company/
└── appname/
    └── __init__.py
    └── main.py
```
Build the executable using cx_Freeze with next `build_exe_options`:
```
build_exe_options = {
    'build_exe': BUILD_DIR,
    'packages': [
        'company.appname'
    ]
}
```
Observe the output directory structure:
```
exe_dir/
└── lib/
    └── company/
        ├── __init__.pyc
        └── appname/
            └── __init__.pyc
            └── main.pyc
```
**Problem**
The presence of the `__init__.pyc` file in the `company` directory converts the namespace package into a regular package, which disrupts the runtime behavior. Specifically, it prevents the correct identification of the first non-namespace package (e.g., `company.appname`), causing it to incorrectly return `company` as the first non-namespace package.

**Expected behavior**
No `__init__.pyc` file should be present in the `exe_dir/lib/company` directory.

**Workaround**
Manually delete the `exe_dir/lib/company/__init__.pyc` file after the build process.

**Desktop:**
 - Platform information: Windows 10
 - OS architecture: amd64
 - cx_Freeze versions: 7.2.3 and 7.1.0.post0
 - Python version: 3.10.14

**Comment by marcelotduarte** [comment]
I understand the issue, and to fix it, we have to remember not to break the fix for #1276.

> The presence of the `__init__.pyc` file in the `company` directory converts the namespace package into a regular package, which disrupts the runtime behavior. Specifically, it prevents the correct identification of the first non-namespace package (e.g., `company.appname`), causing it to incorrectly return `company` as the first non-namespace package.

How do I get this information?

**Comment by marcelotduarte** [comment]
> How do I get this information?

I mean, a small code to detect the namespace.

**Comment by IvanKosik** [comment]
Sorry, did not catch the question at first.
To find the first non-namespace package for a class type, we are using [this method](https://github.com/BSMU-ITLab/vision/blob/main/src%2Fbsmu%2Fvision%2Fcore%2Futils%2Fpackage.py#L16).

But we can use a simpler method just to check if the package name is namespace or regular:
```
import importlib.util


def is_namespace_package(package_name: str) -> bool:
    spec = importlib.util.find_spec(package_name)
    return spec.origin is None

    # # For imported modules next code can be used:
    # import company.appname
    # import sys
    # package_module = sys.modules[package_name]
    # return package_module.__file__ is None


print(is_namespace_package('company'))
print(is_namespace_package('company.appname'))
```

**Comment by marcelotduarte** [comment]
You can test the PR using the wheel from [here](https://github.com/marcelotduarte/cx_Freeze/actions/runs/11689173302/artifacts/2147985880).

**Comment by IvanKosik** [comment]
Thank you very much!
We have tested the wheel. It fixes the main issue successfully: `__init__.pyc` file in the `exe_dir/lib/company/` directory is **not** created now.

There are two questions connected with the new wheel:

1) There is a small problem with `zlib.dll`. The previous version of cx_Freeze (7.2.3) added this dll into the build. The version from the wheel does not do it, so when we run the built app *.exe we are getting the error: `... system did not find zlib.dll ...`.
Is this behaviour intended and do we have to add some flag to add `zlib.dll` into the build?
For now we have added `zlib.dll` from the build, created by cx_Freeze 7.2.3 and everything works like a charm!

2) There is the following use case:
E.g. we have `company.appname.configs` directory - it is a standard folder with config files (no `__init__.py` there and no *.py files).
We have used the `include_files` option to put them into a custom folder near the *.exe:
`'include_files': [('Full-path-to-project-dir/company/appname/configs', 'data/configs')]`
During the build the configs dir is copied into `exe-dir/data/configs`.
Then we want to remove the configs dir from the lib folder: `exe-dir/lib/company/appname/configs` (we do not need two duplicated configs dirs). To do it, we added the `excludes` option like:
`'excludes':  ['company.appname.configs']`
The question is: can we use the `excludes` option for that or is it the wrong usage of that option?
**Why this question is connected with this issue**: in the previous cx_Freeze version (7.2.3) we used the `excludes` option for this use case. E.g.:
`'excludes':  ['company.firstapp.configs', 'company.secondapp.configs', 'company.secondapp.models']`
It worked partially: it excluded the indicated directories from the first nested namespace package (e.g. `company.firstapp.configs`), but did not exclude the indicated directories from the second nested namespace package (e.g. `company.secondapp.configs` and `company.secondapp.models`).
The new wheel does not exclude such dirs (even from `company.firstapp.configs`).
It would be very nice, if that option (if it is intended for such use case) excluded all the passed dirs.

**Comment by marcelotduarte** [comment]
Hi!
1. The official Python embeds zlib, so I assume you use conda-forge. Therefore, zlib and possibly others will be missing. But when I release the version, if you use Conda to install it, you will not have any problems.
2. I use something similar without any problems, later I'll try to automate some tests for this. By the way, if you can contribute with a small code that simulates the situation, that would be great, it will speed up the process.

**Comment by IvanKosik** [comment]
Hello!
1. Got it, thank you for the clarification! (I'm using Miniconda just as a Python virtual environment manager and installing all packages using pip.)
2. I'll gladly make a code example on Sunday.

**Comment by IvanKosik** [comment]
Here is the sample code: https://github.com/IvanKosik/cxfreeze-namespace-issue

We have the following packages: one regular package and one namespace package with two child (nested) packages. Each package has some data directories (configs, models) that should be excluded from the build.

- **Using cx_Freeze 7.2.4**: Everything works well; the data directories are excluded from all packages.
- **Using cx_Freeze 7.3.0.dev0 (the wheel)**: The data directories are excluded only from the regular package and not from the child packages of the nested package.

In my previous post, I mentioned that with version 7.2.3, excluding data directories works partially (excludes only from the first child package). This sample code does not reproduce that behavior; it needs additional investigation.

**Comment by marcelotduarte** [comment]
[Release 7.2.5](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.5) is out!
[Documentation](https://cx-freeze.readthedocs.io)

If you can, test the 7.3.0 w/ https://github.com/marcelotduarte/cx_Freeze/actions/runs/11786951275/artifacts/2173478653

**Comment by IvanKosik** [comment]
Thank you very much!
Both versions (7.2.5 and 7.3.0) work great! All the issues mentioned above are completely resolved. Amazing work!

**Comment by dsmitran** [comment]
I tested 7.2.5. It works. Thank you.
Previously 7.2.4 did not work since it did not bundle zlib.dll (I am using miniconda)
