### ISSUE TITLE
ImportError: No module named __startup__

### ISSUE THREAD

**Issue by shadow111** [marcelotduarte/cx_Freeze#265]
Hello,

i'm using ubuntu 16.04 LTS

python 2.7

Latest FReeze version

after runing   cxfreeze hello.py --target-dir dist

i got the binary but when i run it i have this message in the terminal : ImportError: No module named __startup__

**Comment by MarvBob** [comment]
This issue has already been reported here: #209

**Comment by anthony-tuininga** [comment]
As noted, this issue has already been reported and is being tracked in #209.
