### ISSUE TITLE
Missing libwinpthread-1.dll and libgcc_s_seh-1.dll in top directory

### ISSUE THREAD

**Issue by cedk** [marcelotduarte/cx_Freeze#2671]
Since #2624 the issue  #1651 has reappeared on MSYS build.

**Comment by marcelotduarte** [comment]
[Release 7.2.5](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.5) is out!
[Documentation](https://cx-freeze.readthedocs.io)

https://github.com/msys2/MINGW-packages/pull/22498
