### ISSUE TITLE
cx_freeze failing to freeze torchvision

### ISSUE THREAD

**Issue by splake975** [marcelotduarte/cx_Freeze#2713]
I am trying to use cx_freeze on a program using easyocr and it seems that cx_freeze is not properly freezing torchvision.

here is a minimal reproducible example. 

python version = 3.12.4

`cx_freeze==7.2.7`
`easyocr==1.7.2`

the torchvision version that comes with this easyocr is
`torchvision==0.20.1`

```
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need
# fine tuning.
build_options = {'packages': [], 'excludes': [],"include_files":[]}

base = 'gui'

executables = [
    Executable('./testTorch/test.py', base=base, target_name = 'testTorch')
]

setup(name='testTorch',
      version = '1.0',
      description = 'title',
      options = {'build_exe': build_options},
      executables = executables)
``` 
`./testTorch/test.py`:

```
import logging

class TestError(Exception):
    def __str__(self):
        return f"TestError"
    


def main():
    logging.basicConfig(
        filename='log.log', 
        level=logging.DEBUG, 
        format='%(asctime)s - %(levelname)s - %(message)s', 
    )
    try:
        import torchvision
        logging.info(torchvision.__version__)
        raise TestError
    except Exception as e:
        logging.error(str(e))


if __name__=="__main__":
    main()
```

If run from cmd, I get this in log
```
2024-12-03 04:18:44,585 - INFO - 0.20.1+cpu
2024-12-03 04:18:44,585 - ERROR - TestError
```
but run from the exe that cx_freeze outputs I get 
```
2024-12-03 04:21:35,644 - ERROR - cannot import name 'NP_SUPPORTED_MODULES' from 'torch._dynamo.utils' (C:\...\build\exe.win-amd64-3.12\lib\torch\_dynamo\utils.pyc)
```

I have seen several issues raised on the github page for cx_freeze but they dont quite match the error I am getting here.

**Comment by marcelotduarte** [comment]
You can test the PR with:
`pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.2751.dev1735130372`

**Comment by marcelotduarte** [comment]
[Release 7.2.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.8) is out!
[Documentation](https://cx-freeze.readthedocs.io)

Please give me feedback.

**Comment by splake975** [comment]
I can confirm this newest patch fixes the problem. Thank you.
