### ISSUE TITLE
liblzma-c9407571.so.5.6.3 not found by PIL

### ISSUE THREAD

**Issue by Heribert17** [marcelotduarte/cx_Freeze#2715]
When packaging on Linux Mint and using PIL in the Python script I get this error message:
'ImportError: liblzma-c9407571.so.5.6.3: Can't open Shared-Object-File: File or directory not found

The installed version of liblzma on Linux mint is 5.6.1
The version of liblzma in the lib directory of the packed application is (cx_freeze 7.2.4):  liblzma-004595ca.so.5.2.2
Until cx_freeze version 7.2.3 the right liblzma is called, starting with version 7.2.4 the error is thrown.

```
Traceback (most recent call last):
  File "/home/heribert/Dokumente/Projekte/Privat/Test_python/cx_freeze_error/venv_linux/lib/python3.12/site-packages/cx_Freeze/initscripts/__startup__.py", line 140, in run
    module_init.run(f"__main__{name}")
  File "/home/heribert/Dokumente/Projekte/Privat/Test_python/cx_freeze_error/venv_linux/lib/python3.12/site-packages/cx_Freeze/initscripts/console.py", line 25, in run
    exec(code, main_globals)
  File "test.py", line 5, in <module>
  File "/home/heribert/Dokumente/Projekte/Privat/Test_python/cx_freeze_error/venv_linux/lib/python3.12/site-packages/PIL/Image.py", line 97, in <module>
    from . import _imaging as core
ImportError: liblzma-c9407571.so.5.6.3: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
```

**To Reproduce**
Python sample (test.py):
```
from PIL import Image

if __name__ == "__main__":
    im = Image.open('image.png')
    im.show()

```
setup.py:
```
from cx_Freeze import setup, Executable


build_exe_options = {
    "includes": [],
    "include_files": [],
    "excludes": [],
    "silent_level": 3,
    "optimize": 2,
    "build_exe": "../distribution_linux/test",
}

Target_1 = Executable(
    script="test.py",
    base="console",
    copyright="(c) H. Füchtenhans",
    target_name="test",
)


def main() -> None:
    """Hauptprogramm"""
    setup(
        version="0.0.0",
        description="Test program",
        author="Heribert Füchtenhans",
        name="test",
        options={"build_exe": build_exe_options},
        executables=[Target_1],
    )

if __name__ == "__main__":
    main()

```

**Expected behavior**
Should work with newer versions of cx_freeze

**Desktop (please complete the following information):**
 - Platform information: Linux Mint 22 Wilma
 - OS architecture: amd64
 - cx_Freeze version: 7.2.7
 - Python version: Python 3.12.3

**Comment by marcelotduarte** [comment]
You can test the PR with:
`pip install --extra-index-url https://test.pypi.org/simple/ cx-Freeze==7.3.0.2718.dev1733560081`

**Comment by Heribert17** [comment]
Thank you very much. Test program and real application work with that patch

**Comment by marcelotduarte** [comment]
[Release 7.2.8](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.2.8) is out!
[Documentation](https://cx-freeze.readthedocs.io)
