### ISSUE TITLE
Documentation on how to make a file association in MSI for Windows

### ISSUE THREAD

**Issue by cmcqueen** [marcelotduarte/cx_Freeze#274]
It would be good to document how to create a file association with cx_Freeze `bdist_msi` in Windows. That is, so double-clicking on a file with a certain filename extension in Explorer will open my program.

I guess it would have something to do with the `setup()` call `options` parameter, `bdist_msi` key, `data` sub-key, `Registry` table sub-key (perhaps some other table(s)).

**Comment by marcelotduarte** [comment]
Implemented in PR #1032 (read the first comment of the PR)
CC @cmcqueen @nickvandewiele @guettli

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7b1 has just been released.
pip install cx-Freeze==6.7b1
