### ISSUE TITLE
Problems with Pyqtgraph

### ISSUE THREAD

**Issue by mjs513** [marcelotduarte/cx_Freeze#284]
I am really new to this, trying to make a exe file from a python script.  Anyway I managed to reduce the number of errors I got down to those associated with pygtgraph (I think).  I tried to explicitly include pyqtgraph in the build script but no luck.  Here is a scree shot of the traceback:

![capture](https://user-images.githubusercontent.com/5366213/28047454-1ec531fc-65b8-11e7-9f9e-64ee76341243.PNG)

I am using python 2.7 and pyqtgraph 0.9.6 on a windows 10 machine.

Any help would be appreciated.

**Comment by anthony-tuininga** [comment]
If this is attempting to write to stderr or stdout from inside a Windows GUI executable, it will fail like this. You'll need to avoid those kinds of writes or use a console base instead. If neither of those helps, please provide a sample that demonstrates the problem.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
