### ISSUE TITLE
Freezed app unable to load .so-file

### ISSUE THREAD

**Issue by okin** [marcelotduarte/cx_Freeze#291]
I am trying to package an application that import OpenSSL and fails with the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "app.py", line 4, in <module>
    from OpenSSL import SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libffi-9caa966d.so.6.0.4: cannot open shared object file: No such file or directory
```

The file get's copied: `copying /usr/local/lib/python2.7/dist-packages/.libs_cffi_backend/libffi-9caa966d.so.6.0.4 -> build/exe.linux-i686-2.7/libffi-9caa966d.so.6.0.4`

Somehow the app fails to pick it up when loading.

# Example

This is an example to show the behaviour.

## app.py

    #! /usr/bin/env python
    # -*- coding: utf-8 -*-

    from OpenSSL import SSL

    if __name__ == '__main__':
        assert SSL
        print("Import works.")

## setup.py

    #! /usr/bin/env python
    # -*- coding: utf-8 -*-

    import os

    from cx_Freeze import setup, Executable

    buildOptions = {
        "packages": [
            'cffi',
            'cryptography',
        ],
        "excludes": [],
        "include_files": [],
    }

    localDirectory = os.path.dirname(__file__)

    setup(name='testapp',
          version='1.0',
          description='openssl app freeze test.',
          options={"build_exe": buildOptions},
          executables=[Executable(os.path.join(localDirectory, 'app.py'), 'Console', targetName='app')])

# Environment

* Debian 9 (32bit)
* Python 2.7.13
* cx-Freeze 5.0.2  (also tried with 4.3.4 - resulting in the same error)

* python-cryptography 1.7.1-3
* python-cffi 1.9.1-2
* python-openssl 16.2.0-1 
* openssl 1.1.0f-3

I tried using the packages from pypi instead but this did not seem to change much.

**Comment by anthony-tuininga** [comment]
I just tried this on Fedora 26 using the latest code on the cx_Freeze-5.x branch and all appears to work well. Can you try with the latest code?

**Comment by okin** [comment]
I tried it with the latest version from branch `v5.x` (_64cf9400d031d062402f2d11641d95b213090528_).
This worked - thank you!

I am now getting the error `ImportError: No module named __startup__` that seems to be #209.
