### ISSUE TITLE
Error build on OSX Yosemite

### ISSUE THREAD

**Issue by fgoudreault** [marcelotduarte/cx_Freeze#292]
When I try to freeze a python script (that requires tkinter), I run into the following error when I do:

  $ python setup.py bdist_msi

`
    (...)
    creating directory build/exe.macosx-10.7-x86_64-3.6/lib/python3.6

    Copying data from package IPython...

    Copying data from package OpenSSL...

    Copying data from package PyQt5...

    copying /(...)/miniconda3/lib/python3.6/site-packages/PyQt5/QtCore.so -> build/exe.macosx-10.7-
x86_64-3.6/lib/python3.6/PyQt5/QtCore.so

    copying /(...)/miniconda3/lib/python3.6/site-packages/PyQt5/QtCore.so -> build/exe.macosx-10.7-x86_64-3.6/QtCore.so

    copying /(...)/miniconda3/lib/libQt5Core.5.dylib -> build/exe.macosx-10.7-x86_64-3.6/libQt5Core.5.dylib

    copying /(...)/miniconda3/lib/libz.1.dylib -> build/exe.macosx-10.7-x86_64-3.6/libz.1.dylib

    copying /(...)/miniconda3/lib/libicui18n.54.dylib -> build/exe.macosx-10.7-x86_64-3.6/libicui18n.54.dylib

    copying /(...)/miniconda3/lib/./libicuuc.54.dylib -> build/exe.macosx-10.7-x86_64-3.6/libicuuc.54.dylib

    copying /(...)/miniconda3/lib/././libicudata.54.dylib -> build/exe.macosx-10.7--86_64-.6/libicudata.54.dylib

    copying libicudata.54.1.dylib -> build/exe.macosx-10.7-x86_64-3.6/libicudata.54.1.dylib

    error: [Errno 2] No such file or directory: 'libicudata.54.1.dylib'`

When I look into the build directory `build/exe.macosx-10.7... ` I find that `libicudata.54.dylib` is actually there (since it looked like it was copied from the conda directory) and the file `libicudata.54.1.dylib` is obviously not there even though it exists inside the python install directory.  It seems it tries to copy a file without its absolute path!

Content of setup.py:

`   from cx_Freeze import setup

    base = None
    executables = [Executable("myapp.py", base=base, targetName="myapp.dmg")]
    setupcx(name="myapp",
                  executables=executables)`

I use miniconda with python 3.6 on MacOs Yosemite.

**Comment by fgoudreault** [comment]
After digging into the source code, it seems that when the freezer copies files from the python install directory, it tries to get the files that has dependencies. There seems to have a bug for this particular file: 
`/(...)/miniconda3/lib/././libicudata.54.dylib`. When calling` _GetDependentFiles(this_file)`, it returns a list containing a file without the full path to it. Thus this method returns `["libicudata.54.1.dylib"]` only and it tries to copy this file also but it does not exists in the current directory only in the same directory as its parent, thus the error!

From this error, I tried to redo the otool command to get the dependencies of this file. This is what I get:

`   
       $ otool -L "/(...)/miniconda3/lib/././libicudata.54.dylib"

        /(...)/miniconda3/lib/././libicudata.54.dylib:

	libicudata.54.1.dylib (compatibility version 54.0.0, current version 54.1.0)

	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)`

So it seems that problem comes from `otool` that returns a file without the absolute path. Maybe this is a bug from otool?

**Comment by anthony-tuininga** [comment]
Thanks for the analysis. Can you create a pull request correcting the issue? I have no ready access to the macOS platform and only minor experience with it. All of the macOS work came from others! You could ask on the mailing list and see if anyone there can help you out further.

**Comment by fgoudreault** [comment]
I've submitted a patch. It fixes this problem in particular but there is subsequent bugs thereafter not necessarily linked to otool. Thoss could be in another issue.

**Comment by anthony-tuininga** [comment]
Patch merged.
