### ISSUE TITLE
Python 3.6 and PyQT5 on Mac OS X - Missing Frameworks/Directories

### ISSUE THREAD

**Issue by MCBoarder289** [marcelotduarte/cx_Freeze#299]
**Quick preface**: I'm newer to programming, but pretty comfortable with Python on Windows OS. For a side project, I needed to build an OS X app from the Python app I wrote with PyQT5 that performs a simple script with a simple GUI. 

**Environment**: latest python3 installed using homebrew on an OS X (Sierra 10.12) laptop. Downloaded packages using pip3. Using a setup.py script with the build or bdist_mac commands

**Issue**: During the build/freeze process, I kept getting multiple errors that I would try and resolve one by one until I had completed everything. The main errors were that the files/directories the build process was looking for didn't exist. I'll outline them in order and how I manually fixed them to get this app out the door:

1.  First, the Python.Framework was not found in my /Library/Frameworks directory (likely because homebrew only installs this in the /usr/local/Cellar directory). **Hack Solution**: copy/pasted my Python.Framework in my /usr/local/Cellar directory to the /Library/Frameworks directory

2.  Next, had to copy/paste the site-packages directory from the /usr/local/Cellar directory into the newly pasted Python.Framework.

3.  Now there were errors in the process related to the QT frameworks that were located in /usr/local/lib/python3.6/site-packages/PyQt5/Qt/lib, so I manually copied those into the Library/Frameworks directory as well, but for some reason this did not capture all that were needed. There was a QTGamepad.Framework that didn't exist. **Hack Solution**: I downloaded the latest version of QT for Mac so that I could get ALL the frameworks that existed to paste into that Library location. **Speculation of broader issue**: cx_freeze is not looking in ALL of the locations that homebrew/the Mac OS X file structure places all of its installs (or it only looks in one particular place, but not all). Maybe not 100% a cx_freeze issue, but the only thing that resolved it was manually moving these things around where cx_freeze could find them.

4.  That resolved all of the QT Framework dependencies, but now there was a MySQL .dylib missing from a directory that didn't even exist on my mac (/opt/local/lib/mysql55/mysql/libmysqlclient.18.dylib. **Hack Solution**: I actually manually created this whole directory folder list, and pasted in the latest libmysqlclient.20.dylib after brew-installing MySQL. I renamed that dylib libmysqlclient.18.dylib to suppress the error and the script continued on...

5.  The next error was a PostgresSQL .dylib, which I again copy/pasted/renamed to suppress the error (that one was already located within my homebrew installation folders (/usr/ directory).

These steps finally got the bdist_mac option to create a .App file that I can open on the computer that I built this on. I have to test it on a similar Mac OS without python3 installed to see if it works, but before I wasn't able to get the .app created without all this moving of files/directories around. The only remaining errors are associated with the Xcode application, so i'm not sure how critical that is without testing it on a mac without Python3.

Please let me know if there's anything else that I can provide to help diagnose or do to help work through a solution! Hopefully someone with more Mac experience can take this explanation and make sense of it!

[Working App Terminal Dump.docx](https://github.com/anthony-tuininga/cx_Freeze/files/1239505/Working.App.Terminal.Dump.docx)

**Comment by ijharulislam** [comment]
I am also facing the same issue. Is there any solution?

**Comment by MCBoarder289** [comment]
You're the first to comment on it- and I was only able to get things working with the manual pasting around of everything. Probably not the solution you were looking for, but did you try any of my steps to get the freeze to complete?

**Comment by lithiumFlower** [comment]
I am having exactly this issue with Python3.6, PyQt5.9,  OSX 10.12.6

**Comment by anthony-tuininga** [comment]
Thanks for the detailed explanation....but I'm afraid I am not the one with more Mac experience! Hopefully someone else will see this and comment.

**Comment by skrech** [comment]
Hey guys,

I wanted to report a new bug but I see that there is a similar thread, so I'll use it.
The problem of the OP (at least for the PyQt part) is that he installed the packages with pip. 
Up until PyQt5 version 5.9.2 the PyQt guys were putting wheel packages on PyPI with all the shared libraries having hardcoded install name to /Library/Frameworks/Python*... Since cx_Freeze is using "otool -L" for finding *.so dependencies, it can't distinguish between install names and actual dependencies it failed to copy the non-existing file. However, several people reported this behaviour on PyQt mailing list (including me - http://python.6.x6.nabble.com/PyQt5-5-9-pip-wheels-depend-on-Python-framework-on-OSX-td5224547.html ) and they decided to drop the hardcoded install name in the wheels. 

So updating to PyQt5 5.9.2 from PyPI will fix bugs 1. and 2.

However, the problem that I wanted to report is how cx_Freeze is handling @rpath declarations in *.so loadpaths. 

Here is what cx_Freeze is doing:
freezer.py / method _GetDependentFiles:

```
if sys.platform == "darwin":
                    # Make library paths absolute. This is needed to use
                    # cx_Freeze on OSX in e.g. a conda-based distribution.
                    # Note that with @rpath we just assume Python's lib dir,
                    # which should work in most cases.
                    dirname = os.path.dirname(path)
                    dependentFiles = [p.replace('@loader_path', dirname)
                                      for p in dependentFiles]
                    dependentFiles = [p.replace('@rpath', sys.prefix + '/lib')
for p in dependentFiles]
```

So cx_Freeze is searching for Qt dependencies in sys.prefix/lib while the wheel package Qt dependencies are located in sys.prefix/lib/python3.5/site-packages/PyQt5/Qt/lib.

Here is the output of otool -L QtCore.so:

```
QtCore.so:
	@rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.9.0, current version 5.9.3)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
```

Now, as I think of it may be this is not a cx_Freeze bug but PyQt one. What do you think guys?

Edit: Now I run otool -l QtCore.so and here is why everything is loaded successfully when the program is run non-freezed:

```
Load command 14
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/Frameworks (offset 12)
Load command 15
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/Qt/lib (offset 12)
```

So it's not a PyQt bug. cx_Freeze should have mechanism to check the LC_RPATH attribute in the *.so private headers.

**Comment by anthony-tuininga** [comment]
Can someone with a Mac attempt to solve this issue? You may wish to try the latest code in either v5.x or master, just to make sure that this didn't get fixed by the new code which addresses other issues. There is also a sample PyQt5 app in the samples directory which may prove useful.

**Comment by gmarull** [comment]
Same problem here, as @skrech mentioned, the actual problem comes from:

```
if sys.platform == "darwin":
                    # Make library paths absolute. This is needed to use
                    # cx_Freeze on OSX in e.g. a conda-based distribution.
                    # Note that with @rpath we just assume Python's lib dir,
                    # which should work in most cases.
                    dirname = os.path.dirname(path)
                    dependentFiles = [p.replace('@loader_path', dirname)
                                      for p in dependentFiles]
                    dependentFiles = [p.replace('@rpath', sys.prefix + '/lib')
for p in dependentFiles]
```

The actual rpath can be obtained either by parsing the output of `otool -l` or by using `macholib` similar to the code below:

```
from macholib.MachO import MachO
from macholib.mach_o import LC_RPATH

macho = MachO('QtCore.so')
for command in macho.headers[0].commands:
    if command[0].cmd == LC_RPATH:
        print(command) # this shows the same path listed by 'otool -l'
```

I will try to fix this issue. Probably parsing otool output is a "better" choice to not add new dependencies to cx_Freeze?

Regards,

**Comment by gmarull** [comment]
A first (dirty) approach that seems to work:

```
                if sys.platform == "darwin":
                    # Make library paths absolute. This is needed to use
                    # cx_Freeze on OSX in e.g. a conda-based distribution.
                    # Note that with @rpath we just assume Python's lib dir,
                    # which should work in most cases.
                    from macholib.mach_o import LC_RPATH
                    from macholib.MachO import MachO
                    
                    # default to system lib folder (is this actually reasonable?)
                    rpath = sys.prefix + '/lib'

                    # obtain last rpath
                    macho = MachO(path)
                    for command in macho.headers[0].commands:
                        if command[0].cmd == LC_RPATH:
                            # strip null-bytes, convert to string
                            rpath = command[2].rstrip(b'\x00').decode('utf8')

                    dirname = os.path.dirname(path)
                    # replace first rpath (if it contains loader_path it will be replaced below)
                    dependentFiles = [p.replace('@rpath', rpath)
                                      for p in dependentFiles]
                    dependentFiles = [p.replace('@loader_path', dirname)
                                      for p in dependentFiles]
```

I don't know if taking the last rpath is actually correct (I have no previous experience, I have always left rpath handling to CMake)

EDIT: with the code above, the PyQt5 example works.

**Comment by gmarull** [comment]
Looking at DYLD docs:

```
       @rpath/
              Dyld maintains a current stack of paths called the run path list.  When @rpath is  encountered
              it  is  substituted  with each path in the run path list until a loadable dylib if found.  The
              run path stack is built from the LC_RPATH load commands in the depencency chain that  lead  to
              the  current  dylib  load.   You  can add an LC_RPATH load command to an image with the -rpath
              option  to  ld(1).   You  can  even  add  a  LC_RPATH  load  command  path  that  starts  with
              @loader_path/,  and  it will push a path on the run path stack that relative to the image con-taining containing
              taining the LC_RPATH.  The use of @rpath is most useful when  you  have  a  complex  directory
              structure  of  programs  and  dylibs  which can be installed anywhere, but keep their relative
              positions.  This scenario could be implemented using @loader_path, but every client of a dylib
              could  need  a different load path because its relative position in the file system is differ-ent. different.
              ent. The use of @rpath introduces a level of indirection that simplies  things.   You  pick  a
              location in your directory structure as an anchor point.  Each dylib then gets an install path
              that starts with @rpath and is the path to the dylib relative to the anchor point.  Each  main
              executable  is  linked with -rpath @loader_path/zzz, where zzz is the path from the executable
              to the anchor point.  At runtime dyld sets it run path to be the anchor point, then each dylib
              is found relative to the anchor point.
```

**Comment by gmarull** [comment]
Hi Again,

I have also observed that, in this particular case, if the file is missing the PyQt5 example still works fine (I guess because all PyQt5 module is copied, and therefore the libraries). So maybe issuing a warning for missing files would be enough as a first workaround (or an option for that)?

```patch
diff --git a/cx_Freeze/freezer.py b/cx_Freeze/freezer.py
index 27a78c2..91c1062 100644
--- a/cx_Freeze/freezer.py
+++ b/cx_Freeze/freezer.py
@@ -413,6 +413,11 @@ class Freezer(object):
            Files are included unless specifically excluded but inclusions take
            precedence over exclusions."""
 
+        # check if file exists
+        if not os.path.exists(path):
+            sys.stderr.write('WARNING: missing dependency ({})\n'.format(path))
+            return False
+
         # check for C runtime, if desired
         path = os.path.normcase(path)
         dirName, fileName = os.path.split(path)
```

EDIT:

While doing tests, I have used the following to find RPATH candidates, it may be of interest to better handle RPATH resolution:

```python
# parse RPATH candidates from otool
r = os.popen('otool -l {}'.format(file))

rpaths = re.findall('^.*LC\_RPATH.*\n^.*\n^.*path (.*) \(.*', r.read(), re.MULTILINE)
```

**Comment by skrech** [comment]
Why is this bug closed without resolution?
This makes cx_Freeze (even the trunk) unable to freeze PyQt5 projects after version 5.9. Even more projects might be affected if they make use of rpaths that are different than what cx_Freeze expects (which is really pure guess of one directory).

**Comment by skrech** [comment]
There is even a pull request that fixes this and as bonus doesn't treat LC_ID_DYLIB as dependency:
https://bitbucket.org/anthony_tuininga/cx_freeze/pull-requests/99/improve-the-detection-of-shared-libraries/diff

**Comment by alandmoore** [comment]
@gmarull Just wondering if you have had any progress on this issue?  I'm struggling to get a Qt5 project built for macOS due to this issue.  I've tried manually patching my freezer.py file with your code, but it doesn't seem to make any difference.

I know very little about macOS, but I have access to a mac so if I can help in any way, let me know.

**Comment by gmarull** [comment]
I started using PyInstaller for all my projects, it offers more features and it is more stable.

Gerard Marull-Paretas
teslabs.com

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by humblewolf** [comment]
Issue came for me on `python 3.9` and `pyside6` on `Mac M1`, rpath was broken for `libpyside6.abi3.6.3.dylib` and
 `libshiboken6.abi3.6.3.dylib`, I had to manually paste the files to the resolved rpath.

**Comment by UHaider** [comment]
@humblewolf I am also facing the same issue with `python 3.9` and `pyside6 `on mac intel. Where did you paste the file and from where did you copy it?

**Comment by marcelotduarte** [comment]
Please check the issue #1431 @humblewolf @UHaider
