### ISSUE TITLE
64 bit not working

### ISSUE THREAD

**Issue by MangoTornado** [marcelotduarte/cx_Freeze#305]
cx_Freeze doesn't work on my 64 bit windows 10 computer the install, installs files without extensions and when i added the .exe in it told me that the program didn't support 64 bit only 32.

**Comment by dwcaraway** [comment]
Hi, can you provide further details. 

- Are you using a 64-bit release of Python?
- Are you trying to compile the exe or build an msi installer?
- Can you provide any stack traces or other messages that might indicate the problem?

I built and tested the [simple sample](https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/simple) using 64 bit Anaconda 4.4.0 (using Python 3.6.0) and cx_freeze 5.0.2. I ran `python setup.py build` and observed:
- built on Windows 7, tested on Windows 7 64-bit and Windows 10 64-bit
- built on Windows 10, tested on Windows 7 64-bit and Windows 10 64-bit

You might consider starting with one of the sample applications that are known to work and verifying them on your system and then move up to your custom code.

**Comment by anthony-tuininga** [comment]
Closing due to lack of information.
