### ISSUE TITLE
Will cx_Freeze support python 2.7 still?

### ISSUE THREAD

**Issue by azuring2** [marcelotduarte/cx_Freeze#306]
@anthony-tuininga   ,  will cx_Freeze 6.x support python 2.7 still?
Much of our code still needs python 2.7 library and cannot transport to 3.5 .  We hope cx_Freeze can support 2.7. For example ,there are too many pyds and dlls(more than 70) in the root directories of our application, we hope the new pyd-packing feature can be applied to cx_Freeze version for python 2.7.

**Comment by anthony-tuininga** [comment]
cx_Freeze 6.x is only going to support Python 3.5+. cx_Freeze 5.x will continue to support Python 2.7, however, so that will continue as long as there is interest in Python 2.7.
