### ISSUE TITLE
Issue: The system cannot find the file specified.

### ISSUE THREAD

**Issue by winstoncyh** [marcelotduarte/cx_Freeze#309]
I've posted an issue I'm encountering with cx-freeze in trying to compile some exes. I did not have this issue previously, i was wondering if some updates to my company's windows 64 bit terminal may have caused this issue as I'm able to compile it, on my home desktop, not on my company's terminal.
https://stackoverflow.com/questions/46128280/pywintypes-error-2-beginupdateresource-the-system-cannot-find-the-file-sp

Hope you can give some pointers for this. Thank you so much.

**Comment by anthony-tuininga** [comment]
Looks like the problem is resolved as noted on StackOverflow.
