### ISSUE TITLE
Cannot run properly when the executable's path includes whitespace

### ISSUE THREAD

**Issue by fhfuih** [marcelotduarte/cx_Freeze#310]
I'm running the latest cxfreeze from pypi on Windows. Since python is installed in `%LOCALAPPDATA%`, which is inside `C:\Users\<Username-but-mine-has-a-whitespace>`, Cxfreeze seems unable to run properly. Console information shown below:
```
C:\Users\Huang Zeyu>cxfreeze
'C:\Users\Huang' is not recognized as an internal or external command, operable program or batch file
```
This issue won't occur when running other programs. So basically I think it's related to cxfreeze but not system.

**Comment by MarvBob** [comment]
I think it's a Windows problem actually.
Try adding quotation marks in the Windows environment path to cxfreeze.

**Comment by fhfuih** [comment]
Ok, I will try it out

**Comment by anthony-tuininga** [comment]
I assume that was the issue. Please re-open if not!
