### ISSUE TITLE
C:\Program Files\Anaconda3\Lib\encodings\__init__.py", line 31, in <module> ModuleNotFoundError: No module named 'codecs'

### ISSUE THREAD

**Issue by bilersan** [marcelotduarte/cx_Freeze#311]
Hi,

I'm trying to build my python scripts to binary in order to run it as a service - even though cx_freeze builds it successfully i am having the error "module not found" 

I checked my path variables and also patched cx_fereze with fix@209 

my output folder (exe.win-amd64-3.6) includes lib subfolder which contains all necessary libraries and necessary dlls - it appears binary looking for a different path and i couldn't figure out why

there are no multiple python versions - my environment is;

os: windows 10 enterprise
python: 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]

any help is much appreciated
thank you

**Comment by klensy** [comment]
fix@209 for ```5.x``` branch for python 2.x, for 3.6 you should try to use ```master``` branch (dont know how cx-freeze work with 3.6).

**Comment by anthony-tuininga** [comment]
Can you provide sample code that demonstrates the problem?

**Comment by johnny1496** [comment]
I have a basically identical problem, an error when running the executable. I am using Python 3.6 (anaconda), cx_freeze 5.0 (current) on windows 10. Thank you for any help with this.

> Fatal Python error: Py_Initialize: unable to load the file system codec
> Traceback (most recent call last):
>   File "C:\Anaconda3\lib\encodings\__init__.py", line 31, in <module>
> ModuleNotFoundError: No module named 'codecs'

My program:
`print('Hello, World!')`

My setup:
```
from cx_Freeze import setup, Executable

setup(name="Hello",
      version="0.1",
      executables=[Executable("testExe.py")])
```

This is the result from running : python setup.py build

> running build
> running build_exe
> copying C:\Anaconda3\lib\site-packages\cx_Freeze\bases\Console.exe -> build\exe.win-amd64-3.6\testExe.exe
> copying C:\Anaconda3\api-ms-win-crt-stdio-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-stdio-l1-1-0.dll
> copying C:\Anaconda3\python36.dll -> build\exe.win-amd64-3.6\python36.dll
> copying C:\Anaconda3\VCRUNTIME140.dll -> build\exe.win-amd64-3.6\VCRUNTIME140.dll
> copying C:\Anaconda3\api-ms-win-crt-math-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-math-l1-1-0.dll
> copying C:\Anaconda3\api-ms-win-crt-locale-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-locale-l1-1-0.dll
> copying C:\Anaconda3\api-ms-win-crt-string-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-string-l1-1-0.dll
> copying C:\Anaconda3\api-ms-win-crt-runtime-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-runtime-l1-1-0.dll
> copying C:\Anaconda3\api-ms-win-crt-convert-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-convert-l1-1-0.dll
> copying C:\Anaconda3\api-ms-win-crt-time-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-time-l1-1-0.dll
> copying C:\Anaconda3\api-ms-win-crt-environment-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-environment-l1-1-0.dll
> copying C:\Anaconda3\api-ms-win-crt-process-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-process-l1-1-0.dll
> copying C:\Anaconda3\api-ms-win-crt-heap-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-heap-l1-1-0.dll
> copying C:\Anaconda3\api-ms-win-crt-conio-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-conio-l1-1-0.dll
> copying C:\Anaconda3\api-ms-win-crt-filesystem-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-filesystem-l1-1-0.dll
> Stamped: build\exe.win-amd64-3.6\testExe.exe
> writing zip file build\exe.win-amd64-3.6\lib\library.zip
> 
>   Name                      File
>   ----                      ----
> m BUILD_CONSTANTS           
> m __future__                C:\Anaconda3\lib\__future__.py
> m __startup__               C:\Anaconda3\lib\site-packages\cx_Freeze\initscripts\__startup__.py
> m _ast                      
> m _bisect                   
> m _blake2                   
> m _bootlocale               C:\Anaconda3\lib\_bootlocale.py
> m _bz2                      C:\Anaconda3\DLLs\_bz2.pyd
> m _codecs                   
> m _codecs_cn                
> m _codecs_hk                
> m _codecs_iso2022           
> m _codecs_jp                
> m _codecs_kr                
> m _codecs_tw                
> m _collections              
> m _collections_abc          C:\Anaconda3\lib\_collections_abc.py
> m _compat_pickle            C:\Anaconda3\lib\_compat_pickle.py
> m _compression              C:\Anaconda3\lib\_compression.py
> m _datetime                 
> m _dummy_thread             C:\Anaconda3\lib\_dummy_thread.py
> m _functools                
> m _hashlib                  C:\Anaconda3\DLLs\_hashlib.pyd
> m _heapq                    
> m _imp                      
> m _io                       
> m _locale                   
> m _lzma                     C:\Anaconda3\DLLs\_lzma.pyd
> m _md5                      
> m _multibytecodec           
> m _opcode                   
> m _operator                 
> m _pickle                   
> m _random                   
> m _sha1                     
> m _sha256                   
> m _sha3                     
> m _sha512                   
> m _signal                   
> m _socket                   C:\Anaconda3\DLLs\_socket.pyd
> m _sre                      
> m _ssl                      C:\Anaconda3\DLLs\_ssl.pyd
> m _stat                     
> m _string                   
> m _strptime                 C:\Anaconda3\lib\_strptime.py
> m _struct                   
> m _thread                   
> m _threading_local          C:\Anaconda3\lib\_threading_local.py
> m _tracemalloc              
> m _warnings                 
> m _weakref                  
> m _weakrefset               C:\Anaconda3\lib\_weakrefset.py
> m _winapi                   
> m abc                       C:\Anaconda3\lib\abc.py
> m argparse                  C:\Anaconda3\lib\argparse.py
> m ast                       C:\Anaconda3\lib\ast.py
> m atexit                    
> m base64                    C:\Anaconda3\lib\base64.py
> m bdb                       C:\Anaconda3\lib\bdb.py
> m binascii                  
> m bisect                    C:\Anaconda3\lib\bisect.py
> m builtins                  
> m bz2                       C:\Anaconda3\lib\bz2.py
> m calendar                  C:\Anaconda3\lib\calendar.py
> m cmd                       C:\Anaconda3\lib\cmd.py
> m code                      C:\Anaconda3\lib\code.py
> m codecs                    C:\Anaconda3\lib\codecs.py
> m codeop                    C:\Anaconda3\lib\codeop.py
> P collections               C:\Anaconda3\lib\collections\__init__.py
> m collections.abc           C:\Anaconda3\lib\collections\abc.py
> m contextlib                C:\Anaconda3\lib\contextlib.py
> m copy                      C:\Anaconda3\lib\copy.py
> m copyreg                   C:\Anaconda3\lib\copyreg.py
> m datetime                  C:\Anaconda3\lib\datetime.py
> m difflib                   C:\Anaconda3\lib\difflib.py
> m dis                       C:\Anaconda3\lib\dis.py
> m doctest                   C:\Anaconda3\lib\doctest.py
> m dummy_threading           C:\Anaconda3\lib\dummy_threading.py
> P email                     C:\Anaconda3\lib\email\__init__.py
> m email._encoded_words      C:\Anaconda3\lib\email\_encoded_words.py
> m email._header_value_parser C:\Anaconda3\lib\email\_header_value_parser.py
> m email._parseaddr          C:\Anaconda3\lib\email\_parseaddr.py
> m email._policybase         C:\Anaconda3\lib\email\_policybase.py
> m email.base64mime          C:\Anaconda3\lib\email\base64mime.py
> m email.charset             C:\Anaconda3\lib\email\charset.py
> m email.contentmanager      C:\Anaconda3\lib\email\contentmanager.py
> m email.encoders            C:\Anaconda3\lib\email\encoders.py
> m email.errors              C:\Anaconda3\lib\email\errors.py
> m email.feedparser          C:\Anaconda3\lib\email\feedparser.py
> m email.generator           C:\Anaconda3\lib\email\generator.py
> m email.header              C:\Anaconda3\lib\email\header.py
> m email.headerregistry      C:\Anaconda3\lib\email\headerregistry.py
> m email.iterators           C:\Anaconda3\lib\email\iterators.py
> m email.message             C:\Anaconda3\lib\email\message.py
> m email.parser              C:\Anaconda3\lib\email\parser.py
> m email.policy              C:\Anaconda3\lib\email\policy.py
> m email.quoprimime          C:\Anaconda3\lib\email\quoprimime.py
> m email.utils               C:\Anaconda3\lib\email\utils.py
> P encodings                 C:\Anaconda3\lib\encodings\__init__.py
> m encodings.aliases         C:\Anaconda3\lib\encodings\aliases.py
> m encodings.ascii           C:\Anaconda3\lib\encodings\ascii.py
> m encodings.base64_codec    C:\Anaconda3\lib\encodings\base64_codec.py
> m encodings.big5            C:\Anaconda3\lib\encodings\big5.py
> m encodings.big5hkscs       C:\Anaconda3\lib\encodings\big5hkscs.py
> m encodings.bz2_codec       C:\Anaconda3\lib\encodings\bz2_codec.py
> m encodings.charmap         C:\Anaconda3\lib\encodings\charmap.py
> m encodings.cp037           C:\Anaconda3\lib\encodings\cp037.py
> m encodings.cp1006          C:\Anaconda3\lib\encodings\cp1006.py
> m encodings.cp1026          C:\Anaconda3\lib\encodings\cp1026.py
> m encodings.cp1125          C:\Anaconda3\lib\encodings\cp1125.py
> m encodings.cp1140          C:\Anaconda3\lib\encodings\cp1140.py
> m encodings.cp1250          C:\Anaconda3\lib\encodings\cp1250.py
> m encodings.cp1251          C:\Anaconda3\lib\encodings\cp1251.py
> m encodings.cp1252          C:\Anaconda3\lib\encodings\cp1252.py
> m encodings.cp1253          C:\Anaconda3\lib\encodings\cp1253.py
> m encodings.cp1254          C:\Anaconda3\lib\encodings\cp1254.py
> m encodings.cp1255          C:\Anaconda3\lib\encodings\cp1255.py
> m encodings.cp1256          C:\Anaconda3\lib\encodings\cp1256.py
> m encodings.cp1257          C:\Anaconda3\lib\encodings\cp1257.py
> m encodings.cp1258          C:\Anaconda3\lib\encodings\cp1258.py
> m encodings.cp273           C:\Anaconda3\lib\encodings\cp273.py
> m encodings.cp424           C:\Anaconda3\lib\encodings\cp424.py
> m encodings.cp437           C:\Anaconda3\lib\encodings\cp437.py
> m encodings.cp500           C:\Anaconda3\lib\encodings\cp500.py
> m encodings.cp65001         C:\Anaconda3\lib\encodings\cp65001.py
> m encodings.cp720           C:\Anaconda3\lib\encodings\cp720.py
> m encodings.cp737           C:\Anaconda3\lib\encodings\cp737.py
> m encodings.cp775           C:\Anaconda3\lib\encodings\cp775.py
> m encodings.cp850           C:\Anaconda3\lib\encodings\cp850.py
> m encodings.cp852           C:\Anaconda3\lib\encodings\cp852.py
> m encodings.cp855           C:\Anaconda3\lib\encodings\cp855.py
> m encodings.cp856           C:\Anaconda3\lib\encodings\cp856.py
> m encodings.cp857           C:\Anaconda3\lib\encodings\cp857.py
> m encodings.cp858           C:\Anaconda3\lib\encodings\cp858.py
> m encodings.cp860           C:\Anaconda3\lib\encodings\cp860.py
> m encodings.cp861           C:\Anaconda3\lib\encodings\cp861.py
> m encodings.cp862           C:\Anaconda3\lib\encodings\cp862.py
> m encodings.cp863           C:\Anaconda3\lib\encodings\cp863.py
> m encodings.cp864           C:\Anaconda3\lib\encodings\cp864.py
> m encodings.cp865           C:\Anaconda3\lib\encodings\cp865.py
> m encodings.cp866           C:\Anaconda3\lib\encodings\cp866.py
> m encodings.cp869           C:\Anaconda3\lib\encodings\cp869.py
> m encodings.cp874           C:\Anaconda3\lib\encodings\cp874.py
> m encodings.cp875           C:\Anaconda3\lib\encodings\cp875.py
> m encodings.cp932           C:\Anaconda3\lib\encodings\cp932.py
> m encodings.cp949           C:\Anaconda3\lib\encodings\cp949.py
> m encodings.cp950           C:\Anaconda3\lib\encodings\cp950.py
> m encodings.euc_jis_2004    C:\Anaconda3\lib\encodings\euc_jis_2004.py
> m encodings.euc_jisx0213    C:\Anaconda3\lib\encodings\euc_jisx0213.py
> m encodings.euc_jp          C:\Anaconda3\lib\encodings\euc_jp.py
> m encodings.euc_kr          C:\Anaconda3\lib\encodings\euc_kr.py
> m encodings.gb18030         C:\Anaconda3\lib\encodings\gb18030.py
> m encodings.gb2312          C:\Anaconda3\lib\encodings\gb2312.py
> m encodings.gbk             C:\Anaconda3\lib\encodings\gbk.py
> m encodings.hex_codec       C:\Anaconda3\lib\encodings\hex_codec.py
> m encodings.hp_roman8       C:\Anaconda3\lib\encodings\hp_roman8.py
> m encodings.hz              C:\Anaconda3\lib\encodings\hz.py
> m encodings.idna            C:\Anaconda3\lib\encodings\idna.py
> m encodings.iso2022_jp      C:\Anaconda3\lib\encodings\iso2022_jp.py
> m encodings.iso2022_jp_1    C:\Anaconda3\lib\encodings\iso2022_jp_1.py
> m encodings.iso2022_jp_2    C:\Anaconda3\lib\encodings\iso2022_jp_2.py
> m encodings.iso2022_jp_2004 C:\Anaconda3\lib\encodings\iso2022_jp_2004.py
> m encodings.iso2022_jp_3    C:\Anaconda3\lib\encodings\iso2022_jp_3.py
> m encodings.iso2022_jp_ext  C:\Anaconda3\lib\encodings\iso2022_jp_ext.py
> m encodings.iso2022_kr      C:\Anaconda3\lib\encodings\iso2022_kr.py
> m encodings.iso8859_1       C:\Anaconda3\lib\encodings\iso8859_1.py
> m encodings.iso8859_10      C:\Anaconda3\lib\encodings\iso8859_10.py
> m encodings.iso8859_11      C:\Anaconda3\lib\encodings\iso8859_11.py
> m encodings.iso8859_13      C:\Anaconda3\lib\encodings\iso8859_13.py
> m encodings.iso8859_14      C:\Anaconda3\lib\encodings\iso8859_14.py
> m encodings.iso8859_15      C:\Anaconda3\lib\encodings\iso8859_15.py
> m encodings.iso8859_16      C:\Anaconda3\lib\encodings\iso8859_16.py
> m encodings.iso8859_2       C:\Anaconda3\lib\encodings\iso8859_2.py
> m encodings.iso8859_3       C:\Anaconda3\lib\encodings\iso8859_3.py
> m encodings.iso8859_4       C:\Anaconda3\lib\encodings\iso8859_4.py
> m encodings.iso8859_5       C:\Anaconda3\lib\encodings\iso8859_5.py
> m encodings.iso8859_6       C:\Anaconda3\lib\encodings\iso8859_6.py
> m encodings.iso8859_7       C:\Anaconda3\lib\encodings\iso8859_7.py
> m encodings.iso8859_8       C:\Anaconda3\lib\encodings\iso8859_8.py
> m encodings.iso8859_9       C:\Anaconda3\lib\encodings\iso8859_9.py
> m encodings.johab           C:\Anaconda3\lib\encodings\johab.py
> m encodings.koi8_r          C:\Anaconda3\lib\encodings\koi8_r.py
> m encodings.koi8_t          C:\Anaconda3\lib\encodings\koi8_t.py
> m encodings.koi8_u          C:\Anaconda3\lib\encodings\koi8_u.py
> m encodings.kz1048          C:\Anaconda3\lib\encodings\kz1048.py
> m encodings.latin_1         C:\Anaconda3\lib\encodings\latin_1.py
> m encodings.mac_arabic      C:\Anaconda3\lib\encodings\mac_arabic.py
> m encodings.mac_centeuro    C:\Anaconda3\lib\encodings\mac_centeuro.py
> m encodings.mac_croatian    C:\Anaconda3\lib\encodings\mac_croatian.py
> m encodings.mac_cyrillic    C:\Anaconda3\lib\encodings\mac_cyrillic.py
> m encodings.mac_farsi       C:\Anaconda3\lib\encodings\mac_farsi.py
> m encodings.mac_greek       C:\Anaconda3\lib\encodings\mac_greek.py
> m encodings.mac_iceland     C:\Anaconda3\lib\encodings\mac_iceland.py
> m encodings.mac_latin2      C:\Anaconda3\lib\encodings\mac_latin2.py
> m encodings.mac_roman       C:\Anaconda3\lib\encodings\mac_roman.py
> m encodings.mac_romanian    C:\Anaconda3\lib\encodings\mac_romanian.py
> m encodings.mac_turkish     C:\Anaconda3\lib\encodings\mac_turkish.py
> m encodings.mbcs            C:\Anaconda3\lib\encodings\mbcs.py
> m encodings.oem             C:\Anaconda3\lib\encodings\oem.py
> m encodings.palmos          C:\Anaconda3\lib\encodings\palmos.py
> m encodings.ptcp154         C:\Anaconda3\lib\encodings\ptcp154.py
> m encodings.punycode        C:\Anaconda3\lib\encodings\punycode.py
> m encodings.quopri_codec    C:\Anaconda3\lib\encodings\quopri_codec.py
> m encodings.raw_unicode_escape C:\Anaconda3\lib\encodings\raw_unicode_escape.py
> m encodings.rot_13          C:\Anaconda3\lib\encodings\rot_13.py
> m encodings.shift_jis       C:\Anaconda3\lib\encodings\shift_jis.py
> m encodings.shift_jis_2004  C:\Anaconda3\lib\encodings\shift_jis_2004.py
> m encodings.shift_jisx0213  C:\Anaconda3\lib\encodings\shift_jisx0213.py
> m encodings.tis_620         C:\Anaconda3\lib\encodings\tis_620.py
> m encodings.undefined       C:\Anaconda3\lib\encodings\undefined.py
> m encodings.unicode_escape  C:\Anaconda3\lib\encodings\unicode_escape.py
> m encodings.unicode_internal C:\Anaconda3\lib\encodings\unicode_internal.py
> m encodings.utf_16          C:\Anaconda3\lib\encodings\utf_16.py
> m encodings.utf_16_be       C:\Anaconda3\lib\encodings\utf_16_be.py
> m encodings.utf_16_le       C:\Anaconda3\lib\encodings\utf_16_le.py
> m encodings.utf_32          C:\Anaconda3\lib\encodings\utf_32.py
> m encodings.utf_32_be       C:\Anaconda3\lib\encodings\utf_32_be.py
> m encodings.utf_32_le       C:\Anaconda3\lib\encodings\utf_32_le.py
> m encodings.utf_7           C:\Anaconda3\lib\encodings\utf_7.py
> m encodings.utf_8           C:\Anaconda3\lib\encodings\utf_8.py
> m encodings.utf_8_sig       C:\Anaconda3\lib\encodings\utf_8_sig.py
> m encodings.uu_codec        C:\Anaconda3\lib\encodings\uu_codec.py
> m encodings.zlib_codec      C:\Anaconda3\lib\encodings\zlib_codec.py
> m enum                      C:\Anaconda3\lib\enum.py
> m errno                     
> m fnmatch                   C:\Anaconda3\lib\fnmatch.py
> m functools                 C:\Anaconda3\lib\functools.py
> m gc                        
> m genericpath               C:\Anaconda3\lib\genericpath.py
> m getopt                    C:\Anaconda3\lib\getopt.py
> m gettext                   C:\Anaconda3\lib\gettext.py
> m glob                      C:\Anaconda3\lib\glob.py
> m gzip                      C:\Anaconda3\lib\gzip.py
> m hashlib                   C:\Anaconda3\lib\hashlib.py
> m heapq                     C:\Anaconda3\lib\heapq.py
> P html                      C:\Anaconda3\lib\html\__init__.py
> m html.entities             C:\Anaconda3\lib\html\entities.py
> P http                      C:\Anaconda3\lib\http\__init__.py
> m http.client               C:\Anaconda3\lib\http\client.py
> m http.server               C:\Anaconda3\lib\http\server.py
> m imp                       C:\Anaconda3\lib\imp.py
> P importlib                 C:\Anaconda3\lib\importlib\__init__.py
> m importlib._bootstrap      C:\Anaconda3\lib\importlib\_bootstrap.py
> m importlib._bootstrap_external C:\Anaconda3\lib\importlib\_bootstrap_external.py
> m importlib.abc             C:\Anaconda3\lib\importlib\abc.py
> m importlib.machinery       C:\Anaconda3\lib\importlib\machinery.py
> m importlib.util            C:\Anaconda3\lib\importlib\util.py
> m inspect                   C:\Anaconda3\lib\inspect.py
> m io                        C:\Anaconda3\lib\io.py
> m ipaddress                 C:\Anaconda3\lib\ipaddress.py
> m itertools                 
> m keyword                   C:\Anaconda3\lib\keyword.py
> m linecache                 C:\Anaconda3\lib\linecache.py
> m locale                    C:\Anaconda3\lib\locale.py
> P logging                   C:\Anaconda3\lib\logging\__init__.py
> m lzma                      C:\Anaconda3\lib\lzma.py
> m marshal                   
> m math                      
> m mimetypes                 C:\Anaconda3\lib\mimetypes.py
> m msvcrt                    
> m nt                        
> m ntpath                    C:\Anaconda3\lib\ntpath.py
> m opcode                    C:\Anaconda3\lib\opcode.py
> m operator                  C:\Anaconda3\lib\operator.py
> m optparse                  C:\Anaconda3\lib\optparse.py
> m os                        C:\Anaconda3\lib\os.py
> m pdb                       C:\Anaconda3\lib\pdb.py
> m pickle                    C:\Anaconda3\lib\pickle.py
> m pkgutil                   C:\Anaconda3\lib\pkgutil.py
> m platform                  C:\Anaconda3\lib\platform.py
> m plistlib                  C:\Anaconda3\lib\plistlib.py
> m posixpath                 C:\Anaconda3\lib\posixpath.py
> m pprint                    C:\Anaconda3\lib\pprint.py
> m py_compile                C:\Anaconda3\lib\py_compile.py
> m pydoc                     C:\Anaconda3\lib\pydoc.py
> P pydoc_data                C:\Anaconda3\lib\pydoc_data\__init__.py
> m pydoc_data.topics         C:\Anaconda3\lib\pydoc_data\topics.py
> m pyexpat                   C:\Anaconda3\DLLs\pyexpat.pyd
> m quopri                    C:\Anaconda3\lib\quopri.py
> m random                    C:\Anaconda3\lib\random.py
> m re                        C:\Anaconda3\lib\re.py
> m reprlib                   C:\Anaconda3\lib\reprlib.py
> m select                    C:\Anaconda3\DLLs\select.pyd
> m selectors                 C:\Anaconda3\lib\selectors.py
> m shlex                     C:\Anaconda3\lib\shlex.py
> m shutil                    C:\Anaconda3\lib\shutil.py
> m signal                    C:\Anaconda3\lib\signal.py
> m socket                    C:\Anaconda3\lib\socket.py
> m socketserver              C:\Anaconda3\lib\socketserver.py
> m sre_compile               C:\Anaconda3\lib\sre_compile.py
> m sre_constants             C:\Anaconda3\lib\sre_constants.py
> m sre_parse                 C:\Anaconda3\lib\sre_parse.py
> m ssl                       C:\Anaconda3\lib\ssl.py
> m stat                      C:\Anaconda3\lib\stat.py
> m string                    C:\Anaconda3\lib\string.py
> m stringprep                C:\Anaconda3\lib\stringprep.py
> m struct                    C:\Anaconda3\lib\struct.py
> m subprocess                C:\Anaconda3\lib\subprocess.py
> m sys                       
> m tarfile                   C:\Anaconda3\lib\tarfile.py
> m tempfile                  C:\Anaconda3\lib\tempfile.py
> m testexe__init__           C:\Anaconda3\lib\site-packages\cx_Freeze\initscripts\Console.py
> m testexe__main__           testExe.py
> m textwrap                  C:\Anaconda3\lib\textwrap.py
> m threading                 C:\Anaconda3\lib\threading.py
> m time                      
> m token                     C:\Anaconda3\lib\token.py
> m tokenize                  C:\Anaconda3\lib\tokenize.py
> m traceback                 C:\Anaconda3\lib\traceback.py
> m tracemalloc               C:\Anaconda3\lib\tracemalloc.py
> m tty                       C:\Anaconda3\lib\tty.py
> m types                     C:\Anaconda3\lib\types.py
> m unicodedata               C:\Anaconda3\DLLs\unicodedata.pyd
> P unittest                  C:\Anaconda3\lib\unittest\__init__.py
> m unittest.case             C:\Anaconda3\lib\unittest\case.py
> m unittest.loader           C:\Anaconda3\lib\unittest\loader.py
> m unittest.main             C:\Anaconda3\lib\unittest\main.py
> m unittest.result           C:\Anaconda3\lib\unittest\result.py
> m unittest.runner           C:\Anaconda3\lib\unittest\runner.py
> m unittest.signals          C:\Anaconda3\lib\unittest\signals.py
> m unittest.suite            C:\Anaconda3\lib\unittest\suite.py
> m unittest.util             C:\Anaconda3\lib\unittest\util.py
> P urllib                    C:\Anaconda3\lib\urllib\__init__.py
> m urllib.parse              C:\Anaconda3\lib\urllib\parse.py
> m uu                        C:\Anaconda3\lib\uu.py
> m warnings                  C:\Anaconda3\lib\warnings.py
> m weakref                   C:\Anaconda3\lib\weakref.py
> m webbrowser                C:\Anaconda3\lib\webbrowser.py
> m winreg                    
> P xml                       C:\Anaconda3\lib\xml\__init__.py
> P xml.parsers               C:\Anaconda3\lib\xml\parsers\__init__.py
> m xml.parsers.expat         C:\Anaconda3\lib\xml\parsers\expat.py
> m zipfile                   C:\Anaconda3\lib\zipfile.py
> m zipimport                 
> m zlib                      
> 
> Missing modules:
> ? __main__ imported from bdb, pdb
> ? _dummy_threading imported from dummy_threading
> ? _frozen_importlib imported from importlib, importlib.abc
> ? _frozen_importlib_external imported from importlib, importlib._bootstrap, importlib.abc
> ? _posixsubprocess imported from subprocess
> ? _winreg imported from platform
> ? grp imported from shutil, tarfile
> ? java.lang imported from platform
> ? org.python.core imported from copy, pickle
> ? os.path imported from os, pkgutil, py_compile, tracemalloc, unittest, unittest.util
> ? posix imported from os
> ? pwd imported from http.server, posixpath, shutil, tarfile, webbrowser
> ? termios imported from tty
> ? vms_lib imported from platform
> This is not necessarily a problem - the modules may not be needed on this platform.
> 
> copying C:\Anaconda3\DLLs\_bz2.pyd -> build\exe.win-amd64-3.6\lib\_bz2.pyd
> copying C:\Anaconda3\DLLs\_hashlib.pyd -> build\exe.win-amd64-3.6\lib\_hashlib.pyd
> copying C:\Anaconda3\api-ms-win-crt-utility-l1-1-0.dll -> build\exe.win-amd64-3.6\api-ms-win-crt-utility-l1-1-0.dll
> copying C:\Anaconda3\DLLs\_lzma.pyd -> build\exe.win-amd64-3.6\lib\_lzma.pyd
> copying C:\Anaconda3\DLLs\_socket.pyd -> build\exe.win-amd64-3.6\lib\_socket.pyd
> copying C:\Anaconda3\DLLs\_ssl.pyd -> build\exe.win-amd64-3.6\lib\_ssl.pyd
> copying C:\Anaconda3\DLLs\pyexpat.pyd -> build\exe.win-amd64-3.6\lib\pyexpat.pyd
> copying C:\Anaconda3\DLLs\select.pyd -> build\exe.win-amd64-3.6\lib\select.pyd
> copying C:\Anaconda3\DLLs\unicodedata.pyd -> build\exe.win-amd64-3.6\lib\unicodedata.pyd
>

**Comment by klensy** [comment]
@johnny1496 
>cx_freeze 5.0 (current) on windows 10

is this version from pip or from master branch git (6.x version)?

**Comment by johnny1496** [comment]
It is from pip:

"python -m pip install cx_Freeze --upgrade"

**Comment by klensy** [comment]
Latest version (as i checked now) 6.0b1 in pip

**Comment by johnny1496** [comment]
Ok thanks I will try and get that.

**Comment by jaschau** [comment]
I'm seeing the same behaviour with the latest version 6.0b1 in pip.
I am using anaconda 4.3.30, Python 3.6.3 and Windows 10.
I previously saw the same behaviour using version 5.1.
I should note that I am a conda virtualenv.

Interestingly, I am seeing the same behaviour with a virtualenv under Linux, using Python 3.5.2 and cx_Freeze 5.1.

**Comment by 0x4950** [comment]
I encountered the same problem yesterday while working on a different Windows 10 machine but with the same python files. I re-downloaded Python 3.6.3 and installed it. Then I got the package from pypi (cx_Freeze-6.0b1-cp36-cp36m-win32.whl) and installed it. I first uninstalled version 5.1 through pip and then installed 6. I think this specific file that I mention above though is for 32bit and for Python version 6.3. I am not sure if it was the Python re-installation or the cx_freeze v.6 but it made the error go away for me. Hope it helps.

**Comment by jaschau** [comment]
@melanoleucos I assume you have been using the python from python.org?

**Comment by 0x4950** [comment]
Yes

**Comment by slevon** [comment]
Hi,
I have the same Problem using the latest MiniConda3 (Python 3.6.3) and the latest cx_freeze installed via pip.

**Comment by jtyates2430** [comment]
Hello,

Same problem here. setup.py builds correctly but 'No Module Named Codecs' error (error from__init__.py in line 31) when running the executable. Running Python 3.6.2 (Anaconda) with cx_Freeze 5.1 installed with conda on a Windows 7 64-bit OS.

Any thoughts are much appreciated.

**Comment by anthony-tuininga** [comment]
I'll take a look at it. It seems something strange is going on. I'll report back here once I figure out the issue.

**Comment by jaschau** [comment]
If it helps, I briefly tried with version 5.0.1. It also stopped with a different error what seemed to be a cx_freeze error, complaining about missing main__init__ function, if I remember correctly.
I don't know if that indicates that it potentially got past the Python initialization step in that version...

**Comment by anthony-tuininga** [comment]
This issue may be resolved by the latest commit. See issues #324 and #325.

**Comment by slevon** [comment]
Hi,
I can confirm, that the issue ist fixed for me.
Thanks a lot!
Cheers!
