### ISSUE TITLE
Bug Repro: Hanging thread on dynamic imports using cx_Freeze 5.0.2

### ISSUE THREAD

**Issue by azuring2** [marcelotduarte/cx_Freeze#312]
There is one bug closed for thread hanging on dynamic imports, and then closed for 5.0.2.
https://github.com/anthony-tuininga/cx_Freeze/issues/270

But I find the bug still  repo in some multi-threading cases for 5.0.2.  For instance, i use urllib2.urlopen (there is one dynamic "import types"  in the urlopen function), then the urlopen thread pauses to wait the import ending.

The eviroment is python 2.7, pyside, 32bit, windows 7.

I will post the minimum repro code later if I have time.

**Comment by anthony-tuininga** [comment]
Please re-open if you can provide code to reproduce this issue. Thanks!
