### ISSUE TITLE
Exe detected as Malware

### ISSUE THREAD

**Issue by Frostie2** [marcelotduarte/cx_Freeze#315]
Every exe compiled with cx_Freeze 5.0.2 is detected as malware and will removed. It seems that it doesn’t matter what code it is, every exe seems to be malware.

—Info—
Windows 10 64 Bit
Python 3.6.2 (64 Bit)
AntiVirus software: Symantec Endpoint Protection

It seems that there was no problem with cx_Freeze 4.3 but it’s too old and it’s hard to change the code that it’s working with this version.

**Comment by klensy** [comment]
https://www.virustotal.com/ ?

**Comment by Frostie2** [comment]
![fdf0f59b-86b5-4b68-8f5e-8f2b569e79c9](https://user-images.githubusercontent.com/27697591/31074661-fb79fe98-a771-11e7-89a5-361f33a2806b.png)
![162d21be-73f1-45b5-81f0-d1e642132eb2](https://user-images.githubusercontent.com/27697591/31074660-fb672e3a-a771-11e7-8c74-24f75d98e413.png)
![b9a3e35d-1108-49ff-a7cd-fc3ff52eed10](https://user-images.githubusercontent.com/27697591/31074659-fb6617b6-a771-11e7-8ecf-dbe226cb6d86.png)

My results

**Comment by klensy** [comment]
Link to results will be better, i think.

**Comment by Frostie2** [comment]
https://www.virustotal.com/#/file/d3c3e56a5d29af44487767620ea6d6f5f643d82f8bba2ae64b9b52504d4250bd/details

**Comment by anthony-tuininga** [comment]
Is this still an issue? Can you try one of the samples?

**Comment by rocha6464** [comment]
Scripts compiled with cx-freeze 5.1 are detected as malware by Symantec Endpoint Protection and Emsisoft Anti-malware. The errant file seems to be win32gui.exe.

I am running  python 3.6.1. I uninstalled cx-freeze, and re-installed using "python -m pip install cx-freeze --upgrade". Emsisoft promptly popped up - log extract below:

Found "Trojan.GenericKD.6284204 (B)" in "Win32GUI.exe" -> Quarantined by rule

**Comment by anthony-tuininga** [comment]
I don't have this problem myself. Are you able to build yourself?

**Comment by rocha6464** [comment]
It has been fixed. Repeating the cx-freeze installation steps now results in an installation of cx-freeze 5.1.1. 

Emsisoft Anti-Malware does not flag any malware now.

Thank you!

**Comment by Frostie2** [comment]
Thank you for your help!

________________________________

**Comment by eeyrjmr** [comment]
I am starting to hit this issue as well.

The royally annoying thing about this some old bundles of mine (using 4.3.3 and py3.4, 32bit) are being deleted. Equally a recent build using 4.3.4 + py3.4 + 64bit was getting deleted but a 32bit build was not.

This is via Symantec Endpoint Protection and it is being flagged up by its Heuristic detection

**Comment by abinjohnthomas** [comment]
I got the same issue. This happened when I tried to install the package. 
Here is the error by mccaffe
abin ran C:\Python36\python.exe, which attempted to access C:\Users\abin\AppData\Local\Temp\pycharm-packaging\cx-Freeze\cx_Freeze\bases\Win32GUI.exe. The Trojan named Artemis!1CEA939252D9 was detected and deleted.

**Comment by SauloRocha** [comment]
I fixed the problem, stopping use anaconda and installing the required packages direct to python.

**Comment by eeyrjmr** [comment]
that isn't a "fix"...
I faced this using python and installing the needed packages.
I contacted Symantec to whitelist an example program

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by AndreyLomov** [comment]
Hi all,
I have faced with the same issue for versions 6.1 and 6.2 also.  In order to reproduce you can just test Console.exe from Python\Python38\Lib\site-packages\cx_Freeze\bases at www.virustotal.com
Then you can see notification from one of antivirus app: 
https://www.virustotal.com/gui/file/29d0fc92c952cf40b8fc2381f4b2aabdac6dab17a152a0379ae7cf7b07ae702e/detection

**Comment by klensy** [comment]
@AndreyLomov I assume, that you used prebuild packages from pypi? You can try to build cx_Freeze by yourself from git using different compilers.

**Comment by marcelotduarte** [comment]
I created an extension function to update the PE checksum. I discovered that with MSVC installed in GitHub CI generates a zero checksum. In my machine with Mingw the checksum is correct, but if I add an icon, it should be updated, so this function fix it in all cases.
I released a new beta, please try it out.
pip install cx-Freeze==6.7b1

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
