### ISSUE TITLE
Windows service executable missing in distribution (reopen)

### ISSUE THREAD

**Issue by archivgmbh** [marcelotduarte/cx_Freeze#316]
Wolfgang L. created an issue 2015-06-16

The windows service executable "Win32Service.exe" (part of bases) is missing in the Python 2.7 wheel distribution set. (also in every other binary distribution for Windows)

This needs a dependency to cx-logging to build and run. Could be this is not installed on the build machine.

Think best for long term is to remove the dependency to cx-logging, it seems unmaintained and this dependency is complicated to handle for a build.

**Comment by archivgmbh** [comment]
Win32Service.exe is still missing in version 5.0.2 for Python 3.6

**Comment by klensy** [comment]
>Win32Service.exe is still missing in version 5.0.2 for Python 3.6

v5.x branch for 2.x python. If u use 3.6, try to pull master.

**Comment by anthony-tuininga** [comment]
I just made a 5.1 and 6.0b1 release. Both of them contain the Win32Service.exe base.
