### ISSUE TITLE
Not take in account auto-start for service

### ISSUE THREAD

**Issue by jcrochet-ugloo** [marcelotduarte/cx_Freeze#318]
Hi, 

We are using cx_freeze to generate msi of python module as service.

When using 5.0.2 : auto-start of service after installation.

When using master (6.0b1), service is stopped after installation. Our service manualy start fine.

I think there is a regression on master.

**Comment by anthony-tuininga** [comment]
This is a configuration item. Take a look at the sample for how to set it: https://github.com/anthony-tuininga/cx_Freeze/blob/6.0b1/cx_Freeze/samples/service/Config.py

**Comment by jcrochet-ugloo** [comment]
Hi, 

We already use a config file, but "AUTO_START = True" is not take in account when we generate a msi.

It took in account in 5.0.2.
