### ISSUE TITLE
ImportError: No module named 'zope'

### ISSUE THREAD

**Issue by normanfeltz** [marcelotduarte/cx_Freeze#319]
Hello,

I have coding a application with WAMP.WS (Autobahn & Twisted), i want to compile the programe in exe.

setup.py
```
import sys, os
from cx_Freeze import setup, Executable
 
exe = Executable(
	script = "recv.py",
	targetName='LiveSceneManager.exe'
)

setup(
	name = "LiveSceneManager",
	version = "1.0",
	description = "LiveSceneManager",
	author = "Norman FELTZ",
	executables = [exe]
)
```

Build log: https://hastebin.com/figipiyowa.tex
Error at start of exe: https://hastebin.com/abotafuduj.tex
I am on Windows 7 32 bit, and i use Python 3.5.4

Cordialy

Norman FELTZ

**Comment by klensy** [comment]
Try to add zope to imported packages
```
setup(
...
options={"build_exe": {"packages": ["zope"]}},
...
)
```

**Comment by anthony-tuininga** [comment]
Take a look at the sample specifically for zope: https://github.com/anthony-tuininga/cx_Freeze/tree/6.0b1/cx_Freeze/samples/zope

**Comment by anthony-tuininga** [comment]
Please re-open with sample code if that doesn't help.

**Comment by normanfeltz** [comment]
I have add:

```
setup(
...
options={"build_exe": {"packages": ["zope"]}},
...
)
```

And create a empty file init.py in zope folder

**Comment by delijati** [comment]
Run into the same problem namespace packages have no `__init__.py`  [1]  this probably prevents cx_freeze from finding the package.

[1] https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages

**Comment by marcelotduarte** [comment]
You are using your code like the previously mentioned sample?
```
options = {
    'build_exe': {
        'namespace_packages': ['zope']
    }
}
```

**Comment by delijati** [comment]
@marcelotduarte yes i still need to add a `__init__.py` to get it working

**Comment by marcelotduarte** [comment]
I do a test with the sample at:
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/zope
To test, I installed it in a virtual env.
Python 3.7.5 32 bit
Installed twisted and cx-freeze
And it runs.

It uses namespace_packages not packages (I already mentioned that).
The complete setup.py:
```
from cx_Freeze import setup, Executable

options = {
    'build_exe': {
        'namespace_packages': ['zope']
    }
}

executables = [
    Executable('qotd.py')
]

setup(name='QOTD sample',
      version='1.0',
      description='QOTD sample for demonstrating use of namespace packages',
      options=options,
      executables=executables
      )
```

**Comment by marcelotduarte** [comment]
@delijati 
cx_Freeze 6.2 has just been released with namespace detection. Please, try it.
