### ISSUE TITLE
Release 6.0b1 on pypi

### ISSUE THREAD

**Issue by Toilal** [marcelotduarte/cx_Freeze#320]
Many issues are fixed in development branch, maybe it's time to release the beta version on pipy ?

**Comment by anthony-tuininga** [comment]
Yes, and a new release on the 5.0.x branch is also worthwhile. I have been away for most of the past month but hope to get a chance to get back to cx_Freeze more in the next couple of weeks!

**Comment by anthony-tuininga** [comment]
Done. :-)
