### ISSUE TITLE
sys.getfilesystemencoding() returns None

### ISSUE THREAD

**Issue by rhaxton** [marcelotduarte/cx_Freeze#323]
On Ubuntu 16.0.4 with anaconda 5.0.1 and cx_Freeze 5.1, the following code:

test.py:

```
#!/usr/bin/env python
import sys
print sys.getfilesystemencoding()
print sys.getdefaultencoding()
print sys.api_version
```

setup.py:

```
from cx_Freeze import setup, Executable, hooks

base = None
executables = [
    Executable('./test.py',
               base=base,
               targetName='test.exe'), ]


setup(name="Test",
      version="1.0.0",
      description="Test",
      executables=executables, )
```
prints:
None
ascii
1013

when run from test.exe

rather than:
UTF-8
ascii
1013

when run as ./test.py

I have no idea why, but it breaks at least numpy and my code as well that expects to be able to get the correct encoding.

**Comment by rhaxton** [comment]
I have confirmed that this does not occur with version 5.0 on the pip repository:

pip install cx_freeze==5.0

will result in the above test passing

versions 5.0.1 and 5.0.2 from pip also pass

**Comment by anthony-tuininga** [comment]
Can you try with the latest code on master (assuming you are using Python 3.x) or the latest code on v5.x? I don't have Ubuntu but on my Fedora box it behaves as expected.

**Comment by rhaxton** [comment]
I have confirmed that the  v5.x branch passes this test.   Was this somehow related to #324 and #325 ?

**Comment by Tedezed** [comment]
```
import sys, encodings

reload(sys)
sys.setdefaultencoding('UTF8')
sys.getfilesystemencoding = lambda: 'UTF-8'

print sys.getfilesystemencoding()
print sys.getdefaultencoding()
print sys.api_version
```

**Comment by marcelotduarte** [comment]
@Tedezed Why did you post this code in old python?
