### ISSUE TITLE
6.0b1 PyQt5 dll not found

### ISSUE THREAD

**Issue by dhenryFabrice** [marcelotduarte/cx_Freeze#328]
Hi,

I have some issue with PyQt5 since the DLL do not seems to be "loadable":
from PyQt5 import QtCore, QAxContainer
ImportError: DLL load failed: Le module spécifié est introuvable.

I'm using python 3.6.

Is this due to a bug or do I need to set things differently as before?

Best regards.

**Comment by dhenryFabrice** [comment]
If found a work around: the DLL where not found when the exe was started from a different folder than the exe location, so I added thoses lines:

if getattr(sys, 'frozen', False):
    basedir = os.path.dirname(sys.executable)
else:
    basedir = os.path.dirname(__file__)
os.chdir(basedir) #---> it failes to find PyQt when freezed if the process is not located in the exe folder 


Best regards

**Comment by anthony-tuininga** [comment]
I believe I have corrected this issue and potentially other similar ones. I have also added a sample for PyQt5.

**Comment by dhenryFabrice** [comment]
Hi,

Yes this one works well, I do not need the workaround anymore!

Many thanks!

**Comment by anthony-tuininga** [comment]
You're welcome. cx_Freeze 5.1.1 was just released with this fix included in it. A corresponding release for 6.0 will be released soon as well. I'd like to address one other issue first.

**Comment by Siecje** [comment]
I'm just curious, why was the atexit include required?

https://github.com/anthony-tuininga/cx_Freeze/commit/cebdef5f65e260b3425755e356208b818806af97#diff-6c1471b0fbc40b4475afeb6014e6e276R23
