### ISSUE TITLE
Build broken in 5.x branch with Python 3.4: Py_DecodeLocale doesn't exist

### ISSUE THREAD

**Issue by dcolascione** [marcelotduarte/cx_Freeze#329]
Py_DecodeLocale is part of a backported change from 6.x to 5.x for setting up sys.path. AIUI, 5.x is still supposed to support Python 3.4, but it doesn't build with 3.4 due to the Py_DecodeLocale use.

**Comment by anthony-tuininga** [comment]
cx_Freeze 5.0 supported 3.4, but cx_Freeze 5.1 is not intended to do so. It supports 2.7 and 3.5 and higher. I've clarified the README on the v5.x branch.
