### ISSUE TITLE
Mac OSX ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by rhaxton** [marcelotduarte/cx_Freeze#330]
On Mac OSX 10.12, with the following test case:

file.py:

```
import weakref

def main():
    print dir(weakref)
    print "Hello World"

if __name__ == "__main__":
    main()
```

setup.py:
```

"""
This is the build configuration file
for cx_freeze on macosx
"""
import os
import sys
from cx_Freeze import setup, Executable, hooks

# Dependencies are automatically detected, but it might need fine tuning.
options = {
    'build_exe': {
        'silent': False,
        'includes': [],
        'excludes': [],
        'path': sys.path,
        'include_files': [],
        'packages': [],
        'bin_includes': [],
    },
    'bdist_mac': {
        'bundle_name': "test_cx",
    },
}

base = None
executables = [
    Executable(os.path.join('.', 'file.py'), base=base, targetName='test_cx.exe'),
]

setup(name="test_cx",
      version="1.0",
      description="test_cx",
      options=options,
      executables=executables)
```

When I use the stock install of anaconda 5.0.1 for python 2.7 and a pip install cx_Freeze==5.0.2, and I run file.py from the command line:
```
python file.py
```
I get
```
['CallableProxyType', 'KeyedRef', 'ProxyType', 'ProxyTypes', 'ReferenceError', 'ReferenceType', 'UserDict', 'WeakKeyDictionary', 'WeakSet', 'WeakValueDictionary', '_IterationGuard', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_remove_dead_weakref', 'getweakrefcount', 'getweakrefs', 'proxy', 'ref']
Hello World
```
When I freeze this with `python setup.py build` and run the test_cx.exe from the command line, I get:
```
Traceback (most recent call last):
  File "/Users/rhaxton/anaconda2/lib/python2.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/Users/rhaxton/anaconda2/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "./file.py", line 1, in <module>
  File "/Users/rhaxton/anaconda2/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

If I install the stock anaconda 4.4.0 for python 2.7 and cx_Freeze 5.0.2,  I get the following from the command line (python file.py):
```
['CallableProxyType', 'KeyedRef', 'ProxyType', 'ProxyTypes', 'ReferenceError', 'ReferenceType', 'UserDict', 'WeakKeyDictionary', 'WeakSet', 'WeakValueDictionary', '_IterationGuard', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'getweakrefcount', 'getweakrefs', 'proxy', 'ref']
Hello World
```
If I then freeze it and run the exe:
```
['CallableProxyType', 'KeyedRef', 'ProxyType', 'ProxyTypes', 'ReferenceError', 'ReferenceType', 'UserDict', 'WeakKeyDictionary', 'WeakSet', 'WeakValueDictionary', '_IterationGuard', '__all__', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', 'getweakrefcount', 'getweakrefs', 'proxy', 'ref']
Hello World
```
In the second case, the _remove_dead_weakref symbol does not appear in either run.
It seems that the additional symbol was added in response to python issue [#28427](https://bugs.python.org/issue28427). I do not have any clue why it would affect cx_Freeze.

This behavior is the same with the head of the cx_Freeze 5.x branch as well

**Comment by rhaxton** [comment]
I can confirm that when the stock anaconda 5.0.1 distribution is installed, and then the python is downgraded with `conda install python==2.7.13`, then the above test works.

**Comment by anthony-tuininga** [comment]
Thanks for the detailed explanation. I don't have a Mac to play with, but it suggests that perhaps you built cx_Freeze with a different version of Python than you are actually using to perform the freezing process? That would explain this sort of behaviour. In other words, after installing anaconda, then build and install cx_Freeze, then build your frozen executable. That should work for you.

**Comment by rhaxton** [comment]
@anthony-tuininga Yes, you are correct.  The console application defines these symbols, so swapping anaconda builds and then "pip install ." on cx_freeze can cause a lot of trouble.

The solutions is to make sure to clean and rebuild cx_freeze before installing on a new version.
