### ISSUE TITLE
win32/types.pyd error : 6.0b1 win7 and win10

### ISSUE THREAD

**Issue by dhenryFabrice** [marcelotduarte/cx_Freeze#332]
Hello,

When win32com is imported, cx_Freeze put types.pyd from win32 at the root of the folder which seems to interferes with the type module and produce the error:
from types import MappingProxyType
ImportError: cannot import name 'MappingProxyType'
Since types.pyd is already in lib\win32, I do not understand why it is needed at the root folder.

I have the same issue with cx_Freeze 5.1.

Best regards

**Comment by anthony-tuininga** [comment]
I just pushed a commit that should resolve this issue. Please give it a try and let me know if it works for you, too.

**Comment by dhenryFabrice** [comment]
Hi,

Many thanks for helping!
Not yet :-(
types.pyd is not copied at the root folder anymore but, I get an error 

C:\Users\dhenry\PycharmProjects\sog-packages\client_3DBat\packaging\cx_Freeze\bu
ild\exe.win-amd64-3.6>3Dbat.exe
Traceback (most recent call last):
  File "C:\Users\dhenry\AppData\Local\Programs\Python\Python36\lib\site-packages
\cx_freeze-6.0b1-py3.6-win-amd64.egg\cx_Freeze\initscripts\__startup__.py", line
 14, in run
    module.run()
  File "C:\Users\dhenry\AppData\Local\Programs\Python\Python36\lib\site-packages
\cx_freeze-6.0b1-py3.6-win-amd64.egg\cx_Freeze\initscripts\Console.py", line 26,
 in run
    exec(code, m.__dict__)
  File "C:\Users\dhenry\PycharmProjects\sog-packages\client_3DBat\client_3DBat\_
_main__.py", line 17, in <module>
    wb = excel.Workbooks.Add()
  File "c:\temp\gen_py\3.6\00020813-0000-0000-C000-000000000046x0x1x7\Workbooks.
py", line 34, in Add
    ret = self._oleobj_.InvokeTypes(181, LCID, 1, (13, 0), ((12, 17),),Template
AttributeError: module 'win32.com.client' has no attribute 'VARIANT'
