### ISSUE TITLE
Creating virtualenv from frozen app gives Fatal Python error: Py_Initialize: Unable to get the locale encoding

### ISSUE THREAD

**Issue by ronpandolfi** [marcelotduarte/cx_Freeze#334]
Running 6.0b1, in a frozen build_exe build on linux, I tried to create a virtualenv from within the frozen application with `virtualenv.create_environment`. This causes the error:

```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f7666022380 (most recent call first):
ERROR: The executable /home/rp/.config/xicam/venvs/default/bin/Xi-cam is not functioning
ERROR: It thinks sys.prefix is '/home/rp/PycharmProjects/xi-cam2/xicam' (should be '/home/rp/.config/xicam/venvs/default')
ERROR: virtualenv is not compatible with this system or executable
```

The encodings package is actually in the build/lib directory, but virtualenv seems to crash at virtualenv.py:1393
```norm_home_dir = norm_home_dir.decode(sys.getfilesystemencoding())```

**Comment by anthony-tuininga** [comment]
You're trying to create a virtual environment from within the frozen application? You're probably going to need to understand the internals of virtualenv to make that work. Good luck!

**Comment by ronpandolfi** [comment]
I've asked the virtualenv board, in case anyone else has this question: https://github.com/pypa/virtualenv/issues/1114
