### ISSUE TITLE
Missing application information (name/version/description)

### ISSUE THREAD

**Issue by MaurizioB** [marcelotduarte/cx_Freeze#335]
It looks that version information are missing in the compiled EXE file, at least since version 5.
I used an old 4.3.4 version with python2.7, which still creates the resource information, while any version I could try after 5.0 does not create any.

This is the test script I used:
```
from cx_Freeze import setup, Executable

buildOptions = dict(packages = [], excludes = [], includes = ['atexit'])

import sys
base = 'Win32GUI' if sys.platform=='win32' else None

executables = [
    Executable('test.py', base=base)
]
setup(name='My test program',
      version = '0.5.5',
      description = 'Simple test program',
      options = dict(build_exe = buildOptions),
      executables = executables)
```
Result from 4.3.4 and python 2.7
![cx434](https://user-images.githubusercontent.com/523596/33790794-ab4b4502-dc83-11e7-8204-06319abc68f2.jpg)
Result from 5.0.2 and python 3.4
![cx502](https://user-images.githubusercontent.com/523596/33790795-ab636df8-dc83-11e7-8f9b-96f52a3cd12b.jpg)

**Comment by anthony-tuininga** [comment]
I just tried with cx_Freeze 5.1 and it works as expected. You will get a warning message, however, if the pywin32 extensions are not installed. Is that the case for you?

**Comment by MaurizioB** [comment]
Thanks, I must have installed it somehow with cx_Freeze 4 and forgot about that.
The warning is actually there, but since it's at the beginning, it got lost in the subsequent logging.
I thought that the pip-provided pywin32 was enough, but I was wrong. I successfully installed it on windows, and building correctly creates the resource. Unfortunally I am not able to install pywin32 on wine (there's a problem with the installer), which is a pity.
