### ISSUE TITLE
Windows: The .exe crashes ("... has stopped working") with no details

### ISSUE THREAD

**Issue by gustavklopp** [marcelotduarte/cx_Freeze#336]
I've run the same setup on Linux and macOS without problem. 

The problem is with Windows 7.

The exe is produced but launching it produces: 

```
"... has stopped working"
Problem details:  
APPCRASH
Fault module name: ucrtbase.DLL
Exception code: 40000015
```

My setup.py

```python
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need
# fine tuning.
buildOptions = dict(
        packages = [
            'builtins',
            'sys',
            ...
            'allauth.account.auth_backends',
            ], 
        excludes = ['tkinter',],
        include_files = ['LingL_database.sqlite3']
        )

import sys
base = 'Win32GUI' if sys.platform=='win32' else None

executables = [
    Executable('LingL.py', base=base)
]

setup(name='LingL',
      version = '0.1',
      description = '',
      options = dict(build_exe = buildOptions),
      executables = executables)
```

I've tried to run some samples from the cx_Freeze repo like `simple` and the exe is working without crashes.
Thanks a lot!

**Comment by gustavklopp** [comment]
I've upgraded to version  6 and everything works perfectly! 
Thanks for this amazing program! I can release for Linux, Windows and macOS for python 3.6 and Django 1.11! Amazing!!

**Comment by peiseng** [comment]
May I know why do you exclude the "tkinter"? If i need to import "tkinter" in my code, i should not exclude right?

**Comment by gustavklopp** [comment]
That's a long time ago... I guess it was crashing the program beacause I didn't add the libraries for tkinter (like in https://stackoverflow.com/questions/43059408/how-to-include-tkinter-when-using-cx-freeze-to-convert-script-to-exe/43071342). And since I wasn't using it, I've simply excluded it.
