### ISSUE TITLE
[PyQt5][Python3.6] '...could not find or load the Qt platform plugin "windows" in ""'

### ISSUE THREAD

**Issue by oudent** [marcelotduarte/cx_Freeze#339]
Using Anaconda 5.0.1 (64bit) [Env = Python 3.6.3, PyQt5.6.0, Pandas, Numpy, etc], with cx_Freeze 6.0b1  on Windows 10

Freeze seems to finish ok, but when I run the exe, it gives me this error:

> This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".  

> Reinstalling the application may fix this problem.

Here is my setup file:
``application_title = "My App's Name"
main_python_file = "MyApp.py" 

```
import sys, os.path

from cx_Freeze import setup, Executable

base = None

includeFiles = ['config.yml', 'RELEASE_NOTES.txt']  # extra files I need
includes = ["atexit","re"]
excludes = ["tkinter", "PyQt5.uic"] # get an error without this
packages = ["numpy", "pandas", "yaml", "PyQt5.QtCore", "PyQt5.QtGui", "PyQt5.QtWidgets"]

os.environ['TCL_LIBRARY'] = r'C:\ProgramData\Anaconda3\tcl\tcl8.6'  # fix for TCL bug
os.environ['TK_LIBRARY'] = r'C:\ProgramData\Anaconda3\tcl\tk8.6'

setup(
        name = application_title,
        version = "1.5",
        description = "",
        author = "Me",
        author_email = "my@email.com",
        options = {"build_exe" : {"packages":packages, "include_files":includeFiles, "includes" : includes , "excludes":excludes}},
        executables = [Executable(main_python_file, base = base)])
```
		
Please tell me I'm doing something stupid, I'm on day 3 of trying to recover after my virus scanner started quarantining my previous exe made with PyInstaller...and now I can't even get PyInstaller working again. I've also switched to Anaconda instead of just installing everything separately. Maybe that's the issue?

**Comment by anthony-tuininga** [comment]
You can try with cx_Freeze 5.1.1 (just released) or wait until cx_Freeze 6.0b2 is released (soon).

**Comment by oudent** [comment]
Thanks Anthony. Same error with 5.1.1

**Comment by oudent** [comment]
I uninstalled Anaconda, and installed Python3==3.6.4, PyQt5==5.8, cx-Freeze==5.0.1, etc. 

Used the script above successfully, plus got it working using the following template (I like this template): https://bitbucket.org/Odoth/pyqt5-template/src

The issue seemed to be related to Anaconda, or maybe a combination of versions.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by thierryBottaro** [comment]
I have the same problem with python 3,7,0, PYQt5 = 5.9.2, cx-Freeze=6,2  with ANACONDA (and Anaconda seems to be the problem)
I also have Anaconda, I re-installed it with the last Version 2020.02, no change.

I even tried the template Oudent propose (and the new URL is : )
https://github.com/Odoth/pyqt5-template
this template does not work by me....

Winand point at the solution in https://github.com/marcelotduarte/cx_Freeze/issues/631
