### ISSUE TITLE
Compatibility with VPython (module) HEEELP ME I AM DESPERATE PLEASE

### ISSUE THREAD

**Issue by mohamed-tayeh** [marcelotduarte/cx_Freeze#344]
Hello!
I am currently creating a projectile motion simulation using tkinter and VPython, however I am struggling to convert it to an exe file using cx_freeze. I have attached my setup.py file and an example simulation (as text files) onto this comment.
I have been searching for ages and asked several questions on stackoverflow. It is probably an easy fix, if you can help me that would be very much appreciated from the bottom of my <3
[Test Program.txt](https://github.com/anthony-tuininga/cx_Freeze/files/1608599/Test.Program.txt)
[setup.txt](https://github.com/anthony-tuininga/cx_Freeze/files/1608600/setup.txt)

**Comment by anthony-tuininga** [comment]
Can you provide what errors you are getting? And the versions of the software you are using?

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
