### ISSUE TITLE
On re installation of software antivirus detects as Trojan 

### ISSUE THREAD

**Issue by vegabird** [marcelotduarte/cx_Freeze#345]
Hi,
I am using Python Version 3.6 and cx_freeze 5.1.1 , while re-installing the software the antivirus detects it as Trojan.
There is no detection of Trojan or malware on first installation and in .exe

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
