### ISSUE TITLE
multiprocessing.get_context('spawn') creates fork bomb

### ISSUE THREAD

**Issue by sproberts92** [marcelotduarte/cx_Freeze#351]
The following runs fine when called with the Python interpreter, but creates a fork bomb when frozen.
```Python
import multiprocessing


def foo():
    print('running foo')


def main():
    print('start')
    ctx = multiprocessing.get_context('spawn')

    p = ctx.Process(target=foo)
    p.start()
    p.join()


if __name__ == '__main__':
    main()
```

Using the `fork` start method instead is fine:

```Python
multiprocessing.get_context('fork')
```

Reproducible on Debian and RHEL7.

Also see my [Stackoverflow question on the issue](https://stackoverflow.com/questions/48265137/python-multiprocessing-freeze-fork-bomb).

**Comment by sproberts92** [comment]
Happy to provide whatever diagnostic info that you need.

I actually feel like this is deeper than cxfreeze, as pyinstaller has the same problem, but I thought it better to work top down in tracing the error.

**Comment by anthony-tuininga** [comment]
If "fork" works, why use "spawn"? The SO question seems to indicate that there is a bug in the "spawn" support, so I assume this can be closed?

**Comment by sproberts92** [comment]
Fork and spawn result in different resources being inherited by the child process so it's not as simple as just using the other. Given that the undesirable behaviour only occurs when freezing I'd say it's premature to close until we know more, but that's your call I guess. As I read it, the commenter was only speculating as to the source of the bug.

**Comment by sproberts92** [comment]
Ok - now I've managed to reproduce the bug using just `cpython/Tools/freeze/freeze.py`, so it's not a problem with cx_freeze. Closing.
