### ISSUE TITLE
svg.path module not found if (empty) __init__.py not in svg root

### ISSUE THREAD

**Issue by jabbott52** [marcelotduarte/cx_Freeze#352]
Python 2.7 interpreted works fine but executable fails with 'importerror: no module named svg.path' when __ init __.py is not in svg lib root.  Is __ init __.py required?  And should svg.path (2.2) package include this?  I'm using cx_freeze 4.3.3.

**Comment by jabbott52** [comment]
The build doesn't halt but the executable fails.

**Comment by jabbott52** [comment]
"__init__.py"

**Comment by jabbott52** [comment]
argh.  underscore underscore init.py underscore underscore .py

**Comment by jabbott52** [comment]
btw, cx_freeze I'm using is 4.3.3

**Comment by marcelotduarte** [comment]
Py35+ is supported only.
cx_Freeze 6.1 has just been released.
