### ISSUE TITLE
Move from distutils to setuptools?

### ISSUE THREAD

**Issue by kierun** [marcelotduarte/cx_Freeze#357]
Currently, `from cx_Freeze import setup` inherit from `distutils`. Could we move that to `setuptools`?

This would allow one to use `python setup.py develop` for example…

**Comment by TTimo** [comment]
Seconded!

`distutils` is built to Python 3 though, when `setuptools` is still an independent module.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
