### ISSUE TITLE
Possible Windows Specific Bug

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [marcelotduarte/cx_Freeze#359]
So, on my favourite Open Source project's github page, a number of windows-specific issues have been popping up related to cx_Freeze Python Error in main script. [Here](https://github.com/OpenShot/openshot-qt/issues/1270) is the latest one (I reference some others down in the comments). After a quick web-search though, I found a lot of (mostly) windows-specific cx_freeze errors - none of which were really resolved. [Here](https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/cxfreeze-python-error-in-main-script/795bdf76-4398-4c1d-934c-97172ee9b12e) is an example.

I just wanted to let the developers know. I'm sorry if this turns out to be unrelated to cx_Freeze itself. I hope the issue will be resolved soon.

**Comment by osve001** [comment]
FIXED!
Have a look at:
OpenShot 2.4.1 won't open - cx_Freeze Python error in main script #1244

**Comment by peanutbutterandcrackers** [comment]
Because the solution of @osve001 is only specific to him, so far, and seems to require a clean installation, as far as I know, I would still like to keep this issue open and have the developer's attention into this matter...

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
