### ISSUE TITLE
Windows Service Sample fails on import of `cx_Logging`

### ISSUE THREAD

**Issue by AlexEshoo** [marcelotduarte/cx_Freeze#360]
There seems to be an extra dependency on `cx_Logging` in the `setup.py` file of the `samples/service` example. This leads to throwing an exception for import error.

Removing the package from the `includes` argument allows the executable to build but I get a system error when trying to run the program:
![image](https://user-images.githubusercontent.com/8216513/36428793-e7e209ae-161e-11e8-8e79-5a06b62c6d31.png)

Any idea how to fix what is going on? is `cx_Logging` even necessary anymore? Does the sample code need to be updated to reflect a new change?

**Comment by mathieulj** [comment]
I would also like a clarification as cx_Logging does not seem to be installable via pip on python 3.6 and the installers on the module homepage are outdated (Python <= 3.1).
```
>pip --version
pip 9.0.3 from c:\program files (x86)\python36-32\lib\site-packages (python 3.6)
>pip install cx_Logging
Collecting cx_Logging
    Could not find a version that satisfies the requirement cx_Logging (from versions: )
No matching distribution found for cx_Logging 
```

Edit: It seems that pip still cant install with a fresh copy even of python 3.5
```
>pip --version
pip 9.0.3 from c:\users\mathieulj\appdata\local\programs\python\python35-32\lib\site-packages (python 3.5)
>pip install cx_Logging
Collecting cx_Logging
    Could not find a version that satisfies the requirement cx_Logging (from versions: )
No matching distribution found for cx_Logging 
```

Edit 2: It seems that no version of cx_Logging is available on pypi ([https://pypi.python.org/simple/cx_Logging/](https://pypi.python.org/simple/cx_Logging/)). It is a mystery to me how one is supposed to satisfy this dependency without manually rebuilding cx_Freeze and cx_Logging from source to include the missing code.

**Comment by mathieulj** [comment]
As a helper for those who follow and are not afraid to get their hands dirty, here is the convoluted way I got this working.

1. Install the `mingw32-base` module in [MinGW](https://sourceforge.net/projects/mingw/files/)
2. Add  MinGW binaries to your path
3. Patch `PYTHON_PATH\lib\distutils\cygwinccompiler.py` for recent MSVC versions [patch](https://bugs.python.org/file40608/patch.diff) 
4. Download the latest [cx_Logging](https://github.com/anthony-tuininga/cx_Logging)
5. Patch the linker search path in setup.py `+ library_dirs = [os.path.dirname(sys.executable)], @ line 207`
6. Build and install cx_Logging `python setup.py build --compiler=mingw32 install`

**Comment by mcarpenter** [comment]
This is still broken (Python 3.7, cx-Freeze 6.1)

**Comment by marcelotduarte** [comment]
The sample at https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/service requires cx_Logging. Please, install it with:
pip install cx_Logging

The current cx_Freeze 6.1 has an error with multiprocessing in windows (See issue #536).
PR #622 solve this.
