### ISSUE TITLE
Build Success but exe files cannot run

### ISSUE THREAD

**Issue by khaerulumam42** [marcelotduarte/cx_Freeze#361]
I have some programs that I would build to executable file.
I'm using python 3.6 on windows 10, I have success build executable file with no errors but when I run that executable file just show black windows like cmd and then disappear soon. I have disable my antivirus too.
So whats wrong with my programs? I don't know where the error is

anyone have same problems? or have solve this error?

Thanks for help

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
