### ISSUE TITLE
[Errno2]

### ISSUE THREAD

**Issue by HallSC** [marcelotduarte/cx_Freeze#362]
I am getting the following error when I run the setup.py script (python setup.py bdist_dmg).  It should be copying '/anaconda/lib/libncursesw.6.dylib' instead of '/anaconda/lib/libncursesw.5.dylib'.  

How should I go about fixing this issue?

##################################################################

copying /anaconda/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so -> build/exe.macosx-10.9-x86_64-3.6/lib/_ctypes.cpython-36m-darwin.so
copying /anaconda/lib/python3.6/lib-dynload/_curses.cpython-36m-darwin.so -> build/exe.macosx-10.9-x86_64-3.6/lib/_curses.cpython-36m-darwin.so
copying /anaconda/lib/libncursesw.5.dylib -> build/exe.macosx-10.9-x86_64-3.6/lib/libncursesw.5.dylib
error: [Errno 2] No such file or directory: '/anaconda/lib/libncursesw.5.dylib'

##################################################################

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
