### ISSUE TITLE
cx_Freeze 5.1.1: Lots of duplicate .dll files.

### ISSUE THREAD

**Issue by ltjax** [marcelotduarte/cx_Freeze#366]
Hello. I'm freezing a simple application with PyQt5, numpy, scipy and matplotlib.  Lots of dlls from the libs are duplicated many times. For example, api-ms-win-crt-runtime-l1-1-0.dll is in there 19 times, python36.dll 16 times, QtCore4.dll 4 times. Some of these files are huge, making the folder ~600mb for an about 350locs app.
It seems to just add each .dll for each entry in the lib/ folder instead of consolidating them.

**Comment by reubengann** [comment]
I second this. My project has matplotlib, numpy, pandas, and pyqt. I don't expect the application to be small, but if possible I'd like it not to include python36.dll 21 times.

**Comment by cainesi** [comment]
I am having the same issues on Windows.  It seems like the extra copies are being produced by the ._CopyFile method on the Freezer object.  When that method is called to copy a file, it in turn calls the ._GetDependentFiles method to find other dependent files to also copy.  The dependents are being determined (I think?) by calling some native windows function to determine the bindings.  If it locates dependent libraries then they are also copied into the same directory.  Therefore if there are a bunch of libraries in the application in different locations that all depend (e.g.) on Qt5Core.dll, then it looks like Qt5Core.dll gets copied to each of the locations.  

Could we prevent this by tracking which libraries have already been included in the application as dependents elsewhere?  I don't know enough about how linking works on Windows to know if that would cause problems...

**Comment by tigarmo** [comment]
I'm also having this issue. As far as I can tell this change was added in issue #328 , but that fix seems overkill for the majority of the applications; my test script that just uses subprocess has `python36.dll` and `VMRUNTIME140.dll` in both the root freeze dir and the `lib` dir.

Is there a workaround for this new behavior of copying dependent files to the same directory as the source file?

**Comment by cainesi** [comment]
Do we know why some libraries needed to be co-located in the same directory?

**Comment by tigarmo** [comment]
I don't think it's the case that the libraries need to be next to each other necessarily, but the dependencies have to be "findable" at runtime. So when the change to put some files in a `lib` directory was made it probably broke this lookup in some cases.

For our use case the size of the frozen directory went from 900 MB to 1.8 GB from all the duplicate libs, which complicates releases. Is there anything we can do to help out?

**Comment by cainesi** [comment]
If that was the problem why not just add the lib directory to the library search path?  Or alternatively create one directory that we know is in the path, and put all of the dependencies in there once?

(pardon my ignorance if I am missing something about how the library search works on Windows)

**Comment by tigarmo** [comment]
Well that's just my simplified understanding of the issue, I bet it's more complicated than that :)

**Comment by j33433** [comment]
I am also freezing Qt, numpy, etc. My little file converter program is 1.1G on disk.
As a workaround, running this (I did it from WSL) cuts my disk usage in half:

`find . -name '*.dll' -size +2M -exec upx {} \;`

**Comment by tigarmo** [comment]
If this current behavior is desirable, maybe we could add an option to disable it? I'm currently using an older version of cx_Freeze with a couple of bugfixes patched-in mostly for this reason, and I'd like to keep to vanilla upstream if possible.

**Comment by j33433** [comment]
I got pyinstaller to make 123 MB of files. But it was a **_nightmare_** that took all weekend.

**Comment by cainesi** [comment]
It looks like Windows searches the path for DLLs.  Could we not just add all the library dependencies into the top level directory of the application (or wherever) and then add the appropriate directory to the path with a 'os.environ["PATH"]+= os.pathsep + os.path.dirname(sys.executable)' in the initialization script before  we try to load any of the dependencies?

**Comment by tigarmo** [comment]
While that would fix the problem that needed the duplicate dlls, it would mean that every process that your process spawns would have the frozen dir as first in the search path, which is usually not desirable as those processes might not be compatible with your dlls.

**Comment by cainesi** [comment]
Wouldn't it be at the end of the spawned process search path?

**Comment by tigarmo** [comment]
Oh my apologies I misread your bit of code. You're right

**Comment by cainesi** [comment]
FYI, I suggested adding a "small_app" option that would revert to the old behavior (pre #328) and include the application's directory in the PATH environment variable.

**Comment by andrewchenshx** [comment]
I am having the same issues on Windows 10, cx_freeze 6.1

**Comment by cainesi** [comment]
The issue is fixed for me in the latest version in the repository (6.2).

**Comment by jeromerobert** [comment]
It's not fixed for me in current master (6bf4616), mingw64, Windows 10. I'm still having 6 copy of libpython3.8.dll, one in the root folder and 5 spreads in the lib folder.

**Comment by cainesi** [comment]
Did you try the code from my pull request back in July 2018. Would be curious to know if that fixes it. 

Also, what packages is your program using?

**Comment by cainesi** [comment]
Actually, I see that I am also getting python37.dll and VCRUNTIME140.dll each copied twice.  Once in root, and once in lib.

Wonder if that might have something to do with freezer._GetDefaultBinIncludes(), but don't have time to look into it no.

I don't have a libpython--maybe different naming convention with mingw?

**Comment by jeromerobert** [comment]
> I don't have a libpython--maybe different naming convention with mingw?

Yes it's just a different naming convention.

**Comment by cainesi** [comment]
Hmmm.  In that case, not sure how the hardcoded names in _GetDefaultBinIncludes() would work.

But just tried commenting out that bit, and cx-freeze still worked, and still gave the duplicates, so that wasn't it.

**Comment by xvolte** [comment]
Hello,
I'm also really interested.
I verified that python3.9.1 dll was copied 10 times in my project leading to unnecessary file size too, on windows.
I did not had this problem when running CXFreeze 5 with python 2.7.x

Is there a plan to fix it ?

Maybe the title must be changed, as it also impact CXFreeze 6.5

**Comment by marcelotduarte** [comment]
PR #973, #922, #978, and others optimize the copy of libraries in windows.
More optimizations will be to come.

cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
