### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by pruthvi94** [marcelotduarte/cx_Freeze#369]
HI Team,

While running the build, I am getting the below error, Please help.

File "C:\Users\pruthviraj.hs\AppData\Local\Programs\Python\Python36\lib\site-packages\cx_Freeze\finder.py", line 435, in _LoadModule
module.code = compile(codeString, path, "exec")
ValueError: source code string cannot contain null bytes

Thanks,
Pruthvi

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
