### ISSUE TITLE
ALLUSERS property in MSI

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#37]
Originally reported by: **Anonymous**

----------------------------------------

It is currently not possible to install the MSI produced with bdist_msi without admin privileges.
Could you add this feature?

http://msdn.microsoft.com/en-us/library/windows/desktop/aa367559%28v=vs.85%29.aspx

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/37

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Heads up: if you can work out how to add this yourself (the relevant code is in cx_Freeze/windist.py), it's probably quickest to fix it and make a pull request.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Mario Benito Ríos (Bitbucket: [Maberi](https://bitbucket.org/Maberi), GitHub: [Maberi](https://github.com/Maberi))**:

----------------------------------------

I've just made the pull request #72 to provide this feature.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
