### ISSUE TITLE
Installation of cx_Freeze (Any version) for Anaconda Python3.4 Fails

### ISSUE THREAD

**Issue by Hbethray05** [marcelotduarte/cx_Freeze#370]
Issue/Erro (Sorry for the long Error):  
System:  MacOS X El Capitan (10.11.16)

In the terminal window::

$ pip3 install cx_Freeze

**ERROR**
Collecting cx_Freeze
  Using cached cx_Freeze-5.1.1.tar.gz
Building wheels for collected packages: cx-Freeze
  Running setup.py bdist_wheel for cx-Freeze ... error
  Complete output from command /Users/hyq/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hk/qxsrf6s97r3b016cvy_js6vh2_zq71/T/pip-build-y2xtu7po/cx-Freeze/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/hk/qxsrf6s97r3b016cvy_js6vh2_zq71/T/tmpsuhoyer9pip-wheel- --python-tag cp34:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-3.4
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  copying cx_Freeze/__init__.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  copying cx_Freeze/common.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  copying cx_Freeze/dist.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  copying cx_Freeze/finder.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  copying cx_Freeze/freezer.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  copying cx_Freeze/hooks.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  copying cx_Freeze/macdist.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  copying cx_Freeze/main.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  copying cx_Freeze/setupwriter.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  copying cx_Freeze/windist.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
  copying cx_Freeze/initscripts/__startup__.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
  copying cx_Freeze/initscripts/Console.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
  copying cx_Freeze/initscripts/ConsoleSetLibPath.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
  copying cx_Freeze/initscripts/SharedLib.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
  copying cx_Freeze/initscripts/SharedLibSource.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/advanced
  copying cx_Freeze/samples/advanced/advanced_1.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/advanced
  copying cx_Freeze/samples/advanced/advanced_2.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/advanced
  copying cx_Freeze/samples/advanced/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/advanced
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/asmodule
  copying cx_Freeze/samples/asmodule/asmodule.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/asmodule
  copying cx_Freeze/samples/asmodule/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/asmodule
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/matplotlib
  copying cx_Freeze/samples/matplotlib/matplotlib_eg.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/matplotlib
  copying cx_Freeze/samples/matplotlib/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/matplotlib
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/openpyxl
  copying cx_Freeze/samples/openpyxl/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/openpyxl
  copying cx_Freeze/samples/openpyxl/test_openpyxl.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/openpyxl
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt4
  copying cx_Freeze/samples/PyQt4/PyQt4app.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt4
  copying cx_Freeze/samples/PyQt4/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt4
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt5
  copying cx_Freeze/samples/PyQt5/PyQt5app.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt5
  copying cx_Freeze/samples/PyQt5/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt5
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/relimport
  copying cx_Freeze/samples/relimport/relimport.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/relimport
  copying cx_Freeze/samples/relimport/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/relimport
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/service
  copying cx_Freeze/samples/service/Config.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/service
  copying cx_Freeze/samples/service/ServiceHandler.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/service
  copying cx_Freeze/samples/service/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/service
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/simple
  copying cx_Freeze/samples/simple/hello.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/simple
  copying cx_Freeze/samples/simple/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/simple
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/Tkinter
  copying cx_Freeze/samples/Tkinter/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/Tkinter
  copying cx_Freeze/samples/Tkinter/SimpleTkApp.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/Tkinter
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/wx
  copying cx_Freeze/samples/wx/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/wx
  copying cx_Freeze/samples/wx/wxapp.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/wx
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/zope
  copying cx_Freeze/samples/zope/qotd.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/zope
  copying cx_Freeze/samples/zope/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/zope
  running build_ext
  building 'cx_Freeze.util' extension
  creating build/temp.macosx-10.6-x86_64-3.4
  creating build/temp.macosx-10.6-x86_64-3.4/source
  /usr/bin/clang -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/hyq/anaconda/include -arch x86_64 -I/Users/hyq/anaconda/include/python3.4m -c source/util.c -o build/temp.macosx-10.6-x86_64-3.4/source/util.o
  /usr/bin/clang -bundle -undefined dynamic_lookup -L/Users/hyq/anaconda/lib -arch x86_64 build/temp.macosx-10.6-x86_64-3.4/source/util.o -L/Users/hyq/anaconda/lib -o build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/util.so
  creating build/temp.macosx-10.6-x86_64-3.4/source/bases
  /usr/bin/clang -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/hyq/anaconda/include -arch x86_64 -I/Users/hyq/anaconda/include/python3.4m -c source/bases/Console.c -o build/temp.macosx-10.6-x86_64-3.4/source/bases/Console.o
  In file included from source/bases/Console.c:44:
  source/bases/Common.c:177:23: warning: implicit declaration of function 'Py_DecodeLocale' is invalid in C99 [-Wimplicit-function-declaration]
      wExecutableName = Py_DecodeLocale(g_ExecutableName, NULL);
                        ^
  source/bases/Common.c:177:21: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
      wExecutableName = Py_DecodeLocale(g_ExecutableName, NULL);
                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  source/bases/Common.c:182:24: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
      wExecutableDirName = Py_DecodeLocale(g_ExecutableDirName, NULL);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  source/bases/Common.c:191:18: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
          wargv[i] = Py_DecodeLocale(argv[i], NULL);
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  4 warnings generated.
  creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/bases
  /usr/bin/clang -arch x86_64 build/temp.macosx-10.6-x86_64-3.4/source/bases/Console.o -L/Users/hyq/anaconda/lib/python3.4/config-3.4m -L/Users/hyq/anaconda/lib -lpython3.4m -o build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/bases/Console -ldl -framework CoreFoundation -s
  ld: warning: option -s is obsolete and being ignored
  Undefined symbols for architecture x86_64:
    "_Py_DecodeLocale", referenced from:
        _main in Console.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cx-Freeze
  Running setup.py clean for cx-Freeze
Failed to build cx-Freeze
Installing collected packages: cx-Freeze
  Running setup.py install for cx-Freeze ... error
    Complete output from command /Users/hyq/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hk/qxsrf6s97r3b016cvy_js6vh2_zq71/T/pip-build-y2xtu7po/cx-Freeze/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/hk/qxsrf6s97r3b016cvy_js6vh2_zq71/T/pip-ob3kph57-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-3.4
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    copying cx_Freeze/__init__.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    copying cx_Freeze/common.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    copying cx_Freeze/dist.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    copying cx_Freeze/finder.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    copying cx_Freeze/freezer.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    copying cx_Freeze/hooks.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    copying cx_Freeze/macdist.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    copying cx_Freeze/main.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    copying cx_Freeze/setupwriter.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    copying cx_Freeze/windist.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/__startup__.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/Console.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/ConsoleSetLibPath.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/SharedLib.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/SharedLibSource.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/initscripts
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/advanced
    copying cx_Freeze/samples/advanced/advanced_1.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/advanced
    copying cx_Freeze/samples/advanced/advanced_2.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/advanced
    copying cx_Freeze/samples/advanced/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/advanced
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/asmodule
    copying cx_Freeze/samples/asmodule/asmodule.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/asmodule
    copying cx_Freeze/samples/asmodule/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/asmodule
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/matplotlib
    copying cx_Freeze/samples/matplotlib/matplotlib_eg.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/matplotlib
    copying cx_Freeze/samples/matplotlib/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/matplotlib
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/openpyxl
    copying cx_Freeze/samples/openpyxl/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/openpyxl
    copying cx_Freeze/samples/openpyxl/test_openpyxl.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/openpyxl
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt4
    copying cx_Freeze/samples/PyQt4/PyQt4app.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt4
    copying cx_Freeze/samples/PyQt4/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt4
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt5
    copying cx_Freeze/samples/PyQt5/PyQt5app.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt5
    copying cx_Freeze/samples/PyQt5/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/PyQt5
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/relimport
    copying cx_Freeze/samples/relimport/relimport.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/relimport
    copying cx_Freeze/samples/relimport/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/relimport
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/service
    copying cx_Freeze/samples/service/Config.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/service
    copying cx_Freeze/samples/service/ServiceHandler.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/service
    copying cx_Freeze/samples/service/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/service
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/simple
    copying cx_Freeze/samples/simple/hello.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/simple
    copying cx_Freeze/samples/simple/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/simple
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/Tkinter
    copying cx_Freeze/samples/Tkinter/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/Tkinter
    copying cx_Freeze/samples/Tkinter/SimpleTkApp.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/Tkinter
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/wx
    copying cx_Freeze/samples/wx/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/wx
    copying cx_Freeze/samples/wx/wxapp.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/wx
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/zope
    copying cx_Freeze/samples/zope/qotd.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/zope
    copying cx_Freeze/samples/zope/setup.py -> build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/samples/zope
    running build_ext
    building 'cx_Freeze.util' extension
    creating build/temp.macosx-10.6-x86_64-3.4
    creating build/temp.macosx-10.6-x86_64-3.4/source
    /usr/bin/clang -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/hyq/anaconda/include -arch x86_64 -I/Users/hyq/anaconda/include/python3.4m -c source/util.c -o build/temp.macosx-10.6-x86_64-3.4/source/util.o
    /usr/bin/clang -bundle -undefined dynamic_lookup -L/Users/hyq/anaconda/lib -arch x86_64 build/temp.macosx-10.6-x86_64-3.4/source/util.o -L/Users/hyq/anaconda/lib -o build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/util.so
    creating build/temp.macosx-10.6-x86_64-3.4/source/bases
    /usr/bin/clang -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/hyq/anaconda/include -arch x86_64 -I/Users/hyq/anaconda/include/python3.4m -c source/bases/Console.c -o build/temp.macosx-10.6-x86_64-3.4/source/bases/Console.o
    In file included from source/bases/Console.c:44:
    source/bases/Common.c:177:23: warning: implicit declaration of function 'Py_DecodeLocale' is invalid in C99 [-Wimplicit-function-declaration]
        wExecutableName = Py_DecodeLocale(g_ExecutableName, NULL);
                          ^
    source/bases/Common.c:177:21: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
        wExecutableName = Py_DecodeLocale(g_ExecutableName, NULL);
                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    source/bases/Common.c:182:24: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
        wExecutableDirName = Py_DecodeLocale(g_ExecutableDirName, NULL);
                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    source/bases/Common.c:191:18: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
            wargv[i] = Py_DecodeLocale(argv[i], NULL);
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    4 warnings generated.
    creating build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/bases
    /usr/bin/clang -arch x86_64 build/temp.macosx-10.6-x86_64-3.4/source/bases/Console.o -L/Users/hyq/anaconda/lib/python3.4/config-3.4m -L/Users/hyq/anaconda/lib -lpython3.4m -o build/lib.macosx-10.6-x86_64-3.4/cx_Freeze/bases/Console -ldl -framework CoreFoundation -s
    ld: warning: option -s is obsolete and being ignored
    Undefined symbols for architecture x86_64:
      "_Py_DecodeLocale", referenced from:
          _main in Console.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/hyq/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hk/qxsrf6s97r3b016cvy_js6vh2_zq71/T/pip-build-y2xtu7po/cx-Freeze/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/hk/qxsrf6s97r3b016cvy_js6vh2_zq71/T/pip-ob3kph57-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/hk/qxsrf6s97r3b016cvy_js6vh2_zq71/T/pip-build-y2xtu7po/cx-Freeze/
**END ERROR**

I have tried a few things:: 
-- Checked that xcode developer tools were installed (XCode 7.3.1) -- They are
-- Followed the instructions on: https://github.com/pyca/cryptography/issues/2350
-- Downloaded the tarball and tried to build and install from there (Same error)
-- Attempted install of older version (Same error)

Any help would be greatly appreciated!  I wonder if I need an updated version of XCode?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
