### ISSUE TITLE
It can build the bdist_msi file but it still raise errro???

### ISSUE THREAD

**Issue by jekoie** [marcelotduarte/cx_Freeze#371]
creating build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\.pylintrc -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\const.py -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\const.pyc -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\iface.py -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\iface.pyc -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\profile.py -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\profile.pyc -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\wifi.py -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\wifi.pyc -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\_wifiutil_linux.py -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\_wifiutil_win.py -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\_wifiutil_win.pyc -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\__init__.py -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\pywifi\__init__.pyc -> build\bdist.win32\msi\pywifi
copying build\exe.win32-2.7\sqlite3.dll -> build\bdist.win32\msi
creating build\bdist.win32\msi\tool
copying build\exe.win32-2.7\tool\fping.exe -> build\bdist.win32\msi\tool
copying build\exe.win32-2.7\tool\MDBPlus.exe -> build\bdist.win32\msi\tool
copying build\exe.win32-2.7\tool\mdbplus.ini -> build\bdist.win32\msi\tool
creating build\bdist.win32\msi\win32wifi
copying build\exe.win32-2.7\win32wifi\Win32NativeWifiApi.py -> build\bdist.win32\msi\win32wifi
copying build\exe.win32-2.7\win32wifi\Win32Wifi.py -> build\bdist.win32\msi\win32wifi
copying build\exe.win32-2.7\win32wifi\__init__.py -> build\bdist.win32\msi\win32wifi
creating dist
removing 'build\bdist.win32\msi' (and everything under it)
error removing build\bdist.win32\msi: [Error 32] : 'build\\bdist.win32\\msi'
PS E:\AutoTest>

**Comment by jekoie** [comment]
I use adimistrator privilege,it raise this error.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
