### ISSUE TITLE
Microsoft Visual C runtime DLLs are copied to the wrong folder

### ISSUE THREAD

**Issue by alessandrodd** [marcelotduarte/cx_Freeze#372]
Could be related to #328 ; 
when using the option `'include_msvcr': True` , VCRUNTIME140.dll gets copied to the **lib** folder instead of its parent folder, i.e. the one that will contain the produced .exe:

![cattura](https://user-images.githubusercontent.com/11824406/38361188-daabd0be-38cc-11e8-9111-34850b434227.PNG)

causing the following error:

![err](https://user-images.githubusercontent.com/11824406/38361347-5613ad94-38cd-11e8-9499-577a4f74e41a.jpg)

Moving the VCRUNTIME140.dll from /lib to its parent directory fixes it.

**Comment by FreeHarry** [comment]
I can confirm this issue for cx_freeze 6.0b1 (the newest one from GitHub) at Windows 10. Move the file `VCRUNTIME140.dll` to the parent folder seems to fix the error.

And on my machine (Win 10) it's equal if `include_msvcr` is `True or False`

**Comment by FreeHarry** [comment]
What I also recognized is that the `python36.dll` is copied into both folders: exe-folder and lib-folder. If I remove the duplicated `python36.dll` from the lib-folder and move the `VCRUNTIME140.dll` to the exe-folder all runs well.

So it seems `python36.dll` and `VCRUNTIME140.dll` must be in the same folder as the executable and NOT in the lib-folder.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
