### ISSUE TITLE
Python 3.6 After converting to exe using cx_freeze - paramiko(SSH) function stopped working

### ISSUE THREAD

**Issue by gustavon1973** [marcelotduarte/cx_Freeze#378]
After I convert to exe, ssh(paramiko) function does not work anymore. It does not connect to the device.
I have included paramiko and socket packages. Any Ideas?
It is working in with non-converted version.

import cx_Freeze
from cx_Freeze import setup, Executable
import os
import sys
includes = []
include_files = ["C:\\Python36-32\DLLs\\tcl86t.dll",
                 "C:\\Python36-32\DLLs\\tk86t.dll",
                 "C:\\Gustavo\\cpass.ico",
                 "C:\\Gustavo\\py2.py",
                 "C:\\Gustavo\\py3.py",
                 "C:\\Gustavo\\tn.py",
                 "C:\\Gustavo\\file1.csv"]
PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
os.environ['TCL_LIBRARY'] = "C:\\Python36-32\\tcl\\tcl8.6"
os.environ['TK_LIBRARY'] = "C:\\Python36-32\\tcl\\tk8.6"
base = 'Win32GUI' if sys.platform == 'win32' else None

setup(name='Password Change', version='0.1', description='Password Change',
      options={"build_exe": {"packages": ["tkinter","paramiko","PIL","py2","socket","telnetlib","time","csv","threading","os","sys"], "includes": includes, "include_files": include_files}},
      executables=[Executable('cp.py', base=base)])

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
