### ISSUE TITLE
Not logging some errors related to the icon

### ISSUE THREAD

**Issue by mdalboni** [marcelotduarte/cx_Freeze#379]
Hey there.

In freezer.py on this part of the code:

 def _FreezeExecutable(self, exe):
        finder = self.finder
        finder.IncludeFile(exe.script, exe.moduleName)
        finder.IncludeFile(exe.initScript, exe.initModuleName)
        startupModule = get_resource_file_path("initscripts", "__startup__",
                ".py")
        finder.IncludeFile(startupModule)

        self._CopyFile(exe.base, exe.targetName, copyDependentFiles = True,
                includeMode = True)
        if self.includeMSVCR:
            self._IncludeMSVCR(exe)

        # Copy icon
        ###### Exception location ######
        if exe.icon is not None:
            if sys.platform == "win32":
                import cx_Freeze.util
                cx_Freeze.util.AddIcon(exe.targetName, exe.icon)
            else:
                targetName = os.path.join(os.path.dirname(exe.targetName),
                        os.path.basename(exe.icon))
                self._CopyFile(exe.icon, targetName,
                        copyDependentFiles = False)
         ###### Exception location ######

        if not os.access(exe.targetName, os.W_OK):
            mode = os.stat(exe.targetName).st_mode
            os.chmod(exe.targetName, mode | stat.S_IWUSR)
        if self.metadata is not None and sys.platform == "win32":
            self._AddVersionResource(exe)

It would be nice to have some logger in the marked part or an error traceback.
Why do I ask this? Because my icon was working properly on my machine, when I imported the same come to another machine it wasn't running showing an error on IntelliJ and was python crashing with random error code in terminal.
After some time debuging I found the source of the problem, it wasn't looking in my root folder.

Or I can make a pull request if allowed.

Thanks :D

**Comment by marcelotduarte** [comment]
PR #851 should resolve this issue.

**Comment by marcelotduarte** [comment]
@mdalboni cx_Freeze 6.5 has just been released.
