### ISSUE TITLE
Too many errors while building tensorflow application.

### ISSUE THREAD

**Issue by HorsonLiu** [marcelotduarte/cx_Freeze#380]
hello.py
```
import tensorflow

print('ok')
```

setup.py
```
from cx_Freeze import setup, Executable

setup(
    name='test cx_freeze',
    version='0.1',
    options={
        'build_exe':{ 
            'excludes': ['Tkinter'], 
            'includes': [
                'numpy.core._methods',
                'numpy.lib.format',
            ], 
           'packages': [] 
        }
    },
    executables=[Executable(script='hello.py', base=None)]
)
```

How to edit setup.py to build hello.py successfully and execute whihout any error ?

**Comment by LukasAV** [comment]
Has there been any work or success in using tensorflow with cx_freeze. I am trying to do the same but could not get python code compiled into an executable in any python to .exe tool.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released with namespace detection. Please, try it.

**Comment by HorsonLiu** [comment]
> cx_Freeze 6.2 has just been released with namespace detection. Please, try it.

build ok, but fail to execute.
`
$ pip install cx_Freeze  --upgrade                                                                                                                                                                      Requirement already up-to-date: cx_Freeze in e:\study\ai\python\pyenv3\lib\site-packages (6.2)
--
`

`
$ python setup.py build                                                                                                                                                                                 running build                                                                                                                                                                                           running build_exe
--
`

`
$ ./hello.exe                                                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                                        File "E:\Study\AI\python\pyenv3\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run                                                                                                  module.run()                                                                                                                                                                                          File "E:\Study\AI\python\pyenv3\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in run                                                                                                      exec(code,  m.__dict__)                                                                                                                                                                               File "hello.py", line 1, in                                                                                                                                                                     File "E:\Study\AI\python\pyenv3\lib\site-packages\tensorflow\__init__.py", line 24, in                                                                                                            from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import                                                                                                                      File "E:\Study\AI\python\pyenv3\lib\site-packages\tensorflow\python\__init__.py", line 63, in                                                                                                     from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin                                                                                                          File "E:\Study\AI\python\pyenv3\lib\site-packages\tensorflow\python\framework\framework_lib.py", line 25, in                                                                                      from tensorflow.python.framework.ops import Graph                                                                                                                                                     File "E:\Study\AI\python\pyenv3\lib\site-packages\tensorflow\python\framework\ops.py", line 39, in                                                                                                from tensorflow.python import tf2                                                                                                                                                                   ImportError: cannot import name 'tf2'
--

`

**Comment by marcelotduarte** [comment]
@HorsonLiu 
cx_Freeze 6.3 has just been released.
Can you check if this has been resolved?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Closing due to lack of information.
If you had issues please open a new issue.
