### ISSUE TITLE
cx_Freeze cannot find script, despite its path is defined in build_exe options

### ISSUE THREAD

**Issue by Kamforka** [marcelotduarte/cx_Freeze#382]
Hey there I'm trying to create a setup script that is capable of freezing a script that is one level below in the folder structure than the setup script itself.

Environment:
```
OS: Win 7 x64
Python version: 3.6.1
cx_Freeze version:  5.1.1
```

My folder structure is something similar to this:

```
my_package
│   freeze.py  
│
└───my_package
         calculations.py  
         xl_calculations.py  
```

So as you can see I have a package called `my_package` and I have my `main` in the script `xl_calculations.py`. 

Also please note that `freeze.py` holds the setup for `cx_Freeze` with the following content:

```python
# -*- coding: utf-8 -*-
"""Project setup file."""
import os
import sys
from cx_Freeze import Executable, setup

BUILD_EXE_OPTIONS = {
    'build_exe': r'resources\bin\calculations',  # target path for the frozen executable
    'excludes': ['matplotlib', 'pandas', 'sqlite3', 'scipy', 'numpy'],
    'path': [os.path.abspath('my_package')] + sys.path,
}

setup(name='Calculations',
      version='0.1',
      description='Calculations',
      options={'build_exe': BUILD_EXE_OPTIONS},
      executables=[Executable('xl_calculations.py', targetName='xl_calculations.exe')],
     )
```

I tried to set the `path` parameter for the `build_exe` option, but still when I start the build process I get the following error:

```bash
> python freeze.py build
running build
running build_exe
error: [Errno 2] No such file or directory: 'xl_calculations.py'
```

As a workaround for now I have a convenience script `run.py` on the same level as `freeze.py`, which imports and calls the `main` method from `xl_calculations`, but I want to move away from that approach as it is kinda redundant for me at the moment.

Can you please help me with this issue?

**Comment by marcelotduarte** [comment]
build_exe should be a dict.
Please read the documentation.
If you had issues please reopen.

**Comment by Kamforka** [comment]
@marcelotduarte can you please provide a minimal working example?

**Comment by marcelotduarte** [comment]
You can use the samples folder.
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples
The cryptography, importlib, pillow, sqlite and distutils are samples provided by me.

**Comment by marcelotduarte** [comment]
And, the executables line:
executables=[Executable('xl_calculations.py', targetName='xl_calculations.exe')]
Can be changed to:
executables=[Executable(r'c:\\path\\to\\package\\xl_calculations.py')]
or some relative path like:
executables=[Executable(r'package\\xl_calculations.py')]

**Comment by marcelotduarte** [comment]
I misread you code.
Your build_exe is already a dict. The build_exe in the dict is a path, ok.
So, the error is only on executables option.
Teste it with cx-freeze 6.0 or 6.0b1

**Comment by Kamforka** [comment]
Correct, so it's still an issue right? In that case I would not close it.

**Comment by marcelotduarte** [comment]
I think that it isn't a issue. It's a coding error on the executables option.
Where are the 'xl_calculations.py'? In the same directory of setup.py?
The error is clear: 
error: [Errno 2] No such file or directory: 'xl_calculations.py'
Change the executables like I commented before:
executables=[Executable('mypackage/xl_calculations.py')]

**Comment by franciscomvargas** [comment]
I was going around circles but perhaps this can shorten someone circles:

Considering this build:

    cxfreeze -c app.py --target-dir dist --target-name="app_name.exe" --icon=icon.png

Consider in your app.py header this:

    import os
    
    DIST_PATH=os.path.dirname(os.path.realpath(__file__))
    os.chdir(DIST_PATH)
    APP_PATH=os.path.dirname(DIST_PATH)

Explanation:
The executable is not going to be inside the app.py root folder but inside a child folder "dist"

**Comment by marcelotduarte** [comment]
@franciscomvargas https://cx-freeze.readthedocs.io/en/stable/faq.html#using-data-files
