### ISSUE TITLE
Build error on OS X

### ISSUE THREAD

**Issue by joshuaTTL** [marcelotduarte/cx_Freeze#386]
Hi guys, I'm trying to freeze a script on my Mac but I'm running into the following problem. The command I used is cxfreeze test.py --target-dir dist 

and i got this :   
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl'

Thanks!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
