### ISSUE TITLE
Specifying Mac OS iconfile in script

### ISSUE THREAD

**Issue by ryanfox** [marcelotduarte/cx_Freeze#388]
Hello,

I can currently specify an iconfile in Mac OS via the `iconfile` command line flag:

    $ python setup.py bdist_mac --iconfile=my_icon.icns

Is there a way to specify the filename inside `setup.py`, so one doesn't have to supply `--iconfile` every time? The documentation doesn't seem to indicate where that would be.

**Comment by HotelCalifornia** [comment]
From http://cx-freeze.readthedocs.io/en/latest/distutils.html#bdist-mac

option name | description
-- | --
iconfile | Path to an icns icon file for the application. This will be copied into the bundle.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
