### ISSUE TITLE
ImportError: cannot import name 'idnadata'

### ISSUE THREAD

**Issue by mcl12345** [marcelotduarte/cx_Freeze#389]
Hi,

I have a problem to compile my program :

I did :
python setup.py build
Then  I launch the program and i have that
![sans titre](https://user-images.githubusercontent.com/24854693/41898770-1ccd4948-792b-11e8-9dac-f08ee6d91d49.png)

![sans titre](https://user-images.githubusercontent.com/24854693/41899593-23a8162e-792d-11e8-8537-582b8bd13727.png)

**Comment by mcl12345** [comment]
I have resolved the problem thanks to that : 

    from cx_Freeze import setup, Executable
    import sys


    #main
    exe = Executable(script="test.py", base="Win32GUI")
    buildOptions = dict(excludes = ["tkinter"], includes =["idna.idnadata"], optimize=1)
    setup(name = "instagram",version = "1.0", description = "test", executables = [exe], options =dict(build_exe = buildOptions))

**Comment by pieman64** [comment]
I know this issue is closed but I just wanted to say the script above also fixed idnadata error.
