### ISSUE TITLE
Build not executing correctly on Mac OS X 10.13

### ISSUE THREAD

**Issue by PeronistaUniversal** [marcelotduarte/cx_Freeze#392]
I'm having this problem with Mac OS X 10.13 and Python 3.6.6. The test I made is with a single Python file that with only

`print("Hello world!)`

as its contents. The build process is executed without errors but when I try to run the output I get this error:

`Fatal Python error: Py_Initialize: unable to load the file system codec

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/__init__.py", line 31, in <module>

zipimport.ZipImportError: can't decompress data; zlib not available

Abort trap: 6`

I tried this with Python's official binary, Anaconda distribution and Pyenv, the same result in every case. Obviously, Xcode and CLI tools like gcc are installed. It seems that the executable is trying to load the encodings module from the system wide (or virtual enviroment, when I tried with pyenv) and not from the version that it is inside the build directory.

**Comment by cocoliliace** [comment]
I'm facing the same issue. I've been searching for an answer for 2 days. It will be very appreciated if someone can tell us the solution to this

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
