### ISSUE TITLE
cxfreeze 5.1.1 doesn't seem to pull in dependencies specified with

### ISSUE THREAD

**Issue by wlach** [marcelotduarte/cx_Freeze#393]
When I upgraded [mozregression-gui](https://github.com/mozilla/mozregression) build process to use cx_freeze 5.1.3

```py
from . import winprocess
```
https://searchfox.org/mozilla-central/rev/d2966246905102b36ef5221b0e3cbccf7ea15a86/testing/mozbase/mozprocess/mozprocess/processhandler.py#32

```py
from . import idnadata
```
https://github.com/kjd/idna/blob/master/idna/core.py#L1

mozregression currently has some dependencies on python2 packages, so I haven't tested this behaviour with either 6.0b1 or python3. I do know that the 4.3.4 version I was using before handled the mozprocess case correctly (at least). To get around this problem for now, I've resorted to this rather horrible hack:

https://github.com/mozilla/mozregression/blob/b38fdfcf4bea16b0f52bf857d25a544587ed8202/gui/mozregui/main.py#L23

**Comment by marcelotduarte** [comment]
With the patch #478 resolves this issue and you could remove the hack.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
