### ISSUE TITLE
Run multiprocessin.Process from Win32Service

### ISSUE THREAD

**Issue by alex-eri** [marcelotduarte/cx_Freeze#403]
Process(target=fu).start() not working, not forked from main.

My code has periodic task that makes http requests and task needed to be low latency amd non blocked. So threading not good for me.

PS. How to work with cx_Logging?

**Comment by marcelotduarte** [comment]
For cx_Logging has a sample at https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/service
See https://github.com/anthony-tuininga/cx_Freeze/issues/536#issue-533867698 about it.
PR #622 solve these issues.
