### ISSUE TITLE
cx_freeze project error exe

### ISSUE THREAD

**Issue by VarusEx** [marcelotduarte/cx_Freeze#404]
I have that error when i run cx_freeze app is build but something don't work.
I use modules PyQt5,PIL,XML.DOM,OS:
![shu_o5ojpj](https://user-images.githubusercontent.com/33813509/43044841-32db2ae2-8dae-11e8-9196-6494e56f42a9.png)

That's is my setup.py 
`# -*- coding: utf-8 -*-

from cx_Freeze import setup
from cx_Freeze import Executable

includes = []
excludes = []

exe = Executable(
    script="ImageEditor.pyw",
    base="Win32GUI",
)

setup(
    name="Image",
    version="1.0",
    description=u"description",
    long_description=u"more description",
    author="Me",
    options={
        "build_exe": {
            "includes": includes,
            "excludes": excludes,
            "optimize": 2,
        }
    },
    executables=[exe]
)`

**Comment by marcelotduarte** [comment]
If you change "optimize" to 1 or 0 it'll work, because optimize=2 removes docstrings (`__doc__` is None) and in you version of PIL use it. I think that recent versions of Pillow do not use this.

Assuming this has been resolved.
If you had issues please re-open.
