### ISSUE TITLE
Help need with PYQT4 pulling in all files

### ISSUE THREAD

**Issue by vikingsraven** [marcelotduarte/cx_Freeze#405]
Hi using cx_freeze to create a test program for work.
its working well, but seems to be pulling the whole PYQT4 directory into the build folder.
this is my setup.py 
`from cx_Freeze import setup,Executable

includefiles = ['MatrixList.ui', 'Icons/']
includes = []
excludes = ['Tkinter',"matplotlib.backends.backend_foo"]
packages = ['os']

setup(
    name = 'Matrix',
    version = '0.1',
    description = 'A general enhancement utility',
    author = 'M Stillman',
    author_email = 'le...@null.com',
    options = {'build_exe': {'includes':includes,'excludes':excludes,'packages':packages,'include_files':includefiles}}, 
    executables = [Executable('MatrixV1.pyw')]
)`
this is what im importing in my script
`import sys
import serial
import glob
from PyQt4 import QtCore,QtGui
from PyQt4 import uic`

how can i stop it pulling in all but what is needed.
i tried to use`includes = ['PyQt4.QtGui','PyQt4.QtCore',PyQt4.uic]` 
but its still pulling all the folders including the examples, PyQwt5, translations etc 173Mb.
How can i stop this please.
thanks
Mark

**Comment by Axel-Erfurt** [comment]
I have the same problem in Linux Mint 18.3 with PyQt5 and python3.
Using python2 app is 22MB, using python3 app is > 300MB
It copies the whole PyQt5.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
