### ISSUE TITLE
Docs: Executable: Script (please elaborate)

### ISSUE THREAD

**Issue by guettli** [marcelotduarte/cx_Freeze#408]
Please elaborate the docs for Executable:

 http://cx-freeze.readthedocs.io/en/latest/distutils.html#cx-freeze-executable

What does "script" mean?

Current docs:

> the name of the file containing the script which is to be frozen

Is it just the base name or including the path?

Is this an absolute or relative path?

**Comment by marcelotduarte** [comment]
> What does "script" mean?
https://www.developer.com/lang/other/article.php/626311/Learn-to-Program-using-Python-Writing-and-Using-Scripts.htm

 
> Current docs:
> the name of the file containing the script which is to be frozen
> 
> Is it just the base name or including the path?
I can include the path. 
> Is this an absolute or relative path?
Both.
