### ISSUE TITLE
Encoding Pyc created by cx_freeze keeps fault path

### ISSUE THREAD

**Issue by VagosGrigoropoulos** [marcelotduarte/cx_Freeze#411]
I use cx_freeze to freeze a program i made.Everything works fine in my pc but when i install the programm on another pc i got an error.When i debugged this i saw that an encoding pyc named cp1253.pyc created in lib/encodings keeps a path from my main pc that the programm froze.
If i delete this pyc file , the programm still works but then the encodings needed from this pyc file will not work so my programm can't operate correctly.Is there a fix?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
