### ISSUE TITLE
api-ms-win-crt dlls are not copied correctly

### ISSUE THREAD

**Issue by NN---** [marcelotduarte/cx_Freeze#417]
When you have TortoiseGit installed, it adds its bin folder to the path.
cx_Freeze scans path for all api-ms-win-crt-* files and instead of using Windows\system32, it uses the incorrect ones.

This means that if you have TortoiseGit 64-bit and you run python 32-bit with cx_Freeze you get a dlls not matching the architecture of exe and everything fails.

**Comment by NN---** [comment]
Duplicate of #367

**Comment by xvolte** [comment]
I'm having the same problem.
In fact i would like that those files are NOT copied.
Do you known how i can do that ?
Thanks in advance
