### ISSUE TITLE
cx_Freeze with Python3.7.0 crashes in Win10

### ISSUE THREAD

**Issue by jiangmingwen** [marcelotduarte/cx_Freeze#420]
OS:  win 10
Python version: 3.7.0
pip version: 18.0
cx_Freeze install with `pip install  [cx_Freeze name].whl`
i use an other python package `paramiko` , it must be use Python3.7

this is myname.py ：`
from cx_Freeze import Executable
from cx_Freeze import setup

exe = [Executable("mmd.py")]
setup(name="downloads",
      version="1.0",
      options={"build_exe": {
          "packages": [
              "os",
              "shutil",
              "re",
              "sys",
              "getopt",
              "initProject",
              "packagePc",
              "versionControl",
              "json",
              "subprocess",
              "configparser",
              "datetime",
              "paramiko",
              "publish"
          ],
          "include_files": ["node_modules.zip", "node_server", "template"]
      }},
      executables=exe)`

when i use   `python myname.py  build`   it works success
but when i  run the *.exe error:
`Fatal Python error: initfsencoding: unable to load the file system codec
ImportError: invalid flags 1530043318 in 'encodings'

Current thread 0x00001fd0 (most recent call first):`

**Comment by egormartiniuc** [comment]
Hi there requested to fix it in pull #395, till then you can use version from here https://github.com/egormartiniuc/cx_Freeze

**Comment by NIExpo** [comment]
How I get the fix? Sorry, I am little bit new and running into this issue

**Comment by marcelotduarte** [comment]
Please report at an open issue, like #410 and see my comment.
