### ISSUE TITLE
Requests missing SSL module

### ISSUE THREAD

**Issue by Michelgard** [marcelotduarte/cx_Freeze#428]
Hello,
I'm using cxfreeze to do an .exe with a python program that uses the coinmarketcap module. My program runs smoothly but the program in .exe makes me an error of lack of an SSL module for coinmarketcap. The url of the API is in https.
How can I add this module to the requests module?
Thank you

**Comment by Michelgard** [comment]
up :(

**Comment by jpeg13** [comment]
I've proposed a work-around here: [https://stackoverflow.com/questions/52518979/cx-freeze-error-module-ssl-not-available-python-3-7-windows-10](https://stackoverflow.com/questions/52518979/cx-freeze-error-module-ssl-not-available-python-3-7-windows-10), without feedback so far.

**Comment by sekrause** [comment]
It's most likely related to issue #437.

**Comment by marcelotduarte** [comment]
cx_Freeze 6 has been release. Can you try again? Can I close the issue?

**Comment by ofersadan85** [comment]
> cx_Freeze 6 has been release. Can you try again? Can I close the issue?

I can confirm this works, I had this problem in 5.1.1 but upgrading to 6 solved the issue
