### ISSUE TITLE
Text in tables in documentation should wrap

### ISSUE THREAD

**Issue by henniss** [marcelotduarte/cx_Freeze#429]
Text in tables in the documentation doesn't wrap. This results in very long lines, which are hard to read and must be manually scrolled. [Here, for example](https://cx-freeze.readthedocs.io/en/latest/distutils.html#build-exe)

![image](https://user-images.githubusercontent.com/17056237/46504333-7d171080-c7e2-11e8-8071-f1ced87bc420.png)

Allegedly this has a simple fix: https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html

**Comment by anthony-tuininga** [comment]
Thanks! I've just pushed changes to the documentation to have this corrected.
