### ISSUE TITLE
cx_Freeze crash with no error message when trying to import NumPy

### ISSUE THREAD

**Issue by lgwangh** [marcelotduarte/cx_Freeze#432]
I wrote a simple scrpit for homework with numpy and traitsui, and I'm trying to convert it into .exe with cx_Freeze. But when I use it, it just quit without any output, like this:

```
F:\sublime\FitTool>cxfreeze MyFitTool.py --target-dir dist

F:\sublime\FitTool>
```

I didn't know what happened, and I thought there is something wrong with my python environment. However, I found simple script without importing anything can be converted by cx_Freeze. So I do some test, and I find when modules about numpy or traits.api is commented out, it works fine, like this

```
# import numpy as np
# import pandas as pd
from copy import deepcopy
# from traits.api import HasTraits, Instance, Enum, Int, File, Button, Float, Str
```

I searched similar problems with numpy other people had found, all of them can get some error message. 

I use Windows10, and I run cx_Freeze in cmd. My python version is 3.5.4, numpy version is 1.14.3, and I have tested cx_Freeze in version 5.1.1 and 6.0b1.

I' amateur in programming, and I'm sorry if I don't describe the problem clearly.

**Comment by marcelotduarte** [comment]
cx_Freeze 6 has been release. Can you try again? Can I close the issue?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
