### ISSUE TITLE
Python 3.7 on Windows requires additional DDLs for the SSL module

### ISSUE THREAD

**Issue by sekrause** [marcelotduarte/cx_Freeze#437]
In Python 3.7 on Windows the `_ssl.pyd` is much smaller because most of its functionality has been split into two new DDLs:

* `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` on 64-bit Python.
* `libssl-1_1.dll` and `libcrypto-1_1.dll` on 32-bit Python.

However cx_Freeze doesn't copy them into the `lib` directory, resulting in the following error message when trying to load the `ssl` module:

```
Traceback (most recent call last):
  File ".\lib\ssl.py", line 98, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

The following hook fixes this issue for both the 32-bit and 64-bit version and possibly for future SSL versions > 1.1:

```python
def load_ssl(finder, module):
    """In Windows, the SSL module in Python >= 3.7 requires additional dlls to
       be present in the build directory."""
    if sys.platform == "win32" and sys.version_info >= (3, 7):
        for dll_search in ["libcrypto-*.dll", "libssl-*.dll"]:
            for dll_path in glob.glob(os.path.join(sys.base_prefix, "DLLs", dll_search)):
                dll_name = os.path.basename(dll_path)
                finder.IncludeFiles(dll_path, os.path.join("lib", dll_name))
```

**Comment by buxx** [comment]
Hello @sekrause , i have similar issue (see https://sourceforge.net/p/cx-freeze/mailman/message/36579583/).

How do you use the function `load_ssl` to "patch" cx_Freeze build process ? Thank's.

**Comment by buxx** [comment]
I found a solution:

``` python
# coding: utf-8
from cx_Freeze import setup, Executable
import os
import sys

options = {"build_exe": {}}
PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
if sys.platform == "win32":
    options["build_exe"]['include_files'] = [
        os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libcrypto-1_1-x64.dll'),
        os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libssl-1_1-x64.dll'),
     ]


setup(
    # ...
    options=options,
)
```

Note: File name and path of `libcrypto` and  ̀libssl` should be found with script instead hardcoded name.

**Comment by sekrause** [comment]
> How do you use the function `load_ssl` to "patch" cx_Freeze build process ? Thank's.

I just created my own build of cx_Freeze where I put my hook above into cx_Freeze/hooks.py (don't forget to also add the correct imports). But your solution looks good as well.

**Comment by jngapp** [comment]
> 
> 
> I found a solution:
> 
> ```python
> # coding: utf-8
> from cx_Freeze import setup, Executable
> import os
> import sys
> 
> options = {"build_exe": {}}
> PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
> if sys.platform == "win32":
>     options["build_exe"]['include_files'] = [
>         os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libcrypto-1_1-x64.dll'),
>         os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libssl-1_1-x64.dll'),
>      ]
> 
> 
> setup(
>     # ...
>     options=options,
> )
> ```
> 
> Note: File name and path of `libcrypto` and ̀libssl` should be found with script instead hardcoded name.

Thanks man. I'd been looking for this answer for hours.

**Comment by manziEric** [comment]
> > I found a solution:
> > ```python
> > # coding: utf-8
> > from cx_Freeze import setup, Executable
> > import os
> > import sys
> > 
> > options = {"build_exe": {}}
> > PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
> > if sys.platform == "win32":
> >     options["build_exe"]['include_files'] = [
> >         os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libcrypto-1_1-x64.dll'),
> >         os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libssl-1_1-x64.dll'),
> >      ]
> > 
> > 
> > setup(
> >     # ...
> >     options=options,
> > )
> > ```
> > 
> > 
> > Note: File name and path of `libcrypto` and ̀libssl` should be found with script instead hardcoded name.
> 
> Thanks man. I'd been looking for this answer for hours.



> I found a solution:
> 
> ```python
> # coding: utf-8
> from cx_Freeze import setup, Executable
> import os
> import sys
> 
> options = {"build_exe": {}}
> PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
> if sys.platform == "win32":
>     options["build_exe"]['include_files'] = [
>         os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libcrypto-1_1-x64.dll'),
>         os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libssl-1_1-x64.dll'),
>      ]
> 
> 
> setup(
>     # ...
>     options=options,
> )
> ```
> 
> Note: File name and path of `libcrypto` and ̀libssl` should be found with script instead hardcoded name.

i'm working in Venv virtual environment im trying out your code with python setup.py build.
i get this Error :
cx_Freeze.freezer.ConfigError: cannot find file/directory named C:\Users\win10\PycharmProjects\winlog\venv\DLLs\libcrypto-1_1-x64.dll

Do i have to set the path of the DDLs ?
is this error because im working in a Venv environment ?

Thanks

**Comment by manziEric** [comment]
> I found a solution:
> 
> ```python
> # coding: utf-8
> from cx_Freeze import setup, Executable
> import os
> import sys
> 
> options = {"build_exe": {}}
> PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
> if sys.platform == "win32":
>     options["build_exe"]['include_files'] = [
>         os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libcrypto-1_1-x64.dll'),
>         os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libssl-1_1-x64.dll'),
>      ]
> 
> 
> setup(
>     # ...
>     options=options,
> )
> ```
> 
> Note: File name and path of `libcrypto` and ̀libssl` should be found with script instead hardcoded name.

i'm working in Venv virtual environment im trying out your code with python setup.py build.
i get this Error :
cx_Freeze.freezer.ConfigError: cannot find file/directory named C:\Users\win10\PycharmProjects\winlog\venv\DLLs\libcrypto-1_1-x64.dll

Do i have to set the path of the DDLs ?
is this error because im working in a Venv environment ?

Thanks
