### ISSUE TITLE
Error when Copying data from package PyQt5 

### ISSUE THREAD

**Issue by helloninglei** [marcelotduarte/cx_Freeze#439]
- Environment：python3.6.5 + PyQt5 + cx-Freeze5.1.1

- Error Code:when i run "python setup.py build" , i got this error as follow.

![image](https://user-images.githubusercontent.com/22606004/48877421-0d1a2380-ee3e-11e8-8a93-1378cf8f9183.png)

`
Copying data from package PyQt5...
copying /Users/znl/.pyenv/versions/pacs_env/lib/python3.6/site-packages/PyQt5/Qt.so -> build/exe.macosx-10.13-x86_64-3.6/lib/PyQt5/Qt.so
copying /Users/znl/.pyenv/versions/pacs_env/lib/python3.6/site-packages/PyQt5/QtBluetooth.so -> build/exe.macosx-10.13-x86_64-3.6/lib/PyQt5/QtBluetooth.so
copying /Users/znl/.pyenv/versions/pacs_env/lib/QtGui.framework/Versions/5/QtGui -> build/exe.macosx-10.13-x86_64-3.6/lib/PyQt5/QtGui
error: [Errno 2] No such file or directory: '/Users/znl/.pyenv/versions/pacs_env/lib/QtGui.framework/Versions/5/QtGui'
`

When it copying data from package PyQt5 , at the step of copying QtGui module ,it change it's directory as it should be,so it can't find the file.

- My questions：What the problem and how can i fix it.

**Comment by marcelotduarte** [comment]
cx_Freeze 6 has been release. Can you try again? Can I close the issue?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
