### ISSUE TITLE
[venv] Error when freezing when code needs distutils

### ISSUE THREAD

**Issue by vincent-lg** [marcelotduarte/cx_Freeze#443]
### Summary of issue

When trying to freeze a Python code that imports `distutils`, such as `python-redmine`, one gets an error, not when freezing, but afterward: a lot of things are missing from the frozen `disutils`.  Upon examination, this was due to the fact that we tried to freeze while in a virtual environment, and `distutils` is abridged (to use an understatement) in a virtual environment.

### Ugly fix

There is a quick fix to it, as you might be aware: its full description is [here](https://gist.github.com/nicoddemus/ca0acd93a20acbc42d1d).  It has the advantage of allowing to freeze from a virtual environment.

I don't know if this solution is acceptable.  Building from outside a virtual environment wasn't an option in our case (and when the source code has a lot of dependencies, it is definitely not a good strategy).  Shouldn't such a quick fix be added to cx_Freeze standard processing?  Or something even nicer.

Thank you for all your work,

**Comment by marcelotduarte** [comment]
cx_Freeze 6 has been release. Can you try again? Can I close the issue?
The workaround is no longer needed either.

**Comment by vashek** [comment]
cx_Freeze 6 doesn't solve this.

**Comment by marcelotduarte** [comment]
Some time ago I put this sample:
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/distutils
It is based on a gist[1]

In Linux with py37 runs.
In Windows with py37-32 runs.
I'm running in venv in both systems.
I don't use the workaround and cx-freeze copies from original interpreter, as opposed by the post on gist[1]: "The workaround used was to tell cx-freeze to exclude distutils and add the package from the original interpreter (not from the virtualenv) manually."

[1] https://gist.github.com/nicoddemus/ca0acd93a20acbc42d1d

**Comment by marcelotduarte** [comment]
Here the results (grep) in linux. On windows it has similar results.
```
(rm -rf build/exe.linux-x86_64-3.7/; python setup.py build; build/exe.linux-x86_64-3.7/test_dist) |grep distutils
copying /home/marcelo/.local/venv/distutils/lib/python3.7/site-packages/cx_Freeze/bases/Console -> build/exe.linux-x86_64-3.7/test_dist
m __startup__               /home/marcelo/.local/venv/distutils/lib/python3.7/site-packages/cx_Freeze/initscripts/__startup__.py
P distutils                 /usr/lib/python3.7/distutils/__init__.py
m distutils.archive_util    /usr/lib/python3.7/distutils/archive_util.py
m distutils.cmd             /usr/lib/python3.7/distutils/cmd.py
P distutils.command         /usr/lib/python3.7/distutils/command/__init__.py
m distutils.config          /usr/lib/python3.7/distutils/config.py
m distutils.core            /usr/lib/python3.7/distutils/core.py
m distutils.debug           /usr/lib/python3.7/distutils/debug.py
m distutils.dep_util        /usr/lib/python3.7/distutils/dep_util.py
m distutils.dir_util        /usr/lib/python3.7/distutils/dir_util.py
m distutils.dist            /usr/lib/python3.7/distutils/dist.py
m distutils.errors          /usr/lib/python3.7/distutils/errors.py
m distutils.extension       /usr/lib/python3.7/distutils/extension.py
m distutils.fancy_getopt    /usr/lib/python3.7/distutils/fancy_getopt.py
m distutils.file_util       /usr/lib/python3.7/distutils/file_util.py
m distutils.filelist        /usr/lib/python3.7/distutils/filelist.py
m distutils.log             /usr/lib/python3.7/distutils/log.py
m distutils.spawn           /usr/lib/python3.7/distutils/spawn.py
m distutils.sysconfig       /usr/lib/python3.7/distutils/sysconfig.py
m distutils.text_file       /usr/lib/python3.7/distutils/text_file.py
m distutils.util            /usr/lib/python3.7/distutils/util.py
m distutils.version         /usr/lib/python3.7/distutils/version.py
m distutils.versionpredicate /usr/lib/python3.7/distutils/versionpredicate.py
m test_dist__init__         /home/marcelo/.local/venv/distutils/lib/python3.7/site-packages/cx_Freeze/initscripts/Console.py
? os.path imported from distutils.file_util, os, pkgutil, py_compile, sysconfig, tracemalloc, unittest, unittest.util
Hello distutils
<module 'distutils.dist' from '/home/marcelo/M/github/cx_Freeze/cx_Freeze/samples/distutils/build/exe.linux-x86_64-3.7/lib/library.zip/distutils/dist.pyc'>
<module 'distutils.sysconfig' from '/home/marcelo/M/github/cx_Freeze/cx_Freeze/samples/distutils/build/exe.linux-x86_64-3.7/lib/library.zip/distutils/sysconfig.pyc'>
```

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.

**Comment by purna135** [comment]
I tested this on Python 3.10, and it works fine, but it fails on Python 3.12. It seems like something changed in the way cx_Freeze handles dependencies in this version. Has anyone found a workaround for Python 3.12?

**Comment by marcelotduarte** [comment]
Not cx_Freeze. Python 3.12 removed [distutils](https://docs.python.org/3/library/distutils.html#module-distutils).
