### ISSUE TITLE
使用cx_Freeze对python文件进行打包生成一个可执行的文件，可以把这个可执行文件移植到arm平台上执行吗

### ISSUE THREAD

**Issue by faihung** [marcelotduarte/cx_Freeze#447]

**Comment by bertrandlo** [comment]
cx_Freeze only integrate the DLLs and construct a wrapper for the main script to call python.DLL. the wrapper was platform-depend.  Mostly, these "compilers" most build for the same operation system only.

**Comment by s0lst1ce** [comment]
Shouldn't this be closed since it's asking for something mentioned in the documentation ?

**Comment by anthony-tuininga** [comment]
Yes.
