### ISSUE TITLE
DLL load failed while started the app

### ISSUE THREAD

**Issue by jekoie** [marcelotduarte/cx_Freeze#449]
hi, i use python2.7 and wxpython v4.0.0a1 build a app and install it at windows xp , i packeged it use cx_freeeze module, it run well in some windows xp system, but sometime it run DLL load errrors?
can anyone help me?
![img_1810](https://user-images.githubusercontent.com/6836400/50389400-d0a35580-0764-11e9-8475-308ce23d994e.JPG)

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
