### ISSUE TITLE
Symbol not found: __PySlice_AdjustIndices for importing ctypes in Mac OS

### ISSUE THREAD

**Issue by azuring2** [marcelotduarte/cx_Freeze#452]
Our client ran the Mac release build, then quited immediately with following messages. 
The line 818 of ttLib is only simple  "import ctypes" . 

The binary build works well in the dev machine (macOS El Capitan) and fail in the target client machine (macOS Sierra) . Python 2.7.15 (64 bit) with cx_Freeze 5.1.1 using bdist_mac ,.

Could you please give some hint to debug?

------------------------------------------------
Traceback (most recent call last):\
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run\
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run\
  File "./utest2.py", line 15, in <module>\
  File "ttLib.py", line 818, in init ttLib\
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 7, in <module>\
ImportError: dlopen(/Users/intellisqa/Downloads/build/test_build/lib/_ctypes.so, 2): Symbol not found: __PySlice_AdjustIndices\
  Referenced from: /Users/intellisqa/Downloads/build/test_build/lib/_ctypes.so\
  Expected in: flat namespace\
 in /Users/intellisqa/Downloads/build/test_build/lib/_ctypes.so\

**Comment by azuring2** [comment]
We observed that when we install newest python in the target machine with following command, the above error disappearing. 
>> brew install python@2

Seems cx_Freeze forgot to copy something important about python under Mac OS.

**Comment by marcelotduarte** [comment]
cx_Freeze 6 has been release. Can you try again? Can I close the issue?
NOTE: cx_Freeze 6 suports python 3.5 to 3.7

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
