### ISSUE TITLE
cx_Freeze 5.1.1 doesn't include dump.py in lib\sqlite3 directory (Win10, Python 3.6 32bit)

### ISSUE THREAD

**Issue by shoemak** [marcelotduarte/cx_Freeze#454]
Hello!
I have an App where I make a dump of my PostgreSQL database into Sqlite3 database.
and I use this piece of code:
        ....
        conSQLITE = sqlite3.connect(":memory:")
        curSQLITE = conSQLITE.cursor()
        ...
        # copying fields and so on ....
        ...
        mydump = ""
        for line in conSQLITE.iterdump():
            mydump = mydump + line + "\n"
        con = sqlite3.connect(pathToExportBase)
        cur = con.cursor()
        cur.executescript(mydump)
        con.close()
        ...

When I start my program packed, using cx_Freeze, this code results with error:
"ModuleNotFoundError. No module named 'sqlite3.dump'"

The problem cured by copying file dump.py to \lib\sqlite3\ from sqlite3 directory of Python36 install directory.

I think it's a bug, because I tryed to make a package of the same application, using PyInstaller - all work fine with the dump, but the Pyinstaller has another big problem :-))) its executives start veeeeeeeeryyyy slow on my computer whereas cx_Freeze starts very quickly despite that my app in cx_Freeze weigths 50 Mb more than PyInstaller sibling.

**Comment by marcelotduarte** [comment]
cx_Freeze 6 has been release. Can you try again? Can I close the issue?

**Comment by marcelotduarte** [comment]
No response.
