### ISSUE TITLE
possible bug with including vcruntime dll on windows

### ISSUE THREAD

**Issue by LakiWizard** [marcelotduarte/cx_Freeze#455]
Greetings! I have been using cx_freeze to package a small game I made using pygame, and recently discovered that it may not work without python installed due to a missing file VCRUNTIME140.dll. The docs suggested to use the include_msvcr switch when building, which I added to the options in my setup.py file. However, cx_freeze seems to place the dll in the pygame subdirectory in the build directory, so I needed to manually move it where the executable is before it could work. This is on windows 10 with python 3.6.6 and cx_freeze 5.1.1

**Comment by LakiWizard** [comment]
It seems to be the same problem as #372 except the dll is copied into lib/pygame rather than lib, for some reason.

**Comment by marcelotduarte** [comment]
cx_Freeze 6 has been release. Can you try again? Can I close the issue?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
