### ISSUE TITLE
[Linux Py3.6] can't install with pip or manually

### ISSUE THREAD

**Issue by tuxerrante** [marcelotduarte/cx_Freeze#459]
Hi,
I have a compilation error while trying to install the package either from pip or manually.

1.  If I try to install in the standard way this is what I get:
`$ pip3 install cx_Freeze
Collecting cx_Freeze
  Using cached https://files.pythonhosted.org/packages/5f/16/eab51d6571dfec2554248cb027c51babd04d97f594ab6359e0707361297d/cx_Freeze-5.1.1.tar.gz
Building wheels for collected packages: cx-Freeze
  Building wheel for cx-Freeze (setup.py) ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-srmur119/cx-Freeze/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ty81y3yu --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/cx_Freeze
  copying cx_Freeze/main.py -> build/lib.linux-x86_64-3.6/cx_Freeze
  copying cx_Freeze/hooks.py -> build/lib.linux-x86_64-3.6/cx_Freeze
  copying cx_Freeze/__init__.py -> build/lib.linux-x86_64-3.6/cx_Freeze
  copying cx_Freeze/freezer.py -> build/lib.linux-x86_64-3.6/cx_Freeze
  copying cx_Freeze/finder.py -> build/lib.linux-x86_64-3.6/cx_Freeze
  copying cx_Freeze/dist.py -> build/lib.linux-x86_64-3.6/cx_Freeze
  copying cx_Freeze/common.py -> build/lib.linux-x86_64-3.6/cx_Freeze
  copying cx_Freeze/setupwriter.py -> build/lib.linux-x86_64-3.6/cx_Freeze
  copying cx_Freeze/windist.py -> build/lib.linux-x86_64-3.6/cx_Freeze
  copying cx_Freeze/macdist.py -> build/lib.linux-x86_64-3.6/cx_Freeze
  creating build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
  copying cx_Freeze/initscripts/__startup__.py -> build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
  copying cx_Freeze/initscripts/SharedLibSource.py -> build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
  copying cx_Freeze/initscripts/Console.py -> build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
  copying cx_Freeze/initscripts/SharedLib.py -> build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
  copying cx_Freeze/initscripts/ConsoleSetLibPath.py -> build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/asmodule
  copying cx_Freeze/samples/asmodule/asmodule.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/asmodule
  copying cx_Freeze/samples/asmodule/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/asmodule
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/wx
  copying cx_Freeze/samples/wx/wxapp.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/wx
  copying cx_Freeze/samples/wx/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/wx
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/matplotlib
  copying cx_Freeze/samples/matplotlib/matplotlib_eg.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/matplotlib
  copying cx_Freeze/samples/matplotlib/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/matplotlib
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/simple
  copying cx_Freeze/samples/simple/hello.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/simple
  copying cx_Freeze/samples/simple/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/simple
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/advanced
  copying cx_Freeze/samples/advanced/advanced_1.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/advanced
  copying cx_Freeze/samples/advanced/advanced_2.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/advanced
  copying cx_Freeze/samples/advanced/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/advanced
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/relimport
  copying cx_Freeze/samples/relimport/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/relimport
  copying cx_Freeze/samples/relimport/relimport.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/relimport
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/openpyxl
  copying cx_Freeze/samples/openpyxl/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/openpyxl
  copying cx_Freeze/samples/openpyxl/test_openpyxl.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/openpyxl
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/zope
  copying cx_Freeze/samples/zope/qotd.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/zope
  copying cx_Freeze/samples/zope/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/zope
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt4
  copying cx_Freeze/samples/PyQt4/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt4
  copying cx_Freeze/samples/PyQt4/PyQt4app.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt4
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/service
  copying cx_Freeze/samples/service/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/service
  copying cx_Freeze/samples/service/ServiceHandler.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/service
  copying cx_Freeze/samples/service/Config.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/service
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt5
  copying cx_Freeze/samples/PyQt5/PyQt5app.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt5
  copying cx_Freeze/samples/PyQt5/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt5
  creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/Tkinter
  copying cx_Freeze/samples/Tkinter/SimpleTkApp.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/Tkinter
  copying cx_Freeze/samples/Tkinter/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/Tkinter
  running build_ext
  building 'cx_Freeze.util' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/source
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c source/util.c -o build/temp.linux-x86_64-3.6/source/util.o
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/source/util.o -o build/lib.linux-x86_64-3.6/cx_Freeze/util.cpython-36m-x86_64-linux-gnu.so
  creating build/temp.linux-x86_64-3.6/source/bases
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c source/bases/Console.c -o build/temp.linux-x86_64-3.6/source/bases/Console.o
  creating build/lib.linux-x86_64-3.6/cx_Freeze/bases
  x86_64-linux-gnu-gcc -pthread build/temp.linux-x86_64-3.6/source/bases/Console.o -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -o build/lib.linux-x86_64-3.6/cx_Freeze/bases/Console -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -lpthread -ldl -lutil -lm -lexpat -L/usr/lib -lz -lexpat -s
  /usr/bin/ld: cannot find -lz
  collect2: error: ld returned 1 exit status
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  Failed building wheel for cx-Freeze
  Running setup.py clean for cx-Freeze
Failed to build cx-Freeze
Installing collected packages: cx-Freeze
  Running setup.py install for cx-Freeze ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-srmur119/cx-Freeze/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kdc7x8xa/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cx_Freeze
    copying cx_Freeze/main.py -> build/lib.linux-x86_64-3.6/cx_Freeze
    copying cx_Freeze/hooks.py -> build/lib.linux-x86_64-3.6/cx_Freeze
    copying cx_Freeze/__init__.py -> build/lib.linux-x86_64-3.6/cx_Freeze
    copying cx_Freeze/freezer.py -> build/lib.linux-x86_64-3.6/cx_Freeze
    copying cx_Freeze/finder.py -> build/lib.linux-x86_64-3.6/cx_Freeze
    copying cx_Freeze/dist.py -> build/lib.linux-x86_64-3.6/cx_Freeze
    copying cx_Freeze/common.py -> build/lib.linux-x86_64-3.6/cx_Freeze
    copying cx_Freeze/setupwriter.py -> build/lib.linux-x86_64-3.6/cx_Freeze
    copying cx_Freeze/windist.py -> build/lib.linux-x86_64-3.6/cx_Freeze
    copying cx_Freeze/macdist.py -> build/lib.linux-x86_64-3.6/cx_Freeze
    creating build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/__startup__.py -> build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/SharedLibSource.py -> build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/Console.py -> build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/SharedLib.py -> build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
    copying cx_Freeze/initscripts/ConsoleSetLibPath.py -> build/lib.linux-x86_64-3.6/cx_Freeze/initscripts
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/asmodule
    copying cx_Freeze/samples/asmodule/asmodule.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/asmodule
    copying cx_Freeze/samples/asmodule/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/asmodule
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/wx
    copying cx_Freeze/samples/wx/wxapp.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/wx
    copying cx_Freeze/samples/wx/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/wx
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/matplotlib
    copying cx_Freeze/samples/matplotlib/matplotlib_eg.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/matplotlib
    copying cx_Freeze/samples/matplotlib/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/matplotlib
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/simple
    copying cx_Freeze/samples/simple/hello.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/simple
    copying cx_Freeze/samples/simple/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/simple
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/advanced
    copying cx_Freeze/samples/advanced/advanced_1.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/advanced
    copying cx_Freeze/samples/advanced/advanced_2.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/advanced
    copying cx_Freeze/samples/advanced/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/advanced
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/relimport
    copying cx_Freeze/samples/relimport/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/relimport
    copying cx_Freeze/samples/relimport/relimport.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/relimport
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/openpyxl
    copying cx_Freeze/samples/openpyxl/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/openpyxl
    copying cx_Freeze/samples/openpyxl/test_openpyxl.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/openpyxl
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/zope
    copying cx_Freeze/samples/zope/qotd.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/zope
    copying cx_Freeze/samples/zope/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/zope
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt4
    copying cx_Freeze/samples/PyQt4/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt4
    copying cx_Freeze/samples/PyQt4/PyQt4app.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt4
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/service
    copying cx_Freeze/samples/service/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/service
    copying cx_Freeze/samples/service/ServiceHandler.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/service
    copying cx_Freeze/samples/service/Config.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/service
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt5
    copying cx_Freeze/samples/PyQt5/PyQt5app.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt5
    copying cx_Freeze/samples/PyQt5/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/PyQt5
    creating build/lib.linux-x86_64-3.6/cx_Freeze/samples/Tkinter
    copying cx_Freeze/samples/Tkinter/SimpleTkApp.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/Tkinter
    copying cx_Freeze/samples/Tkinter/setup.py -> build/lib.linux-x86_64-3.6/cx_Freeze/samples/Tkinter
    running build_ext
    building 'cx_Freeze.util' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/source
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c source/util.c -o build/temp.linux-x86_64-3.6/source/util.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/source/util.o -o build/lib.linux-x86_64-3.6/cx_Freeze/util.cpython-36m-x86_64-linux-gnu.so
    creating build/temp.linux-x86_64-3.6/source/bases
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c source/bases/Console.c -o build/temp.linux-x86_64-3.6/source/bases/Console.o
    creating build/lib.linux-x86_64-3.6/cx_Freeze/bases
    x86_64-linux-gnu-gcc -pthread build/temp.linux-x86_64-3.6/source/bases/Console.o -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -o build/lib.linux-x86_64-3.6/cx_Freeze/bases/Console -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -lpthread -ldl -lutil -lm -lexpat -L/usr/lib -lz -lexpat -s
    /usr/bin/ld: cannot find -lz
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-srmur119/cx-Freeze/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kdc7x8xa/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-srmur119/cx-Freeze/
`

1.  So I tried to download the package and I've run
`$ python3 /home/alex/.local/lib/python3.6/site-packages/cx_Freeze/setup.py build`
which gives me a lot of path errors that I can fix in this way:
from
`os.path.join("cx_Freeze", "initscripts")`
to
`os.path.join(os.path.dirname(os.path.abspath(__file__)), "cx_Freeze", "initscripts")`

but then the problem is propagated elsewhere:
`$ python3 /home/alex/.local/lib/python3.6/site-packages/cx_Freeze/setup.py build
 current directory: /home/alex/.local/lib/python3.6/site-packages/cx_Freeze
running build
running build_py
error: package directory 'cx_Freeze' does not exist
`

**Comment by s0lst1ce** [comment]
@tuxerante I had this problem once under windows. I had to remove all of cx_Freeze to be able to install it correctly. This had happened to me after having installed a new version of the software or when upgrading python.

**Comment by marcelotduarte** [comment]
The output is a little hard to read, but what I've seen is that this manual method is wrong.
This should be a pip error that should be leaving locked files on the uninstall. So you can:
1) Uninstall: pip uninstall cx_Freeze
2) Manually remove the cx_Freeze directory that may have been in site-packages
3) Update the pip: pip install -U pip
4) And the setuptools, if you are using
5) Install again: pip install cx_Freeze --no-cache-dir
