### ISSUE TITLE
cx_Freeze source does not support `setup.py develop`

### ISSUE THREAD

**Issue by TTimo** [marcelotduarte/cx_Freeze#460]
Debian Buster - Python 3.7 - cx_Freeze github master:

Observed: I can run `python3 setup.py develop` in the cx_Freeze tree, but when I try to package a small test project, I get an error `cx_Freeze.freezer.ConfigError: no base named Console`

Expected result: support `setup.py develop` mode so it's easier to install/debug/test.

Thanks!

**Comment by anthony-tuininga** [comment]
Is this still an issue with cx_Freeze 6 just released? I just tried it myself and it worked fine. This was on Fedora 30, not Debian, though!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
