### ISSUE TITLE
Pip installs cx_Freeze 5.1.1 and not 6.0b1

### ISSUE THREAD

**Issue by s0lst1ce** [marcelotduarte/cx_Freeze#461]
Hey recently I've reinstalled some of my OSs and I reinstalled python (3.7) and cx_Freeze with pip. When I tried to compile a project of mine I had an issue which I know had been fixed with cx_Freeze 6 (#324). This surprised me and I ended up noticing that pip automatically installs cx_Freeze 5.1.1 and not 6.0b1. It's not a big issue but I think it's too bad people don't get the 6th version which fixed a lot of bugs I was experiencing.

**Comment by anthony-tuininga** [comment]
Yes, this is because cx_Freeze 6.0b1 is designated a beta. You have to use this command instead:

``python -m pip install cx_Freeze==6.0b1``

I am hoping to make a non-beta release of cx_Freeze 6 shortly, however!
