### ISSUE TITLE
msi installer not installing into specified directory

### ISSUE THREAD

**Issue by mhogg** [marcelotduarte/cx_Freeze#463]
Hi,

I have been using cx_Freeze to build executables on Windows 7, but thought I would try building an msi using build_msi. The msi file is created ok, but it always installs into the c:\ drive, ignoring the specified directory. I found an identical error here:

https://sourceforge.net/p/cx-freeze/mailman/message/31155211/

I tried the suggestions in this message, include setting initial_target_dir (on the build_msi options in the setup.py file) and install_dir (on the install options), but the same thing occurs. I have also tried cx_Freeze versions 5.1.1 and 6.01b.

Any thoughts on this? If you gave me a clue on where to look, I might be able to figure it out and submit a fix.

Cheers,
Michael

**Comment by florianbehrens** [comment]
I have the same problem with cx_Freeze version 6.0.0 on Windows 10.

**Comment by florianbehrens** [comment]
After some research (I'm not a Windows pro) I think it has something to do with the fact, that on my machine the registry key 

`HKLM\SOFTWARE\Policies\Microsoft\Windows\Installer\AlwaysInstallElevated`

is set to 1 which seems to give a non-admin user the right to install MSIs (more info [here](https://docs.microsoft.com/en-us/windows/win32/msi/installing-a-package-with-elevated-privileges-for-a-non-admin)). Setting this value to 0 results in the installation process prompting for admin credentials and the installation ends up at the right place.

**Comment by florianbehrens** [comment]
Some further digging in the wild of the Windows documentation got a [solution/workaround (?)](https://social.msdn.microsoft.com/Forums/windows/en-US/36036c55-2b64-4026-8ecc-39a251807273/setup-project-not-picking-up-default-location-during-install?forum=winformssetup) that at least works on my machine:

It requires to put the `TARGETDIR` variable into the `SecureCustomProperties` property of the `Property` table of the MSI. For whatever reason. It can be tested with the [Orca](https://docs.microsoft.com/en-us/windows/win32/msi/orca-exe) tool which is part of the Windows SDK.

This is also what was done in the [MSI build of CPython 3.4](https://github.com/python/cpython/blob/v3.4.10/Tools/msi/msi.py#L296).

**Comment by machobymb** [comment]
I use under Windows 10 codepage 852, but when I create a MSI installer with cx_Freeze, I don't view UTF-8 chars in installation windows (the source encoding is UTF-8, and I import the encodings module in setup.py).
When I modify HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\OEMCP to 65001, then all character is correct. I don't like modify Registry.
How can I setup cx_Freeze correct?
