### ISSUE TITLE
Is this project dead or just extremely sleepy?

### ISSUE THREAD

**Issue by mikedarcy** [marcelotduarte/cx_Freeze#465]
No commits for six months. A 6.0 release that never made it out of beta and up to PyPi, yet seems  functional and provides needed features. It is a bit disconcerting.

This is an important component of a software stack I work on and I've seen it used in quite a few other projects as well. Should we be worried?

@anthony-tuininga Any comment or guidance?

**Comment by anthony-tuininga** [comment]
It is not dead. Just very sleepy for the past six months. ;-) In the past I was able to work on it during work hours. Now it is something I do in my spare time, of which there has been little for the past six months. I'm hopeful that I will have more time again soon!

**Comment by ecejeff** [comment]
It would be really great to have a 6.0 (even 6.0b1) wheel for Python 3.7 on PyPI

**Comment by mikedarcy** [comment]
> It would be really great to have a 6.0 (even 6.0b1) wheel for Python 3.7 on PyPI

I agree wholeheartedly. Putting up 6.0b1 to PyPi as-is would be a huge help for those currently using it.

**Comment by s0lst1ce** [comment]
I totally agree. I have lots and lots of people always asking me what they should use to compile their scripts and I always turn them to cx_Freeze. However few of them get far enough to compile cx_Freeze 6 and as the fifth version is so full of bugs I have to admit that I prefer to tell them to put a hold on it for now. I'd be very grateful of you to get the project back on track.
I have little competences in python and none in C but if I could be of some help I'd be ready to try.

**Comment by anthony-tuininga** [comment]
Thanks. I have a vacation coming up and a couple of other things I need to do first, but I should have more time by the end of May at the latest. Please continue to be patient -- or better yet, let me know which issues are the ones that need to get corrected in a final 6.0 release. :-)

**Comment by anthony-tuininga** [comment]
So, maybe not the end of May. :-( But soon!

**Comment by s0lst1ce** [comment]
Well for me the biggest issue is that sometimes for GUI applications, libraries are missing when running the compiled version on another computer.

**Comment by bigretromike** [comment]
Wishing you the best!

**Comment by anthony-tuininga** [comment]
cx_Freeze 6 has just been released.
