### ISSUE TITLE
executable not looking from compiled lib

### ISSUE THREAD

**Issue by sunilk-n** [marcelotduarte/cx_Freeze#467]
I had created an exe with cx_Freeze and its working fine in my PC... but when I take the build to another system, Its just looking from the 'virtualenv/' but not from the compiled library... can anyone help with this...
```
   options = {
        'build_exe':
             'includes': ['typing'],
             'add_to_path': True}
    }
    setup(name='App Name',
          version=0.1.0,
          description='App Description',
          options=options,
          executables=[Executable("finalExe.py", base='Win32GUI')])

```
Am I doing anything wrong with anything?

**Comment by marcelotduarte** [comment]
I see a missing '{' after 'build_exe'
should be:
'build_exe': {
What you want to say with "Its just looking from the 'virtualenv/' but not from the compiled library."
You receive a traceback? Can you provide?
If you resolved the issue, please close.

**Comment by sunilk-n** [comment]
'{' is a typo and that is working fine.

"Its just looking from the 'virtualenv/' but not from the compiled library."
Here, when I run the code from one system where I added the python environment, the code is runnin good with that environment path. But when I use the same code in another system, the python environment python is missing and as I need to run the code from basic python interpretor and not from an environment path

**Comment by marcelotduarte** [comment]
Can you provide a traceback and more information, like python version, cx_freeze version?
