### ISSUE TITLE
-l gcov required on arm platform

### ISSUE THREAD

**Issue by reetzjonas** [marcelotduarte/cx_Freeze#471]
Hi,

I tried to build cx_freeze 5.0.2 on two different arm based devices and had the following error on running "python setup.py install"

Output: https://pastebin.com/TYpZuFy0

The tested systems were:

> Debian 6.0.10
> armv5tel
> Linux 3.8.13 #12
> gcc version 4.4.5 (Debian 4.4.5-8)
> Python 3.6.8

> Debian 9.6
> armv7l
> Linux 4.4.153-mvebu #36
> gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
> Python 3.6.8

To get around this problem I had to add an `extraArgs` entry on line 98 in setup.py

`extraArgs.append("-lgcov")`

After that the build process worked fine. I also tried this on x86 systems but they worked without this change.

I am not very deep in C so I dont know the exact effects on this. Maybe someone can have a look on this.

Best regards

JonasR

**Comment by reetzjonas** [comment]
I initially tried it on cx_freeze 5.1.1 which gives the same behaviour

**Comment by marcelotduarte** [comment]
Please, inform the value of:
sys.platform
os.name
I'll try do a patch

**Comment by reetzjonas** [comment]
Thanks for this :)
```
>>> import os
>>> import sys
>>> sys.platform
'linux2'
>>> os.name
'posix'
```

**Comment by marcelotduarte** [comment]
This values are from py27?
Your initial issue is about py36. 
From what I saw you are using a python compiled from sources, am I right? And it is compiled with gcov. Must be compiled without gcov as the default.

**Comment by reetzjonas** [comment]
You are right the output was from py27
This one is from py36
```
Python 3.6.8 (default, May 22 2019, 14:03:27)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import os
>>> sys.platform
'linux'
>>> os.name
'posix'
```

I will see if I can recompile it without gcov and and give you feedback

**Comment by marcelotduarte** [comment]
cx_Freeze 6 has been release. Can you try again? Can I close the issue?
