### ISSUE TITLE
Lot of GetDependentFiles() errors while building SimpleTkApp.exe

### ISSUE THREAD

**Issue by Suzumizaki** [marcelotduarte/cx_Freeze#473]
Due to SHA-1: b55577333e2aa7274f013fe18eb08d094572d2f9, many `GetDependentFiles()` related errors are reported while building `SimpleTkApp.exe` from `cx_Freeze/samples/Tkinter` .

The one of the messages are below:

    error during GetDependentFiles() of "C:\3bin\python\3.7.4_x64\tcl\tk8.6\ttk\vistaTheme.tcl": (0, '間違ったフォーマットのプログラムを読み込もうとしました。', 'C:\\3bin\\python\\3.7.4_x64\\tcl\\tk8.6\\ttk\\vistaTheme.tcl', 11, None)

There's no need to check dependencies against `.tcl`, `.msg`, `.enc`, picture files, or other non-executable files.

Thanks.

**Comment by Suzumizaki** [comment]
This issue would be resolved after https://github.com/anthony-tuininga/cx_Freeze/pull/492 applied.

**Comment by marcelotduarte** [comment]
Can you close the issue? #492 merged.
