### ISSUE TITLE
The Most Recent Release / Beta Was 2017 , Post an Updated Release Or Beta for python 3.7 Fix

### ISSUE THREAD

**Issue by CanIGetaPR** [marcelotduarte/cx_Freeze#496]
https://pypi.org/project/cx_Freeze/#history

The version of cx_freeze that pip installs (5.1.1) has the issue of creating executables #399 

The support for python 3.7 was added in 2018 in this commit 5461c71cbef64f96e24c3c91891bda44f369b6ff but there is no current release that contains this fix as the most recent release and beta was 2017

**Comment by anthony-tuininga** [comment]
Yes, I agree. Its been far too long. I am hoping to make a new release soon. Since this is done in my spare time, though, its been taking far longer than I had hoped. The work done by @marcelotduarte is much appreciated. I am reviewing his changes and merging the ones that are obvious to me. Once that is done I'll make a new release and then review the more complex pull requests later.

**Comment by tamenol** [comment]
Maybe it can be put in the readme that currently there are bugs when using Python3.7 until the fix is released? It could have saved me some hours of debugging.

**Comment by marcelotduarte** [comment]
Python 3.7 is not mentioned in the readme, about session. See https://github.com/anthony-tuininga/cx_Freeze/tree/v5.x
And version 6.0b1 is a beta version.

**Comment by anthony-tuininga** [comment]
@marcelotduarte, I have pushed the release notes and I am planning on making this release early next week -- unless you think there are some additional patches that ought to be applied first. After this release there will be a 6.0.1 (or 6.1 depending on the type of patches) relatively soon thereafter (a month or so at most).

**Comment by marcelotduarte** [comment]
I think it will run well on windows, but on Linux, without the #494 patch there will still be problems with tools that use cffi or that use external dl, like PIL, bcrypt and cryptography. The #479 patch is just a whim to make it easier in some cases. But if you have no time to review, make this release.

**Comment by anthony-tuininga** [comment]
Thanks. I'll take a look next week.

**Comment by anthony-tuininga** [comment]
I have run into some build issues...so unfortunately another delay. :-(

**Comment by marcelotduarte** [comment]
If you find that I can assist in anything ... :-)

**Comment by anthony-tuininga** [comment]
Thanks. I just released cx_Freeze 6. I'm sure assistance will be needed as people upgrade. :-)
