### ISSUE TITLE
Throwing FileNotFoundError with orderedmultidict

### ISSUE THREAD

**Issue by akhilrajvc** [marcelotduarte/cx_Freeze#498]
Throwing FileNotFoundError  "build/exe.linux-x86_64-3.6/lib/orderedmultidict/__version__.py" with orderedmultidict
OS: Ubuntu 16.04 LTS
Python: 3.6.7

**Comment by marcelotduarte** [comment]
Can I help you? Please, post a test case and/or a trackback...

**Comment by marcelotduarte** [comment]
cx_Freeze 6 has been release. Can you try again? Can I close the issue?

**Comment by Shashank0719** [comment]
Hi @marcelotduarte ,

I ran into same issue and has cx-freeze 6 installed. But even it is missing _version_.py file. Could you help me here please?

**Comment by marcelotduarte** [comment]
https://github.com/Shashank0719 Please, post a test case and/or a trackback...

**Comment by marcelotduarte** [comment]
orderedmultidict uses magic import at __init__, and has the following comment:
Import all variables in __version__.py without explicit imports.

The likely solution will be to include it in the packages option.
For more information see the first answer of the faq.
https://cx-freeze.readthedocs.io/en/latest/faq.html

**Comment by Shashank0719** [comment]
Hi @marcelotduarte, 

Please find the below traceback:

_FileNotFoundError: [Errno 2] No such file or directory: '/home/shashank/application/build/exe.linux-x86_64-3.6/lib/orderedmultidict/__version__.py'_

I did try to put explicitly in packages option but it is not working.  I did provide packages=['orderedmultidict']

But it is not getting included. Please let me know your input on it.

Thanks

**Comment by marcelotduarte** [comment]
try to use includes, like:
`
includes = ['orderedmultidict.__version__']
`

**Comment by Shashank0719** [comment]
Thanks @marcelotduarte , That worked magically. But only query I have is why it is not working when I am using it like includes = ['orderedmultidict'] ? Any idea on it, because according to the documentation this is the way we should deal with this kind of issue.

**Comment by marcelotduarte** [comment]
As per documentation:
includes - ist of names of modules to include
packages - list of packages to include, which includes all submodules in the package
In that case, `orderedmultidict` is a package, `orderedmultidict.__version__` is a module
