### ISSUE TITLE
error: file 'C:\...\Temp\1\pip-req-build-zv8knuaw\cxfreeze-postinstall' does not exist

### ISSUE THREAD

**Issue by jschueller** [marcelotduarte/cx_Freeze#499]
when building cxfreeze 6 for conda-forge, python 3.6.7, it fails with:
```
error: file 'C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-zv8knuaw\cxfreeze-postinstall' does not exist
```

full logs here:
https://ci.appveyor.com/project/conda-forge/cx-freeze-feedstock/builds/27066845/job/l8womye6hph0gf6j

**Comment by adamkbmc** [comment]
I had the same issue building with python 3.7.4 - the cxfreeze-postinstall script just seems to be missing from the latest tar ball. I just pulled it directly from GitHub and dropped it into place

**Comment by marcelotduarte** [comment]
PR #511 will solve that.

**Comment by marcelotduarte** [comment]
Duplicate of #56

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
