### ISSUE TITLE
Can't install cx_Freeze on Ubuntu

### ISSUE THREAD

**Issue by careyshan** [marcelotduarte/cx_Freeze#500]
Hi,

When trying to install cx Freeze with `pip install cx-Freeze`
I get the following error: 

`Collecting cx-Freeze
  Using cached https://files.pythonhosted.org/packages/14/74/a76c12e4e357c79999191d5db259e66b46c57708515395c023d38e6bbbd7/cx_Freeze-6.0.tar.gz
Building wheels for collected packages: cx-Freeze
  Building wheel for cx-Freeze (setup.py) ... error
  ERROR: Command errored out with exit status 1:`

**Comment by marcelotduarte** [comment]
Please, verify if you have build-essential installed, or install it:
**sudo apt install build-essential**

**Comment by careyshan** [comment]
Hi,

build-essential is installed.

Thanks
Le gach dea ghui,
*Shane Carey*
*GIS and Data Solutions Consultant*

**Comment by careyshan** [comment]
But still no joy  unfortunately.
Thanks
Le gach dea ghui,
*Shane Carey*
*GIS and Data Solutions Consultant*

**Comment by marcelotduarte** [comment]
Do you have a complete error log?

**Comment by marcelotduarte** [comment]
run:
pip install cx-Freeze --log cx-Freeze.log
and attach the cx-Freeze.log

**Comment by careyshan** [comment]
[cx-Freeze.log](https://github.com/anthony-tuininga/cx_Freeze/files/3572884/cx-Freeze.log)
Cheers

**Comment by marcelotduarte** [comment]
You're using miniconda3. I think the error is on compiler from miniconda. See line 197 of the log:
lto1: internal compiler error: in lto_tag_to_tree_code, at lto-streamer.h:1005

Here, with Ubuntu 19.04 using standard libraries cx-Freeze install and run.
You can try using python from ubuntu.
**sudo apt install build-essential python3.7 python3.7-dev python3.7-venv**

**Comment by careyshan** [comment]
Ok I did that and I still get the same error when I then do a pip install `cx-Freeze`. Is there a way to remove miniconda3 and use Ubuntu standard libaries instead?
Thanks for your help

**Comment by careyshan** [comment]
Ok, I removed miniconda and it worked :)
Thanks for your help

**Comment by marcelotduarte** [comment]
Of course!

**Comment by GeniusPeterJiang** [comment]
I didn't have to remove miniconda, but I conda deactivate and it worked.
