### ISSUE TITLE
Version 6.0 still displays the earlier version 6.0b1

### ISSUE THREAD

**Issue by jpeg13** [marcelotduarte/cx_Freeze#503]
Version 6.0 still has `version = "6.0b1"` instead of `version = "6.0"`

https://github.com/anthony-tuininga/cx_Freeze/blob/6d43fad1ad382b1e491baa944864d3663fabdb1d/cx_Freeze/__init__.py#L1

**Comment by marcelotduarte** [comment]
We will correct in the next version. Thank you.
