### ISSUE TITLE
6.0 and PyQt5 import error: missing DLL

### ISSUE THREAD

**Issue by VegarS** [marcelotduarte/cx_Freeze#504]
I get an import error (missing DLL) with cx_Freeze 6 and PyQt5. Can be reproduced with the PyQt5 sample files:

![bilde](https://user-images.githubusercontent.com/1231463/64682042-0d44e780-d481-11e9-92c1-c61614ddcbd4.png)

Seems similar to #328, but the workaround there is not working.

Versions:
Python 3.7.3
PyQt5 5.13.0
cx_Freeze 6.0 (from pip/pypi)

**Comment by jpeg13** [comment]
Maybe you can get a workaround by manually copying the missing DLL (presumably MSVCP140.dll from Microsoft Visual C++ 2015 Redistributable package) into the PyQt5 subdirectory inside the build directory, or into the build directory itself. I get a similar error message with PySide and cx_Freeze 5.1.1 or 6.0 (but not 6.0b1), see [my comment](https://github.com/anthony-tuininga/cx_Freeze/issues/278#issuecomment-392075260) to #278.

**Comment by VegarS** [comment]
It seems like several DLLs are missing from build\exe.win-amd64-3.7\PyQt5.

To get it working I made a build with cx_Freeze 5.1.1 and copied over the extra DLLs that 5.1.1 included in that directory: python3.dll, Qt5Core.dll, Qt5Gui.dll, Qt5Network.dll, Qt5Widgets.dll and VCRUNTIME140.dll

**Comment by marcelotduarte** [comment]
I tested the sample file on Linux and it worked. I will test on Windows later.

**Comment by marcelotduarte** [comment]
I tested on Windows with py37-32. The workaround is to copy python3.dll to the directory where the executable was made. cx_Freeze copies python37.dll, but does not copy python3.dll. The vcruntime140.dll may also have to be copied when it no longer exists on the system. I will do a PR later.

**Comment by VegarS** [comment]
I can confirm that copying python3.dll to the executable directory works.

**Comment by Berserker66** [comment]
Same deal on PySide2, python3.dll is missing there as well

**Comment by stephenmhall** [comment]
adding an include_files to the python3.dll solves you forgetting to copy it manually.

**Comment by tamenol** [comment]
I have the same issue. I downgraded to python3.5.4 and problem solved. cx_freeze could successfully make an .msi and it can run without errors.

**Comment by zkn365** [comment]
“copy **python3.dll** to the directory where the executable was made” can solve my problem.
Python 3.7.4
PyQt5 5.13.0
cx_Freeze 6.0

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
