### ISSUE TITLE
zipimport.ZipImportError on python3.6/encodings/__init__.py

### ISSUE THREAD

**Issue by GGui** [marcelotduarte/cx_Freeze#513]
Hello,

I'm trying to execute the https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/advanced with docker.

I built my docker image everything is ok ("docker build -t test1 .")
But i'm trying to run my image,i get the following exeption:

"Fatal Python error: Py_Initialize: Unable to get the locale encoding
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/encodings/__init__.py", line 31, in <module>
zipimport.ZipImportError: can't decompress data; zlib not available"

I can't find a solution. I may have forgotten something.

Thank you.

My docker file is:
FROM python:3.6-alpine3.6 as builder

RUN apk --no-cache upgrade && apk --no-cache add build-base tar musl-utils openssl-dev && pip3 install --upgrade pip
RUN pip3 install setuptools cx_Freeze

COPY . .
RUN ln -s /lib/libc.musl-x86_64.so.1 ldd
RUN ln -s /lib /lib64
#RUN pip3 install -r requirements.txt
RUN python3 setup.py build_exe

FROM alpine:3.6
RUN apk --no-cache upgrade && apk --no-cache add wget zlib
COPY --from=builder build/exe.linux-x86_64-3.6 /test/
USER nobody:nobody
ENTRYPOINT ["/test/advanced_1"]

**Comment by marcelotduarte** [comment]
In ubuntu this library is installed with the package 'zlib1g-dev', in alpine uses '-dev'?
I also think it has to be installed before you run python.
And I also think it's much more of a stackoverflow help question than a cx_Freeze issue.

**Comment by GGui** [comment]
Sorry but i thought it was an issue.
I think that the issue is not due to the "zlib-dev" lib. I change in my docker file from zlib to zlib-dev and there is no change.

In the seconde part of my docker file, i create an alpine image without installing python to run the exe file builded in the first part of my docker file.

I thought weird that the exe file try to read /usr/local/lib/python3.6/encodings/init.py while my image don't contain "python", does it?

Is that normal behavior?

Thank you for your help.

**Comment by marcelotduarte** [comment]
You mean two dockers right?
An executable generated by cx still has the same needs as python. It is a built-in python, where .py is compiled in bytecode. So something is probably missing from the docker to run.

**Comment by GGui** [comment]
I have 1 dockerfile but yes, i have 2 stages in my dockerfile, 1 buider stage and 1 runner stage.
After built, i can use the exe file without python rigth?

If i run the exe file in the builder stage. It works but python is installed.
you advise me to publish my request on stackoverflow?

**Comment by marcelotduarte** [comment]
I have little experience with docker. Just did tests. I've seen this error with python installed from sources, when trying to use cx_Freeze, it happens because it looks for some libraries for linux that don't have it installed by default.
So I don't see this as a cx_Freeze issue, but that doesn't stop me from trying to help, but maybe on SO you are luckier because you can find someone who understands docker.
One thing I can suggest to you is to look at how the python docker was made and try to create the same environment for the executable program. Say, look at:
https://github.com/docker-library/python/blob/88ba87d31a3033d4dbefecf44ce25aa1b69ab3e5/3.6/alpine/Dockerfile

And looking at this dockerfile, I see that python was compiled from sources, so it will depend on all those -dev that are installed ...

**Comment by GGui** [comment]
I have succeeded to run it!!
It's a little weird but i change in my dockerfile cx_Freeze==6.0b1, it works.

**Comment by marcelotduarte** [comment]
Weird...
Can you do a test with py37 and cx_Freeze == 6.0?

**Comment by GGui** [comment]
Same issue.
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/encodings/__init__.py", line 31, in <module>
zipimport.ZipImportError: can't decompress data; zlib not available

**Comment by GGui** [comment]
Do you think, it's a issue in cx_Freeze?

**Comment by marcelotduarte** [comment]
Yes. I am preparing some patches for full alpine support even without workarounds.

**Comment by marcelotduarte** [comment]
I made some patches that solve this issue. I hope they will be accepted soon.
Can you test with the attached [Dockerfile](https://github.com/anthony-tuininga/cx_Freeze/files/3663919/Dockerfile.txt) or adapt to your tests?

Let me know if it worked with you.

**Comment by GGui** [comment]
it's good. I tested it and it worked

thank you

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
