### ISSUE TITLE
cx_Freeze and TensorFlow

### ISSUE THREAD

**Issue by kiflowb777** [marcelotduarte/cx_Freeze#514]
System: Windows 10
cx_Freeze: 5.0.2
TensorFlow: GPU 1.14.0

After updating TensorFlow (1.13.1 to 1.14.0) and freeze, my project cannot run.
Its stop on import tensorflow:

```
Traceback (most recent call last):
  File "C:\python\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\python\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "project.py", line 45, in <module>
  File "C:\Project\Freeze\tensorflow\__init__.py", line 729, in <module>
    if _running_from_pip_package():
  File "C:\Project\Freeze\tensorflow\__init__.py", line 727, in _running_from_pip_package
    _current_file_location.startswith(dir_) for dir_ in _site_packages_dirs)
  File "C:\Project\Freeze\tensorflow\__init__.py", line 727, in <genexpr>
    _current_file_location.startswith(dir_) for dir_ in _site_packages_dirs)
TypeError: startswith first arg must be str or a tuple of str, not NoneType
```

The _site_packages_dirs in TensorFlow 1.14 keeps paths to Pythons Lib\site-packages.
On TensorFlow 1.13.1 after freezing my project works.

**Comment by kiflowb777** [comment]
I found a solution to the problem. To fix this, add the current directory (when the python project is freezed) to your sys.path before `import tensorflow as tf`

**Comment by aodiwei** [comment]
> I found a solution to the problem. To fix this, add the current directory (when the python project is freezed) to your sys.path before `import tensorflow as tf`

hi, what is '**the current directory**' ?

**Comment by nikzcodefreak** [comment]
> 
> 
> I found a solution to the problem. To fix this, add the current directory (when the python project is freezed) to your sys.path before `import tensorflow as tf`

what do you mean by current directory?

**Comment by gudong321** [comment]
what is the meaning of "add the current directory"? @kiflowb777

**Comment by shivomthakkar** [comment]
Can you please elaborate? @kiflowb777

**Comment by ghost** [comment]
> I found a solution to the problem. To fix this, add the current directory (when the python project is freezed) to your sys.path before `import tensorflow as tf`

Can you please elaborate?

**Comment by kiflowb777** [comment]
'the current directory' is a path where is the main *.py script or root directory of the project. 
You can get it with e.g `os.path.realpath(__file__)`
Add this path to sys.path.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
