### ISSUE TITLE
Win32Service.exe base doesn't get built

### ISSUE THREAD

**Issue by adamkbmc** [marcelotduarte/cx_Freeze#519]
When you build 6.0 the Win32Service.exe base doesn't get built, it's just silently ignored. You need to have cx_Logging available - not installed but a built distribution in a parallel directory without the version number (i.e. "cx_Logging" not "cx_Logging-2.2")

Also, the cx_Logging 2.2 tar ball is missing the cx_Logging.h so it doesn't build. I had to pull that from GitHub and drop it into cx_Logging\src

Finally, the cx_Freeze build will still fail if cx_Logging.h isn't also put into the root of cx_Logging!

Since cx_Logging hasn't changed in years could it not be included in the cx_Freeze tar ball so you can build Win32Service.exe without so much pain!?

**Comment by marcelotduarte** [comment]
@adamkbmc @darad @danielmenzel
Can you test the PR? (only if you have a C compiler)

`pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/650/head`
