### ISSUE TITLE
Executable error

### ISSUE THREAD

**Issue by qrdbr** [marcelotduarte/cx_Freeze#520]
Dear Friends,

I have 6 programs in python. I am using the cx_freeze library to generate these executables.
For 5 of them that are simple codes (file read, data cleanup ...) I was able to run .exe successfully.
However for one of the modules that work with multiple libraries (such as fbprophet, multiprocessing cython, scipy and others) at runtime .exe generates errors and does not execute.
It is noteworthy that without being through .exe the code executes perfectly (python myproject06.py).
Does anyone have any other suggestions for generating .exe that is efficient? Any alternatives?

Thanks!

Python Version:
Python 3.7.4

Operating System:
Windows 10 Pro
![code_Easy-Resize com](https://user-images.githubusercontent.com/51255841/66755296-16551a00-ee6e-11e9-95e4-4e9f4bb84598.jpg)
![error_Easy-Resize com](https://user-images.githubusercontent.com/51255841/66755297-16551a00-ee6e-11e9-83eb-0a01930a5f64.jpg)

**Comment by marcelotduarte** [comment]
try to include 'cython' in lowercase in packages list.

**Comment by qrdbr** [comment]
I had tried with cython in lowercase but still no work

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released. Can you try it?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
