### ISSUE TITLE
cx_Freeze looks for non-existent sqlite3.dll in virtualenv's DLLs directory in winodws

### ISSUE THREAD

**Issue by darad** [marcelotduarte/cx_Freeze#521]
Using Python 3.6 and cx-Freeze v6.0b1, `build_exe` fails because cx-freeze is looking for `sqlite3.dll` inside the (non-existent) `DLLs` directory inside the virtual environment from which it was invoked. If I copy the `sqlite3.dll` file into newly created `DLLs` inside my virtual environment folder, the build is successful.

**Comment by marcelotduarte** [comment]
Can you test with cx_Freeze 6.0?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
