### ISSUE TITLE
gestalt is a python module and should not be excluded by default

### ISSUE THREAD

**Issue by slizer2000** [marcelotduarte/cx_Freeze#522]
currently gestalt is in the initial exclude list in hooks.py if not a mac device. However, there is a python package with this name, resulting in module not found error

https://pypi.org/project/gestalt/

remove from hooks.py or allow overriding this list if specified in the requires/packages fields

**Comment by anthony-tuininga** [comment]
Done.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
