### ISSUE TITLE
libffi-7.dll is not grabbed for projects using ctypes module on Python 3.8

### ISSUE THREAD

**Issue by t-o-n-y-p** [marcelotduarte/cx_Freeze#523]
**Environment**: Windows

**Steps**:
1) download the project https://github.com/t-o-n-y-p/rssim/tree/4e21c9e9cbe23cc3f7eefc4ee876608b6db5aa9d and install all the requirements
2) patch the implementation of nullterm method in win32verstamp.py 
```
def nullterm(s):
  # get raw bytes for a NULL terminated unicode string.
  if sys.version_info[:2] < (3, 8):
    return (str(s) + '\0').encode('unicode-internal')
  else:
    return (str(s) + '\0').encode('utf-16le')
```
3) run `python setup.py build`

**Result**:
After freezing my project on Python 3.8, libffi-7.dll is missing in /lib folder, and that's what I get when launching the exe:
![image](https://user-images.githubusercontent.com/42129780/67045247-f445eb00-f13e-11e9-9ce7-5a8804491435.png)
The workaround is to copy this file manually.

Works fine on Python 3.7.5.

**Comment by Wyirren** [comment]
You just really saved my life

**Comment by hawkerm** [comment]
I just hit the same error as well, also using Python 3.8 x64 on Windows (latest master of cx_Freeze)

Dropping libffi-7.dll from the Python38\DLLs folder to the lib\ folder made it work right away at runtime.

**Comment by hawkerm** [comment]
This was also encountered by someone else from a thread on [stackoverflow](https://stackoverflow.com/questions/58953290/cx-freeze-importerror-dll-load-failed-failed-while-importing-ctypes-the-speci).

**Comment by marcelotduarte** [comment]
I will send a PR this week.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by lmayorga1980** [comment]
> I just hit the same error as well, also using Python 3.8 x64 on Windows (latest master of cx_Freeze)
> 
> Dropping libffi-7.dll from the Python38\DLLs folder to the lib\ folder made it work right away at runtime.

I was using a virtual environment `venv` and had to copy these extra `DLLs` in order to fix the issue.

```
cp /c/Python38/DLLs/tcl86t.dll venv/DLLs/
cp /c/Python38/DLLs/libffi-7.dll venv/DLLs/
cp /c/Python38/DLLs/tk86t.dll venv/DLLs/
```

**Comment by marcelotduarte** [comment]
@lmayorga1980 I didn't understand if you still have a problem. Do you use python on msys2/ming32 or for windows? For python for windows PR #556 solve this issue, for msys see at issue #596

**Comment by lmayorga1980** [comment]
Works for me with the following setup.

`Git Bash` on Windows.
Python `venv`

**Comment by FabeG** [comment]
With latest python 3.8 version (3.8.12) the version of  ``libffi.dll``  has changed  on Windows and became ``libffi-8.dll``. The windows PR #556 doesn't work anymore.
Replacing ``libffi-7.dll`` by ``libffi-8.dll`` in the ``load__ctypes`` function of ``hooks.py`` file did the trick for me, but I guess a more generic solution is needed...

**Comment by marcelotduarte** [comment]
PR #1279 fix this.

**Comment by marcelotduarte** [comment]
@FabeG From python.org and from Github Actions CI only 3.8.10 is available. Python 3.8.12 does not have binaries. How did you test it?

**Comment by FabeG** [comment]
@marcelotduarte Python 3.8.12 came with the Anaconda distribution (see https://docs.anaconda.com/anaconda/packages/py3.8_win-64/)

**Comment by nuffsaz** [comment]
I have just come across another instance that I think might be related, using the current version of cx_Freeze and python3.10.    I get the following warning:

WARNING: Could not resolve dynamic link to [@rpath/libffi.7.dylib] in file [/Users/xxxxxx/opt/anaconda3/envs/my-rdkit-env/lib/python3.10/site-packages/_cffi_backend.cpython-310-darwin.so], and could not find any likely intended target.

This appears to be fatal for the build process (not surprisingly).

If this is not the right place to raise this, please advise.  Thanks.

**Comment by marcelotduarte** [comment]
@nuffsaz This issue is about anaconda and mingw in windows.

**Comment by nuffsaz** [comment]
Apologies.  Is there a more appropriate place to raise this, or should I start a new thread?

**Comment by marcelotduarte** [comment]
@nuffsaz Please open a new issue preferably with a good report.

**Comment by nuffsaz** [comment]
Will do
