### ISSUE TITLE
cxfreeze compiled executable does not work - Help

### ISSUE THREAD

**Issue by psmux** [marcelotduarte/cx_Freeze#524]
Hello,
I compiled a cxfreeze executable and it does not work on openwrt which has both Python3 and python2 installed.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/encodings/__init__.py", line 31, in <module>
zipimport.ZipImportError: can't decompress data; zlib not available
Aborted
```

Need urgent help,...What may be the root cause of this issue? 

The executable is compiled in Alpine. It works on Alpine

The executable is used inside Openwrt but this is the error shown inside openwrt.

The architecture is armv7

I would appreciate any help.

Thank you.

**Comment by marcelotduarte** [comment]
I think this issue is the same as #513 
See my comments about zlib.
You can use the a cx-freeze version that I posted in Dockerfile to try to resolve yout issue (https://github.com/anthony-tuininga/cx_Freeze/issues/513#issuecomment-536033503).

**Comment by psmux** [comment]
@marcelotduarte Thank you so much! I just uninstalled the existing cx-freeze and instyalled your copy and it just worked out of the Box. Thank you!

**Comment by marcelotduarte** [comment]
Duplicate of #513
