### ISSUE TITLE
ImportError: bad magic number

### ISSUE THREAD

**Issue by fleimgruber** [marcelotduarte/cx_Freeze#525]
Using cx_Freeze from PyPI (6.0) and Python 3.6.8 from a (mini)conda environment, after freezing I get the error

```
ImportError: bad magic number in 'mymodule': b'3\r\r\n'
```

I did some research and it seems that the Python versions are off.
From within the target Python env it gives the expected magic number

```
>>> import importlib.util
>>> importlib.util.MAGIC_NUMBER
b'3\r\r\n'
```

Any ideas on how to debug this further?

**Comment by marcelotduarte** [comment]
Can you send some trackback?

**Comment by fleimgruber** [comment]
Ultimately this was due to the dependency [msl-loadlib](https://github.com/MSLNZ/msl-loadlib) not working correctly - downgraded that and the error went away. Somewhere between 0.4.1 and 0.6.0 presumably their importing logic changed and the application code could not modify the import paths accordingly when frozen. Sorry for the noise.

**Comment by fleimgruber** [comment]
@marcelotduarte this happened again recently, if you would be so kind please see https://github.com/MSLNZ/msl-loadlib/issues/25. Do you see any obvious information for debugging?

**Comment by marcelotduarte** [comment]
As I understand you changed to use py38 and the library server uses py37[1] since v0.60
You should use the same version as the server or freeze your own server.

[1] https://msl-loadlib.readthedocs.io/en/latest/changelog.html#version-0-9-0-2021-05-13

**Comment by fleimgruber** [comment]
@marcelotduarte thanks for your prompt response and analysis. At the bottom it was indeed a similar issue and freezing a fresh server solved it.
