### ISSUE TITLE
App with wxPython doesn't work

### ISSUE THREAD

**Issue by FreeHarry** [marcelotduarte/cx_Freeze#528]
I have some different apps with wxPython. There were no problems with the previous beta version of 6.0. But after I updated to the newest 6.0 version the freezed apps doesn't work anymore. I got the following error ... see the first snapshot.

<img width="304" alt="Screenshot_2019-10-25_12-07-11" src="https://user-images.githubusercontent.com/24735031/67563339-c1908980-f720-11e9-8e89-e88e6ca01394.png">

In the second snapshot you can see the comparison of the lib-folders (6.0beta and latest 6.0). It seems there is a difference of the naming in the dll-files (.pyd) of wxPython. On the newest version the wxPython dll-files include the text `.cp37-win_amd64`. Maybe this breaks the execution of the app.

![Screenshot_2019-10-25_12-08-22](https://user-images.githubusercontent.com/24735031/67563359-cd7c4b80-f720-11e9-807f-3d2208ca4ff6.png)

I work on Windows 10 with Python 3.7.4 and wxPython 4.0.6.

**Comment by FreeHarry** [comment]
I made some tests meanwhile and it seems the problem is not the different naming of the `wx*.pyd` files. The problem is just the missing `wx*.dll` files. If I copy these files from the old 6.0beta lib-folder to the new 6.0 lib-folder, the application works.

**Comment by marcelotduarte** [comment]
#512 was merged and solve this.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
