### ISSUE TITLE
setRelativeReferencePaths() Error when trying to freeze wxPython app

### ISSUE THREAD

**Issue by anuraj-rp** [marcelotduarte/cx_Freeze#529]
Hi,

OS - MacOS Mojave
Python version: 3.7.5

When trying to freeze a wxPython application cx_Freeze fails with following traceback

`
File "../../Python.framework/Versions/3.7/lib/python3.7/site-packages/cx_Freeze/macdist.py", line 180, in setRelativeReferencePaths
if "Mach-O" in p.stdout.readline().decode():
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 281-282: invalid continuation byte
`

Any suggestions on how to proceed?

**Comment by bryantye** [comment]
modify the code at line 180 of "../../Python.framework/Versions/3.7/lib/python3.7/site-packages/cx_Freeze/macdist.py"  to below, it works for me:
`              
               
                p = subprocess.Popen(("file", os.path.join(root, f)), stdout=subprocess.PIPE)
                try:
                    if "Mach-O" in p.stdout.readline().decode():
                        files.append(os.path.join(root, f).replace(self.binDir + "/", ""))
                except:
                    print(p.stdout.readline())
`

**Comment by anuraj-rp** [comment]
Should this issue be classified as a bug? and is a pull-request with bug fix needed? 

Is GitHub the correct medium to discuss issues for cx_Freeze? @anthony-tuininga

**Comment by marcelotduarte** [comment]
Yes, You can send a PR for this bug.
I think that if can remove only the '.decode()' in the code.
Only PY35+ is supported.

**Comment by marcelotduarte** [comment]
@anuraj-rp I have a patch to this issue. Can you test it and report?
use:
pip uninstall cx-freeze
pip install git+https://github.com/marcelotduarte/cx_Freeze.git@macdist

**Comment by marcelotduarte** [comment]
@bryantye Can you test my patch? (See previous comment)

**Comment by marcelotduarte** [comment]
@anuraj-rp @bryantye Can you test my PR?
pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/573/head

**Comment by anthony-tuininga** [comment]
Presuming PR has resolved issue.
