### ISSUE TITLE
[PATCH] fix "replace_paths" in combination with "namespace_packages"

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#53]
Originally reported by: **Gaëtan de Menten (Bitbucket: [gdementen](https://bitbucket.org/gdementen), GitHub: [gdementen](https://github.com/gdementen))**

----------------------------------------

Here is an excerpt of my setup.py which caused an exception (with release 4.3.2 on Windows 7):
```
#!python
{
"replace_paths": [("*", "")],
"namespace_packages": ["mpl_toolkits"],
}
```
Attached is a patch (against release 4.3.2) to fix the problem.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/53

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Thanks. Questions about the fix:

- Is the bug actually that file shouldn't be None for modules in namespace packages? i.e. should this be fixed by setting `mod.file`, instead of ignoring the case where it's None?
- The patch checks `topLevelModule.file` inside a for loop, but there's nothing within that loop that can change it. So if it's None the first time, it will be None on each subsequent iteration, and also when the function recurses in the next code block. So it can be done outside the loop, and just return `co` unmodified if necessary.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Gaëtan de Menten (Bitbucket: [gdementen](https://bitbucket.org/gdementen), GitHub: [gdementen](https://github.com/gdementen))**:

----------------------------------------

* It might be better, I don't know. I can just tell you that my fix results in an (apparent) correct behavior.
* You are right. I tried to produce a minimal fix/patch. But given the large return statement and the fact that it needs to be different on py3, I wouldn't bother checking it before the loop, I would only replace "continue" by "break" in my patch. Just my 2c. Do whatever is best for you.

**Comment by anthony-tuininga** [comment]
*Original comment by* **EricSmith (Bitbucket: [EricSmith](https://bitbucket.org/EricSmith), GitHub: [EricSmith](https://github.com/EricSmith))**:

----------------------------------------

To the first point:

It seems to me that the file attribute being None is reasonably consistent with how namespace packages work. From the [Python Cookbook](http://chimera.labs.oreilly.com/books/1230000000393/ch10.html#_discussion_173):

*...the main way that you can tell if a package is serving as a namespace package is to check its __file__ attribute. If it’s missing altogether, the package is a namespace.*

To the second point:

While there might be marginally more efficient ways to fix the problem, I'd be thrilled just to have a fix, and the provided patch (perhaps with the change from `continue` to `break`) seems like a pretty simple one.

**Comment by marcelotduarte** [comment]
namespace_packages are deprecated and automatic.
