### ISSUE TITLE
"Bad file descriptor" error when freezing with base="Win32GUI"

### ISSUE THREAD

**Issue by MarvBob** [marcelotduarte/cx_Freeze#531]
Windows 10
Python 2.7.17 32bit
cx-Freeze 5.1.1

My software runs smoothly in Python, but when I freeze it with base="Win32GUI" and run it as an executable, most of its functions raise an error "[Errno9] Bad file descriptor". If I'm not mistaken, this is a Windows error saying that I am trying to access to a file already closed or that does not exist anymore. If I freeze my software with base=None I have no problem at all so I suspect the error to come from the fact that there is no console for printing, but I am not sure.
This error seems to be present at least since version 5.0.

**Comment by marcelotduarte** [comment]
I think you are right about the source of the problem ("I suspect the error to come from the fact that there is no console for printing").
Try running the executable from a command prompt to confirm.
Give more details about your program, for example if you use wxPython, or another library that needs Win32GUI ...
NOTE: Please do not open issues to same issue (#530).

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
