### ISSUE TITLE
Installing a Win32Service gives AttributeError: module '__main__' has no attribute 'NAME'

### ISSUE THREAD

**Issue by danielmenzel** [marcelotduarte/cx_Freeze#536]
Hi,
I have built cx_Freeze 6.0 with Python 3.7.5, cx_Logging 2.2, Visual Studio 2019 on Windows 10 and have managed to get a `Win32Service.exe` in the `bases` directory.
I then built the provided sample under `samples/service`, but when I run the created executable with
```cmd
build\exe.win-amd64-3.7\cx_FreezeSampleService.exe --install test
```
I get the error
```
Service not installed. See log file for details.
```
and the following log file:
```
[20580] 2019/12/06 08:09:43.120 starting logging at level ERROR
[20580] 2019/12/06 08:09:43.134 Python exception encountered:
[20580] 2019/12/06 08:09:43.134     Internal Message: cannot locate service name
[20580] 2019/12/06 08:09:43.134     Type => <class 'AttributeError'>
[20580] 2019/12/06 08:09:43.135     Value => module '__main__' has no attribute 'NAME'
[20580] 2019/12/06 08:09:43.142     AttributeError: module '__main__' has no attribute 'NAME'

[20580] 2019/12/06 08:09:43.154 ending logging
```
It seems like the global variables in `Config.py` like `NAME` etc. are somehow not recognized as attributes of the `__main__` module.
I managed to get it working by explicitly adding the variables to the `__main__` module in `Config.py` like this
```python
import sys
sys.modules[__name__].NAME = 'cx_FreezeSampleService%s'
sys.modules[__name__].DISPLAY_NAME = 'cx_Freeze Sample Service - %s'
sys.modules[__name__].MODULE_NAME = 'ServiceHandler'
sys.modules[__name__].CLASS_NAME = 'Handler'
sys.modules[__name__].DESCRIPTION = 'Sample service description'
sys.modules[__name__].AUTO_START = False
sys.modules[__name__].SESSION_CHANGES = False
```
Perhaps there is something that can be changed in `Win32Service.c` instead of this inelegant workaround, but I have not enough knowledge about the Python C API to understand what is going on.

**Comment by anthony-tuininga** [comment]
I don't use Windows much at all in the past few years but if I get a chance, I'll take a look at this. Its possible that some of the recent changes to simplify things have inadvertently broken this!

**Comment by Matthias-Wagner** [comment]
Hi, this probably doesn't only affect Win32Service. I'm a colleague of Daniel, and in the meantime we experienced another problem. In the same environment as above we also had to move a class from a normal executable starting script into a module in order to make it pickle-able (which worked before cx_Freeze and Python Upgrade).

**Comment by danielmenzel** [comment]
A small example illustrating what Matthias was talking about:

```python
import multiprocessing
import multiprocessing.pool


class processPoolApplyFunc:
    def __init__(self, func):
        pass


class ProcessPoolTest(multiprocessing.pool.Pool):
    def apply_async(self, func, args=(), kwds={}, callback=None, error_callback=None):
        return super().apply_async(processPoolApplyFunc(func), args, kwds, callback, error_callback)


if __name__ == "__main__":
    multiprocessing.freeze_support()

    def func():
        pass

    with ProcessPoolTest() as pool:
        pool.apply(func)
```

If I freeze this (cx_Freeze 6.0 and Python 3.7.5 on Windows) and run the resulting executable I get

```
Traceback (most recent call last):
  File "D:\Repos\cx_Freeze-service\env\lib\site-packages\cx_freeze-6.0-py3.7-win-amd64.egg\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "D:\Repos\cx_Freeze-service\env\lib\site-packages\cx_freeze-6.0-py3.7-win-amd64.egg\cx_Freeze\initscripts\Console.py", line 23, in run
    exec(code, {'__name__': '__main__'})
  File "hello.py", line 29, in <module>
    pool.apply(func)
  File "c:\Python37\lib\multiprocessing\pool.py", line 261, in apply
    return self.apply_async(func, args, kwds).get()
  File "c:\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "c:\Python37\lib\multiprocessing\pool.py", line 431, in _handle_tasks
    put(task)
  File "c:\Python37\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "c:\Python37\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class '__main__.processPoolApplyFunc'>: attribute lookup processPoolApplyFunc on __main__ failed
```

This looks similar to the Win32Service problem above because again an attribute of the `__main__` module can not be found.

**Comment by marcelotduarte** [comment]
See PR #622, tested with the sample at https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/service

**Comment by marcelotduarte** [comment]
Can you test the PR? (only if you have a C compiler)

pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/622/head

**Comment by Matthias-Wagner** [comment]
I've tested the PR with our original service config.py and it seems to work fine for our use case. Thank you very much :).

**Comment by 666github666** [comment]
Hi Matthias,

Can you share your  setup for cx_freeze? 
Mainly config.py and ServiceHandler?
I’m struggling with this for few hours now to run windows service with frozen code with multiprocessing (apply_async) without success.
Can’t start child process. 
Thanks in advance.

**Comment by marcelotduarte** [comment]
@666github666 You are using plain cx-freeze 6.1 or using the patched version with my PR?

**Comment by 666github666** [comment]
I’ve build cx_freeze using your code from branch multiprocessing that has this PR. Console version works fine. I’ve been playing with multiprocessing methods like freeze_support(), set_executable() or to get WINSERVICE flag True in spawn.py but that gave me exitcode 2 of pool worker. Without any adjustments I’m getting exitcode 0. Workers are being created and exiting in infinite loop, but child process doesn’t start.

**Comment by marcelotduarte** [comment]
If you are using multiprocessing.Pool that are other PR to resolve this, but has a workaround (issue #353).
I can try with all PR about this (uninstall the previous version first):
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop2`

**Comment by Matthias-Wagner** [comment]
@666github666  Config.py is basically shared above, other service name of course. The handler itself doesn't have anything special. freeze_support() definitely needs to be called on Windows:
```
if __name__ == '__main__':  
    multiprocessing.freeze_support()
```
The code that builds the installer does have a lot of customization, which partially isn't required with newer cx_Freeze and Python versions: Similarly like mentioned in #353 we had to remove a file, in our case **P**rocess.py(c/o) from library.zip. I guess that's obsolete now that process.py is directly in the filesystem instead of library.zip. We also added 'multiprocessing' to build exe options `packages` and `zip_include_packages` (the latter is probably obsolete, again).

**Comment by 666github666** [comment]
Thanks for answers.
I think that what I’m confused about is where to put code with: 

if __name__ == '__main__':  
    multiprocessing.freeze_support()

It is clear for me for console application but I don’t know where to put it for Windows service and how to execute it. Should it be imported in ServiceHandler?

**Comment by Matthias-Wagner** [comment]
Ah that's probably a special case for us: we have another console executable (the actual service) that's run in Handler::Run using subprocess.Popen(), forwarding the stdout/stderr streams to disk and controlling actual service stop by sending a command using stdin in Handler::Stop. That's because we also need our service as separate executable without Windows Service. And it's that separate console executable that's launching multiprocessing subprocesses (and freeze_support). If I had no separate executable, I'd probably try it at the bottom of service_handler.py, yes.

**Comment by 666github666** [comment]
I tried different settings to include multiprocessing pool in windows service app but still getting same result.
In the end, I’ve tested setup as Matthias described and it is working as expected.
Nevertheless it would be nice to have this functionality embedded directly in windows service.
Thanks for your inputs.
