### ISSUE TITLE
Unable to import numpy, DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by wallacez1** [marcelotduarte/cx_Freeze#541]
i builded a tkinter app where i use pandas and the executable runs fine on my computer and in computers with anaconda env but everytime i try to run on computers without python i get the following error.

![image](https://user-images.githubusercontent.com/37086969/71002476-1d8ee300-20be-11ea-98ff-2c0e7e63e6b6.png)

my setup.py

`   from cx_Freeze import setup, Executable
import os.path
import sys
import nltk
import numpy

nltk.download('punkt', download_dir='nltk_packages') 

PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))

os.environ['TCL_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tcl8.6')
os.environ['TK_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tk8.6')

base = None

if sys.platform == 'win32':
base = "Win32GUI"
    
executables = [Executable("main.py", base=base)]

packages = ['sqlalchemy.dialects','sqlalchemy.sql.default_comparator','numpy']
options = {
    'build_exe': {    
        'packages':packages,
        "includes": ["numpy","numpy.core._methods"],
        'include_files':['nltk_packages','stemmedStop.csv','stemmedWhite.csv',os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tk86t.dll'),
           os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tcl86t.dll') ]},
        
     
}

setup(
    name = "Carrefour Nlc",
    options = options,
    version = "0.0.1",
    description = '<any description>',
    executables = executables
)

`
i already tried this solution with no sucess #205 , i appreciate any help.

Enviroment: 
Python: 3.7.5
cx_Freeze:6.0
pandas:0.25.3
numpy: 1.17.4

**Comment by marcelotduarte** [comment]
What solution you tried? You referenced your issue....
With anaconda, some dlls is in diferent path, and are not copied (issue #526)
Can you try with official python, downloading from python.org?

**Comment by wallacez1** [comment]
> What solution you tried? You referenced your issue....
> With anaconda, some dlls is in diferent path, and are not copied (issue #526)
> Can you try with official python, downloading from python.org?


thank you marcelo for your time, already fixed the referenced issue and yes i will try with  oficial python

**Comment by marcelotduarte** [comment]
Please report if you have success.

**Comment by wallacez1** [comment]
> Please report if you have success.

Thank you, the idea of running with official python worked!! but i had to add a new DLL, 'libffi-7.dll' to my setup.py

`from cx_Freeze import setup, Executable
import os.path
import sys
import nltk
nltk.download('punkt', download_dir='nltk_packages') 


PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
print(PYTHON_INSTALL_DIR)
os.environ['TCL_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tcl8.6')
os.environ['TK_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tk8.6')


base = None

 if sys.platform == 'win32':
       base = "Win32GUI"
    
executables = [Executable("main.py", base=base)]


packages = ['sqlalchemy.dialects','sqlalchemy.sql.default_comparator']
options = {
    'build_exe': {    
        'packages':packages,
        'include_files':['nltk_packages','stemmedStop.csv','stemmedWhite.csv',os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tk86t.dll'),
           os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tcl86t.dll'),os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'libffi-7.dll')]},
        
     
}

setup(
    name = "Carrefour Nlc",
    options = options,
    version = "0.0.1",
    description = '<any description>',
    executables = executables
)`

Python: 3.8.0
cx_Freeze: 6.1
numpy:1.17.4
pandas:0.25.3

**Comment by marcelotduarte** [comment]
With python 3.7.5 it will work.
In py38 has an issue #523

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
