### ISSUE TITLE
Feature: zip_include_package_data

### ISSUE THREAD

**Issue by marcelotduarte** [marcelotduarte/cx_Freeze#551]
I think to add a new option to build_exe:

zip_include_package_data
     - packages which should include the data in the zip file; it is expected a mapping (dict) from package name to a list of relative path names that should be copied in the zip file; they may contain glob patterns as well; example:
zip_include_package_data={'mypkg': ['data/*.dat']}

@anthony-tuininga What do you think?

**Comment by marcelotduarte** [comment]
The ideia is based on package_data of distutils.

**Comment by anthony-tuininga** [comment]
The existing infrastructure for hooks should be adequate, I think, but it could be enhanced to include support for glob patterns, if needed.

It might be a good idea to add the ability to add custom hooks without having to modify cx_Freeze source. If we are going to do that I think we shuld change the hook infrastructure to be PEP 8 compliant and then document it. In addition, I think it would be better to have each hook in a separate file in a common directory, with the ability to specify additional directories added. I'll see if I can put something together along those lines.

**Comment by marcelotduarte** [comment]
With the changes you recently made, we can use zip_includes. Even, I think it was missing documenting.

About the changes you want to make, I'll wait, and if there is anything you want me to make to gt it PEP8 compliant.

In that sense, if I convert main.py to use argparse and get PEP8 compliance, do you accept the patch or find it unnecessary to change optparse (deprecated) to argparse?
