### ISSUE TITLE
Missed cxfreeze-postinstall script in source distribution

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#56]
Originally reported by: **Anonymous**

----------------------------------------

Can't create wheel package for cxfreeze from sources.

c:\Python32\Scripts\pip.exe wheel --wheel-dir dist\wheelhouse cx_freeze

error: file '~\build\cx-freeze\cxfreeze-postinstall' does not exist.

Probably need to add this script into file: MANIFEST

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/56

**Comment by anthony-tuininga** [comment]
*Original comment by* **Sam Schauer (Bitbucket: [luminous2269](https://bitbucket.org/luminous2269), GitHub: Unknown)**:

----------------------------------------

cxfreeze-postinstall is missing from the 'Source code only (.tar.gz)' link on the main Sourceforge page [http://prdownloads.sourceforge.net/cx-freeze/cx_Freeze-4.3.2.tar.gz?download] for me as well.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

This is because that script is not needed on Linux and that is where I built the source distribution! I will see if this script is needed and if so, make sure it is included in the next release.

**Comment by anthony-tuininga** [comment]
*Original comment by* **László Nagy (Bitbucket: [nagylzs](https://bitbucket.org/nagylzs), GitHub: [nagylzs](https://github.com/nagylzs))**:

----------------------------------------

All users who have MSVC and want to install cx_Freeze with pip will fail to install it. Can you please fix this? Thanks!

**Comment by anthony-tuininga** [comment]
*Original comment by* **12345 67890 (Bitbucket: [12345_67890](https://bitbucket.org/12345_67890), GitHub: Unknown)**:

----------------------------------------

I don't think one file is too much to ask for windows compatibility.

**Comment by anthony-tuininga** [comment]
*Original comment by* **12345 67890 (Bitbucket: [12345_67890](https://bitbucket.org/12345_67890), GitHub: Unknown)**:

----------------------------------------

Alright folks! In the interest of convenience, I have created the cx_Freeze-win package. It is exactly the same as the cx_Freeze package, except it will install on windows.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

I just checked and when I run python setup.py sdist the file cxfreeze-postinstall is included. So the next release will have this.

**Comment by acaparroso** [comment]
Hello, If you are still having issues like this, for me running the following command worked:

pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master

Hope it works, spent countless hours trying to install it.

**Comment by dougschurman** [comment]
> 
> 
> Hello, If you are still having issues like this, for me running the following command worked:
> 
> pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master
> 
> Hope it works, spent countless hours trying to install it.

Worked for me, successful cx_Freeze-6.0b1 installation. Had problems before with no directory or file of cxfreeze-postinstall.

**Comment by hawkerm** [comment]
Thanks @acaparroso!

Do we know when an official package be released with this fix?  

It seems there are dozens of issues all related to not being able to install on windows due to the cx-freeze-postinstall error.  I was just about to file another one.

**Comment by marcelotduarte** [comment]
#511 was merged and fix this issue

**Comment by hawkerm** [comment]
@marcelotduarte thanks I saw, that's why pulling from master on pip works, but there's not an updated package yet on pypi with it.  So, I was curious when 6.0.1 or 6.1 with this fix will be released.

**Comment by marcelotduarte** [comment]
@hawkerm Since September Anthony plans to release a version ;-)
He should release version 6.1 later this month.

**Comment by hawkerm** [comment]
@marcelotduarte no problem, I know how it is.  Thanks for the info here and on the other issue.

**Comment by anthony-tuininga** [comment]
The intent is to release 6.1 in the next few weeks, as Marcelo mentioned.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
