### ISSUE TITLE
cx_freeze 6.1 fails in cxfreeze command line

### ISSUE THREAD

**Issue by msilano** [marcelotduarte/cx_Freeze#560]
When trying to run cx_freeze 6.1 on Windows 10 against any python file, it fails with the error: 
TypeError: __init__() missing 1 required positional argument: 'constantsModule'.  Stack trace below.

Thanks!

C:\Users\mike\Box\Inbox\boxbot>cxfreeze test.py
Traceback (most recent call last):
  File "c:\users\mike\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\mike\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mike\AppData\Local\Programs\Python\Python38-32\Scripts\cxfreeze.exe\__main__.py", line 7, in <module>
  File "c:\users\mike\appdata\local\programs\python\python38-32\lib\site-packages\cx_Freeze\main.py", line 165, in main
    freezer = cx_Freeze.Freezer(executables,
TypeError: __init__() missing 1 required positional argument: 'constantsModule'

C:\Users\mike\Box\Inbox\boxbot>type test.py
print("Hello")

**Comment by marcelotduarte** [comment]
Thanks for reporting. PR #561 will solve this.
As a workaround, create a minimal setup.py manually or using the command line "cxfreeze-quickstart".

**Comment by msilano** [comment]
Thanks @marcelotduarte.  Really appreciate the help.  
I tried out the change; introduced a slightly different error downstream on a Mac.  Will try on windows VM once it finishes updating itself.......

  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/cxfreeze", line 5, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cx_Freeze/main.py", line 168, in main
    freezer = cx_Freeze.Freezer(executables, constants_module,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 97, in __init__
    self.constantsModules = list(constantsModules)
TypeError: 'ConstantsModule' object is not iterable

**Comment by msilano** [comment]
Thanks for the quick fix.  Really appreciate the help.

**Comment by ghost** [comment]
Hello i've the same issue (v 6.1). Is there a fix ?

**Comment by ShanshanBi** [comment]
> Thanks for reporting. PR #561 will solve this.
> As a workaround, create a minimal setup.py manually or using the command line "cxfreeze-quickstart".

I use quickstart,PermissionError: [Errno 13] Permission denied: . And I checked my folder properties, it can be read, write and modify

**Comment by marizoldi** [comment]
I have the same issue but in MacOS. Using cxfreeze-quickstart fixed it. Shall I open a new issue?

**Comment by marcelotduarte** [comment]
Shall I open a new issue? No.
Patch is available.
https://github.com/anthony-tuininga/cx_Freeze/commit/4a24f1cdefe05c84c215c9f1b3694697e6ccab60

**Comment by jschueller** [comment]
could a new version be published ?

**Comment by Berserker66** [comment]
Apparently this is related:
https://bugreports.qt.io/browse/PYSIDE-1257

**Comment by marcelotduarte** [comment]
@Berserker66 No, this issue is a simple command line cxfreeze that has a error. If you use a setup, you do not need this. If you use python setup.py build, you do not need this.
In your bug report at pyside, I see that you use py38 to build but you reference py36 hardcoded in your setup.

**Comment by Berserker66** [comment]
The "if holoviews" where the python 36 line occurs hasn't been used in ages, you can see that the holoviews variable is turned to off and the code is simply there should it be needed again. Any actually currently used code should not reference python 36

**Comment by marcelotduarte** [comment]
Oh... ;-)
Related to this case appears to be PR #570

**Comment by Berserker66** [comment]
It doesn't look to be (PyQt5 vs PySide2 and not sip related). The issue lies with PySide2 and shiboken,specifically the way that PySide2 loads shiboken with the new version. It is looking for the module as an actual file. I don't think the update is even capable of finding a shiboken that's in a library,zip. It also works fine with earlier versions of PySide2, which use a different method of loading shiboken ( such as import... which the new pyside2 doesn't even try).

As such I did report the issue to Qt, as from the looks of the error and surrounding code, it very much looks like "their fault".

I only posted here because they linked me here and I hope to get the issue rolling along.

Edit: I use cx_freeze with plenty other projects (thank you for an amazing module btw). The only thing that ever breaks is Qt.

**Comment by boralprophecy** [comment]
Still facing this issue. Can a new version be published to pip please.

**Comment by alexdelorenzo** [comment]
Encountering this issue as well on Python 3.8 on both Linux and Windows.

**Comment by codeyourdream** [comment]
Got this issue on Windows with Python 3.8.

**Comment by monkeyman51** [comment]
> @Berserker66 No, this issue is a simple command line cxfreeze that has a error. If you use a setup, you do not need this. If you use python setup.py build, you do not need this.
> In your bug report at pyside, I see that you use py38 to build but you reference py36 hardcoded in your setup.

Used the cxfreeze-quickstart command and created the setup.py successfully.  What steps are needed next in order to launch the executable file on a different system?

**Comment by monkeyman51** [comment]
> Encountering this issue as well on Python 3.8 on both Linux and Windows.

Did you run the cxfreeze-quickstart command?

**Comment by marcelotduarte** [comment]
@monkeyman51 @Berserker66 @codeyourdream @alexdelorenzo
cx_Freeze 6.2 has just been released and merged the solution to this issue.
