### ISSUE TITLE
Demo PyQt5app.py (and setup.py associated with it) not working as expected. 

### ISSUE THREAD

**Issue by Echeban** [marcelotduarte/cx_Freeze#562]
I downloaded the sample code provided here:
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/PyQt5

I run ```(venv375-32) python setup.py bdist_msi``` 
in my development machine, with Windows 10, Python 3.7.5-32 bit, 
and these packages in a venv:  
 cffi            1.13.2 
 cryptography    2.8    
 cx-Freeze       6.0    
 cycler          0.10.0 
 kiwisolver      1.1.0  
 matplotlib      3.1.2  
 numpy           1.17.4 
 pip             19.3.1 
 pycparser       2.19   
 pyparsing       2.4.5  
 PyQt5           5.13.2 
 PyQt5-sip       12.7.0 
 python-dateutil 2.8.1  
 scipy           1.3.3  
 setuptools      41.2.0 
 six             1.13.0 

The build .exe runs well on the dev. machine. 
I copy the .msi to a machine that does not have PyQt5 installed. 

I install the msi, and when I try to run it, I get this error:
```
File PyQt5app.py Line 5 in <module> import error DLL load failed: The specified module could not be found.
```

Line 5 is the app is
```from PyQt5.QtWidgets import QApplication, QWidget```

The app and setup.py are attached to this post just in case.

It seems that the PyQt5 DLL's are not included in the freeze or not installed on the target machine, I don't know what the problem is. What can I do?

[PyQt5app.py.txt](https://github.com/anthony-tuininga/cx_Freeze/files/4023971/PyQt5app.py.txt)
[setup.py.txt](https://github.com/anthony-tuininga/cx_Freeze/files/4023972/setup.py.txt)

Here is the log file from running 
```
python setup.py bdist_msi > PyQt5app_setup_log.txt
```

[PyQt5app_setup_log.txt](https://github.com/anthony-tuininga/cx_Freeze/files/4026149/PyQt5app_setup_log.txt)

**Comment by marcelotduarte** [comment]
For me it's working as expected. I've tested it in December before the version 6.1 and now.
The pyqt dls are included.
I believe what may have happened is that on the target machine there is no vcruntime.
In the documentation is a bit confusing, but see:
https://cx-freeze.readthedocs.io/en/latest/faq.html#microsoft-visual-c-redistributable-package

Ignore the download and use this link:
https://www.microsoft.com/en-US/download/details.aspx?id=48145

**Comment by Echeban** [comment]
Before attempting to force cx-freeze to include the vcruntime I wanted to see if installing VC manually would solve the problem. I now have VC++2015 Redistributable(x86) and (x64) installed on the target machine, which anyway is giving the same error as before. Next, I installed python 3.7.5, created a venv, intalled PyQt5. Now the app works.  Next, I try my app on another clean target machine that has VC++2008/2010/2012 and 2017 (but not 2015) Redistributable(x86) and (x64) on it. It does not have python and PyQt5 installed. Same error! I am using cx-freeze 6.0.  What do you recommend I do?

**Comment by Echeban** [comment]
Installed cx-freeze 6.1. Froze my app with 6.1. Removed all instances of MSVC++ Runtime from target machine. Installed app on target machine. Got a different error: "The code execution cannot proceed because VCRUNTIME140.dll was not found". I downloaded it from MS site, installed it. Problem solved. Thank you! -- PS: how do I modify setup.py to force cx-freeze to add VCRUNTIME140.dll in case the user does not have any VCRUNTIME ?

**Comment by marcelotduarte** [comment]
With cx-freeze 6.0 had a regression and was missing some dlls. In version 6.1 is working fine. Before installing on a new machine, install vcruntime. I updated information in the doc (PR #564), but should come out in the next version. I believe this include_msvcr option is not working. I will test it in the future, but if you want to test and inform me ;-)

**Comment by Echeban** [comment]
ok. thank you.
