### ISSUE TITLE
when using cx_Freeze.Freezer : missing 1 required positional argument: 'constantsModule'

### ISSUE THREAD

**Issue by hackery98** [marcelotduarte/cx_Freeze#563]
https://github.com/anthony-tuininga/cx_Freeze/blob/6c1d6f23f401d40368d4fab5cd710a784b114a12/cx_Freeze/main.py#L165

__init__() missing 1 required positional argument: 'constantsModule'

**Comment by marcelotduarte** [comment]
Duplicate of #560
