### ISSUE TITLE
tkinter path error

### ISSUE THREAD

**Issue by mrichez** [marcelotduarte/cx_Freeze#566]
Hi,
Got a problem with version  mingw-w64-x86_64-python-cx_Freeze-6.0-1
Can't find path to tkinter (error: [Errno 2] No such file or directory: 'C:/msys64/mingw64/tcl/tcl8.6')
I try to add path in setup-freeze.py:
...
include_files = [
    r"C:\msys64\mingw64\bin\tcl86.dll",
    r"C:\msys64\mingw64\bin\tk86.dll",]

os.environ['TCL_LIBRARY'] = r'C:\msys64\mingw64\lib\tcl8.6'
os.environ['TK_LIBRARY'] = r'C:\msys64\mingw64\lib\tk8.6'
....
Got this error: error: [Errno 2] No such file or directory: 'C:/msys64/mingw64/Dlls/tcl86t.dll'
tcl86t.dll doesn't exist, my file is tcl86.dll

Thanks for help!

**Comment by mrichez** [comment]
I try the sample:
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/Tkinter
Got:
...
copying C:/msys64/mingw64/tcl/tcl8.6 -> build/exe.mingw-3.8/tcl
error: [Errno 2] No such file or directory: 'C:/msys64/mingw64/tcl/tcl8.6'

**Comment by mrichez-saluc** [comment]
Can bypass error doing this:

- Create С:\msys64\mingw64\tcl directory and copy into it these directories:
    C:\msys64\mingw64\lib\tcl8.6
    C:\msys64\mingw64\lib\tk8.6
- Create С:\msys64\mingw64\Dlls directory and copy into it these files:
    C:\msys64\mingw64\bin\tcl86.dll
    C:\msys64\mingw64\bin\tk86.dll
- Rename these files in С:\msys64\mingw64\Dlls directory:
    tcl86.dll -> tcl86t.dll
    tk86.dll -> tk86t.dll

**Comment by mrichez** [comment]
Can bypass error doing this:

- Create С:\msys64\mingw64\tcl directory and copy into it these directories:
    C:\msys64\mingw64\lib\tcl8.6
    C:\msys64\mingw64\lib\tk8.6
- Create С:\msys64\mingw64\Dlls directory and copy into it these files:
    C:\msys64\mingw64\bin\tcl86.dll
    C:\msys64\mingw64\bin\tk86.dll
- Rename these files in С:\msys64\mingw64\Dlls directory:
    tcl86.dll -> tcl86t.dll
    tk86.dll -> tk86t.dll

**Comment by totaam** [comment]
Same here, any basic MSYS2 installation triggers this bug.
Edit: I can exclude tcl and tk by spelling them correctly (case sensitive under mingw): [xpra changeset 25138](http://xpra.org/trac/changeset/25138/xpra)

**Comment by marcelotduarte** [comment]
@mrichez @totaam 
Can you test the PR? (only if you have a C compiler)
First, uninstall your current version of cx-freeze (using pacman or pip uninstall)

`pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/642/head`

**Comment by mrichez-saluc** [comment]
@marcelotduarte 
Working with https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/Tkinter
:-)
