### ISSUE TITLE
The MATPLOTLIBDATA environment variable was deprecated

### ISSUE THREAD

**Issue by jpeg13** [marcelotduarte/cx_Freeze#569]
While executing an application built with cx_Freeze and depending on matplotlib 3.1.2, I get the following warning:

`The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.`

See https://github.com/matplotlib/matplotlib/pull/11241

**Comment by marcelotduarte** [comment]
@jpeg13 Can you test the PR?
pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/574/head

**Comment by jpeg13** [comment]
@marcelotduarte Tested with python 3.6.8 and matplotlib 3.1.2 under Windows 10: the warning has disappeared and the executable still works as expected. It also still works with matplotlib 2.2.2. Thank you very much!
