### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by woodpecker02** [marcelotduarte/cx_Freeze#581]
Hello @all,

my PIP - Version List:

> pip freeze
> altgraph==0.17
> bcrypt==3.1.7
> certifi==2019.11.28
> cffi==1.13.2
> chardet==3.0.4
> ciscoconfparse==1.4.11
> colorama==0.4.3
> cryptography==2.8
> cx-Freeze==6.1
> dnspython==1.16.0
> future==0.18.2
> idna==2.8
> Jinja2==2.11.1
> junos-eznc==2.2.1
> lxml==4.5.0
> macholib==1.14
> MarkupSafe==1.1.1
> napalm==2.5.0
> ncclient==0.6.7
> netaddr==0.7.19
> netmiko==2.4.2
> nxapi-plumbing==0.5.2
> paramiko==2.7.1
> passlib==1.7.2
> pefile==2019.4.18
> pycparser==2.19
> pyeapi==0.8.3
> PyInstaller==3.6
> pyIOSXR==0.53
> PyNaCl==1.3.0
> pyparsing==2.4.6
> pyserial==3.4
> pywin32-ctypes==0.2.0
> PyYAML==5.3
> requests==2.22.0
> scp==0.13.2
> six==1.14.0
> textfsm==1.1.0
> transitions==0.7.2
> urllib3==1.25.8
> yamlordereddictloader==0.4.0

> python 3.7

when i create my exe-file with cx_Freeze, i got the following Module error:

> Traceback (most recent call last):
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
>     module.run()
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
>     exec(code, {'__name__': '__main__'})
>   File "change_if_description.py", line 10, in <module>
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\napalm\__init__.py", line 3, in <module>
>     from napalm.base import get_network_driver
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\napalm\base\__init__.py", line 27, in <module>
>     from napalm.base.base import NetworkDriver
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\napalm\base\base.py", line 21, in <module>
>     from netmiko import ConnectHandler, NetMikoTimeoutException
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\__init__.py", line 8, in <module>
>     from netmiko.ssh_dispatcher import ConnectHandler
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\ssh_dispatcher.py", line 4, in <module>
>     from netmiko.a10 import A10SSH
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\a10\__init__.py", line 2, in <module>
>     from netmiko.a10.a10_ssh import A10SSH
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\a10\a10_ssh.py", line 4, in <module>
>     from netmiko.cisco_base_connection import CiscoSSHConnection
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\cisco_base_connection.py", line 3, in <module>
>     from netmiko.base_connection import BaseConnection
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\netmiko\base_connection.py", line 22, in <module>
>     import paramiko
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\__init__.py", line 22, in <module>
>     from paramiko.transport import SecurityOptions, Transport
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\transport.py", line 89, in <module>
>     from paramiko.dsskey import DSSKey
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\dsskey.py", line 37, in <module>
>     from paramiko.pkey import PKey
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\paramiko\pkey.py", line 31, in <module>
>     import bcrypt
>   File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\site-packages\bcrypt\__init__.py", line 25, in <module>
>     from . import _bcrypt
> ModuleNotFoundError: No module named '_cffi_backend'

When i copy the file "_cffi_backend.cp37-win_amd64.pyd"from my python "site-packages" to my new exe/lib-dir everything works fine.

i hope this will help other!

Regards,
Mario

**Comment by marcelotduarte** [comment]
You can add the module '_cffi_backend' to the includes list.


```
from cx_Freeze import setup, Executable

build_options = {"includes": ["_cffi_backend"]}
executables = [Executable("test_crypt.py")]

setup(name='test_crypt',
      version='0.1',
      description='cx_Freeze script to test cryptography',
      executables=executables,
      options={"build_exe": build_options})
```

**Comment by alandmoore** [comment]
Hello, I'm still getting this error after adding `_cffi_backend` to `includes`.  Same happens with the test setup above:

```
Traceback (most recent call last):
  File "/home/alanm/.local/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 113, in run
    module_init.run(name + "__main__")
  File "/home/alanm/.local/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 15, in run
    exec(code, module_main.__dict__)
  File "test_crypt.py", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python3.9/site-packages/paramiko/transport.py", line 89, in <module>
    from paramiko.dsskey import DSSKey
  File "/usr/lib/python3.9/site-packages/paramiko/dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File "/usr/lib/python3.9/site-packages/paramiko/pkey.py", line 31, in <module>
    import bcrypt
  File "/usr/lib/python3.9/site-packages/bcrypt/__init__.py", line 25, in <module>
    from . import _bcrypt  # type: ignore
ModuleNotFoundError: No module named '_cffi_backend'
```

I am using cx-freeze 6.8 from PyPI, Python 3.9 on arch linux 64-bit.  I tried my build on Windows 10 and Ubuntu Linux and it succeeded.

**Comment by marcelotduarte** [comment]
The setup above isn't necessary anymore. See this sample: https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples/bcrypt

**Comment by alandmoore** [comment]
With or without the setup, I get the `ModuleNotFoundError` on arch.

**Comment by marcelotduarte** [comment]
Later I'll try in a docker. What are the versions of the libs used? bcrypt, cffi, etc

**Comment by alandmoore** [comment]
bcrypt == 3.2.0
cffi==1.14.6
paramiko == 2.7.2

I think these are the latest versions, which I have installed system-wide from the arch repos.  I note that if I pip install these I get older versions from PyPI.  Would explain why it works on Ubuntu and Windows, perhaps.
