### ISSUE TITLE
issue with VersionInfo

### ISSUE THREAD

**Issue by AceScottie** [marcelotduarte/cx_Freeze#586]
Using Tendo and the build gets the error: [screenshot](https://prnt.sc/r29pxg)
Using cx_freeeze 6.1.
Issues is with these lines:
```
_v = VersionInfo('tendo').semantic_version()
__version__ = _v.release_string()
version_info = _v.version_tuple()
```
Commenting these lines out seems to fix the issue.

**Comment by marcelotduarte** [comment]
Try to include in your setup.py:
packages = ['packaging', 'tendo']

**Comment by marcelotduarte** [comment]
Can you test the PR? (only if you have a C compiler)

`pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/608/head`
