### ISSUE TITLE
libffi-7.dll not found with msys2/mingw64

### ISSUE THREAD

**Issue by behrisch** [marcelotduarte/cx_Freeze#596]
An error log can be found here: https://ci.appveyor.com/project/behrisch/texttest/builds/31035619/job/pkh1ru8vptyn039k
This is probably a consequence of the fix for #523 in #556. In the light of https://github.com/conan-io/conan/issues/2638 it is not clear to me how a workaround would look like.

**Comment by marcelotduarte** [comment]
If you install cx-freeze 6.0 you get the same error? I think so. 
PR #556 wasn't the issue. The issue is that msys2 is different than python on windows.
A PR #565 should solve this.

**Comment by behrisch** [comment]
The build with 6.0 was fine, see here: https://ci.appveyor.com/project/behrisch/texttest/builds/30073780/job/xhxu9ho4rq990pn6?fullLog=true. But you are right #565 should fix this.

**Comment by behrisch** [comment]
The msys/mingw people now patched their cxFreeze version so it is not that urgent.
