### ISSUE TITLE
Import error while the application is running in another Pc

### ISSUE THREAD

**Issue by helamdaini** [marcelotduarte/cx_Freeze#598]
Hello, 
I created an executable on windows platform by cx_freeze , the exe file run successfully in my pc , it works also in another pc but when i try to  use some features in my application, i find this error in my log file:
<class 'ImportError'> 
 File "C:\Users\xxxx\venv\mpetools\lib\site-packages\pandas\io\pytables.py", line 448, in __init__
this is the bloc of the error in pytables.py:
        try:
            import tables  # noqa
        except ImportError as ex:  # pragma: no cover
            raise ImportError('HDFStore requires PyTables, "{ex}" problem '
                              'importing'.format(ex=str(ex)))

Ps: the pytables.pyc and the folder tables exist in my build folder 
My pc:
os：win10 64bit
python：Python 3.6.8
Miniconda3: 4.7.12
cx_freeze: 6.0

the other pc:
os：win10 64bit
How can i resolve this problemn please?
thank you:

**Comment by marcelotduarte** [comment]
Can you test with cx-freeze 6.1?
Other changes that you can try it to add pytables and dependencies to the packages list of setup.
I think that issue #396 are related.

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
If you had issues please re-open.
