### ISSUE TITLE
Frozen application fails with non-ascii command line on Linux

### ISSUE THREAD

**Issue by tigarmo** [marcelotduarte/cx_Freeze#611]
Hi,

I've tested this with cx_Freeze 6.1 and the current master branch, on Linux CentOS 7, Python 3.6.7. Freezing the `simple` project in the `samples` directory and then calling the generated `hello` executable fails if the command line contains non-ascii characters, when trying to print it. Command:

```
./hello ação
```

Output:

```python
Hello from cx_Freeze
The current date is March 04, 2020 11:30:16

Executable: '/home/osboxes/Work/miniconda/envs/rocky30-py36/lib/python3.6/site-packages/cx_Freeze/samples/simple/build/exe.linux-x86_64-3.6/hello'
Prefix: ''
Default encoding: 'utf-8'
File system encoding: 'utf-8'

ARGUMENTS:
./hello
Traceback (most recent call last):
  File "/home/osboxes/Work/miniconda/envs/rocky30-py36/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
    module.run()
  File "/home/osboxes/Work/miniconda/envs/rocky30-py36/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "hello.py", line 19, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1-4: surrogates not allowed
```

Here's the output of the program when passing only ascii arguments, so you can see the rest of the output in case it's helpful:

```python
Hello from cx_Freeze
The current date is March 04, 2020 11:32:06

Executable: '/home/osboxes/Work/miniconda/envs/rocky30-py36/lib/python3.6/site-packages/cx_Freeze/samples/simple/build/exe.linux-x86_64-3.6/hello'
Prefix: ''
Default encoding: 'utf-8'
File system encoding: 'utf-8'

ARGUMENTS:
./hello
world

PATH:
/home/osboxes/Work/miniconda/envs/rocky30-py36/lib/python3.6/site-packages/cx_Freeze/samples/simple/build/exe.linux-x86_64-3.6
/home/osboxes/Work/miniconda/envs/rocky30-py36/lib/python3.6/site-packages/cx_Freeze/samples/simple/build/exe.linux-x86_64-3.6/lib/library.zip
/home/osboxes/Work/miniconda/envs/rocky30-py36/lib/python3.6/site-packages/cx_Freeze/samples/simple/build/exe.linux-x86_64-3.6/lib
```
```

**Comment by marcelotduarte** [comment]
Oi.
I had already detected some problems and I have a patch practically ready, just a few details.
According to the sys.argv documentation[1] this is normal, but I think we can improve this.

[1] https://docs.python.org/3.8/library/sys.html?highlight=sys%20argv#sys.argv



Note

On Unix, command line arguments are passed by bytes from OS. Python decodes them with filesystem encoding and “surrogateescape” error handler. When you need original bytes, you can get it by [os.fsencode(arg) for arg in sys.argv].

**Comment by tigarmo** [comment]
Thanks for the quick reply,

>  According to the sys.argv documentation[1] this is normal, but I think we can improve this.

I see that the "surrogateescape" error handler is normal as you say, but I can't see how my command line would generate any errors at all because everything is utf-8 here: my shell's locale, `sys.getfilesystemencoding()`, `locale.getlocale()`, etc. So the byte sequence provided by the OS to the program should be decodable from utf-8 without issues.

Unless this is the bug and what you meant about "we can improve this", in which case I look forward to your patch :)

Thanks again.

**Comment by marcelotduarte** [comment]
For example, if you change:
print(sys.argv)
to:
print([os.fsencode(arg) for arg in sys.argv])
it runs ok.
What I'm doing in my patch is something like this ...

**Comment by marcelotduarte** [comment]
Can you test the PR? (only if you have a C compiler)

`pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/645/head`

**Comment by tigarmo** [comment]
Hi @marcelotduarte, thanks for the link. I'll try it out over the weekend

Tiago

**Comment by tigarmo** [comment]
Hi again, sorry for the delay. I tested your PR and can confirm that the command line is coming in the correct as expected. I tested by running the `simple` sample, which echoes the command line.

Thanks!
