### ISSUE TITLE
add_to_path seems to require all_users

### ISSUE THREAD

**Issue by behrisch** [marcelotduarte/cx_Freeze#613]
When building an msi with the new cx_Freeze 6.1, which now has all_users set to False by default, the installation fails with insufficient priviliges to adapt the PATH enironment variable. A better solution would be to add to the users PATH or at least ask for privilege elevation.

**Comment by marcelotduarte** [comment]
What are you saying has to do with this patch?
https://github.com/anthony-tuininga/cx_Freeze/commit/2365c83ee1fe67d47859afe21366ccbdbe9ecb06#diff-c48eeebfff652a09f77102153d9be4c0

**Comment by behrisch** [comment]
Yes, this seems to be the solution. There needs to be a switch using the one or the other way of adding to the PATH depending on whether all_users is set or not. Should I try to prepare a PR? It may be relevant not only for PATH but also for other environment variables.

**Comment by marcelotduarte** [comment]
Feel free to submit a PR! ;-)
