### ISSUE TITLE
Error importing .so file when pyproj is installed

### ISSUE THREAD

**Issue by rmoretto** [marcelotduarte/cx_Freeze#615]
Hello,

I have an application that mainly uses `pyproj` lib.
After running the `python setup.py build_exe` and running the frozen bin I get the following error:

```python
Traceback (most recent call last):
  File "/home/rodrigo/programations/misc/test-cx_freeze/.venv/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
    module.run()
  File "/home/rodrigo/programations/misc/test-cx_freeze/.venv/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "app.py", line 2, in <module>
    import pyproj
  File "/home/rodrigo/programations/misc/test-cx_freeze/.venv/lib/python3.6/site-packages/pyproj/__init__.py", line 51, in <module>
    from pyproj import _datadir
ImportError: libproj-9e402c09.so.15.3.1: cannot open shared object file: No such file or directory
```

One strange thing (that I don't know if is intended or not) is that the `__startup__.py` file being used for initializing the application is in my virtualenv:
 `"[...]/test-cx_freeze/.venv/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py"`

Furthermore, when I ran the `find` command into the build folder, I get the following response:
```bash
find build/ -name "libproj-9e402c09.so.15.3.1"
build/lib/pyproj/libproj-9e402c09.so.15.3.1
```
So it looks like that the `.so` file exists inside the `build/lib/` folder.

I don't know if I'm missing some configuration, or anything else. Any help is greatly appreciated!

#### Using:
* Python 3.6.9
* OS: Ubuntu 18.04.4 LTS
* cx-freeze: 6.1
* pyproj: 2.6.0

##### setup.py
```python
# setup.py
from cx_Freeze import setup, Executable

BUILD_PATH = "build/"

ENTRY_SCRIPT_NAME = "app.py"
TARGET_NAME = "test_freeze"

# Setup base packages
build_exe_options = {
    "packages": [
        "pyproj",
    ],
}

# Defines the executable for the app
EXECUTABLES = [
    Executable(
        ENTRY_SCRIPT_NAME,
        targetName=TARGET_NAME,
    )
]

setup(
    name="TestFreeze",
    version="0.0.1",
    description="Test Freeze",
    options={
        "build": {
            "build_exe": BUILD_PATH,
        },
        "build_exe": build_exe_options
    },
    executables=EXECUTABLES
)

```

##### app.py
```python
# app.py

import pyproj


def main():
    print(pyproj.__version__)


if __name__ == '__main__':
    main()
```
#### Commands used for setting up the project:
```bash
# inside a virtualenv
pip install pyproj cx-freeze
python setup.py build_exe
./build/test_freeze
```

### Edit 1:

So, I was fiddling around with the `pyproj` version and I discovered that downgrading the version to `2.5.0` fixed the problem.

For now this is a solution, but I think that is far from optimal. Is there a way to discover what the differences are between the `2.6.0` and `2.5.0` of the `pyproj` lib for finding a more permanent solution?

**Comment by marcelotduarte** [comment]
For me it runs.
```
(pyproj) marcelo@teste6:~/D/testes/pyproj$ build/test_freeze 
2.6.0
(pyproj) marcelo@teste6:~/D/testes/pyproj$ pip list
Package       Version
------------- -------
cx-Freeze     6.1    
pip           20.0.2 
pkg-resources 0.0.0  
pyproj        2.6.0  
setuptools    46.1.1 
(pyproj) marcelo@teste6:~/D/testes/pyproj$ python -V
Python 3.7.5
(pyproj) marcelo@teste6:~/D/testes/pyproj$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
(pyproj) marcelo@teste6:~/D/testes/pyproj$ find build/ -name "libproj-9e402c09.so.15.3.1"
build/lib/pyproj/libproj-9e402c09.so.15.3.1
build/lib/pyproj/.libs/libproj-9e402c09.so.15.3.1
(pyproj) marcelo@teste6:~/D/testes/pyproj$ find $VIRTUAL_ENV -name "libproj-9e402c09.so.15.3.1"
/home/marcelo/.local/venv/pyproj/lib/python3.7/site-packages/pyproj/.libs/libproj-9e402c09.so.15.3.1
```
The file should be "build/lib/pyproj/.libs/libproj-9e402c09.so.15.3.1"

And for "One strange thing (that I don't know if is intended or not) is that the __startup__.py file being used for initializing the application is in my virtualenv"
Take note that this is only a debug information, the real `__startup__` in on build/lib/library.zip

**Comment by rmoretto** [comment]
Oh, I see. 
Most likely I'm doing something wrong with my build process.

I will verify if the pyproj `.so` file is in the right place via the setup script, and make adjustments from there.

Thank you for the response!
