### ISSUE TITLE
Creating a shortcut does not create a working directory

### ISSUE THREAD

**Issue by mrkaban** [marcelotduarte/cx_Freeze#623]
When creating a shortcut, the working directory is not created, because of this it does not work.

I found on the Internet how to fix the problem, I bring you in the hope that you will fix the problem.

there is a file called "windist.py", in it in the "add_config" section you need to fix it:
`msilib.add_data(self.db, "Shortcut",
                        [("S_APP_%s" % index, executable.shortcutDir,
                                executable.shortcutName, "TARGETDIR",
                                "[TARGETDIR]%s" % baseName, None, None, None,
                                None, None, None, "TARGETDIR")])`

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Can you check if this has been resolved?
Or maybe you can contribute with a fix?

**Comment by mrkaban** [comment]
updated to the latest version and went to look at the windist file, but it still does not contain "TARGETDIR". I had to insert it manually, which is not convenient, otherwise the shortcut does not plow.
![Снимок](https://user-images.githubusercontent.com/14289360/114888093-24a13f00-9e33-11eb-8f3d-6ff8b80d8a4a.png)

**Comment by mrkaban** [comment]
this solves the problem
![Снимок1](https://user-images.githubusercontent.com/14289360/114888238-3da9f000-9e33-11eb-8b44-c217e0f627af.png)

**Comment by marcelotduarte** [comment]
This should be changed definitively or in a condition?

**Comment by mrkaban** [comment]
didn't understand the question, but after every update cx_freeze I have to change this line in this file. This life hack did not come up with himself, he found a solution to the problem on the Internet, it turns out that it is popular.

**Comment by marcelotduarte** [comment]
Now, I see that this issue is a duplicate of #48 

This should be changed definitively or in a condition?
I need to know if this change doesn't break other usages. If we need to make an option to enable it.

**Comment by mrkaban** [comment]
With each new installation of the cx_Freeze library, I go in and make these changes, and after that everything works for me without problems.

**Comment by mrkaban** [comment]
that is, these are the final changes.

**Comment by marcelotduarte** [comment]
PR #1083 
Soon I'll release a version.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
