### ISSUE TITLE
in 32-bit OS does not copy data to the installer

### ISSUE THREAD

**Issue by mrkaban** [marcelotduarte/cx_Freeze#624]
in 32-bit OS does not copy data to the installer, the same script in AMD-64 works without problems.

`# coding: utf-8

from cx_Freeze import setup, Executable
import sys

excludes = ['asyncio', '', 'collections', 'concurrent', 'distutils', 'email', 'PyQt5',
'shiboken2', 'test', 'unittest', 'libcrypto-1_1']

include_files = ['data']

base = None
if sys.platform == "win32":
    base = "Win32GUI"

if 'bdist_msi' in sys.argv:
    sys.argv += ['--initial-target-dir', 'C:\\LicenseCheker']

options = {
    'build_msi': {
        'include_msvcr': True,
        'include_files': include_files,
        "excludes": excludes,
        'initial_target_dir': 'C:\\LicenseCheker',
    }
}

setup(name='LicenseCheker',
      version='0.2',
      description='LicenseCheker',
      options=options,
      executables = [
        Executable(
            script = "main.pyw",
            copyright="mrkaban",
            base=base,
            icon="data/LicenseCheker.ico",
            shortcutName="LicenseCheker",
            shortcutDir="DesktopFolder",
            )
        ]
      )
`

It does not copy "include_files = ['data']", the data folder. I don’t understand what the problem is if the 64-bit OS compiles without problems. Also, on a 64-bit OS, MSI takes up ~ 200 megabytes, and on a 32-bit ~ 14 megabytes.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Can you check if this has been resolved?

**Comment by mrkaban** [comment]
Problem solved! Thank you! And a special thank you for writing!
