### ISSUE TITLE
close program automatic

### ISSUE THREAD

**Issue by Mohammadwh** [marcelotduarte/cx_Freeze#628]
hi 
after build the program by cx_Freeze has been closed
i try to debug by try and except but not have error
and i run manual by cmd and check program but not have error
i use this libraries:
PyQt5
time
telebot
requestium
mechanicalsoup
ast
BeautifulSoup
re
threading
datetime
json
sys
os 
urllib
sqlite3
random
requests
i use windows10 64Xbit python 3.8.2

**Comment by marcelotduarte** [comment]
You can try to use breakpoint() at main script.
Check too if the sample using pyQt5 run for you:
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/PyQt5

**Comment by Mohammadwh** [comment]
all my code is in try and except 
![image](https://user-images.githubusercontent.com/18552903/78468552-4c44ce00-772e-11ea-96a3-52d43ff8ad7c.png)
but not write error.txt

**Comment by marcelotduarte** [comment]
Execute it from console (cmd) to see the output.
If you can, post the setup.py
