### ISSUE TITLE
cx_Freeze imports the wrong zlib for h5py

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#63]
Originally reported by: **Anonymous**

----------------------------------------

I have a lot of programs on my computer that use zlib for compression.  cx_Freeze finds the wrong one when it imports the h5py package:

...
copying c:\Python27\lib\site-packages\h5py\_conv.pyd -> PDSimGUI\h5py._conv.pyd
copying c:\Python27\lib\site-packages\h5py\hdf5dll18.dll -> PDSimGUI\hdf5dll18.dll
copying C:\Ruby200-x64\bin\zlib1.dll -> PDSimGUI\zlib1.dll
copying c:\Python27\lib\site-packages\h5py\szlibdll.dll -> PDSimGUI\szlibdll.dll
copying c:\Python27\lib\site-packages\h5py\_errors.pyd -> PDSimGUI\h5py._errors.pyd
copying c:\Python27\lib\site-packages\h5py\_objects.pyd -> PDSimGUI\h5py._objects.pyd
copying c:\Python27\lib\site-packages\h5py\_proxy.pyd -> PDSimGUI\h5py._proxy.pyd
copying c:\Python27\lib\site-packages\h5py\defs.pyd -> PDSimGUI\h5py.defs.pyd
...

In this case it pulls the ruby zlib, but we want it to use the zlib that comes provided with h5py

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/63

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
