### ISSUE TITLE
No module named 'blinker' when package flask app

### ISSUE THREAD

**Issue by xuqinghan** [marcelotduarte/cx_Freeze#630]
setup.py:

```
import sys
from cx_Freeze import setup, Executable
import os
import shutil

options = {'includes': ['sqlalchemy.sql.default_comparator', 
                        'sqlalchemy.ext.baked',
                        ],
            'include_files': [
                            './WHOOSH_BASE_INDEX',
                            './db_mobile',
                            'mock.xlsx',
                            'Manual.md',
                            './static',
                            './templates',
                            './config.yml'
                            ],
            "packages": ["os",'numpy', 'pandas', 'jinja2', 'jieba'],
            "excludes": ["tkinter"],
            "build_exe": 'D:/dev/ne/seim-frontend-mobile/client/backend',
            }


base = None

setup(  name = "seim",
        version = "0.1",
        description = "My GUI application!",
        options = {"build_exe": options},
        executables = [Executable("app.py", base=base)])
```

run app.exe OK with python3.7 + cx_freeze 6.0 but error python3.8 + cx_freeze 6.1:

> Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "app.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "D:\dev\ne\seim-backend\extensions.py", line 4, in <module>
    import flask_whooshalchemyplus
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Program Files\Python38\lib\site-packages\flask_whooshalchemyplus-0.7.6-py3.8.egg\flask_whooshalchemyplus.py", line 300, in <module>
    def _after_flush(app, changes):
  File "C:\Program Files\Python38\lib\site-packages\flask\signals.py", line 38, in _fail
    raise RuntimeError(
RuntimeError: Signalling support is unavailable because the blinker library is not installed.
PS D:\dev\ne\seim-frontend-mobile\client\backend> ./app.exe
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "app.py", line 6, in <module>
ModuleNotFoundError: No module named 'blinker'

blinker is imported by flask,  I tried to add 'blinker' to options "packages", but cant build:

> running build
> running build_exe
> C:\Program Files\Python38\lib\site-packages\win32com\client\makepy.py:369: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   if path is not '' and not os.path.exists(path):
> C:\Program Files\Python38\lib\site-packages\flask_whooshalchemyplus-0.7.6-py3.8.egg\flask_whooshalchemyplus.py:132: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   if like and like_limit is not 0:
> C:\Program Files\Python38\lib\site-packages\whoosh\codec\whoosh3.py:1116: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   elif fixedsize is 0:
> C:\Program Files\Python38\lib\site-packages\pandas\tests\frame\test_alter_axes.py:241: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   False if (keys[0] is "A" and keys[1] is "A") else drop  # noqa: F632
> C:\Program Files\Python38\lib\site-packages\pandas\tests\frame\test_alter_axes.py:241: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   False if (keys[0] is "A" and keys[1] is "A") else drop  # noqa: F632
> Traceback (most recent call last):
>   File "setup_mobile.py", line 41, in <module>
>     setup(  name = "seim",
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\dist.py", line 340, in setup
>     distutils.core.setup(**attrs)
>   File "C:\Program Files\Python38\lib\distutils\core.py", line 148, in setup
>     dist.run_commands()
>   File "C:\Program Files\Python38\lib\distutils\dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "C:\Program Files\Python38\lib\distutils\dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "C:\Program Files\Python38\lib\distutils\command\build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "C:\Program Files\Python38\lib\distutils\cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "C:\Program Files\Python38\lib\distutils\dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\dist.py", line 211, in run
>     freezer.Freeze()
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\freezer.py", line 610, in Freeze
>     self.finder = self._GetModuleFinder()
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\freezer.py", line 356, in _GetModuleFinder
>     finder.IncludePackage(name)
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 640, in IncludePackage
>     module = self._ImportModule(name, deferredImports)
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 348, in _ImportModule
>     raise ImportError("No module named %r" % name)
> ImportError: No module named 'blinker'

**Comment by marcelotduarte** [comment]
pip install blinker
python setup.py build

**Comment by xuqinghan** [comment]
> pip install blinker
> python setup.py build

not work.  It seems problem only for python 3.8,  python3.7 + cx_freeze 6.1 works well.

> PS D:\dev\ne\seim-backend> pip install blinker
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> Requirement already satisfied: blinker in c:\program files\python38\lib\site-packages\blinker-1.4-py3.8.egg (1.4)
> PS D:\dev\ne\seim-backend> python setup_mobile.py build
> running build
> running build_exe
> C:\Program Files\Python38\lib\site-packages\win32com\client\makepy.py:369: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   if path is not '' and not os.path.exists(path):
> C:\Program Files\Python38\lib\site-packages\flask_whooshalchemyplus-0.7.6-py3.8.egg\flask_whooshalchemyplus.py:132: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   if like and like_limit is not 0:
> C:\Program Files\Python38\lib\site-packages\whoosh\codec\whoosh3.py:1116: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   elif fixedsize is 0:
> C:\Program Files\Python38\lib\site-packages\pandas\tests\frame\test_alter_axes.py:241: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   False if (keys[0] is "A" and keys[1] is "A") else drop  # noqa: F632
> C:\Program Files\Python38\lib\site-packages\pandas\tests\frame\test_alter_axes.py:241: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   False if (keys[0] is "A" and keys[1] is "A") else drop  # noqa: F632
> Traceback (most recent call last):
>   File "setup_mobile.py", line 41, in <module>
>     setup(  name = "seim",
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\dist.py", line 340, in setup
>     distutils.core.setup(**attrs)
>   File "C:\Program Files\Python38\lib\distutils\core.py", line 148, in setup
>     dist.run_commands()
>   File "C:\Program Files\Python38\lib\distutils\dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "C:\Program Files\Python38\lib\distutils\dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "C:\Program Files\Python38\lib\distutils\command\build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "C:\Program Files\Python38\lib\distutils\cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "C:\Program Files\Python38\lib\distutils\dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\dist.py", line 211, in run
>     freezer.Freeze()
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\freezer.py", line 610, in Freeze
>     self.finder = self._GetModuleFinder()
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\freezer.py", line 356, in _GetModuleFinder
>     finder.IncludePackage(name)
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 640, in IncludePackage
>     module = self._ImportModule(name, deferredImports)
>   File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 348, in _ImportModule
>     raise ImportError("No module named %r" % name)
> ImportError: No module named 'blinker'
> PS D:\dev\ne\seim-backend>

**Comment by marcelotduarte** [comment]
I do a test in Linux, py3.7.5 64bit, and Windows py 3.8 64bit, in a virtualenv:
pip install flask blinker cx-freeze
The sample to to test:
```
#test.py
from flask import Flask, escape, request, request_started

app = Flask(__name__)

@app.route('/')
def hello():
    name = request.args.get("name", "World")
    return f'Hello, {escape(name)}!'

def log_request(sender, **extra):
    sender.logger.debug('Request context is set up')
    print('Request context is set up')

request_started.connect(log_request, app)

if __name__ == '__main__':
    app.run()


#setup.py
from cx_Freeze import setup, Executable

build_options = {'packages': [], 'excludes': [],}

executables = [
    Executable('test.py')
]

setup(name='Flask Test',
      version = '0.1',
      description = '',
      options = {'build_exe': build_options},
      executables = executables)
```

**Comment by marcelotduarte** [comment]
> PS D:\dev\ne\seim-backend> pip install blinker
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> Requirement already satisfied: blinker in c:\program files\python38\lib\site-packages\blinker-1.4-py3.8.egg (1.4)

Maybe your issue is the egg
You can try:
pip uninstall blinker
pip install --use-pep517 blinker

**Comment by xuqinghan** [comment]
> > PS D:\dev\ne\seim-backend> pip install blinker
> > Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> > Requirement already satisfied: blinker in c:\program files\python38\lib\site-packages\blinker-1.4-py3.8.egg (1.4)
> 
> Maybe your issue is the egg
> You can try:
> pip uninstall blinker
> pip install --use-pep517 blinker

It works, thanks!
