### ISSUE TITLE
Platform plugins not included into package [Anaconda]

### ISSUE THREAD

**Issue by Winand** [marcelotduarte/cx_Freeze#631]
Related to #339. cx_Freeze cannot find Anaconda's platforms folder.

- Windows 7 x64
- Anaconda
- cx_Freeze 6.1
- Python 3.7.6
- PyQt 5.9.2

After some investigation I've found out that I have to initialize `QCoreApplication` manually during the building process so `cx_freeze.hooks.copy_qt_plugins` can find plugins directory within `QCoreApplication.libraryPaths`, which is empty otherwise.

```
from qtpy import QtCore
# otherwise `cx_freeze.hooks.copy_qt_plugins` will not find plugins folder
_ = QtCore.QCoreApplication([])
print("Qt library paths:", _.libraryPaths())
```
P. S. But the created package is bloated with duplicate files, e.g. icudt58.dll (25MB) is copied not only into `lib`, but also `imageformats` and `platforms` directories.
upd: i see, it's issue 366

**Comment by thierryBottaro** [comment]
I have the same problem... but your solution did not solve my problem.
I added 
```
# otherwise `cx_freeze.hooks.copy_qt_plugins` will not find plugins folder
_ = QtCore.QCoreApplication([])
print("Qt library paths:", _.libraryPaths())
```
I still get : "This application failed to start because it could not find or load the Qt platform plugin "windows"
in ""."

**Comment by Winand** [comment]
You've added these lines into a building script or your program? I call these lines during the building process.

**Comment by thierryBottaro** [comment]
You are right ! https://github.com/Odoth/pyqt5-template works now with your trick added in the building script (build.py)
Thanks a lot !

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.

**Comment by marcelotduarte** [comment]
I confirmed this issue. I'll work on a solution.
@Winand Your comments in #718 and here helped to see the problem. Do you have the same version of pyqt?
I tested with the current of conda-forge pyqt 5.12.3
CC @thierryBottaro

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8b1 has just been released with fixes for pyqt5. Please, try it out and report.
pip install cx-Freeze==6.8b1

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.8b2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8b2) has just been released.
Please, try it out and report.
pip install cx-Freeze==6.8b2

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
