### ISSUE TITLE
how i can use all base in settup?

### ISSUE THREAD

**Issue by Mohammadwh** [marcelotduarte/cx_Freeze#632]
hello i need to run my program in cmd and gui how i can do this by cx_Freeze?

**Comment by marcelotduarte** [comment]
In windows you can specify the base. You can see at samples, for example in:
https://github.com/anthony-tuininga/cx_Freeze/blob/master/cx_Freeze/samples/PyQt5/setup.py

**Comment by marcelotduarte** [comment]
The complete documentation:
https://cx-freeze.readthedocs.io/en/latest/index.html
