### ISSUE TITLE
Code signing and numpy on macos

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [marcelotduarte/cx_Freeze#634]
When using the code signing option to create a .app on macos certain packages will fail. Notably numpy and scipy. This is because they contain a hidden folder `.dylibs` which contains some of the libraries used by numpy and scipy, and hidden folder are not allowed inside .apps.

Following error occurs during code signing:

```
build/MyApp-1.0.0.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: build/MyApp-1.0.0.app/Contents/MacOS/lib/numpy/.dylibs
```

To resolve this would require finding and moving the hidden files (those starting with a `.`) and also adjusting the associated library references.

In the case of numpy these library references are `@loader_path` which usually are skipped. So perhaps should address that too.

Example of skipped `@loader_path`:

```
skip unknown file b'@loader_path/libgcc_s.1.dylib'
skip unknown file b'@loader_path/../.dylibs/libgfortran.3.dylib
```

**Comment by marcelotduarte** [comment]
The referenced PR was merged. I can close this issue?

**Comment by QuantumEntangledAndy** [comment]
The issue is not directly related to that PR and is not resolved by it.

It's a bit more complex. Folders that start with a dot are forbidden when code signing. Some packages like numpy contain such folders.

To resolve there would have to be a means to rename the folders and update the reference in the library files.

**Comment by marcelotduarte** [comment]
As I don't develop for mac, I may not have understood the problems. But, the PR #590 by @cainesi resolves this issue?
Can you test it?
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/590/head`

**Comment by cainesi** [comment]
The PR might help. But I think you’d also need to mark the packages to be included in the zip file (that way all the binary dependencies would be dumped into one directory and you would not need to worry about the original package structure with the hidden folder). 

As a fringe benefit, your bundled app may get a lot smaller.

**Comment by QuantumEntangledAndy** [comment]
My MacBook is currently in the repair shop but I'll test when it comes back.

I'm not familiar with the option to include packages in the zip. But the docs suggest it's a simple as adding the `zip_include_packages` option. If that's the one you mean I will try it when my Mac is back.

**Comment by cainesi** [comment]
Yes, that’s the option I had in mind. 

Best,
Ian

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
