### ISSUE TITLE
ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' 

### ISSUE THREAD

**Issue by gudong321** [marcelotduarte/cx_Freeze#646]
- Windows 10
- cx-Freeze 6.1
- Tensorflow 1.15.0

> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\flask\app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\flask\_compat.py", line 39, in reraise
>     raise value
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\flask\app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "CorrosionAI.py", line 15, in train
>   File "C:\Users\Administrator\Desktop\my_space\CorrosionAI\func.py", line 443, in check_and_train
>     import tensorflow as tf
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
>     from tensorflow_core import *
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
> ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' (unknown location)

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released with namespace detection. Please, try it.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
