### ISSUE TITLE
Add hook for QtSql

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#65]
Originally reported by: **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**

----------------------------------------

QtSql uses a set of plugins called 'sqldrivers'. See [this SO question](http://stackoverflow.com/questions/21791868/cx-freeze-qodbc-driver-not-loaded). These appear to be pretty small (10s of KB), so it's easiest just to copy whatever's there.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/65

**Comment by anthony-tuininga** [comment]
*Original comment by* **Arve Knudsen (Bitbucket: [arve.knudsen](https://bitbucket.org/arve.knudsen), GitHub: Unknown)**:

----------------------------------------

I just ran into this issue myself, I'd appreciate if it were handled automatically.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
