### ISSUE TITLE
Encodings Module Is Not Found

### ISSUE THREAD

**Issue by pcbt** [marcelotduarte/cx_Freeze#652]
Hi, 

When I pack my obfuscated python program with cx_freeze I got the following error:

```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001718 (most recent call first):
```

I am using ```cx_freeze 6.2``` with ```Python 3.6.10 :: Anaconda, Inc.```

Then I tried with ```cx_freeze 6.2``` and ```Python 3.7.7``` then got the following error:

```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000050d8 (most recent call first):
```
This was not happening until I added pythonnet(clr) package to program. Here is my setup.py:
```
import sys
from cx_Freeze import setup, Executable

base = None
# Normally packages are found automatically but since we obfuscate the code cx_freeze can not find them automatically
build_exe_options = {"packages": ["flask", "server", "connexion", "jinja2.ext", "google/protobuf", "zmq", "clr"]}

setup(
    name="Demo App",
    version="0.0.1",
    description="Prelim App Rest Server",
    options={"build_exe": build_exe_options},
    executables=[Executable("dist/dist/app.py", base=base, targetName="app.exe")],
)
```

I searched a litte bit about issue and It should be fixed in the latest cx_freeze version, that is why I am opening a new issue.

**Comment by marcelotduarte** [comment]
Windows or Linux?
Package "google/protobuf" probably should be "google.protobuf"
Can you try with official cx-freeze 6.1?

**Comment by pcbt** [comment]
Sorry I forgot to mention OS. I am on Windows 10 Version 1909 (OS Build 18363.657). "google/protobuf" is working nicely, problem started when I started to use pythonnet(clr) package.
I tried version 6.1 (installed via pip) but got the same result:

```
(rest) C:\development\git-clones\rest-server>build\exe.win-amd64-3.7\app.exe
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002108 (most recent call first):

(rest) C:\development\git-clones\rest-server>pip show cx_freeze
Name: cx-Freeze
Version: 6.1
Summary: create standalone executables from Python scripts
Home-page: https://anthony-tuininga.github.io/cx_Freeze
Author: None
Author-email: None
License: Python Software Foundation License
Location: c:\devtools\conda3-4.7.12\envs\rest\lib\site-packages
Requires:
Required-by:

(rest) C:\development\git-clones\rest-server>python -V
Python 3.7.7

```

I also tried with ```python 3.6``` but did not help.

**Comment by marcelotduarte** [comment]
Verify if in the build directory has python37.dll and if has python3.dll
You can try a PR that resolves issues with python3.dll
`pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/640/head`

**Comment by pcbt** [comment]
Before trying PR 640 I got only python37.dll, now I got both python37.dll and python3.dll in the build folder but problem is not solved.

![2020-05-12 11_29_06-StrokesPlus](https://user-images.githubusercontent.com/8384926/81661072-43899b00-9444-11ea-89c4-0b22c2a66e50.png)

**Comment by marcelotduarte** [comment]
I will suggest you install the official python. I've seen some errors similar to this in anaconda for Linux and it was solved using the official ubuntu python. In the case of windows, download python from python.org

**Comment by pcbt** [comment]
Hi, I used official python and problem solved thanks for help.

**Comment by fabiencastan** [comment]
Same problem on centos 7 with cx_freeze-6.2 and python-3.6 (installed using yum package rh-python36).
```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
```
Any idea?

**Comment by fabiencastan** [comment]
I have the problem only with cx_freeze-6.2.
The same thing works fine with 6.1 and 6.0.

**Comment by marcelotduarte** [comment]
@fabiencastan 
cx_Freeze 6.3 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
