### ISSUE TITLE
ImportError: DLL load failed while importing QtCore: Can not find specific program. 

### ISSUE THREAD

**Issue by TigerVersusT** [marcelotduarte/cx_Freeze#655]
Hi, I used  cx_Freeze to package my program, after everying is done, I run the execuateable and received this:

C:\Users\Administrator\source\repos\meshroom\build\exe.win-amd64-3.8>Meshroom.exe
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "meshroom/ui/__main__.py", line 10, in <module>
  File "C:\Users\Administrator\source\repos\meshroom\meshroom\ui\app.py", line 5, in <module>

    __from PySide2.QtCore import Qt, QUrl, Slot, QJsonValue, Property, Signal, qInstallMessageHandler, QtMsgType, QSettings   ImportError: DLL load failed while importing QtCore: Can not find specific program。__

**Comment by TigerVersusT** [comment]
And my enviroment is:
os: windows 10
PySide2==5.1.1
cx_Freeze==6.1

**Comment by marcelotduarte** [comment]
Please, look at issues #638 and #593 to see if they are related and have information that will help you.
If possible, also build a sample test, perhaps a modified version of:
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/PyQt5

**Comment by TigerVersusT** [comment]
Thanks for your reply! I have read the related issues，I met the same problem as issue #638, after changing PySide2 5.14.2 to version 5.14.1 I received the current problem. For issue  #593 I think it's not related because my path is all ASCII characters:  C:\Users\Administrator\source\repos\meshroom\build\exe.win-amd64-3.8>. And I'll give you a sample as soon as possible.

**Comment by TigerVersusT** [comment]
That's all my probem, so I closed this issue.
