### ISSUE TITLE
cx_freeze wont copy Pillow.libs folder

### ISSUE THREAD

**Issue by YaPeL** [marcelotduarte/cx_Freeze#657]
Hi, I'm using ubuntu 20.04, and Pillow 7.1.1, build seems fine (I'm building from a venv), but when I execute my program, it appears it cannot find some libs needed for Pillow (libjpeg-ba7bf5af.so.9.4.0) if I go to the libs folder on my venv and manually copy the folder Pillow.libs to the libs folder in the build, it starts to work correctly, I'm not sure if this is a bug, or if there is a workaround for this that I'm missing? 

thanks.

**Comment by jgirardet** [comment]
same thing : 
python 3.7
ubuntu 19.10
cxfreeze 6.1
PIL 7.1.2

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released.
I see an issue with pillow 7.x, and I'm investigating.
For now, it has a workaround.
pip install "pillow<7"

**Comment by marcelotduarte** [comment]
@YaPeL @jgirardet 
With a series of patches, mainly #964, #965, #966, #967, #968, packages distributed as manylinux wheels, like Pillow and NumPy, which use extension modules, can locate its external shared libraries. With the help of patchelf, we automatically modify the appropriate RPATH entries such that these libraries will be picked up at runtime.
Tested with Pillow 6.2.x, 7.2.x and 8.1.2 and numpy 1.18.2, 1.19.x and 1.20.x
Please note that patchelf and the C compiler must be installed. 
To install patchelf in debian/ubuntu:
`sudo apt install patchelf`
Now you can test the development version:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main`

If your project builds successfully, please notify me.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
