### ISSUE TITLE
clr module fails when initializing 

### ISSUE THREAD

**Issue by pcbt** [marcelotduarte/cx_Freeze#658]
Pythonnet (clr) module initialization fails. I tried with two different python versions. Here is the example code:

```
import platform

import clr

if __name__ == "__main__":
    print(platform.system())
    print(platform.machine())

```
When I try to build without importing clr it builds succesfully and I get "Windows" ,"AMD64" output when i run the exe. Here is the error when I want to import clr module:

```
C:\development\git-clones\rest-server>build\exe.win-amd64-3.7\test.exe

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Python.Runtime.Runtime.InitializePlatformData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.InitExt()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at clrModule.PyInit_clr()

C:\development\git-clones\rest-server>python -V
Python 3.7.7

C:\development\git-clones\rest-server>pip show cx_freeze
Name: cx-Freeze
Version: 6.2
Summary: create standalone executables from Python scripts
Home-page: https://anthony-tuininga.github.io/cx_Freeze
Author: None
Author-email: None
License: Python Software Foundation License
Location: c:\devtools\python-3.7.7\lib\site-packages
Requires:
Required-by:
```
Python is standart python dowloaded form python.org and cx_freeze is installed via pip. Looks like clr can not found the platform module:

[Issue #1145 in pythonnet repo](https://github.com/pythonnet/pythonnet/issues/1145)

Here is the result I got on Python 3.6:

```
C:\development\git-clones\rest-server>build\exe.win-amd64-3.6\test.exe
Traceback (most recent call last):
  File "C:\devtools\python-3.6.8\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\devtools\python-3.6.8\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "cx_test.py", line 3, in <module>
    import clr
SystemError: initialization of clr did not return an extension module

C:\development\git-clones\rest-server>python -V
Python 3.6.8

C:\development\git-clones\rest-server>pip show cx_freeze
Name: cx-Freeze
Version: 6.1
Summary: create standalone executables from Python scripts
Home-page: https://anthony-tuininga.github.io/cx_Freeze
Author: None
Author-email: None
License: Python Software Foundation License
Location: c:\devtools\python-3.6.8\lib\site-packages
Requires:
Required-by:
```

**Comment by marcelotduarte** [comment]
This issue is a continuation of #652?
Do you use https://github.com/anthony-tuininga/cx_Freeze/issues/652#issuecomment-627007260 to solve your issue? If no, list the build folder for me.

**Comment by pcbt** [comment]
Yes this issue is continuation of #652 . Sorry, maybe I should continue on that issue but I opened a new one because this is completely related to pythonnet package I guess.

I used ``` pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git@refs/pull/640/head ```
but did not help. Here is my build folder:

![2020-05-22 00_07_20-StrokesPlus](https://user-images.githubusercontent.com/8384926/82606779-50368d80-9bc0-11ea-91a3-6b6b03ef303c.png)

**Comment by marcelotduarte** [comment]
For me its works with python 3.7.7, cx-freeze 6.1
See:
![remmina_teste5_teste5 local_2020524-63424,737645](https://user-images.githubusercontent.com/12752334/82747532-2e7c0880-9d70-11ea-9a6c-71c973365bb7.png)

**Comment by marcelotduarte** [comment]
And outside of cmd:
![remmina_teste5_teste5 local_2020524-63956,736372](https://user-images.githubusercontent.com/12752334/82747551-6e42f000-9d70-11ea-8e72-d5258c9def52.png)

**Comment by marcelotduarte** [comment]
Can you close the issue if it's resolved.

**Comment by pcbt** [comment]
I tried on different W10 pc and importing clr module worked with simple code:
```
import platform

import clr

if __name__ == "__main__":
    print(platform.system())
    print(platform.machine())
```
Somehow I am getting the same error with my original code which is more complicated than the code above, two dll reference and bunch of method invokes. I am having no error with pyarmor pack (which uses pyinstaller).

Issue is not resolved but I have no time in these days to find the problem. Thanks for your help so far.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released. Try it, if you have time.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
