### ISSUE TITLE
freezer._GetDependentFiles may be change `X_OK` to `R_OK` will be better

### ISSUE THREAD

**Issue by medns** [marcelotduarte/cx_Freeze#659]
freezer.[_GetDependentFiles](https://github.com/anthony-tuininga/cx_Freeze/blob/c25fedd9c26a58139ac158259d35fc3d964fc509/cx_Freeze/freezer.py#L280)  May be change `X_OK` to `R_OK` will be better because a lot of dynamic library(*.so) no execute permission.

``` python
 if not os.access(path, os.X_OK):
```

change to:

``` python
 if not os.access(path, os.R_OK):
```

**Comment by marcelotduarte** [comment]
Can you send a PR? Do you have a use case?

**Comment by marcelotduarte** [comment]
Do you have a sample or use case?

**Comment by marcelotduarte** [comment]
@medns Do you have a sample or use case?
