### ISSUE TITLE
dbm module in python3 is still using CAN NOT be excluded

### ISSUE THREAD

**Issue by medns** [marcelotduarte/cx_Freeze#660]
modules `dbm`, `dbm.ndbm`, `dbm.dumb`, `dbm.gnu` in python3.8 not been removed or renamed, so it CAN __NOT__ be excluded

https://github.com/anthony-tuininga/cx_Freeze/blob/64e3c6583bc9b7b528458e89abdcba64dc7e55d9/cx_Freeze/hooks.py#L29

**Comment by marcelotduarte** [comment]
Based on py27 doc it was removed, but based on py3, dbm fallback to new dbm.dumb, lol.
But, excluding the module dbm doesn't exclude the modules dbm.ndbm, dbm.gnu nor dbm.dumb.
I'll revert this.

**Comment by medns** [comment]
> Based on py27 doc it was removed, but based on py3, dbm fallback to new dbm.dumb, lol.
> But, excluding the module dbm doesn't exclude the modules dbm.ndbm, dbm.gnu nor dbm.dumb.
> I'll revert this.

i use `dbm.ndbm` finder will be looking for parentModule `dbm` cause this problem
https://github.com/anthony-tuininga/cx_Freeze/blob/64e3c6583bc9b7b528458e89abdcba64dc7e55d9/cx_Freeze/finder.py#L373
