### ISSUE TITLE
Please release a new version to PyPI

### ISSUE THREAD

**Issue by sekrause** [marcelotduarte/cx_Freeze#666]
The latest version on PyPI (6.1) doesn't really work because of issue #560 which was fixed by @anthony-tuininga in commit 4a24f1cdefe05c84c215c9f1b3694697e6ccab60 just 2 days after the release. But a fixed version was never uploaded to PyPI, so the latest "stable" official release has been broken for half a year now.

It would be nice if there were timely updates on PyPI once a critical bug has been found so that we're not always forced to use a locally built version from GitHub.

**Comment by Metadorius** [comment]
Agreed. Just tried to use cx_freeze and encountered this bug.

**Comment by marcelotduarte** [comment]
@sekrause @Metadorius 
Hi, I'm a new maintainer of cx-freeze.
New versions will be released in a shorter time and bugfix versions will be published as soon as we have a patch.
cx_Freeze 6.2 has just been released.

**Comment by sekrause** [comment]
I think pull request #608 is important enough to warrant another release since more and more libraries use importlib_metadata which doesn't work without this patch.

**Comment by marcelotduarte** [comment]
@sekrause version 6.2 includes this PR.

**Comment by sekrause** [comment]
Hmm, then it's a different issue that got fixed. I have an application that works with the Git master, but not 6.2. Need to figure out what it is...

**Comment by marcelotduarte** [comment]
@sekrause cx_Freeze 6.3 has just been released.
