### ISSUE TITLE
[Bug] unable to create exe with ssl (python internal module)

### ISSUE THREAD

**Issue by DEEP7696** [marcelotduarte/cx_Freeze#674]
cxfreeze 6.1
Copyright (c) 2007-2020 Anthony Tuininga. All rights reserved.
Copyright (c) 2001-2006 Computronix Corporation. All rights reserved.
Version of Python: 3.7
Platform: Windows 7,10

example code:
import ssl

getting error:
![WhatsApp Image 2020-06-15 at 11 01 20 AM](https://user-images.githubusercontent.com/26339251/84621263-c3010300-aef7-11ea-9187-8a84424a4ab8.jpeg)

**Comment by marcelotduarte** [comment]
Hey, you aren't using cx-freeze! Try it!

**Comment by DEEP7696** [comment]
how could u say that. I have provided details about version.

**Comment by marcelotduarte** [comment]
In your image: you are using pyinstaller
