### ISSUE TITLE
Why does cx_freeze for Python 3 packs a project into 8000+ files whereas cx_freeze for Python 2 packed the same project in 25 files?

### ISSUE THREAD

**Issue by josephernest** [marcelotduarte/cx_Freeze#675]
First of all congrats for this great library!

Let's say `numpy_example.py` is:

    import numpy as np
    a = np.array([1, 2, 3])
    print(a)

* With Python 2.7.9, generating an executable from this with cxFreeze 4.3.3, with:

        "C:\python27\python.exe" "C:\python27\Scripts\cxfreeze" numpy_example.py 
           --target-dir=.\cxfreeze_x64_py2 --base-name=Win32GUI 
           --target-name=test.exe --exclude-modules=Tkinter,scipy,Crypto,_ssl,bz2,_yaml 
           --include-modules=lxml._elementpath

  gave 25 files (only `.dll`, `.pyd` and `.exe` files) for a total of 71 MB, with no subfolder:

    [![enter image description here][1]][1]

* With Python 3.7.6, generating an executable with cxFreeze 6, **with the same command-line command** gives a **total of 8533 files for a total of 374 MB**!

    In particular, there is the `Lib` subfolder containing many libraries unused for this project:

    [![enter image description here][2]][2]

    Also, with the Python 2 version, Numpy was packed into 9 `.pyd` files (and nothing else), whereas here in the Python 3 version it's split in many files and subfolders.

**Question: what has changed in `cx_freeze`, resulting in this less efficient packing?**

**And how to get a similar packing with `cx_freeze` for Python 3 than with Python 2?**

  [1]: https://i.stack.imgur.com/w78hG.png
  [2]: https://i.stack.imgur.com/DcXHP.png

**Comment by marcelotduarte** [comment]
Hi, 
Obviously, from Python 2 to Python 3 there have been many changes and this impacts the system. More are required libraries, for example, encodings, unicodedata and others. Of course, it doesn't justify so many files.
I know that are some files being copied in duplicate and I have a version that eliminates this in Linux, and soon I will work on the version for windows and release.
But there is a change between these versions that makes the comparison a little unreal. I think that before, several files were compressed in the executable and I think that in version 5 this has changed and some have passed and there is a zip file.
Later, there was a zip_include_packages/zip_exclude_packages option that differ from the previous default, and it does not have it in the cxfreeze script, and this means that several files are not compressed.
To compare you should use:

```
#setup.py
from cx_Freeze import setup, Executable

build_options = {
    "excludes": ["tkinter","ssl","bz2","asyncio","numpy.random._examples"],
    "zip_include_packages": ["*"],
    "zip_exclude_packages": []}
executables = [
    Executable('numpy_example.py', targetName = 'test')
]

setup(name='Test',
      version = '0.1',
      description = 'Test',
      options = {'build_exe': build_options},
      executables = executables)
```
And build:
python setup.py build

With version 6.2 it has 562 files.
With my alpha version, in Linux the number of files is 50, using 82MB.

**Comment by josephernest** [comment]
Thanks @marcelotduarte for your feedback!

I've tried your build code, and indeed, it reduces the number of files. I get 863 files, ~ 234 MB. (Windows 7 x64, Python 3.7, cx_freeze 6.2).

> With my alpha version, in Linux the number of files is 50, using 82MB.

How can I try this alpha version on Windows? Is there a command like `pip install cxfreeze --alpha` ?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by marcelotduarte** [comment]
cxfreeze script has new options:
https://cx-freeze.readthedocs.io/en/latest/script.html
