### ISSUE TITLE
icon not set on executable on linux

### ISSUE THREAD

**Issue by flrt** [marcelotduarte/cx_Freeze#677]
My pyqt5 test is named banana (https://github.com/flrt/test-pyqt-deploy) is a very simple pyqt5 application. 
When I want to build for the 3 OS, the icon setting is OK on windows and macos, but not on Linux.

On windows [Windows build] (https://raw.githubusercontent.com/flrt/test-pyqt-deploy/master/img/test_deploy_windows.png)
On Linux : [Linux build] (https://raw.githubusercontent.com/flrt/test-pyqt-deploy/master/img/test_deploy_linux.png)

It does not set the icon on the linux platform.

My setup.py 
```
executables = [
    Executable('main.py', base=base, targetName = 'banana', icon='assets/banana.ico')
]

setup(  name = "banana",
        version = "0.1",
        description = "My Banana!",
        options = {"build_exe": buildOptions},
        executables = executables)
```

**Comment by marcelotduarte** [comment]
from the doc at https://cx-freeze.readthedocs.io/en/latest/distutils.html#cx-freeze-executable
"
icon
name of icon which should be included in the executable itself on Windows or placed in the target directory for other platforms
"

In the macOS it's set?

I think that in Linux it depends on the framework, like qt, wx, gtk...

**Comment by flrt** [comment]
Yes it's set in macos thanks to the paramater in the `info.plist` given to the `bdist_mac.`

the framework used here is qt5.

Is there a way to make it work on linux ?

**Comment by marcelotduarte** [comment]
Use a .desktop file like in this answer:
https://askubuntu.com/questions/929536/how-to-add-launcher-icon-for-python-script
