### ISSUE TITLE
ImportError: unable to find Qt5Core.dll on PATH

### ISSUE THREAD

**Issue by andrewchenshx** [marcelotduarte/cx_Freeze#678]
env:
1)Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
2)PyQt5 Version: 5.12.3
3)cx_freeze: Version: 6.1
result:
1)The exe file is generated without error messages. 
2)while the exe invoked from command line, here is the error messages:

> Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "my_program.py", line 10, in <module>
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\PyQt5\__init__.py", line 41, in <module>
    find_qt()
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\PyQt5\__init__.py", line 33, in find_qt
    raise ImportError("unable to find Qt5Core.dll on PATH")
ImportError: unable to find Qt5Core.dll on PATH

line 10 of my_program.py is as following:
`from PyQt5 import QtCore`

after some investigation, here is something interesting.
compared to the last successful build( i committed to my private git server), 
/lib/PyQt5/Qt5Core.dll, /lib/PyQt5/Qt5Gui.dll, and /lib/PyQt5/Qt5Widgets.dll and some other files are now **missing**,
and   /lib/PyQt5/Qt5Core_conda.dll, /lib/PyQt5/Qt5Gui_conda.dll, and /lib/PyQt5/Qt5Widgets_conda.dll and some other files are now **added**.

**Comment by marcelotduarte** [comment]
Your last successful build was with the same configuration or Anaconda is updated? Or some component is updated?

**Comment by andrewchenshx** [comment]
@marcelotduarte , same configuration but Anaconda is updated with this command:
`conda update anaconda`
i'm not sure the exact version of anaconda.
the python version remains 3.7.

**Comment by marcelotduarte** [comment]
It makes me think that the problem is with this anaconda update. Try to:
1- remove the build directory and run the setup again
2- do a test with the sample at:
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/PyQt5

**Comment by andrewchenshx** [comment]
hi @marcelotduarte ,

> 1- remove the build directory and run the setup again

same error message (ImportError: unable to find Qt5Core.dll on PATH)

> 2- do a test with the sample at:
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/PyQt5

same error message(ImportError: unable to find Qt5Core.dll on PATH)

**Comment by marcelotduarte** [comment]
If you have a C compiler, you can test the development version:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
Can you check if this has been resolved?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
