### ISSUE TITLE
EXE exits without error shown but works from command line

### ISSUE THREAD

**Issue by double0darbo** [marcelotduarte/cx_Freeze#682]
I am through the looking glass here. 

I am running cx_freeze on the following system:

- OS: Windows 10
- System type: 64-bit, x64-based processor
- Python ver: 3.7
- conda ver: 4.8.3
- cx_freeze                 6.1              conda-forge

I've included the main modules used for this program.
- matplotlib:                3.2.2                         0
- numpy:                     1.18.5           py37h6530119_0
- pandas:                    1.0.5            py37h47e9c7a_0
- scipy:                     1.5.0            py37h9439919_0

First build had initial problem discussed in #355 and #199 , including the proper DLLs.
```
INTEL MKL ERROR: The specified module could not be found. mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
```
I corrected by copying `libiomp5md.dll`, `mkl_intel_thread.dll`, and `mkl_sequential.dll` into the build folder. 

Next, I get a scipy error, similar to past issues, #43 , #233 , and others, regarding the scipy modules.
```
...lib\site-packages\scipy\ndimage\filters.py", line 36, in <module>
    from . import _ni_support
ImportError: cannot import name '_ni_support' from 'scipy.ndimage' 
```
I solved this, not by specifying scipy in the `includes` exe setup options, but rather in the `"include_files"` option as `(scipy_path, "scipy")`, where scipy_path is the location of the `site-packages\scipy` folder for the specific envs path (conda environment) I am building the .exe in. I am not certain why I can't specify the particular modules used in `includes`, as I have done this for `matplotlib.pyplot`. 

My program will execute now as expected, but only from the conda powershell/command line. When attempting to click on the .exe file, nothing happens. 

Attempting a solution, I placed the `base="Win32GUI"` in the Executable, as per [here](https://stackoverflow.com/questions/22004721/creating-exe-file-with-cx-freeze-for-a-tkinter-interface), but to no avail. Thoughts?

**Comment by double0darbo** [comment]
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Users\rob.macdonald\Anaconda3\envs\clone37\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\rob.macdonald\Anaconda3\envs\clone37\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "pykopter.py", line 738, in <module>
  File "pykopter.py", line 735, in main
RuntimeError: input(): lost sys.stdin

---------------------------
OK   
---------------------------
This is the exact error I get with `base="Win32GUI"`.

**Comment by double0darbo** [comment]
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Users\<user>\Anaconda3\envs\clone37\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\<user>\Anaconda3\envs\clone37\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "foo.py", line 738, in <module>
  File "foo.py", line 735, in main
RuntimeError: input(): lost sys.stdin

---------------------------


This is the exact error I get with `base="Win32GUI".`

**Comment by marcelotduarte** [comment]
Try to add the "scipy.ndimage.filters" to packages option or "scipy.ndimage._ni_support" to includes option.
If it fails, show me the folder at `site-packages\scipy\ndimage`
For the second comment, do you have a input() in your code or in some lib? In the Win32GUI mode, the input is disabled.

**Comment by double0darbo** [comment]
The `ndimage.filters` worked, but I have other scipy packages causing errors now, specifically the `linalg` method:
```
  File "C:\Users\double0darbo\Anaconda3\envs\conda37\lib\site-packages\scipy\sparse\csgraph\__init__.py", line 183, in <module>
    from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
  File "stringsource", line 105, in init scipy.sparse.csgraph._shortest_path
AttributeError: type object 'scipy.sparse.csgraph._shortest_path.array' has no attribute '__reduce_cython__'
```
I am looking to slim it down rather than using `"include_files":[(scipy_path, "scipy")]`, but this seems like vanity while the bigger problem persists, since including the full scipy file is functional.

I did have an input function in my code, which I greyed out with no change for the better. The `exe` still does not launch and now the program will not run from the command prompt either. 

Here is my set-up script to help guide where I may have taken a wrong turn:

```
#!/usr/bin/python
from cx_Freeze import setup, Executable
import os, matplotlib, sys, numpy, tkinter, scipy, codecs

wd = os.getcwd()
os.environ['TCL_LIBRARY'] = os.path.join(wd, r'tcl\tcl8.6')
os.environ['TK_LIBRARY'] = os.path.join(wd, r'tcl\tcl8.6')

base = None
if sys.platform == "win32": base = "Win32GUI"
scipy_path = os.path.join(wd, r'Lib\site-packages\scipy')
build_exe_options = {"includes":   ["matplotlib.backends.backend_tkagg",
                                    "matplotlib.pyplot",
                                    "tkinter.filedialog",
                                    'numpy.matlib', 
                                    'multiprocessing.process',
                                    "numpy",
                                    # "scipy.ndimage._ni_support",
                                    # "scipy.stats", # ".gaussian_kde",
                                    # "scipy.linalg",
                                    # "scipy.signal",
                                    "codecs"],
                      "include_files":[(matplotlib.get_data_path(),"mpl-data"),
                                        (scipy_path, "scipy"),
                                        # (r'lib\site-packages\scipy\sparse',
                                        #  "scipy/sparse"),
                                       'Library/bin/libiomp5md.dll',
                                       'Library/bin/mkl_intel_thread.dll',
                                       'Library/bin/mkl_sequential.dll' 
                                       ],
                      "excludes":[],
                    }
setup(
    name = "foo", version = "0.0", description = "Jun_25_2020",
    options = {"build_exe": build_exe_options},
    executables = [Executable("foo.py", base=base)]    
)
```

Not having an `input` fxn presents a new challenge for my program, as I needed a way to get user input into it (my next hill to climb is the tkinter, which may help solve this problem). I will explore ways to help this in the future, as presently I can get the program to work in the command line without specifying the `base='Win32GUI'`.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.2 has just been released with namespace detection. Please, try it.

**Comment by double0darbo** [comment]
I am not able to get any similar response with the new installation. It seems to have sent me back further:

---------------------------
cx_Freeze: Python error in main script (traceback unavailable)
---------------------------
Cannot import traceback module.
Exception: No module named 'traceback'
Original Exception: No module named 'os'
---------------------------
OK   
---------------------------

**Comment by marcelotduarte** [comment]
> Not having an `input` fxn presents a new challenge for my program

If you don't use a tkinter or wx or another framework, you don't need to add Win32GUI. On windows, you can run the console app too.
In cx-freeze 6.2 the support for matplot has been enhanced (include mpl-data) but has a bug that can be workaround:
https://github.com/marcelotduarte/cx_Freeze/issues/692#issuecomment-657125847

This new error is strange. Can you remove and reinstall cx-freeze package and use the workarounds?

**Comment by double0darbo** [comment]
I have found the error may be related to my program, and I am having to go through object by object to see where the error lies. 

I have had progress with opening the program, but now that I've incorporated the GUI with tkinter, new problems are arising. 

I believe that reinstalling my anaconda and cx_freeze environments solved some concerns, but I am running aground with getting the output to show in the GUI, to show that it is indeed working. This will show where it breaks, so more to come once I unlock the tkinter framework.

**Comment by double0darbo** [comment]
I have been able to get my program to run using the console, but not the app. S'funny to wind up back here, but I have made some progress with the update, and by getting rid of the eviron variables, and matching closely to what I put up earlier for my set-up.

**Comment by marcelotduarte** [comment]
If you have a C compiler, you can test the development version:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Comment by double0darbo** [comment]
I have run this install, and now I get a new error:   

```
File "C:\Users\<user>\Anaconda3\envs\pyko\lib\sysconfig.py", line 358, in _get_sysconfigdata_name
    abi=sys.abiflags,
AttributeError: module 'sys' has no attribute 'abiflags'
```

**Comment by marcelotduarte** [comment]
PR #727 solve this. Can you test again?

**Comment by double0darbo** [comment]
OK, that hurdle is now passed--no longer get the abiflags error--thanks! 

I am at the same point from a week ago. 

Perhaps I am not doing the C-compiler test properly. Can you walk me through this post-running the install? I ran the install, which worked. Do I now build from that and not the console?

**Comment by marcelotduarte** [comment]
With the development version of cx-freeze, workarounds aren't necessary.
For example, this test with matplotlib pass, see the setup.py, it's so simple.
https://github.com/marcelotduarte/cx_Freeze/tree/master/cx_Freeze/samples/matplotlib

**Comment by double0darbo** [comment]
Thank you for getting back to me so fast! OK, makes sense as a way to bypass having to make the plugins on the respective files. I suppose I need to run this each time to ensure I have the latest updates, yes? 

I was able to get matplotlib examples to run, but had to add my own DLLs, same as before, so I'm still not clear on the benefit. I did get through the workarounds, however. 

However, back to the original problem, the matplotlib files do not run from the exe, but rather from console only. Fortunately, I can get them to run from there, so's I know I'm not losing it.

**Comment by marcelotduarte** [comment]
Until I release a new version, if you can test the latest updates, you should run the command:
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop
A more stable is at:
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@master

Show me your updated setup.py

**Comment by double0darbo** [comment]
```
import sys
from cx_Freeze import setup, Executable

base = 'Console'
if sys.platform == 'win32':
    base = 'Win32GUI'

options = {
    'build_exe': {"include_files": ['Library/bin/libiomp5md.dll',
                                    'Library/bin/mkl_intel_thread.dll',
                                    'Library/bin/mkl_sequential.dll' 
                                     ],
                    # Sometimes a little fine-tuning is needed
                    # exclude all backends except wx
                    'excludes': ['gtk', 'PyQt4', 'PyQt5', 'tkinter']
    }
}

executables = [
    Executable('matplotlib_afm.py'),
    Executable('matplotlib_eg.py', base=base)
]

setup(name='matplotlib_samples',
      version='0.1',
      description='Sample matplotlib script',
      executables=executables,
      options=options
      )
```

**Comment by double0darbo** [comment]
Just following back up. Is this how you imagined the setup file would look?

**Comment by averner** [comment]
Hi Marcelo (@marcelotduarte) and @double0darbo,

I've read your correspondence on the cx_Freeze issues with Python packages. Thanks for sharing your experience. I'm having trouble with using cx_Freeze to create a console executable from Python code that uses scipy. I tried numerous solutions, which are listed above, but none of them worked. I'm using cx_Freeze 6.2 (latest from your development branch), scipy 1.5.0, Python 3.7.7, Conda 4.8.2, running on x64 Windows 10. Below is a minimalistic Python script that uses scipy, and a setup.py file:

test.py:
```
import scipy
if __name__ == '__main__':
    print(scipy.__version__)
```

setup.py:
```
from cx_Freeze import setup, Executable
build_exe_options = {'build_exe': r'C:\Dev\DNA\dist', include_files: [(r'C:\Env.DNA\Lib\site-packages\scipy', 'scipy')]}
exe = Executable(script=r'C:\Dev\DNA\test.py', targetName='DNA.exe')
setup(name='DNA', version='0.1', description='DNA', options={'build_exe': build_exe_options}, executables=[exe])
```

For the above example, an executable is created. When been bun in Conda shell with the proper environment is activated, it runs fine. However, I need to be able to execute it in the ordinary Windows command line, which I cannot do as it dies on the import line, never reaching the line that prints scipy version. Any help with this issue will be mostly appreciated. Thank you in advance.

Regards,
Alexander (@averner).

**Comment by double0darbo** [comment]
Is this the exact copy? The line: `build_exe_options = {'build_exe': r'C:\Dev\DNA\dist', include_files: [(r'C:\Env.DNA\Lib\site-packages\scipy', 'scipy')]}` should have quotes around `include_files` to begin with. 

If it helps, here's what I got for an error on my system:

```
Traceback (most recent call last):
  File "...\envs\pyko\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "...\envs\pyko\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in run
    exec(code,  m.__dict__)
  File "test.py", line 1, in <module>
    import scipy
  File "...\envs\pyko\build\exe.win-amd64-3.7\scipy\__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "...\envs\pyko\lib\site-packages\numpy\__init__.py", line 235, in <module>
    import mkl
  File "...\envs\pyko\lib\site-packages\mkl\__init__.py", line 54, in <module>
    from ._py_mkl_service import *
  File "mkl\_mkl_service.pyx", line 27, in init mkl._py_mkl_service
ModuleNotFoundError: No module named 'six'
```

I haven't dig into this any further. Thanks for the idea to try it though. 

Here's my script:

```
from cx_Freeze import setup, Executable
import os

wd = os.getcwd()

scipy_path = os.path.join(wd, r'Lib\site-packages\scipy')

build_exe_options = {"include_files": [(scipy_path, "scipy"),
                                    	'Library/bin/libiomp5md.dll',
                                    	'Library/bin/mkl_intel_thread.dll',
                                    	'Library/bin/mkl_sequential.dll' ]}
exe = Executable('test.py', targetName='DNA.exe')
setup(name='DNA', version='0.1', description='DNA', options={'build_exe': build_exe_options}, executables=[exe])
```

**Comment by averner** [comment]
Hi @double0darbo,

Thank you very much for your help! I used your version of setup.py, and it worked. I was able to run my test file. The version that worked for me is as follows:

```
from cx_Freeze import setup, Executable
build_exe_options = {'include_files': [(r'C:\Env.DNA\Lib\site-packages\scipy', 'scipy'), 
                                                           r'C:\Env.DNA\Library\bin\mkl_intel_thread.dll', 
                                                           r'C:\Env.DNA\Library\bin\libiomp5md.dll', 
                                                           r'C:\Env.DNA\Library\bin\mkl_sequential.dll']}
exe = Executable(script=r'C:\Dev\DNA\test.py', targetName='DNA.exe', base=None)
setup(name='KLA DNA', version='0.1', description='KLA - OMD/Algo - DNA', options={'build_exe': build_exe_options}, 
          executables=[exe])
```

Many thanks again, and best wishes.

Regards,
Alexander.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Comment by marcelotduarte** [comment]
@double0darbo 
cx_Freeze 6.3 has just been released.
Can you check if this has been resolved?

**Comment by double0darbo** [comment]
Please see comment here: https://github.com/marcelotduarte/cx_Freeze/issues/739#issuecomment-759056808. Plenty more debugging to come, but I am making progress after many errors.

**Comment by mbunse** [comment]
Same issue here, with cx_Freeze 6.5.3, numpy 1.20.1, mkl 2020.4 (installed via conda) on Windows 10 1909.
I solved the issue by including all mkl_*.dll files
```python
python_path = os.path.split(sys.executable)[0] 
mkl_omp_files_relative_path = os.path.join("Library", "bin")
mkl_omp_files = glob.glob(os.path.join(python_path, mkl_omp_files_relative_path, "libiomp*.dll")) 
mkl_files = glob.glob(os.path.join(python_path, mkl_omp_files_relative_path, "mkl_*.dll"))
setup(
    ....
    options={
        "build_exe": {
            "includes": ["pandas", "PySimpleGUI", ],
            "excludes": ["pytest", "unittest"],
            "include_files": mkl_files + mkl_omp_files,
        },
    }
)
```
The resulting MSI installer is 280 MB big. Two weeks ago i had a build (in a different environment for which I don't have the specs anymore) were it worked without inluding mkl files and the resulting installer was only 50 MB big. Fixing to numpy<1.18.3 does not work for me.

**Comment by adouverny** [comment]
I had the same issue very recently. The program (the executable) would run fine in PyCharm and in the anaconda prompt, but would crash without errors when run from the command line or by clicking the excutable in Explorer. 

I tried running the python script in the command prompt via C:\<INTERPRETER_PATH>\python.exe C:\<PATH_TO_SCRIPT>script.py, and would get the following error (see long traceback below).

Apparently this was casued by some issue when installing numpy via conda. Removing numpy from the environment and insalling it with pip solved the problem immediately. It worked both when run from the command line as a python script AND as an executable. Perhaps this might help others as well.

NB: I made sure to explicitly include the mkl_thread.dll in my "include_files".  

```
C:\...\envs\pytorch\lib\site-packages\numpy\__init__.py:138: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\...\envs\pytorch\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\...\envs\pytorch\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\...\envs\pytorch\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\script.py", line 27, in <module>
    from mayavi.core.ui.api import MayaviScene, MlabSceneModel, SceneEditor
  File "...\envs\pytorch\lib\site-packages\mayavi\core\ui\api.py", line 1, in <module>
    from mayavi.tools.mlab_scene_model import MlabSceneModel
  File "...\envs\pytorch\lib\site-packages\mayavi\tools\mlab_scene_model.py", line 8, in <module>
    from tvtk.pyface.scene_model import SceneModel
  File "...\envs\pytorch\lib\site-packages\tvtk\pyface\scene_model.py", line 20, in <module>
    from tvtk.pyface.tvtk_scene import TVTKScene
  File "...\envs\pytorch\lib\site-packages\tvtk\pyface\tvtk_scene.py", line 19, in <module>
    from apptools.persistence import state_pickler
  File "...\envs\pytorch\lib\site-packages\apptools\persistence\state_pickler.py", line 116, in <module>
    import numpy
  File "...\envs\pytorch\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "...\envs\pytorch\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

**Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.**

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "C:\...\envs\pytorch\python.exe"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.
```

**Comment by marcelotduarte** [comment]
@adouverny 
With a series of patches, mainly #964, #965, #966, #967, #968, packages distributed as manylinux wheels, like Pillow and NumPy, which use extension modules, can locate its external shared libraries. With the help of patchelf, we automatically modify the appropriate RPATH entries such that these libraries will be picked up at runtime.
Tested with Pillow 6.2.x, 7.2.x and 8.1.2 and numpy 1.18.2, 1.19.x and 1.20.x
Please note that patchelf and the C compiler must be installed. 
To install patchelf in debian/ubuntu:
`sudo apt install patchelf`
Now you can test the development version:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main`
If your project builds successfully, please notify me with a comment.

For numpy+mkl the solution is to come.

**Comment by marcelotduarte** [comment]
@adouverny @mbunse @double0darbo 
With recent patches and changes in hooks of matplotlib, numpy and pandas, I get success building the samples matplotlib and pandas (that use numpy).
The samples are in https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples

I used numpy 1.18.2, 1.19.4 and 1.20.1 to test, in py36, 37, 38, 39 on Windows 10
And used numpy 1.19.5+mkl and py38 only (with cx-freeze 6.5.3 I get errors, with current main branch, I get success).
Tested only with official python.org (not anaconda yet).

Please test it and put a comment.

1) Sources: `pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@main`
2) Wheels: https://github.com/marcelotduarte/cx_Freeze/suites/2241813794/artifacts/46547164

**Comment by mbunse** [comment]
Hi @marcelotduarte,
thank you very much for your effort!
Unfortunatly, the fix did not work for me, I still get the following error message:
```
INTEL MKL ERROR: Das angegebene Modul wurde nicht gefunden. mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
```
My setup.py looks like above, I just commented out the `build_exe` part.

This is my conda environment:
```
channels:
  - conda-forge
  - defaults
dependencies:
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - bleach=3.3.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2021.1.19=haa95532_1
  - certifi=2020.12.5=py38haa95532_0
  - cffi=1.14.5=py38hcd4344a_0
  - chardet=4.0.0=py38haa95532_1003
  - cmarkgfm=0.4.2=py38h2bbff1b_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py38h2bbff1b_2
  - cryptography=3.4.6=py38h71e12ea_0
  - docutils=0.16=py38_1
  - future=0.18.2=py38_1
  - idna=2.10=pyhd3eb1b0_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2020.2=254
  - keyring=22.3.0=py38haa95532_0
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - liblapack=3.9.0=8_mkl
  - mkl=2020.4=hb70f87d_311
  - more-itertools=8.7.0=pyhd3eb1b0_0
  - numpy=1.20.1=py38h0cc643e_0
  - openssl=1.1.1j=h2bbff1b_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.2=py38h4c96930_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pkginfo=1.7.0=py38haa95532_0
  - pluggy=0.13.1=py38_0
  - py=1.10.0=pyhd3eb1b0_0
  - py-cpuinfo=7.0.0=py_0
  - pycparser=2.20=py_2
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pysimplegui=4.34.0=pyh44b312d_0
  - pysocks=1.7.1=py38haa95532_0
  - pytest=6.2.2=py38haa244fe_0
  - pytest-benchmark=3.2.3=py38_0
  - pytest-cov=2.11.1=pyh44b312d_0
  - python=3.8.0=hc9e8b01_5
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - pywin32-ctypes=0.2.0=py38_1000
  - readme_renderer=24.0=py38haa95532_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-toolbelt=0.9.1=py_0
  - rfc3986=1.4.0=py_0
  - setuptools=49.6.0=py38haa244fe_3
  - setuptools-scm=5.0.1=pyhd3eb1b0_1
  - setuptools_scm=5.0.1=hd8ed1ab_0
  - six=1.15.0=py38haa95532_0
  - sqlite=3.33.0=h2a8f88b_0
  - tk=8.6.10=h8ffe710_1
  - toml=0.10.1=py_0
  - tqdm=4.56.0=pyhd3eb1b0_0
  - twine=3.3.0=py38haa244fe_1
  - urllib3=1.26.3=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - webencodings=0.5.1=py38_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - cx-freeze==6.6.dev0
    - importlib-metadata==3.7.2
    - zipp==3.4.1
```

**Comment by marcelotduarte** [comment]
@mbunse For conda, I put the hooks is in develop branch:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

It builds simple samples that use numpy. I used miniconda3 with py3.8.8 to test.

Do you need wheels to test?

**Comment by mbunse** [comment]
@marcelotduarte Thank you very much again! 

The app starts without any problem from within a conda shell, now! Great work!

But without conda in my path I just get a generic popup window "app.exe has stopped working". Here you can find a minimal example reproducing the problem: https://github.com/mbunse/cxfreeze_test
The environment uses python 3.8.8 with anaconda3. I am still reading similar error reports from the past to find a fix for that.

**Comment by marcelotduarte** [comment]
@mbunse I updated the branch, please rerun:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

Also, with recent changes, you should use --includes-msvcr=true or include it in build_exe option of the setup file if you need vcruntimes in the build.

Your sample now build for me.

**Comment by mbunse** [comment]
The app now works as expected after installation. `--includes-msvcr=true` was not necessary. 
Thank you very, very much!

**Comment by adouverny** [comment]
@marcelotduarte I have tried to use the newest branch in a clean test environemnt, and it works like a charm (I made sure to install numpy via pip this time). Thank you very much for your work!

**Comment by ArVar** [comment]
Finally, installing numpy from pip (together with the most recent cx_freezer repo) did also the trick for me. 👍

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
