### ISSUE TITLE
cx_Freeze 6.2 breaks matplotlib projects 

### ISSUE THREAD

**Issue by smalbadger** [marcelotduarte/cx_Freeze#692]
When I build my project using cx_Freeze 6.1, it works fine. I recently upgraded to 6.2 and I get the following error:

`error: The baseline image directory does not exist. This is most likely because the test data is not installed. You may need to install matplotlib from source to get the test data.`

I tried building matplotlib from source, but that didn't solve it. Then I stumbled on [this SO post](https://stackoverflow.com/questions/62828976/cx-freeze-error-baseline-image-directory-does-not-exist) and found that it might be a cx-Freeze/matplotlib compatibility issue. 

Thanks for your great work on this package! My team really enjoys using it.

<details>
<summary>System information</summary>

### Machine
- **OS**: Windows-10-10.0.18362-SP0

---

### Python
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
<details>
<summary>Packages</summary>

Package Name | Version
------------ | -------   
alabaster | 0.7.12
atomicwrites | 1.4.0
attrs | 19.3.0
Babel | 2.8.0
BeneDict | 0.3.2
cached-property | 1.5.1
certifi | 2020.6.20
cffi | 1.14.0
chardet | 3.0.4
click | 7.1.2
colorama | 0.4.3
comtypes | 1.1.7
cx-Freeze | 6.2
cycler | 0.10.0
decorator | 4.4.2
docutils | 0.16
idna | 2.10
imageio | 2.9.0
imagesize | 1.2.0
importlib-metadata | 1.7.0
Jinja2 | 2.11.2
joblib | 0.16.0
kiwisolver | 1.2.0
MarkupSafe | 1.1.1
matplotlib | 3.2.2
more-itertools | 8.4.0
MouseInfo | 0.1.3
networkx | 2.4
nltk | 3.5
numpy | 1.19.0
packaging | 20.4
Pillow | 7.2.0
pluggy | 0.13.1
psutil | 5.7.0
py | 1.9.0
PyAutoGUI | 0.9.50
pycparser | 2.20
PyGetWindow | 0.0.8
pygit2 | 1.2.1
Pygments | 2.6.1
PyMsgBox | 1.0.8
pyparsing | 2.4.7
pyperclip | 1.8.0
PyRect | 0.1.4
PyScreeze | 0.1.26
PySide2 | 5.15.0
pytest | 5.4.3
python-dateutil | 2.8.1
PyTweening | 1.0.3
pytz | 2020.1
PyWavelets | 1.1.1
pywin32 | 228
pywinauto | 0.6.8
PyYAML | 5.3.1
qtmodern | 0.2.0
QtPy | 1.9.0
regex | 2020.6.8
requests | 2.24.0
scikit-image | 0.17.2
scikit-learn | 0.23.1
scipy | 1.5.1
shiboken2 | 5.15.0
six | 1.15.0
sklearn | 0.0
snowballstemmer | 2.0.0
Sphinx | 3.1.2
sphinx-rtd-theme | 0.5.0
sphinxcontrib-applehelp | 1.0.2
sphinxcontrib-devhelp | 1.0.2
sphinxcontrib-htmlhelp | 1.0.3
sphinxcontrib-jsmath | 1.0.1
sphinxcontrib-qthelp | 1.0.3
sphinxcontrib-serializinghtml | 1.1.4
threadpoolctl | 2.1.0
tifffile | 2020.7.4
tqdm | 4.47.0
typing | 3.7.4.1
urllib3 | 1.25.9
wcwidth | 0.2.5
zipp | 3.1.0

</details>
</details>

**Comment by marcelotduarte** [comment]
I have already identified the source of this problem, it is the patch 7ec3eaa96765703c53c377e4f309bdde0a947bac
Using the matplot sample, I see an issue with numpy 1.18.3 to 1.19 and pillow 7.x, and I'm investigating.
For now, it has a workaround.
pip install "numpy<1.18.3" "pillow<7"
To build add ["matplotlib.tests", "numpy.random._examples"] to excludes or build with:
python setup.py build_exe --excludes=matplotlib.tests,numpy.random._examples
If you have a "excludes" in your setup.py, add the two excluded modules int it, options in setup is exclusive.

**Comment by marcelotduarte** [comment]
@smalbadger 
cx_Freeze 6.3 has just been released.
