### ISSUE TITLE
cx_Freeze 6.2 - TypeError dist must be a Distribution instance

### ISSUE THREAD

**Issue by DraXus** [marcelotduarte/cx_Freeze#693]
I've upgraded cx_Freeze from 6.1 to 6.2 in a project and now I got this error when running `python setup.py bdist_msi`:
```
TypeError dist must be a Distribution instance
```

This seems to be related to this warning:
```
UserWarning: Distutils was imported before Setuptools
```

Downgrading to 6.1 fixed the issues.

Environment:
* Python 3.6.8
* Windows 10

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
