### ISSUE TITLE
cx_Freeze 6.2 error when using bdist_msi

### ISSUE THREAD

**Issue by mwentzWW** [marcelotduarte/cx_Freeze#699]
`TypeError: dist must be a Distribution instance`

cx-freeze==6.2
setuptools>48.0

python==3.7.7
python from conda

system: Windows 10 64-bit

Build works fine, but `bdist_msi` fails with the final line reading `TypeError: dist must be a Distribution instance`.

Current work around:

`pip install cx-freeze==6.1 setuptools==47.1.1`

**Comment by marcelotduarte** [comment]
Duplicate of #693 
The fix has been merged. A new release will be coming soon.
