### ISSUE TITLE
Allow changes in executable filename

### ISSUE THREAD

**Issue by cainesi** [marcelotduarte/cx_Freeze#703]
The bundled application currently looks at the name of the executable to determine which python module to load to start the program (this is from __startup__.py):

    def run():
        baseName = os.path.normcase(os.path.basename(sys.executable))
        name, ext = os.path.splitext(baseName)
        module = __import__(name + "__init__")
        module.run()

This means that the program breaks if the executable filename changes, which is a bit unexpected.  Would people be open to a change to instead store the name of the relevant module in the BUILD_CONSTANTS module?

**Comment by marcelotduarte** [comment]
The name is derivated from the executable:
https://github.com/marcelotduarte/cx_Freeze/blob/master/cx_Freeze/freezer.py#L707
I think this is good, the user cannot change the name of your program.
And the developer can define the name at setup, using the parameter targetName.

**Comment by cainesi** [comment]
From what I could understand when I tried to reverse engineer it:

1. A compiled copy of Common.c (or alternative) becomes the executable file (suppose it is "EXECUTABLE");
2. The executable finds and launches "__startup__.py", (so __startup__.py is included with that name);
3.  __startup__.py then finds the name of the executable that launched python (EXECUTABLE), and finds and launches EXECUTABLE__init__.py (which is a renamed copy of Console.py, by default);
4. EXECUTABLE__init__.py (after making some adjustments to the environment) determines a new module name by stripping the "__init__" from its own name, adding "__main__" and loading that module (i.e., EXECUTABLE__main__).
5. The target script is put into EXECUTABLE__main__ so that finally launches the program.

It seems a little fragile to have the data about internal module names encoded into the executable file name like that.  It means if a user installs my app (say "bob.exe") and later decides that they want to rename the executable for some reason (say to "jack.exe") everything mysteriously breaks (which has happened...).

In the change I am proposing, we could still let the setup script specify the name of the executable, it is just that none of the subsequent steps would depend on the file name.  E.g., we could always used fixed names for the *__init__ and *__main__ files (e.g., cxfrozen__init__ / cxfrozen__main__).  Or we could keep those names variable, but encode the underlying module names differently.

The one big problem I can see is if you were including multiple Executables in one freeze, but not sure if that is a common use case?

**Comment by marcelotduarte** [comment]
The correct info is:
There are 3 scripts are saved to library.zip and an external C module (Console.c or Win32GUI.c):
Console.c -> compiled to name of your program (executable)
`__startup__.py` calls `executable__init__.py`
Console.py becomes the `executable__init__.py`
executable.py (your entry point) becomes `executable__main__.py`

I understood that you want to permit the rename. I think that you could do it without change the cx-freeze behavior. cx-freeze can generate varios executables using the library.zip and dll/so. I have project with 6, 8 executables using the same base. If the name was fixed, like in py2exe one module, the disk space grows. I migrated to cx-freeze because of this and because I can use it in windows and linux.

How you can permit the rename? You could specify a initscript and base that you create. See at:
https://cx-freeze.readthedocs.io/en/latest/distutils.html#cx-freeze-executable

**Comment by cainesi** [comment]
Okay, if people are actually using multiple executables we can leave it.  I can't see a good way of accommodating that without dynamically creating the bases...

**Comment by marcelotduarte** [comment]
It is possible to implement this with a new option in executable (internal_name) and then have a change in startup. And this internal_name recorded in BUILD_CONSTANTS as you initially thought.
But there would have to be a way to identify the executable or allow only one if that option is used.

**Comment by cainesi** [comment]
I've given this some more thought.  How about this:
1. We create two version of the launch executable.  "Version 1" would use a hard-coded name to find the target script, and "Version 2" would use the current procedure. 
2. When freezing, we would check if there was only one executable (in which case we would use "Version 1"), or multiple executables (in which case "Version 2"). 

If that sounds acceptable, I can work on something when I get some free time.

**Comment by marcelotduarte** [comment]
@cainesi Please check PR #858 
In the develop branch it is already merged, so you can test.
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.

**Comment by cainesi** [comment]
Hi Marcelo-- Finally had a chance to check this.  Works for me.  Thanks for making this fix.

> @cainesi Please check PR #858
