### ISSUE TITLE
Matplotlib's mpl_toolkits raises TypeError

### ISSUE THREAD

**Issue by mx2048** [marcelotduarte/cx_Freeze#705]
After the patch in [this comment](https://github.com/marcelotduarte/cx_Freeze/issues/692#issuecomment-657125847), `mpl_toolkits` raises `TypeError` in function `_ReplacePathsInCode` of `finder.py` in this code

```
if searchValue == "*":
    searchValue = os.path.dirname(topLevelModule.file)
```
`topLevelModule.file` becomes `None`.

To fix that, use `'excludes': ['mpl_toolkits']` in the `build_exe`.

Also see this [comment](https://github.com/marcelotduarte/cx_Freeze/issues/696#issuecomment-662776313).

**Comment by mx2048** [comment]
Update: package `google` also raises the same error.

**Comment by mx2048** [comment]
Environment: `Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32`

**`pip list`**

Package                  Version
------------------------ ------------
atomicwrites             1.3.0
attrs                    19.3.0
beautifulsoup4           4.8.2
boto3                    1.12.22
botocore                 1.15.22
bs4                      0.0.1
cachetools               4.0.0
certifi                  2019.11.28
chardet                  3.0.4
colorama                 0.4.3
cx-Freeze                6.2
cycler                   0.10.0
decorator                4.4.2
docutils                 0.15.2
gensim                   3.8.1
google-api-core          1.16.0
google-auth              1.11.3
google-cloud-core        1.3.0
google-cloud-storage     1.26.0
google-resumable-media   0.5.0
googleapis-common-protos 1.51.0
idna                     2.9
ipython-genutils         0.2.0
Jinja2                   2.11.2
jmespath                 0.9.5
joblib                   0.14.1
jsonschema               3.2.0
jupyter-core             4.6.3
kiwisolver               1.1.0
lxml                     4.5.0
MarkupSafe               1.1.1
matplotlib               3.2.1
more-itertools           8.2.0
nbformat                 5.0.4
nltk                     3.4.5
numpy                    1.18.1+mkl
packaging                20.3
pandas                   1.0.2
pip                      20.1.1
pipdeptree               1.0.0
plotly                   4.6.0
pluggy                   0.13.1
protobuf                 3.11.3
psutil                   5.7.0
py                       1.8.1
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pyparsing                2.4.6
pyrsistent               0.15.7
pytest                   5.4.1
python-dateutil          2.8.1
pytz                     2019.3
pywin32                  227
requests                 2.23.0
retrying                 1.3.3
rsa                      4.0
s3transfer               0.3.3
scikit-learn             0.22.2.post1
scipy                    1.4.1
selenium                 3.141.0
setuptools               41.2.0
six                      1.14.0
sklearn                  0.0
smart-open               1.10.0
soupsieve                2.0
traitlets                4.3.3
urllib3                  1.25.8
wcwidth                  0.1.8
Whoosh                   2.7.4
xlrd                     1.2.0
XlsxWriter               1.2.2


**Full list of modules having `topLevelModule.file` as `None`:**

google\auth\transport\grpc.py
google\protobuf\internal\wire_format.py
google\api_core\page_iterator.py
google\protobuf\text_format.py
google\resumable_media\requests\download.py
google\protobuf\pyext\__init__.py
google\auth\environment_vars.py
google\protobuf\internal\python_message.py
google\cloud\storage\acl.py
google\auth\crypt\rsa.py
google\protobuf\internal\encoder.py
google\cloud\storage\hmac_key.py
google\auth\_cloud_sdk.py
google\auth\_helpers.py
google\auth\_service_account_info.py
google\protobuf\internal\__init__.py
mpl_toolkits\mplot3d\axis3d.py
google\protobuf\descriptor_pool.py
google\cloud\storage\__init__.py
mpl_toolkits\mplot3d\proj3d.py
google\api_core\__init__.py
google\protobuf\pyext\cpp_message.py
google\auth\credentials.py
google\auth\jwt.py
google\cloud\storage\notification.py
google\oauth2\service_account.py
google\protobuf\message.py
google\protobuf\reflection.py
google\auth\compute_engine\_metadata.py
google\api_core\exceptions.py
google\protobuf\message_factory.py
google\auth\compute_engine\__init__.py
google\auth\transport\__init__.py
google\api_core\datetime_helpers.py
google\oauth2\credentials.py
google\auth\transport\requests.py
mpl_toolkits\mplot3d\__init__.py
google\cloud\storage\bucket.py
google\api_core\client_options.py
google\protobuf\internal\api_implementation.py
google\auth\app_engine.py
google\protobuf\duration_pb2.py
google\cloud\exceptions.py
google\cloud\storage\batch.py
google\auth\iam.py
google\auth\compute_engine\credentials.py
google\cloud\storage\blob.py
google\protobuf\__init__.py
google\protobuf\descriptor_database.py
mpl_toolkits\mplot3d\axes3d.py
google\protobuf\internal\extension_dict.py
google\oauth2\_client.py
google\cloud\storage\_signing.py
google\resumable_media\requests\_helpers.py
google\cloud\storage\_helpers.py
google\resumable_media\__init__.py
google\protobuf\descriptor_pb2.py
google\auth\exceptions.py
google\protobuf\internal\type_checkers.py
google\auth\__init__.py
google\protobuf\internal\containers.py
google\protobuf\internal\enum_type_wrapper.py
google\resumable_media\_upload.py
google\resumable_media\_download.py
google\oauth2\__init__.py
google\protobuf\internal\decoder.py
google\auth\crypt\base.py
google\cloud\storage\client.py
google\resumable_media\common.py
google\protobuf\symbol_database.py
google\cloud\storage\constants.py
google\protobuf\descriptor.py
google\resumable_media\requests\__init__.py
google\protobuf\timestamp_pb2.py
google\protobuf\text_encoding.py
google\cloud\client.py
google\auth\crypt\_python_rsa.py
google\api_core\iam.py
google\protobuf\internal\well_known_types.py
google\protobuf\internal\message_listener.py
google\auth\crypt\__init__.py
google\cloud\storage\_http.py
google\auth\_default.py
google\resumable_media\requests\upload.py
google\cloud\_helpers.py
google\auth\crypt\_cryptography_rsa.py
mpl_toolkits\mplot3d\art3d.py
google\resumable_media\_helpers.py
google\auth\transport\_http_client.py

**Comment by marcelotduarte** [comment]
merged PR #695, #697 and some other not yet merged solves these issues.

**Comment by marcelotduarte** [comment]
If you have a C compiler, you can test the development version:
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop

**Comment by mx2048** [comment]
I tested on the development version too, and the error persists.

```
  File "...\cx_Freeze\finder.py", line 543, in _ReplacePathsInCode
    searchValue = os.path.dirname(topLevelModule.file)
  File "C:\Program Files (x86)\Python38\lib\ntpath.py", line 223, in dirname
    return split(p)[0]
  File "C:\Program Files (x86)\Python38\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by marcelotduarte** [comment]
try:
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@master

**Comment by mx2048** [comment]
Yes, the same error both with development and master.

There are two ways to avoid this error:

Whether use `"excludes": ['mpl_toolkits', 'google']` or `pip install cx_freeze==6.1`

**Comment by marcelotduarte** [comment]
You are using replace_paths... Try to comment this line in setup...

**Comment by mx2048** [comment]
Yes, I was using `'replace_paths': [("*", "")]`. Without it, it works fine!

**Comment by marcelotduarte** [comment]
Later I'll take a look at this.

**Comment by marcelotduarte** [comment]
An updated development branch is available. Activate your replace_paths and try it out.

pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop

**Comment by mx2048** [comment]
Works great! Very much appreciated!
