### ISSUE TITLE
Issue with Pyglet compiling in cx_Freeze

### ISSUE THREAD

**Issue by TechPriestJon** [marcelotduarte/cx_Freeze#714]
Previously cx_freeze worked really well with Pyglet. However recently something has changed which prevents my project from compiling.

I get the error - TypeError: argument of type 'NoneType' is not iterable

This only occurs when I attempt to import Pyglet. Other libraries and code works fine, and even the most cut down Pyglet App refuses to compile so its explicitly an issue with the Pyglet package, somewhere.

Also if it matters I'm running the latest Python, 3.8.5

Note: Other code freeze libraries do work, such as PyInstaller, but I'm still curious what the issue is. I do prefer using cx_Freeze together with Pyglet but if I need to change libraries I may not have a choice. If a suggetion/fix can be offered it would be most welcome.

**Comment by marcelotduarte** [comment]
What a version of cx-freeze you're using?
The previous version of cx-freeze works well with pyglet or the previous version of pyglet works well?
Your system: Linux, mac, Windows?
Put the final traceback to me (final max 10 lines)

**Comment by TechPriestJon** [comment]
Latest version of cx_Freeze, 6.2. Pyglet is 1.5.7
Previous versions of both cx_Freeze and Pyglet, its been a year or 2 since I had a look at my codebase but it executes fine, even with later versions. 
System is Windows 10, latest patch.
Traceback - 
`  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 343, in _ImportModule
    module = self._InternalImportModule(name,

  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\finder.py", line 397, in _InternalImportModule
    spec = importlib.util.find_spec(name)

  File "C:\Program Files\Python38\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])

  File "C:\Program Files\Python38\lib\site-packages\pyglet\libs\darwin\__init__.py", line 36, in <module>
    from .cocoapy import *

  File "C:\Program Files\Python38\lib\site-packages\pyglet\libs\darwin\cocoapy\__init__.py", line 32, in <module>
    from .runtime import objc, send_message, send_super

  File "C:\Program Files\Python38\lib\site-packages\pyglet\libs\darwin\cocoapy\runtime.py", line 51, in <module>
    objc = cdll.LoadLibrary(util.find_library('objc'))

  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)

  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:

TypeError: argument of type 'NoneType' is not iterable`

**Comment by marcelotduarte** [comment]
The development version has this issue resolved.
If you have a C compiler, you can test:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git`

I tested pyglet with the fixed_resolution example.
In the next week, I'll release a new version.

**Comment by TechPriestJon** [comment]
Thank you, much appreciated. 

Tried the fix and got the following error from Vs Build Tools.

    LINK : fatal error LNK1181: cannot open input file 'cx_Logging.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

Its not a serious issue though and I can wait until the next release.

Thank you for looking into this,

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
