### ISSUE TITLE
Allow to change default library.zip name

### ISSUE THREAD

**Issue by CHUK-ANDREW** [marcelotduarte/cx_Freeze#731]
library.zip is a default and hard-coded name for Freezed dependencies. This works fine until we need to Freeze two and more python scripts into few binaries, which will be stored into one directory. In this case library.zip will be overwritten and only one binary will keep working. I suggest to change default library.zip name and use binary name (similar to older cx_Freeze versions).

[cx_Freeze-6.2.patch.txt](https://github.com/marcelotduarte/cx_Freeze/files/4996140/cx_Freeze-6.2.patch.txt)

**Comment by marcelotduarte** [comment]
But cx-freeze can generate more than one executable - For me is the best ;-)
In this sample you can see how to do:
https://github.com/marcelotduarte/cx_Freeze/blob/master/cx_Freeze/samples/matplotlib/setup.py

**Comment by CHUK-ANDREW** [comment]
Thank you for answer, but my case is a little bit different.
We have setup.py for each application/script. And distribution could be done in different way - some binaries added or removed.
Before we used Python 2.7 and cx_Freeze 4 - so we get one binary and one zip, which could be easily moved.

And one more - each script may have its own dependencies, which are not used in other one

**Comment by marcelotduarte** [comment]
Please read:
https://cx-freeze.readthedocs.io/en/latest/development/index.html

**Comment by CHUK-ANDREW** [comment]
Will prepare pull request for this

**Comment by marcelotduarte** [comment]
Maybe another approach can do what you want. If you use a setup like this:
https://github.com/marcelotduarte/cx_Freeze/blob/master/cx_Freeze/samples/matplotlib/setup_zip.py
The difference is:
'zip_include_packages': ["*"],
'zip_exclude_packages': [],

Or, use a different build dir for each executable, see in that example the option: 
'build_exe': build_exe_dir

I'm suggesting this, because this change can break others. For me, I use projects with 8 executables, and they share the library.zip, and this reduces the size of the final distribution by a factor of 6.

**Comment by CHUK-ANDREW** [comment]
I already use 'zip_include_packages': ["*"], 'zip_exclude_packages': [] - helps a lot, but unfortunately its not enough in my case. Also different subdirs wont work for me.
I have double check my solution and yes, you was right - it might broke generation more than one executable...

**Comment by enkore** [comment]
library.zip has to be known to the launcher/bootstrapper/base (see source/bases/common.c, CX_PATH_FORMAT), so you can only change it if you patch and recompile the base. It would of course be possible to extend the bases to support configuration without recompilation (the classic approach is just appending some configuration data to the binary).

**Comment by marcelotduarte** [comment]
[Documentation](https://cx-freeze--2379.org.readthedocs.build/en/2379/setup_script.html#cmdoption-arg-zip_filename)

You can test the patch in the latest development build (cx_Freeze 7.1.0.dev16):
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`
