### ISSUE TITLE
importlib.util.find_spec causes modules to be imported

### ISSUE THREAD

**Issue by cainesi** [marcelotduarte/cx_Freeze#734]
Calls to importlib.util.find_spec() (used in _InternalImportModule() from finder.py) cause the relevant modules to be imported.  That can have unexpected effects if a module runs code when imported that might not be appropriate to run at the time of freeze.  It looks like this issue was introduced with commit 7a146cbabf back in June, as part of dealing with namespace packages.

Note sure if there is any alternative to using importlib.util.find_spec() there?

**Comment by marcelotduarte** [comment]
It's not expected that the module will be imported.
In this example: https://docs.python.org/3.6/library/importlib.html?highlight=find_spec#checking-if-a-module-can-be-imported
Says: "If you need to find out if a module can be imported without actually doing the import, then you should use importlib.util.find_spec()."

**Comment by cainesi** [comment]
I guess maybe not the module itself, but the parent module (this can have the same result, if package __init__.py imports the module or does other stuff...).  The [documentation](https://docs.python.org/3.6/library/importlib.html?highlight=find_spec#importlib.util.find_spec) for find_spec() says:

```
If name is for a submodule (contains a dot), the parent module is automatically imported.
```

Here is a sample that illustrates the problem: #735

**Comment by marcelotduarte** [comment]
I'll rewrite _FindModule, and this namespace detection will be in it (I have something done). Maybe a reorganization of the call to be the last can avoid the imports. Later I'll use your sample to test it.
The actual way to find the other modules, using "imp.find_module", fails with some modules. And it should do an import of the module too.

Without import namespaces automatically, It's too difficult to freeze programs that use "google.cloud" and family. It's more than 100 packages that need the hooks and use of "namespace_packages" option. With this, this is reduced drastically.

**Comment by cainesi** [comment]
Thanks.

FYI, #735 was initially missing one file so that it did not actually illustrate the problem.  But I have fixed it now.  It throws an exception when you do the freeze, due to it running the code in the package.  (Of course, it would also throw exceptions if you tried to run the target script--but you could have a more complicated example where the code in the package would be fine at runtime but fail during the freeze...)

Is the problem that we are trying to solve that we want to find things that exist in namespace packages?   It looks like the parent package only gets imported in order to access its __path__ -- but it seems like the path should be determinable without actually importing, e.g., just look at the directory tree (I guess this doesn't work if encounter a program that uses a custom loading mechanism--but I'm not sure if cx_freeze handles that anyway) .  I confess that I do not know so much about the import mechanism, so these ideas may be completely stupid!

**Comment by FedeMiorelli** [comment]
+1 for this issue.
In my case, I get a RunTimeError raised when processing the traitsui package, which is not catched and stops the build.

**Comment by marcelotduarte** [comment]
@cainesi Can you test my patch #811?
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@loadmodule`

**Comment by cainesi** [comment]
Hi Marcel,

Sorry for the delay.  Just tested it, and it seems to be working fine now (both with the test case, and my actual project).  

Looks like it was a fairly big change.  I'll need to look at it when I have some more time to learn exactly how you got it working.  When I was thinking about it, it seemed like it was going to be a bit messy.

Thanks,
Ian

**Comment by marcelotduarte** [comment]
Yes, I got it to work, much better than before. And I believe it is well in tune. I solved not only this error that you noticed but several others that I had to deal with, with packages like six, matplotlib, and others from google namespace.
