### ISSUE TITLE
how cx_Freeze manages the conftest.py file of pytest module

### ISSUE THREAD

**Issue by Lois31** [marcelotduarte/cx_Freeze#747]
Hello,

Pytest offers the possibility of configuring argument parsing via the _conftests.py_ file.
However I couldn't find a way to configure cx_Freeze to take this file into account.
Do you have a working configuration example?

Thanks,

**Comment by Lois31** [comment]
Hello Team,
Do you have any ideas ?

**Comment by marcelotduarte** [comment]
Maybe the author of #617 @lexa

**Comment by lexa** [comment]
Unfortunately pytest does not include conftest neigther pytest.ini in its list of frozen packages, so you have to track them manually. For example:

```
resources += [Path("conftest.py").resolve()]
resources += [Path("pytest.ini").resolve()]
build_exe_options['include_files'] = resources

setup(...
        options = {"build_exe": build_exe_options},
)
```
