### ISSUE TITLE
Symlinked libraries are resolved to duplicate files in <lib> output

### ISSUE THREAD

**Issue by enkore** [marcelotduarte/cx_Freeze#750]
On Linux systems stuff like "libfoo.so -> libfoo.so.2 -> libfoo.so.2.0 -> libfoo.so.2.0.0" is quite common. When cx_Freeze encounters libraries like this it copies every instance of them as a separate file, which causes a blow-up of storage requirements.

**Comment by marcelotduarte** [comment]
[cx_Freeze 6.8.4](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8.4) has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.
