### ISSUE TITLE
How can I properly choose the resources that cx_Freeze.Freezer adds to the installer?

### ISSUE THREAD

**Issue by aborzin** [marcelotduarte/cx_Freeze#755]
Hi,

I have been using cx_Freeze to create a Windows MSI installer and now I need to create and maintain different installer flavors (per customer). In fact, all I need is to use different set of resources that should be included in the installer.
My project structure looks like this (simplified):

root
|- my_project
|        |- resources  
|        |        |- img1.jpeg
|        |        |- img2.jpeg
|        |-__init__.py
|        |-main.py
|-setup.py 

So my goal is to create one flavor of the installer with img1.jpeg only and another one with img2.jpeg only.

My executable definition is as following:

Executable(script=os.path.join(ROOT_FOLDER, 'my_project', 'main.py'),
               base=base,
               targetName='my_project',
               shortcutName='my_project',,
               shortcutDir='DesktopFolder',
               icon=ICON_FILE)

The module "my_project" is properly discovered by the Finder and at some point, the Freezer calls the Freezer._WriteModules method to copy the entire file structure to the build directory (while excluding the Python types):
`      

       ignorePatterns = shutil.ignore_patterns("*.py", "*.pyc", "*.pyo",
                "__pycache__")
       for module in modules:
            # determine if the module should be written to the file system;
            # a number of packages make the assumption that files that they
            # require will be found in a location relative to where
            # they are located on disk; these packages will fail with strange
            # errors when they are written to a zip file instead
            includeInFileSystem = module.WillBeStoredInFileSystem()

            # if the module refers to a package, check to see if this package
            # should be included in the zip file or should be written to the
            # file system; if the package should be written to the file system,
            # any non-Python files are copied at this point if the target
            # directory does not already exist
            if module.path is not None and includeInFileSystem:
                parts = module.name.split(".")
                targetPackageDir = os.path.join(targetDir, *parts)
                sourcePackageDir = os.path.dirname(module.file)
                if not os.path.exists(targetPackageDir):
                    print("Copying data from package", module.name + "...")
                    shutil.copytree(sourcePackageDir, targetPackageDir,
                            ignore = ignorePatterns)
           ...
`
As a result, all the resources (entire resources folder in my case) are copied. If there was an option to extend the ignored patterns, I could exclude all *.jpeg files and add them with the includeFiles option.

There is an option to move the resources to the root folder and copy only relevant files, but that seem to be less convenient. Another solution I tried was to patch the Freezer._WriteModules method with my own version that ignores the *.jpeg pattern, but that cannot be a long term solution.

So, is there a more convenient and recommended mode of work for projects that need to choose which resource files to include in the executables?

Thanks.

**Comment by DraXus** [comment]
I have the same issue. Currently I'm moving resources manually, which is not very practical. Are there any plans to support this?

**Comment by marcelotduarte** [comment]
Observe this comment:
```
# any non-Python files are copied at this point if the target
# directory does not already exist
```
Then, you'll need more work but can skip this copy. If you explicitly include the modules, the base directory of the project is created and not the package. Do you have more modules in the my_project structure? If you have file1.py the you can add a includes = ['my_project.file1']
If you have only a init file, you can move the source on it to file1.
And use include_files to include the resource files.

PS1: This is non tested.

PS2: I accept a PR with an option to https://cx-freeze.readthedocs.io/en/latest/distutils.html#build-exe

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
Can I close this issue?

**Comment by DraXus** [comment]
Sorry, I haven't had the chance to get back to it. From my side you can feel free to close it, I'll reopen it if needed. Thanks a lot for the answer!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5.3 has just been released.
