### ISSUE TITLE
python setup.py build: ValueError: PyCapsule_GetPointer called with incorrect name

### ISSUE THREAD

**Issue by tobylaifun** [marcelotduarte/cx_Freeze#757]
_qtcore = __import__(name, fromlist=['QtCore']).QtCore
ValueError: PyCapsule_GetPointer called with incorrect name
the file I want to pack uses PyQt5
**cx_freeze version:6.2**

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Can you check if this has been resolved?

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
If you had issues please re-open.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
