### ISSUE TITLE
Setup attributes do not appear in the properties of the generated EXE

### ISSUE THREAD

**Issue by alaa137** [marcelotduarte/cx_Freeze#758]
I have the following setup parameters:

```
setup(
    name="myfile",
    options=options,
    version="1.2.3.4",
    description='My file',
    executables=executables
)
```

And I expect "version" and "description" to appear in the details of the generated EXE file properties:

![image](https://user-images.githubusercontent.com/11571579/93197226-0fa4e600-f754-11ea-9970-68b749d11072.png)

But as you can see they are empty. If they do not appear here, then what is their purpose? And how do I get them to appear here?

**cx_Freeze version 6.0**

**Comment by alaa137** [comment]
Found the problem... Just install `pywin32`

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
