### ISSUE TITLE
return split(p)[0] File "C:\Users\Ftech-PC\AppData\Local\Programs\Python\Python36\lib\ntpath.py", line 205, in split p = os.fspath(p) TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by faizi1122** [marcelotduarte/cx_Freeze#759]
i am getting this error tried so hard to get rid of it.But all my attempts went unsuccessful

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
