### ISSUE TITLE
cx_freeze Does not add related packages completely

### ISSUE THREAD

**Issue by m-aminiz** [marcelotduarte/cx_Freeze#762]
Hi. thank you for your great library. I write a code that uses pylibjpeg. the code works pretty well. I created an executable file of my code with cx_freeze but in the generated .exe program, pylibjpeg doesn't work and it gives me GDCM handler error. I think the problem happened because of pylibjpeg-libjpeg. pylibjpeg-libjpeg is a plugin that pylibjpeg  works with. if I add pylibjpeg-libjpeg to packages list and run the setup.py it gives me error(No module named 'pylibjpeg-libjpeg'). cx_freeze did not recognize pylibjpeg-libjpeg and did not add it to the .exe lib folder. how can I solve this problem? I should add pylibjpeg-libjpeg plugin because  pylibjpeg ( main library) need it

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Can you check if this has been resolved?

**Comment by marcelotduarte** [comment]
I did a test
#test.py
```
from libjpeg import decode

with open('filename.jpg', 'rb') as f:
    # Returns a numpy array
    arr = decode(f.read())
print("ok")
```

#install
pip install pylibjpeg-libjpeg
pip install cx-freeze
cxfreeze test.py
dist/test

It runs

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
If you had issues please re-open.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
