### ISSUE TITLE
[Numpy] TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by raylemon** [marcelotduarte/cx_Freeze#763]
Hello, 
cx_freeze (6.2)  throw this error when I want to freeze any application with PySide2 and numpy. If I remove numpy from project, the problem is solved.

cx_freeze 6.1 doesn’t have this problem.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
