### ISSUE TITLE
PySide2 & cx_Freeze

### ISSUE THREAD

**Issue by Lois31** [marcelotduarte/cx_Freeze#769]
Hello Team,

Why cx_Freeze does not properly package PySide2 module by importing the following folders correctly:
- lib/python3.8/site-packages/PySide2/Qt/plugins/platforms
- lib/python3.8/site-packages/PySide2/Qt/plugins/imageformats

Moreover I am forced to modify the _RPATH_ of each of these libraries under Linux as follows: _${ORIGIN}:${ORIGIN}/../../lib_

Platform configuration:

- Linux RHEL 7 & Windows 10
- Python V3.8.3
- cx_Freeze 6.1

I fixed the problem by manually importing the missing folders by adding the following lines in my setup.py file:

```
import PySide2
pyside2_plugins = os.path.dirname(PySide2.__file__)
if sys.platform != 'win32': # On windows plf, there is no 'Qt' directory
    pyside2_plugins` = os.path.join(pyside2_plugins, 'Qt')
pyside2_plugins      = os.path.join(pyside2_plugins, 'plugins')
pyside2_platforms    = os.path.join(pyside2_plugins, 'platforms')
pyside2_imageformats = os.path.join(pyside2_plugins, 'imageformats')

include_files = [pyside2_platforms, pyside2_imageformats]
```

**Comment by marcelotduarte** [comment]
cx_Freeze 6.3 has just been released.
Can you check if this has been resolved?

**Comment by Lois31** [comment]
The problem seems partly resolved but with impacts on the installation directory tree.

First, we are still forced to manually add the `platforms` and `imageformats` folders of `PySide2` with the `include_files` option.
Without it we get the following error:
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Abort(coredump)
```

Secondly, under Linux, we had to patch the RPATH of the libraries of the `platforms` and `imageformats` folders manually included with the following value: `$ORIGIN: ../../$ORIGIN` in order to correct the problems loading these libraries.
This problem seems to be solved by the fact that cx_Freeze 6.3 copies some libraries to the `lib` folder of the parent folder of the installation folder.
To make it more explicit, below are the tree structure differences between the two versions of cx_Freeze:

 
**cx_Freeze 6.1**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**cx_Freeze 6.3**
install_dir/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lib/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;my_exe &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;install_dir/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;imageformats/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;my_exe
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lib/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;imageformats/  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;platforms/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lib/
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;platforms/

However I find this solution not elegant: having two `lib` folders including one outside the instalation folder...

**Comment by ferdnyc** [comment]
@Lois31 

By any chance, are you freezing the RHEL-packaged Qt libraries?

The plugins packaged by RedHat, like most Linux distributions' official packages, are built without `RPATH`s, making them essentially unrelocatable. They're packaged with the assumption that they will only ever be used from their installed system locations.

In both the Qt bundled into the PyQt5 wheels by Riverbank Computing, and the official Qt5 downloadable installation (which I installed in `$HOME/Qt` on my own Fedora 32 system), the `RPATH` is set exactly as you say:

```sh
$ chrpath -l lib/python3.8/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.so 
lib/python3.8/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.so: 
RUNPATH=$ORIGIN/../../lib

$ chrpath -l ~/Qt/5.15.1/gcc_64/plugins/imageformats/libqtiff.so 
/home/ferd/Qt/5.15.1/gcc_64/plugins/imageformats/libqtiff.so: 
RUNPATH=$ORIGIN/../../lib

$ chrpath -l /usr/lib64/qt5/plugins/imageformats/libqtiff.so 
/usr/lib64/qt5/plugins/imageformats/libqtiff.so: no rpath or runpath tag found.
```

I'm not sure how much `cx_Freeze` can realistically do to mitigate the distros' intentional handicapping of the Qt component libraries.

**Comment by Lois31** [comment]
@ferdnyc, you had a good intuition. I did not install the Qt packages from RedHat but I installed Qt from sources. So now I understand why cx_freeze is not correctly modifying the RPATH in this case.
It remains for cx_freeze to correctly import the following directories: _platforms_ and _imageformats_

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
