### ISSUE TITLE
_sqlite3.cpython-38-x86_64-linux-gnu.so: undefined symbol: sqlite3_errstr

### ISSUE THREAD

**Issue by gabiapple** [marcelotduarte/cx_Freeze#771]
I am getting this error when when executing the binary file of my program.

Cx Freeze version 6.3

**Comment by marcelotduarte** [comment]
With the sample at https://github.com/marcelotduarte/cx_Freeze/tree/master/cx_Freeze/samples/sqlite 
Do you have the same error?

**Comment by gabiapple** [comment]
I don't. The sample works fine.
Do you have any hints of what may be going wrong in my setup?

I've noticed that I'm not using the same options from sample:
options={"build_exe": {"excludes": ["tkinter"],
                             "replace_paths": [("*", "")],
                             "zip_include_packages": ["*"],
                             "zip_exclude_packages": []}}

Are they required?

**Comment by marcelotduarte** [comment]
They aren't required. The excludes is interesting to reduce the generated executable files.
But you cant test your program with the zip* options to see the result....
Your program runs without errors when called on command line?
You can put the traceback?

**Comment by gabiapple** [comment]
I've tried with zip* options, but I got the same error.
If I call my programm on command line I don't get any errors (e.g python service.py)

```
Traceback (most recent call last):
File "/home/gabriela/pkgs/latest-anaconda3/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
    module.run()
  File "/home/gabriela/pkgs/latest-anaconda3/lib/python3.8/site-packages/cx_Freeze/initscripts/Console.py", line 33, in run
    exec(code,  m.__dict__)
  File "service.py", line 4, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/gabriela/pkgs/latest-anaconda3/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "<frozen zipimport>", line 259, in load_module
  File "/home/gabriela/pkgs/latest-anaconda3/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /home/gabriela/dev-gabriela/lib/_sqlite3.cpython-38-x86_64-linux-gnu.so: undefined symbol: sqlite3_errstr
```

**Comment by marcelotduarte** [comment]
Probably is your version of anacond that is broken.
You can test with python native of your SO (Ubuntu, fedora?) 
What has at File "service.py", line 4? import sqlite3?

**Comment by gabiapple** [comment]
File "service.py" line 4 has import sqlite3

I was able to build my application and execute the binary successfully in another machine, which is RHEL 7.4 (using same anaconda environment).
However, it's not working in my RHEL 6.5 machine.

**Comment by marcelotduarte** [comment]
The same anaconda version?

Internally the _sqlite3.so binds to sqlite3.so (names abbreviated) and probably the last wasn't copied. Check the files in your dist/build to see if have differences.

**Comment by gabiapple** [comment]
I couldn't find any difference in my dist/build directories. However, it seems there is something missing on binary setup.
I'm saying that because this sqlite3 error doesn't happen if I execute `/home/gabriela/pkgs/latest-anaconda3/bin/python -c 'import sqlite3'`
If I add anaconda library path to LD_LIBRARY_PATH and then execute the binary, it works on RHEL 6.5.

**Comment by gabiapple** [comment]
Apparently, some required libraries are not being copy to build/lib folder. They are being copy to upper level directories following relative paths from source. Then when the program is executed it gets the libraries from the local system which are compiled for a different version for sqlite3, SSL, etc. Is there a way to force the copy to lib folder?

**Comment by marcelotduarte** [comment]
Good catch. Apparently anaconda has some history of alternating the use of static link and dynamic link. Maybe this is the problem. Maybe not. 
A way to force is to do a hook. For sqlite3 we have a hook only for windows.
https://github.com/marcelotduarte/cx_Freeze/blob/master/cx_Freeze/hooks.py#L956
You can make a monkey patch to test it and maybe better you can fork the project and send a PR.

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
If you had issues please re-open.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
