### ISSUE TITLE
No module named 'vtkmodules'. 

### ISSUE THREAD

**Issue by l1va** [marcelotduarte/cx_Freeze#772]
Good day! 
I am trying to build exe. I am using python3.8, pyQt, pyVTK. And build is successful but when I run, I get `No module named 'vtkmodules'`:

![image](https://user-images.githubusercontent.com/1406586/97004277-7ed8db80-1545-11eb-9cb0-1f2f22a979f7.png)

The 6.3 version of cx_Freeze I have checked too -  the same.
My `setup.py` file :
![image](https://user-images.githubusercontent.com/1406586/97004730-26560e00-1546-11eb-85b2-c81d82c1c4a8.png)

ps. I found the solution: I added `packages=['vtkmodules']` to buildOptions, but is it correct? (size of the directory increased by 150 Mb)

**Comment by marcelotduarte** [comment]
Hi! Some modules are dynamic loaded and aren't detectable. When the cx-freeze hasn't a hook, the solution is to use the options 'includes' and/or 'packages'. Note that options like 'excludes', 'bin_excludes' can be used to fine tune and exclude some unecessary module and reduce the size.
All options in https://cx-freeze.readthedocs.io/en/latest/distutils.html#build-exe can be used as build options.

**Comment by l1va** [comment]
Marcelo, thank you for the answer! 
As I understood it is not a bug and I need to close the issue. 
Do you know what is needed or what I can exclude? There are *.lib, *.dll, *.exp, *.py files.
( now the lib folder is 340 Mb  -  160Mb is pyQT5 and 160 - vtk )

**Comment by marcelotduarte** [comment]
Common use to reduce is "excludes": ["tkinter"]
Using zip_include_packages option and zip_exclude_packages option can reduce too, as it excludes data. For pyside2 and pyqt2 you can check some closed issues e some open issue about this.
