### ISSUE TITLE
Build package for imported module not having constant content

### ISSUE THREAD

**Issue by kalindkaria** [marcelotduarte/cx_Freeze#774]
cx_Freeze is indeed a better tool than Pyinstaller I feel as its easier and faster to use.
I maybe asking a silly question but I'm stuck on this and can't find answer on any online forums.

My requirement are as follows:
- a `module1.py` file for which Executable is to be created
- the `module1.py` imports another `module2.py` as: `import module2`
- the `module2.py` content will not be constant, based on the content, the output of running the bundled package will vary

I have added the `module2.py` in the **include_files** option of command **build_exe**. This copies the `module2.py` file to the directory where the built package resides.

Now, if I make any change to the functions in `module2.py` _(lets say initially the code is perfectly fine for an application and I purposely make a syntax error)_ and then run the built package of `module1.py` as it imports `module2.py`, I expect the output of package to throw error. But instead it runs well without any error and provides the correct output of the application. This means that the package bundled the `module2.py` at the time when it was built, and I guess it also generates the compile `module2.pyc` in library.zip.
Note: Here, I am making the changes to `module2.py` file which got copied to the directory where package resides due to the addition of this file in **include_files** option.

Is there anything I have missed from the docs of cx_Freeze?
Kindly suggest a solution for this requirement.

Thanks in advance.

**Comment by marcelotduarte** [comment]
If I understood.. you should use excludes=["module2"] to exclude the module from the freezing process, and include_files to include it like a data file.

**Comment by kalindkaria** [comment]
Thank you for quick response.

I tried that option, but with the **excludes=['module2']** option the bundled packaged ignores the `import module2` statement and throws `ImportError` even if the `module2.py` file is present in the same directory as the package.

I'll be really thankful if I get the way out for this!

**Comment by marcelotduarte** [comment]
Use a dynamic import then... using `__import__` or imporlib.import_module (https://docs.python.org/3/library/importlib.html)

**Comment by kalindkaria** [comment]
Yes, I used the dynamic import with `__import__('module2')` and also tried now with `importlib.import_module('module2')` but since these statements are not tracked by cx_Freeze (I read about this over here: https://pypubsub.readthedocs.io/en/v3.3.0/development/py2exe.html), it throws same ImportError when running the bundled package.

It didn't work with dynamic import even.

**Comment by kalindkaria** [comment]
For supporting my query, following is the content of `setup.py`:

```python3
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need
# fine tuning.
build_options = {'packages': [], 'excludes': [], 'include_files': ['images/', 'module2.py']}

base = 'Console'

executables = [
    Executable('module1.py', base=base)
]

setup(name='Module1 App',
      version = '0.0.1',
      description = 'Testing of Module1 App',
      options = {'build_exe': build_options},
      executables = executables)
```

**Comment by marcelotduarte** [comment]
It should work. The ImportError is because the module is not found. Where in the dist/build the module2 is placed?

**Comment by kalindkaria** [comment]
The 'module2.py' is present in same directory (`build`) as 'module1' package.
But am I right in considering that cx_Freeze ignores the dynamic import statements (such as `module2 = __import__('module2')` or `module2 = importlib.import_module('module2')`) present in the 'module1.py' file?

**Comment by marcelotduarte** [comment]
This work.
`# module1.py`
```
import sys, os
if hasattr(sys, "frozen"):
	print("executable", sys.executable)
	sys.path.append(os.path.dirname(sys.executable))
module2 = __import__("module2")
print("module1 ok")

```
`# module2.py`
```
print("module2 ok")

```
`# Use your setup.py`

**Comment by marcelotduarte** [comment]
my results
```
(issue774) marcelo@teste6:~/testes/issue774$ build/exe.linux-x86_64-3.8/module1
executable /home/marcelo/testes/issue774/build/exe.linux-x86_64-3.8/module1
module2 ok
module1 ok
(issue774) marcelo@teste6:~/testes/issue774$ build/exe.linux-x86_64-3.8/module1
executable /home/marcelo/testes/issue774/build/exe.linux-x86_64-3.8/module1
module2 ok modi
module1 ok
(issue774) marcelo@teste6:~/testes/issue774$ build/exe.linux-x86_64-3.8/module1
executable /home/marcelo/testes/issue774/build/exe.linux-x86_64-3.8/module1
module2 changed by user
module1 ok
(issue774) marcelo@teste6:~/D/testes/issue774$ 
```

**Comment by kalindkaria** [comment]
Thanks alot @marcelotduarte for your answer! It worked like a charm. 😃 

A last question I have, can I bundle my package into single standalone file, instead of the `lib` folder having a `library.zip` consisting of compiled `.pyc` file of '`module2.py` that is imported in `module1` package?
I'm asking this as there are available tools for decompiling the `.pyc` files so one may find the source code of my package and that's a risk!

**Comment by marcelotduarte** [comment]
The short answer: No.
This method (one file) should not protect your source code either.
What I've used is cryptography fernet in data files.
For my source python files, I use cython on some python files, but this adds some work (the packages are not detected - I use the packages and includes options to specify them), and a coleteral effect: speed up ;-)

**Comment by kalindkaria** [comment]
Thank you for the reply. I understand and I must say that I have learnt from you.
I will close this issue. Thanks 👍🏻
