### ISSUE TITLE
bdist_msi

### ISSUE THREAD

**Issue by CraftedCat** [marcelotduarte/cx_Freeze#779]
cx_Freeze 6.3

After run:
python setup.py bdist_msi -> folder \build\bdist.win-amd64 is empty.
In log:
...
copying...
removing 'build\bdist.win-amd64\msi' (and everything under it)

what's wrong?

**Comment by cainesi** [comment]
Would you be able to share the setup.py file you're using?  Hard to tell what's going on without that.

**Comment by CraftedCat** [comment]
@cainesi
```

from cx_Freeze import setup, Executable

executables = [Executable('main.py',
                          targetName='App.exe',
                          # base='Win32GUI',
                          base='Console',
                          icon='log.ico')]


includes = ['threading', 'argparse', 'colorama', 'platform', 're', 'datetime', 'requests', 'logging', 'bs4',
            'secrets', 'time', 'os', 'configparser', 'random', 'queue']

include_files = ['bot_funcs.py',
                 'classes.py',
                 'functions.py',
                 'default.ini',
                 'RUN_EXE.bat',
                 'bins'
                 ]

zip_include_packages = ['aiohttp', 'asyncio', 'async_timeout', 'attr', 'bs4', 'certifi',
                        'chardet', 'collections', 'colorama', 'concurrent', 'ctypes', 'email',
                        'encodings', 'html', 'http', 'idna', 'importlib', 'json', 'logging', 'multidict',
                        'multiprocessing', 'pydoc_data', 'python_rucaptcha', 'requests', 'soupsieve', 'unittest',
                        'urllib', 'urllib3', 'xml', 'xmlrpc', 'yarl']



options = {
    'build_exe': {
        'include_msvcr': True,
        'includes': includes,
        'zip_include_packages': zip_include_packages,
        'build_exe': 'build_windows',
        'include_files': include_files,
        },
}

setup(name=' main',
      version='1.0.0',
      description='My app',
      executables=executables,
      options=options)

```

**Comment by cainesi** [comment]
Replace the "options" dictionary in your code with this and it should work:

```
options = {
    'build': { 'build_exe': "build_windows"},
    'build_exe': {
        'include_msvcr': True,
        'includes': includes,
        'zip_include_packages': zip_include_packages,
        'include_files': include_files,
        },
}
```

We might want to clarify the documentation on those options...

I suggested just getting rid of the build_exe option for the build_exe command in issue #782.

**Comment by CraftedCat** [comment]
@cainesi  same, no errors in log, but folder \build\bdist.win-amd64 still empty

**Comment by cainesi** [comment]
To clarify---the directory '\build\bdist.win-amd64' should be empty at the end of the process, and the subdirectory 'build\bdist.win-amd64\msi' should be deleted (it's created temporarily as part of making the MSI file). The subdirectory where you should find the MSI file at the end (by default) is 'dist'.  However, with your original setup.py, I think the process would have failed even before the `removing 'build\bdist.win-amd64\msi'` line (unless you had previously run setup with different options to have created the build directory in the expected spot).

**Comment by marcelotduarte** [comment]
@CraftedCat Can you let me know if this has been resolved?
I take this opportunity to inform you that cx_Freeze 6.4.1 is available.

**Comment by marcelotduarte** [comment]
Closing due to lack of response.
If you had issues please re-open.

**Comment by LoneWanderer-GH** [comment]
I've got a similar issue with` cx_Freeze  6.14.9`, `python 3.9`, `Windows 10 x64`

Setup.py
```python
win_executable_options = {
    "build_exe":  r"C:\delivery\sub\folder",
    "silent_level": 0,
}
bdist_msi_options = {
    "summary_data": {
        "author": "me !",
        "comments": "foo",
        "keywords": "These Are Some Keywords",
    },
}
my_super_app_main_path = Path(..........) # somewhere
my_executable = Executable(script=my_super_app_main_path.as_posix(),
                            base="Console", 
                            base=None, 
                            target_name="MySuperExe.exe",
                            copyright="mine !"
                            )
setup(
    name="MyApp",
    version="0.0.0",
    description="",
    author="me",
    options={"build_exe": win_executable_options,
                   "bdist_msi": bdist_msi_options},
    executables=[my_executable ], )
```

The `C:\delivery\sub\folder` contains `MySuperExe.exe` and everything needed.
But the MSI file is built into a `.\dist` folder next to my `Setup.py` file.

I naively expected the MSI file to be built within the `"build_exe":  r"C:\delivery\sub\folder",` folder.

---
Possible implementation would be to have this behaviour:


```
|- C:\delivery\sub\folder from the build_exe options
|--
|--- exe
        |-- MySuperExe.exe
        |--lib
        |--etc.
|--- msi_installer
        |-- MySuperExe.v0.0.0.msi
```

**Comment by cainesi** [comment]
You can specify where the MSI file is finally saved with the "dist_dir" option to "bdist_msi" command.  Something like the following:

```
setup(
  executables = [exe],
  options = {
    "bdist_msi":{"dist_dir": PATH_TO_DIRECTORY_FOR_MSI},
  }
)
```
