### ISSUE TITLE
Setting "build_exe" option on "build_exe" command breaks bdist_mac

### ISSUE THREAD

**Issue by cainesi** [marcelotduarte/cx_Freeze#782]
It also appears to break other commands.  The issue seems to be that bdist_mac (and similar commands), do not check what directory was set on the "build_exe" command but instead look at the options on the "build" command.  See, e.g., the finalize_options() of the install_exe command.

Could we just get rid of the "build_exe" options on the "build_exe" command?  The "build_exe" option on the "build" command seems to have the same result, but not be broken.

**Comment by marcelotduarte** [comment]
> Could we just get rid of the "build_exe" options on the "build_exe" command?

I believe this is an old option and would cause a breach of compatibility.
I didn't quite understand the problem, but a solution will have to be found in order to get around the problem, either by propagating the option or otherwise, maintaining compatibility.

**Comment by cainesi** [comment]
> I believe this is an old option and would cause a breach of compatibility.
> 
> I didn't quite understand the problem, but a solution will have to be found in order to get around the problem, either by propagating the option or otherwise, maintaining compatibility.

Fair enough. I suppose I might be missing something about what the "build_exe" option on the build_exe command is supposed to do, and when it is intended to be used. It just seems that if I set that option, and run the bdist_msi command, it fails...

**Comment by marcelotduarte** [comment]
I tested PR #1480 using 'build' with 'bdist_msi'. I believe it will work with 'bdist_mac' the same way.
