### ISSUE TITLE
Python 3.5 EOL and PyQt4 EOL

### ISSUE THREAD

**Issue by marcelotduarte** [marcelotduarte/cx_Freeze#792]
I am intending to end support for python 3.5. But if someone still needs it I can keep it for one or two more versions. But, for that, we will have to adapt the type annotations of the darwintools module as it supports py36 and up.

The PR #791 remove support for PyQt4 and PySide, with the argument[1]:
Qt 4 reached end-of-life on 2015-12-19. Its Python bindings are also EOL: PyQt4 since 2018-08-31 and PySide since 2015-10-14.

[1] https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html

@cainesi @klensy @mikedarcy @robes @sekrause

**Comment by klensy** [comment]
I think, need to check main linux distros for python version supported first.

**Comment by marcelotduarte** [comment]
"Python 3.5 is no longer supported.  There will be no more bug fixes or security patches for the 3.5 series, and Python 3.5.10 is the last release.  The Python core development community recommends that all remaining Python 3.5 users should upgrade to the latest version."[1]

[1] https://pythoninsider.blogspot.com/2020/10/python-35-is-no-longer-supported.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+PythonInsider+%28Python+Insider%29

**Comment by cainesi** [comment]
No objections from me.

Incidentally, I noticed in the python documentation that as of Python 3.9 the bdist_msi command is being depreciated (https://docs.python.org/3/distutils/apiref.html#module-distutils.command.bdist_msi). Presumably we want to keep that command in cx_freeze, but it will take a bit of extra work once the command disappears from distutils.

**Comment by marcelotduarte** [comment]
> Python 3.9 the bdist_msi command is being depreciated

I see that. Maybe in a year or two, 3.10, 3.11 can remove it...

**Comment by cainesi** [comment]
Yeah, not an immediate problem. When the time comes, I think it should be possible to basically just lift the final version of the distutils code and incorporate ￼it into cx_freeze so the cx_freeze can continue as before.

**Comment by sekrause** [comment]
I think it's a good rule of thumb to only support those Python versions which are still supported upstream, so it's fine to drop support for Python 3.5.

People who need older Python versions can still use older cx_Freeze after all.

**Comment by marcelotduarte** [comment]
Thanks for the comments.

cx_Freeze 6.4 has just been released.
