### ISSUE TITLE
Win64 service executable missing in distribution

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#8]
Originally reported by: **Anonymous**

----------------------------------------

In the Windows 64bit distribution the service base executable is missing.
In Windows 32bit it is included.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/8

**Comment by anthony-tuininga** [comment]
*Original comment by* **Alexandre JABORSKA (Bitbucket: [ajaborska](https://bitbucket.org/ajaborska), GitHub: Unknown)**:

----------------------------------------

The Win32Service.exe is also missing in the Python 3.2 distribution.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Note that the service executable is currently only compiled for Python 2 - someone who needs it will have to do the work to make it work on Python 3, though hopefully that won't be too difficult.

**Comment by fabioparodi** [comment]
I would like to run a python script as a service under windows 64 bit.

The workaround is to use nssm, which is working; still, I would like an integrated solution, like win32serviceutil.ServiceFramework, but it does not work with cx_Freeze.

I have seen that the cx_Freeze bases for python3.7 only include Console.exe and Win32GUI.exe, and in my understanding there should be some Win32Service.exe or (better) Win64Service.exe.

I am willing to contribute some engineering work to get Win64Service.exe working with python 3.7 64 bit under windows 10; as Anthony pointed out, hopefully that won't be very difficult but I do not know where to start.

**Comment by marcelotduarte** [comment]
Assuming this has been resolved.
