### ISSUE TITLE
cx_Freeze does not correctly copy matplotlib module

### ISSUE THREAD

**Issue by Lois31** [marcelotduarte/cx_Freeze#805]
Hello Team,

_cx_Freeze_ does not copy all the files necessary for a good functioning of the _matplotlib_ module.
Below are the versions of the tools used:

- Windows 10
- Python 3.8.3
- cx_Freeze 6.3
- matplotlib 3.2.2
- pandas==1.0.4

In order to get matplotlib to work correctly on Windows, I need to add the following lines to my setup.py file:
```
if sys.platform == 'win32':
    import matplotlib
    site_package_path           = os.path.dirname(os.path.dirname(matplotlib.__file__))
    matplotlib_backends         = os.path.join('matplotlib', 'backends')
    matplotlib_backend_tkagg    = os.path.join(matplotlib_backends, 'backend_tkagg.py')
    matplotlib_backend_tk       = os.path.join(matplotlib_backends, '_backend_tk.py')
    matplotlib_backend_managers = os.path.join('matplotlib', 'backend_managers.py')
    includefiles.extend([(os.path.join(site_package_path, matplotlib_backend_tkagg),    os.path.join('lib', matplotlib_backend_tkagg)),
                         (os.path.join(site_package_path, matplotlib_backend_tk),       os.path.join('lib', matplotlib_backend_tk)),
                         (os.path.join(site_package_path, matplotlib_backend_managers), os.path.join('lib', matplotlib_backend_managers))])
```

**Comment by marcelotduarte** [comment]
Hi, use packages=["matplotlib"] instead.

**Comment by marcelotduarte** [comment]
@Lois31 
PR #807 should fix this issue.
cx_Freeze 6.4.1 has just been released.
Can you check if this has been resolved?

**Comment by Lois31** [comment]
> Hi, use packages=["matplotlib"] instead.

This workaround works with cx_Freeze 6.3, however, you have to add the _tkinter_ module in _packages_:
```
packages=["matplotlib", "tkinter"]
```

**Comment by Lois31** [comment]
> @Lois31
> PR #807 should fix this issue.
> cx_Freeze 6.4.1 has just been released.
> Can you check if this has been resolved?

_matplotlib_ module is correctly copied with cx_Freeze 6.4.1 version. 
However, be careful not to exclude the _tkinter_ module
