### ISSUE TITLE
Python 3.4 venv importlib AttributeError

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#81]
Originally reported by: **Anonymous**

----------------------------------------

The build works find, but there is an issue with importlib\_bootstrap.py when running the application.

 import inspect
File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2214, in _find_and_load
File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2203, in _find_and_load_unlocked
File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1191, in _load_unlocked
File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 1161, in _load_backward_compatible
AttributeError: 'module' object has no attribute '_fix_up_module'

Python 3.4.1
cx_Freeze 4.3.3
I am also using a venv virtual environment.

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/81

**Comment by anthony-tuininga** [comment]
*Original comment by* **TWAC (Bitbucket: [TWAC](https://bitbucket.org/TWAC), GitHub: [TWAC](https://github.com/TWAC))**:

----------------------------------------

_fix_up_module was added with 3.4.1.
http://hg.python.org/cpython/rev/7d20e30bd540

I think the PyPI packages need to be recompiled for it to work.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

This is a problem for me too

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

i CAN confirm that recompiling it fixes the problem.

**Comment by anthony-tuininga** [comment]
*Original comment by* **zaazbb (Bitbucket: [zaazbb](https://bitbucket.org/zaazbb), GitHub: [zaazbb](https://github.com/zaazbb))**:

----------------------------------------

i have this problem too. can you upload a recompiled packetage? I have no vc installed.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

 get mingw32(unless you're compiling for 64bit, then you need vc, and a few other hacks to get it working)
or just install visual studio yourself.. it doesn't take long. get 2010 express.

**Comment by anthony-tuininga** [comment]
*Original comment by* **zaazbb (Bitbucket: [zaazbb](https://bitbucket.org/zaazbb), GitHub: [zaazbb](https://github.com/zaazbb))**:

----------------------------------------

i'll try it later, thank you.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

Christoph Gohlke's site apparently has a recompiled version which fixes this issue:

http://www.lfd.uci.edu/~gohlke/pythonlibs/#cx_freeze

(From discussion on [this thread](https://groups.google.com/forum/#!msg/comp.lang.python/Ubagx7NDtJE/_47ZP2Uj-BUJ))

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Official binary for pypi please, waiting 4 months more for the next release seems like a bad idea

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Get the installer, or build it from source yourself. It's not that hard.

**Comment by anthony-tuininga** [comment]
*Original comment by* **wiz21 NA (Bitbucket: [wiz21](https://bitbucket.org/wiz21), GitHub: [wiz21](https://github.com/wiz21))**:

----------------------------------------

Just for the sake of completeness, this bug seems triggered by any non built-in import. For example, a python script as simple as :

    import urllib.request

will trigger the bug. I'm using python 3.4.1 and cx_freeze 4.3.3 on windows.

**Comment by anthony-tuininga** [comment]
*Original comment by* **wiz21 NA (Bitbucket: [wiz21](https://bitbucket.org/wiz21), GitHub: [wiz21](https://github.com/wiz21))**:

----------------------------------------

Python 3.4.1 and Christoph Gohlke's build (as advertised above) work fine here. Fixes my problem !

**Comment by anthony-tuininga** [comment]
*Original comment by* **Mark Grandi (Bitbucket: [mgrandi](https://bitbucket.org/mgrandi), GitHub: [mgrandi](https://github.com/mgrandi))**:

----------------------------------------

holy god, this wasted so much of my time today because whoever is the maintainer at pypi hasn't updated the build. 

So for anyone who wants a 64 bit python3.4 build of cx_freeze, here is a wheel for you: http://mgrandi.no-ip.org:81/pypi/cx_Freeze-4.3.3-cp34-none-win_amd64.whl

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

That isnt needed. Recompiling fixes the issue, and if you can't do that, the previous comment shows that you can install the recompiled version from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#cx_freeze)

**Comment by anthony-tuininga** [comment]
*Original comment by* **Mark Grandi (Bitbucket: [mgrandi](https://bitbucket.org/mgrandi), GitHub: [mgrandi](https://github.com/mgrandi))**:

----------------------------------------

Yes, but 1: you need visual studio 2010 to recompile it, which not everyone has, and if you want 64bit builds, you need the full versions, not just express cause Microsoft is terrible. and 2: you can't use the already compiled one in a virtualenv, it just installs it to the global python site-packages directory. I have automation scripts that create a virtualenv and then call pip on the requirements.txt file, I can't just run an installer

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

I don't have the full version. I compile for 64-bit.

use the microsoft SDK.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Mark Grandi (Bitbucket: [mgrandi](https://bitbucket.org/mgrandi), GitHub: [mgrandi](https://github.com/mgrandi))**:

----------------------------------------

Its literally like 1 command to update the build on pypi, although you do have to do it for all the OS versions, but its still very...annoying that the 'released build' is non-functional. Compiling things on windows is hard enough, it would just be easier to release a revision update release to fix this bug... this issue has been going on since may 2014! Its been almost half a year!

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

Hi Mark. I understand the pain of this and I agree a new version should have been released a while back to resolve this issue. I had thought that the new version (5.0), which won't have this problem going forward, would have been ready long before this. I am inclined to release 5.0 and suggest people use that since I have been using it for some time now quite successfully -- but Thomas has a few plans and there are a couple of outstanding issues that need to be resolved. Hopefully these matters can be resolved soon. If that is not the case, I will make sure a new release is made sometime before the end of the year, one way or the other!

**Comment by anthony-tuininga** [comment]
*Original comment by* **Mark Grandi (Bitbucket: [mgrandi](https://bitbucket.org/mgrandi), GitHub: [mgrandi](https://github.com/mgrandi))**:

----------------------------------------

I would just release 4.3.4, and have it be a windows only release (if at all possible, you can just release the same wheels for mac/linux on pypi) that is just recompiled, as it would cause more problems to release a version too early, and like people have said, it just takes a recompile, but as we have discussed its more difficult to compile on windows then other platforms

and not to mention this only effects py3.4 + ? so maybe just have the release be windows only py3.4?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anton Shiryaev (Bitbucket: [med_phisiker](https://bitbucket.org/med_phisiker), GitHub: Unknown)**:

----------------------------------------

Hello, I have the same problem with Python3.3 and cx_Freeze‑4.3.3.win32‑py3.3.exe from this site http://www.lfd.uci.edu/~gohlke/pythonlibs/#cx_freeze. 
In the comments below Thomas Kluyver Christoph writes that Gohlke's site apparently has a recompiled version which fixes this issue:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#cx_freeze
but for me it doesn't working.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

So far the change has only been affecting Python 3.4. If it's now affecting 3.3 as well, cx_Freeze may need to be recompiled again for that.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

It really shouldent effect python 3.3

The problem was only introduced in python 3.4

Are you sure it is the same error?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anton Shiryaev (Bitbucket: [med_phisiker](https://bitbucket.org/med_phisiker), GitHub: Unknown)**:

----------------------------------------

I write my problem in 'my problem.doc' file. I successfully build distribution with Python2.7 with cx-freeze 4.3.3 but have problem with Python3.3.5 and cx_freeze 4.3.3. I think that this is the same error but I new in programming - you can see my  'my problem.doc' file.

link to 'my problem.doc' in my dropbox https://www.dropbox.com/s/w22yof15h5nnqav/my%20problem.doc?dl=0

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

The error seems to show that some module you are using is outdated, and will be removed.

It is not related to this error, nor is it a bug with cx_freeze

In python 3, it was most likely removed, causing the error.

In python 2.7, it is there, but should NOT be used.


[This](http://matplotlib.org/api/api_changes.html) stats that

```
#!text

As part of the refactoring to enable Qt5 support, the module matplotlib.backends.qt4_compat was renamed to matplotlib.qt_compat.
qt4_compat is deprecated in 1.4 and will be removed in 1.5.
```

What you should do is change your code, as the warnings tell you to.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

The bigger issue there is that anything that attempts to show a warning will cause an error, because by default it tries to write warnings to sys.stderr, and if you use the Win32GUI base, there's no stderr to write to. Calling `warnings.simplefilter('ignore')` beforehand should prevent that.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

I think the bigger issue is that, whatever he is using is deprecated in 2.7, most definitely removed in 3.3, don't you think?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Nvm, i think.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**:

----------------------------------------

I think the deprecation is in matplotlib, not in Python; Anton may have different versions of matplotlib installed in his different Python versions, giving him the error in one but not the other.

About relative issue size: I meant it's a bigger issue for cx_Freeze, i.e. possibly someone should file a separate issue for that, or work on a fix. We can't fix people using deprecated APIs, but it shouldn't crash with an obscure error if you do.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Oh, wow. I was mistaken.

Idk why, but i thought that was a standard thing for some reason.

Though i can't think what would cause the issue in python 3.3 but not in 2.7 on the same install

It's an error in showing the error, it seems.

Maybe on win32GUI bases, create a wrapper class for sys.stderr that will cause it open an error message with the information supplied?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anonymous**:

----------------------------------------

Or one that redirects it to nowhere, with an option to print non errors to logs when creating the exe?

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anton Shiryaev (Bitbucket: [med_phisiker](https://bitbucket.org/med_phisiker), GitHub: Unknown)**:

----------------------------------------

I  have same version of matplotlib, PyQt and cx_freeze for Python27 and Python 335. Thomas Kluyver, I want  to say 'Thank you very mich!' =) You are right, when I write 
import warnings
warnings.simplefilter('ignore')

in the begining of my script cx_freeze made his work and program distribution works right way for now ) Thank you again )

**Comment by anthony-tuininga** [comment]
*Original comment by* **Anthony Tuininga (Bitbucket: [anthony_tuininga](https://bitbucket.org/anthony_tuininga), GitHub: Unknown)**:

----------------------------------------

This issue should now be resolved. cx_Freeze 5.0 no longer ships part of the standard library so should no longer run into problems like this.

**Comment by J-TUREK** [comment]
I am experiencing this exact error on cx-freeze version 6.11.1 python version: 3.9.0

**Comment by marcelotduarte** [comment]
@J-TUREK I recommend that you open an issue with details, so I will analyze. It's probably a similar error but caused by another library.
