### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005) If .ico file is not as expected

### ISSUE THREAD

**Issue by Berserker66** [marcelotduarte/cx_Freeze#824]
I switched my exe icon from a simple .ico to my website's favicon.ico and then got a log like this:

```
running build_exe
copying c:\program files\python38\vcruntime140.dll -> build\exe.win-amd64-3.8\vcruntime140.dll
copying c:\program files\python38\python38.dll -> build\exe.win-amd64-3.8\python38.dll
copying c:\program files\python38\python3.dll -> build\exe.win-amd64-3.8\python3.dll
copying C:\Program Files\Python38\lib\site-packages\cx_Freeze\bases\Console.exe -> build\exe.win-amd64-3.8\BerserkerMultiClient.exe

Process finished with exit code -1073741819 (0xC0000005)
```

offending ico file:
https://github.com/Berserker66/MultiWorld-Utilities/blob/master/WebHostLib/static/static/favicon.ico

Tested on 6.4.0 on Python 3.8 and Python 3.9; then updated to 6.4.2 in case it is fixed, but same error.

I don't know if this can be fixed, as this ico might just not be exe compatible; but if so a more graceful crash with an error message to narrow down the search for the problem would be quite nice.

**Comment by marcelotduarte** [comment]
PR #850 sample
PR #851 fix

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5 has just been released.
