### ISSUE TITLE
broken pyside2 example with commit in develop

### ISSUE THREAD

**Issue by klensy** [marcelotduarte/cx_Freeze#825]
Hi.

python 3.8.6, pyside2==5.14.2.3, develop branch.

Pyside2 example became broken with commit https://github.com/marcelotduarte/cx_Freeze/commit/40fb1ec299b14f24c399eb243de537c294c7d526 (even with manually adding needed libs)

![PySide2app_2020-12-07_19-59-43](https://user-images.githubusercontent.com/1782831/101380680-e022f700-38c6-11eb-8528-cbb8ce45e677.png)

**Comment by marcelotduarte** [comment]
I updated the branch.
I have some test: https://github.com/marcelotduarte/freeze-test/actions/runs/406434735

**Comment by marcelotduarte** [comment]
I'm closing this issue. Please feel free to open a new issue when it arises.
