### ISSUE TITLE
Customer side Error 

### ISSUE THREAD

**Issue by Arickaji** [marcelotduarte/cx_Freeze#855]
https://i.imgur.com/Jal32L9.png 
Please see this link and my python code is perfect but when i run this code in customer computer i need this error please reply sir.
and i run this python code into exe and give this exe to customer but this error return .

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5.2 has just been released. Please, try it out.

**Comment by Arickaji** [comment]
thanks you sir

**Comment by Arickaji** [comment]
Sorry sir i tried 6.5.2 version i get the same error again .

**Comment by Arickaji** [comment]
Sorry sir i tried 6.5.2 version i get the same error again .


---------- Forwarded message ---------
From: Aric Kaji <arickaji007@gmail.com>
Date: Tue, 19 Jan 2021 at 11:52
Subject: Re: [marcelotduarte/cx_Freeze] Customer side Error (#855)
To: marcelotduarte/cx_Freeze <
reply@reply.github.com>


thanks you sir

**Comment by marcelotduarte** [comment]
Does the Tkinter sample work for you?
https://github.com/marcelotduarte/cx_Freeze/tree/master/cx_Freeze/samples/Tkinter

**Comment by Arickaji** [comment]
thanks for your reply i will check then reply you .

**Comment by Arickaji** [comment]
I also use reportlab library.

**Comment by marcelotduarte** [comment]
Does your project use Tkinter? If so, build the sample and test like you tested your project and we can eliminate the problems, step by step...

**Comment by Arickaji** [comment]
ohk i can do and if something wrong i can tell and thanks for your help.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.

**Comment by Arickaji** [comment]
ok sir
