### ISSUE TITLE
cx-freeze setup.py typo

### ISSUE THREAD

**Issue by klensy** [marcelotduarte/cx_Freeze#866]
Hi.

1. Typo with double `os.path` at: https://github.com/marcelotduarte/cx_Freeze/blob/8bc2fba1cd149d0796b403f701adbb35b898a1f1/setup.py#L93
2.  Are it really need to write something out of cx-freeze dev folder? We can build it inside of cx_feeze subfolder, removing one of ` os.path.dirname`

**Comment by marcelotduarte** [comment]
See conversations at PR #650

**Comment by klensy** [comment]
Still `os.path.os.path`, but surprisingly, it won't break anything.

**Comment by marcelotduarte** [comment]
PR #877 fix two typos. Thanks!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.5.1 has just been released.
