### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by jschueller** [marcelotduarte/cx_Freeze#871]
on conda-forge osx/py3.9, the 6.5 build fails because of the "-Wl,-export_dynamic -g" flags:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/257875/logs/72 (https://github.com/conda-forge/cx_freeze-feedstock/pull/24)

it seems to originate from setup.py, as for python 3.8 the compilation line just contains the additional -s:
```
            # PR #812 - fix a bug using macOS on Github Actions
            # PY_LDFLAGS_NODIST = "-flto -Wl,-export_dynamic -g"
            if get_config_var("PY_LDFLAGS_NODIST"):
                extra_args.extend(get_config_var("PY_LDFLAGS_NODIST").split())
            else:
                extra_args.append("-s")
```

**Comment by marcelotduarte** [comment]
From the logs, I saw that for py36-38 it worked, only for py39 that didn't. I used a system variable exactly to avoid errors. The variable must contain something like: "-flto -Wl,-export_dynamic"
Sometimes it has -g too.
But in this issue, you didn't mention the "-flto"
Can you put the result of following command for py38 and py39?
python -c "import distutils.sysconfig as ds; from pprint import pprint as p; p(ds.get_config_vars())"

**Comment by jschueller** [comment]
yes, -flto does not appear here, being a python configure option I guess it is not enabled by the conda-forge recipe of python

**Comment by marcelotduarte** [comment]
PR #812 is the cause of this issue. Can you send me the result of the command list above?
Or test adding -flto to the build?

**Comment by marcelotduarte** [comment]
Wait, it's important to note that cx_Freeze 6.4.2 already used this 812 patch and it builds in conda-forge. You must have changed something in the build and removed the -flto for py39.

**Comment by jschueller** [comment]
-flto was missing for the 6.4.2 version also:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/248451/logs/78

**Comment by marcelotduarte** [comment]
Can you test adding -flto or check the build script if has changes about this or show the place of this script?

**Comment by marcelotduarte** [comment]
In this log https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/257875/logs/72
I found reference to python 3.8:
2021-01-03T21:54:56.6651820Z Extracting : python_abi-3.8-1_cp38.tar.bz2:  82%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ– | 28/34 [00:02<00:01,  4.72it/s]

**Comment by jschueller** [comment]
that's possible, there's a bootstrap conda environment used to install the target/build environment

**Comment by marcelotduarte** [comment]
The error is the python 3.9.1 from conda-forge. Using the 3.9.0 the build is successful.
