### ISSUE TITLE
Mac error when freeze PySide2 app with virtual environment activated 

### ISSUE THREAD

**Issue by ktmlleska** [marcelotduarte/cx_Freeze#873]
Hello, 
I'm in a python3k virtual environment and I'm to build a package for mac that uses PySide2. When building with bdist_mac with cx_Freeze 6.5 I receive the following error:

`cx_Freeze.darwintools.DarwinException: resolveRPath() failed to resolve path: @rpath/QtCore.framework/Versions/5/QtCore`

Which I understand that it happens because the @rpath is pointing to: `/Users/MyUser/.pyenv/versions/3.7.6/envs/MyVirtualEnv/lib/python3.7/site-packages/PySide2`
when trying to look for the PySide framework. 

Instead it should be looking to: `/Users/MyUser/.pyenv/versions/3.7.6/envs/MyVirtualEnv/lib/python3.7/site-packages/PySide2/Qt/lib` which is where the framework files exist.

Does anyone knows any solution to this or found the same issue?

Thanks!

**Comment by marcelotduarte** [comment]
Hi
Can you test the PR #887 (if you have a C compiler):
pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/887/head

**Comment by ktmlleska** [comment]
Thanks I'll test it.

**Comment by ktmlleska** [comment]
Hey, thanks! it solves the PySide errors, but still failing with the following error:
`error: [Errno 2] No such file or directory: '/usr/local/opt/gdbm/lib/libgdbm.4.dylib'`
In that folder the only files I have are libgdbm.6.dylib, libgdbm_compat.4.dylib and libgdbm.dylib
But I guess this is an unrelated error, so it seems to me that this issue is solved.
Thank you again.

**Comment by marcelotduarte** [comment]
@cainesi He tested your PR too.

**Comment by cainesi** [comment]
> Hey, thanks! it solves the PySide errors, but still failing with the following error:
> 
> `error: [Errno 2] No such file or directory: '/usr/local/opt/gdbm/lib/libgdbm.4.dylib'`
> 
> In that folder the only files I have are libgdbm.6.dylib, libgdbm_compat.4.dylib and libgdbm.dylib
> 
> But I guess this is an unrelated error, so it seems to me that this issue is solved.
> 
> Thank you again.

Just to confirm – the program runs okay unfrozen, but the freeze fails with the message above￼?

Would you mind uploading all the output from cx_freeze so I can see what is happening. Might still be something I can fix?

Thanks.

**Comment by ktmlleska** [comment]
Hi @cainesi Sorry for the late response:

**Comment by ktmlleska** [comment]
Hi @cainesi, sorry for the late response.

So this error appears just in one computer, it's probably some particular system configuration I have in this computer, and appears when I'm building the application with bdist_mac, after coping all the Qt frameworks. (Here is a pice of the error, sorry I can't send you much more) (This is in mojave and with homebrew installed)
```
copying /Users/lluser/.pyenv/versions/3.7.6/lib/python3.7/lib-dynload/_elementtree.cpython-37m-darwin.so -> build/exe.macosx-10.14-x86_64-3.7/lib/_elementtree.cpython-37m-darwin.so
copying /Users/lluser/.pyenv/versions/3.7.6/lib/python3.7/lib-dynload/_gdbm.cpython-37m-darwin.so -> build/exe.macosx-10.14-x86_64-3.7/lib/_gdbm.cpython-37m-darwin.so
copying /usr/local/opt/gdbm/lib/libgdbm.4.dylib -> build/exe.macosx-10.14-x86_64-3.7/libgdbm.4.dylib
error: [Errno 2] No such file or directory: '/usr/local/opt/gdbm/lib/libgdbm.4.dylib'
```

But I tried in another computer, with Catalina and I could build successfully without any error. It's true though that after build the application, I can't make it run because of the following errors with PySide:
```
PySide2/__init__.py: Unable to import shiboken2 from /Users/lluser/work/package/build/exe.macosx-10.15-x86_64-3.7/lib/library.zip, /Users/lluser/work/package/build/exe.macosx-10.15-x86_64-3.7/lib
Traceback (most recent call last):
  File "/Users/lluser/.pyenv/versions/build_connect/lib/python3.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 66, in run
    module.run()
  File "/Users/lluser/.pyenv/versions/build_connect/lib/python3.7/site-packages/cx_Freeze/initscripts/Console.py", line 36, in run
    exec(code, m.__dict__)
  File "source/package/__main__.py", line 113, in <module>
  File "/Users/lluser/.pyenv/versions/build_connect/lib/python3.7/site-packages/connect.dev171+g0f21c4d-py3.7.egg/connect/__main__.py", line 15, in <module>
    from Qt import QtWidgets, QtCore
  File "/Users/lluser/.pyenv/versions/build_connect/lib/python3.7/site-packages/Qt.py", line 1919, in <module>
    _install()
  File "/Users/lluser/.pyenv/versions/build_connect/lib/python3.7/site-packages/Qt.py", line 1867, in _install
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.
```
And this last error I solved using the include_files in the setup py including the platforms, imageformats and iconengines plugins from pyside.

**Comment by cainesi** [comment]
Hi @ktmlleska. For the "shiboken2" problem, could you just try adding "import shiboken2" into your program somewhere, and see if that fixes it (alternatively, include it in the list of specifically included modules in the setup.py script)?  (I know plugins sometimes separately need to be explicitly included--for PyQt there are more hooks to do that automatically--but I'm not sure why that would have dealt with the shiboken2 error...)

For the "libgdbm.4.dylib" problem, I'm less sure.  It seems like cx_Freeze is probably trying to include a library that dynamically loads "/usr/local/opt/gdbm/lib/libgdbm.4.dylib", and that file simply does not exist.  I'm not sure why that would not also be a problem when trying to run the program unfrozen...

**Comment by ktmlleska** [comment]
> alternatively, include it in the list of specifically included modules in the setup.py script

This is what I did and works perfectly. EDITED: Sorry, that is not true, isn't working yet. I will check what is going on and I will let you know if I can find the cause or the solution for this. Thanks.

>  It seems like cx_Freeze is probably trying to include a library that dynamically loads "/usr/local/opt/gdbm/lib/libgdbm.4.dylib", and that file simply does not exist

Yes, I'm not sue why this is happening, and is only happening on one computer, ("the one that has ruby installed with mojave") in the other computer with catalina, the gdbm folder doesn't even exist and works perfectly.

**Comment by marcelotduarte** [comment]
> For the "libgdbm.4.dylib" problem

Python has a module dbm.gnu that depends on libraries installed on the system. So, you can use "excludes": ["dbm.gnu"] 
If your app doesn't use it, it is safe to exclude that module and its dependencies

**Comment by ktmlleska** [comment]
Hi @cainesi I tried to import shiboken2 in my code and then build, I got the following error: 

`Traceback (most recent call last):
  File "/Users/lluser/.pyenv/versions/build_connect/lib/python3.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 66, in run
    module.run()
  File "/Users/lluser/.pyenv/versions/build_connect/lib/python3.7/site-packages/cx_Freeze/initscripts/Console.py", line 36, in run
    exec(code, m.__dict__)
  File "source/package/__main__.py", line 8, in <module>
    import shiboken2
  File "/Users/lluser/.pyenv/versions/build_connect/lib/python3.7/site-packages/shiboken2/__init__.py", line 27, in <module>
    from .shiboken2 import *
ImportError: dlopen(/Users/lluser/work/package/build/exe.macosx-10.15-x86_64-3.7/lib/shiboken2.shiboken2.abi3.so, 2): Library not loaded: @rpath/libshiboken2.abi3.5.15.dylib
  Referenced from: /Users/lluser/work/package/build/exe.macosx-10.15-x86_64-3.7/lib/shiboken2.shiboken2.abi3.so
  Reason: image not found`

@marcelotduarte I'll try your suggestion for the gdbm. Thanks

**Comment by ktmlleska** [comment]
@marcelotduarte seems that "excludes" works for build_exe but not for bdist_mac.

**Comment by cainesi** [comment]
What failure do you get in bdist_mac?

**Comment by cainesi** [comment]
Looks like other people have had shiboken problems, apart from cx:

https://github.com/mherrmann/fbs/issues/119

I've been working on a PR that works provide detailed explanations of why cx freeze is including each file.  Might be useful to try with that, one available.

**Comment by ktmlleska** [comment]
@cainesi 
> What failure do you get in bdist_mac?

`error: error in setup script: command 'bdist_mac' has no such option 'excludes'`

And that is correct according to the documentation: https://cx-freeze.readthedocs.io/en/latest/distutils.html#distutils

**Comment by cainesi** [comment]
The excludes option is only for build_exe.  Even if you are using the bdist_mac command, you would need to specify the option for build_exe.  (bdist_mac invokes build_exe to basically assemble all the required files into one directory, before bdist_mac packages them into an .app bundle)

**Comment by ktmlleska** [comment]
A okok sorry for the confusion. Trying it now. Thanks.

**Comment by ktmlleska** [comment]
Hi @marcelotduarte and @cainesi.
I finally have my build working, but I saw a couple of things that I'm not sure if they are bugs from cx_freeze or you already want them working this way.
So first of all, to make it work and avoid the shiboken2 error I had to include the the following files manually into the setup.py using:

`include_files.extend(
            [
                (os.path.join(pyside_path, "Qt", "plugins", "platforms"), 'lib/Qt/plugins/platforms'),
                (os.path.join(pyside_path, "Qt", "plugins", "imageformats"), 'lib/Qt/plugins/imageformats'),
                (os.path.join(pyside_path, "Qt", "plugins", "iconengines"), 'lib/Qt/plugins/iconengines'),
                (os.path.join(pyside_path, "Qt", "lib"), 'lib/Qt/lib'),
                (os.path.join(pyside_path, "libpyside2.abi3.5.15.dylib"), 'lib/libpyside2.abi3.5.15.dylib'),
                (os.path.join(shiboken_path, "libshiboken2.abi3.5.15.dylib"), 'lib/libshiboken2.abi3.5.15.dylib')
            ]
        )`

The most important ones are these 3:

`(os.path.join(pyside_path, "Qt", "lib"), 'lib/Qt/lib'),
  (os.path.join(pyside_path, "libpyside2.abi3.5.15.dylib"), 'lib/libpyside2.abi3.5.15.dylib'),
  (os.path.join(shiboken_path, "libshiboken2.abi3.5.15.dylib"), 'lib/libshiboken2.abi3.5.15.dylib')`

The lib includes all the .frameworks on the lib/qt/lib folder and the other two add the dylib files into the lib folder of the build, otherwise the my build doesn't start.

So in here I realise the following, when I add the frameworks on the include_files, the QT executables ad for example: Qt3DAnimation, QtCore, QtGui, etc.... are added to the root folder of the build, instead of going to the build/lib folder.

And much more important, even this 2 files (libpyside2.abi3.5.15.dylib, libshiboken2.abi3.5.15.dylib) together with some other dylib files (libssl.1.1.dylib, libcrypto,....) are automatically added to the build root folder, I have to manually add them into the build/lib folder with the include files to make it work.

So my question is, shouldn't all those files be added directly into the build/lib folder?

Thanks for your help, If this is a bug and you need more information, don't hesitate to contact me, I'll be happy to help you fix it.
