### ISSUE TITLE
mixup of the main module when using multiple executables with a "-" in the target name

### ISSUE THREAD

**Issue by jensgoe** [marcelotduarte/cx_Freeze#875]
i am using cx_Freeze to build two exe files.

```
setup(
        name = "hello",
        version = "0.1",
        description = "the typical 'Hello, world!' script",
        executables = [Executable("gui.py", base="Win32GUI", target_name="myapp.exe"),
                       Executable("cli.py", target_name="myapp-cli.exe")]
)
```

Because i am using the "-" char in my target name the internal main module is not detected correctly. the reason is #857. 
Especially the `name = name.partition("-")[0]` is causing this issue.

**Comment by marcelotduarte** [comment]
PR #878 
cx_Freeze 6.5.1 has just been released.
