### ISSUE TITLE
support for executable names that may not be valid identifiers

### ISSUE THREAD

**Issue by HotelCalifornia** [marcelotduarte/cx_Freeze#884]
in #857 the following line was added to the `target_name` setter for `Executable`s:

https://github.com/marcelotduarte/cx_Freeze/blob/50c379f694e251f6185f121a2a2def920c0dd2cf/cx_Freeze/freezer.py#L902

this breaks our workflow which involves an executable named `intercept-c++`, presumably because the `+` characters are not valid in an identifier.

could you shed some light on why this check was added? if it's necessary for other parts of cx_Freeze to function, we can work around it, but if not I feel it's too strict of a check.

**Comment by HotelCalifornia** [comment]
traceback:

```
Traceback (most recent call last):
  File "build.py", line 55, in <module>
    Executable('pros/cli/compile_commands/intercept-cc.py', target_name=f'intercept-c++{extension}')]
  File "/home/hotel/.pyenv/versions/pros-cli-build/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 830, in __init__
    "target_name", target_name, targetName
  File "/home/hotel/.pyenv/versions/pros-cli-build/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 903, in target_name
    raise ConfigError(f"Invalid name for target_name ({self._name!r})")
cx_Freeze.common.ConfigError: Invalid name for target_name ('intercept-c++')
```

(the build.py in question can be found [here](https://github.com/purduesigbots/pros-cli/blob/develop/build.py))

**Comment by marcelotduarte** [comment]
PR #889
cx_Freeze 6.5.2 has just been released.
