### ISSUE TITLE
#815 broke Windows `build_exe` calls with non-existent `cx_Freeze.util` import

### ISSUE THREAD

**Issue by jackson15j** [marcelotduarte/cx_Freeze#897]
Upgraded from v6.4.1 to latest (v6.5.1) and noticed that #815 had broken Windows `build_exe` calls. Traceback:

```
(test_venv) C:\test_project>python cx_freeze_setup.py build_exe
Traceback (most recent call last):
  File "cx_freeze_setup.py", line 9, in <module>
    from cx_Freeze import ConfigError
  File "c:\test_venv\lib\site-packages\cx_Freeze\__init__.py", line 13, in <module>
    from cx_Freeze.freezer import ConstantsModule, Executable, Freezer
  File "c:\test_venv\lib\site-packages\cx_Freeze\freezer.py", line 35, in <module>
    import cx_Freeze.util
ModuleNotFoundError: No module named 'cx_Freeze.util'
(test_venv) C:\test_project>
```

Digging into the PR, it looks like you need to import: `cx_Freeze.common`, instead of: `cx_Freeze.util`, in: `freezer.py` (https://github.com/marcelotduarte/cx_Freeze/blob/f5be487e5db58d2a482b272313e6809a06b7e3d0/cx_Freeze/freezer.py#L35) to complete this refactor.

**Comment by marcelotduarte** [comment]
In windows, cx_Freeze.util is an extension. Maybe something is broken in your installation. Please uninstall it and install it.
Like:
pip uninstall -y cx-freeze
pip install -U cx-freeze
I take this opportunity to inform you that cx_Freeze 6.5.3 is available.

**Comment by jackson15j** [comment]
Was coming to the same conclusion. Colleague has this working in their venv. Will kick this about to see what is breaking in my fresh venv vs theirs.

**Comment by marcelotduarte** [comment]
If It can be `importlib-metadata`. If you are uninstalling and installing it resolves.
