### ISSUE TITLE
Trouble with PyQt4

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#9]
Originally reported by: **Anonymous**

----------------------------------------

I have built Qt 4.8.2, PyQt 4.9.4 and cx_Freeze 4.3 with mingw 4.6.2.

Under these conditions, an example of cx_Freeze-4.3\samples\PyQt4\PyQt4app.py ends with the message -
"Runtime Error!

Program: ...reeze-4.3\samples\PyQt4\build\exe.win32-2.6\PyQt4app.exe

This application has requested the Runtime to terminate it in an unusual way.
Please contct the application's support team for more information."

I'm doing something wrong?

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/9

**Comment by anthony-tuininga** [comment]
*Original comment by* **Christopher Foo (Bitbucket: [chfoo0](https://bitbucket.org/chfoo0), GitHub: Unknown)**:

----------------------------------------

I had this error for a more complex program (using official Qt and PySide downloads). My problem is likely unrelated but I hope the following helps. 

If you haven't already, install the Windows Debugger Tools (WinDbg) and use it to run PyQt4App.exe. Keep clicking Go to see messages. 

For PyQt4App.exe, it ran ok and it listed what DLLs it loaded.

In my program that I was trying to freeze, it was saying ``Fatal Python error: can't initialize module QtUiTools``. It turns out QtUiTools needed QtXml but QtXml4.dll wasn't included. Requiring PySide.QtXml solved the problem.

I hope the above info helps.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.
