### ISSUE TITLE
ImportError: cannot import 'util' from 'pandastable' after cx_freeze compile

### ISSUE THREAD

**Issue by SylvanusMounk** [marcelotduarte/cx_Freeze#908]
Hello,
My script was working fine before compiling with cx_freeze.
But after creating the.exe, I have error messages relating to a circular import.
I'm using Windows 10 32bits and python38 cx_freeze version 6.5
 
the error message :
Traceback (most recent call last):
  File "C:\Users\Administrateur\Desktop\ligne_d_Vis\.mdenv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
    module.run()
  File "C:\Users\Administrateur\Desktop\ligne_d_Vis\.mdenv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
    exec(code, m.__dict__)
  File "Vimasys.py", line 45, in <module>
  File "C:\Users\Administrateur\Desktop\ligne_d_Vis\.mdenv\lib\site-packages\pandastable\__init__.py", line 5, in <module>
    from .core import *
  File "C:\Users\Administrateur\Desktop\ligne_d_Vis\.mdenv\lib\site-packages\pandastable\core.py", line 42, in <module>
    from .data import TableModel
  File "C:\Users\Administrateur\Desktop\ligne_d_Vis\.mdenv\lib\site-packages\pandastable\data.py", line 30, in <module>
    from . import util
ImportError: cannot import name 'util' from partially initialized module 'pandastable' (most likely due to a circular import) (C:\Users\Administrateur\Desktop\ligne_d_Vis\build_console\exe.win32-3.8\lib\pandastable\__init__.pyc)
Hope someone will get me out of this shit.

Setup.py file
```
import sys, os
from cx_Freeze import setup, Executable

build_exe_options = {"packages": ["os"],
                    
                     "include_files": ["ViMa.ico", "imgs/", "important/", "Dossier_graphiques", "Dossier_QR", 
                                        "sam_fichierspdf", "sam_fichiersexcel", ]
                     }


base = None
if sys.platform == "win32":
    base = "Win32GUI"

setup(name = "VIMASYS",
      version = "2.1",
      description ="Application de gestion et d'archivages des visites",
      author = "Mounk Digital",
      options ={"build_exe": build_exe_options},
      executables=[Executable("Vimasys.py", base=base, icon="ViMa.ico", shortcutDir="Desktop",
                               )])
```

And here's my program file 
```
from datetime import datetime
import os
import random
import sqlite3
import tempfile
import sqlite3 as sql
import time
from time import strftime
import time as tm
from tkinter import *
from shutil import copyfile
import tkinter.colorchooser
from tkinter import filedialog
from tkinter import messagebox
from tkinter import ttk
#import tkinter as tk
import tempfile
import pyqrcode
import qrcode
from tkinter import Tk, filedialog
from tkinter.ttk import Treeview
import csv
import webbrowser
import string
from random import randint, choice
import _csv
from PIL import Image, ImageTk
from sqlite3 import connect
from arrow import utcnow, get
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.lib.pagesizes import letter
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.colors import black, purple, white
from reportlab.pdfgen import canvas
import numpy as np
import matplotlib.pyplot as plt 
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import pandastable
from pandastable import Table, TableModel
import pandas as pd
from pandas import DataFrame
import cv2
from PyQt5.QtMultimedia import *
from PyQt5.QtCore import QUrl
import hashlib
```

**Comment by marcelotduarte** [comment]
I used a sample at pandastable docs.
If you use "packages": ["pandastable"] you can solve the issue with circular imports. Probably you should include other packages too.
The pandastable has information about freeze: https://pandastable.readthedocs.io/en/latest/examples.html#freezing-the-app

A problem with your code could arise because you're mixing tkinter and pyqt5. The author of pandastable has another library to be used with pyqt5: https://github.com/dmnfarrell/tablexplore

**Comment by SylvanusMounk** [comment]
Ok, thanks, I will try to apply your ideas.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
