### ISSUE TITLE
How to comply with licenses when shipping cx_Freeze'd applications.  

### ISSUE THREAD

**Issue by jounathaen** [marcelotduarte/cx_Freeze#911]
If I got it right, almost all open source licenses like GPL and MIT require you to include the license text when distributing the software. So I assume that for every dependency I include in my cx_frozen folder I have to include the license as well.

cx_freeze doesn't seem to include the license files, so I would have to add them all individually with `include_files`, right?
This sounds a bit tedious as dependencies of dependencies quickly add up.

Is there a good solution to properly handle licenses of dependencies with this tool?

**Comment by jounathaen** [comment]
After some thought about this, I've included a `3rd party licenses` document which includes the open source licenses and lists the included packages. This single file can then be included with `include_files`.

This issue can be closed, but maybe it is in scope of this project to add some helper functionality for this or add this to the documentation. I'll leave the issue open for this case.

**Comment by marcelotduarte** [comment]
> This single file can then be included with `include_files`.

This is the common case, but a developer can choose another place, inside a program, in an about, etc (Firefox uses about and redirect to about:license)


> add this to the documentation

I accept a PR ;-) or a close.
