### ISSUE TITLE
macos: missing zlib on cx_Freeze > 6.2

### ISSUE THREAD

**Issue by antirotor** [marcelotduarte/cx_Freeze#914]
Running freezed project will result in:
```
Fatal Python error: initfsencoding: unable to load the file system codec
Traceback (most recent call last):
  File "/Users/annatar/.pyenv/versions/3.7.9/lib/python3.7/encodings/__init__py", line 31, in <module>
zipimport.ZipImportError: can't decompress data; zlib not available
```
When freezed in 6.1 or 6.2 it does work correctly but not in newer versions. It doesn't matter what Python version is used (tried on 3.7.9, 3.8.2 and 3.9.4. Also **pyenv** doesn't seem to play role in this, even running under system wide Python installation. I've tried to manually copying zlib libraries to frozen code location.

This is on **Catalina** and **Big Sur**.

[failed-6.3.log](https://github.com/marcelotduarte/cx_Freeze/files/5966168/failed-6.3.log)
[success-6.2.log](https://github.com/marcelotduarte/cx_Freeze/files/5966214/success-6.2.log)

main difference is at the beginning. It seems that newer verisons fail to find libpython

**Comment by marcelotduarte** [comment]
With pyenv I have information about success, using --enable-shared

EDIT:
This should be your issue, as in your log has:
*** WARNING *** default bin include not found: libpython3.7m.a

EDIT2:
related issue #701

**Comment by antirotor** [comment]
> With pyenv I have information about success, using --enable-shared

I tried even with `--enable-shared`. Warning in log changes to correct file name (from .so to .dylib) but it is still not found. But even if I don't use **pyenv** at all and just install and use Python directly it will still be missing zlib module.

**Comment by marcelotduarte** [comment]
After you changed the python, uninstall cx-freeze and reinstall, to force the recompile of C sources.

**Comment by antirotor** [comment]
I am using Poetry for this. So I either run pyenv to handle "base" Python version or use system wide installation of Python. cx-freeze is installed into virtual env managed by Poetry and to be sure I start with clean slate, I completely re-create virtual env when I switch base Python.

**Comment by marcelotduarte** [comment]
upgrade to cx-freeze 6.5.3 and run build_exe as:
python setup.py build_exe --silent
and put the log to me.
cx-freeze 6.5.3 has some fix for macOS.

> main difference is at the beginning. It seems that newer versions fail to find libpython

And, understand, it has to find this shared library. In cx-freeze 6.2 it finds the system shared library, not the package shared library. For example, if your systems have official python 3.8.2 and in your packager, you have python 3.8.6, it finds the library for 3.8.2 if you do not have a 3.8.6 shared library.

**Comment by antirotor** [comment]
Thanks, I've done as you suggested.

**Summary:**
macOS Big Sur (11.1)
python 3.9.1
cx_freeze 6.5.3 installed in virtualenv with Poetry

```
poetry run python3 setup.py build_exe --silent
```

resulting [build.log](https://github.com/marcelotduarte/cx_Freeze/files/5971470/build.log)

but running frozen code still fails on missing zlib (it is more verbose on 3.9.1 then older versions, but result is the same)

frozen code output in [error.log](https://github.com/marcelotduarte/cx_Freeze/files/5971475/error.log)

This is running on Big Sur under virtualbox on Intel platform. It seems that Python distools are still having trouble to properly detect system architecture (note `exe.macosx-10.9-x86_64-3.9`, should be `exe.macosx-11.1-x86_64-3.9`). Freezing code on other platforms (linux/windows) with the same versions is working ok, no problems with zlib. Also this happens on Catalina (10.15) with 3.8 and 3.7 Python versions.

**Comment by marcelotduarte** [comment]
Put the result of:
python -m sysconfig

> detect system architecture (note exe.macosx-10.9-x86_64-3.9, should be exe.macosx-11.1-x86_64-3.9).

MACOSX_DEPLOYMENT_TARGET defines this value (you can check in the above command)

**Comment by antirotor** [comment]
indeed, it seems there is
```
MACOSX_DEPLOYMENT_TARGET = "10.9"
```
I suppose this is like miminum compatibility version for build and doesn't reflect current platform.

[sysconfig.txt](https://github.com/marcelotduarte/cx_Freeze/files/5981519/sysconfig.txt)

**Comment by marcelotduarte** [comment]
In a Github Action that I have a running test, some variable has been set for macOS (to indicate --enable-shared):

CONFIG_ARGS = "'--prefix=/Users/runner/hostedtoolcache/Python/3.9.0/x64' '--enable-optimizations' '--enable-shared' '--with-lto' '--with-openssl=/usr/local/opt/openssl@1.1' '--enable-loadable-sqlite-extensions' 'CFLAGS= -I/usr/local/opt/sqlite/include' 'LDFLAGS= -L/usr/local/opt/sqlite/lib'"

Py_ENABLE_SHARED = "1"

In your sysconfig that wasn't enabled:

CONFIG_ARGS = "'-C' '--enable-framework' '--enable-universalsdk=/' '--with-universal-archs=intel-64' '--with-computed-gotos' '--without-ensurepip' '--with-openssl=/tmp/_py/libraries/usr/local' '--with-tcltk-includes=-I/tmp/_py/libraries/usr/local/include' '--with-tcltk-libs=-ltcl8.6 -ltk8.6' 'LDFLAGS=-g' 'CFLAGS=-g' 'CC=gcc'"

Py_ENABLE_SHARED = "0"

> Freezing code on other platforms (linux/windows) with the same versions is working ok

If you check these variables in Linux for example, it has been enabled.

**Comment by antirotor** [comment]
what puzzles me is that output I've posted is from "vanilla" Python distribution from **python.org**. I would guess that they compile all versions with the same options, but maybe not. I'll try 3.9.0 built with `--enable-shared` via **pyenv**

**Comment by marcelotduarte** [comment]
What is the command that you have used to install 3.9.1?

**Comment by marcelotduarte** [comment]
I found some information in https://medium.com/faun/pyenv-multi-version-python-development-on-mac-578736fb91aa
Apparently --enable-shared is to be used in Linux, but in macOS, the command should be:
`env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.9.1`

**Comment by antirotor** [comment]
I've tried two ways - first was just installing Python 3.9.1 with installer downloaded from **python.org**. That Python is compiled with `Py_ENABLE_SHARED = "0"`.

Then I removed it completely and installed it with **pyenv** using `CONFIGURE_OPTS="--enable-shared" pyenv install -v 3.9.1` and it did built Python with enabled shared libraries, but I've hit another problem that this Python variant is not able to build PyQt5 (but that is not relevant here). Next I'll try to build Python with `--enable-framework` and it seems you can set `MACOSX_DEPLOYMENT_TARGET = "11.1"` before build start.

I must admit that so far supporting Big Sur is real pain for us.

**Comment by antirotor** [comment]
Building with `--enable-framework` won't set `Py_ENABLE_SHARED` to 1 (and will also result in missing zlib error). It somehow feels like #513 but on macos and newer cx_freeze version.  I'll try to find out how zlib is linked.

**Comment by marcelotduarte** [comment]
If you observe, in 513 the error isn't in zlib. As zlib is the first module loaded, the error was to load it. In the case of 513 is a dependence issue in alpine with a virtual library.
Can you test CONFIGURE_OPTS="--enable-shared --enable-framework"?

**Comment by antirotor** [comment]
`--enable-shared` and `--enable-framework` are mutually exclusive.

But we've just found that we are unable to build with the same error (missing zlib) even on Linux (centos 7/ubuntu 20) so macos is probably not to be blamed. Simple tests I've ran freezed ok without any zlib error at all.

With cx_freeze 6.2 all is good but with newer versions zlib is missing :(

**Comment by marcelotduarte** [comment]
I use ubuntu 20.10 and I can build simple or larger projects if I run it on another machine with the same platform. Then I compile in a VM with ubuntu 18.04 to release.
I'm planning to support wheels for Linux to resolve issues like this (no shared lib and an older platform).
For macOS, I should do it too, later. But in macOS, we can use a newer platform to compile. As I'm not a macOS user/developer I need some time...
In conda-forge cx-freeze does not compile with py391 only 390 on macOS. Maybe the same problem is affecting you.

**Comment by marcelotduarte** [comment]
I have some wheels of a test, do you can try it?
[wheelhouse.zip](https://github.com/marcelotduarte/cx_Freeze/files/6009194/wheelhouse.zip)

**Comment by antirotor** [comment]
thanks, I've ran them all with the same error - **BUT**.... going through all the logs I've probably found culprit. I've overlooked it before but comparing build log with that coming from windows I've found out this error message appears on all unix builds:

```
error: [Errno 2] No such file or directory: '/home/annatar/pype/pype-3/.venv/lib/python3.7/site-packages/setuptools-49.6.0.dist-info/__pycache__'
```
and this definitely stops copying all necessary files in random order so build is incomplete.

Is it possible cx_freeze is trying to copy stuff from setuptools and is expecting all there is to be files?

**Comment by marcelotduarte** [comment]
try to uninstall setuptools, importlib-metadata and cx-freeze, then install setuptools and cx-freeze (importlib-metadata is installed by cx-freeze and some versions of it has bugs).

**Comment by antirotor** [comment]
ok, that works - I had to reinstall setuptools, importlib-metadata, cx_freeze, pip and wheel. Thanks for your help. Any idea if this is problem with poetry not creating `__pycache__` or cx_freeze not picking them correctly?

**Comment by marcelotduarte** [comment]
This can be an error of importlib-metadata. Maybe you had an old version and poetry did not update it.
Now your build is ok for Windows, Linux, and macOS?

**Comment by antirotor** [comment]
Yeah, builds are working correctly. I still need to find out why I need to reinstall all those dependencies bitching about `__pycache__` missing. It did probably work in older cx_freeze versions because different pulled in dependencies. Thank you very much for your help.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
