### ISSUE TITLE
PyQt5 ModuleNotFoundError: No module named PyQt5.sip

### ISSUE THREAD

**Issue by Dereas** [marcelotduarte/cx_Freeze#921]
When starting the  `PyQt5app.exe ` produced by `python setup.py build` for the minimal PyQt5 sample contained in cx_Freeze,
 a  `cx_Freeze: Python error in main script ` pops up with a `PyQt5 ModuleNotFoundError: No module named PyQt5.sip`
error. 

When i add `PyQt5.sip` to the 'includes' in the setup file, i already get an error during the build process after calling `python setup.py build` :
`ImportError: No module named 'PyQt5.sip'`.

I can import `PyQt5.sip` in the same python environment that i used to call  `python setup.py build`, therefore i don't understand why the error occurs during the build process.

Traceback for execution of `PyQt5app.exe `:
```python
Traceback (most recent call last):
File 
"C:\Users\Dereas\AppData\Local\Programs\Python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74 in run module.run()
File
"C:\Users\Dereas\AppData\Local\Programs\Python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36 in run exec(code, m.__dict__)
File "PyQt5app.py", line 4 in <module> from
  from PyQt5.QtWidgets import QApplication, QWidget
ModuleNotFoundError: No module named 'PyQt5.sip'
```

Related PR:
#718

Python 3.8.7 x64
Windows 10 x64
`python -m pip freeze`:
```
cx-Freeze==6.5.3
importlib-metadata==3.4.0
PyQt5==5.15.2
PyQt5-sip==12.8.1
zipp==3.4.0
```

**Comment by Dereas** [comment]
I cannot reproduce this anymore... i guess it was a problem with my environment (even though i observed it on 2 machines with minimal venvs). I noticed that sometimes it is necessary to `pip uninstall PyQt5 PyQt5-sip` (and `PyQt5-Qt` in case of `PyQt5 5.15.3`) when switching PyQt versions... i.e.` pip install PyQt5==5.15.2 `followed by `pip install PyQt5==5.15.3 ` will result in an error when trying to import `PyQt5.QtCore` (independent of cx_Freeze).

PyQt issues with cx_Freeze can also occur when having different PyQt5 versions installed with in the user packages folder (`pip install PyQt5 --user`) and in the system site packages folder (`pip install PyQt5`)

**Comment by xupan1992** [comment]
I solved this issue by upgrade the PyQt5-sip modul; 

pip install --upgrade PyQt5-sip
