### ISSUE TITLE
Failed to load plists

### ISSUE THREAD

**Issue by bubio** [marcelotduarte/cx_Freeze#924]
When using "custom_info_plist" option, the plist fails to load.

`
macdist.py", line 218, in create_plist
    contents = plistlib.load(fp, fmt=None, use_builtin_types=False)
TypeError: load() got an unexpected keyword argument 'use_builtin_types'
`

Starting with Python 3.9, 'use_builtin_types' has been removed.
https://github.com/unified-font-object/ufoNormalizer/issues/73

**Comment by marcelotduarte** [comment]
Can you test the fix at PR #926?
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/926/head`

**Comment by AdarshSrikanth** [comment]
any timeline for the next release with this fix?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
CC @AdarshSrikanth @bubio

**Comment by AdarshSrikanth** [comment]
yup, this issue got fixed. Thanks! 👍
