### ISSUE TITLE
pkg_resource.DistributionNotFound: The 'pycountry' distribution was not found and is required by the application.

### ISSUE THREAD

**Issue by kozzza** [marcelotduarte/cx_Freeze#930]
Upon running ``cx_freeze``, everything builds smoothly and all packages seem to be installed properly. 

However, when I run the ``main.exe`` file in the build folder I encounter the following error dialog: [error screenshot](https://i.imgur.com/lhnUQrg.png). I'm not sure how to fix this, but I have read about similar problems with the ``pycountry`` package for those packaging with ``pyinstaller``. 

I am using the template found on the ``cx_freeze`` docs for my ``setup.py`` file.
```python
import sys
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {"packages": ["os"], "excludes": ["tkinter"]}

# GUI applications require a different base on Windows (the default is for
# a console application).
base = None

if sys.platform == "win32":
    base = "Win32GUI"

setup(  name = "MyProject",
        version = "0.1",
        description = "MyProjectDescription",
        options = {"build_exe": build_exe_options},
        executables = [Executable('main.py', base=base)])
```
I run ``python setup.py build`` in my terminal on a virtual environment to build the project.

**Comment by marcelotduarte** [comment]
Try to include `"pycontry"` in the packages list.

**Comment by kozzza** [comment]
Still throws the same error even though the ``pycountry`` package is successfully installed in the build.

**Comment by marcelotduarte** [comment]
What are the python version and cx-freeze version?

**Comment by kozzza** [comment]
Running cx-freeze version 6.5.3 on Python 3.7.9

**Comment by marcelotduarte** [comment]
Please, run the commands:
pip uninstall -y pycountry
pip install --no-cache --use-pep517 pycountry

Then, rebuild your project.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
