### ISSUE TITLE
Feature: cx_Freeze and TensorFlow AutoGraph

### ISSUE THREAD

**Issue by kiflowb777** [marcelotduarte/cx_Freeze#931]
The TF AutoGraph  translates python code to tf.function, however when the code is freezen the AutoGraph cannot read the code which causes the program to fail.
Please add the possibility to use the TensorFlow 2.x AutoGraph with cx_freeze.

```
WARNING AutoGraph could not transform <function categorical_crossentropy.<locals>crossentropy at 0x0000021D0152EF28> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function create_weighted_categorical_crossentropy.<locals>.categorical_crossentropy at 0x0000021D0152EF28>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert   tensorflow:146
```

More info:
https://www.tensorflow.org/api_docs/python/tf/autograph
https://www.tensorflow.org/guide/function

**Comment by marcelotduarte** [comment]
Do you tried to use include_files to include the .py that has the function that it claims?
https://cx-freeze.readthedocs.io/en/latest/distutils.html#build-exe

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Closing due to lack of response.
If you had issues please open a new issue.
