### ISSUE TITLE
FileNotFoundError: pyzmq.libs folder missing with pyzmq >= 22.0

### ISSUE THREAD

**Issue by Dereas** [marcelotduarte/cx_Freeze#950]
In `pyzmq >= 22.0` [some changes](https://github.com/zeromq/pyzmq/blob/master/docs/source/changelog.rst) were made regarding the libzmq bundling. With pyzmq 22 importing `import zmq.libzmq` fails even though libzmq is bundled on windows.

`cx-Freeze==6.6.dev0` works fine with pyzmq 21, but with pyzmq 22  cx_Freeze assumes libzmq is not bundled because importing `zmq.libzmq` fails. However the required dlls are present in the build environment and can be found in site-packages/pyzmq.libs (maybe the following pyzmq commit is relevant even though i don't use conda, just a normal python venv: [pyzmq commit ddb311125c1f822](https://github.com/zeromq/pyzmq/commit/ddb311125c1f822b88bd10c9737e202d114be2dc#diff-96feb4f9391bfdcc1b368c3a26e5e1d91bb6b56e579878c9ca2ee2651371ee8e))
Running the frozen application results in a FileNotfoundError:

```python
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\Users\\Dereas\\code\\cx_Freeze\\cx_Freeze\\samples\\pyzmq\\build\\exe.win-amd64-3.8\\lib\\pyzmq.libs'
```

When i copy the pyzmq.libs folder manually to my frozen \lib folder, the small example runs fine.

<details>
<summary>test_pyzmq.py</summary>

```python
import zmq
import time

context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:5556")

while True:
    message = socket.recv()
    time.sleep(1)
    socket.send(f"I received your message: {message}")
```
</details>

<details>
<summary> setup.py</summary>

```python
from cx_Freeze import setup, Executable

setup(
    name="test_pyzmq",
    version="0.1",
    description="cx_Freeze script to test pyzmq",
    executables=[Executable("test_pyzmq.py")]
)

```
</details>

Relevant PR's: [PR #442 ](https://github.com/marcelotduarte/cx_Freeze/pull/442), [PR #843](https://github.com/marcelotduarte/cx_Freeze/pull/843)

<details>
<summary>Full Traceback</summary>

```python
(zmqenv) C:\Users\Dereas\code\cx_Freeze\cx_Freeze\samples\pyzmq\build\exe.win-amd64-3.8>test_pyzmq.exe
Traceback (most recent call last):
  File "C:\Users\Dereas\code\cx_Freeze\cx_Freeze\samples\pyzmq\zmqenv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
    module.run()
  File "C:\Users\Dereas\code\cx_Freeze\cx_Freeze\samples\pyzmq\zmqenv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
    exec(code, m.__dict__)
  File "test_pyzmq.py", line 1, in <module>
  File "C:\Users\Dereas\code\cx_Freeze\cx_Freeze\samples\pyzmq\zmqenv\lib\site-packages\zmq\__init__.py", line 19, in <module>
    _delvewheel_init_patch_0_0_10()
  File "C:\Users\Dereas\code\cx_Freeze\cx_Freeze\samples\pyzmq\zmqenv\lib\site-packages\zmq\__init__.py", line 10, in _delvewheel_init_patch_0_0_10
    os.add_dll_directory(libs_dir)
  File "C:\Users\Dereas\AppData\Local\Programs\Python\Python38\lib\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\Users\\Dereas\\code\\cx_Freeze\\cx_Freeze\\samples\\pyzmq\\build\\exe.win-amd64-3.8\\lib\\pyzmq.libs'
```

</details>

<details>
<summary>Python 3.8.8 environment on Windows 10 x64</summary>

```
cx-Freeze==6.6.dev0
importlib-metadata==3.7.0
pyzmq==22.0.3
zipp==3.4.0
```
</details>

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
