### ISSUE TITLE
Issue with Chinese character in the name of folder of executable

### ISSUE THREAD

**Issue by qqdzhang** [marcelotduarte/cx_Freeze#972]
For an executable frozen by cx-Freeze 6.5.3, with Python:
 Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)] on win32
 PyQt5 5.15.4

If there is Chinese character in the name of folder of executable, it failed to execute with messages prompted :
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

![err](https://user-images.githubusercontent.com/2564044/111026755-fc36b700-8426-11eb-87e0-fa52acedeeee.png)

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Can you check if this has been resolved?

**Comment by qqdzhang** [comment]
> cx_Freeze 6.6 has just been released.
> Can you check if this has been resolved?
(Sorry replying you late) Unfortunately the problem is still there -- with different error messages.
![image](https://user-images.githubusercontent.com/2564044/116114258-c7877200-a6eb-11eb-9c49-c043e58410e5.png)

**Comment by livius545** [comment]
The same issue occurs when Japanese characters are included in the execution path. 
Python 3.9.2
cx-Freeze 6.6

![image](https://user-images.githubusercontent.com/84485498/118906766-58ebac00-b959-11eb-8441-fa22498d5d78.png)

**Comment by livius545** [comment]
I think this issue is due to the change in #872.
But I don't know how to fix it.

**Comment by marcelotduarte** [comment]
The #872 is part of v 6.6. The author of first comment reported using 6.5.3
You can check with v 6.5 or 6.5.1 or 6.5.2 for example. I'll take a look.

**Comment by livius545** [comment]
In my environment, the issue does not occur with v 6.5 - 6.5.3.
The first report and the second report seem to have different causes, in my opinion.

**Comment by qqdzhang** [comment]
With 6.5, I got the same problem as I reported at the verify beginning on Mar. 13. So as Livius54 said, this issue "seem to have different causes"
> The #872 is part of v 6.6. The author of first comment reported using 6.5.3
> You can check with v 6.5 or 6.5.1 or 6.5.2 for example. I'll take a look.

**Comment by marcelotduarte** [comment]
> I think this issue is due to the change in #872.

Yes, you're correct.

cx_Freeze 6.7b2 has just been released with a fix (#1077).
pip install cx-Freeze==6.7b2

**Comment by marcelotduarte** [comment]
@qqdzhang @livius545 Please try it out and report

**Comment by qqdzhang** [comment]
6.7b2 still NOT working...  NOTE that it takesTWO conditions to duplicate the problem : 1) Asian(Chinese) chars in folder name  2) Use **PyQt5** module.  without 2) ,  Just 1) itself won't trigger the problem. Please refer to screenshot blow (also with .py files to duplicate the problem)
[case.zip](https://github.com/marcelotduarte/cx_Freeze/files/6541109/case.zip)
![image](https://user-images.githubusercontent.com/2564044/119538871-1e04d080-bdbe-11eb-93f5-e343cb5b985b.png)

**Comment by marcelotduarte** [comment]
But with v 6.6 both cases fails for you? And with 6.7b2 only a pyqr5 case fail?

**Comment by livius545** [comment]
> @qqdzhang @livius545 Please try it out and report

In my environment (no PyQt5), 6.7b2 worked fine.

**Comment by qqdzhang** [comment]
> But with v 6.6 both cases fails for you? And with 6.7b2 only a pyqr5 case fail?

That's right.

**Comment by qqdzhang** [comment]
> > @qqdzhang @livius545 Please try it out and report
> 
> In my environment (no PyQt5), 6.7b2 worked fine.

Right, without PyQt5, 6.7b2 works fine (with Asian chars in folder name) -- this can also be telled from my sceenshot (indicated by green lines/words)

**Comment by qqdzhang** [comment]
HINT: this problem is still related with cxFreeze (no with PyQt5 ) -- If I package a binary (with PyQt5 module) using pyinstaller, there's no problem -- binary can launch and run under folder-with-chinese-name

**Comment by marcelotduarte** [comment]
With PyQt5 5.15.4, if the folder name contains non-ascii characters (tested with Portuguese words in utf-8), the libraryPaths returns empty (tested with Linux and Windows). Prior to this version, this doesn't happen (tested in Linux only).
I had a patch. Soon I release a beta version to test.
You can test with a line before creating a app:
print("libraryPaths", QApplication.libraryPaths())

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8b1 has just been released with fixes for pyqt5. Please, try it out and report.
pip install cx-Freeze==6.8b1

**Comment by qqdzhang** [comment]
6.8b1 **WORK**s! This problem has been fixed. THANKs a lot !

> cx_Freeze 6.8b1 has just been released with fixes for pyqt5. Please, try it out and report.
> pip install cx-Freeze==6.8b1

**Comment by marcelotduarte** [comment]
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
