### ISSUE TITLE
cx_Freeze lower cases the dlls in the root folder of the build

### ISSUE THREAD

**Issue by husseinhussein** [marcelotduarte/cx_Freeze#986]
There is bug in freeze.py (_GetDependentFiles()), which inspects the base binary to determine the dlls that need to be included. The code lower-cases the dlls names. This causes the import to fail. For example, cx_Logging.pyd becomes cx_logging.pyd.

**Comment by marcelotduarte** [comment]
Do you are using the released version or the main branch?

**Comment by husseinhussein** [comment]
Thank you so much for a quick reply.

I am using a portable python v3.8 and have installed cx-Freeze v6.5 using pip.

The problem is that when I build an executable for my application to run as a service using base Win32Service, cx_Freeze includes cx_Logging and then lowercases it.

**Comment by husseinhussein** [comment]
Greetings,

Did you get a chance to look at this issue?

Thanks,
Hussein

**Comment by marcelotduarte** [comment]
Yes, I will soon release a version.

**Comment by husseinhussein** [comment]
Thanks a million.

**Comment by husseinhussein** [comment]
Greetings,

Sorry for bothering you.

When are you planning to release a new version? Just wanted to know so I can provide an update to my PM.

Thanks a million.

**Comment by marcelotduarte** [comment]
I hope to be able to solve some problems and release a version this week.

**Comment by husseinhussein** [comment]
Thank you so much.

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
