### ISSUE TITLE
SyntaxError: (unicode error)

### ISSUE THREAD

**Issue by gbtami** [marcelotduarte/cx_Freeze#989]
I'm using cx_Freeze to create .msi installer for https://github.com/pychess/pychess in a fresh install of MSYS2 environment, but it fails.
`python setup.py bdist_msi`
```
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/finder.py", line 411, in _load_module
    module.code = loader.source_to_code(
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Users/tamas/AppData/Local/Temp/3abf29f7-4063-428a-a81a-c2ab6550ebfe.py", line 4
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe1 in position 1: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 304, in <module>
    setup(
  File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/dist.py", line 392, in setup
    distutils.core.setup(**attrs)
  File "C:/msys64/mingw64/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "C:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/windist.py", line 793, in run
    self.run_command("build")
  File "C:/msys64/mingw64/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:/msys64/mingw64/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:/msys64/mingw64/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/dist.py", line 260, in run
    freezer.Freeze()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 765, in Freeze
    self._WriteModules(fileName, self.finder)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 592, in _WriteModules
    self.constantsModule.Create(finder)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 974, in Create
    module = finder.IncludeFile(filename, self.module_name)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/finder.py", line 623, in IncludeFile
    module = self._load_module(name, path, deferred_imports)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/cx_Freeze/finder.py", line 419, in _load_module
    raise ImportError(f"Invalid syntax in {path}", name=name)
ImportError: Invalid syntax in C:/Users/tamas/AppData/Local/Temp/3abf29f7-4063-428a-a81a-c2ab6550ebfe.py
```

I put some debug print lines to finder.py to see what went wrong, and got this:
```
BUILD_CONSTANTS C:/Users/tamas/AppData/Local/Temp/3abf29f7-4063-428a-a81a-c2ab6550ebfe.py
b"BUILD_COPYRIGHT = None\r\nBUILD_HOST = 'DESKTOP-89DJHHI'\r\nBUILD_RELEASE_STRING = '1.0.3'\r\nBUILD_TIMESTAMP = 'm\xe1rcius 19, 2021 14:20:55'\r\nSOURCE_TIMESTAMP = 'm\xe1rcius 19, 2021 11:57:41'"
```

My windows is Windows 10 pro (Hungarian!)
I solved my problem in MSYS2 console with
`export LC_ALL=C`
but I think it would be better to fix it in cx_Freeze

**Comment by marcelotduarte** [comment]
@gbtami I can't reproduce your error on Linux, Windows, or MSYS2. 
I made a PR #1005 that should solve this issue. Can you test my patch for this issue?

`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@refs/pull/1005/head`

Out of curiosity, what is the value of LC_ALL or LC_CTYPE in your system?

**Comment by gbtami** [comment]
tamas@DESKTOP-89DJHHI MINGW64 ~
$ echo "$LC_ALL"

tamas@DESKTOP-89DJHHI MINGW64 ~
$ echo "$LC_CTYPE"
hu_HU.UTF-8

tamas@DESKTOP-89DJHHI MINGW64 ~
$ python3
Python 3.8.8 (default, Feb 20 2021, 07:16:03)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
('Hungarian_Hungary', '1250')
>>> locale.getpreferredencoding()
'cp1250'

Yeah, your patch works.
Localized Windows is a  special kind of animal :)

**Comment by marcelotduarte** [comment]
In my system LC_CTYPE is pt_BR.UTF-8 and python on mingw64 and official python returns locale pt_BR and cp 1252
In yours the LC_CTYPE is different than the value returned by getlocale()
So the error is on msys.
```
$ python
Python 3.8.9 (default, Apr  3 2021, 09:30:04)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
('pt_BR', 'cp1252')
>>> locale.getpreferredencoding()
'cp1252'
>>>
```

**Comment by gbtami** [comment]
"So the error is on msys."
I'm not sure about this. Your getlocale() and getpreferredencoding() seems consistent with your LC_CTYPE, but on my side ('Hungarian_Hungary', '1250') and 'cp1250' seems doesn't match with hu_HU.UTF-8. I can imagine that this is not MSYS error but strange Windows localization instead. Anyhow I didn't changed anything in my Windows or MSYS install, everything is on default, so idk.

**Comment by marcelotduarte** [comment]
Do you have python from python.org installed? Because for me, the MSYS python and official python returns the same values.
But this is not too important. Just knowing that there may be cases in which what is documented is inconsistent already helps to avoid other cases.

**Comment by marcelotduarte** [comment]
Can you test the `cxfreeze-quickstart` in your system for me? Because it uses open without forcing the encoding.

**Comment by gbtami** [comment]
I installed latest official python from python.org as you suggested, and the MSYS python and official python returns the same values.
But.
Your `cxfreeze-quickstart` suggestion was a winning hint. I run it and saved the created setup.py as cx-setup.py
And running` python cx-setup.py bdist_msi` didn't produced Invalid syntax error.
Bingo!
Now I just had to find what line causes this issue in my own setup.py
And the solution is:` import Gtk`
You can try it yourself in MSYS2 if you have installed the needed packages.
```
import locale
from datetime import datetime
import _strptime

now=datetime.now()

print(locale.getlocale())
print(locale.getpreferredencoding())
print(locale.getdefaultlocale())
print(vars(_strptime.LocaleTime())["f_month"])

print(now.strftime("%B"))

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

print(locale.getlocale())
print(locale.getdefaultlocale())
print(locale.getpreferredencoding())
print(vars(_strptime.LocaleTime())["f_month"])
print(now.strftime("%B"))
```
```
$ python import_gtk.py
('Hungarian_Hungary', '1250')
cp1250
('hu_HU', 'cp1250')
['', 'january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december']
April
('Hungarian_Hungary', '1250')
('hu_HU', 'cp1250')
cp1250
['', 'janu▒r', 'febru▒r', 'm▒rcius', '▒prilis', 'm▒jus', 'j▒nius', 'j▒lius', 'augusztus', 'szeptember', 'okt▒ber', 'november', 'december']
▒prilis
```

**Comment by gbtami** [comment]
All-in-all if you want to avoid to add encoding to open() you have to avoid using localized month name formatting codes in strftime()
Instead of "%B" just use "%m".

Created https://github.com/marcelotduarte/cx_Freeze/pull/1006

**Comment by marcelotduarte** [comment]
But what happens if the user add localized constants in BUILD_CONSTANTS?
There are a sample: https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples/build_constants
You can modify the setup.py and add new localized constants to test.

**Comment by gbtami** [comment]
My PR changes BUILD_TIMESTAMP and SOURCE_TIMESTAMP format to show months as a zero-padded decimal numbers. As I see ConstantsModule.time_format is not used for anything else. Maybe I'm wrong.

If you want me to test a modified setup.py, just paste a modified setup.py here please. I think i don't understand your concerns.

**Comment by marcelotduarte** [comment]
#setup.py
#Please substitute the word TEST to some localized word
```
from cx_Freeze import setup, Executable

executables = [Executable("hello.py")]
options = {"build_exe": {"constants": ["A=7", 'B="hello=7"', C="TEST"]}}
setup(
    name="hello",
    version="0.1",
    description="Sample cx_Freeze script",
    options=options,
    executables=executables,
)

```
#hello.py
```

from datetime import datetime
import sys

print("Hello from cx_Freeze")
print(
    "The current date is %s\n"
    % datetime.today().strftime("%B %d, %Y %H:%M:%S")
)

print(f"Executable: {sys.executable!r}\n")

import BUILD_CONSTANTS

excludedVars = [
    "__builtins__",
    "__cached__",
    "__doc__",
    "__loader__",
    "__package__",
    "__spec__",
]

print("== variables in BUILD_CONSTANTS ==\n")
for var in dir(BUILD_CONSTANTS):
    if var in excludedVars:
        continue
    attr = BUILD_CONSTANTS.__getattribute__(var)
    print(f"{var} = {attr!r}")
```

**Comment by gbtami** [comment]
OK, I understand now. My PR solves only this very special issue triggered by` import Gtk`, while your PR fixes more wide range of similar possible issues as well. Confirmed.
```
tamas@DESKTOP-89DJHHI MINGW64 ~/cx/build/exe.mingw-3.8
$ ./hello.exe
Hello from cx_Freeze
The current date is April 10, 2021 00:15:30

Executable: 'C:\\msys64\\home\\tamas\\cx\\build\\exe.mingw-3.8\\hello.exe'

== variables in BUILD_CONSTANTS ==

A = 7
B = 'hello=7'
BUILD_COPYRIGHT = None
BUILD_HOST = 'DESKTOP-89DJHHI'
BUILD_RELEASE_STRING = '0.1'
BUILD_TIMESTAMP = 'April 10, 2021 00:08:58'
C = '▒prilis'
SOURCE_TIMESTAMP = 'April 09, 2021 22:14:48'
TCL_LIBRARY = 'lib/tkinter/tcl8.6'
TK_LIBRARY = 'lib/tkinter/tk8.6'
__file__ = 'C:/msys64/home/tamas/cx/build/exe.mingw-3.8/lib/library.zip/BUILD_CONSTANTS.pyc'
__name__ = 'BUILD_CONSTANTS'
```

**Comment by gbtami** [comment]
I think this issue is solved now, so I close it.
Thx a lot!

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
