### ISSUE TITLE
[Errno 2]

### ISSUE THREAD

**Issue by erkin98** [marcelotduarte/cx_Freeze#990]
```
error: [Errno 2] No such file or directory: 'C:\\ProgramData\\Miniconda3\\lib\\site-packages\\psutil-5.8.0-py3.8-win-amd64.egg\\psutil-5.8.0.dist-info\\LICENSE'
```
i get this error after when building executables my version is cx-Freeze-6.6.dev0
how can i handle this?

**Comment by marcelotduarte** [comment]
- remove the package psutil
- install package wheel
- install package psutil
- freeze

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.
