### ISSUE TITLE
Install packages programmatically after build

### ISSUE THREAD

**Issue by padmalcom** [marcelotduarte/cx_Freeze#992]
Hi I wrote a speech assistant that can be extended by skills. These skills come as python file and optionally a requirements.txt that I install programmatically using pip. In my anaconda environment it works well but when I build the application using cx_Freeze it cannot find the modules (even though the programmatic installation via pip is successful). Any ideas how I can do the dynamic installation and loading of modules?

**Comment by marcelotduarte** [comment]
I think this is possible, however, cx-freeze is basically an isolated python, that is, it does not search for these external packages. But if you create an init script[1], you can create something along these lines. Basically, the 'site module'[2] has no effect in isolated mode.

[1] https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/initscripts
[2] https://docs.python.org/3/library/site.html?highlight=site#module-site

**Comment by marcelotduarte** [comment]
cx_Freeze 6.6 has just been released.
Can I close this issue?

**Comment by marcelotduarte** [comment]
cx_Freeze 6.7 has just been released.
